### ISSUE TITLE
reduce log size

### ISSUE THREAD

**Issue by LeoHChen** [harmony-one/harmony#1127]
## Summary

We are using logs to do metrics analysis and reporting right now.  The size of the log file increases too fast.  One day's log take more than 300M of disk spaces. We should drastically reduce the log size.

## Current Design
 
Currently, 87.5% of logs are debugging log. Among the debug logs, 86% are used to report the public address of each signer who signed the blocks.

## Proposal
We will limit the log to "info" level by default.  "debug" level log can be used on certain nodes.

**Comment by hsienchiaolee** [comment]
In addition to reducing logs, how do you feel about outputting logs as JSON for easier metrics parsing? 

Also, for logging library, I've been using [ZeroLog](https://github.com/rs/zerolog) with great experience so far. Not only does it support JSON output and contextual chaining, it is also significantly [faster](https://github.com/rs/zerolog#benchmarks) than log15.

**Comment by hsienchiaolee** [comment]
In addition to reducing logs, how do you feel about adding rolling log files with GZIP compression for older files? [LumberJack](https://github.com/natefinch/lumberjack) seems to do this well and easy to integrate into current setup.

Additionally, I've been using [ZeroLog](https://github.com/rs/zerolog) for [faster performance](https://github.com/rs/zerolog#benchmarks) as compared to log15. This would be a much bigger change, but just thought I would bring it up for future consideration.

**Comment by LeoHChen** [comment]
that sounds like good suggestion.  we have too much logs right now.

**Comment by LeoHChen** [comment]
one challenge is we don't even have a uniform logger.

**Comment by hsienchiaolee** [comment]
We can break this down into smaller tasks then:
• Default to INFO log level
• Unify logger across application
• Rolling log files with GZIP compression
• Replace log15 with ZeroLog (optional)
