### ISSUE TITLE
[Feature] expose node metrics to local/grafana

### ISSUE THREAD

**Issue by LeoHChen** [harmony-one/harmony#1161]
# Problem/limitation At Hand

We have no metrics generated from Harmony node program, such like the network connectivity stats, consensus message stats, consensus time, etc. Right now, we rely on the offline log file analysis to generate the metrics.  They are not real-time and error prone, as we may change log file format etc.

**Which component?**

- [ ] consensus
- [ ] deploy script
- [ ] wallet
- [ ] explorer
- [ ] node script
- [ ] test automation
- [ ] demo app
- [x] others ...

# Proposed Solution

We need to design a metrics system, ideally exposing rpc/json api. So that the we can collect the metrics from remote server, as well as local monitoring.

https://github.com/prometheus/pushgateway

# Alternatives Considered

# Additional Context

**Comment by AndyBoWu** [comment]
This functionality will be implemented in this script: git@github.com:harmony-one/experiment-deploy.git/userdata-soldier-http.sh.
