### ISSUE TITLE
concurrent map write crash

### ISSUE THREAD

**Issue by LeoHChen** [harmony-one/harmony#1162]
fatal error: concurrent map read and map write

goroutine 5636214 [running]:
runtime.throw(0xff0dee, 0x21)
        /usr/local/go/src/runtime/panic.go:617 +0x72 fp=0xc00511d8a8 sp=0xc00511d878 pc=0x433732
runtime.mapaccess2_faststr(0xe787a0, 0xc000589f20, 0xc00650b3a0, 0x14, 0xc00650b3a0, 0x14)
        /usr/local/go/src/runtime/map_faststr.go:116 +0x4a4 fp=0xc00511d918 sp=0xc00511d8a8 pc=0x418e74
github.com/harmony-one/harmony/node.(*Node).CalculateResponse(0xc000055c00, 0xc002dc1900, 0xe9af00, 0xc006ad3b00, 0x12c4b60)
        /home/ec2-user/go/src/github.com/harmony-one/harmony/node/node_syncing.go:293 +0x1012 fp=0xc00511db10 sp=0xc00511d918 pc=0xc67632
github.com/harmony-one/harmony/api/service/syncing/downloader.(*Server).Query(0xc0001a81a0, 0x12dd760, 0xc00315c8d0, 0xc002dc1900, 0xc0001a81a0, 0xc00315c8d0, 0xc00511dba8)
        /home/ec2-user/go/src/github.com/harmony-one/harmony/api/service/syncing/downloader/server.go:28 +0x3d fp=0xc00511db48 sp=0xc00511db10 pc=0xb52b5d
github.com/harmony-one/harmony/api/service/syncing/downloader/proto._Downloader_Query_Handler(0xe9af00, 0xc0001a81a0, 0x12dd760, 0xc00315c8d0, 0xc006ad3b80, 0x0, 0x12dd760, 0xc00315c8d0, 0xc00818af60, 0x2a)
        /home/ec2-user/go/src/github.com/harmony-one/harmony/api/service/syncing/downloader/proto/downloader.pb.go:326 +0x23e fp=0xc00511dbb8 sp=0xc00511db48 pc=0xb5091e
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000370d80, 0x12e84e0, 0xc002793800, 0xc0000d7f00, 0xc0010f8210, 0x1c2cf50, 0x0, 0x0, 0x0)
        /home/ec2-user/go/pkg/mod/google.golang.org/grpc@v1.21.1/server.go:998 +0x4b5 fp=0xc00511de50 sp=0xc00511dbb8 pc=0xa33bc5
google.golang.org/grpc.(*Server).handleStream(0xc000370d80, 0x12e84e0, 0xc002793800, 0xc0000d7f00, 0x0)
        /home/ec2-user/go/pkg/mod/google.golang.org/grpc@v1.21.1/server.go:1278 +0xda6 fp=0xc00511df80 sp=0xc00511de50 pc=0xa37aa6
google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc005577aa0, 0xc000370d80, 0x12e84e0, 0xc002793800, 0xc0000d7f00)
        /home/ec2-user/go/pkg/mod/google.golang.org/grpc@v1.21.1/server.go:717 +0x9f fp=0xc00511dfb8 sp=0xc00511df80 pc=0xa4359f
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1337 +0x1 fp=0xc00511dfc0 sp=0xc00511dfb8 pc=0x460361
created by google.golang.org/grpc.(*Server).serveStreams.func1
        /home/ec2-user/go/pkg/mod/google.golang.org/grpc@v1.21.1/server.go:715 +0xa1

**Comment by chaosma** [comment]
PR: [1164](https://github.com/harmony-one/harmony/pull/1164)
