### ISSUE TITLE
Replace log15 with ZeroLog

### ISSUE THREAD

**Issue by hsienchiaolee** [harmony-one/harmony#1171]
## Summary

Throughout the development process, there had been a few logging libraries that has been introduced into the system. To be consistent across our codebase, we should standardize to use a single library.

## Current Design

Use log15 as logging library as well as default go `log`

## Problems

Slower performance with less ideal `struct` support.

## Proposal

While introducing yet another logging library is the the ideal solution to solve the too many logging libraries issue, I strongly believe that switching to [ZeroLog](https://github.com/rs/zerolog) would result in a much higher [performance gain](https://github.com/rs/zerolog#benchmarks). In addition, it  has additional convenient features:
• supports `struct` logging:
```
type FooFoo struct {
	Foo    Foo
	hidden string # private fields will not be printed
}

type Foo struct {
	Bar string
	Baz int
}

func main() {
	fooFoo := FooFoo{Foo: Foo{Bar: "bar", Baz: 1}, hidden: "will not print"}
	log.Info().Interface("FooFoo", fooFoo).Msg("I am a test")
	// Output: {"level":"info","FooFoo":{"Foo":{"Bar":"bar","Baz":1}},"time":"2019-06-26T15:48:24-07:00","message":"I am a test"}
}
```
• supports [CallerWithSkipFrameCount](https://godoc.org/github.com/rs/zerolog#Context.CallerWithSkipFrameCount), which we are currently using a [temporary hack](https://github.com/harmony-one/harmony/blob/master/internal/utils/logging.go#L13)

**Comment by LeoHChen** [comment]
https://github.com/harmony-one/harmony/pull/1264
