### ISSUE TITLE
Cmd wallet is slow

### ISSUE THREAD

**Issue by flicker-harmony** [harmony-one/harmony#1198]
Our current cmd wallet is slow. Specially the check balance function. Need to improve it. For now researched the harmony/cmd/client/wallet.go code.

**Comment by LeoHChen** [comment]
1. we can parallelize the query of 4 shards
2. we need to query multiple rpc end points at the same time and compare the results

**Comment by lazaruscrypto** [comment]
Upd: parallelizing by shard is added by RL, I'm adding multiple rpc end points now to return precise balance

**Comment by flicker-harmony** [comment]
Upd: parallelizing by shard is added by RL, working on querying multiple rpc end points now.
