### ISSUE TITLE
unable to start without shared object

### ISSUE THREAD

**Issue by jeee** [harmony-one/harmony#1259]
./wallet 
./wallet: error while loading shared libraries: libbls384_256.so: cannot open shared object file: No such file or directory

please supply the procedure to compile the binaries staticly so it runs without these dependencies

**Comment by eyooooo** [comment]
how did you fix this? @jeee

**Comment by jeee** [comment]
Don't recall and because binance f*&*$% up I am not involved anymore.

**Comment by adsorptionenthalpy** [comment]
Error: 
`/harmony: error while loading shared libraries: libbls384_256.so: cannot open shared object file: No such file or directory`
Solution:
Dynamic linker cannot find shared libraries
```
cd $(go env GOPATH)/src/github.com/harmony-one/harmony/bin 
cp *.so /usr/lib/ 
sudo /sbin/ldconfig -v
```
