### ISSUE TITLE
[Feature] enable throttled tx on mainnet configuration

### ISSUE THREAD

**Issue by LeoHChen** [harmony-one/harmony#1267]
# Problem/limitation At Hand

We need to enabled a throttled tx support in mainnet configuration.  Basically, if the tx amount is larger than say 10 ONE, we can return an error message. Also, we can look into how many small tx can be enabled per day.  This throttle feature is also related to txpool tx selection algorithm.

One design thinking is to design a filter module for the txpool transaction selection.  We can apply a chain of filter to filter out the tx from the txpool.

**Which component?**

- [ ] consensus
- [ ] deploy script
- [x] wallet
- [ ] explorer
- [ ] node script
- [ ] test automation
- [ ] demo app
- [x] transaction
- [ ] others ...

# Additional Context

Need to use wallet to test it.

**Comment by mikedoan** [comment]
1/ The coming transactions are first accepted in node here
node.go
func (node *Node) addPendingTransactions(newTxs types.Transactions) {

2/ another goroutine waits every 8 seconds to generate new block in node_newblock.go

selectedTxs = node.getTransactionsForNewBlock(MaxNumberOfTransactionsPerBlock, coinbase)
