### ISSUE TITLE
"My Genesis Account" and "cannot find your BLS key" messages should be logged, not just sent to stdout

### ISSUE THREAD

**Issue by nyetwurk** [harmony-one/harmony#1320]
There are several messages generated by harmony that are sent to stdout are not logged (or sent to stderr). This is problematic for monitoring, since monitoring should not have to monitor more than one information source, especially when attempting to detect harmony launch failures via monitoring.

**To Reproduce**
1. Run harmony normally
2. See the "My Genesis Account" message on stdout, and not in either `latest/validator-*.log` or `latest/zero-validator-*.log`

**Expected behavior**
The "My Genesis Account" message should appear in either `latest/validator-*.log` or `latest/zero-validator-*.log` as `INFO` level.

**To Reproduce**
1. Run harmony with a non FN BLS key
2. See the "cannot find your BLS" message on stdout, and not in either `latest` log or stderr

**Expected behavior**
The "cannot find your BLS" message should appear in either `latest/validator-*.log` or `latest/zero-validator-*.log` as `ERROR` level. Alternately, it should be sent to stderr as a severe error.

**Comment by nyetwurk** [comment]
There are several such Printfs in `cmd/harmony/main.go`
```./cmd/harmony/main.go: fmt.Printf("error when reading passphrase file: %v\n", err)
./cmd/harmony/main.go: fmt.Printf("cannot find your BLS key in the genesis/FN tables: %s\n", pubKey.SerializeToHexStr())
./cmd/harmony/main.go: fmt.Printf("My Genesis Account: %v\n", *genesisAccount)
./cmd/harmony/main.go: fmt.Printf("error when loading bls key, err :%v\n", err)
```
In general these should all go to logging as well, and if an error NOT to stdout but to stderr

**Comment by nyetwurk** [comment]
There are a quite a few fmt.Printfs() in general:
```
$ find . -name \*.go | xargs grep -l Printf
./api/proto/discovery/pingpong.go
./test/p2pchat/chat.go
./test/chain/main.go
./test/crypto/bls/main.go
./test/txgen/main.go
./cmd/hmyclient/main.go
./cmd/client/wallet/main.go
./cmd/client/txgen/main.go
./cmd/bootnode/main.go
./cmd/keygen/main.go
./cmd/harmony/main.go
./accounts/abi/abi_test.go
./core/vm/instructions_test.go
./core/vm/logger.go
./core/vm/stack.go
./core/vm/memory.go
./core/types/bloom9_test.go
./internal/genesis/genesis_test.go
./internal/utils/passphrase.go
```

**Comment by nyetwurk** [comment]
Note that in general, `stdout` is very noisy, but at least each item that is logged via the log interface has a prefix. The pure `fmt.Printf()` generally have NO prefix, so it is hard to categorize them in monitoring. Separating stdout/stderr is one temporary workaround.

**Comment by nyetwurk** [comment]
https://github.com/harmony-one/harmony/pull/1322

**Comment by LeoHChen** [comment]
Is it still open or shall we close it? @nyetwurk

**Comment by nyetwurk** [comment]
There are still a ton of Printf()s taht should be triaged as stderr/stdout or logged.
```
$ find . -name \*.go | xargs grep -l Printf
./test/p2pchat/chat.go
./test/one_address/main.go
./test/chain/main.go
./test/crypto/bls/main.go
./test/txgen/main.go
./cmd/hmyclient/main.go
./cmd/client/wallet/main.go
./cmd/client/wallet_stress_test/main.go
./cmd/client/txgen/main.go
./cmd/bootnode/main.go
./cmd/staking/root.go
./cmd/keygen/main.go
./cmd/harmony/main.go
./accounts/abi/abi_test.go
./core/vm/instructions_test.go
./core/vm/logger.go
./core/vm/stack.go
./core/vm/memory.go
./core/types/bloom9_test.go
./internal/genesis/genesis_test.go
./internal/utils/passphrase.go
```
