### ISSUE TITLE
Transaction problems

### ISSUE THREAD

**Issue by charleszqwang** [harmony-one/harmony#1328]
Transfers that occur soon after the nodes are setup will work. Transfers after a period of time (probably resharded) won't work. Specifically, the nonce of the account will not increment and the receiving account doesn't seem to be credited. 

Commit d57acb9 is the first commit with this bug. This commit solved a different bug that produced this when transferring 
![image](https://user-images.githubusercontent.com/39063357/62827746-6839a500-bb8a-11e9-917c-bf7441bf01fb.png)

Latest working commit is e41f398.

**Comment by rlan35** [comment]
Some of the code in this PR will fix this problem: https://github.com/harmony-one/harmony/pull/1348. Basically the local shard setup is wrong.
