### ISSUE TITLE
blockEpoch and blockNumber are sent as strings not integers in JSON logs so they cannot be used as metrics by filebeats

### ISSUE THREAD

**Issue by nyetwurk** [harmony-one/harmony#1333]
The "added block to chain" message in `core/blockchain.go` logs json as:
```
{"level":"info","port":"9000","ip":"104.155.69.66","blockHash":"0x3bd8288eeef3be5af7bf3bc81c7eee3df2a0cc033727498bfa5d393b8fd75a32","blockShard":3,"blockEpoch":"7","blockNumber":"454522","segmentIndex":0,"parentHash":"0xe8bd5baee3db49a3d9f1b75b2b56635fd295e17dfe6f4e8de7b5b0148f71aa89","caller":"/home/nyet/src/harmony-one/harmony/core/blockchain.go:1102","time":"2019-08-11T16:02:45Z","message":"added block to chain"}
```
Note that `blockShard` is an integer (`3`) with no quotes, but both `blockEpoch` and `blockNumber` come out as quoted strings (`"7"` and `"454522"`)

They should be logged as integers to ensure that applications such as filebeats can extract them as integers without logstash conversion or other filebeats processing.

**Comment by AndyBoWu** [comment]
I agree with you, the data type of those three fields should be int.

**Comment by nyetwurk** [comment]
#1334 and #1335 seem to fix ths
