### ISSUE TITLE
RPC Compatability for Trust Wallet

### ISSUE THREAD

**Issue by john-harmony** [harmony-one/harmony#1340]
**Overview**
As part of Trust Wallet support for Harmony we need to ensure RPC Compatibility

**Background - Reference Material**
Communication 
* via Telegram (Trust Wallet/Harmony)

Key Contact 
* Mykola - https://github.com/kolya182

Documents
* https://trustwallet.com/
* https://developer.trustwallet.com/
* Harmony document - https://docs.google.com/document/d/1KJmCNzocnyuA53LcSzbHW5QeLMI6x7mxfSZLgFoQyIQ/edit

Key Areas
* Harmony API
  * https://github.com/harmony-one/harmony/blob/master/hmy/backend.go
  * https://github.com/harmony-one/harmony/blob/master/hmy/api_backend.go
  * Sample Curl Request
```
johns-mbp:docs johnwhitton$ curl http://localhost:9500 -H "Content-Type: application/json" -X POST --data '{"jsonrpc":"2.0","method":"hmy_getBalance","params":["0x3aea49553Ce2E478f1c0c5ACC304a84F5F4d1f98", "latest"],"id":1}'
{"jsonrpc":"2.0","id":1,"result":"0x15af1d3b97541f000"}
```

Sub Tasks
- [x] Ensure RPC Compatibility - [Trust Wallet 28](https://github.com/TrustWallet/developer/issues/28)

**Acceptance Criteria**
- [ ]  query account / address balance
- [ ]  query sent / received transactions for an account / address
- [ ] query transaction details
- [ ] query fee / nonce for sending transaction
- [ ]  query blockchain status (block height)
- [x]  send raw transaction

**Comment by fxfactorial** [comment]
Done
