### ISSUE TITLE
Bootnode overload after 1000+ connections

### ISSUE THREAD

**Issue by xChickens** [harmony-one/harmony#1409]
On Pangaea, when launched with 1000 nodes, as soon as people begin connecting, number of connections in Recv-Q for the Pangaea port of the bootnode server begins increasing. Very soon after, the max number of TCP connections is reached (128/129). Causes a major problem as nodes can't ever reach consensus. Has occurred on 3 different relaunches.

After relaunch with 700 nodes, people are capable of reaching consensus. Really suspicious about maximum connections for bootnode.

**Comment by xChickens** [comment]
https://puu.sh/E8bOy.gif example of bootnode output

**Comment by LeoHChen** [comment]
This is fixed after EK raise the file descriptor per bootnode process to 4000.
