### ISSUE TITLE
[crash] node crash in cross shard branch

### ISSUE THREAD

**Issue by LeoHChen** [harmony-one/harmony#1410]
ERROR[08-23|04:56:56.559] cannot commit new block: cannot finalize block: cannot pay block reward: cannot set group sig mask bits: mismatching bitmap lengths port=9001 ip=127.0.0.1 funcName=github.com/harmony-one/harmony/node.(*Node).WaitForConsensusReadyv2.func1       funcFile=node_newblock.go funcLine=114 expectedBitmapLength=2 providedBitmapLength=1
ERROR[08-23|04:56:56.762] cannot commit new block: cannot finalize block: cannot pay block reward: cannot set group sig mask bits: mismatching bitmap lengths port=9001 ip=127.0.0.1 funcName=github.com/harmony-one/harmony/node.(*Node).WaitForConsensusReadyv2.func1       funcFile=node_newblock.go funcLine=114 expectedBitmapLength=2 providedBitmapLength=1
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xa8bec2]

goroutine 182 [running]:
github.com/harmony-one/harmony/core/types.(*Block).NumberU64(...)
   /home/leochen/go/src/github.com/harmony-one/harmony/core/types/block.go:387
github.com/harmony-one/harmony/core.IsEpochLastBlock(0x0, 0xc001048840)
   /home/leochen/go/src/github.com/harmony-one/harmony/core/blockchain.go:246 +0x22
github.com/harmony-one/harmony/node.(*Node).proposeShardStateWithoutBeaconSync(0xc000112c00, 0x0, 0x60, 0x60)
   /home/leochen/go/src/github.com/harmony-one/harmony/node/node_newblock.go:141 +0x2f
github.com/harmony-one/harmony/node.(*Node).WaitForConsensusReadyv2.func1(0xc000c426c0, 0xc000112c00, 0xc000c42660, 0xc00018f0e0)
   /home/leochen/go/src/github.com/harmony-one/harmony/node/node_newblock.go:118 +0x988
created by github.com/harmony-one/harmony/node.(*Node).WaitForConsensusReadyv2
   /home/leochen/go/src/github.com/harmony-one/harmony/node/node_newblock.go:27 +0x5d
ERROR[08-23|04:56:56.966] cannot commit new block: cannot finalize block: cannot pay block reward: cannot set group sig mask bits: mismatching bitmap lengths port=9001 ip=127.0.0.1 funcName=github.com/harmony-one/harmony/node.(*Node).WaitForConsensusReadyv2.func1       funcFile=node_newblock.go funcLine=114 expectedBitmapLength=2 providedBitmapLength=1

**Comment by rlan35** [comment]
https://github.com/harmony-one/harmony/pull/1413/commits/6a18b0401c0ff5668c0c9b873c9c9b0a10131461
