### ISSUE TITLE
[crash] cross-shard branch

### ISSUE THREAD

**Issue by LeoHChen** [harmony-one/harmony#1411]
ERROR[08-23|04:57:52.053] cannot commit new block: cannot finalize block: cannot pay block reward: cannot set group sig mask bits: mismatching bitmap lengths port=9001 ip=127.0.0.1 funcName=github.com/harmony-one/harmony/node.(*Node).WaitForConsensusReadyv2.func1       funcFile=node_newblock.go funcLine=114 expectedBitmapLength=2 providedBitmapLength=1
ERROR[08-23|04:57:52.099] cannot commit transactions: nonce too low port=9002 ip=127.0.0.1 funcName=github.com/harmony-one/harmony/node.(*Node).WaitForConsensusReadyv2.func1       funcFile=node_newblock.go funcLine=70
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xccc123]

goroutine 172 [running]:
github.com/harmony-one/harmony/node.(*Node).ProposeCrossLinkDataForBeaconchain(0xc000130c00, 0x1ee1248, 0x0, 0x0, 0xc000988da8, 0x1)
   /home/leochen/go/src/github.com/harmony-one/harmony/node/node_cross_shard.go:227 +0x423
github.com/harmony-one/harmony/node.(*Node).WaitForConsensusReadyv2.func1(0xc000090900, 0xc000130c00, 0xc000090720, 0xc0001a90e0)
   /home/leochen/go/src/github.com/harmony-one/harmony/node/node_newblock.go:96 +0x65e
created by github.com/harmony-one/harmony/node.(*Node).WaitForConsensusReadyv2
   /home/leochen/go/src/github.com/harmony-one/harmony/node/node_newblock.go:27 +0x5d
ERROR[08-23|04:57:52.221] cannot commit new block: cannot finalize block: cannot pay block reward: cannot set group sig mask bits: mismatching bitmap lengths port=9003 ip=127.0.0.1 funcName=github.com/harmony-one/harmony/node.(*Node).WaitForConsensusReadyv2.func1       funcFile=node_newblock.go funcLine=114 expectedBitmapLength=2 providedBitmapLength=1
ERROR[08-23|04:57:52.257] cannot commit new block: cannot finalize block: cannot pay block reward: cannot set group sig mask bits: mismatching bitmap lengths port=9001 ip=127.0.0.1 funcName=github.com/harmony-one/harmony/node.(*Node).WaitForConsensusReadyv2.func1       funcFile=node_newblock.go funcLine=114 expectedBitmapLength=2 providedBitmapLength=1

**Comment by rlan35** [comment]
https://github.com/harmony-one/harmony/pull/1413/commits/6a18b0401c0ff5668c0c9b873c9c9b0a10131461
