### ISSUE TITLE
grafana link in pagerduty

### ISSUE THREAD

**Issue by mikedoan** [harmony-one/harmony#1443]
Andy please fix the link of grafana in pagerduty. See the picture below

https://cdn.discordapp.com/attachments/595294633236496395/614938328705531924/Screen_Shot_2019-08-24_at_2.43.53_PM.png

**Comment by mindstyle85** [comment]
@AndyBoWu this can be closed?

**Comment by lijiang2087** [comment]
closing for now @AndyBoWu @mindstyle85
