### ISSUE TITLE
[Feature] use dnsaddress for bootnode

### ISSUE THREAD

**Issue by LeoHChen** [harmony-one/harmony#1448]
# Problem/limitation At Hand

We use IP address for bootnodes, which makes it hard to maintain the bootnodes in case of networking or ec2 issues.  I saw go-libp2p starts to have dnsaddr support.  We should explore this in our multiaddress for bootnodes.

**Which component?**

- [ ] consensus
- [ ] deploy script
- [ ] wallet
- [ ] explorer
- [ ] node script
- [ ] test automation
- [ ] demo app
- [x] networking

# Proposed Solution

See example here.
https://github.com/libp2p/go-libp2p/blob/a3c39ad62a5d215b78fd95947dc304784faa98f6/p2p/host/basic/basic_host_test.go#L408

**Comment by mindstyle85** [comment]
@LeoHChen this still open?
