### ISSUE TITLE
API-Method Tasks

### ISSUE THREAD

**Issue by charleszqwang** [harmony-one/harmony#1474]
**Overview**
The following API's were tested using the [postman betanet collection](https://www.getpostman.com/collections/d3a30f1499c59dac4f84)
Issues from this testing are documented below.

**Smart Contract Related Methods (needs further testing)**
- [ ] getCode
- [ ] getStorageAt
- [ ] call

**Explorer API's were inconsistent**
- [ ] explorer_getBlocks -needs pagination and error message when blocks aren't found
- [ ] explorer_tx -broken
- [ ] explorer_nodeCount -returns 2 instead of number of nodes
- [ ] explorer_shard -needs work
- [ ] netPeerCount -shard0 -> 170; shard1 -> 230 - betanet seems high
- [ ] Syncing - test functionality

**Additional Issues**
- [ ] getTransactionCount -needs to support onex format
- [ ] getLogs -doesn't work
- [ ] gasPrice -needs work
- [ ] netVersion - needs testing
- [ ] protocolVersion-needs testing

Filter Methods(needs testing)
- [ ] getFilterChanges
- [ ] newPendingTransactionFilter
- [ ] newBlockFilter
- [ ] newFilter

**Comment by john-harmony** [comment]
@flicker-harmony can you work with @charleszqwang and resolve the explorer API issues as a priority.

**Comment by mikedoan** [comment]
The followings API are not used - we should not add them in our docs.
```
 getFilterChanges
 newPendingTransactionFilter
 newBlockFilter
 newFilter
```

**Comment by john-harmony** [comment]
Have removed the above API's from the [developers guide](https://docs.harmony.one/sdk-wiki/)
