### ISSUE TITLE
Wallet Token Transfer Issue - shard 0 transaction send to all shards incorrectly

### ISSUE THREAD

**Issue by denniswon** [harmony-one/harmony#1486]
Bug reported by a customer on #development channel on Discord

**Describe the bug**
WALLET TRANSFER ISSUES
	•	"If you are sending from shard 0, and specifying shard 0, it will take all shards by default instead of just shard 0"

**To Reproduce**
s3 branch (cc: tested and reported by @mindstyle in #development Discord channel. cc: @LeoHChen)

**Expected behavior**
Only shard 0 should receive and handle the transfer

If this issue is already resolved in the recent s3 update, please close this issue. cc: @mikedoan @LeoHChen @xChickens

**Comment by xChickens** [comment]
I already posted this in #1458, it doesn't exist anymore.
