### ISSUE TITLE
Wallet Issue - account nonce displayed as 0 when balance is 0

### ISSUE THREAD

**Issue by denniswon** [harmony-one/harmony#1487]
Bug reported by a customer on #development channel on Discord

**Describe the bug**

WALLET TRANSFER ISSUES
•	Once you empty one shard of balance, even if it has some NONCEs before, it will put them back to 0, and show the correct number of NONCE since it has balance again.

**To Reproduce**
s3 branch (cc: tested and reported by @Mindstyle in #development Discord channel. cc: @LeoHChen)

**Expected behavior**
correct nonce handling

If this issue is already resolved in the recent s3 update, please close this issue. cc: @LeoHChen @rlan35

**Comment by xChickens** [comment]
I already posted this in #1458, it doesn't exist anymore.
