### ISSUE TITLE
Constantly receiving PING PeerInfo from old network (Pangaea)

### ISSUE THREAD

**Issue by xChickens** [harmony-one/harmony#1500]
{"level":"info","port":"9000","ip":"54.154.37.103","myEpoch":0,"myBlock":59,"myViewID":58,"phase":1,"mode":"Normal","validatorPubKey":"883fd0b374dd579376ff48fddad4aba970793bf7073e2723438654d57026e9c72e9b43e17da708f2f34ca133a7fc940f","NumReceivedSoFar":138,"PublicKeys":250,"caller":"/data/harmony-main/consensus/consensus_v2.go:370","time":"2019-09-03T11:12:33.610614119Z","message":"[OnPrepare] Received New Prepare Signature"}
{"level":"debug","port":"9000","ip":"54.154.37.103","Version":"Harmony (C) 2019. harmony, version v4118-pangaea-20190820.0-14-gb4c9a326 (jenkins@ 2019-08-22T09:16:33+0000)","BlsKey":"4425f1dc4a0505a06cec3d83d247885d38fcb72ab36e36168e0fff5ee4362ac46b356ccb850bbf3b23ba5496ceb4a783","IP":"95.179.162.91","Port":"9000","PeerID":"QmeYRzAjBNNa3N1RrZpBwY5XjkmHNiYarwGXX6RsSnKf3H","caller":"/data/harmony-main/node/node_handler.go:747","time":"2019-09-03T11:12:33.614663901Z","message":"[PING] PeerInfo"}
{"level":"info","port":"9000","ip":"54.154.37.103","myEpoch":0,"myBlock":59,"myViewID":58,"phase":1,"mode":"Normal","validatorPubKey":"5967c49a27230e5d09641f56a34709ba6bd69ba04d89cea0e12037017704f6dfdef1e51da5c1c464933ed59cd58df194","NumReceivedSoFar":139,"PublicKeys":250,"caller":"/data/harmony-main/consensus/consensus_v2.go:370","time":"2019-09-03T11:12:33.616448868Z","message":"[OnPrepare] Received New Prepare Signature"}
{"level":"info","port":"9000","ip":"54.154.37.103","myEpoch":0,"myBlock":59,"myViewID":58,"phase":1,"mode":"Normal","validatorPubKey":"66002b3b505b6ea30e9f60b7881c8b79ad5e6eb12bf83bd4a2124bb2e0255268508f9437d3f50494504f4b0c1795ee06","NumReceivedSoFar":140,"PublicKeys":250,"caller":"/data/harmony-main/consensus/consensus_v2.go:370","time":"2019-09-03T11:12:33.621876249Z","message":"[OnPrepare] Received New Prepare Signature"}
{"level":"info","port":"9000","ip":"54.154.37.103","myEpoch":0,"myBlock":59,"myViewID":58,"phase":1,"mode":"Normal","validatorPubKey":"110786216f4a9ffbbec91ef14fcb87a90ed201ca07ba8efdf7f096c454150b46f6f2a9dfb1141a6758da73c08a36cb03","NumReceivedSoFar":141,"PublicKeys":250,"caller":"/data/harmony-main/consensus/consensus_v2.go:370","time":"2019-09-03T11:12:33.627327394Z","message":"[OnPrepare] Received New Prepare Signature"}
{"level":"info","port":"9000","ip":"54.154.37.103","myEpoch":0,"myBlock":59,"myViewID":58,"phase":1,"mode":"Normal","validatorPubKey":"40017f60f5be4df97d7e006ffa738db20f2761fd68c3af2bb634200ce650fdc9b3ac5d4b5848fce6ca9336518aa3c194","NumReceivedSoFar":142,"PublicKeys":250,"caller":"/data/harmony-main/consensus/consensus_v2.go:370","time":"2019-09-03T11:12:33.632822517Z","message":"[OnPrepare] Received New Prepare Signature"}
{"level":"info","port":"9000","ip":"54.154.37.103","myEpoch":0,"myBlock":59,"myViewID":58,"phase":1,"mode":"Normal","validatorPubKey":"871e2a4fc9963a1123809afbc62324470f3a4a28a225cf4797abaddb0286944b3f8a0922763a347c7c3ba8f32f11d10d","NumReceivedSoFar":143,"PublicKeys":250,"caller":"/data/harmony-main/consensus/consensus_v2.go:370","time":"2019-09-03T11:12:33.638284203Z","message":"[OnPrepare] Received New Prepare Signature"}
{"level":"info","port":"9000","ip":"54.154.37.103","myEpoch":0,"myBlock":59,"myViewID":58,"phase":1,"mode":"Normal","validatorPubKey":"7c409973b51d60b7305f99ff4ae90bd8f71ebf7c869ad1b7ec2ad18c501b571a4c21ae78414f013918750969e5799c05","NumReceivedSoFar":144,"PublicKeys":250,"caller":"/data/harmony-main/consensus/consensus_v2.go:370","time":"2019-09-03T11:12:33.643739534Z","message":"[OnPrepare] Received New Prepare Signature"}
{"level":"info","port":"9000","ip":"54.154.37.103","myEpoch":0,"myBlock":59,"myViewID":58,"phase":1,"mode":"Normal","validatorPubKey":"735bb504e9e89f3bb5da914a4a479a8703e9495b65f908a1b7681dc3be7846bb51949ba5a805a0ecbce8d03a83bf0b11","NumReceivedSoFar":145,"PublicKeys":250,"caller":"/data/harmony-main/consensus/consensus_v2.go:370","time":"2019-09-03T11:12:33.649142533Z","message":"[OnPrepare] Received New Prepare Signature"}
{"level":"info","port":"9000","ip":"54.154.37.103","myEpoch":0,"myBlock":59,"myViewID":58,"phase":1,"mode":"Normal","validatorPubKey":"d04e2b46838ce0e66a0a60dcb8444c61a0980011ebce011b049a8c3f1213aae05b9d124cb07a2fbd5c0863dc8873a00f","NumReceivedSoFar":146,"PublicKeys":250,"caller":"/data/harmony-main/consensus/consensus_v2.go:370","time":"2019-09-03T11:12:33.654667546Z","message":"[OnPrepare] Received New Prepare Signature"}
{"level":"info","port":"9000","ip":"54.154.37.103","myEpoch":0,"myBlock":59,"myViewID":58,"phase":1,"mode":"Normal","validatorPubKey":"9999afa49b080316426c13be7f1d897ac4834f5a003f2d814b0e0b885e08780eebed6e2368ee931cfbfe9b120feed98a","NumReceivedSoFar":147,"PublicKeys":250,"caller":"/data/harmony-main/consensus/consensus_v2.go:370","time":"2019-09-03T11:12:33.660073982Z","message":"[OnPrepare] Received New Prepare Signature"}
{"level":"info","port":"9000","ip":"54.154.37.103","myEpoch":0,"myBlock":59,"myViewID":58,"phase":1,"mode":"Normal","validatorPubKey":"f050ba210b398ddebdc179f6b2e996c34ab0aeed7f3ea01b18cafe40215ddfb113459da1a0425b3d1ac2d0038513cd84","NumReceivedSoFar":148,"PublicKeys":250,"caller":"/data/harmony-main/consensus/consensus_v2.go:370","time":"2019-09-03T11:12:33.665680241Z","message":"[OnPrepare] Received New Prepare Signature"}
{"level":"info","port":"9000","ip":"54.154.37.103","myEpoch":0,"myBlock":59,"myViewID":58,"phase":1,"mode":"Normal","validatorPubKey":"92a5f4465458ddf16cf7c5e2b647bd07ec640a5f36a699ecb68d97742d2d4f25d400a2747dd9d183c9ecf4bb438beb94","NumReceivedSoFar":149,"PublicKeys":250,"caller":"/data/harmony-main/consensus/consensus_v2.go:370","time":"2019-09-03T11:12:33.671164321Z","message":"[OnPrepare] Received New Prepare Signature"}
{"level":"info","port":"9000","ip":"54.154.37.103","myEpoch":0,"myBlock":59,"myViewID":58,"phase":1,"mode":"Normal","validatorPubKey":"d3315aac34e1de513f4566d1cc27bc79c77436982d32fbac0e70f8f0b253439c9304cf88e9739ce5397b7bb15aa59380","NumReceivedSoFar":150,"PublicKeys":250,"caller":"/data/harmony-main/consensus/consensus_v2.go:370","time":"2019-09-03T11:12:33.676671417Z","message":"[OnPrepare] Received New Prepare Signature"}
{"level":"info","port":"9000","ip":"54.154.37.103","myEpoch":0,"myBlock":59,"myViewID":58,"phase":1,"mode":"Normal","validatorPubKey":"1db8a089c1db55a41a3a78939562c1c4a0369c62ee36dfa2bc6edae4382dd3911b33a48ee776b62e5519a3064d33190d","NumReceivedSoFar":151,"PublicKeys":250,"caller":"/data/harmony-main/consensus/consensus_v2.go:370","time":"2019-09-03T11:12:33.682092171Z","message":"[OnPrepare] Received New Prepare Signature"}
{"level":"info","port":"9000","ip":"54.154.37.103","myEpoch":0,"myBlock":59,"myViewID":58,"phase":1,"mode":"Normal","validatorPubKey":"e61b83cac4fa1ac5607a6a8d065d2df1a6226b370c8b034db1377e722ba34008369e5ae87319547ffa83f636c14cd306","NumReceivedSoFar":152,"PublicKeys":250,"caller":"/data/harmony-main/consensus/consensus_v2.go:370","time":"2019-09-03T11:12:33.687593Z","message":"[OnPrepare] Received New Prepare Signature"}
{"level":"info","port":"9000","ip":"54.154.37.103","myEpoch":0,"myBlock":59,"myViewID":58,"phase":1,"mode":"Normal","validatorPubKey":"57e569062fb29e3bca922dfa7e7771043ee5521a92b0165de6f2d816abe4efc7570af8d321ccc5bc474533a72cdda692","NumReceivedSoFar":153,"PublicKeys":250,"caller":"/data/harmony-main/consensus/consensus_v2.go:370","time":"2019-09-03T11:12:33.693180275Z","message":"[OnPrepare] Received New Prepare Signature"}
{"level":"info","port":"9000","ip":"54.154.37.103","myEpoch":0,"myBlock":59,"myViewID":58,"phase":1,"mode":"Normal","validatorPubKey":"4381ce5d560518f5a26deccbbb233ed2f7ce569b530ab684ca90cfa775bb7c1d17a5d4622b1421f62d9d40fb3d5edc06","NumReceivedSoFar":154,"PublicKeys":250,"caller":"/data/harmony-main/consensus/consensus_v2.go:370","time":"2019-09-03T11:12:33.698656278Z","message":"[OnPrepare] Received New Prepare Signature"}
{"level":"info","port":"9000","ip":"54.154.37.103","myEpoch":0,"myBlock":59,"myViewID":58,"phase":1,"mode":"Normal","validatorPubKey":"8b8134193c165e4eef967eebdb614ef30a1b7fef8c40e4c2812972fc3540bbc4b387be4ab12c9b53b0e5bbad48c6fc0c","NumReceivedSoFar":155,"PublicKeys":250,"caller":"/data/harmony-main/consensus/consensus_v2.go:370","time":"2019-09-03T11:12:33.704101248Z","message":"[OnPrepare] Received New Prepare Signature"}
{"level":"debug","port":"9000","ip":"54.154.37.103","Version":"Harmony (C) 2019. harmony, version v4118-pangaea-20190820.0-14-gb4c9a326 (jenkins@ 2019-08-22T09:16:33+0000)","BlsKey":"abf69133352ff83ac4caec8aa2c83cf54e5dadc4315bd820578fe002e20afbdf34a137966e2b894dbfae779002c96802","IP":"194.67.91.93","Port":"9000","PeerID":"QmbFLBRA6gTbpiPxs948Z85PRBPjs3UoQKgA3SnjmssN3j","caller":"/data/harmony-main/node/node_handler.go:747","time":"2019-09-03T11:12:33.707060384Z","message":"[PING] PeerInfo"}
{"level":"info","port":"9000","ip":"54.154.37.103","myEpoch":0,"myBlock":59,"myViewID":58,"phase":1,"mode":"Normal","validatorPubKey":"216ef88ec96ccc23dedcf8f3a3884f80ef775077848f43beae9491689e7caa047f65bd6d9dda42062072783ac2d40497","NumReceivedSoFar":156,"PublicKeys":250,"caller":"/data/harmony-main/consensus/consensus_v2.go:370","time":"2019-09-03T11:12:33.710013205Z","message":"[OnPrepare] Received New Prepare Signature"}
{"level":"info","port":"9000","ip":"54.154.37.103","myEpoch":0,"myBlock":59,"myViewID":58,"phase":1,"mode":"Normal","validatorPubKey":"a599261ebf77458c96b4d53675eb01a71af85dc45e99e1c44f09b774975d9cc8776f88ca720fbddece7114fb62960f18","NumReceivedSoFar":157,"PublicKeys":250,"caller":"/data/harmony-main/consensus/consensus_v2.go:370","time":"2019-09-03T11:12:33.715412933Z","message":"[OnPrepare] Received New Prepare Signature"}
{"level":"info","port":"9000","ip":"54.154.37.103","myEpoch":0,"myBlock":59,"myViewID":58,"phase":1,"mode":"Normal","validatorPubKey":"6d6522f600a84353f6b5b8ab1eaf83b48c7dfa6272cbba1e8d8ff00ebbe4b2ad7e2f4d9f18e8a78041f7938035bd7102","NumReceivedSoFar":158,"PublicKeys":250,"caller":"/data/harmony-main/consensus/consensus_v2.go:370","time":"2019-09-03T11:12:33.720830815Z","message":"[OnPrepare] Received New Prepare Signature"}
{"level":"info","port":"9000","ip":"54.154.37.103","myEpoch":0,"myBlock":59,"myViewID":58,"phase":1,"mode":"Normal","validatorPubKey":"423201c0e14da302af574b6dcd262f0544916c596f7e89ec9897748a3bbf6179c68de0c65bdb20a51c7cbea6a5dcd90a","NumReceivedSoFar":159,"PublicKeys":250,"caller":"/data/harmony-main/consensus/consensus_v2.go:370","time":"2019-09-03T11:12:33.726277014Z","message":"[OnPrepare] Received New Prepare Signature"}
{"level":"info","port":"9000","ip":"54.154.37.103","myEpoch":0,"myBlock":59,"myViewID":58,"phase":1,"mode":"Normal","validatorPubKey":"da4080cc0278f9438de46271199969e3d4db593cc2ca8f1975c2f8e40655e9375536d441e2e8b8b8b1f3c0df69a30d8d","NumReceivedSoFar":160,"PublicKeys":250,"caller":"/data/harmony-main/consensus/consensus_v2.go:370","time":"2019-09-03T11:12:33.731702056Z","message":"[OnPrepare] Received New Prepare Signature"}
{"level":"debug","port":"9000","ip":"54.154.37.103","Version":"Harmony (C) 2019. harmony, version v4118-pangaea-20190820.0-14-gb4c9a326 (jenkins@ 2019-08-22T09:16:33+0000)","BlsKey":"7b139908b6c968db7d2218191023e610a042125ef84cde0197da6b4f097f76d9d48730135e2c42f6f7287f62fc0f4217","IP":"51.158.176.151","Port":"9000","PeerID":"QmUghStAZgKa7pDJEQrcy8tQvfxbWZCPTmB84PC1UFyxGz","caller":"/data/harmony-main/node/node_handler.go:747","time":"2019-09-03T11:12:33.777947493Z","message":"[PING] PeerInfo"}
{"level":"debug","port":"9000","ip":"54.154.37.103","Version":"Harmony (C) 2019. harmony, version v4118-pangaea-20190820.0-14-gb4c9a326 (jenkins@ 2019-08-22T09:16:33+0000)","BlsKey":"14f762757672ef35e532d07606f68ceeff8daa318ad96354344da87e73c87502a263996c6859b7df8ea6d96dbead0918","IP":"116.203.219.146","Port":"9000","PeerID":"QmcymUqgqu2NDw4xyUPzL9nLGoHm533LdCouyVVJY49GV2","caller":"/data/harmony-main/node/node_handler.go:747","time":"2019-09-03T11:12:34.060903411Z","message":"[PING] PeerInfo"}
{"level":"debug","port":"9000","ip":"54.154.37.103","Version":"Harmony (C) 2019. harmony, version v4118-pangaea-20190820.0-14-gb4c9a326 (jenkins@ 2019-08-22T09:16:33+0000)","BlsKey":"618196d8796db3e0d7df3a2badfa302b8534cdb60cc8464b642d00153e2a1d05c0c8b56c03b17958ac77f527fa9aab18","IP":"157.230.35.213","Port":"9000","PeerID":"QmWGd9B5pp1rvWonAMcW2oGJLkDPtS9HWpy1awUa5hd1A3","caller":"/data/harmony-main/node/node_handler.go:747","time":"2019-09-03T11:12:34.082486078Z","message":"[PING] PeerInfo"}
{"level":"info","port":"9000","ip":"54.154.37.103","myEpoch":0,"myBlock":59,"myViewID":58,"phase":1,"mode":"Normal","validatorPubKey":"a39b56a9556a7c25931809e41359662ec796932b66614160d1dff03e9f71816bb5660a805225c1c3b9bbf8abc8dc8389","NumReceivedSoFar":161,"PublicKeys":250,"caller":"/data/harmony-main/consensus/consensus_v2.go:370","time":"2019-09-03T11:12:34.088005184Z","message":"[OnPrepare] Received New Prepare Signature"}
{"level":"debug","port":"9000","ip":"54.154.37.103","Version":"Harmony (C) 2019. harmony, version v4118-pangaea-20190820.0-14-gb4c9a326 (jenkins@ 2019-08-22T09:16:33+0000)","BlsKey":"58097664709ffb232d060e564d36e3688ec36a026f871b4e8f38a12366a64379e539527845fb27355e42a1fca7996095","IP":"45.76.39.199","Port":"9000","PeerID":"QmScbCsUhc4LPJsFxG3o1wF7UTtFkuvQBTNpqQsSwTk53H","caller":"/data/harmony-main/node/node_handler.go:747","time":"2019-09-03T11:12:34.096614856Z","message":"[PING] PeerInfo"}
{"level":"debug","port":"9000","ip":"54.154.37.103","Version":"Harmony (C) 2019. harmony, version v4118-pangaea-20190820.0-14-gb4c9a326 (jenkins@ 2019-08-22T09:16:33+0000)","BlsKey":"29bf0f8442ecdcb70136d143d765d0540ed266d879279b5edef97597d486473ce915dcad4daaa9e8052a595805b56700","IP":"35.196.165.120","Port":"9000","PeerID":"QmNgFPHZpcGuGU1AQcdSjhpJGTXpHAV4pkEfBqY8ERoCWP","caller":"/data/harmony-main/node/node_handler.go:747","time":"2019-09-03T11:12:34.156120683Z","message":"[PING] PeerInfo"}
{"level":"debug","port":"9000","ip":"54.154.37.103","Version":"Harmony (C) 2019. harmony, version v4118-pangaea-20190820.0-14-gb4c9a326 (jenkins@ 2019-08-22T09:16:33+0000)","BlsKey":"e91a90478108f975e9054c9d19dd11068e889e7d7b31623f785ccd00f0eeacd2a4f21ce2d978b031c0d34d8957884388","IP":"45.77.243.240","Port":"9000","PeerID":"QmP6UBZ3sEDFVnN5Dip33EVMbPgp6dAoGpF2K7cL2ou3SD","caller":"/data/harmony-main/node/node_handler.go:747","time":"2019-09-03T11:12:34.184808258Z","message":"[PING] PeerInfo"}
{"level":"debug","port":"9000","ip":"54.154.37.103","Version":"Harmony (C) 2019. harmony, version v4118-pangaea-20190820.0-14-gb4c9a326 (jenkins@ 2019-08-22T09:16:33+0000)","BlsKey":"f050ba210b398ddebdc179f6b2e996c34ab0aeed7f3ea01b18cafe40215ddfb113459da1a0425b3d1ac2d0038513cd84","IP":"104.154.121.195","Port":"9000","PeerID":"QmQVrxu3Pw9wNFMhQweAnPdDCDeQb1HCppGqNbBcFBqeKv","caller":"/data/harmony-main/node/node_handler.go:747","time":"2019-09-03T11:12:34.185400662Z","message":"[PING] PeerInfo"}
{"level":"info","port":"9000","ip":"54.154.37.103","myEpoch":0,"myBlock":59,"myViewID":58,"phase":1,"mode":"Normal","validatorPubKey":"d9653cb9f6344fadc584cd876c25289fe423e0b124e0d0478d8b14b769a9f8142712f37b85536f73f8b7efa723fd5d93","NumReceivedSoFar":162,"PublicKeys":250,"caller":"/data/harmony-main/consensus/consensus_v2.go:370","time":"2019-09-03T11:12:34.22269259Z","message":"[OnPrepare] Received New Prepare Signature"}
{"level":"debug","port":"9000","ip":"54.154.37.103","Version":"Harmony (C) 2019. harmony, version v4118-pangaea-20190820.0-14-gb4c9a326 (jenkins@ 2019-08-22T09:16:33+0000)","BlsKey":"6f91a6ce1135dff61a45daee0263f4df3ad3ca4a3be3f330bd567a1a1136d26709fb95ad812280044fbdcb0b5d23718b","IP":"35.193.227.40","Port":"9000","PeerID":"QmbA7ti6ebCrh36sWgwYqkUB95ZsmzHvcQ7Ad2KrUMBZhQ","caller":"/data/harmony-main/node/node_handler.go:747","time":"2019-09-03T11:12:34.286305487Z","message":"[PING] PeerInfo"}
{"level":"info","port":"9000","ip":"54.154.37.103","myEpoch":0,"myBlock":59,"myViewID":58,"phase":1,"mode":"Normal","validatorPubKey":"5f033aa9ba7e3c4b1e8ec8499d0d5fb1d9596346d3f8b0044014676c57413467ac2edc067328a27fc4af141dd1568503","NumReceivedSoFar":163,"PublicKeys":250,"caller":"/data/harmony-main/consensus/consensus_v2.go:370","time":"2019-09-03T11:12:34.340417567Z","message":"[OnPrepare] Received New Prepare Signature"}
{"level":"info","port":"9000","ip":"54.154.37.103","myEpoch":0,"myBlock":59,"myViewID":58,"phase":1,"mode":"Normal","validatorPubKey":"e1ce0f6db5dda1efc57edf38458a7182ed8351bf6e3fdaff5f9f91d04268e176845d4c820f24760fb16db828322f0817","NumReceivedSoFar":164,"PublicKeys":250,"caller":"/data/harmony-main/consensus/consensus_v2.go:370","time":"2019-09-03T11:12:34.359441182Z","message":"[OnPrepare] Received New Prepare Signature"}
{"level":"info","port":"9000","ip":"54.154.37.103","myEpoch":0,"myBlock":59,"myViewID":58,"phase":1,"mode":"Normal","validatorPubKey":"ed3ea6de20720d36787a73be68af546909053dc7caf08dc97ab28e3c5fc156c6e7fa30be752d500a800f0ef7c3703a0b","NumReceivedSoFar":165,"PublicKeys":250,"caller":"/data/harmony-main/consensus/consensus_v2.go:370","time":"2019-09-03T11:12:34.433153195Z","message":"[OnPrepare] Received New Prepare Signature"}
{"level":"debug","port":"9000","ip":"54.154.37.103","Version":"Harmony (C) 2019. harmony, version v4118-pangaea-20190820.0-14-gb4c9a326 (jenkins@ 2019-08-22T09:16:33+0000)","BlsKey":"53620cef074fc303b4b00abf552d2836b749d0e3f70ee0bd8105f824e55b079bf2dd1c54669000ed5166298d85fc5b13","IP":"152.115.95.206","Port":"9000","PeerID":"QmVcjLy9D3WQbbxuYncSbxhhJF7Z9J6dTqsaxVjddQjuDU","caller":"/data/harmony-main/node/node_handler.go:747","time":"2019-09-03T11:12:34.642608033Z","message":"[PING] PeerInfo"}
{"level":"debug","port":"9000","ip":"54.154.37.103","Version":"Harmony (C) 2019. harmony, version v4118-pangaea-20190820.0-14-gb4c9a326 (jenkins@ 2019-08-22T09:16:33+0000)","BlsKey":"556e079697dac6b56a065facaf35acb189c442f34eeb610e2af3c6e3b7e834dbeea9ae333748589ce5480e849d7cd899","IP":"217.160.65.29","Port":"9000","PeerID":"QmQcipdK2ViHrevVZ8z5SK7BTAhe8d2i1TCqruu2mFcrYQ","caller":"/data/harmony-main/node/node_handler.go:747","time":"2019-09-03T11:12:34.659346078Z","message":"[PING] PeerInfo"}
{"level":"debug","port":"9000","ip":"54.154.37.103","Version":"Harmony (C) 2019. harmony, version v4118-pangaea-20190820.0-14-gb4c9a326 (jenkins@ 2019-08-22T09:16:33+0000)","BlsKey":"be50ea63f9e7c4b861d0d6659ae800109c61d6e979eec8a5abbb297bfe6ad8895745949aeaf3e68a264270de6550418e","IP":"18.191.205.83","Port":"9000","PeerID":"QmcuspV7NaAv7usYcxVdHEojHGh1C53jzfD7HripmtGx9k","caller":"/data/harmony-main/node/node_handler.go:747","time":"2019-09-03T11:12:34.686969091Z","message":"[PING] PeerInfo"}
{"level":"debug","port":"9000","ip":"54.154.37.103","Version":"Harmony (C) 2019. harmony, version v4118-pangaea-20190820.0-14-gb4c9a326 (jenkins@ 2019-08-22T09:16:33+0000)","BlsKey":"43463f472782e4df2960a7d1ac5368f77b6be253b0fa357953d6999abd0606965e54f82f15f9f649be59591065f0f78b","IP":"35.222.204.250","Port":"9000","PeerID":"QmSXyZj6FbGjA7yoxW7jP5UtxNoMtCQtKdqgmzTaMc2PB5","caller":"/data/harmony-main/node/node_handler.go:747","time":"2019-09-03T11:12:34.699868997Z","message":"[PING] PeerInfo"}
{"level":"debug","port":"9000","ip":"54.154.37.103","Version":"Harmony (C) 2019. harmony, version v4118-pangaea-20190820.0-14-gb4c9a326 (jenkins@ 2019-08-22T09:16:33+0000)","BlsKey":"62f79d3f70a6e65b1cd858c23eb56a97e1eb23f7eade71933bd61830cca3ab8f6c8521ccdce770f21db38635da7c8b0f","IP":"34.90.33.24","Port":"9000","PeerID":"QmPBmQrZryot2mQ7nmZbR9kE7XSGvAkpoQVcVRfYJ7Vpna","caller":"/data/harmony-main/node/node_handler.go:747","time":"2019-09-03T11:12:34.736875192Z","message":"[PING] PeerInfo"}
{"level":"info","port":"9000","ip":"54.154.37.103","myEpoch":0,"myBlock":59,"myViewID":58,"phase":1,"mode":"Normal","validatorPubKey":"ea3d6267f5cce1187a12a4f0698a035a41a0f8c03cba12173d7cb16462c1491bd6506c70effa897290f81d6d814b8e0d","NumReceivedSoFar":166,"PublicKeys":250,"caller":"/data/harmony-main/consensus/consensus_v2.go:370","time":"2019-09-03T11:12:34.767771678Z","message":"[OnPrepare] Received New Prepare Signature"}
{"level":"debug","port":"9000","ip":"54.154.37.103","myEpoch":0,"myBlock":59,"myViewID":58,"phase":1,"mode":"Normal","validatorPubKey":"ea3d6267f5cce1187a12a4f0698a035a41a0f8c03cba12173d7cb16462c1491bd6506c70effa897290f81d6d814b8e0d","NumReceivedSoFar":166,"PublicKeys":250,"caller":"/data/harmony-main/consensus/consensus_v2.go:379","time":"2019-09-03T11:12:34.767832668Z","message":"[OnPrepare] Received Enough Prepare Signatures"}
{"level":"debug","port":"9000","ip":"54.154.37.103","myEpoch":0,"myBlock":59,"myViewID":58,"phase":1,"mode":"Normal","senderKey":"52167fc8450eb655ea1fb3de45ec7694fb3afea6778f6b4c46beb0ba9d4137334cd4b625e2f09bd55c37d72ba8697816","caller":"/data/harmony-main/consensus/consensus_service.go:73","time":"2019-09-03T11:12:34.767864653Z","message":"[populateMessageFields]"}
{"level":"debug","port":"9000","ip":"54.154.37.103","myEpoch":0,"myBlock":59,"myViewID":58,"phase":1,"mode":"Normal","blockHash":"sC\ufffdD\ufffd\ufffd\n\ufffd/,\ufffd\u0014\ufffd;\ufffde|\ufffd\ufffdV\ufffdP�\ufffd\ufffdk\ufffd\u0011\ufffd[\ufffd","blockNum":59,"caller":"/data/harmony-main/consensus/consensus_v2.go:411","time":"2019-09-03T11:12:34.771686691Z","message":"[OnPrepare] Sent Prepared Message!!"}
{"level":"debug","port":"9000","ip":"54.154.37.103","myEpoch":0,"myBlock":59,"myViewID":58,"phase":1,"mode":"Normal","From":"Prepare","To":"Commit","caller":"/data/harmony-main/consensus/consensus_v2.go:419","time":"2019-09-03T11:12:34.77172951Z","message":"[OnPrepare] Switching phase"}
{"level":"debug","port":"9000","ip":"54.154.37.103","myEpoch":0,"myBlock":59,"myViewID":58,"phase":2,"mode":"Normal","validatorPubKey":"8e14ffff484e165b85affc0adb5d8fc95885853677fec336a1db32f90a20b797b32fd6285b5df2442ce010fe54de9480","caller":"/data/harmony-main/consensus/consensus_v2.go:347","time":"2019-09-03T11:12:34.777884825Z","message":"[OnPrepare] Received Additional Prepare Message"}
{"level":"debug","port":"9000","ip":"54.154.37.103","Version":"Harmony (C) 2019. harmony, version v4118-pangaea-20190820.0-14-gb4c9a326 (jenkins@ 2019-08-22T09:16:33+0000)","BlsKey":"d9653cb9f6344fadc584cd876c25289fe423e0b124e0d0478d8b14b769a9f8142712f37b85536f73f8b7efa723fd5d93","IP":"45.32.47.88","Port":"9000","PeerID":"QmTp7xHmiHPo2JAGt49miUddS1qacStHtnkg8UhXdXPsgz","caller":"/data/harmony-main/node/node_handler.go:747","time":"2019-09-03T11:12:34.819942241Z","message":"[PING] PeerInfo"}
{"level":"debug","port":"9000","ip":"54.154.37.103","Version":"Harmony (C) 2019. harmony, version v4118-pangaea-20190820.0-14-gb4c9a326 (jenkins@ 2019-08-22T09:16:33+0000)","BlsKey":"474cf6544309e56b6821519457396fdb83b0e4b06c871092076da8908108733081c5082d072dc5e23e7ff877f4ddfe83","IP":"34.66.170.30","Port":"9000","PeerID":"QmQtnYZ3UXmcfUkAWtFdVns8HmD38BFBLKZ578h7tjHjgG","caller":"/data/harmony-main/node/node_handler.go:747","time":"2019-09-03T11:12:34.872716443Z","message":"[PING] PeerInfo"}
{"level":"debug","port":"9000","ip":"54.154.37.103","myEpoch":0,"myBlock":59,"myViewID":58,"phase":2,"mode":"Normal","validatorPubKey":"f81bafc3ecfd762455446cd623b94f0b6d0f6702a86818e97e4088745cd75fd1d655363992128050389284e5c43c3a07","caller":"/data/harmony-main/consensus/consensus_v2.go:347","time":"2019-09-03T11:12:34.880162999Z","message":"[OnPrepare] Received Additional Prepare Message"}
{"level":"debug","port":"9000","ip":"54.154.37.103","Version":"Harmony (C) 2019. harmony, version v4118-pangaea-20190820.0-14-gb4c9a326 (jenkins@ 2019-08-22T09:16:33+0000)","BlsKey":"18b24debb08cb124cf34778291d83b9c113f95af59e1b9ce630c3df4e873cd1e63236412866fa54f5a9abe86b68c688f","IP":"45.32.137.187","Port":"9000","PeerID":"QmRQvn79gkdjzv8FtVRRPQpsmxF8F7M55Kyq3GKWQG2FYq","caller":"/data/harmony-main/node/node_handler.go:747","time":"2019-09-03T11:12:34.9201627Z","message":"[PING] PeerInfo"}

**Comment by xChickens** [comment]
Can stop consensus from starting from the beginning
![image](https://user-images.githubusercontent.com/2402510/64214765-8e3f2600-ce66-11e9-90f4-0926713efba5.png)

**Comment by xChickens** [comment]
Sometimes shows this error:

{"level":"warn","port":"9000","ip":"18.223.3.99","error":"[SYNC] cannot find peers using DNS name \"s0.p.hmny.io\": lookup s0.p.hmny.io on 172.31.0.2:53: no such host","shard_id":0,"caller":"/data/harmony-main/node/node_syncing.go:210","time":"2019-09-03T12:44:13.598222204Z","message":"cannot retrieve syncing peers"}

**Comment by xChickens** [comment]
![image](https://user-images.githubusercontent.com/2402510/64214831-db22fc80-ce66-11e9-922f-0aee0b2b6a5f.png)

**Comment by LeoHChen** [comment]
this is mostly because of network bootnode was messed up with two network nodes connected to each other.  We have seen pangaea nodes connected to mainnet.  This issue is fixed by using different group discovery id in networkinfo service.
