### ISSUE TITLE
Pangaea transactions slow and inconsistent (20% succes rate)

### ISSUE THREAD

**Issue by JB273** [harmony-one/harmony#1509]
**Describe the bug**
Sending from shards is slow, but more important the succesrate seen for multiple users is ~20%, I've personally send out 300 transactions and only 45 of them were succesful.
Also when sending manually 1 in about 5 or 6 transactions actually show as succesful (nonce counter going up)

**To Reproduce**
1. run the wallet.sh -t transfer command multiple times on the Pangaea network

**Expected behavior**
All transactions should eventually be succesful

**Screenshots**
If needed I (or one of the Pangaea Tech Support Team) can deliver

**Environment (please complete the following information):**
 - OS: Linux (Ubuntu)

**Comment by JB273** [comment]
Seems to be a hard cap on transactions in function promoteExecutables on https://github.com/harmony-one/harmony/blob/s3/core/tx_pool.go, line 1047 is about spammers!
			// Only evict transactions from high rollers
			if !pool.locals.contains(addr) && uint64(list.Len()) > pool.config.AccountSlots {
				spammers.Push(addr, int64(list.Len()))
Can this be what we run into on Pangaea? 
Are scripters being punished for sending out to much TX in a certain timeframe?
Please inform us on this (Pangaea Tech Support Team on Telegram), thank you for your time and effort!

**Comment by denniswon** [comment]
https://github.com/harmony-one/harmony/pull/1552

**Comment by denniswon** [comment]
https://github.com/harmony-one/harmony/blob/s3/core/tx_pool.go is ethereum's transaction pool that is not integrated to Harmony protocol yet. For Harmony, currently the code resides in https://github.com/harmony-one/harmony/blob/master/node/node.go and https://github.com/harmony-one/harmony/blob/master/node/worker/worker.go
When transactions are "throttle", nonce should not go up (just tested on localnet and verified).
Current throttling logic on mainnet/pangea: 1. max amount per transaction: 1000 ONE: txn will fail 2. max number of transactions per account per hour: 100 transactions per hour per account 3. current wallet-imposed limit (non txn throttlng, but imposed by the protocol): Cannot make another transaction until one's last transaction gets processed (i.e. per each block, no account can make more than one transaction)
