### ISSUE TITLE
Wallet is able to attempt a transaction if --from flag not set

### ISSUE THREAD

**Issue by xChickens** [harmony-one/harmony#1520]
![image](https://user-images.githubusercontent.com/2402510/64385487-6200e200-cfeb-11e9-9ea7-69fbf8a46a28.png)
![image](https://user-images.githubusercontent.com/2402510/64386161-3c74d800-cfed-11e9-83b8-b7ed6b57c9b4.png)
Found by a Pangaea user who didn't know how to actually transfer correctly. Apparently whatever is happening with the from address, there's balance on the supposed address on mainnet, but not Pangaea. I have an inkling that it's using "one1qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqquzw7vz" but I'm not sure. It also shouldn't unlock properly, so there;s something really weird here...

**Comment by LeoHChen** [comment]
Can you check if it is still the issue?  If yes, please fix it.
