### ISSUE TITLE
Unthrottle Pangaea Transactions

### ISSUE THREAD

**Issue by xChickens** [harmony-one/harmony#1521]
Pangaea needs to be not throttled in order to experiment and see what happens. However people are apparently saying they're under the throttle limit and many transactions aren't going through. Which is also kind of a concern. #1509

**Comment by LeoHChen** [comment]
assigning to @denniswon

**Comment by denniswon** [comment]
https://github.com/harmony-one/harmony/blob/s3/core/tx_pool.go is ethereum's transaction pool that is not integrated to Harmony protocol yet. For Harmony, currently the code resides in https://github.com/harmony-one/harmony/blob/master/node/node.go and https://github.com/harmony-one/harmony/blob/master/node/worker/worker.go

When transactions are "throttle", nonce should not go up (just tested on localnet and verified).

Current throttling logic on mainnet/pangea:
1. max amount per transaction: 1000 ONE: txn will fail
2. max number of transactions per account per hour: 100 transactions per hour per account
3. current wallet-imposed limit (non txn throttlng, but imposed by the protocol): Cannot make another transaction until one's last transaction gets processed (i.e. per each block, no account can make more than one transaction)

**Comment by denniswon** [comment]
https://github.com/harmony-one/harmony/pull/1552
