### ISSUE TITLE
[Feature] create static harmony binary

### ISSUE THREAD

**Issue by LeoHChen** [harmony-one/harmony#1534]
# Problem/limitation At Hand

Right now, harmony binary has dependencies of a few .so files, which makes it harder to distribute and upgrade.  We should try to create a fully static linked binary of harmony node program.

Some clue can be found here.
https://github.com/herumi/bls/issues/22

**Which component?**

- [ ] consensus
- [ ] deploy script
- [ ] wallet
- [ ] explorer
- [ ] node script
- [ ] test automation
- [ ] demo app
- [x] node

**Comment by LeoHChen** [comment]
https://github.com/harmony-one/harmony/pull/1776

**Comment by LeoHChen** [comment]
For Amazon Linux AMI, you just need to do the following.

```
sudo yum install -y glibc-static
sudo yum install -y gmp-static
sudo yum install -y openssl-static
```

**Comment by yelllowsin** [comment]
@LeoHChen this issue can be closed, no? Statically linked binaries are working on main net, i am running node.sh with no issues it is been months using static binaries,
