### ISSUE TITLE
If binary upgrade fails, node.sh still thinks they are upgraded

### ISSUE THREAD

**Issue by xChickens** [harmony-one/harmony#1535]
```
[Report] bug in node.sh script @Leo | Harmony @Eugene Kim | Harmony 
What?
When harmony binary or lib* files are removed, the script seems not to detect (prints binaries not changed) it and when the script is launched again, it doesn't download them and launch of the node fails
Workaround that helped
Once I deleted md5sum.txt, node.sh script detected binaries change correctly and downloaded files and node launched successfully.
``` 
--- Lukas101

Basically if somehow the node.sh fails to upgrade the binaries, it will download the md5sum.txt, and will never upgrade the binaries unless md5sum is different, which would be the next upgrade. This could be due to running node.sh without sudo, and consequent runs with sudo will no longer attempt to upgrade the binaries.

**Comment by LeoHChen** [comment]
we have added -d, and -V option in node.sh.  Agree we still need further improvement on node.sh to make it more reliable.
