### ISSUE TITLE
BetaNet Explorer Nodes Aren't Returning Transactions or Blocks

### ISSUE THREAD

**Issue by charleszqwang** [harmony-one/harmony#1537]
This was tested through the Explorer RPC calls and the Explorer website.

Initially the nodes kept showing numPeersNow=0
![image](https://user-images.githubusercontent.com/39063357/64481186-a62ae880-d18b-11e9-88bf-12db9c6e3b0b.png)

We restarted the explorer nodes with commit #bed4b80, PR #1510, now the explorer nodes show a bitmap length mismatch error
![image](https://user-images.githubusercontent.com/39063357/64481196-f5711900-d18b-11e9-85e0-3b5334d9a95d.png)

**Comment by flicker-harmony** [comment]
There was a problem that discovery service was removed for explorer nodes in node service setup, which caused it to not receive any updates for blocks. Should be fixed with this pr https://github.com/harmony-one/harmony/pull/1510. Have you updated betanet with it?

**Comment by charleszqwang** [comment]
fixed by flicker

**Comment by charleszqwang** [comment]
u fixed it 👍
