### ISSUE TITLE
block errors in the log

### ISSUE THREAD

**Issue by LeoHChen** [harmony-one/harmony#1543]
**Describe the bug**

Foundational node runners reported the errors found in the log messages.

```
for the normal performing node, i have
any error: 1249
"Block content is not verified successfully" 565
"Block header is not verified successfully" 265
"DeadlineExceeded" 10
"invalid merkle root" 48
```

**Comment by rlan35** [comment]
Is there more context to this? This seems an aggregation of lots of separate errors. Hard to tackle without the context.

**Comment by LeoHChen** [comment]
It's reported by the FN runners on their logs.  Maybe we can grep some of our nodes to see if we see those errors as well.
