### ISSUE TITLE
[Feature] block nodes running older version in p2p network layer

### ISSUE THREAD

**Issue by LeoHChen** [harmony-one/harmony#1544]
# Problem/limitation At Hand

When nodes are not up to date, peers should drop the link with the outdated/bad peers.

**Which component?**

- [ ] consensus
- [ ] deploy script
- [ ] wallet
- [ ] explorer
- [ ] node script
- [ ] test automation
- [ ] demo app
- [x] p2p

# Proposed Solution

We are checking the version of the node anyway. If we see nodes are running lower version, we should just disconnect the nodes.  However, there is some risk of no being able to create a connected p2p network.  We need a better design and thinking on this one.

**Comment by gaia** [comment]
If

1. the notice to upgrade nodes is at least 10 days in advance
2. and the network upgrade requires that all nodes connected past the deadline run the new version (mandatory upgrade)
3. and the "breakage" causes adverse effects on the nodes that are up to date (we don't care about the outdated nodes)

then by all means, block the older versions.
consensus requires what % of nodes running the current version? as long as this %+1 upgraded, the network won't break. this is the case with any fork. if not enough nodes upgrade, maybe the node operators do not agree with the upgrade, but we haven't seen any contentious forks in harmony. and I doubt we will come across one.

PS: this is obviously valid for hard forks. but it is also valid for soft forks as long as #3 is true

**Comment by mindstyle85** [comment]
@LeoHChen not sure about this one, can we close it?

**Comment by LeoHChen** [comment]
This is still relevant, maybe used to validate the p2p message, not high priority though.

**Comment by LeoHChen** [comment]
no need to support this
