### ISSUE TITLE
Factor chain IDs out

### ISSUE THREAD

**Issue by harmony-ek** [harmony-one/harmony#1551]
> declaring as constants would look better, like in mainnet/testnet/localnet.go, etc.

_Originally posted by @denniswon in https://github.com/harmony-one/harmony/pull/1550#discussion_r322586159_

```go
var (
    MainnetChainID = big.NewInt(1)
    TestnetChainID = big.NewInt(2)
    TestChainID = big.NewInt(99)
    // ... and so on
)

**Comment by LeoHChen** [comment]
It's done already.
