### ISSUE TITLE
Explorer gets stuck on betanet and localnet

### ISSUE THREAD

**Issue by flicker-harmony** [harmony-one/harmony#1555]
**Describe the bug**

Explorer stops storing blocks after 14th block for localnet and 77th block on betanet even though nodes continue to reach consensus. It happened before new upgrades. It somehow manages to stay alright for mainnet, maybe due to the higher number of validators. 

**Log**
{"level":"info","port":"9099","ip":"127.0.0.1","caller":"/Users/flicker/go/src/github.com/harmony-one/harmony/internal/chain/sig.go:27","time":"2019-09-10T17:08:55.469039+03:00","message":"bitmap lol \ufffd\u0000"}
{"level":"info","port":"9099","ip":"127.0.0.1","caller":"/Users/flicker/go/src/github.com/harmony-one/harmony/internal/chain/sig.go:33","time":"2019-09-10T17:08:55.469766+03:00","message":"keys len 7"}
{"level":"info","port":"9099","ip":"127.0.0.1","caller":"/Users/flicker/go/src/github.com/harmony-one/harmony/internal/chain/sig.go:35","time":"2019-09-10T17:08:55.469788+03:00","message":"public key 65f55eb3052f9e9f632b2923be594ba77c55543f5c58ee1454b9cfd658d25e06373b0f7d42a19c84768139ea294f6204"}
{"level":"info","port":"9099","ip":"127.0.0.1","caller":"/Users/flicker/go/src/github.com/harmony-one/harmony/internal/chain/sig.go:35","time":"2019-09-10T17:08:55.469811+03:00","message":"public key 02c8ff0b88f313717bc3a627d2f8bb172ba3ad3bb9ba3ecb8eed4b7c878653d3d4faf769876c528b73f343967f74a917"}
{"level":"info","port":"9099","ip":"127.0.0.1","caller":"/Users/flicker/go/src/github.com/harmony-one/harmony/internal/chain/sig.go:35","time":"2019-09-10T17:08:55.469837+03:00","message":"public key e751ec995defe4931273aaebcb2cd14bf37e629c554a57d3f334c37881a34a6188a93e76113c55ef3481da23b7d7ab09"}
{"level":"info","port":"9099","ip":"127.0.0.1","caller":"/Users/flicker/go/src/github.com/harmony-one/harmony/internal/chain/sig.go:35","time":"2019-09-10T17:08:55.469854+03:00","message":"public key 2d61379e44a772e5757e27ee2b3874254f56073e6bd226eb8b160371cc3c18b8c4977bd3dcb71fd57dc62bf0e143fd08"}
{"level":"info","port":"9099","ip":"127.0.0.1","caller":"/Users/flicker/go/src/github.com/harmony-one/harmony/internal/chain/sig.go:35","time":"2019-09-10T17:08:55.469869+03:00","message":"public key 86dc2fdc2ceec18f6923b99fd86a68405c132e1005cf1df72dca75db0adfaeb53d201d66af37916d61f079f34f21fb96"}
{"level":"info","port":"9099","ip":"127.0.0.1","caller":"/Users/flicker/go/src/github.com/harmony-one/harmony/internal/chain/sig.go:35","time":"2019-09-10T17:08:55.469882+03:00","message":"public key 52ecce5f64db21cbe374c9268188f5d2cdd5bec1a3112276a350349860e35fb81f8cfe447a311e0550d961cf25cb988d"}
{"level":"info","port":"9099","ip":"127.0.0.1","caller":"/Users/flicker/go/src/github.com/harmony-one/harmony/internal/chain/sig.go:35","time":"2019-09-10T17:08:55.469902+03:00","message":"public key 678ec9670899bf6af85b877058bea4fc1301a5a3a376987e826e3ca150b80e3eaadffedad0fedfa111576fa76ded980c"}
{"level":"warn","port":"9099","ip":"127.0.0.1","error":"mismatching bitmap lengths, expectedBitmapLength=1, providedBitmapLength=2","caller":"/Users/flicker/go/src/github.com/harmony-one/harmony/internal/chain/sig.go:43","time":"2019-09-10T17:08:55.469932+03:00","message":"mask.SetMask failed"}
{"level":"info","port":"9099","ip":"127.0.0.1","caller":"/Users/flicker/go/src/github.com/harmony-one/harmony/node/node_explorer.go:45","time":"2019-09-10T17:08:55.469948+03:00","message":"mask.Bitmap \u0000"}
{"level":"error","port":"9099","ip":"127.0.0.1","need":5,"have":0,"caller":"/Users/flicker/go/src/github.com/harmony-one/harmony/node/node_explorer.go:51","time":"2019-09-10T17:08:55.469969+03:00","message":"[Explorer] not have enough signature"}

I have some more logging with tracing error back. Starts when trying to parse pbft message and extract consensus payload with validators bitmap. Then bitmap is converted to mask in sig.go. There it fails because bitmap has longer length than 8 keys (2 bytes, not 1 byte) and is actually looks strange, you can see it in logging. The value before error \u007f:
{"level":"info","port":"9099","ip":"127.0.0.1","caller":"/Users/flicker/go/src/github.com/harmony-one/harmony/node/node_explorer.go:45","time":"2019-09-10T17:08:47.254021+03:00","message":"mask.Bitmap \u007f"}. Little later this bitmap value becomes  \ufffd\u0001.

**Screenshots**
<img width="1280" alt="Screenshot 2019-09-10 at 18 06 00" src="https://user-images.githubusercontent.com/52401354/64625975-bba34b00-d3f5-11e9-9393-47e165f68cf4.png">
<img width="1282" alt="Screenshot 2019-09-10 at 18 06 22" src="https://user-images.githubusercontent.com/52401354/64625976-bba34b00-d3f5-11e9-8753-fa096b569d86.png">

**Environment (please complete the following information):**
 - OS: [Linux, MacOS]
- Go environment [ ```go env``` ]

**Additional context**

**Comment by john-harmony** [comment]
Closing as fixed as per @rlan35

**Comment by rlan35** [comment]
http://52.193.75.216:5000/blocks?from=77&to=82
