### ISSUE TITLE
NO valid public IP found

### ISSUE THREAD

**Issue by joesixpack** [harmony-one/harmony#1558]
**Describe the bug**
Continual failures to get the public IP.  Must restart node over and over until it takes.

**To Reproduce**
sudo ./node.sh -t -k /home/j/.hmy/keystore/[DELETED].key

**Expected behavior**
Works the first time to get the public IP.

**Screenshots**
![image](https://user-images.githubusercontent.com/23145642/64654403-04e7a080-d3de-11e9-8e71-c08e76e94dc6.png)

**Environment (please complete the following information):**
 - OS: Linux
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/j/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/j/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build016517383=/tmp/go-build -gno-record-gcc-switches"

**Additional context**
Maybe switch to a more reliable public IP provider or build in secondary redundancy?

**Comment by nyetwurk** [comment]
There is likely something else going on with your own ISP's firewall or NAT policy.

**Comment by nyetwurk** [comment]
What does `dig -4 @resolver1.opendns.com ANY myip.opendns.com +short` return on your machine?

**Comment by joesixpack** [comment]
I am using Cloudflare for DNS.

That command returns nothing, actually.

Traceroute to resolver1.opendns.com works fine.  However, the other:

![image](https://user-images.githubusercontent.com/23145642/64655196-58f38480-d3e0-11e9-875f-704869a8f392.png)

**Comment by nyetwurk** [comment]
That's not how dig works. It works by sending a NS request for myip.opendns.com to *only* resolver1.opendns.com

Something is intercepting ALL 53 packets and redirecting them so that the NS request is never making it to resolver1

**Comment by joesixpack** [comment]
Couldn't it working with OpenDNS or with Google's, so I just overrode the dig command with my own domain name.

**Comment by nyetwurk** [comment]
That isn't at all how the public ip discovery works, its unrelated to that entirely. That's a different topic.

**Comment by joesixpack** [comment]
Allright, to maintain purity, I've replaced the dig command with:

PUB_IP=$(curl -s http://whatismyip.akamai.com/)

There's other edge cases where dig for detecting the public IP simply does not work (or reliably if at all).  Possibly realted to NAT of DNS queries, though DMZ didn't make a difference.  The IP is simply not showing up when excluding +short (same happens with Google or Akamai).

![image](https://user-images.githubusercontent.com/23145642/64903582-9d954f00-d670-11e9-8e11-85188ce97613.png)

**Comment by nyetwurk** [comment]
You're best off just hardcoding your public ip if you know it. Ridiculous that your ISP is hijacking all DNS regardless of destination. SO rude. That's definitely a red flag.

**Comment by yelllowsin** [comment]
@joesixpack do you still have this issue? If not, can this one be closed? On Debian node.sh didn't detected my public ip, installing dnsutils did the trick for me. But since this issue is so old i imagine it must be fixed already.
