### ISSUE TITLE
Temp directories created in binaries location

### ISSUE THREAD

**Issue by josectheone** [harmony-one/harmony#1574]
When running transactions with wallet.sh several thousands of directories are created in the working directory with name [.dht-127.0.0.1-XXXXX] 

**To Reproduce**
run ./wallet.sh -t transfer .........

**Expected behavior**
This temp dirs/files should be in local temp folder to clean the mess

**Environment (please complete the following information):**
 - OS: [Linux, Google Cloud ubuntu VM]

![Screenshot (3)](https://user-images.githubusercontent.com/42573751/64740487-e95ac380-d4cb-11e9-996a-830a893d358e.png)

**Comment by josectheone** [comment]
I have currently 999 of this temp directories

**Comment by developery-nl** [comment]
> I have currently 999 of this temp directories

this means 1000 is max and oldest is removed?

**Comment by LeoHChen** [comment]
@charleszqwang , can you handle this ticket?  This is created by p2p for DHT persistence.

**Comment by LeoHChen** [comment]
fixed in https://github.com/harmony-one/harmony/issues/1574
