### ISSUE TITLE
[Estimate Gas] Finish the logic of estimating gas

### ISSUE THREAD

**Issue by mikedoan** [harmony-one/harmony#1576]
I have implemented the estimated gas but It's not working for Michael and i did not have time to look at it.

Created this issue for someone to pick it up. Basically given a transaction, the we define lower bound and upper bound of the gas for that transaction, then we do binary search and use EVM to try to process that transaction.

https://github.com/harmony-one/harmony/pull/1227

**Comment by LeoHChen** [comment]
there are many improvement can be done.  we can do some research on how to properly set the gas fee.  One thing I read about is to select a list of tx ranked by the gas fee, but use the low fee for every transaction.
