### ISSUE TITLE
Cross Shard Transactions - Balance updates incorrect

### ISSUE THREAD

**Issue by john-harmony** [harmony-one/harmony#1620]
**Describe the bug**
When transferring balances between two shards the balances appear to not be updated correctly when queried by hmy_getBalance and address.

**To Reproduce**
1. Send 800 from shard 0 to shard 3
2. Check Balances for new wallet (both shard 0 and shard 3 show 800)
3. Send 500 from new wallet to a different wallet on shard 0 (shard 0 shows 800, shard 3 shows 500)

Transaction Info
* [Send 800](https://explorer.harmony.one/#/tx/0x616c6e789ea0824553850cc4a3d77158b845118ff0f82ad8b5be6e3dfe5f2782)
* [Send 500](https://explorer.harmony.one/#/tx/0x4b4e053cfc9afe1f71c522dbf0ccba0b63d3cf630ab731187dc2512fbb6f7bf6)
* [Balance for Account](https://explorer.harmony.one/#/address/one1egk8zk52f39537m06rdc6nfldxg24k2swep03r)
* Apis
[get address shard 0](52.37.59.120:5000/address?id=one1egk8zk52f39537m06rdc6nfldxg24k2swep03r&tx_view=ALL&offset=1000)
```
{
    "id": "one1egk8zk52f39537m06rdc6nfldxg24k2swep03r",
    "balance": 800000000000000000000,
    "txs": [
        {
            "id": "0x616c6e789ea0824553850cc4a3d77158b845118ff0f82ad8b5be6e3dfe5f2782",
            "timestamp": "1568834589000",
            "from": "one1p3u89p0p4nxaj5sdcx0s20g5u9a3xjccjmfwuu",
            "to": "one1egk8zk52f39537m06rdc6nfldxg24k2swep03r",
            "value": 800000000000000000000,
            "bytes": "113",
            "data": "",
            "type": "RECEIVED"
        }
    ]
}
```
[Get Address Shard 3](52.193.75.216:5000/address?id=one1egk8zk52f39537m06rdc6nfldxg24k2swep03r&tx_view=ALL&offset=1000)
```
{
    "id": "one1egk8zk52f39537m06rdc6nfldxg24k2swep03r",
    "balance": 500000000000000000000,
    "txs": [
        {
            "id": "0x4b4e053cfc9afe1f71c522dbf0ccba0b63d3cf630ab731187dc2512fbb6f7bf6",
            "timestamp": "1568835237000",
            "from": "one1egk8zk52f39537m06rdc6nfldxg24k2swep03r",
            "to": "one1p3u89p0p4nxaj5sdcx0s20g5u9a3xjccjmfwuu",
            "value": 500000000000000000000,
            "bytes": "117",
            "data": "74657374",
            "type": "SENT"
        }
    ]
}
```
**Wallet appears correct**
```
[ec2-user@ip-172-31-12-93 ~]$ ./wallet.sh balances --address one1egk8zk52f39537m06rdc6nfldxg24k2swep03r
Using main profile for wallet
Account: one1egk8zk52f39537m06rdc6nfldxg24k2swep03r:
    Balance in Shard 0:  0.0000, nonce: 0
    Balance in Shard 1:  0.0000, nonce: 0
    Balance in Shard 2:  0.0000, nonce: 0
    Balance in Shard 3:  299.99872368, nonce: 1
[ec2-user@ip-172-31-12-93 ~]$
```

Get Balance Shard 0
```
{
    "jsonrpc": "2.0",
    "method": "hmy_getBalance",
    "params": [
        "one1egk8zk52f39537m06rdc6nfldxg24k2swep03r",
        "latest"
    ],
    "id": 1
}
```
Response
```
{
    "jsonrpc": "2.0",
    "id": 1,
    "result": "0x2b5e3af16b18800000"
}
```

Get Balance Shard 3
```
{
    "jsonrpc": "2.0",
    "method": "hmy_getBalance",
    "params": [
        "one1egk8zk52f39537m06rdc6nfldxg24k2swep03r",
        "latest"
    ],
    "id": 1
}
```
Response
```
{
    "jsonrpc": "2.0",
    "id": 1,
    "result": "0x10435191b9c0f7c000"
}
```

**Expected behavior**
Shard 3 should be left with a balance of 300

**Environment (please complete the following information):**
- Mainnet

**Comment by benjaminbfong** [comment]
one1kmmplqq3e8jvn2x4fwau8djnymqj7sawxyfea4

**Comment by benjaminbfong** [comment]
Issue confirmed in testnet.  Sending cross-shard transaction (80) shows balance sent in both shards of recipient.  Returning tokens (50) only decreases the correct recipient shard's balance. 
Accounts used: 
one18t4yj4fuutj83uwqckkvxp9gfa0568uc48ggj7
one1kmmplqq3e8jvn2x4fwau8djnymqj7sawxyfea4
Tx hashes:
0x02969cb5253b8a0fe8b0a2a0ef68a0ec167e66c5e79366259de69dd0e105c53d
0x777302729c24490bc7f45274addaf4b36587e89f180065c0597b29f5b95eea0c

**Comment by rlan35** [comment]
It's fixed by this: https://github.com/harmony-one/harmony/pull/1621/commits/396fd319b4b289c53eda6c9ca48ce84991b59080
