### ISSUE TITLE
Explorer search for transaction not working

### ISSUE THREAD

**Issue by rlan35** [harmony-one/harmony#1630]
this txn was submitted 0xcff4a3a6fd4eb34b9a7e48e3eca0c8c899de71a1ea21a126cc1048e65b332a72 to testnet and it's not searchable in testnet explorer: https://explorer.beta.harmony.one/#/

Reproduce it by sending another transaction and search for it in explorer.

**Comment by john-harmony** [comment]
Here are two new transactions
- 0xfdfb4b514be1018a5a038d8f9c8e73d29a708c93ea2edf869893b92b91d227d7 (cross shard)
- 0xd73804146dbefb94edf5b54baaee8d9a57734b5c16ded05cbba3289435d40ea5 (same shard)

**Comment by john-harmony** [comment]
Latest testnet transaction
https://explorer.beta.harmony.one/#/tx/0x1bb3cadb2031e5ce987b0c557abe134986b9834963dd0d54f75a9c7d966606ce
