### ISSUE TITLE
Refactor and Consolidation of API's

### ISSUE THREAD

**Issue by john-harmony** [harmony-one/harmony#1633]
## Summary

Harmony currently has API's located in many areas. This ticket is to review and align Harmony's API's to best practices.

## Current Design
**API's are currently held in multiple locations including**
- [blockchain.go](https://github.com/harmony-one/harmony/blob/master/internal/hmyapi/blockchain.go)
- [api_backend.go](https://github.com/harmony-one/harmony/blob/master/hmy/api_backend.go)
- [explorer](https://github.com/harmony-one/harmony/blob/master/api/service/explorer/service.go)

**API's are referenced by** 
- Harmony Javascript SDK [here](https://github.com/harmony-one/sdk/blob/master/packages/harmony-network/src/rpcMethod/rpc.ts)
- Harmony CLI [here](https://github.com/harmony-one/go-sdk/blob/master/pkg/rpc/methods.go)

## Problems

- Code is fragmented
- Code is inconsistent
- Code is/was exposed on different ports

## Proposal

- Consolidate API's into functional/technical areas
- Ensure all API's accept one address format 
- Ensure all API's return address in one address format
- Ensure all API's are exposed on port 9500 (remove 5000)

Sample one address `one18t4yj4fuutj83uwqckkvxp9gfa0568uc48ggj7`

## Acceptance criteria

- [ ] Code has been consolidated
- [ ] API's have test included in [Postman](https://www.getpostman.com/collections/d3a30f1499c59dac4f84)
- [ ] API test suite is included in [Jenkins](https://github.com/harmony-one/jenkins)
- [ ] API's are [documented](https://docs.harmony.one/home/api-developers-guide/overview/methods)
- [ ] Testnet Migration and Validation complete
- [ ] Mainnet Migration and validation complete

**Comment by Daniel-VDM** [comment]
As request by John, the following do not use the one1 address:

`hmy_getTransactionReceipt` has a 0x address in the 'from' and 'to' address of the result.
`hmy_getTransactionByHash` has a 0x address in the 'from' and 'to' address of the result.
`hmy_getTransactionByBlockNumberAndIndex` has a 0x address in the 'from' and 'to' address of the result.
`hmy_getTransactionByBlockHashAndIndex` has a 0x address in the 'from' and 'to' address of the result.
`hmy_getCSReceiptByHash` has a 0x address in the 'from' and 'to' address of the result.
`hmy_resendCx` has a 0x address in the 'from' and 'to' address of the result.

Below are some SS of the first 3, the rest are similar:

<img width="752" alt="hmy_getTransactionReceipt" src="https://user-images.githubusercontent.com/31291913/65464456-ae7f5680-de0e-11e9-8d50-761d707b8b3d.png">

<img width="758" alt="hmy_getTransactionByHash" src="https://user-images.githubusercontent.com/31291913/65464481-bd660900-de0e-11e9-85dd-c9ceee625c1b.png">

<img width="752" alt="hmy_getTransactionByBlockNumberAndIndex" src="https://user-images.githubusercontent.com/31291913/65464496-c8209e00-de0e-11e9-9d46-b94bf170c8cb.png">

**Comment by LeoHChen** [comment]
still valid, assigning to @Daniel-VDM . he owns the RPC now.

**Comment by LeoHChen** [comment]
rpc refactoring has been done.
