### ISSUE TITLE
previous leaders can't reach consensus after rolling update

### ISSUE THREAD

**Issue by LeoHChen** [harmony-one/harmony#1652]
**Describe the bug**

We just did the rolling update from v1-20190917.0 to v1-20190924.0.

The previous leaders on 1,2,3 can't reach consensus after the rolling update.

The nodes are:

54.92.81.196
54.249.98.66
34.221.150.79

**Comment by chaosma** [comment]
fixed in pr: [1654](https://github.com/harmony-one/harmony/pull/1654)
