### ISSUE TITLE
EPoS calculation based on stake info: rank, calculate effective stake etc.

### ISSUE THREAD

**Issue by rlan35** [harmony-one/harmony#1660]

**Comment by grassr00t** [comment]
This issue is related to block reward, should go to @denniswon, I think.

**Comment by LeoHChen** [comment]
better goes to dennis as it is related to block rewards.

**Comment by rlan35** [comment]
This is preparation work for many other stuff (reward, slashing, sharding etc.) better be worked on by Edgar first.

**Comment by mindstyle85** [comment]
@rlan35 this can be closed?
