### ISSUE TITLE
Ledger staking integration

### ISSUE THREAD

**Issue by rlan35** [harmony-one/harmony#1667]

**Comment by coolcottontail** [comment]
any further information regarding this issue?

**Comment by rlan35** [comment]
This is a open project. You should do some research on this. But Cosmos definitely support delegation using ledger: https://app.lunie.io/ledger and many other projects: https://www.google.com/search?q=ledger+staking&oq=ledger+staking&aqs=chrome..69i57j35i39j0j69i60j69i61j69i60.2656j0j7&sourceid=chrome&ie=UTF-8

**Comment by yelllowsin** [comment]
@rlan35 @coolcottontail I would love to see staking integrated into Ledger Live later on. Having staking via Staking Dashboard is nice, but having it on Ledger Live is even better. Something to work on afterwards, if not in the plans already?

https://support.ledger.com/hc/en-us/articles/360010653260-Earn-Tezos-staking-rewards

**Comment by rlan35** [comment]
@coolcottontail @mikedoan can we close this now？
