### ISSUE TITLE
Transactions with a lot of embedded Base64 data takes a long time to load on the Explorer Web UI

### ISSUE THREAD

**Issue by SebastianJ** [harmony-one/harmony#1676]
**Describe the bug**
Transactions that are created using a lot of embedded base64 data will take a long time to load on the web explorer interface. The page will take several seconds to load and the CPU will get massively pegged when trying to load the transaction.

**To Reproduce**

[Reproducing the transaction](https://gist.github.com/SebastianJ/50c1405109d64651e13958d82eae112c)

[Example on Pangaea's explorer of such a transaction](https://explorer.pangaea.harmony.one/#/tx/0x9dc7387532089aefbbb2f6762c9ed731ee051aeb7a35e5a22c94c631ff4a4bf2)

That's a transaction I created for Pangaea, I assume the same thing will happen to the Mainnet explorer as soon as someone starts sending transactions with a lot of base64 embedded data.

**Expected behavior**
The transaction page should load without freezing up the UI, not take several seconds to load and without pegging the CPU like crazy.

**Screenshots**
Loading the transaction page:
![Loading](https://i.ibb.co/yq6VVNH/Screenshot-2019-09-27-at-13-16-07.png)

CPU usage while loading the transaction page:
![CPU Usage when loading the page/transaction](https://i.ibb.co/Y8vDCg3/Screenshot-2019-09-27-at-13-16-22.png)

When the transaction has finally loaded (after several seconds and pegging the CPU like crazy):
![Loaded transaction](https://i.ibb.co/hy3R888/Screenshot-2019-09-27-at-13-35-12.png)

**Environment (please complete the following information):**
 - OS: [MacOS]
- Browser: Safari, Chrome, Firefox

**Comment by yelllowsin** [comment]
@SebastianJ performed a TX with a huge amount of data on main net and it seems the issue doesn't happen anymore, no hang: https://explorer.harmony.one/#/tx/0xe1072ab1631501253ff58e21bfa2e85795fab475320bdbd7a96f856f56fd180c

Though...i noticed the explorer layout cuts part of the data of the tx when presenting to the user. If you use Chrome Dev tools to check you will see the whole tx data is on HTML, it was just cut out from the view. Maybe close this one and open a new one with this new case?

![image](https://user-images.githubusercontent.com/7217595/77456828-95b22680-6dda-11ea-8c9c-ca288aa69736.png)
