### ISSUE TITLE
API's unable to retrieve information for deployed Contracts

### ISSUE THREAD

**Issue by john-harmony** [harmony-one/harmony#1678]
**Issue**
On testnet when deploying a contract some API's do not work.

**To Reproduce**
1. Deploy a contract to testnet
2. Try and retrieve the information

**Expected behavior**
API's should return the associated data.

**Sample Data**
The puzzle contract was deployed in testnet and the following apis had issues.
- Contract - `0x80000b2fc774b4d32acc33f75bada54ddeb174c3`
- Transaction Hash `0x9666a782b40e23851160e28a0046f7822d9b154d03702de3d7dd0d0d73846630`
- Shard 0 
- BlockHash - `0xcbd7fd80b288893c3d712a53b0ef95611aad12d0dd70bcdddb498f6991af3cbf`
- BlockNumber - `0x284d4`

**Result from hmy_getTransactionReceipt**
```
{
    "jsonrpc": "2.0",
    "id": 1,
    "result": {
        "blockHash": "0xcbd7fd80b288893c3d712a53b0ef95611aad12d0dd70bcdddb498f6991af3cbf",
        "blockNumber": "0x284d4",
        "contractAddress": "0x80000b2fc774b4d32acc33f75bada54ddeb174c3",
        "cumulativeGasUsed": "0x3fcd1",
        "from": "0x3aea49553ce2e478f1c0c5acc304a84f5f4d1f98",
        "gasUsed": "0x3fcd1",
        "logs": [],
        "logsBloom": "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
        "shardID": 0,
        "status": "0x1",
        "to": null,
        "transactionHash": "0x9666a782b40e23851160e28a0046f7822d9b154d03702de3d7dd0d0d73846630",
        "transactionIndex": "0x0"
    }
}
```

**API's that need to be fixed**
- [x] hmy_getTransactionByHash - Currently not returning a result
- [x] hmy_getTransactionReceipt - Ensure data is correct e.g. transactionIndex
- [x] hmy_getBlockByNumber - Currently not returning a result
- [x] hmy_getBlockByHash - Ensure transactions are shown in block

**Acceptance criteria**
- [x] Tested Sucessfully Locally
- [x] Data can be retrieved on Testnet
- [x] Truffle deploy of new contracts work

**Comment by flicker-harmony** [comment]
hmy_getTransactionReceipt had 0x addresses - it's bad, but it was manually set in the method without going through hmy types marshalling and I didn't see that first time, I've changed that. With simple transactions everything is shown by hmy_getBlockByHash and hmy_getBlockByNumber, but in getBlockByHash the flag incTx was set to false, which is why they were not shown in block, I changed that to true and added fullTx flag (show full tx info in block) into consideration.
<img width="1370" alt="Screenshot 2019-09-28 at 18 24 26" src="https://user-images.githubusercontent.com/52401354/65818885-90569380-e21e-11e9-95e3-906cec989bd2.png">
<img width="1364" alt="Screenshot 2019-09-28 at 18 24 35" src="https://user-images.githubusercontent.com/52401354/65818886-90569380-e21e-11e9-8732-4bf7a89b0121.png">
<img width="1375" alt="Screenshot 2019-09-28 at 18 24 43" src="https://user-images.githubusercontent.com/52401354/65818887-90ef2a00-e21e-11e9-9f6a-41721ec5f78f.png">
<img width="1363" alt="Screenshot 2019-09-28 at 18 24 56" src="https://user-images.githubusercontent.com/52401354/65818888-90ef2a00-e21e-11e9-9ebc-7bd9344f5fb4.png">

**Comment by flicker-harmony** [comment]
hmy_getTransactionReceipt data seems correct, but I have a hard time generating more than 1 tx in a single block, wallet doesn't allow to make 2 txs at the same time and time of block generation passes.

**Comment by flicker-harmony** [comment]
I was able to replicate case when tx occured and address nonce is incremented, but tx is not shown in any api method, maybe nonce can be incremented even in case if tx is not successful, but
 is it okay?
<img width="1680" alt="Screenshot 2019-09-28 at 18 56 19" src="https://user-images.githubusercontent.com/52401354/65819177-38219080-e222-11e9-9f1c-8bc33af12cef.png">
<img width="1366" alt="Screenshot 2019-09-28 at 19 00 09" src="https://user-images.githubusercontent.com/52401354/65819178-38219080-e222-11e9-8928-35745d0ce944.png">

**Comment by john-harmony** [comment]
@flicker-harmony 
Testing locally seems to have fixed the initial issue.
However I am now seeing this message when deploying a contract
```
Johns-MacBook-Pro:puzzle johnwhitton$ truffle migrate --network development --reset

Compiling your contracts...
===========================
> Everything is up to date, there is nothing to compile.



Migrations dry-run (simulation)
===============================
> Network name:    'development-fork'
> Network id:      2
> Block gas limit: 0xe4a1b


1_initial_migration.js
======================

   Deploying 'Migrations'
   ----------------------
   > block number:        153
   > block timestamp:     1569817609
   > account:             0x3aea49553Ce2E478f1c0c5ACC304a84F5F4d1f98
   > balance:             4.999246013
   > gas used:            246329
   > gas price:           2 gwei
   > value sent:          0 ETH
   > total cost:          0.000492658 ETH

   -------------------------------------
   > Total cost:         0.000492658 ETH


2_puzzle.js
===========

   Deploying 'Puzzle'
   ------------------
   > block number:        155
   > block timestamp:     1569817609
   > account:             0x3aea49553Ce2E478f1c0c5ACC304a84F5F4d1f98
   > balance:             4.997719017
   > gas used:            736475
   > gas price:           2 gwei
   > value sent:          0 ETH
   > total cost:          0.00147295 ETH

   -------------------------------------
   > Total cost:          0.00147295 ETH


Summary
=======
> Total deployments:   2
> Final cost:          0.001965608 ETH





Starting migrations...
======================
> Network name:    'development'
> Network id:      2
> Block gas limit: 0xe4a1b


1_initial_migration.js
======================

   Deploying 'Migrations'
   ----------------------
   > transaction hash:    0x2b559be387aeece21baf4c254c57c01e1aad24f88b332930d246ff0954f2cf95
   ⠹ Blocks: 0            Seconds: 0

Error: Error: Error: Given address "one18t4yj4fuutj83uwqckkvxp9gfa0568uc48ggj7" is not a valid Ethereum address.
    at Object.run (/Users/johnwhitton/.nvm/versions/node/v12.10.0/lib/node_modules/truffle/build/webpack:/packages/migrate/index.js:96:1)
Truffle v5.0.36 (core: 5.0.36)
Node v12.10.0
```

**Comment by flicker-harmony** [comment]
We will fix this by making special contract tx case in methods - return 0x from address if to address in receipt or tx is nil.

**Comment by LeoHChen** [comment]
assigning to @Daniel-VDM to triage and check.

**Comment by LeoHChen** [comment]
old issue
