### ISSUE TITLE
incorrect # of txs in explorer

### ISSUE THREAD

**Issue by mikedoan** [harmony-one/harmony#1697]
**Describe the bug**

Incorrect # of txs:
Looking at https://explorer.harmony.one/#/address/0xd763cf49cadfd4652434036fe9f2ae038fdc25dc

there are at least 4 txs happened in shard 2 but it only shows 1 transaction.

it could be explorer frontend bug or could be in explorer service.

**Comment by mikedoan** [comment]
<img width="1142" alt="Screen Shot 2019-10-02 at 11 52 48 AM" src="https://user-images.githubusercontent.com/40258599/66073164-6bf30380-e50b-11e9-9d9d-ddcb1a9e129a.png">

**Comment by lzl124631x** [comment]
![image](https://user-images.githubusercontent.com/5824517/66105319-04bb6a80-e570-11e9-863c-018ba578c057.png)

![image](https://user-images.githubusercontent.com/5824517/66105428-4ba96000-e570-11e9-87aa-8c6238739682.png)

The RPC returns 5 tx count but only 3 txs.

@flicker-harmony May you help check the issue? Thanks!

**Comment by flicker-harmony** [comment]
This is resolved, because TxCount considers only txs where address if "from", TxHistory considers both "from" and "to".
