### ISSUE TITLE
Two nodes in the testnet stuck in GetBlockHashes query failure

### ISSUE THREAD

**Issue by AndyBoWu** [harmony-one/harmony#1708]
**Describe the bug**
Two nodes in the testnet stuck.

**To Reproduce**
1. go to http://watchdog.hmny.io/report-testnet#shard-0
2. click the 'Block Number' header to sort the blocks in the ascending order
3. two nodes are stuck, harmony process is running, but they are not syncing with the rest of the nodes in the same shard

**Expected behavior**
block numbers should be increasing 

some log entries might be helpful for troubleshooting
`{"level":"error","port":"9000","ip":"34.238.42.51","error":"rpc error: code = Unknown desc = [SYNC] GetBlockHashes Request cannot find startHash 0x5ccd29f316871b85c457a7771a89d779747b496ebeaf568177c1cae180229029","target":"54.218.186.24:6000","caller":"/home/ec2-user/go/src/github.com/harmony-one/harmony/api/service/syncing/downloader/client.go:52","time":"2019-10-07T17:56:55.583917025Z","message":"[SYNC] GetBlockHashes query failed"}
{"level":"warn","port":"9000","ip":"34.238.42.51","peerIP":"54.218.186.24","peerPort":"6000","caller":"/home/ec2-user/go/src/github.com/harmony-one/harmony/api/service/syncing/syncing.go:351","time":"2019-10-07T17:56:55.583924392Z","message":"[SYNC] GetConsensusHashes Nil Response"}
{"level":"error","port":"9000","ip":"34.238.42.51","error":"rpc error: code = Unknown desc = [SYNC] GetBlockHashes Request cannot find startHash 0x5ccd29f316871b85c457a7771a89d779747b496ebeaf568177c1cae180229029","target":"54.186.83.167:6000","caller":"/home/ec2-user/go/src/github.com/harmony-one/harmony/api/service/syncing/downloader/client.go:52","time":"2019-10-07T17:56:55.584512825Z","message":"[SYNC] GetBlockHashes query failed"}
{"level":"warn","port":"9000","ip":"34.238.42.51","peerIP":"54.186.83.167","peerPort":"6000","caller":"/home/ec2-user/go/src/github.com/harmony-one/harmony/api/service/syncing/syncing.go:351","time":"2019-10-07T17:56:55.584523668Z","message":"[SYNC] GetConsensusHashes Nil Response"}
{"level":"info","port":"9000","ip":"34.238.42.51","maxFirstID":0,"maxCount":19,"caller":"/home/ec2-user/go/src/github.com/harmony-one/harmony/api/service/syncing/syncing.go:329","time":"2019-10-07T17:56:55.584542164Z","message":"[SYNC] block consensus hashes"}
{"level":"info","port":"9000","ip":"34.238.42.51","caller":"/home/ec2-user/go/src/github.com/harmony-one/harmony/api/service/syncing/syncing.go:377","time":"2019-10-07T17:56:55.584547452Z","message":"[SYNC] Finished getting consensus block hashes"}
{"level":"info","port":"9000","ip":"34.238.42.51","length":0,"caller":"/home/ec2-user/go/src/github.com/harmony-one/harmony/api/service/syncing/syncing.go:396","time":"2019-10-07T17:56:55.5845536Z","message":"[SYNC] Finished generateStateSyncTaskQueue"}
{"level":"debug","port":"9000","ip":"34.238.42.51","myHeight":247021,"requestHeight":247021,"incomingIP":"18.236.104.207","incomingPort":"9000","incomingPeer":"18.236.104.207:53184","caller":"/home/ec2-user/go/src/github.com/harmony-one/harmony/node/node_syncing.go:354","time":"2019-10-07T17:56:55.770079599Z","message":"[SYNC] GetBlockHashes Request: I am not higher than requested node"}`

**Comment by LeoHChen** [comment]
Another node is also stuck into this GetBlockHashes query failed loop.

```
{"level":"error","port":"9000","ip":"18.236.104.207","error":"rpc error: code = Unknown desc = [SYNC] GetBlockHashes Request cannot find startHash 0x5ccd29f316871b85c457a7771a89d779747b496ebeaf568177c1cae180229029","target":"18.236.131.248:6000","caller":"/home/ec2-user/go/src/github.com/harmony-one/harmony/api/service/syncing/downloader/client.go:52","time":"2019-10-08T19:52:15.397257061Z","message":"[SYNC] GetBlockHashes query failed"}
{"level":"warn","port":"9000","ip":"18.236.104.207","peerIP":"18.236.131.248","peerPort":"6000","caller":"/home/ec2-user/go/src/github.com/harmony-one/harmony/api/service/syncing/syncing.go:351","time":"2019-10-08T19:52:15.397264911Z","message":"[SYNC] GetConsensusHashes Nil Response"}
{"level":"error","port":"9000","ip":"18.236.104.207","error":"rpc error: code = Unknown desc = [SYNC] GetBlockHashes Request cannot find startHash 0x5ccd29f316871b85c457a7771a89d779747b496ebeaf568177c1cae180229029","target":"35.175.187.114:6000","caller":"/home/ec2-user/go/src/github.com/harmony-one/harmony/api/service/syncing/downloader/client.go:52","time":"2019-10-08T19:52:15.467303542Z","message":"[SYNC] GetBlockHashes query failed"}
{"level":"warn","port":"9000","ip":"18.236.104.207","peerIP":"35.175.187.114","peerPort":"6000","caller":"/home/ec2-user/go/src/github.com/harmony-one/harmony/api/service/syncing/syncing.go:351","time":"2019-10-08T19:52:15.467344863Z","message":"[SYNC] GetConsensusHashes Nil Response"}
{"level":"error","port":"9000","ip":"18.236.104.207","error":"rpc error: code = Unknown desc = [SYNC] GetBlockHashes Request cannot find startHash 0x5ccd29f316871b85c457a7771a89d779747b496ebeaf568177c1cae180229029","target":"34.236.36.83:6000","caller":"/home/ec2-user/go/src/github.com/harmony-one/harmony/api/service/syncing/downloader/client.go:52","time":"2019-10-08T19:52:15.467303533Z","message":"[SYNC] GetBlockHashes query failed"}
{"level":"error","port":"9000","ip":"18.236.104.207","error":"rpc error: code = Unknown desc = [SYNC] GetBlockHashes Request cannot find startHash 0x5ccd29f316871b85c457a7771a89d779747b496ebeaf568177c1cae180229029","target":"35.175.113.250:6000","caller":"/home/ec2-user/go/src/github.com/harmony-one/harmony/api/service/syncing/downloader/client.go:52","time":"2019-10-08T19:52:15.467353719Z","message":"[SYNC] GetBlockHashes query failed"}
{"level":"warn","port":"9000","ip":"18.236.104.207","peerIP":"34.236.36.83","peerPort":"6000","caller":"/home/ec2-user/go/src/github.com/harmony-one/harmony/api/service/syncing/syncing.go:351","time":"2019-10-08T19:52:15.467359733Z","message":"[SYNC] GetConsensusHashes Nil Response"}
{"level":"warn","port":"9000","ip":"18.236.104.207","peerIP":"35.175.113.250","peerPort":"6000","caller":"/home/ec2-user/go/src/github.com/harmony-one/harmony/api/service/syncing/syncing.go:351","time":"2019-10-08T19:52:15.467364011Z","message":"[SYNC] GetConsensusHashes Nil Response"}
{"level":"error","port":"9000","ip":"18.236.104.207","error":"rpc error: code = Unknown desc = [SYNC] GetBlockHashes Request cannot find startHash 0x5ccd29f316871b85c457a7771a89d779747b496ebeaf568177c1cae180229029","target":"3.81.27.2:6000","caller":"/home/ec2-user/go/src/github.com/harmony-one/harmony/api/service/syncing/downloader/client.go:52","time":"2019-10-08T19:52:15.471133701Z","message":"[SYNC] GetBlockHashes query failed"}
{"level":"warn","port":"9000","ip":"18.236.104.207","peerIP":"3.81.27.2","peerPort":"6000","caller":"/home/ec2-user/go/src/github.com/harmony-one/harmony/api/service/syncing/syncing.go:351","time":"2019-10-08T19:52:15.47116009Z","message":"[SYNC] GetConsensusHashes Nil Response"}
{"level":"error","port":"9000","ip":"18.236.104.207","error":"rpc error: code = Unknown desc = [SYNC] GetBlockHashes Request cannot find startHash 0x5ccd29f316871b85c457a7771a89d779747b496ebeaf568177c1cae180229029","target":"3.215.177.163:6000","caller":"/home/ec2-user/go/src/github.com/harmony-one/harmony/api/service/syncing/downloader/client.go:52","time":"2019-10-08T19:52:15.471567952Z","message":"[SYNC] GetBlockHashes query failed"}
{"level":"warn","port":"9000","ip":"18.236.104.207","peerIP":"3.215.177.163","peerPort":"6000","caller":"/home/ec2-user/go/src/github.com/harmony-one/harmony/api/service/syncing/syncing.go:351","time":"2019-10-08T19:52:15.471603361Z","message":"[SYNC] GetConsensusHashes Nil Response"}
{"level":"error","port":"9000","ip":"18.236.104.207","error":"rpc error: code = Unknown desc = [SYNC] GetBlockHashes Request cannot find startHash 0x5ccd29f316871b85c457a7771a89d779747b496ebeaf568177c1cae180229029","target":"35.172.121.207:6000","caller":"/home/ec2-user/go/src/github.com/harmony-one/harmony/api/service/syncing/downloader/client.go:52","time":"2019-10-08T19:52:15.472195704Z","message":"[SYNC] GetBlockHashes query failed"}
{"level":"warn","port":"9000","ip":"18.236.104.207","peerIP":"35.172.121.207","peerPort":"6000","caller":"/home/ec2-user/go/src/github.com/harmony-one/harmony/api/service/syncing/syncing.go:351","time":"2019-10-08T19:52:15.472231341Z","message":"[SYNC] GetConsensusHashes Nil Response"}
{"level":"error","port":"9000","ip":"18.236.104.207","error":"rpc error: code = Unknown desc = [SYNC] GetBlockHashes Request cannot find startHash 0x5ccd29f316871b85c457a7771a89d779747b496ebeaf568177c1cae180229029","target":"3.225.221.156:6000","caller":"/home/ec2-user/go/src/github.com/harmony-one/harmony/api/service/syncing/downloader/client.go:52","time":"2019-10-08T19:52:15.479609905Z","message":"[SYNC] GetBlockHashes query failed"}
{"level":"warn","port":"9000","ip":"18.236.104.207","peerIP":"3.225.221.156","peerPort":"6000","caller":"/home/ec2-user/go/src/github.com/harmony-one/harmony/api/service/syncing/syncing.go:351","time":"2019-10-08T19:52:15.479648104Z","message":"[SYNC] GetConsensusHashes Nil Response"}
{"level":"info","port":"9000","ip":"18.236.104.207","maxFirstID":0,"maxCount":19,"caller":"/home/ec2-user/go/src/github.com/harmony-one/harmony/api/service/syncing/syncing.go:329","time":"2019-10-08T19:52:15.47966881Z","message":"[SYNC] block consensus hashes"}
{"level":"info","port":"9000","ip":"18.236.104.207","caller":"/home/ec2-user/go/src/github.com/harmony-one/harmony/api/service/syncing/syncing.go:377","time":"2019-10-08T19:52:15.479677104Z","message":"[SYNC] Finished getting consensus block hashes"}
{"level":"info","port":"9000","ip":"18.236.104.207","length":0,"caller":"/home/ec2-user/go/src/github.com/harmony-one/harmony/api/service/syncing/syncing.go:396","time":"2019-10-08T19:52:15.479685552Z","message":"[SYNC] Finished generateStateSyncTaskQueue"}
```

**Comment by chaosma** [comment]
After investigation, these two nodes contains block different than others which makes them stuck forever (fork). Further investigation is needed to understand why the fork happened.

two stuck nodes: 
`{
  "id": 0,
  "jsonrpc": "2.0",
  "result": {
    "difficulty": 0,
    "extraData": "0x",
    "gasLimit": "0x6f05b59d3b20000",
    "gasUsed": "0x0",
    "hash": "0x5ccd29f316871b85c457a7771a89d779747b496ebeaf568177c1cae180229029",
    "logsBloom": "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
    "miner": "0x261fa45c6a09cd3faa277d829e91d9473973357c",
    "mixHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
    "nonce": 0,
    "number": "0x3c4ed",
    "parentHash": "0x28dc572d74c76fb09b06caa0f20c5d7e3f54b210021f3e4b81fd6804e33c1576",
    "receiptsRoot": "0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421",
    "size": "0x2de",
    "stateRoot": "0x4bf0f8e32282dd2792db83eab58660a8851845023d850830ee81b19eb03db2c1",
    "timestamp": "0x5d991add",
    "transactions": [],
    "transactionsRoot": "0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421",
    "uncles": []
  }
}`

Normal nodes:
`{
  "id": 0,
  "jsonrpc": "2.0",
  "result": {
    "difficulty": 0,
    "extraData": "0x",
    "gasLimit": "0x6f05b59d3b20000",
    "gasUsed": "0x0",
    "hash": "0x0693fd6d8d8e80a377de456852f5f69838786ba82b34d2af3c6debeb887b0707",
    "logsBloom": "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
    "miner": "0x0f25138bbbbff872e662c364ed0ff7f81640ab1a",
    "mixHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
    "nonce": 0,
    "number": "0x3c4ed",
    "parentHash": "0x28dc572d74c76fb09b06caa0f20c5d7e3f54b210021f3e4b81fd6804e33c1576",
    "receiptsRoot": "0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421",
    "size": "0x2de",
    "stateRoot": "0x4bf0f8e32282dd2792db83eab58660a8851845023d850830ee81b19eb03db2c1",
    "timestamp": "0x5d9a5fd6",
    "transactions": [],
    "transactionsRoot": "0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421",
    "uncles": []
  }
}`

**Comment by chaosma** [comment]
Further investigation showed that the two stuck nodes are the first two in the config files and the restart time of these nodes are early comparing to other nodes. My suspicion is that the network restart, the leader (index=0) is restarted first and only the leader and the one validator (index=1) got the committed message and others not received the committed message. 

To recover the two nodes: restart them will one block roll back.

**Comment by LeoHChen** [comment]
Can yo provide a generic fix ?  How to restart with one block rollback? Shall we add a generic tooling?

**Comment by LeoHChen** [comment]
okay.  I'd assign the ticket to @AndyBoWu to restart the testnet node, after remove the db.

**Comment by LeoHChen** [comment]
I'll open a ticket for an offline tool to remove the blocks from DB.
