### ISSUE TITLE
[Feature] update api functionality

### ISSUE THREAD

**Issue by flicker-harmony** [harmony-one/harmony#1711]
# Problem/limitation At Hand

1. Explorer api has block signers functionality: blocks can be shown with validators signed these blocks or without. Same should be implemented on hmy side to abandon explorer api in future.

2. John requested private accounts api methods to be implemented or or to be included and tested in validators methods list so that validators can easily use that. Needed methods: fetch user accounts (with private info or not?), sign and submit transactions with smart contract data.

3. Small details that current explorer or future validator explorer needs to be completed...

4. Maybe add some stacking api or refactor existing methods taking staking into account, for example, GetCommittee will have to return stakes of validators, not their balances.

**Which component?**

- [] hmyapi
- [] validator_api

# Proposed Solution

1. Add method separate getBlockSigners(blockHash []common.Hash) []internal_common.Address {} that returns list of signers, then add flags to block fetch methods (or refactor args into single Object struct to satisfy more args in future, also possibly add optional arg to show or not input/data byte for transactions).

2. We need to checkout and test existing signTransaction(), submitTransaction(), Accounts() methods if they satisfy requirements.

3. ...

# Alternatives Considered

# Additional Context

**Comment by LeoHChen** [comment]
assigned to Daniel to triage.

**Comment by LeoHChen** [comment]
old issue
