### ISSUE TITLE
cmd/wallet not working in local

### ISSUE THREAD

**Issue by rlan35** [harmony-one/harmony#1716]
./bin/wallet -p local transfer --from one1uyshu2jgv8w465yc8kkny36thlt2wvel89tcmg --to one1z05g55zamqzfw9qs432n33gycdmyvs38xjemyl --shardID 1 --toShardID 0 --amount 300 --pass file:empty.txt
Using local profile for wallet
Unlock account succeeded! 'file:empty.txt'
Transaction Id for shard 1: 0xa454f4ac91421f2c1b030ccf81fa931b6bb7d23836bb44f99c3d2f1e7abdf359

Nothing happens after the transfer

**Comment by flicker-harmony** [comment]
<img width="1152" alt="Screenshot 2019-10-12 at 04 59 21" src="https://user-images.githubusercontent.com/52401354/66704931-4fd03d00-ed29-11e9-8e74-ff234b00330e.png">
I set some logging to trace issue and got on shard 1 node (not shard 0 as supposed!)
./bin/wallet -p local transfer -from one103q7qe5t2505lypvltkqtddaef5tzfxwsse4z7 -to one18t4yj4fuutj83uwqckkvxp9gfa0568uc48ggj7 -amount 0.1 -shardID 0 -toShardID 0 -pass file:empty.txt
{"level":"info","port":"9001","ip":"127.0.0.1","caller":"/Users/vladlazarus/go/src/github.com/harmony-one/harmony/node/worker/worker.go:108","time":"2019-10-12T06:12:22.169512+03:00","message":"WTF? 0 1 0x5cb0779031d7f003a52f097ac6e114612f398c7f903403feb08b8f89e7f7c1c9"}, of course chan ids don't correspond as this was just shard 0 transaction. Transfer is done wallet and it does it by submitTransaction method which uses 
msg := proto_node.ConstructTransactionListMessageAccount(types.Transactions{tx})
clientGroup := nodeconfig.NewClientGroupIDByShardID(nodeconfig.ShardID(shardID))	
err := walletNode.GetHost().SendMessageToGroups([]nodeconfig.GroupID{clientGroup}, p2p_host.ConstructP2pMessage(byte(0), msg)). Possible errors is somewhere here, checking last merged PRs.

**Comment by LeoHChen** [comment]
fixed with my PR https://github.com/harmony-one/harmony/pull/1730
