### ISSUE TITLE
Nodes Syncing from the Beginning Stuck at Height 156

### ISSUE THREAD

**Issue by AndyBoWu** [harmony-one/harmony#1720]
**Describe the bug**
Restarted two nodes and forced them to sync from the beginning, but two of them are stuck at block 156. This is on Testnet.

**To Reproduce**
* remove the database from these two nodes 
* restart them using the command `./restart_node.sh -t 0 -r 0 -R 0 18.236.104.207`
* check out the log

**Expected behavior**
nodes will sync up from the beginning to the latest block

**Screenshots**
![Screen Shot 2019-10-10 at 4 41 12 PM](https://user-images.githubusercontent.com/5258417/66614368-a3058c80-eb7d-11e9-9b2d-0d81f6ae91cf.png)

**Environment (please complete the following information):**
N/A

**Additional context**
This is related to our previous ticket https://github.com/harmony-one/harmony/issues/1708

Some interesting log entries
`
{"level":"error","port":"9000","ip":"18.236.104.207","caller":"/home/ec2-user/go/src/github.com/harmony-one/harmony/core/blockchain.go:1666","time":"2019-10-10T23:42:44.719938454Z","message":"\n########## BAD BLOCK #########\nChain config: {ChainID: 2 EIP155: 0 CrossTx: 1 CrossLink: 2}\n\nNumber: 158\nHash: 0xa84186035821526972942f6ae15cfb4ffbbe3ac81efd7ae3aba7bb382c3570be\n\t&{[] 1 21000 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0] [] [29 4 155 114 60 243 41 76 79 249 80 97 86 8 250 50 17 16 7 44 25 140 81 208 156 16 232 17 190 92 64 101] [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0] 21000}\n\n\nError: invalid receipt root hash (remote: 14d733fcdecb87b0317f427a645628d921633a92cc264aa05c452df2c47cdb62 local: 056b23fbba480696b65fe5a59b8f2148a1299103c4f57df839233af2cf4ca2d2)\n##############################\n"}
`
`
{"level":"error","port":"9000","ip":"34.238.42.51","error":"invalid receipt root hash (remote: 14d733fcdecb87b0317f427a645628d921633a92cc264aa05c452df2c47cdb62 local: 056b23fbba480696b65fe5a59b8f2148a1299103c4f57df839233af2cf4ca2d2)","caller":"/home/ec2-user/go/src/github.com/harmony-one/harmony/api/service/syncing/syncing.go:564","time":"2019-10-10T23:43:24.263767299Z","message":"[SYNC] Error adding new block to blockchain 158 0"}
`

**Comment by LeoHChen** [comment]
@chaosma , can you take a look?

**Comment by LeoHChen** [comment]
@AndyBoWu , we should probably do a test of syncing from 0 on mainnet.

**Comment by LeoHChen** [comment]
I have concern on the signer.

**Comment by rlan35** [comment]
Invalid receipt root hash, related to cross shard @chao

**Comment by AndyBoWu** [comment]
@LeoHChen we can pick a random validator to do that in the mainnet. Let me know if you are OK with that.

**Comment by LeoHChen** [comment]
sure.  Please backup the db at first so that we can easily restore it w/o
resync everything.  Maybe try to use the sentry nodes.
-----
Leo Chen

work hard, dream big, make history.
culture <https://harmony.one/culture>, team <https://harmony.one/team/>,
deck <https://harmony.one/deck>, roadmap <http://harmony.one/roadmap>,
vision <https://harmony.one/xoogler>, research
<https://harmony.one/research>, whitepaper <https://harmony.one/whitepaper>,
code <https://github.com/harmony-one/harmony>, annual-letter
<https://harmony.one/annual-letter>, newsletter <https://harmony.one/news>,
overview <http://harmony.one/overview>, binance-report
<https://harmony.one/binance-report>
