### ISSUE TITLE
Failed to restart a node

### ISSUE THREAD

**Issue by AndyBoWu** [harmony-one/harmony#1735]
**Describe the bug**
Failed to restart a node

**To Reproduce**
1. pick any node from this list (18.236.136.215, 54.186.93.148, 52.27.34.100, 34.214.14.21, 34.213.125.94, and 35.153.143.150)
2. ./restart_node.sh -t 0 -R 0 54.186.93.148

**Expected behavior**
`harmony` service starts, and the node is online for voting  

**Screenshots**
Node stuck, and the related log entries are the following
`
{"level":"debug","port":"9000","ip":"54.186.93.148","runtime":1727.677467,"caller":"/data/harmony/internal/hmyapi/blockchain.go:171","time":"2019-10-15T19:16:10.517221676Z","message":"Executing EVM call finished"}
`

**Environment (please complete the following information):**
 - OS: [Linux, MacOS]
- Go environment [ ```go env``` ]

**Additional context**

**Comment by LeoHChen** [comment]
We need to bring back those nodes.  

0) stop the harmony process on the nodes
1) remove all the harmony_db_* from the node
2) create tarballs of harmony_db_* from a good node
3) copy the tarball to the trouble nodes, untar
4) restart the harmony process.

**Comment by AndyBoWu** [comment]
172.31.26.113 - 52.27.34.100

172.31.31.159 - 54.186.93.148

172.31.28.127 - 18.236.136.215

172.31.25.88 - 34.213.125.94

172.31.31.199 - 34.214.14.21

**Comment by AndyBoWu** [comment]
also found this on 54.186.93.148

`
{"level":"error","port":"9000","ip":"54.186.93.148","error":"leveldb: not found","caller":"/data/harmony/node/node_cross_shard.go:219","time":"2019-10-16T20:59:46.832627949Z","message":"[ProcessingHeader] ReadCrossLink cannot read previousLink with number 184017, shardID 1"}
`

**Comment by LeoHChen** [comment]
34.213.125.94 has the OOM memory crash issue @harmony-ek was looking at.
52.27.34.100 can't connect to bootnode

**Comment by LeoHChen** [comment]
Can't connect to 34.214.14.21

**Comment by LeoHChen** [comment]
So all the "Executing EVM call finished" are actually OOM issue.  Found it on "18.236.136.215"
