### ISSUE TITLE
[Bounty] one click migration from ethereum to harmony

### ISSUE THREAD

**Issue by LeoHChen** [harmony-one/harmony#1760]
We need to build a website to help dApp developers migrate existing ethereum smart contracts to harmony blockchain (testnet/mainnet).

Harmony blockchain is very compatible to ETH, however, our API have additional fields like shard info.  The one-click migration website should be able to support convert existing ethereum smart contract and deploy it to Harmony testnet.

**Comment by isaacadams** [comment]
I'd be happy to work on this

**Comment by LeoHChen** [comment]
fully evm compatible, not needed anymore
