### ISSUE TITLE
[Feature] latest/zerolog-*.log is automatically rotated but latest/validator-*.log is not

### ISSUE THREAD

**Issue by nyetwurk** [harmony-one/harmony#1771]
Currently zerolog is autorotated by harmony, but validator-*.log is not.

This means it needs to be externally rotated via something like logrotate, but the other does not.

This should be one or the other for both.

**Comment by nyetwurk** [comment]
Having experimented with this, bad things happen when native zerolog rotation is disabled; logrotate CANNOT rotate out logs created by zerolog, it holds them open via what appears to be mmap(), so if logrotate does copy/truncate, the next time zerolog writes out an entry, the entire file gets recreated with leading zeros.

**Comment by yelllowsin** [comment]
Closing this one as logs have been consolidated into zerolog-validator*.log file and being rotated accordingly. Feel free to reopen if any issue remains.
