### ISSUE TITLE
testnet bootstrap failed

### ISSUE THREAD

**Issue by LeoHChen** [harmony-one/harmony#1775]
**Describe the bug**

Latest master code, unable to bootstrap the blockchai network.  Leader proposed the blockchain in announce message, it is unable to receive enough signed messages to proceed.

This problem was found on Jenkins and I verified it by launching a new pr100 testnet work.

**Comment by rlan35** [comment]
how many signatures did the leader get? Seems a timing or p2p network issue.

**Comment by LeoHChen** [comment]
The root cause is the min-peer set to 32 when we launch the testnet.  Leader has not enough peers for consensus after proposing the block.  I changed it to 66 and the network seems okay in my test.
