### ISSUE TITLE
[Bounty] docker images for building harmony blockchain node program and release

### ISSUE THREAD

**Issue by LeoHChen** [harmony-one/harmony#1790]
# About The Bounty
https://github.com/harmony-one/harmony-open/blob/master/README.md

# Category
- [x] build
- [ ] bug
- [ ] feature
- [ ] document
- [ ] dApp
- [ ] test

# Description

A docker image contains all the necessary toolchain that can be used to build harmony blockchain node program. This docker image can be uploaded to our official docker hub.  It should contain the golang toolchain 1.13, some tools like jq, bash 4.x+, openssl, gmp,  So a new developer can just download the docker image and clone all the codes and start to build the node program.

This can be extended to another docker image contains the toolchain and all the source code for release as well.

# T-shirt Size

S

# Time Estimation
2 days

# Key Deliverables
* dockerfile to build the docker images
* documentation
* first release of working docker image can be used by the team

# Explore All Bounties
https://gitcoin.co/profile/harmony-one

**Comment by JB273** [comment]
Hi Leo, I have a question about this;
On what Linux distro do you want this image to run?
