### ISSUE TITLE
[security] harden our node setup document

### ISSUE THREAD

**Issue by LeoHChen** [harmony-one/harmony#1791]
**Describe the bug**

Our current node setup document https://nodes.harmony.one/foundational-node-playbook/setting-up-your-node/setupnode didn't use security group and IP to protect the port 22 of node runner's host.  This is risky.  The best practice is to always whitelist the IP address to access the host, so that there is a protection on the IP address that can connect to the host.  Of course, we have to give user warnings on how to whitelist additional IP addresses to the security group.

Expectation is to add some doc/warning about how to whitelist the IP address to access the host, and provide an FAQ entry about why I can't access the host from a different IP address.  This security tip is not a mandatory requirement, but it is always good to provide and educate node runners on the security issue.

**Comment by mindstyle85** [comment]
@AndyBoWu this still open?

**Comment by LeoHChen** [comment]
not needed
