### ISSUE TITLE
[Feature] smart contracts events

### ISSUE THREAD

**Issue by flicker-harmony** [harmony-one/harmony#1798]
# Problem/limitation At Hand

@v1ruc on discord noted that there is not possible to fetch events from smart contracts for now, and hmy_getLogs method that suppose to do that isn't implemented. We also hadn't smart contracts events in our roadmap so I'm not sure if this functionality even exist. Solidity of course has events functionality. Question stands - do we support current version of Solidity fully? What needs to be added to enable smart contracts events functionality?

API methods to fetch events can be implemented on Node API, SDK, go-sdk, everywhere if events are supported by our smart contracts.

**Which component?**

- [ ] contracts

# Proposed Solution

To figure out what needs to be done for smart contracts events functionality and implement that.

# Alternatives Considered

# Additional Context

**Comment by v1ruc** [comment]
What is required in terms of being able to work with the Logs are 2 `json_rpc` calls: `hmy_getTransactionReceipt`, `hmy_getLogs`

**Comment by john-harmony** [comment]
@flicker-harmony can you add your thoughts on this.

**Comment by flicker-harmony** [comment]
hmy_getTransactionReceipt has transaction hash and smart contract address field. hmy_getLogs return smart contract events based on arg Ethereum Filter Criteria (json struct), format can be seen there https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_getlogs. It subscribes to events based on filter and returns past logs. Events already implemented in harmony-sdk https://github.com/harmony-one/sdk/tree/master/packages/harmony-contract/src/events https://github.com/harmony-one/sdk/blob/master/packages/harmony-network/src/subscriptions/LogSub.ts . Using them as simple as using specific node.js package.

**Comment by LeoHChen** [comment]
getlog is implemented already
