### ISSUE TITLE
[Feature] smart contracts missing functionality

### ISSUE THREAD

**Issue by flicker-harmony** [harmony-one/harmony#1799]
# Problem/limitation At Hand

@johnwhitton noted that some of functionality to work with smart contracts is missing
and also which was confirmed in https://github.com/harmony-one/harmony/issues/1798. Discrepancies between current APIs, SDK, contract-library and  https://web3js.readthedocs.io/en/v1.2.2/web3-eth-contract.html#  are noted in https://docs.google.com/spreadsheets/d/1wRDYhvX11gEuD0arpXrVK4HJEoxnpC6YoX3BgH6rDeA/edit#gid=0

**Which component?**

- [ ] contract-library
- [ ] go-sdk
- [ ] harmony-sdk
- [ ] wallet-cli

# Proposed Solution

Most of missing functionality should be implemented in web3 like style. So deploy, clone, send, call accounts, contract methods and tx signing/generation best to be implemented on go-sdk/wallet-cli/contract-library which can work with user private info, private keys and it makes more sense to implement it there as users will use it to create, compile, send and call contracts from contract-library. Some of methods can be implemented on any API too, for example contract.Call which doesn't change blockchain state or Events fetching.

# Alternatives Considered

We need to discuss where to add each method. Are constants like defaultBlock, defaultCommon, defaultChain are needed, do we have them, are they implemented? Do we support full Solidity functionality and current Solidity version? Do we support contracts events?

# Additional Context

**Comment by LeoHChen** [comment]
fully evm compatible already
