### ISSUE TITLE
Single Bootnode Down, No Peers Connect

### ISSUE THREAD

**Issue by gaia** [harmony-one/harmony#1812]
**Describe the bug**
54.213.43.194 is currently down (can't telnet, [can't nc](https://nodes.harmony.one/foundational-node-playbook/faq#how-to-check-my-bootnode-connectivity)). node doesn't start. commenting out `/ip4/54.213.43.194/tcp/9874/p2p/QmZJJx6AdaoEkGLrYG4JeLCKeCKDjnFz2wfHNHxAqFSGA9` in node.sh allows the node to start.

**To Reproduce**
1. block outbound to one of the bootnodes
2. start node.sh
3. no BINGOs, unsurprisingly: "No peers, continue" "failed to dial : all dials failed" "can't connect to bootnode", although the bootnodes that are up connected fine:

![image](https://user-images.githubusercontent.com/87547/68415282-d587b280-0146-11ea-9b80-f814d5d9b65f.png)

**Expected behavior**
The purpose of having multiple bootnodes is exactly redundancy, but having the node stop because a single bootnode is down makes this redundancy pointless.

**Environment (please complete the following information):**
 - OS: Ubuntu 18.04

**Comment by AndyBoWu** [comment]
This issue has been fixed. Thank you for reporting the issue.

**Comment by nyetwurk** [comment]
Just fixing the node is NOT sufficient; harmony should not fail to start if a a single bootnode is down.

**Comment by rlan35** [comment]
https://github.com/harmony-one/harmony/pull/1815 This will fix the issue. The bootnode down is actually not blocking the client to start forever, but it blocked for 10 mins. This PR changes it to be 30s so it won't appear to be blocking.
