### ISSUE TITLE
Localnet cross-shard transaction does not work after block 15

### ISSUE THREAD

**Issue by Daniel-VDM** [harmony-one/harmony#1838]
**Describe the bug**
Unable to send Cx on localnet after block 15

**To Reproduce**
https://www.youtube.com/watch?v=52lVyZCkCZA&feature=youtu.be 
https://www.youtube.com/watch?v=A3ekto75hLE&feature=youtu.be 

**Expected behavior**
Cx works.

**Screenshots**
Reference video

**Environment (please complete the following information):**
 - OS: MacOS: Catalina 
- Go environment:
```
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/danielvdm/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/danielvdm/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/Cellar/go@1.12/1.12.10/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go@1.12/1.12.10/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/14/nf2hcx6j27q3pw4sl1653_4c0000gn/T/go-build996035426=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

**Additional context**
Reported this in person, this is just for bookkeeping.

**Comment by rlan35** [comment]
https://github.com/harmony-one/harmony/pulls?q=is%3Apr+is%3Aclosed
