### ISSUE TITLE
Naming and type consistency of PRC API

### ISSUE THREAD

**Issue by liuyangc3** [harmony-one/harmony#1843]
## Problems
the key of shardid in respone of `hmy_latestHeader` and `hmy_getShardingStructure` is `shardID`
while `hmy_getNodeMetadata` is `shard-id`.

type of `chainid` is string while `shard-id` is number in `hmy_getNodeMetadata`, also consider `chainID` instead of `chainid`.

method `hmy_latestHeader` and `hmy_getNodeMetadata` not list in document, but can be found  here: https://github.com/harmony-one/harmony-ops/blob/master/monitoring/harmony-monitor/blockchain-watchdog/reporting-server.go#L24

## Proposal
better naming , better document

**Comment by LeoHChen** [comment]
@fxfactorial , @john-harmony
