### ISSUE TITLE
TODO: Add staking transactions into txns root

### ISSUE THREAD

**Issue by rlan35** [harmony-one/harmony#1918]
Currently the staking transactions are not computed into the transaction root of the header.

We need to add that logic in block proposal and also block verification

search for "TODO: Add staking transactions into txns root" for the places that need changes.

**Comment by mindstyle85** [comment]
this looks done @rlan35 , closing for now

**Comment by fxfactorial** [comment]
Sort of done, not really in a way . I have huge amount of work on this from earlier this week
