### ISSUE TITLE
[Staking Economy] Add circulating supply schedule in the codebase

### ISSUE THREAD

**Issue by rlan35** [harmony-one/harmony#1922]
Currently we have 12.6 total supply coded in the codebase for staking ratio calculation.

But the staking ratio should really be calculated with circulating supply described in harmony.one/unlock.

Add a hardcoded schedule based on block time for the circulating supply and replace the total supply in the staking ratio calculation: https://github.com/harmony-one/harmony/blob/master/internal/chain/reward.go#L161

**Comment by fxfactorial** [comment]
done: https://github.com/harmony-one/harmony/pull/1929
