### ISSUE TITLE
[Feature] SDK wiki

### ISSUE THREAD

**Issue by flicker-harmony** [harmony-one/harmony#1923]
# Problem/limitation At Hand

Right now wiki for https://github.com/harmony-one/sdk is just a README and should be updated to look the same as https://github.com/ethereum/wiki/wiki/JavaScript-API. Harmony SDK methods and packages almost the same as Web3. It was done for Ethereum ecosystem support. 

**Which component?**

- [ ] sdk
- [ ] wiki

# Proposed Solution

Can be done in https://app.gitbook.com.

# Alternatives Considered

# Additional Context

**Comment by LeoHChen** [comment]
https://api.hmny.io is up and running.
