### ISSUE TITLE
Bad Block during shard 0 consensus

### ISSUE THREAD

**Issue by rlan35** [harmony-one/harmony#1924]
{"level":"error","port":"9000","ip":"34.209.25.152","caller":"/home/ec2-user/RJ/harmony/core/blockchain.go:1847","time":"2019-11-30T22:51:04.929748765Z","message":"\n########## BAD BLOCK #########\nChain config: {ChainID: 3 EIP155: 0 CrossTx: 0 Staking: 3 CrossLink: 2}\n\nNumber: 5466\nEpoch: 36\nNumTxn: 0\nNumStkTxn: 0\nHash: 0x5477afd8685815f590a80f5e4e424b922138482eeae7e11a5b7fe4ad31d5b59a\n\n\nError: invalid merkle root (remote: a959705fd296634cfc31decd17faf7743d35cba0320c7a74fabff2cfe6492088 local: 73cdf3bd44443b2982d12517c219b677d79ca26ba724efe3398157410322d06b)\n##############################\n"}
{"level":"error","port":"9000","ip":"34.209.25.152","blockHash":"0x5477afd8685815f590a80f5e4e424b922138482eeae7e11a5b7fe4ad31d5b59a","numTx":0,"error":"invalid merkle root (remote: a959705fd296634cfc31decd17faf7743d35cba0320c7a74fabff2cfe6492088 local: 73cdf3bd44443b2982d12517c219b677d79ca26ba724efe3398157410322d06b)","caller":"/home/ec2-user/RJ/harmony/node/node_handler.go:277","time":"2019-11-30T22:51:04.929803888Z","message":"cannot ValidateNewBlock"}
{"level":"info","port":"9000","ip":"34.209.25.152","caller":"/home/ec2-user/RJ/harmony/consensus/consensus_v2.go:1023","time":"2019-11-30T22:51:04.929853152Z","message":"[TryCatchup]block verification faied"}
{"level":"warn","port":"9000","ip":"34.209.25.152","beforeCatchupBlockNum":5466,"caller":"/home/ec2-user/RJ/harmony/consensus/consensus_v2.go:804","time":"2019-11-30T22:51:04.929863714Z","message":"[FinalizeCommits] Leader cannot provide the correct block for committed message"}
{"level":"info","port":"9000","ip":"34.209.25.152","policy":"SuperMajorityStake","phase":"Prepare","threshold":"0.666666666666666667","total-power-of-signers":"0.988325581395348838","caller":"/home/ec2-user/RJ/harmony/consensus/quorum/one-node-staked-vote.go:61","time":"2019-11-30T22:51:04.936994185Z","message":"Attempt to reach quorum"}
{"level":"info","port":"9000","ip":"34.209.25.152","validatorPubKey":"66002b3b505b6ea30e9f60b7881c8b79ad5e6eb12bf83bd4a2124bb2e0255268508f9437d3f50494504f4b0c1795ee06","MsgViewID":5465,"MsgBlockNum":5466,"numReceivedSoFar":39,"caller":"/home/ec2-user/RJ/harmony/consensus/consensus_v2.go:742","time":"2019-11-30T22:51:04.942675966Z","message":"[OnCommit] Received new commit message"}
{"level":"info","port":"9000","ip":"34.209.25.152","policy":"SuperMajorityStake","phase":"Prepare","threshold":"0.666666666666666667","total-power-of-signers":"1.005325581395348838","caller":"/home/ec2-user/RJ/harmony/consensus/quorum/one-node-staked-vote.go:61","time":"2019-11-30T22:51:04.94290679Z","message":"Attempt to reach quorum"}
{"level":"info","port":"9000","ip":"34.209.25.152","policy":"SuperMajorityStake","phase":"Prepare","threshold":"0.666666666666666667","total-power-of-signers":"1.005325581395348838","caller":"/home/ec2-user/RJ/harmony/consensus/quorum/one-node-staked-vote.go:61","time":"2019-11-30T22:51:04.951123581Z","message":"Attempt to reach quorum"}
{"level":"info","port":"9000","ip":"34.209.25.152","validatorPubKey":"5b4af2ba307819c7f3d8524c12149f24b9dba324907a5be382666a91de23ebfdd5056bc05935591c0b6d8ce6ebfa0703","MsgViewID":5465,"MsgBlockNum":5466,"numReceivedSoFar":40,"caller":"/home/ec2-user/RJ/harmony/consensus/consensus_v2.go:742","time":"2019-11-30T22:51:04.95663483Z","message":"[OnCommit] Received new commit message"}
{"level":"info","port":"9000","ip":"34.209.25.152","policy":"SuperMajorityStake","phase":"Prepare","threshold":"0.666666666666666667","total-power-of-signers":"1.022325581395348838","caller":"/home/ec2-user/RJ/harmony/consensus/quorum/one-node-staked-vote.go:61","time":"2019-11-30T22:51:04.956877973Z","message":"Attempt to reach quorum"}
{"level":"info","port":"9000","ip":"34.209.25.152","NumCommits":41,"caller":"/home/ec2-user/RJ/harmony/consensus/consensus_v2.go:773","time":"2019-11-30T22:51:04.957028458Z","message":"[Finalizing] Finalizing Block"}
{"level":"info","port":"9000","ip":"34.209.25.152","validatorPubKey":"7af325e13ba1c08a9468433fd34d0adb3cea2eae8d88bf5932115bf1e08e9aae0ddcde4fb840bc2af6006b42d1568a0d","MsgViewID":5465,"MsgBlockNum":5466,"numReceivedSoFar":37,"caller":"/home/ec2-user/RJ/harmony/consensus/consensus_v2.go:765","time":"2019-11-30T22:51:04.957231589Z","message":"[OnCommit] 90% Enough commits received"}
{"level":"debug","port":"9000","ip":"34.209.25.152","myEpoch":36,"myBlock":5466,"myViewID":5465,"phase":2,"mode":"Normal","senderKey":"52167fc8450eb655ea1fb3de45ec7694fb3afea6778f6b4c46beb0ba9d4137334cd4b625e2f09bd55c37d72ba8697816","caller":"/home/ec2-user/RJ/harmony/consensus/consensus_service.go:72","time":"2019-11-30T22:51:04.957248075Z","message":"[populateMessageFields]"}
{"level":"info","port":"9000","ip":"34.209.25.152","numShards":102,"caller":"/home/ec2-user/RJ/harmony/core/rawdb/accessors_chain.go:480","time":"2019-11-30T22:51:04.959458678Z","message":"wrote last commits"}
{"level":"info","port":"9000","ip":"34.209.25.152","caller":"/home/ec2-user/RJ/harmony/consensus/consensus_v2.go:998","time":"2019-11-30T22:51:04.959568785Z","message":"[TryCatchup] commit new blocks"}
{"level":"error","port":"9000","ip":"34.209.25.152","numMsgs":5,"caller":"/home/ec2-user/RJ/harmony/consensus/consensus_v2.go:1011","time":"2019-11-30T22:51:04.959598044Z","message":"[TryCatchup] DANGER!!! we should only get one committed message for a given blockNum"}
{"level":"info","port":"9000","ip":"34.209.25.152","caller":"/home/ec2-user/RJ/harmony/consensus/consensus_v2.go:1013","time":"2019-11-30T22:51:04.959605714Z","message":"[TryCatchup] committed message found"}

**Comment by rlan35** [comment]
View Change didn't happen because all the new leaders got:

{"level":"debug","port":"9000","ip":"34.204.206.172","caller":"/home/ec2-user/RJ/harmony/consensus/view_change.go:220","time":"2019-11-30T23:58:29.483933541Z","message":"[onViewChange] add my M1 type messaage"}
{"level":"debug","port":"9000","ip":"34.204.206.172","need":29,"have":21,"caller":"/home/ec2-user/RJ/harmony/consensus/view_change.go:288","time":"2019-11-30T23:58:29.488846779Z","message":"[onViewChange] M1 Payload Not Have Enough Signature"}
{"level":"info","port":"9000","ip":"34.204.206.172","policy":"SuperMajorityStake","phase":"Commit","threshold":"0.666666666666666667","total-power-of-signers":"0.017000000000000000","caller":"/home/ec2-user/RJ/harmony/consensus/quorum/one-node-staked-vote.go:61","time":"2019-11-30T23:58:29.529925912Z","message":"Attempt to reach quorum"}
{"level":"debug","port":"9000","ip":"34.204.206.172","need":29,"have":21,"caller":"/home/ec2-user/RJ/harmony/consensus/view_change.go:288","time":"2019-11-30T23:58:29.537238479Z","message":"[onViewChange] M1 Payload Not Have Enough Signature"}
{"level":"info","port":"9000","ip":"34.204.206.172","policy":"SuperMajorityStake","phase":"Commit","threshold":"0.666666666666666667","total-power-of-signers":"0.017000000000000000","caller":"/home/ec2-user/RJ/harmony/consensus/quorum/one-node-staked-vote.go:61","time":"2019-11-30T23:58:29.550012881Z","message":"Attempt to reach quorum"}
{"level":"debug","port":"9000","ip":"34.204.206.172","need":29,"have":21,"caller":"/home/ec2-user/RJ/harmony/consensus/view_change.go:288","time":"2019-11-30T23:58:29.557122669Z","message":"[onViewChange] M1 Payload Not Have Enough Signature"}
{"level":"info","port":"9000","ip":"34.204.206.172","policy":"SuperMajorityStake","phase":"Commit","threshold":"0.666666666666666667","total-power-of-signers":"0.017000000000000000","caller":"/home/ec2-user/RJ/harmony/consensus/quorum/one-node-staked-vote.go:61","time":"2019-11-30T23:58:29.576744323Z","message":"Attempt to reach quorum"}
{"level":"debug","port":"9000","ip":"34.204.206.172","need":29,"have":21,"caller":"/home/ec2-user/RJ/harmony/consensus/view_change.go:288","time":"2019-11-30T23:58:29.583745453Z","message":"[onViewChange] M1 Payload Not Have Enough Signature"}
{"level":"info","port":"9000","ip":"34.204.206.172","policy":"SuperMajorityStake","phase":"Commit","threshold":"0.666666666666666667","total-power-of-signers":"0.017000000000000000","caller":"/home/ec2-user/RJ/harmony/consensus/quorum/one-node-staked-vote.go:61","time":"2019-11-30T23:58:29.597882121Z","message":"Attempt to reach quorum"}
{"level":"debug","port":"9000","ip":"34.204.206.172","need":29,"have":21,"caller":"/home/ec2-user/RJ/harmony/consensus/view_change.go:288","time":"2019-11-30T23:58:29.605472665Z","message":"[onViewChange] M1 Payload Not Have Enough Signature"}
{"level":"info","port":"9000","ip":"34.204.206.172","policy":"SuperMajorityStake","phase":"Commit","threshold":"0.666666666666666667","total-power-of-signers":"0.017000000000000000","caller":"/home/ec2-user/RJ/harmony/consensus/quorum/one-node-staked-vote.go:61","time":"2019-11-30T23:58:29.644134819Z","message":"Attempt to reach quorum"}
{"level":"debug","port":"9000","ip":"34.204.206.172","need":29,"have":21,"caller":"/home/ec2-user/RJ/harmony/consensus/view_change.go:288","time":"2019-11-30T23:58:29.651195221Z","message":"[onViewChange] M1 Payload Not Have Enough Signature"}
{"level":"info","port":"9000","ip":"34.204.206.172","policy":"SuperMajorityStake","phase":"Commit","threshold":"0.666666666666666667","total-power-of-signers":"0.017000000000000000","caller":"/home/ec2-user/RJ/harmony/consensus/quorum/one-node-staked-vote.go:61","time":"2019-11-30T23:58:29.858313952Z","message":"Attempt to reach quorum"}
{"level":"debug","port":"9000","ip":"34.204.206.172","need":29,"have":21,"caller":"/home/ec2-user/RJ/harmony/consensus/view_change.go:288","time":"2019-11-30T23:58:29.865324234Z","message":"[onViewChange] M1 Payload Not Have Enough Signature"}
{"level":"info","port":"9000","ip":"34.204.206.172","policy":"SuperMajorityStake","phase":"Commit","threshold":"0.666666666666666667","total-power-of-signers":"0.017000000000000000","caller":"/home/ec2-user/RJ/harmony/consensus/quorum/one-node-staked-vote.go:61","time":"2019-11-30T23:58:30.124951851Z","message":"Attempt to reach quorum"}
{"level":"debug","port":"9000","ip":"34.204.206.172","need":29,"have":21,"caller":"/home/ec2-user/RJ/harmony/consensus/view_change.go:288","time":"2019-11-30T23:58:30.131759849Z","message":"[onViewChange] M1 Payload Not Have Enough Signature"}
{"level":"info","port":"9000","ip":"34.204.206.172","policy":"SuperMajorityStake","phase":"Commit","threshold":"0.666666666666666667","total-power-of-signers":"0.017000000000000000","caller":"/home/ec2-user/RJ/harmony/consensus/quorum/one-node-staked-vote.go:61","time":"2019-11-30T23:58:30.356739318Z","message":"Attempt to reach quorum"}
{"level":"debug","port":"9000","ip":"34.204.206.172","need":29,"have":21,"caller":"/home/ec2-user/RJ/harmony/consensus/view_change.go:288","time":"2019-11-30T23:58:30.363687677Z","message":"[onViewChange] M1 Payload Not Have Enough Signature"}

**Comment by chaosma** [comment]
The root cause is that the validators still used counting 2/3 of total nodes instead of 2/3 of total voting power to validate the signatures.
