### ISSUE TITLE
./hmy cookbook has a typo for balance check command

### ISSUE THREAD

**Issue by mirrormirage0** [harmony-one/harmony#1945]
**Describe the bug**
`./hmy cookbook` has a typo for balance check command

**To Reproduce**
1. open a terminal and type ./hmy cookbook
2. it shows the balance check command as 
`hmy --node="https://api.s1.b.hmny.io/" balance <SOME_ONE_ADDRESS>`
3. if you type this command, hmy will complain 
**_Error: unknown command "balance" for "hmy"
Did you mean this?
	balances
Run 'hmy --help' for usage._**

**Expected behavior**
.hmy cookbook should show the balance check command as "balances" not "balance"

**Screenshots**
![image](https://user-images.githubusercontent.com/29485946/70092915-c3f7d480-1638-11ea-9f6d-b88729d5914b.png)

**Environment (please complete the following information):**
 - OS: [Linux]
- .hmy version Harmony (C) 2019. hmy, version v139-409693d (@harmony.one 2019-12-02T11:52:15-0800)

**Comment by fxfactorial** [comment]
thank you, fixed. Also the right repo to report issues about the `hmy` cli is here: https://github.com/harmony-one/go-sdk
