### ISSUE TITLE
./hmy balances oneXXXXX throws segmentation fault error

### ISSUE THREAD

**Issue by mirrormirage0** [harmony-one/harmony#1953]
**Describe the bug**
./hmy balances throws error 
 ./hmy balances one1w38sklxrekm3u28ruf367kxyadqhzpzsr86u6f
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x63 pc=0x7f2d7d1c8448]
 
runtime stack:
runtime.throw(0xdba3fb, 0x2a)
    /usr/local/go/src/runtime/panic.go:617 +0x72
runtime.sigpanic()
    /usr/local/go/src/runtime/signal_unix.go:374 +0x4a9
 
goroutine 74 [syscall]:
runtime.cgocall(0xa1fb59, 0xc00036a5e0, 0xc00038e020)
    /usr/local/go/src/runtime/cgocall.go:128 +0x5b fp=0xc00036a5b0 sp=0xc00036a578 pc=0x40491b
net._C2func_getaddrinfo(0xc000282200, 0x0, 0xc0000a5950, 0xc00038e020, 0x0, 0x0, 0x0)
    _cgo_gotypes.go:91 +0x55 fp=0xc00036a5e0 sp=0xc00036a5b0 pc=0x5839b5
net.cgoLookupIPCNAME.func1(0xc000282200, 0x13, 0x13, 0xc0000a5950, 0xc00038e020, 0x12, 0x42d74f, 0x8)
    /usr/local/go/src/net/cgo_unix.go:154 +0x13e fp=0xc00036a628 sp=0xc00036a5e0 pc=0x5891ee
net.cgoLookupIPCNAME(0xd8089b, 0x2, 0xc000282160, 0x12, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
    /usr/local/go/src/net/cgo_unix.go:154 +0x176 fp=0xc00036a718 sp=0xc00036a628 pc=0x584e86
net.cgoIPLookup(0xc0000ba4e0, 0xd8089b, 0x2, 0xc000282160, 0x12)
    /usr/local/go/src/net/cgo_unix.go:206 +0x67 fp=0xc00036a7b8 sp=0xc00036a718 pc=0x585577
runtime.goexit()
    /usr/local/go/src/runtime/asm_amd64.s:1337 +0x1 fp=0xc00036a7c0 sp=0xc00036a7b8 pc=0x45b821
created by net.cgoLookupIP
    /usr/local/go/src/net/cgo_unix.go:216 +0xc7
 
goroutine 1 [select]:
net.(*Resolver).lookupIPAddr(0x180a6c0, 0x105bfc0, 0xc0000b6018, 0xd8089b, 0x2, 0xc000282160, 0x12, 0x7f2d830dad98, 0x0, 0x414d9f, ...)
    /usr/local/go/src/net/lookup.go:275 +0x663
net.(*Resolver).LookupIPAddr(...)
    /usr/local/go/src/net/lookup.go:205
net.LookupIP(0xc000282160, 0x12, 0x1bb, 0x0, 0x0, 0x3, 0x0)
    /usr/local/go/src/net/lookup.go:191 +0x88
github.com/valyala/fasthttp.resolveTCPAddrs(0xc000282160, 0x16, 0xc000282100, 0x16, 0x1848e20, 0x8, 0x203000, 0xc0000a51a0)
    /root/go/pkg/mod/github.com/valyala/fasthttp@v1.2.0/tcpdialer.go:425 +0xc7
github.com/valyala/fasthttp.(*TCPDialer).getTCPAddrs(0x17712e0, 0xc000282160, 0x16, 0x7f2d830e4700, 0xc0006115a0, 0x40d0c9, 0xc0000ae5b0, 0x4e56f9, 0xc000282160, 0x16)
    /root/go/pkg/mod/github.com/valyala/fasthttp@v1.2.0/tcpdialer.go:390 +0x14c
github.com/valyala/fasthttp.(*TCPDialer).dial(0x17712e0, 0xc000282160, 0x16, 0xd80000000070c300, 0xb2d05e00, 0xd83550da1474c32d, 0xc000282160, 0x12, 0xc0000a5560)
    /root/go/pkg/mod/github.com/valyala/fasthttp@v1.2.0/tcpdialer.go:255 +0xac
github.com/valyala/fasthttp.(*TCPDialer).Dial(...)
    /root/go/pkg/mod/github.com/valyala/fasthttp@v1.2.0/tcpdialer.go:164
github.com/valyala/fasthttp.Dial(0xc000282160, 0x16, 0xc0000a5101, 0xc000282160, 0x16, 0xc0000ae638)
    /root/go/pkg/mod/github.com/valyala/fasthttp@v1.2.0/tcpdialer.go:36 +0x51
github.com/valyala/fasthttp.dialAddr(0xc000282160, 0x16, 0x0, 0xc000080100, 0xc00008d080, 0x10dfa83cc, 0x180aee0, 0xc000611748, 0x7482ba)
    /root/go/pkg/mod/github.com/valyala/fasthttp@v1.2.0/client.go:1566 +0x4a
github.com/valyala/fasthttp.(*HostClient).dialHostHard(0xc00028a500, 0xf5e420, 0xc00028a500, 0x73183f, 0xc0000cdd40)
    /root/go/pkg/mod/github.com/valyala/fasthttp@v1.2.0/client.go:1526 +0x199
github.com/valyala/fasthttp.(*HostClient).acquireConn(0xc00028a500, 0x5b29e2c1, 0x180aee0, 0x18127a0)
    /root/go/pkg/mod/github.com/valyala/fasthttp@v1.2.0/client.go:1292 +0xee
github.com/valyala/fasthttp.(*HostClient).doNonNilReqResp(0xc00028a500, 0xc000122dc0, 0xc0000cdd40, 0x403671, 0xc000282180, 0x6fc078f6)
    /root/go/pkg/mod/github.com/valyala/fasthttp@v1.2.0/client.go:1143 +0xcb
github.com/valyala/fasthttp.(*HostClient).do(0xc00028a500, 0xc000122dc0, 0xc0000cdd40, 0xf70000c000282160, 0xc0006118a0, 0xf79bd5c02373a6c1)
    /root/go/pkg/mod/github.com/valyala/fasthttp@v1.2.0/client.go:1110 +0x57
github.com/valyala/fasthttp.(*HostClient).Do(0xc00028a500, 0xc000122dc0, 0xc0000cdd40, 0x12, 0xc0003b0300)
    /root/go/pkg/mod/github.com/valyala/fasthttp@v1.2.0/client.go:1060 +0x76
github.com/valyala/fasthttp.(*Client).Do(0x180b3c0, 0xc000122dc0, 0xc0000cdd40, 0xc000611a20, 0x1a)
    /root/go/pkg/mod/github.com/valyala/fasthttp@v1.2.0/client.go:437 +0x1f2
github.com/valyala/fasthttp.Do(...)
    /root/go/pkg/mod/github.com/valyala/fasthttp@v1.2.0/client.go:37
github.com/harmony-one/go-sdk/pkg/rpc.baseRequest(0xd866f6, 0xe, 0xc00039a0a0, 0x1a, 0xc8bc40, 0xc00028c0c0, 0xc000282100, 0x1f, 0xc000611b80, 0x40af6d, ...)
    /root/go/src/github.com/go-sdk/pkg/rpc/query.go:32 +0x48a
github.com/harmony-one/go-sdk/pkg/rpc.Request(0xd866f6, 0xe, 0xc00039a0a0, 0x1a, 0xc8bc40, 0xc00028c0c0, 0x1f, 0x0, 0x0)
    /root/go/src/github.com/go-sdk/pkg/rpc/query.go:59 +0xab
github.com/harmony-one/go-sdk/pkg/sharding.CheckAllShards(0xd8a560, 0x15, 0x7ffcb5555efc, 0x2a, 0xd81800, 0x4, 0x985d30, 0xc000345d48, 0xc000345d18)
    /root/go/src/github.com/go-sdk/pkg/sharding/structure.go:43 +0x224
github.com/harmony-one/go-sdk/cmd/subcommands.init.0.func1(0xc000300280, 0xc0002ecfd0, 0x1, 0x1, 0x0, 0x0)
    /root/go/src/github.com/go-sdk/cmd/subcommands/balance.go:17 +0x6c
github.com/spf13/cobra.(*Command).execute(0xc000300280, 0xc0002ecf90, 0x1, 0x1, 0xc000300280, 0xc0002ecf90)
    /root/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:826 +0x465
github.com/spf13/cobra.(*Command).ExecuteC(0x1778b60, 0xd7e6a0, 0x0, 0xc000361680)
    /root/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x2fc
github.com/spf13/cobra.(*Command).Execute(...)
    /root/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
github.com/harmony-one/go-sdk/cmd/subcommands.Execute()
    /root/go/src/github.com/go-sdk/cmd/subcommands/root.go:87 +0x2e
main.main()
    /root/go/src/github.com/go-sdk/cmd/main.go:32 +0xbe
 
goroutine 19 [sleep]:
runtime.goparkunlock(...)
    /usr/local/go/src/runtime/proc.go:307
time.Sleep(0x3b9aca00)
    /usr/local/go/src/runtime/time.go:105 +0x159
github.com/valyala/fasthttp.init.0.func1()
    /root/go/pkg/mod/github.com/valyala/fasthttp@v1.2.0/header.go:1443 +0x2a
created by github.com/valyala/fasthttp.init.0
    /root/go/pkg/mod/github.com/valyala/fasthttp@v1.2.0/header.go:1441 +0x3a
 
goroutine 21 [syscall]:
os/signal.signal_recv(0x0)
    /usr/local/go/src/runtime/sigqueue.go:139 +0x9c
os/signal.loop()
    /usr/local/go/src/os/signal/signal_unix.go:23 +0x22
created by os/signal.init.0
    /usr/local/go/src/os/signal/signal_unix.go:29 +0x41
 
goroutine 22 [chan receive]:
github.com/rjeczalik/notify.(*nonrecursiveTree).dispatch(0xc0000ba720, 0xc0000ba660)
    /root/go/pkg/mod/github.com/rjeczalik/notify@v0.9.2/tree_nonrecursive.go:36 +0xb6
created by github.com/rjeczalik/notify.newNonrecursiveTree
    /root/go/pkg/mod/github.com/rjeczalik/notify@v0.9.2/tree_nonrecursive.go:29 +0xdd
 
goroutine 23 [chan receive]:
github.com/rjeczalik/notify.(*nonrecursiveTree).internal(0xc0000ba720, 0xc0000ba6c0)
    /root/go/pkg/mod/github.com/rjeczalik/notify@v0.9.2/tree_nonrecursive.go:81 +0x58
created by github.com/rjeczalik/notify.newNonrecursiveTree
    /root/go/pkg/mod/github.com/rjeczalik/notify@v0.9.2/tree_nonrecursive.go:30 +0x109
 
goroutine 24 [chan receive]:
github.com/ethereum/go-ethereum/core.(*txSenderCacher).cache(0xc0002ec470)
    /root/go/pkg/mod/github.com/ethereum/go-ethereum@v1.8.27/core/tx_cacher.go:63 +0x97
created by github.com/ethereum/go-ethereum/core.newTxSenderCacher
    /root/go/pkg/mod/github.com/ethereum/go-ethereum@v1.8.27/core/tx_cacher.go:55 +0x9f
 
goroutine 25 [chan receive]:
github.com/ethereum/go-ethereum/core.(*txSenderCacher).cache(0xc0002ec470)
    /root/go/pkg/mod/github.com/ethereum/go-ethereum@v1.8.27/core/tx_cacher.go:63 +0x97
created by github.com/ethereum/go-ethereum/core.newTxSenderCacher
    /root/go/pkg/mod/github.com/ethereum/go-ethereum@v1.8.27/core/tx_cacher.go:55 +0x9f
 
goroutine 26 [chan receive]:
github.com/ethereum/go-ethereum/core.(*txSenderCacher).cache(0xc0002ec470)
    /root/go/pkg/mod/github.com/ethereum/go-ethereum@v1.8.27/core/tx_cacher.go:63 +0x97
created by github.com/ethereum/go-ethereum/core.newTxSenderCacher
    /root/go/pkg/mod/github.com/ethereum/go-ethereum@v1.8.27/core/tx_cacher.go:55 +0x9f
 
goroutine 27 [chan receive]:
github.com/ethereum/go-ethereum/core.(*txSenderCacher).cache(0xc0002ec470)
    /root/go/pkg/mod/github.com/ethereum/go-ethereum@v1.8.27/core/tx_cacher.go:63 +0x97
created by github.com/ethereum/go-ethereum/core.newTxSenderCacher
    /root/go/pkg/mod/github.com/ethereum/go-ethereum@v1.8.27/core/tx_cacher.go:55 +0x9f
 
goroutine 28 [chan receive]:
github.com/ethereum/go-ethereum/core.(*txSenderCacher).cache(0xc0002ec470)
    /root/go/pkg/mod/github.com/ethereum/go-ethereum@v1.8.27/core/tx_cacher.go:63 +0x97
created by github.com/ethereum/go-ethereum/core.newTxSenderCacher
    /root/go/pkg/mod/github.com/ethereum/go-ethereum@v1.8.27/core/tx_cacher.go:55 +0x9f
 
goroutine 29 [chan receive]:
github.com/ethereum/go-ethereum/core.(*txSenderCacher).cache(0xc0002ec470)
    /root/go/pkg/mod/github.com/ethereum/go-ethereum@v1.8.27/core/tx_cacher.go:63 +0x97
created by github.com/ethereum/go-ethereum/core.newTxSenderCacher
    /root/go/pkg/mod/github.com/ethereum/go-ethereum@v1.8.27/core/tx_cacher.go:55 +0x9f
 
goroutine 30 [chan receive]:
github.com/ethereum/go-ethereum/core.(*txSenderCacher).cache(0xc0002ec470)
    /root/go/pkg/mod/github.com/ethereum/go-ethereum@v1.8.27/core/tx_cacher.go:63 +0x97
created by github.com/ethereum/go-ethereum/core.newTxSenderCacher
    /root/go/pkg/mod/github.com/ethereum/go-ethereum@v1.8.27/core/tx_cacher.go:55 +0x9f
 
goroutine 31 [chan receive]:
github.com/ethereum/go-ethereum/core.(*txSenderCacher).cache(0xc0002ec470)
    /root/go/pkg/mod/github.com/ethereum/go-ethereum@v1.8.27/core/tx_cacher.go:63 +0x97
created by github.com/ethereum/go-ethereum/core.newTxSenderCacher
    /root/go/pkg/mod/github.com/ethereum/go-ethereum@v1.8.27/core/tx_cacher.go:55 +0x9f
 
goroutine 32 [chan receive]:
github.com/harmony-one/harmony/core.(*txSenderCacher).cache(0xc0002ec730)
    /root/go/pkg/mod/github.com/harmony-one/harmony@v0.0.0-20191106012056-10f5d6274891/core/tx_cacher.go:63 +0x97
created by github.com/harmony-one/harmony/core.newTxSenderCacher
    /root/go/pkg/mod/github.com/harmony-one/harmony@v0.0.0-20191106012056-10f5d6274891/core/tx_cacher.go:55 +0x9f
 
goroutine 33 [chan receive]:
github.com/harmony-one/harmony/core.(*txSenderCacher).cache(0xc0002ec730)
    /root/go/pkg/mod/github.com/harmony-one/harmony@v0.0.0-20191106012056-10f5d6274891/core/tx_cacher.go:63 +0x97
created by github.com/harmony-one/harmony/core.newTxSenderCacher
    /root/go/pkg/mod/github.com/harmony-one/harmony@v0.0.0-20191106012056-10f5d6274891/core/tx_cacher.go:55 +0x9f
 
goroutine 34 [chan receive]:
github.com/harmony-one/harmony/core.(*txSenderCacher).cache(0xc0002ec730)
    /root/go/pkg/mod/github.com/harmony-one/harmony@v0.0.0-20191106012056-10f5d6274891/core/tx_cacher.go:63 +0x97
created by github.com/harmony-one/harmony/core.newTxSenderCacher
    /root/go/pkg/mod/github.com/harmony-one/harmony@v0.0.0-20191106012056-10f5d6274891/core/tx_cacher.go:55 +0x9f
 
goroutine 35 [chan receive]:
github.com/harmony-one/harmony/core.(*txSenderCacher).cache(0xc0002ec730)
    /root/go/pkg/mod/github.com/harmony-one/harmony@v0.0.0-20191106012056-10f5d6274891/core/tx_cacher.go:63 +0x97
created by github.com/harmony-one/harmony/core.newTxSenderCacher
    /root/go/pkg/mod/github.com/harmony-one/harmony@v0.0.0-20191106012056-10f5d6274891/core/tx_cacher.go:55 +0x9f
 
goroutine 36 [chan receive]:
github.com/harmony-one/harmony/core.(*txSenderCacher).cache(0xc0002ec730)
    /root/go/pkg/mod/github.com/harmony-one/harmony@v0.0.0-20191106012056-10f5d6274891/core/tx_cacher.go:63 +0x97
created by github.com/harmony-one/harmony/core.newTxSenderCacher
    /root/go/pkg/mod/github.com/harmony-one/harmony@v0.0.0-20191106012056-10f5d6274891/core/tx_cacher.go:55 +0x9f
 
goroutine 37 [chan receive]:
github.com/harmony-one/harmony/core.(*txSenderCacher).cache(0xc0002ec730)
    /root/go/pkg/mod/github.com/harmony-one/harmony@v0.0.0-20191106012056-10f5d6274891/core/tx_cacher.go:63 +0x97
created by github.com/harmony-one/harmony/core.newTxSenderCacher
    /root/go/pkg/mod/github.com/harmony-one/harmony@v0.0.0-20191106012056-10f5d6274891/core/tx_cacher.go:55 +0x9f
 
goroutine 38 [chan receive]:
github.com/harmony-one/harmony/core.(*txSenderCacher).cache(0xc0002ec730)
    /root/go/pkg/mod/github.com/harmony-one/harmony@v0.0.0-20191106012056-10f5d6274891/core/tx_cacher.go:63 +0x97
created by github.com/harmony-one/harmony/core.newTxSenderCacher
    /root/go/pkg/mod/github.com/harmony-one/harmony@v0.0.0-20191106012056-10f5d6274891/core/tx_cacher.go:55 +0x9f
 
goroutine 39 [chan receive]:
github.com/harmony-one/harmony/core.(*txSenderCacher).cache(0xc0002ec730)
    /root/go/pkg/mod/github.com/harmony-one/harmony@v0.0.0-20191106012056-10f5d6274891/core/tx_cacher.go:63 +0x97
created by github.com/harmony-one/harmony/core.newTxSenderCacher
    /root/go/pkg/mod/github.com/harmony-one/harmony@v0.0.0-20191106012056-10f5d6274891/core/tx_cacher.go:55 +0x9f
 
goroutine 40 [sleep]:
runtime.goparkunlock(...)
    /usr/local/go/src/runtime/proc.go:307
time.Sleep(0x2540be400)
    /usr/local/go/src/runtime/time.go:105 +0x159
github.com/valyala/fasthttp.(*Client).mCleaner(0x180b3c0, 0xc0002fdbc0)
    /root/go/pkg/mod/github.com/valyala/fasthttp@v1.2.0/client.go:462 +0x143
created by github.com/valyala/fasthttp.(*Client).Do
    /root/go/pkg/mod/github.com/valyala/fasthttp@v1.2.0/client.go:434 +0x24b
 
goroutine 41 [sleep]:
runtime.goparkunlock(...)
    /usr/local/go/src/runtime/proc.go:307
time.Sleep(0x2540be400)
    /usr/local/go/src/runtime/time.go:105 +0x159
github.com/valyala/fasthttp.(*HostClient).connsCleaner(0xc000121540)
    /root/go/pkg/mod/github.com/valyala/fasthttp@v1.2.0/client.go:1354 +0x332
created by github.com/valyala/fasthttp.(*HostClient).acquireConn
    /root/go/pkg/mod/github.com/valyala/fasthttp@v1.2.0/client.go:1289 +0x192
 
goroutine 42 [sleep]:
runtime.goparkunlock(...)
    /usr/local/go/src/runtime/proc.go:307
time.Sleep(0x3b9aca00)
    /usr/local/go/src/runtime/time.go:105 +0x159
github.com/valyala/fasthttp.(*TCPDialer).tcpAddrsClean(0x17712e0)
    /root/go/pkg/mod/github.com/valyala/fasthttp@v1.2.0/tcpdialer.go:367 +0x110
created by github.com/valyala/fasthttp.(*TCPDialer).dial.func1
    /root/go/pkg/mod/github.com/valyala/fasthttp@v1.2.0/tcpdialer.go:252 +0x6a
 
goroutine 66 [sleep]:
runtime.goparkunlock(...)
    /usr/local/go/src/runtime/proc.go:307
time.Sleep(0x2540be400)
    /usr/local/go/src/runtime/time.go:105 +0x159
github.com/valyala/fasthttp.(*Client).mCleaner(0x180b3c0, 0xc0003a8210)
    /root/go/pkg/mod/github.com/valyala/fasthttp@v1.2.0/client.go:462 +0x143
created by github.com/valyala/fasthttp.(*Client).Do
    /root/go/pkg/mod/github.com/valyala/fasthttp@v1.2.0/client.go:434 +0x24b
 
goroutine 67 [sleep]:
runtime.goparkunlock(...)
    /usr/local/go/src/runtime/proc.go:307
time.Sleep(0x2540be400)
    /usr/local/go/src/runtime/time.go:105 +0x159
github.com/valyala/fasthttp.(*HostClient).connsCleaner(0xc0003c0000)
    /root/go/pkg/mod/github.com/valyala/fasthttp@v1.2.0/client.go:1354 +0x332
created by github.com/valyala/fasthttp.(*HostClient).acquireConn
    /root/go/pkg/mod/github.com/valyala/fasthttp@v1.2.0/client.go:1289 +0x192
 
goroutine 72 [sleep]:
runtime.goparkunlock(...)
    /usr/local/go/src/runtime/proc.go:307
time.Sleep(0x2540be400)
    /usr/local/go/src/runtime/time.go:105 +0x159
github.com/valyala/fasthttp.(*HostClient).connsCleaner(0xc00028a500)
    /root/go/pkg/mod/github.com/valyala/fasthttp@v1.2.0/client.go:1354 +0x332
created by github.com/valyala/fasthttp.(*HostClient).acquireConn
    /root/go/pkg/mod/github.com/valyala/fasthttp@v1.2.0/client.go:1289 +0x192
 
goroutine 73 [select]:
net.cgoLookupIP(0x105bf80, 0xc000396080, 0xd8089b, 0x2, 0xc000282160, 0x12, 0x0, 0x0, 0x0, 0x0, ...)
    /usr/local/go/src/net/cgo_unix.go:217 +0x195
net.(*Resolver).lookupIP(0x180a6c0, 0x105bf80, 0xc000396080, 0xd8089b, 0x2, 0xc000282160, 0x12, 0x0, 0x0, 0xc000353800, ...)
    /usr/local/go/src/net/lookup_unix.go:96 +0x1a4
net.glob..func1(0x105bf80, 0xc000396080, 0xc000288240, 0xd8089b, 0x2, 0xc000282160, 0x12, 0x0, 0x0, 0x0, ...)
    /usr/local/go/src/net/hook.go:23 +0x72
net.(*Resolver).lookupIPAddr.func1(0x0, 0x0, 0x0, 0x0)
    /usr/local/go/src/net/lookup.go:269 +0x116
internal/singleflight.(*Group).doCall(0x180a6d0, 0xc000330000, 0xc0002821c0, 0x15, 0xc0003960c0)
    /usr/local/go/src/internal/singleflight/singleflight.go:95 +0x2e
created by internal/singleflight.(*Group).DoChan
    /usr/local/go/src/internal/singleflight/singleflight.go:88 +0x29d
**To Reproduce**
1. ./hmy balances oneXXXXXX

**Expected behavior**
Display wallet balance

**Environment (please complete the following information):**
 - OS: [Linux] Ubuntu 18.04
- Go environment [ ```go env``` ] gov1.12
- ./hmy version
Harmony (C) 2019. hmy, version v139-409693d (@harmony.one 2019-12-02T11:52:15-0800)

**Comment by fxfactorial** [comment]
thank you for report, this is a known issue, @LeoHChen

**Comment by fxfactorial** [comment]
thank you, fixed in latest version , please download and check

**Comment by mirrormirage0** [comment]
Verified.
Issue is fixed in the latest binary.
./hmy balances one1hs80ss7xzxt6rl6kkvecc4yrenttx8dw308vyj
[
  {
    "shard": 0,
    "amount": 9999.999959912
  },
  {
    "shard": 1,
    "amount": 0.0000
  }
]
