### ISSUE TITLE
Edit Validator Segmentation Fault

### ISSUE THREAD

**Issue by mirrormirage0** [harmony-one/harmony#1961]
**Describe the bug**
Edit validator command dies with segmentation fault

**To Reproduce**
./hmy --node=https://api.s0.pga.hmny.io/ staking edit-validator --validator-addr one1hs80ss7xzxt6rl6kkvecc4yrenttx8dw308vyj --name Mirror --identity Mirror --website mirrormirage0@gmail.com --security-contact Mirror --details "One Too Many"  --rate 0.01 --min-self-delegation 2 --max-total-delegation 30 --remove-bls-key 4cc25d3c530d8ce6d0ec3c1e8f14454739fbf69b607cd80e2567252ac7d426f85f2cffebf47b2f6b28031d5bfd70b815 --add-bls-key 4cc25d3c530d8ce6d0ec3c1e8f14454739fbf69b607cd80e2567252ac7d426f85f2cffebf47b2f6b28031d5bfd70b815 --chain-id pangaea
Enter the bls passphrase:
Repeat the bls passphrase:
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xa0e903]

goroutine 1 [running]:
github.com/harmony-one/go-sdk/cmd/subcommands.delegationAmountSanityCheck(0xc0002cc120, 0xc0002cc140, 0x0, 0x0, 0x0)
    /home/edgar/go/src/github.com/harmony-one/go-sdk/cmd/subcommands/staking.go:167 +0x143
github.com/harmony-one/go-sdk/cmd/subcommands.stakingSubCommands.func2(0xc0002f9400, 0xc0000afa00, 0x0, 0x19, 0x0, 0x0)
    /home/edgar/go/src/github.com/harmony-one/go-sdk/cmd/subcommands/staking.go:412 +0x3a3
github.com/spf13/cobra.(*Command).execute(0xc0002f9400, 0xc0000af860, 0x19, 0x1a, 0xc0002f9400, 0xc0000af860)
    /home/edgar/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:826 +0x465
github.com/spf13/cobra.(*Command).ExecuteC(0x15a3d80, 0x10, 0x0, 0xc000306280)
    /home/edgar/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x2fc
github.com/spf13/cobra.(*Command).Execute(...)
    /home/edgar/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
github.com/harmony-one/go-sdk/cmd/subcommands.Execute()
    /home/edgar/go/src/github.com/harmony-one/go-sdk/cmd/subcommands/root.go:87 +0x2e
main.main()
    /home/edgar/go/src/github.com/harmony-one/go-sdk/cmd/main.go:37 +0xec

**Expected behavior**
Validator information should be updated.

**Environment (please complete the following information):**
 - OS: [AWS Linux]
-  hmy: [Harmony (C) 2019. hmy, version v155-0e04a27 (edgar@harmony.one 2019-12-05T01:03:36-0800)]

**Comment by janet-harmony** [comment]
Fixed & new version of CLI uploaded

**Comment by mattlockyer** [comment]
Re-opening because I also experienced this issue.

For me it was making the `/bls` repo manually, then attempting to run make in `/go-sdk`

Steps to fix:
Go to `/bls` run `make clean`
Go to `/harmony` repo, run make, run `source scripts/setup_bls_build_flags.sh`
Go to `/go-sdk`, run make

**Comment by fxfactorial** [comment]
@mattlockyer on linux, you invoke `make static` and the result `hmy` binary is fully statically linked
