### ISSUE TITLE
Staking Delegate command dies (with passphrase)

### ISSUE THREAD

**Issue by mirrormirage0** [harmony-one/harmony#1962]
**Describe the bug**
Staking delegate command dies on typing the first character of passphrase

**To Reproduce**
./hmy --node=https://api.s0.pga.hmny.io/ staking delegate --delegator-addr one130rxdq6gzkmacqgp8fk07sxjv5mdg7yrykknr6 --validator-addr one1hs80ss7xzxt6rl6kkvecc4yrenttx8dw308vyj --amount 10 --chain-id pangaea
Error: could not decrypt key with given passphrase: could not unlock account with passphrase, perhaps need different phrase
v156f947e75: could not decrypt key with given passphrase: could not unlock account with passphrase, perhaps need different phrase

**Expected behavior**
Prompt for passphrase, accept passphrase, delegate

**Environment (please complete the following information):**
 - OS: AWS Linux
- hmy version Harmony (C) 2019. hmy, version v156-f947e75 (edgar@harmony.one 2019-12-05T01:18:14-0800)

**Comment by janet-harmony** [comment]
`./hmy staking delegate` does not prompt for passphrase. It requires the passphrase to unlock the keystore for the "one130rxdq6gzkmacqgp8fk07sxjv5mdg7yrykknr6" address (delegator). Use `--passphrase`. 

```
./hmy --node=https://api.s0.pga.hmny.io/ staking delegate --delegator-addr one130rxdq6gzkmacqgp8fk07sxjv5mdg7yrykknr6 --validator-addr one1hs80ss7xzxt6rl6kkvecc4yrenttx8dw308vyj --amount 10 --chain-id pangaea --passphrase (YOUR_PASSPHRASE)
```

If `--passphrase` flag is not given, the CLI assumes the default passphrase which is an empty string.

**Comment by mindstyle85** [comment]
question, why do we need to provide a flag for this, why arent we just prompted for the wallet pass, same as bls key for creating validator for example? i think both passes should be prompted like that everywhere, to unify... @fxfactorial @janet-harmony

**Comment by mindstyle85** [comment]
this one can now be closed @mirrormirage0
