### ISSUE TITLE
HMY CLI gives out empty results on queries via localhost node

### ISSUE THREAD

**Issue by mindstyle85** [harmony-one/harmony#1965]
**Describe the bug**
With steps to reproduce below, and the command I ran, I am getting an empty result back, which should not happen if my localhost has a fully updates DB by running a node/validator, which I did.

**To Reproduce**
1. curl -LO https://harmony.one/hmycli && mv hmycli hmy && chmod +x hmy
2. have a working node on devnet, make it a validator and do 1 extra self delegation with collecting rewards
3. run the hmy commands: 
./hmy blockchain validator all
./hmy blockchain delegation by-delegator one1rn89qcxm3pqf83sk5jx54w9hdwftxg4khylfe 
./hmy blockchain delegation by-validator one1rn89qcxm3pqf83sk58jx54w9hdwftxg4khylfe

Received result:
./hmy blockchain validator all
{
  "id": "0",
  "jsonrpc": "2.0",
  "result": []
}

./hmy blockchain delegation by-validator one1rn89qcxm3pqf83sk58jx54w9hdwftxg4khylfe
{
  "id": "0",
  "jsonrpc": "2.0",
  "result": []
}

 ./hmy blockchain delegation by-delegator one1rn89qcxm3pqf83sk5jx54w9hdwftxg4khylfe 
{
  "id": "0",
  "jsonrpc": "2.0",
  "result": []
}

**Expected behavior**
Expected is a non 0 result, such as:
./hmy --node=https://api.s0.pga.hmny.io blockchain validator all
{
  "id": "0",
  "jsonrpc": "2.0",
  "result": [
    "one1pdv9lrdwl0rg5vglh4xtyrv3wjk3wsqket7zxy",
    "one1zksj3evekayy90xt4psrz8h6j2v3hla4qwz4ur",
    "one1zeaj5yqtkjz0wdjkqvlejxk3vljx5g3k8xzfx0",
    "one1rn89qcxm3pqf83sk58jx54w9hdwftxg4khylfe",
    "one1qmkfpu8xhdy685z9gxpm053lm89qtqs45ut9mp",
    "one1echapu535qgtc5ktkgjj3raec4x4gp0a2mh9ec",
    "one152yn6nvyjuln3kp4m2rljj6hvfapfhdxsmr79a",
    "one103q7qe5t2505lypvltkqtddaef5tzfxwsse4z7",
    "one1hs80ss7xzxt6rl6kkvecc4yrenttx8dw308vyj"
  ]
}

**Environment:**
 - OS: Linux, ubuntu 16.04 LTS with dnsmasq installed

**Additional context**
Some other node validators on devnet did get non empty result on the above queries, without using the RPC endpoint.

**Comment by rlan35** [comment]
Not reproducible anymore. It's likely due to inconsistent binary issue at devnet when the test happens. The local running node likely didn't join consensus successfully so didn't show the latest staking formation.

I did the same in current devnet and it works.
