### ISSUE TITLE
HMY CLI gives 2 different outputs on 2 active validators when they query the chain

### ISSUE THREAD

**Issue by mindstyle85** [harmony-one/harmony#1966]
**Describe the bug**
Myself and @yelllowsin tried to check whether we both get the same list of active validators. We were both synced and active at that point (it was about 11-12 hours ago from now).

**To Reproduce**
1. Have 2 active validators on devnet
2. Install hmycli on those
3. run the following command:
./hmy blockchain validator all-active

**Received result**

yellowsin's query:
./hmy blockchain validator all-active
{
  "id": "0",
  "jsonrpc": "2.0",
  "result": [
    "one103q7qe5t2505lypvltkqtddaef5tzfxwsse4z7",
    "one1pdv9lrdwl0rg5vglh4xtyrv3wjk3wsqket7zxy",
    "one1qmkfpu8xhdy685z9gxpm053lm89qtqs45ut9mp",
    "one1zksj3evekayy90xt4psrz8h6j2v3hla4qwz4ur",
    "one1zeaj5yqtkjz0wdjkqvlejxk3vljx5g3k8xzfx0",
    "one1echapu535qgtc5ktkgjj3raec4x4gp0a2mh9ec",
    "one152yn6nvyjuln3kp4m2rljj6hvfapfhdxsmr79a",
    "one1rn89qcxm3pqf83sk58jx54w9hdwftxg4khylfe"
  ]
}

my query:
./hmy blockchain validator all-active
{
  "id": "0",
  "jsonrpc": "2.0",
  "result": [
    "one1qmkfpu8xhdy685z9gxpm053lm89qtqs45ut9mp",
    "one1pdv9lrdwl0rg5vglh4xtyrv3wjk3wsqket7zxy",
    "one1zksj3evekayy90xt4psrz8h6j2v3hla4qwz4ur",
    "one1zeaj5yqtkjz0wdjkqvlejxk3vljx5g3k8xzfx0",
    "one1echapu535qgtc5ktkgjj3raec4x4gp0a2mh9ec",
    "one1rn89qcxm3pqf83sk58jx54w9hdwftxg4khylfe"
  ]

**Expected behavior**
Exact same result on both queries (from myself and yelllowsin).

**Environment (please complete the following information):**
 - OS: yelllowsin (Debian 10), me (Ubuntu 16.04 LTS), latest hmycli version on both

**Comment by janet-harmony** [comment]
Unable to reproduce.

When you say you were both synced, you if latest block was matching?
Are you still getting this issue now?

**Comment by mindstyle85** [comment]
yes we were both synced fully and having working validators, unfortunately cant check again since my validator is still running on devnet and @yelllowsins is stuck/not syncing anymore

**Comment by rlan35** [comment]
This is usually a node sync'ing issue. Now the devnet is updated with latest binary in the release. Please retry. Otherwise, this should be safe to close.

**Comment by mindstyle85** [comment]
closing, tried on pangaea instead of devnet, getting the same results so its possible one of the nodes was not syncing correctly at that point
