### ISSUE TITLE
HMYCLI querying active validators right now gives a list of validators that are stuck/cant sync

### ISSUE THREAD

**Issue by mindstyle85** [harmony-one/harmony#1968]
**Describe the bug**
HMYCLI querying active validators right now gives a list of validators that are stuck/cant sync

./hmyblockchain validator all-active
{
  "id": "0",
  "jsonrpc": "2.0",
  "result": [
    "one1qmkfpu8xhdy685z9gxpm053lm89qtqs45ut9mp",
    "one1pdv9lrdwl0rg5vglh4xtyrv3wjk3wsqket7zxy",
    "one103q7qe5t2505lypvltkqtddaef5tzfxwsse4z7",
    "one1zksj3evekayy90xt4psrz8h6j2v3hla4qwz4ur",
    "one1zeaj5yqtkjz0wdjkqvlejxk3vljx5g3k8xzfx0",
    "one1echapu535qgtc5ktkgjj3raec4x4gp0a2mh9ec",
    "one152yn6nvyjuln3kp4m2rljj6hvfapfhdxsmr79a",
    "one1rn89qcxm3pqf83sk58jx54w9hdwftxg4khylfe"
  ]
}

and same result with the endpoint:

 ./hmy --node=https://api.s0.pga.hmny.io blockchain validator all
{
  "id": "0",
  "jsonrpc": "2.0",
  "result": [
    "one1pdv9lrdwl0rg5vglh4xtyrv3wjk3wsqket7zxy",
    "one1zksj3evekayy90xt4psrz8h6j2v3hla4qwz4ur",
    "one1zeaj5yqtkjz0wdjkqvlejxk3vljx5g3k8xzfx0",
    "one1rn89qcxm3pqf83sk58jx54w9hdwftxg4khylfe",
    "one1qmkfpu8xhdy685z9gxpm053lm89qtqs45ut9mp",
    "one1echapu535qgtc5ktkgjj3raec4x4gp0a2mh9ec",
    "one152yn6nvyjuln3kp4m2rljj6hvfapfhdxsmr79a",
    "one103q7qe5t2505lypvltkqtddaef5tzfxwsse4z7",
    "one1hs80ss7xzxt6rl6kkvecc4yrenttx8dw308vyj"
  ]
}

**Expected behavior**
Most validator nodes are stuck and cant sync, except mine one1rn89qcxm3pqf83sk58jx54w9hdwftxg4khylfe, so why are all those stuck nodes still listed as active?

**Comment by mindstyle85** [comment]
@fxfactorial think this question is for you :)

**Comment by fxfactorial** [comment]
Active in this context doesn’t mean like they are making progress but more that they are active as actual validators known in the chain
