### ISSUE TITLE
 ChainID on node differs from received chainID:  Tranfers / Tx

### ISSUE THREAD

**Issue by BrunoMarshall** [harmony-one/harmony#1971]
**Describe the bug**
when i try to perform a transfer on Pangaea, returns this:

Error: ChainID on node differs from received chainID: current chain id:2: invalid chain id for signer
v156f947e75: ChainID on node differs from received chainID: current chain id:2: invalid chain id for signer

i´m assuming for Pangaea network we are using: --chain-id pangaea 

**To Reproduce**
./hmy --node="https://api.s0.b.hmny.io/" transfer --from XXXX --to XXXX --from-shard 0 --to-shard 0 --amount 1 --chain-id pangaea --passphrase XXXX

**Expected behavior**
Perfom the tx

**Comment by mindstyle85** [comment]
chain id for Pangaea is testnet, so: chain-id testnet

**Comment by BrunoMarshall** [comment]
I will close this issue, pls see Mindstyle comment
Thank you
