### ISSUE TITLE
Tx issue : Transaction & "transaction-receipt" don´t appear to be reliable, specially when the transaction don´t occur

### ISSUE THREAD

**Issue by BrunoMarshall** [harmony-one/harmony#1976]
**Describe the bug**
when we perform a transaction between 2 wallet addresses, the expectation is that the transaction occur and/with the  "Transaction-receipt" confirmation.
The issue is that for some reason the transaction command is not reliable all the time, and some times we receive the transaction-receipt **but** effectively there was not transferred any tokens.

![image](https://user-images.githubusercontent.com/35432495/70324119-f1a66e80-182e-11ea-992a-b628e6c2e055.png)

Taken this for example, performing 10 transactions, only 5 really occurs ->  50%
but we receive 10 transaction-receipts.  

Same is occurring with the math wallet, some transaction don´t occur, leading to uncertainly and lack of reliability

**To Reproduce**
1. Perform 10 transaction to 10 different accounts

./hmy --node="https://api.s0.b.hmny.io/" transfer --from one1yc06ghr2p8xnl2380kpfayweguuhxdtupkhqzw --to one1q6gkzcap0uruuu8
r6sldxuu47pd4ww9w9t7tg6 --from-shard 0 --to-shard 0 --amount 10 --chain-id testnet

Record the  {"transaction receipt":"0xXXXXXXX"}
2. Check the balance on the wallets

**Expected behavior**
The expectation is that the Transaction occur, or the feedback that the transaction did not occur

**Comment by mindstyle85** [comment]
@BrunoMarshall @fxfactorial @janet-harmony i guess this issue can also be closed now

**Comment by BrunoMarshall** [comment]
Will close this issue, solved
