### ISSUE TITLE
Chrome Extension - Recover wallet asks for 12 word seed

### ISSUE THREAD

**Issue by mirrormirage0** [harmony-one/harmony#1977]
**Describe the bug**
Chrome Extension - Recover wallet - asks for 12 word seed. .hmy cli creates a 24 word seed. Can't recover wallet with 

**To Reproduce**
1. Install Chrome extension.
2. Click on Recover

**Expected behavior**
Prompt for 24 word seed phrase as given by .hmy
private key doesnt work either

**Screenshots**
![image](https://user-images.githubusercontent.com/29485946/70341431-57fdb200-186c-11ea-9931-fdcd1837a6bb.png)

**Environment (please complete the following information):**
 - OS: Any
- Chrome Browser extension for https://staking.harmony.one/extension

**Comment by BrunoMarshall** [comment]
This should be ok now, please confirm and close the issue. thanks

**Comment by davelovejoy** [comment]
Im having the same problem

**Comment by Marc6666** [comment]
I am having same issue , any update?
