### ISSUE TITLE
[Feature] market cap stats and transaction volume

### ISSUE THREAD

**Issue by flicker-harmony** [harmony-one/harmony#1984]
# Problem/limitation At Hand

Add market cap stats on block explorer backend and frontend. Should be shown at global summary above on http://explorer.testnet.harmony.one. https://coincodex.com/crypto/harmony/ this has API and needed data: 24h tx volume, market cap, supply, token price, price change. 

**Which component?**

- [ ] blockexplorer

# Proposed Solution

I will work on backend side. Yuriy on frontend side. Minh can help on both.

# Alternatives Considered

# Additional Context

**Comment by potvik** [comment]
Front: https://github.com/harmony-one/harmony-dashboard

**Comment by LeoHChen** [comment]
not needed.
