### ISSUE TITLE
rpc GetValidatorInformation is returning empty result for valid validator

### ISSUE THREAD

**Issue by rlan35** [harmony-one/harmony#2008]
I created a validator with address one1f33w8c3dupm30p4fhemy89646xw7xpxcnmy6e4

it can be seen from explorer: https://staking.harmony.one/validators/one1f33w8c3dupm30p4fhemy89646xw7xpxcnmy6e4

But the cli returns nothing for the getValidatorInformation RPC.

./hmy --node="https://api.s1.p.hmny.io" blockchain validator information one1f33w8c3dupm30p4fhemy89646xw7xpxcnmy6e4

return is {}

**Comment by fxfactorial** [comment]
I believe it is because the RPC taking too long to finish and hence context kills it, demoed to @gupadhyaya yesterday evening

**Comment by gupadhyaya** [comment]
No longer reproducible. For not existing validator, it used to return `{}`. This PR fixes that: https://github.com/harmony-one/harmony/pull/2272
