### ISSUE TITLE
Able to send tx while wallet account has been staked

### ISSUE THREAD

**Issue by sophoah** [harmony-one/harmony#2009]
**Describe the bug**
In devnet, I was able to send ONE token while the fund was supposed to be blocked through staking.

**To Reproduce**
**1) Make sure we have fund in the wallet:**
root@vmi317161:~ /hmy-devnet# ./hmy balances one15knq45tf5psjze6q65dpm4lumqhm8jny997mph
[
  {
    "shard": 0,
    "amount": 7488.0000
  },
  {
    "shard": 1,
    "amount": 0.0000
  }
]
root@vmi317161:~ /hmy-devnet

**2) Create a new validator and stake the entire fund**
root@vmi317161:~ /hmy-devnet# ./hmy staking create-validator --validator-addr one15knq45tf5psjze6q65dpm4lumqhm8jny997mph --name Soph --identity Soph --website Soph@soph.one --security-contact Soph --details "Soph the validator" --rate 0.1 --max-rate 0.9 --max-change-rate 0.05 --min-self-delegation 2 --max-total-delegation 99999999999 --bls-pubkeys 0xb3727f8a497174dba2d4859a131a79f4065fa8d18b5e51e5624bc7dcc1e39ae25b0eb5a0b9a4b25a49c9ee3d3ebf7804 --amount 7487 --chain-id devnet
Enter the bls passphrase:
{"transaction-receipt":"0x156605f7a0b05bad73195171e4c05dfe1e6a3fcd6e89c9f00132bd9fa7d2c9c3"}

**3) checking wallet again** 
root@vmi317161:~ /hmy-devnet# ./hmy balances one15knq45tf5psjze6q65dpm4lumqhm8jny997mph
[
  {
    "shard": 0,
    "amount": 7487.999960252
  },
  {
    "shard": 1,
    "amount": 0.0000
  }
]

Gas fees only deducted from the wallet, shouldn't the stake amount be blocked by sending it somewhere ? or I was hoping it would be known to be blocked by the protocol

**4) try to send token**
root@vmi317161:~ /hmy-devnet# ./hmy transfer --from one15knq45tf5psjze6q65dpm4lumqhm8jny997mph --to one1v9dq279psll5lyxmtkuv4s4xzwn7z2x3dxk445 --from-shard 0 --to-shard 0 --amount 50 --chain-id devnet
{"transaction-receipt":"0x3655af121d1e687b910c2f5973370363955c2ed601bfd3d1a866cda8917e1a0e"}
root@vmi317161:~ /hmy-devnet# ./hmy balances one1v9dq279psll5lyxmtkuv4s4xzwn7z2x3dxk445
[
  {
    "shard": 0,
    "amount": 1000050.0000
  },
  {
    "shard": 1,
    "amount": 0.0000
  }
]
root@vmi317161:~ /hmy-devnet# ./hmy balances one15knq45tf5psjze6q65dpm4lumqhm8jny997mph                                          [
  {
    "shard": 0,
    "amount": 7437.999939252
  },
  {
    "shard": 1,
    "amount": 0.0000
  }
]

**Expected behavior**
Staked token should be blocked and can't be used to transfer token

**Screenshots**
captured the staking failure errors but only the last few seemed to be from me or match the command I made
root@vmi317161:~/hmy-devnet# ./hmy failures staking --node="https://api.s0.pga.hmny.io"
{
  "id": "0",
  "jsonrpc": "2.0",
  "result": [
    {
      "directive-kind": "CreateValidator",
      "error-message": "insufficient balance to pay for gas",
      "time-at-rejection": 1576049281,
      "tx-hash-id": "0xe02045667c208f860a62008dce2266e3a314b90b1c58db54245d2e1e1a274e67"
    },
    {
      "directive-kind": "Delegate",
      "error-message": "insufficient balance to stake",
      "time-at-rejection": 1576052305,
      "tx-hash-id": "0x32ece961a3ee9fb9842bb3d56d9e1b6d9f01ff5d2254b547d2b6373199f22b55"
    },
    {
      "directive-kind": "CreateValidator",
      "error-message": "insufficient balance to pay for gas",
      "time-at-rejection": 1576062960,
      "tx-hash-id": "0xc881bb739d8041066569c585bb10bd200ed673aa437c3524fae2a88ac1b754af"
    },
    {
      "directive-kind": "CreateValidator",
      "error-message": "insufficient balance to pay for gas",
      "time-at-rejection": 1576063726,
      "tx-hash-id": "0xc881bb739d8041066569c585bb10bd200ed673aa437c3524fae2a88ac1b754af"
    },
    {
      "directive-kind": "Delegate",
      "error-message": "total delegation can not be bigger than max_total_delegation",
      "time-at-rejection": 1576065393,
      "tx-hash-id": "0x4bf8c7ac8a9e332cd888e98b6d18408ef7fe076091ba38e8510735c6ea38fcba"
    },
    {
      "directive-kind": "Delegate",
      "error-message": "total delegation can not be bigger than max_total_delegation",
      "time-at-rejection": 1576065704,
      "tx-hash-id": "0x5b68d98279a52d67caa933f40e2fcb4540e787c71e73a52ea03288f31aa4ee43"
    },
    {
      "directive-kind": "CreateValidator",
      "error-message": "staking validator already exists",
      "time-at-rejection": 1576072069,
      "tx-hash-id": "0x14f9312d46449a8960368c4522d798783929169fa3a4162f64ec4f48d381739d"
    }
  ]
}

**Environment (please complete the following information):**
 - OS: linux, ubuntu
- Go environment [ ```go env``` ]

**Additional context**

**Comment by mindstyle85** [comment]
so tldr; Soph delegated almost everything save 0,99 token to the validator with the validator creation command, and was then still able to send me 50 tokens to my address, which i received, and his balance got deducted for 50 tokens. This shouldnt have been allowed since creating validator means staking the coins meaning theyre locked?

@fxfactorial @rlan35 @astralblue

**Comment by janet-harmony** [comment]
Actually, the create-validator transaction failed and did not make it to the chain. So no money was deducted from Soph's account (except a gas fee).
```
 ./hmy --node=https://api.s0.pga.hmny.io/ blockchain transaction-by-hash 0x156605f7a0b05bad73195171e4c05dfe1e6a3fcd6e89c9f00132bd9fa7d2c9c3
{
  "id": "0",
  "jsonrpc": "2.0",
  "result": null
}
```

A validator can only be 'created' once using create-validator. If you want to stake more, you must use the `staking delegate` with `--delegator-addr <YOUR_ADDRESS>` and `--validator-addr <YOUR_ADDRESS>`.

Also, when you stake X ONE, they are locked and will NOT show up in your balance when you query for it.

**Comment by mindstyle85** [comment]
are you sure? How come then i also see my full balance even though i staked 5k for the validator (granted i was not in sync at that time but right now i am and also making bingos):

luka@ubuntu:~/devnet$ ./hmy balances --node="https://api.s0.pga.hmny.io" one1v9dq279psll5lyxmtkuv4s4xzwn7z2x3dxk445
[
  {
    "shard": 0,
    "amount": 1000049.999959988
  },
  {
    "shard": 1,
    "amount": 0.0000
  }
]


my initial balance was 1M tokens, +50 Soph sent to me - gas fee for create validator tx

so if my 5k is locked (which should be since im validating - bingos), why do i still see them in my balance too??

**Comment by sophoah** [comment]
@janet-harmony so i tried to replicate the issue, but i think devnet has some tx issue right now however, i managed to create a new validator soph2 with almost all my token and once created, they were never deducted from my wallet.  here are the logs 


**my newly created wallet that i wanna use for staking test with fund**
./hmy balances one1zd6v5z3sdu5epk4gvl3knn6jkzwh5lcmdj3m3f
[
  {
    "shard": 0,
    "amount": 10000.0000
  },
  {
    "shard": 1,
    "amount": 0.0000
  }
]

**Creation of a new validator**
./hmy --node=https://api.s0.pga.hmny.io/ staking create-validator --validator-addr one1zd6v5z3sdu5epk4gvl3knn6jkzwh5lcmdj3m3f --name Soph2 --identity Soph2 --website Soph2@harmony.one --security-contact Soph2 --details "Soph2 the validator" --rate 0.1 --max-rate 0.9 --max-change-rate 0.05 --min-self-delegation 2 --max-total-delegation 9999999999 --bls-pubkeys 0xde3fb916884fee1ab139896a42b6c4030da74ab82740a975c2aba7d1a87ce23bfab14f837461325a5b13bdca4d778e04 --amount 9995 --chain-id devnet
Enter the bls passphrase:
{"transaction-receipt":"0x00ab33b34fa1b9117e957f9953b7ecd733ab797c20b446cc4aee52adc5818712"}

**Checking the validator has been successfully added**
./hmy --node=https://api.s0.pga.hmny.io/  blockchain validator information one1zd6v5z3sdu5epk4gvl3knn6jkzwh5lcmdj3m3f
{
  "id": "0",
  "jsonrpc": "2.0",
  "result": {
    "active": true,
    "address": "one1zd6v5z3sdu5epk4gvl3knn6jkzwh5lcmdj3m3f",
    "avg_voting_power": "",
    "commission": {
      "commission_rates": {
        "max_change_rate": "0.050000000000000000",
        "max_rate": "0.900000000000000000",
        "rate": "0.100000000000000000"
      },
      "update_height": 14354
    },
    "creation_height": 14354,
    "description": {
      "details": "Soph2 the validator",
      "identity": "Soph2",
      "name": "Soph2",
      "security_contact": "Soph2",
      "website": "Soph2@harmony.one"
    },
    "max_total_delegation": 9.999999999e+27,
    "min_self_delegation": 2000000000000000000,
    "slot_pub_keys": [
      "de3fb916884fee1ab139896a42b6c4030da74ab82740a975c2aba7d1a87ce23bfab14f837461325a5b13bdca4d778e04"
    ],
    "slot_shard_ids": [
      0
    ],
    "total_effective_stake": "",
    "unbonding_height": 0,
    "uptime": ""
  }
}

**Validator has been created but fund are not blocked or still not deducted**
./hmy balances one1zd6v5z3sdu5epk4gvl3knn6jkzwh5lcmdj3m3f
[
  {
    "shard": 0,
    "amount": 9999.99995977
  },
  {
    "shard": 1,
    "amount": 0.0000
  }
]
95

wanted to tx here my account with supposingly 9995 staked token as confirmed here:

./hmy --node="https://api.s0.pga.hmny.io/" blockchain delegation by-delegator one1zd6v5z3sdu5epk4gvl3knn6jkzwh5lcmdj3m3f
root@scw-zealous-bohr:~# ./hmy --node="https://api.s0.pga.hmny.io/" blockchain delegation by-delegator one1zd6v5z3sdu5epk4gvl3knn6jkzwh5lcmdj3m3f
{
  "id": "0",
  "jsonrpc": "2.0",
  "result": [
    {
      "Undelegations": [],
      "amount": 9.995e+21,
      "delegator_address": "one1zd6v5z3sdu5epk4gvl3knn6jkzwh5lcmdj3m3f",
      "reward": 147156522000794620000,
      "validator_address": "one1zd6v5z3sdu5epk4gvl3knn6jkzwh5lcmdj3m3f"
    }
  ]
}

but as mentioned above I think there are tx are not working or stuck. Reason being i also tried to send only 2 (normally not staked token), and didn't work and tried to send again from my original wallet to that same wallet a new tx and didn't work as well
