### ISSUE TITLE
Staking dashboard shows 0 uptime for an active validator

### ISSUE THREAD

**Issue by mindstyle85** [harmony-one/harmony#2019]
**Describe the bug**
 my validator is bingoing but on the staking dashboard my uptime is 0, while some others have 95%+?
https://staking-explorer.firebaseapp.com/validators/one1v9dq279psll5lyxmtkuv4s4xzwn7z2x3dxk445

NOTE: due to further testing i currently stopped this validator node, so adding zerolog here too.

**Expected behavior**
Show how much uptime my validator node really has/had.

**Environment (please complete the following information):**
Harmony (C) 2019. harmony, version v5398-master-20191208.0-21-g37935bb2 (jenkins@ 2019-12-11T07:45:36+0000)

[zerolog-validator-93.103.119.129-9000.zip](https://github.com/harmony-one/harmony/files/3957576/zerolog-validator-93.103.119.129-9000.zip)

**Comment by rlan35** [comment]
This validator did have block rewards: one1v9dq279psll5lyxmtkuv4s4xzwn7z2x3dxk445. So it should be an RPC issue on the getValidatorInformation(). @fxfactorial is fixing issues on this RPC.

**Comment by sophoah** [comment]
just to report that I also have the same issue with my new validator on shard 1, didn't had that issue on shard 0

**Comment by mindstyle85** [comment]
yes, noting that the validator above on the original post with 0 uptime was on shard 1, my currently active one is on shard 0 and looks like uptime is ok (99%+)

**Comment by mindstyle85** [comment]
@rlan35 @fxfactorial 

bump, current staking dashboard still has 0 uptime for validator
