### ISSUE TITLE
Claiming reward through staking explorer doesn’t show a correct message

### ISSUE THREAD

**Issue by sophoah** [harmony-one/harmony#2026]
**Describe the bug**
Claiming reward through staking explorer doesn’t show a correct message

**To Reproduce**
1 claim the staking reward via the staking explorer

**Expected behavior**

**Screenshots**
https://imgur.com/a/LADDmaS

**Environment (please complete the following information):**
 - OS: [win, chrome]

**Additional context**

**Comment by yelllowsin** [comment]
@sophoah I feel this issue can be closed as there is a duplicated and newer here with the same issue here #2225 . Feel free to reopen if i did something wrong.
