### ISSUE TITLE
hmy_getTransactionsHistory available with common api endpoint

### ISSUE THREAD

**Issue by flicker-harmony** [harmony-one/harmony#2027]
## Summary

Right now fetching hmy_getTransactionsHistory by api.s0.p.hmny.io doesn't return results because this api call only available for explorer nodes. It was done to spare storage for normal nodes so that they don't need to store address txs index. But of course it's confusing. Best solution would be to make redirection from common endpoint to explorer endpoint if the call using hmy_getTransactionsHistory.

## Current Design

hmy_getTransactionsHistory only available for explorer nodes.

## Problems

Confusing for API users that they need to use additional endpoint for specific call and we are exposing explorer node API.

## Proposal

Either change implementation, but it's really not desirable because of inefficiency and possible additional storage use if we want that to be for all nodes. Or combine API endpoints to single one with load balancing, additional server or smth like that.

**Comment by LeoHChen** [comment]
There are a few challenges here.

1) to support hmy_getTransactionHistory will take extra disk space, I assume (not measured yet). So it is wise to support it on every single nodes.

2) if we add additional explorer nodes, just to be the RPC API end points, are those nodes able to handle all the rpc calls.  This is a question and needs to be figured out.

**Comment by flicker-harmony** [comment]
@LeoHChen additional explorer nodes can do all api calls maybe except submit transaction and rpc connected to account which requires signing

**Comment by LeoHChen** [comment]
then we can use the explorer node as the generic rpc end points though.  The RPC end points have to be able to submit transactions. 

What do you mean by rpc connected to account which requires signing? The transaction has to signed by client anyway.

**Comment by LeoHChen** [comment]
The plan is to use load balancer of a few explorer node sas the RPC end points. @AndyBoWu

**Comment by LeoHChen** [comment]
The mitigation of this issue will be tracked in an op ticket. https://github.com/harmony-one/harmony-ops/issues/312
