### ISSUE TITLE
[Feature] RPC API upgrades

### ISSUE THREAD

**Issue by flicker-harmony** [harmony-one/harmony#2033]
# Problem/limitation At Hand

1. Right now api.s0.p.hmny.io (s1, s2, s3, etc and for other networks) don't support hmy_getTransactionsHistory, but explorer nodes like e0.t.hmny.io and for others shards/networks
support that and support all other hmy rpc methods except https://github.com/harmony-one/harmony/blob/master/internal/hmyapi/private_account.go which involves transaction signing with accounts password. But private account method shouldn't be allowed to use for public APIs anyway - you can't send your pass to an arbitrary node or even our explorer nodes.

2. Some external partners like TrustWallet want us to switch from 0x format in return values for all RPC structs to decimals if possible. 

**Which component?**

- [ ] rpc
- [ ] block-explorer
- [ ] staking-explorer
- [ ] go-sdk
- [ ] test automation
- [ ] harmony-sdk
- [ ] deployment

# Proposed Solution

1. Solution for that is to just make explorer nodes as public endpoints but make load balancing and protection against attacks and wrap direct endpoints with api.s0.p.hmny.io endpoint. 
  a) Update docs, API endpoints for apps and notify partners
  b) @AndyBoWu @john-harmony can help and setup api endpoints to block explorer nodes securely
  c) @Daniel-VDM or P-OPS can test if all APIs after that (except private_account.go APIs) are available and return correct results
  d) Update wiki and guides and notify partners (biz or any engineer can do that).

2. It will require adjusting RPC APIs and other apps for that like staking explorer, block explorer, go-sdk, harmony-sdk, harmony docs and of course make testing for that and for and notifying partners for their apps.
   a) It should involve me on RPC
   b) @potvik for block/staking explorer frontends
   c) @mikedoan and me for block explorer, staking explorer
   d) @gupadhyaya for harmony-sdk
   e) @fxfactorial or @Daniel-VDM for go-sdk
   f) Test that to return correct results for all changed methods @Daniel-VDM and P-OPS
   g) update wiki/guides when its done, notify partners (anyone, biz or P-OPS or @Daniel-VDM)

We can also contact and ask P-OPS team for proper testing. 

# Timeline

We will starting working on it next month after vacation. We can make adjustments and discussions from now. Delivery shouldn't take long from one week to two weeks, but we should consider pessimistic scenarios if bugs/issues are found or engineers who own components aren't available to make upgrades because of others tasks

Please everyone who was added as assignee give your availability for next month if you'll be able to adjust your components and sync on progress to check that upgrade working full-stack and nothing is crashed. 

# Alternatives Considered

# Additional Context

**Comment by LeoHChen** [comment]
old issue.
