### ISSUE TITLE
Failed to transfer money in a local testnet

### ISSUE THREAD

**Issue by samohyes** [harmony-one/harmony#2043]
Hi , I set up a local testnet according to the readme instructions. And run with "./test/debug.sh".
But When I tried to send cross shard transaction it gave me this error.

> ./bin/wallet -p local transfer --from one103q7qe5t2505lypvltkqtddaef5tzfxwsse4z7 --to one1r4zyyjqrulf935a479sgqlpa78kz7zlcg2jfen --amount 2 --shardID 0 --toShardID 1
Using local profile for wallet
Cannot read passphrase: invalid passphrase reading method ""

Can anyone help me figure out what I did wrong here?

**Comment by mindstyle85** [comment]
you didnt add --passphrase at the end of your command, eg; --passphrase thisismypassword

**Comment by samohyes** [comment]
Thanks. But I tried it give me this error.

./bin/wallet -p local transfer --from one103q7qe5t2505lypvltkqtddaef5tzfxwsse4z7 --to one1r4zyyjqrulf935a479sgqlpa78kz7zlcg2jfen --amount 2 --shardID 0 --toShardID 1 --passphrase thisismypassword
Using local profile for wallet
flag provided but not defined: -passphrase
Usage of transfer:
  -amount float
    	Specify the amount to transfer
  -from string
    	Specify the sender account address or index (default "0")
  -gasPrice uint
    	Specify the gas price amount. Unit is Nano. (default 1)
  -inputData string
    	Base64-encoded input data to embed in the transaction
  -pass string
    	Passphrase of the sender's private key
  -shardID int
    	Specify the shard ID for the transfer (default -1)
  -to string
    	Specify the receiver account
  -toShardID int
    	Specify the destination shard ID for the transfer (default -1)
  -waitThenBal

**Comment by mindstyle85** [comment]
it would be better if you used hmy for this anyways, as wallet.sh is deprecated and things might not work with the newer versions:

curl -LO https://harmony.one/hmycli && mv hmycli hmy && chmod a+x hmy
