### ISSUE TITLE
[networking] two leaders reported on watchdog

### ISSUE THREAD

**Issue by LeoHChen** [harmony-one/harmony#2044]
**Describe the bug**

A leader change failed on shard0 on mainnet. http://watchdog.hmny.io/report-mainnet reports two leaders.  One of them hit the "rx overrun" issue. Node is: 3.112.219.248

```
{"level":"warn","port":"9000","ip":"3.112.219.248","error":"rx overrun","sender":"QmXhdA7t5EiMrzobrKtjKfmnzHWCcRtpSKH1wpT6hmWrYD","caller":"/home/leochen/go/src/github.com/harmony-one/harmony/node/node_handler.go:62","time":"2019-12-31T21:16:54.199257221Z","message":"cannot enqueue incoming message for processing"}
{"level":"warn","port":"9000","ip":"3.112.219.248","error":"rx overrun","sender":"QmRXD9XvZGgkzU9RFgkNr49AYW5DPnoFrdUumKwNiM3QGN","caller":"/home/leochen/go/src/github.com/harmony-one/harmony/node/node_handler.go:62","time":"2019-12-31T21:16:54.206721021Z","message":"cannot enqueue incoming message for processing"}
{"level":"warn","port":"9000","ip":"3.112.219.248","error":"rx overrun","sender":"QmX8fE15MosqXSswd6VrXLrpLS38z7R4djkNLB2f91qNkH","caller":"/home/leochen/go/src/github.com/harmony-one/harmony/node/node_handler.go:62","time":"2019-12-31T21:16:54.227252028Z","message":"cannot enqueue incoming message for processing"}
{"level":"warn","port":"9000","ip":"3.112.219.248","error":"rx overrun","sender":"QmUfQYEqnYFeAnmR5v16J48hNf2aPiEXrxF8ycwjjucQYH","caller":"/home/leochen/go/src/github.com/harmony-one/harmony/node/node_handler.go:62","time":"2019-12-31T21:16:54.23494016Z","message":"cannot enqueue incoming message for processing"}
{"level":"warn","port":"9000","ip":"3.112.219.248","error":"rx overrun","sender":"QmTLV2J1FL6kQ5Y6toZFHo5NKnNgW65thuh6H3d3tVRLZz","caller":"/home/leochen/go/src/github.com/harmony-one/harmony/node/node_handler.go:62","time":"2019-12-31T21:16:54.276531525Z","message":"cannot enqueue incoming message for processing"}
{"level":"warn","port":"9000","ip":"3.112.219.248","error":"rx overrun","sender":"QmeeCNWUdZghjPBgeppz44okMGWRx9A9gSiBig4iyAYM15","caller":"/home/leochen/go/src/github.com/harmony-one/harmony/node/node_handler.go:62","time":"2019-12-31T21:16:54.529838851Z","message":"cannot enqueue incoming message for processing"}
{"level":"debug","port":"9000","ip":"3.112.219.248","caller":"/home/leochen/go/src/github.com/harmony-one/harmony/node/node_handler.go:120","time":"2019-12-31T21:16:54.538869948Z","message":"NET: received message: Node/Block"}
{"level":"debug","port":"9000","ip":"3.112.219.248","caller":"/home/leochen/go/src/github.com/harmony-one/harmony/node/node_handler.go:124","time":"2019-12-31T21:16:54.538908729Z","message":"NET: received message: Node/Sync"}
{"level":"debug","port":"9000","ip":"3.112.219.248","caller":"/home/leochen/go/src/github.com/harmony-one/harmony/node/node_handler.go:120","time":"2019-12-31T21:16:54.539001218Z","message":"NET: received message: Node/Block"}
```

**To Reproduce**
1. Check out code with "sha1" commit
2. Build
3. run local test using "...." commands

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: [Linux, MacOS]
- Go environment [ ```go env``` ]

**Additional context**

**Comment by LeoHChen** [comment]
All the logs of this node are in s3://harmony-benchmark/logs/mainnet/3.112.219.248/

**Comment by rlan35** [comment]
initial investigation shows that the select clause is stuck in the consensus.Start function: https://github.com/harmony-one/harmony/blob/master/consensus/consensus_v2.go#L1111. The evidence is that no "[ConsensusMainLoop] Received Proposed New Block!" message is seen after "=========Successfully Proposed New Block==========", basically showing that the blockChannel doesn't dequeue.

The other normal consensus is very likely failed to being processed due to the same select clause being stuck. But no clear root cause is found so far. Further evidence is needed.

**Comment by denniswon** [comment]
<img width="374" alt="Screen Shot 2020-01-13 at 1 16 03 PM" src="https://user-images.githubusercontent.com/3278577/72292783-f832bd80-3606-11ea-9f63-f87908b97922.png">

**Comment by rlan35** [comment]
Same issue on the leader: {"level":"warn","port":"9000","ip":"3.112.219.248","error":"rx overrun","sender":"QmZrVpAigejPrkuQc444HTsz9Yh4jAFtr8jYxi2W7uRERo","caller":"/home/leochen/go/src/github.com/harmony-one/harmony/node/node_handler.go:62","time":"2020-01-13T21:24:10.678229024Z","message":"cannot enqueue incoming message for processing"}

This PR added more log to trouble shoot the issue: https://github.com/harmony-one/harmony/pull/2076

**Comment by janet-harmony** [comment]
`52.221.194.101` is out of sync on Mainnet Shard 1.
<img width="405" alt="Screen Shot 2020-02-10 at 12 19 40 PM" src="https://user-images.githubusercontent.com/56005637/74186809-2b656e00-4c00-11ea-97ba-fa327ac7724f.png">
<img width="1653" alt="Screen Shot 2020-02-10 at 12 21 11 PM" src="https://user-images.githubusercontent.com/56005637/74186821-33251280-4c00-11ea-8cfa-d951ac078613.png">

Same issue in the logs.
```
{"level":"warn","port":"9000","ip":"52.221.194.101","error":"rx overrun","sender":"QmejVf4SB23X89fXP455gdJkux8PdhkgN2tQ6JhbqKWrjd","caller":"/mnt/jenkins/workspace/harmony-release/harmony/node/node_handler.go:62","time":"2020-02-10T20:22:44.510672413Z","message":"cannot enqueue incoming message for processing"}
```

**Comment by janet-harmony** [comment]
Watchdog reporting 2 leaders. `13.52.219.208` is out of sync.

<img width="394" alt="Screen Shot 2020-03-24 at 1 28 11 AM" src="https://user-images.githubusercontent.com/56005637/77404299-bfcdff00-6d6e-11ea-8c05-8084418008c8.png">

<img width="1649" alt="Screen Shot 2020-03-24 at 1 18 52 AM" src="https://user-images.githubusercontent.com/56005637/77404250-acbb2f00-6d6e-11ea-82d8-a8e6453f47f4.png">

```
{"level":"warn","port":"9000","ip":"13.52.219.208","error":"rx overrun","sender":"QmPu3a6SpMugrLZnDowwQtjuXsLQNWg11aLW9QivPz8Uhf","caller":"/mnt/jenkins/workspace/harmony-release/harmony/node/node_handler.go:62","time":"2020-03-24T08:26:22.474590777Z","message":"cannot enqueue incoming message for processing"}
```

**Comment by janet-harmony** [comment]
<img width="403" alt="Screen Shot 2020-03-24 at 3 13 34 AM" src="https://user-images.githubusercontent.com/56005637/77413990-85b82980-6d7d-11ea-8d01-f60f5925d913.png">

`18.144.14.99` out of sync. STN Shard 1.

```
{"level":"warn","port":"9000","ip":"18.144.14.99","error":"rx overrun","sender":"QmXxut8piPaSCP8a9R9Xw6qaGPASAfC4LWQp8nr8V9JQ8J","caller":"/home/ec2-user/JL/harmony/node/node_handler.go:62","time":"2020-03-24T10:12:28.300850419Z","message":"cannot enqueue incoming message for processing"}
{"level":"warn","port":"9000","ip":"18.144.14.99","error":"rx overrun","sender":"QmRKjMVVq2M9TSvNtz391gTE5Q2jaDFg3yk6Zw4JZnWPPs","caller":"/home/ec2-user/JL/harmony/node/node_handler.go:62","time":"2020-03-24T10:12:28.320540176Z","message":"cannot enqueue incoming message for processing"}
{"level":"warn","port":"9000","ip":"18.144.14.99","error":"rx overrun","sender":"QmU7ueqPM2Ajd4hFH5F81XhAPtDLgoz7aZzdjEgFofaBc9","caller":"/home/ec2-user/JL/harmony/node/node_handler.go:62","time":"2020-03-24T10:12:28.323892738Z","message":"cannot enqueue incoming message for processing"}
{"level":"warn","port":"9000","ip":"18.144.14.99","error":"rx overrun","sender":"QmRKjMVVq2M9TSvNtz391gTE5Q2jaDFg3yk6Zw4JZnWPPs","caller":"/home/ec2-user/JL/harmony/node/node_handler.go:62","time":"2020-03-24T10:12:28.324861705Z","message":"cannot enqueue incoming message for processing"}
```

**Comment by LeoHChen** [comment]
![image](https://user-images.githubusercontent.com/4513927/77513438-3c75e180-6e32-11ea-9a77-aba5449c0305.png)

**Comment by AndyBoWu** [comment]
same error on shard 2, rebooted the node

`
{"level":"warn","port":"9000","ip":"13.231.200.234","error":"rx overrun","sender":"QmVGXmHm3N69KaR7oiYxT7CxXesaUEBdwPQusL2qBa6ZmM","caller":"/mnt/jenkins/workspace/harmony-release/harmony/node/node_handler.go:62","time":"2020-03-31T22:29:23.459618593Z","message":"cannot enqueue incoming message for processing"}
`
