### ISSUE TITLE
Network split

### ISSUE THREAD

**Issue by harmony-ek** [harmony-one/harmony#2053]
## Summary

Malicious internet service provider (ISP) may partition the blockchain network into groups or delays block propagation.  This may lead to stalled consensus.

## Current Design

Node discovery mechanism currently does not attempt to diversify connectivity by remaining agnostic of the remote location of the node.

## Problems

Over time, a node may end up being connected to a topologically concentrated neighbors, especially after multiple transient inter-region/inter-network connectivity failures.  These failures may be induced by attackers which can directly/indirectly control ISPs that serve connectivity among nodes.  In particular, these attackers may be ISPs themselves, operating maliciously or subverted/subpoenaed to do so.

## Proposal

A node can be made aware of where other discovered nodes reside, e.g. using GeoIP, so that it maintains connectivity to diverse set of IP addresses.  For example, Ethereum has a heuristic of favoring new connections in different IP subnets.

**Comment by LeoHChen** [comment]
potential improvement on the discovery algorithm, we are using Kademila DHT for peer discovery now.
