### ISSUE TITLE
Sending 1 atto returns 0x0 (12 decimals instead of 18)

### ISSUE THREAD

**Issue by mindstyle85** [harmony-one/harmony#2057]
## Summary

Sending an atto amount seems to return a successfull tx, but all query options show amount as 0x0 (12 zeroes instead of 18)

./hmy --node="https://api.s0.pga.hmny.io" transfer --from one1pvyt28lp8fu4wfqvynulvsqaqu2xqnqqzplkyn --to one1al7vdj2h9xkfjdnwpzrss0m58nt5rz3mjtapu2 --from-shard 0 --to-shard 0 --amount 0.000000000000000001 --chain-id devnet

HASH: 0x2fd2cf6fcdd73fdf6f337a9c69134f5789be82f485d5440e31723b24eb3fc1d7

Query results:
./hmy blockchain transaction-by-hash 0x2fd2cf6fcdd73fdf6f337a9c69134f5789be82f485d5440e31723b24eb3fc1d7 --node="https://api.s0.pga.hmny.io"
{
  "id": "0",
  "jsonrpc": "2.0",
  "result": {
    "blockHash": "0x0cc2e0b9baf81b94d098a56cf11d2adb0af0eb0969e95d6373ebf5e43db4c34b",
    "blockNumber": "0x58d",
    "from": "one1pvyt28lp8fu4wfqvynulvsqaqu2xqnqqzplkyn",
    "gas": "0x5208",
    "gasPrice": "0x3b9aca00",
    "hash": "0x2fd2cf6fcdd73fdf6f337a9c69134f5789be82f485d5440e31723b24eb3fc1d7",
    "input": "0x",
    "nonce": "0x2",
    "r": "0x6c58ea6907e4e8b5c645546d0831f7135c0fe072f5cdb6a1a31587ff3a92a610",
    "s": "0x23fbc2190b5e6e8960ae54f250fd14646d92571b4ba396fb8cd0d57e6cd89612",
    "shardID": 0,
    "timestamp": "0x5e17aca1",
    "to": "one1v9dq279psll5lyxmtkuv4s4xzwn7z2x3dxk445",
    "toShardID": 0,
    "transactionIndex": "0x0",
    "v": "0x2a",
    "value": "**0x0**"
  }

curl --location --request POST 'https://api.s0.pga.hmny.io' --header 'Content-Type: application/json' --data-raw '{"jsonrpc": "2.0","method": "hmy_getTransactionByHash","params": ["0x2fd2cf6fcdd73fdf6f337a9c69134f5789be82f485d5440e31723b24eb3fc1d7"],"id": 1}'
{"jsonrpc":"2.0","id":1,"result":{"blockHash":"0x0cc2e0b9baf81b94d098a56cf11d2adb0af0eb0969e95d6373ebf5e43db4c34b","blockNumber":"0x58d","from":"one1pvyt28lp8fu4wfqvynulvsqaqu2xqnqqzplkyn","timestamp":"0x5e17aca1","gas":"0x5208","gasPrice":"0x3b9aca00","hash":"0x2fd2cf6fcdd73fdf6f337a9c69134f5789be82f485d5440e31723b24eb3fc1d7","input":"0x","nonce":"0x2","to":"one1v9dq279psll5lyxmtkuv4s4xzwn7z2x3dxk445","transactionIndex":"0x0",**"value":"0x0"**,"shardID":0,"toShardID":0,"v":"0x2a","r":"0x6c58ea6907e4e8b5c645546d0831f7135c0fe072f5cdb6a1a31587ff3a92a610","s":"0x23fbc2190b5e6e8960ae54f250fd14646d92571b4ba396fb8cd0d57e6cd89612"}}

## Current Design

looks like all outputs are limited to 12 decimals (in hex)?

**Comment by flicker-harmony** [comment]
Deeper issue, hmy api just forwards tx.Value() to output, in my formatting PRs it will not change its format from decimal to 0x.
Balance doesn't get changed after sending  0.000000000001, but it also just forwards the balance number to output. 
<img width="1057" alt="Screenshot 2020-01-10 at 08 27 16" src="https://user-images.githubusercontent.com/52401354/72128533-4b490e00-3384-11ea-8af9-b379d53c1b29.png">
<img width="1163" alt="Screenshot 2020-01-10 at 08 27 50" src="https://user-images.githubusercontent.com/52401354/72128534-4be1a480-3384-11ea-8f39-e44a4da7b57b.png">
![Uploading Screenshot 2020-01-10 at 08.34.18.png…]()

**Comment by flicker-harmony** [comment]
Maybe, it's because *big.Int doesn't have expected behaviour?

**Comment by mindstyle85** [comment]
> Maybe, it's because *big.Int doesn't have expected behaviour?

thats odd, you got 0 as return while i got 0 too, but in the 0x0 format (while yours is 0x)

**Comment by flicker-harmony** [comment]
@mindstyle85 that's the same, I'm on my pr branch that changes 0x format to decimal

**Comment by flicker-harmony** [comment]
https://github.com/harmony-one/harmony/blob/master/cmd/client/wallet/main.go#L766 fix this line, it's incorrect, if amount is very small (10^-16) amountBigInt is 0 because of int64 round amount * denominations.Nano.

**Comment by Daniel-VDM** [comment]
I was able to do a transfer of 1e-18 using math wallet and got the correct value back (on tesnet). Confirming that it's just the CLI / Wallet issue. 

![image](https://user-images.githubusercontent.com/31291913/72209563-a7835f00-3464-11ea-9645-edd85a5df51c.png)

**Comment by mindstyle85** [comment]
This still seems to be an issue with CLI (this time i get value of 0x1 which is 1), and also no way of checking balance since it doesnt show attos in CLI:

./hmy transfer --node="https://api.s0.pga.hmny.io" --from one16eqzc5jqp62vwgeuz9vlavh0pdr7gx323gw98m --to one1v9dq279psll5lyxmtkuv4s4xzwn7z2x3dxk445 --from-shard 0 --to-shard 1 --amount 0.000000000000000001 --chain-id devnet
{"transaction-receipt":"0x91485fa122fd8943a92bc8e5786a2f64274a582cf005020b05b268ff0e82cbac"}


{
  "id": "0",
  "jsonrpc": "2.0",
  "result": {
    "blockHash": "0xb33e27c16adc966c314af42710715012ae255da576bda4f0382069a4941d322a",
    "blockNumber": "0x432",
    "from": "one16eqzc5jqp62vwgeuz9vlavh0pdr7gx323gw98m",
    "gas": "0x5208",
    "gasPrice": "0x5208",
    "hash": "0x91485fa122fd8943a92bc8e5786a2f64274a582cf005020b05b268ff0e82cbac",
    "input": "0x",
    "nonce": "0x2",
    "r": "0xf0b49510cba85dcb1fd303f6a65dcb3c6f1c3b36ae6dea97f18097f5e713d44f",
    "s": "0x4e29f74015c14a7439cdc071be6b4cd878762e7ee410812b81b8dfdc852e9355",
    "shardID": 0,
    "timestamp": "0x5e1f8b0a",
    "to": "one1v9dq279psll5lyxmtkuv4s4xzwn7z2x3dxk445",
    "toShardID": 1,
    "transactionIndex": "0x2",
    "v": "0x2a",
    "value": "0x1"
  }

**Comment by LeoHChen** [comment]
@janet-harmony , please update in the ticket. @mindstyle85 , you may need to download the latest hmycli.

**Comment by mindstyle85** [comment]
@LeoHChen actually this is my mistake, value of 0x1 is not 1 right since these are not whole numbers but wei/gwei?

**Comment by janet-harmony** [comment]
@mindstyle85 The RPC return for value is in Atto (gwei).

**Comment by mindstyle85** [comment]
ok, 2 confirmed it works so closing this now
