### ISSUE TITLE
Fails to commit blocks to explorer storage

### ISSUE THREAD

**Issue by flicker-harmony** [harmony-one/harmony#2058]
**Describe the bug**
Blocks don't get stored in explorer storage which confirms why tx history isn't working again. When running localnet in the zerolog of explorer node I can see only node_explorer.go:63","time":"2020-01-10T12:23:49.618222+03:00","message":"[Explorer] Failed to verify the multi signature for commit phase"} without commit or adding block messages which happen when block is correctly added.

**To Reproduce**
1. Check out code with "sha1" commit
2. Build
3. run local test using "...." commands

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: [Linux, MacOS]
- Go environment [ ```go env``` ]

**Additional context**

**Comment by LeoHChen** [comment]
Please confirm it is on s3 branch.  We will release on s3 for token swap

**Comment by flicker-harmony** [comment]
Checked, it works for s3 and explorer blocks are stored, yet we should consider this as master issue.
<img width="1014" alt="Screenshot 2020-01-15 at 23 00 10" src="https://user-images.githubusercontent.com/52401354/72466877-d134e100-37ea-11ea-931f-018c1284a2fd.png">

**Comment by LeoHChen** [comment]
Got it.  Then we can take this ticket off the token transfer project. I'll add it to open staking project.

**Comment by rlan35** [comment]
Tested on s3 locally, didn't see the issue. @flicker-harmony can you test with s3 code again?
