### ISSUE TITLE
gas fee for transaction

### ISSUE THREAD

**Issue by LeoHChen** [harmony-one/harmony#2061]
How do we calculate and deduct the gas fee from token transaction?  

To test it properly, we need to have a scenario of not enough gas fee in transfer, such as 1 Atto.

**Comment by LeoHChen** [comment]
Please cherry-pick the change of txpool from master to s3 branch.

**Comment by mindstyle85** [comment]
also, note that it seems currently the explorer does not show gas amount (its 0), while if i query a tx, i see gas used and gas price
