### ISSUE TITLE
Wrong error message if amount is way too large

### ISSUE THREAD

**Issue by mindstyle85** [harmony-one/harmony#2062]
**Describe the bug**
looks like if you write in big enough number (can vary), it will always respond with the number 9223372036.854776

**To Reproduce**

./hmy --node="https://api.s0.pga.hmny.io" transfer --from one1pvyt28lp8fu4wfqvynulvsqaqu2xqnqqzplkyn --to one1pvyt28lp8fu4wfqvynulvsqaqu2xqnqqzplkyn --from-shard 0 --to-shard 1 --amount 100000000000000000000 --chain-id devnet

Error: current balance of 488.999853 is not enough for the requested transfer 9223372036.854776
v186a546c34: current balance of 488.999853 is not enough for the requested transfer 9223372036.854776

**Comment by janet-harmony** [comment]
Issue should be fixed in this PR: https://github.com/harmony-one/go-sdk/pull/106
@mindstyle85 Can you download the newest CLI & try again?

**Comment by mindstyle85** [comment]
i dont think it is, using the newest hmy from about 30min ago:

Error: insufficient balance of 9997999999951490000000.000000000000000000 for the requested transfer of 10000000000000000000000000000000000000000000000000000000000002100000.000000000000000000
v20283d3b57: insufficient balance of 9997999999951490000000.000000000000000000 for the requested transfer of 10000000000000000000000000000000000000000000000000000000000002100000.000000000000000000

**Comment by mindstyle85** [comment]
above output is fine, sorted it with @janet-harmony
