### ISSUE TITLE
It's possible to send transactions without a gas cost

### ISSUE THREAD

**Issue by SebastianJ** [harmony-one/harmony#2067]
**Describe the bug**
It seems it's possible to send transactions without any gas fees at all.

While writing my [tx tester tool](https://github.com/SebastianJ/harmony-tx-tests) I experimented with setting the gas to 0.

Here's for example a wallet that receives 1 token and sends back exactly 1 token:
[https://explorer.testnet.harmony.one/#/address/one1wcl08vp25w74x0samsc309r2s7zcecd4kuxgn6](https://explorer.testnet.harmony.one/#/address/one1uj8y426q7w8ufmvuqv0pzf7399uh9tvgnxuaqt)

If you [lookup the tx that](https://explorer.testnet.harmony.one/#/tx/0xc358d79f0b6af99a83ac7e6cb04ad17d3ec39f67f454711ce92943cdd4e0ec3c) sends back the 1 token (without gas cost) using hmy it looks like this:

```
$ ./hmy --node="https://api.s0.pga.hmny.io" blockchain transaction-by-hash 0xc358d79f0b6af99a83ac7e6cb04ad17d3ec39f67f454711ce92943cdd4e0ec3c
{
  "id": "0",
  "jsonrpc": "2.0",
  "result": {
    "blockHash": "0x759867af7bbeac04fb57dbaa6342262f4c6377b708e885f981de9d37aa675c98",
    "blockNumber": "0x458f",
    "from": "one1uj8y426q7w8ufmvuqv0pzf7399uh9tvgnxuaqt",
    "gas": "0xcf08",
    "gasPrice": "0x0",
    "hash": "0xc358d79f0b6af99a83ac7e6cb04ad17d3ec39f67f454711ce92943cdd4e0ec3c",
    "input": "0x",
    "nonce": "0x0",
    "r": "0xfbf0d3ab45f223f809dbddd46ff144d8a80ae99104eb921759b305e389eedf8a",
    "s": "0x5415c0bd9ca56051664e54b9be3a7eb75178294cf3c9d6cdb99f1a185ae75a16",
    "shardID": 0,
    "timestamp": "0x5e19c51d",
    "to": "one1sps9axc6tfcxxt0hk78qqzy5jddwspa6f0pr6x",
    "toShardID": 0,
    "transactionIndex": "0x1",
    "v": "0x2a",
    "value": "0xde0b6b3a7640000"
  }
}
```

`gasPrice` is set to `0x0 = 0` - so no gas was used for the transaction (which is also evident since I could send back exactly 1 token which was the wallet's entire balance).

If I send a similar transaction (sending 1 token from a wallet with exactly 1 token) using hmy (and without specifying `--gas-price 0`) the transaction won't complete because there's not enough gas, e.g:

```
$ ./hmy --node="https://api.s0.pga.hmny.io" transfer --from one1wcl08vp25w74x0samsc309r2s7zcecd4kuxgn6 --from-shard 0 --to one13j3zvm7xanmzt3752gzr0rpkq97m866x4qee3g --to-shard 0 --amount 1 --chain-id devnet --passphrase "" --wait-for-confirm 60
null
```

But if I specifically force hmy to set gas-price to 0 it works:
```
$ ./hmy --node="https://api.s0.pga.hmny.io" transfer --from one1wcl08vp25w74x0samsc309r2s7zcecd4kuxgn6 --from-shard 0 --to one13j3zvm7xanmzt3752gzr0rpkq97m866x4qee3g --to-shard 0 --amount 1 --chain-id devnet --passphrase "" --wait-for-confirm 60 --gas-price 0
{
  "id": "12",
  "jsonrpc": "2.0",
  "result": {
    "blockHash": "0xf86e938633ce6a6f855dd91db43ed04b27ecc41a8849f93d2b09a3af8aae7362",
    "blockNumber": "0x4682",
    "contractAddress": null,
    "cumulativeGasUsed": "0x5208",
    "from": "one1wcl08vp25w74x0samsc309r2s7zcecd4kuxgn6",
    "gasUsed": "0x5208",
    "logs": [],
    "logsBloom": "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
    "shardID": 0,
    "status": "0x1",
    "to": "one13j3zvm7xanmzt3752gzr0rpkq97m866x4qee3g",
    "transactionHash": "0x286262fa4b53e7d8d30df89be424493dc78410f778a48cf997ace18727606cc9",
    "transactionIndex": "0x0"
  }
}
```

And [looking up the tx](https://explorer.testnet.harmony.one/#/tx/0x286262fa4b53e7d8d30df89be424493dc78410f778a48cf997ace18727606cc9) using transaction-by-hash:

```
$ ./hmy --node="https://api.s0.pga.hmny.io" blockchain transaction-by-hash 0x286262fa4b53e7d8d30df89be424493dc78410f778a48cf997ace18727606cc9
{
  "id": "0",
  "jsonrpc": "2.0",
  "result": {
    "blockHash": "0xf86e938633ce6a6f855dd91db43ed04b27ecc41a8849f93d2b09a3af8aae7362",
    "blockNumber": "0x4682",
    "from": "one1wcl08vp25w74x0samsc309r2s7zcecd4kuxgn6",
    "gas": "0x5208",
    "gasPrice": "0x0",
    "hash": "0x286262fa4b53e7d8d30df89be424493dc78410f778a48cf997ace18727606cc9",
    "input": "0x",
    "nonce": "0x0",
    "r": "0xb11b453cca04a8a1d4a2f4c6578cfec37c59acc95b9196de1de427f861d3dd8c",
    "s": "0x59806520b44932ff6d0cab2be5daa721c99217c628ef820f026bf443fd98f184",
    "shardID": 0,
    "timestamp": "0x5e19cd20",
    "to": "one13j3zvm7xanmzt3752gzr0rpkq97m866x4qee3g",
    "toShardID": 0,
    "transactionIndex": "0x0",
    "v": "0x29",
    "value": "0xde0b6b3a7640000"
  }
}
```

`gasPrice` is yet again set to `0x0 = 0` and the transaction is successful.

If this isn't intentional by design - shouldn't this be validated both in hmy as well as in the nodes' respective tx pools (i.e. dropping txs without proper gas set)?

**To Reproduce**
1. Send exactly 1 token (or another amount that's easy to remember) to a new wallet
2. Send the 1 token from the newly created wallet somewhere, use `--gas-price 0` as an argument for the hmy transfer command - e.g: `./hmy --node="https://api.s0.pga.hmny.io" transfer --from one1wcl08vp25w74x0samsc309r2s7zcecd4kuxgn6 --from-shard 0 --to one13j3zvm7xanmzt3752gzr0rpkq97m866x4qee3g --to-shard 0 --amount 1 --chain-id devnet --passphrase "" --wait-for-confirm 60 --gas-price 0`
3. Transaction is successful - no gas is charged

**Expected behavior**
If this isn't intentional by design 0 gas transactions shouldn't be allowed.

**Environment (please complete the following information):**
 - OS: MacOS Catalina 10.15.2
- Go: 1.12

**Comment by LeoHChen** [comment]
please retest on the latest testnet.  we have enabled gasfee in tx.

**Comment by LeoHChen** [comment]
close the ticket as we have enabled gas fee on testnet.  Feel free to re-open it if the issue surfaces again.
