### ISSUE TITLE
Missing the message: not enough gas fee for the transactions in same / multiple account

### ISSUE THREAD

**Issue by BrunoMarshall** [harmony-one/harmony#2071]
**Describe the bug**
the "not enough gas fee" message is not working, trying to do a transation i recieve a transaction-receipt that can´t be found in the explorer. 
The transaction did not occur, is expected that, but is missing the message : not enough gas fee for the transactions 

**To Reproduce**
1. Have an account with 0.999979 token
2. Transfer 0.999979 token to other wallet or same
./hmy --node=https://api.s0.pga.hmny.io/ transfer --from one1wa07sdquyurrtsqq3t9uae2txwezn9unt7veet --to one1wa07sdquyurrtsqq3t9uae2txwezn9unt7veet --from-shard 0 --to-shard 0 --amount 0.999979 --chain-id devnet

3- check the transaction-receipt on the explorer, or check the balance afterwards

**Expected behavior**
is expected the message : not enough gas fee for the transaction

**Comment by BrunoMarshall** [comment]
here the findings:
- Transation : amount 0.000001   appears error message: current balance of 0.000000 is not enough for the requested transfer 0.000001   -->  (OK)
- Transation : amount 0.0000001 appears error message:  current balance of 0.000000 is not enough for the requested transfer 0.000000  -->(missing the complete value)
- Transation : amount 0.0000000001 DON´T appears error message, but instead a transaction-receipt
that can´t be found/not succeed
example ":"0x462a73af462a881aa7891d09b17fbb0003c19f0dc168c31bd074e65d6e6354c8

**Comment by yelllowsin** [comment]
Tested again using latest hmy version with an amount of 1 ONE. Now the hmy throws an error saying the balance of 1 is insufficient as we need some gas added to the tx, thus you cannot send the max amount. Eventough the error doesn't specifically say there is gas missing, it is not wrong to say the balance is insufficient. I would personally close this one as solved, as the error will be the same for any amount that exceeds the balance discounted the tx fee. Or maybe ask for a more detailed error message in this case whereas the default gas fee is known.

```
./hmy version
Harmony (C) 2020. hmy, version v300-d6ddd06 (deploy@harmony.one 2020-02-29T12:52:16+0100)
```

```
./hmy --node="https://api.s0.os.hmny.io" transfer --from one1tsv8kpj26x5gzh48vketzyyyx75d7veah9hnc6 --to one1zmtegpk65ghgwxzhq9q6hc6tjyj5z0ey8ge6zd --from-shard 0 --to-shard 0 --amount 1 --chain-id testnet
{
  "errors": [
    "[2020-03-02 17:51:39.154301] [Plain transaction] insufficient balance of 1.000000000000000000 in shard 0 for the requested transfer of 1.000000000000000000 -- 2020-03-02 17:51:39 +0000 UTC",
    "[2020-03-02 17:51:39.154304] transaction has bad parameters",
    "[2020-03-02 17:51:39.154318] Failed to confirm transaction"
  ],
  "time-signed-utc": "2020-03-02 17:51:39.123834"
}
commit: v300-d6ddd06, error: Failed to confirm transaction
```

**Comment by BrunoMarshall** [comment]
I will close this issue, please see the comment from Yelllowsin.
Solved.
Thank you
