### ISSUE TITLE
Add remove/delete option to hmy cli

### ISSUE THREAD

**Issue by JB273** [harmony-one/harmony#2072]
# Problem/limitation At Hand

Currently there's no option to remove a wallet-address from hmy with the cli command.
Removal could be done by hand by removing the directories from the location where these files are stored (**./hmy keys location**)

**Which component?**

- [ ] consensus
- [ ] deploy script
- [ ] wallet
- [ ] explorer
- [ ] node script
- [ ] test automation
- [ ] demo app
- [X] hmy cli

# Proposed Solution

Add an option (**remove** or **delete**) to the _**keys**_ part of hmy cli
Example: ./hmy keys remove [ADDRESS (one1....)]

**Comment by SebastianJ** [comment]
I've opened a pull request for this: [https://github.com/harmony-one/go-sdk/pull/103](https://github.com/harmony-one/go-sdk/pull/103)

**Comment by yelllowsin** [comment]
@JB273 @SebastianJ this one can be closed. Tested here with the remove parameter and it works:

`./hmy keys remove foster-imported`

```
./hmy version
Harmony (C) 2020. hmy, version v300-d6ddd06 (deploy@harmony.one 2020-02-29T12:52:16+0100)
```

**Comment by yelllowsin** [comment]
@JB273 closing this issue as it has been resolved accordingly to my comment above. Feel free to reopen if needed.
