### ISSUE TITLE
Empty Header on WebSocket querying latest block headers

### ISSUE THREAD

**Issue by neeboo** [harmony-one/harmony#2079]
**Describe the bug**
When subscribing latest block header via websocket api, `newHeads`, which should return blockHeader object when new block is generated.

**To Reproduce**
1. JS sdk
```javascript

const { Harmony } =require('@harmony-js/core')
const { ChainID, ChainType } = require('@harmony-js/utils');

const harmony= new Harmony('ws://localhost:9800',{chainId:ChainID.HmyLocal,chainType:ChainType.Harmony}

const sub = harmony.blockchain.newBlockHeaders(0);

sub
  .onData((data) => {
    console.log(data.params.result.Header);
  })
  .onError((err) => {
    console.log('err:' + err);
  });

```

**Expected behavior**
Should return Header

**Screenshots**

**Environment (please complete the following information):**
 - OS: [Linux, MacOS]
- Go environment [ ```go env``` ]

**Additional context**
See https://github.com/harmony-one/sdk/issues/15

**Comment by flicker-harmony** [comment]
APIs working fine
<img width="1262" alt="Screenshot 2020-01-14 at 09 30 50" src="https://user-images.githubusercontent.com/52401354/72319859-5a47fd00-36b1-11ea-9286-912f31c72864.png">

Same for header by number, block by hash and number.

**Comment by neeboo** [comment]
> APIs working fine
> <img alt="Screenshot 2020-01-14 at 09 30 50" width="1262" src="https://user-images.githubusercontent.com/52401354/72319859-5a47fd00-36b1-11ea-9286-912f31c72864.png">
> 
> Same for header by number, block by hash and number.

Problem exist in WebSocket， not http

**Comment by flicker-harmony** [comment]
I see, but is it on node side and not sdk? If it was working before, as far as I know we didnt change node/rpc.go which creates web sockets.

**Comment by neeboo** [comment]
> I see, but is it on node side and not sdk? If it was working before, as far as I know we didnt change node/rpc.go which creates web sockets.

Yes. Its on node side. I think we should check with   pub/sub methods

**Comment by flicker-harmony** [comment]
If you want faster fix I’d ask @mikedoan, I’m not familiar with code on node/rpc.go and pub/sub part of the code. I can go deep, if it will not be resolved fast.

**Comment by mikedoan** [comment]
@neeboo sorry for the late response - how urgent are you for this request? i'm working on another sprint of block explorer now

**Comment by flicker-harmony** [comment]
@neeboo, can you check out it happens on master or s3? Or both?

**Comment by flicker-harmony** [comment]
Maybe it's because hmy module is not exposed to websockets https://github.com/harmony-one/harmony/blob/master/node/rpc.go#L39 and https://github.com/harmony-one/harmony/blob/s3/node/rpc.go#L42, I don't see any other changes though.

**Comment by flicker-harmony** [comment]
@neeboo

**Comment by flicker-harmony** [comment]
@neeboo @mattlockyer I merge PR into master which added hmy to websockets modules, it could fix the issue

**Comment by mattlockyer** [comment]
Tested with a local dapp.

Confirmed it's fixed, @flicker-harmony you're the bomb!

**Comment by gitloverr** [comment]
> **Describe the bug**
> When subscribing latest block header via websocket api, `newHeads`, which should return blockHeader object when new block is generated.
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 
> 1. JS sdk
> 
> ```js
> const { Harmony } =require('@harmony-js/core')
> const { ChainID, ChainType } = require('@harmony-js/utils');
> 
> const harmony= new Harmony('ws://localhost:9800',{chainId:ChainID.HmyLocal,chainType:ChainType.Harmony}
> 
> const sub = harmony.blockchain.newBlockHeaders(0);
> 
> sub
>   .onData((data) => {
>     console.log(data.params.result.Header);
>   })
>   .onError((err) => {
>     console.log('err:' + err);
>   });
> ```
> 
> **Expected behavior**
> Should return Header
> 
> **Screenshots**
> If applicable, add screenshots to help explain your problem.
> 
> **Environment (please complete the following information):**
> 
> * OS: [Linux, MacOS]
> * Go environment [ `go env` ]
> 
> **Additional context**
> See [harmony-one/sdk#15](https://github.com/harmony-one/sdk/issues/15)

hi @neeboo,

how did you solve this problem?

I have the same problem. I would like to listen the newly header/ blocks on Harmony blockchain via my node websocket stream. 

I tried your code snippets, but didn't return anything information about the last blocknumber or  blockheader...

what should I do?

thank you
