### ISSUE TITLE
Report concise messages when the balance is 0, for TX with small value

### ISSUE THREAD

**Issue by BrunoMarshall** [harmony-one/harmony#2082]
## Summary issue
If we have a wallet with 0 balance and if we try to do a transaction, the error message is not always the same, (not for all the possible scenarios) is depending on the decimal numbers of the value for the transactions.
Example: 
Account A = 0
Transaction from A to A : amount 0.000001 appears error message:
"current balance of 0.000000 is not enough for the requested transfer 0.000001 --> ( this is OK)

Transaction from A to A : amount 0.0000001 appears error message: current balance of 0.000000 is not enough for the requested transfer 0.000000 -->(missing the complete value 0.0000001)

Transaction from A to A  : amount 0.0000000001 -->( DON´T appears error message, but instead a transaction-receipt that can´t be found/not succeed)
example ":"0x462a73af462a881aa7891d09b17fbb0003c19f0dc168c31bd074e65d6e6354c8

## Proposal
We propose that for all scenarios when the balance in a wallet is 0 should report 
"current balance of 0.0000000000 is not enough for the requested transfer X"

**Comment by janet-harmony** [comment]
@BrunoMarshall, you are using the CLI?
CLI issues should be fixed with https://github.com/harmony-one/go-sdk/pull/106

**Comment by BrunoMarshall** [comment]
Thanks, i see that the issues is solved:
[ec2-user@ip-172-31-38-220 ~]$ ./hmy --node=https://api.s0.pga.hmny.io/ transfer --from one12fjmqsl2lrzsvqvvdtvy9tnq5af3dkeefucag3 --to one12fjmqsl2lrzsvqvvdtvy9tnq5af3dkeefucag3 --from-shard 0 --to-shard 0 --amount 0.000000000000000001 --chain-id devnet
commit: v2061540ed7, error: insufficient balance of 0.000000000000000000 for the requested transfer of 0.000021000000000001
check hmy cookbook for valid examples or try adding a `--help` flag
[ec2-user@ip-172-31-38-220 ~]$ ./hmy --node=https://api.s0.pga.hmny.io/ transfer --from one12fjmqsl2lrzsvqvvdtvy9tnq5af3dkeefucag3 --to one12fjmqsl2lrzsvqvvdtvy9tnq5af3dkeefucag3 --from-shard 0 --to-shard 0 --amount 0.0000000000000000001 --chain-id devnet
commit: v2061540ed7, error: too much precision, maximum 18, len decimal 19


You can close this issue.
