### ISSUE TITLE
Expose number of pending cross-shard receipts and cross links in RPC

### ISSUE THREAD

**Issue by rlan35** [harmony-one/harmony#2085]
We need to be able to monitor the number of pending cross shard receipts and cross links.

We need to return the length of "Node.pendingCXReceipts" and "Node.pendingCrossLinks" with rpc endpoint such as hmy_getNumPendingCXReceipts and hmy_getNumPendingCrossLinks.

**Comment by LeoHChen** [comment]
we can add the info to watchdog, closing this one.
