### ISSUE TITLE
[Feature] sign harmony released binaries

### ISSUE THREAD

**Issue by LeoHChen** [harmony-one/harmony#2092]
# Problem/limitation At Hand

To protect harmony released binary, we need to incorporate a signing process.  Please create a public security repo with our public key. And add signing and verification scripts. All Harmony released binaries shall be signed and verified against the open public key. The private key has to be stored offline, but we need to have a solution/process to sign the released binaries, automatically.

**Which component?** .

- [x] security
- [ ] consensus
- [x] deploy script
- [ ] wallet
- [ ] explorer
- [ ] node script
- [ ] test automation
- [ ] demo app
- [ ] others ...

# Proposed Solution

# Alternatives Considered

# Additional Context

**Comment by coolcottontail** [comment]
https://github.com/harmony-one/harmony-open/pull/1/files

**Comment by LeoHChen** [comment]
As the signing tools is created, we need to incorporate it into the node.sh and release process, in Jenkins job and build process.  All official build binaries have to be signed by our private key, also, the node.sh should verify the signature of the binaries by default.

@Daniel-VDM, Please work with @coolcottontail to roll out the binary signing process.

**Comment by coolcottontail** [comment]
Updated node.sh in client to verify the signature in PR https://github.com/harmony-one/harmony/pull/2155

### The updated node.sh will download harmony public signing key and use it to verify against harmony binaries.

###  Step 1. Generate signature files

  check out https://github.com/harmony-one/harmony-open/tree/master/harmony-signing
  read https://github.com/harmony-one/harmony-open/blob/master/harmony-signing/README.md

  sign harmony executables 

```bash
source venv/bin/activate
python ../sign_binary.py arn:aws:kms:us-west-2:656503231766:key/370d45bb-d629-45d7-8d1c-db0560895690 harmony harmony.sig
python ../sign_binary.py arn:aws:kms:us-west-2:656503231766:key/370d45bb-d629-45d7-8d1c-db0560895690 wallet wallet.sig
python ../sign_binary.py arn:aws:kms:us-west-2:656503231766:key/370d45bb-d629-45d7-8d1c-db0560895690 bootnode bootnode.sig
python ../sign_binary.py arn:aws:kms:us-west-2:656503231766:key/370d45bb-d629-45d7-8d1c-db0560895690 libbls384_256.so libbls384_256.so.sig
python ../sign_binary.py arn:aws:kms:us-west-2:656503231766:key/370d45bb-d629-45d7-8d1c-db0560895690 libmcl.so libmcl.so.sig
```

### Release the signature files at the same directory as binary files in AWS (aka. http://${BUCKET}.s3.amazonaws.com/${FOLDER}${bin).sig

**Comment by LeoHChen** [comment]
done
