### ISSUE TITLE
Double spend failed transactions not showing up on explorer.

### ISSUE THREAD

**Issue by Cem-Harmony** [harmony-one/harmony#2106]
**Describe the bug**
When creating two transactions with the same nonce and different amounts, you receive two different hashes. The second hash is not found on the explorer.

**To Reproduce**
1. Transfer two different amounts in two separate transactions:
  - The transactions should have the same sender and receiver
  - The transactions should occur around the same time (same nonce)

**Expected behavior**
The explorer should let you know that a transaction has failed

**Screenshots**
[Screenshot of explorer.](https://drive.google.com/open?id=1vizUTrRXq1MkkvcV3V13p4rTw0gmoSEa)

**Environment (please complete the following information):**
 - OS: [MacOS]
- Go environment [1.13.6]

**Additional context**
The CLI shell is used to create two transactions and retrieve the hash from the transactions.

**Comment by NiteeshHarmony** [comment]
Same issue as above, but with Math Wallet. 

The transaction for 10 tokens went through but 20 tokens didn't. Below 

Transaction ID: 0x69fe332a5a03ce4b8f57b6c72025f5c2c25b9d53353eff47d109ed8cabdd77fd

10 Tokens Worked Hash: 
0x69fe332a5a03ce4b8f57b6c72025f5c2c25b9d53353eff47d109ed8cabdd77fd
20 Tokens Didn't Send Hash: 
0x9406d3dde1375fcdf4ca2206e72c2b45be692fad19685cdc5ef9edc928eee2db
