### ISSUE TITLE
Add size check on the fields of validator description.

### ISSUE THREAD

**Issue by rlan35** [harmony-one/harmony#2108]
add checking like in CLI: ensureLength for validator description in core protocol.

Also need to update the size limit to:

	MaxNameLength            = 140
	MaxIdentityLength        = 140
	MaxWebsiteLength         = 140
	MaxSecurityContactLength = 140
	MaxDetailsLength         = 280

**Comment by gupadhyaya** [comment]
I think this is already addressed. @rlan35
