### ISSUE TITLE
view change didn't start on some nodes

### ISSUE THREAD

**Issue by LeoHChen** [harmony-one/harmony#2120]
**Describe the bug**

Rolling upgrade was failed on one shard. I then manually upgraded all the node in the shard, and restart the entire shard.  However, some nodes weren't able to enter the viewchanging mode to start view change, thus the entire shard is stuck.

I run a script to query the viewchangingid of the shard, while some nodes are returning the same viewchangingid, those returned status 1 has not entered into viewchanging mode.

```
ViewChangingID":9933
3.92.216.102 returned status 1
34.218.224.196 returned status 1
ViewChangingID":9933
54.189.159.135 returned status 1
ViewChangingID":9933
13.52.252.76 returned status 1
ViewChangingID":9933
34.215.117.42 returned status 1
ViewChangingID":9933
52.24.234.153 returned status 1
35.165.215.97 returned status 1
ViewChangingID":9933
ViewChangingID":9933
ViewChangingID":9933
52.33.13.48 returned status 1
13.57.207.184 returned status 1
ViewChangingID":9933
54.213.9.222 returned status 1
ViewChangingID":9933
ViewChangingID":9933
ViewChangingID":9933
ViewChangingID":9933
```

The original leader of the shard is:
```{"level":"info","port":"9000","ip":"3.133.155.37","blockNum":9892,"ViewId":9929,"blockHash":"0x50eaa32fd444a67d3880d2f4aba400814196195823be72028ec98cd52c0cb2b7","index":0,"caller":"/home/leochen/go/src/github.com/harmony-one/harmony/consensus/consensus_v2.go:834","time":"2020-01-18T06:06:25.372618422Z","message":"HOORAY!!!!!!! CONSENSUS REACHED!!!!!!!"}```

**Comment by rlan35** [comment]
Related to block sync'ing issue.
"level":"debug","port":"9000","ip":"34.218.224.196","myHeight":9891,"requestHeight":9891,"incomingIP":"34.218.224.196","incomingPort":"9000","incomingPeer":"34.218.224.196:50374","caller":"/home/leochen/go/src/github.com/harmony-one/harmony/node/node_syncing.go:355","time":"2020-01-18T07:19:53.295065133Z","message":"[SYNC] GetBlockHashes Request: I am not higher than requested node"}
{"level":"info","port":"9000","ip":"34.218.224.196","maxFirstID":0,"maxCount":3,"caller":"/home/leochen/go/src/github.com/harmony-one/harmony/api/service/syncing/syncing.go:330","time":"2020-01-18T07:19:53.317336449Z","message":"[SYNC] block consensus hashes"}
When a node is sync'ing, it won't have consensus timeout timer.
select {
            case <-ticker.C:
                if toStart == false && isInitialLeader {
                    continue
                }
                for k, v := range consensus.consensusTimeout {
                    if consensus.current.Mode() == Syncing ||
                        consensus.current.Mode() == Listening {
                        v.Stop()
                    }
                    if !v.CheckExpire() {
                        continue
                    }
                    if k != timeoutViewChange {
                        utils.Logger().Debug().Msg("[ConsensusMainLoop] Ops Consensus Timeout!!!")
                        consensus.startViewChange(consensus.viewID + 1)
                        break
                    } else {
                        utils.Logger().Debug().Msg("[ConsensusMainLoop] Ops View Change Timeout!!!")
                        viewID := consensus.current.ViewID()
                        consensus.startViewChange(viewID + 1)
                        break
                    }
                }
And this node seems requesting state syncing with a node that's also out of sync
so it stuck in sync'ing
