### ISSUE TITLE
Add monitoring of GetPendingCXReceipts into watchdog

### ISSUE THREAD

**Issue by rlan35** [harmony-one/harmony#2122]
We need to monitor the number of pendingCxReceipts to avoid cross-shard txns not being processed for too long.

The rpc GetPendingCXReceipts is already added into the backend. We need to query it from watch dog and add alert to it.

Please setup alert if GetPendingCXReceipts increase to > 1000. Query it every 5 mins.

**Comment by janet-harmony** [comment]
harmony-ops PR#337
