### ISSUE TITLE
Ledger instructions doc for explorer using ledger and chrome ext

### ISSUE THREAD

**Issue by rlan35** [harmony-one/harmony#2132]
Add documentation on how to use ledger to do staking in staking explorer.

**Comment by yelllowsin** [comment]
There is some documentation already done here, more specifically at the end of this page: https://docs.harmony.one/home/wallet-guides/ledger/staking-with-ledger#sign-staking-with-ledger

Maybe it needs to be better organized/revamped only?

**Comment by mikedoan** [comment]
@yelllowsin RJ wants to add it in the staking dashboard. your docs are very useful to add there too.
