### ISSUE TITLE
State pruning to reduce size of blockchain

### ISSUE THREAD

**Issue by rlan35** [harmony-one/harmony#2136]
This may be a blocker as we use code as the storage for validator record, which can be huge if there are a lot of delegations in it. The validator record will be modified every block due to block reward data. This may cause a huge amount of state history data if we don't prune it.

**Comment by yelllowsin** [comment]
@rlan35 @denniswon  this one can be closed, i can confirm i am running nodes with pruning on main net, shard 0 and 3. Other FN nodes are running succesfully on other shards as well.
