### ISSUE TITLE
Staking Explorer allows for negative amount of one to type.

### ISSUE THREAD

**Issue by JB273** [harmony-one/harmony#2137]
**Describe the bug**
When sending an amount of one from the staking explorer, you are allowed to select a negative amount. You can type it, but also do this with the up/down arrows at the right side of the box. It throws a message this amount needs to be between some values, but it's nicer to disable having a negative amount at all.

**To Reproduce**
1. When logged on in Staking Explorer select "Send" button
2. In the Send box type in a negative amount to send or click the down arrow until a negative amount appears

**Expected behavior**
It should not be able to give a negative amount at all!

**Screenshots**
![image](https://user-images.githubusercontent.com/54506968/72935608-f767fd00-3d65-11ea-9e0f-352e52ebd456.png)

**Environment (please complete the following information):**
 - OS: Google Chrome browser

**Comment by mikedoan** [comment]
thanks @JB273 it was fixed long ago. should be working well on the latest version.
