### ISSUE TITLE
Staking Explorer Windows warning can be removed

### ISSUE THREAD

**Issue by JB273** [harmony-one/harmony#2138]
**Describe the bug**
When sending ONE form staking explorer and signing with Ledger Nano S you get a warning about 
Windows 10 (may update 2019) version.

**To Reproduce**
1. Logged in at https://staking.harmony.one with Ledger
2. Select "Send" in Portfolio, a pop-up box to send ONE will appear, the message is in here...

**Expected behavior**
This can be removed imo, I'm running version 1903 (may 2019) and sending and signing tokens works very well. Also at least one other P-OPS @sophoah has succesfully send and signed with Ledger from staking explorer.

**Screenshots**
![image](https://user-images.githubusercontent.com/54506968/72937050-b0c7d200-3d68-11ea-9cca-d6dd8199a392.png)

**Environment (please complete the following information):**
 - OS: Windows 10 (1903)

**Comment by JB273** [comment]
Also on the link https://staking.harmony.one/ledger it can be removed

![image](https://user-images.githubusercontent.com/54506968/72937621-be318c00-3d69-11ea-9998-bdae4ff83ece.png)

**Comment by sophoah** [comment]
Hi All,

Also tested with my windows 10 1903 last updated on 19/10/2019 OS build 18362.535, and no issue with it signing and sending transaction.

cc : @JB273

**Comment by yelllowsin** [comment]
Seems this one went missing in the last updates done on the dashboard. Can maybe we assing Potvik or Mike maybe to check on this? @rlan35

**Comment by yelllowsin** [comment]
@JB273 closing this issue as current dashboard has been updated and doesn't have this message anymore. Feel free to reopen if needed.
