### ISSUE TITLE
ValidatorWrapper may cause excessive storage burden due to state change

### ISSUE THREAD

**Issue by rlan35** [harmony-one/harmony#2147]
Currently ValidatorWrapper is a all-in-one object that contains all validator related data: meta data, all delegations and all undelegations, also signing stats. ValidatorWrapper is stored in the account.code field in the state trie.

This means basically for every block the ValidatorWrapper object will be changed, and it may cause a huge amount of state change history data to be generated as both old and the new version of the whole ValidatorWrapper may be recorded.

We need to dig into the seriousness of this issue and potentially change the storage structure of Validator data and take use of the account.storage field.

**Comment by LeoHChen** [comment]
still valid

**Comment by AlexiaChen** [comment]
close. duplicated issue https://github.com/harmony-one/harmony/issues/3843
