### ISSUE TITLE
release static harmony binaries

### ISSUE THREAD

**Issue by LeoHChen** [harmony-one/harmony#2153]
## Summary

We have support of the statically build binary of harmony node.  We need to roll out the statically linked binary to all foundational nodes then, including wallet, hmycli, harmony binaries. 

The node.sh, and release scripts will need to be modified to support the full static binaries.

**Comment by yelllowsin** [comment]
@Daniel-VDM  i think this one can be closed. Both harmony and hmy have statically linked binaries working by my tests, the only issue found that is related to this feature is #2351 that can be addressed separately.
