### ISSUE TITLE
[Feature] Staking explorer -  shard 0 supported only -  information message 

### ISSUE THREAD

**Issue by sophoah** [harmony-one/harmony#2156]
# Problem/limitation At Hand
There is currently no other normal wallet using windows 10 for normal operation (sending, receiving ONE) except that using the staking explorer with our ledger nano S. (https://staking.harmony.one/)
Staking explorer only support shard 0 (by design it make sense since staking operation are only done on shard 0)

# A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
Win10 user with their ledger nano S will see a balance of 0 if their fund are not sent to shard 0

**Which component?**

- [ ] consensus
- [ ] deploy script
- [ ] wallet
- [ ] explorer
- [ ] node script
- [ ] test automation
- [ ] demo app
- [ X ] others : Staking explorer 

# Proposed Solution
1) any other wallet usable with windows 10 and ledger (ie : math wallet ?)
2) add shard support in the staking explorer
2) add a warning/information message in the portfolio https://staking.harmony.one/portfolio page to warn the user regarding the limitation.

# Alternatives Considered

# Additional Context

**Comment by sophoah** [comment]
@coolcottontail I just saw your medium article https://medium.com/@coolcottontail/using-ledger-nano-for-harmony-one-fee58ad0ac5c with more people aware of the staking explorer to check their balance with ledger, I think we really need have at least an informative message that will tell everyone about that limitation.

**Comment by LeoHChen** [comment]
already supported
