### ISSUE TITLE
Importing same keystore file with hmy keys import-ks gives duplicate account aliases for same address

### ISSUE THREAD

**Issue by mirrormirage0** [harmony-one/harmony#2163]
**Describe the bug**
Importing same keystore file with hmy keys import-ks gives duplicate account aliases for same address

**To Reproduce**
1. `hmy keys import-ks YOURKEYFILENAME`
2. `hmy keys list`
This shows the account alias and the wallet address. Make a note of this.
Now try to re-import the same key file again
3. `hmy keys import-ks YOURKEYFILENAME`
4. `hmy keys list`
This will show multiple account aliases for the same wallet address.

**Expected behavior**
Should ideally check for duplicates and have only ONE account-alias for a given keystore file.

**Screenshots**
![image](https://user-images.githubusercontent.com/29485946/73247899-5648ce80-41cb-11ea-9c47-fd80565a3601.png)

**Environment (please complete the following information):**
- OS: Linux 70255766b7a1 5.0.0-37-generic #40~18.04.1-Ubuntu SMP Thu Nov 14 12:06:39 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
- hmy version Harmony (C) 2020. hmy, version v238-878cc03 (@harmony.one 2020-01-28T08:17:01+0000)

**Comment by sophoah** [comment]
issue fixed, @mirrormirage0  feel free to close it.

**Comment by mirrormirage0** [comment]
Verified and closed.
As expected, trying to import duplicate key now fails with error message "already exists in keystore"
![image](https://user-images.githubusercontent.com/29485946/75606958-c10f6180-5b0b-11ea-9b69-86333df2c5ce.png)
