### ISSUE TITLE
Staking explorer doesn't work with new testnet api.s0.os.hmny.io

### ISSUE THREAD

**Issue by sophoah** [harmony-one/harmony#2195]
**Describe the bug**

Staking explorer doesn't show any validator while we have active validator in the network :
```bash
./hmy blockchain validator all -n https://api.s0.os.hmny.io
{
  "id": "0",
  "jsonrpc": "2.0",
  "result": [
    "one15uwuu2kwth75xxspzn7r4ja2cnhtpgqkvnpgh0",
    "one1s7fp0jrmd97estwye3mhkp7xsqf42vn5x2sfqy",
    "one1u6c4wer2dkm767hmjeehnwu6tqqur62gx9vqsd",
    "one1v83yuvgdzrj9xgx69uwqmmxzhp5ngrczdcn0rf",
    "one1gjsxmewzws9mt3fn65jmdhr3e4hel9xza8wd6t"
  ]
}
````

Balance on shard 0 of the account are also not updated, shown 0 while there are for sure balances:
```bash
./hmy balances one1u6c4wer2dkm767hmjeehnwu6tqqur62gx9vqsd --node="https://api.s0.os.hmny.io"
[
  {
    "shard": 0,
    "amount": 9000.000000000000000000
  },
  {
    "shard": 1,
    "amount": 10000.000000000000000000
  },
  {
    "shard": 2,
    "amount": 10000.000000000000000000
  }
]
```
**To Reproduce**
Make sure there are active validator in hmy cli and access the staking explorer validator page. Change network to Openstakingnet and verify balance in portfolio page, and empty validators in the validator page

**Expected behavior**
non 0 balance, and active validators shown

**Screenshots**

**Environment (please complete the following information):**
 - OS: windows 10
- Go environment [ ```go env``` ]

**Additional context**

**Comment by mikedoan** [comment]
@sophoah thank you so much - i'm looking into this now

**Comment by mikedoan** [comment]
@sophoah let me close it - it was a typo in our backend as we specified http://api.s0.os.hmny.io instead of https://api.s0.os.hmny.io

**Comment by mindstyle85** [comment]
@mikedoan sure, he is asleep but you can, will update our track sheet too

**Comment by mikedoan** [comment]
let me close this one to look into the incorrectness of the dashboard.
