### ISSUE TITLE
./hmy blockchain validator information shows wrong max-total-delegation

### ISSUE THREAD

**Issue by sophoah** [harmony-one/harmony#2196]
**Describe the bug**
./hmy blockchain validator information one1u6c4wer2dkm767hmjeehnwu6tqqur62gx9vqsd -n https://api.s0.os.hmny.io shows a a wrong wrong max-total-delegation

validator was created with : --min-self-delegation 2 --max-total-delegation 10000

however the cli command shows:
```json
    "max-total-delegation": 1864712049423024000,
    "min-self-delegation": 2000000000000000000,
```

**To Reproduce**
1. create validator
2. show its information

**Expected behavior**
the data shown in wei : 
```json
    "max-total-delegation": 1864712049423024000,
    "min-self-delegation": 2000000000000000000,
```
match the min-self-delegation of 2 but the max-total-delegation after conversion is 1.864712049423024, I am expecting to have 10000 so 10000000000000000000000 wei

**Screenshots**
N/A

**Environment (please complete the following information):**
 - OS: Ubuntu
- ./hmy version
```bash
Harmony (C) 2020. hmy, version v246-c28ff50 (edgar@harmony.one 2020-02-04T17:32:58-0800)
```
**Additional context**

**Comment by sophoah** [comment]
Hi all,

For info, on the staking explorer, the issue can also be seen when looking at the validator information

**Comment by gupadhyaya** [comment]
https://github.com/harmony-one/harmony/pull/2240
