### ISSUE TITLE
staking reward not incrementing when waiting for a new delegator to become active

### ISSUE THREAD

**Issue by sophoah** [harmony-one/harmony#2198]
**Describe the bug**
Here is the scenario:
There is already an active delegator who was earning regularly the staking reward after each BINGO (can be observed by executing every x second):
```bash
./hmy blockchain delegation by-validator one1u6c4wer2dkm767hmjeehnwu6tqqur62gx9vqsd -n https://api.s0.os.hmny.io
```
Now, a new delegator decide to stake with the same validator.

While waiting for the new epoch to start and have the new delegator to become active, we can see the new delegator present (along with 1st one) with : 
```bash
./hmy blockchain delegation by-validator one1u6c4wer2dkm767hmjeehnwu6tqqur62gx9vqsd -n https://api.s0.os.hmny.io
```
however the first delegator reward stop to increase regularly until the next epoch starts. At that time both delegator starts to see their staking reward increased.

**To Reproduce**
1 - have an active delegator who is earning regularly
2 - add new delegator 

**Expected behavior**
I was expecting the reward to still increase for the first delegator. If the increase is just not shown (maybe just a UI issue) and actually work in the background, That is ok but if not, that could be a real issue considering an epoch in mainnet would be 1 day. (if there everyday one new validator, you would basically not earning until there is 1 day without a new validator added)

**Screenshots**
N/A

**Environment (please complete the following information):**
 - OS: ubuntu 18

**Additional context**
Other POPs to confirm if they have the same behavior,

**Comment by rlan35** [comment]
Hi, Soph: thanks for reporting this.

Can you show the command results like the delegation and rewards? that will help with the debugging. 

Does the 1st and 2nd delegator having the same amount of stakes?

**Comment by sophoah** [comment]
Hi @rlan35, I am not home so can't give you the output of the command, will do once I am back after work. The stake amount are different from the first and the second delegator.

**Comment by sophoah** [comment]
Hi @rlan35 

so i was looking more carefully again at the logs, and I think i was looking at the wrong field - amount (which is the amount stake and which shouldn't change), the reward field was actually incrementing.

so my bad.

Closing the issue.
