### ISSUE TITLE
Staking error messages arent shown

### ISSUE THREAD

**Issue by mindstyle85** [harmony-one/harmony#2199]
**Describe the bug**
While trying to delegate over the maximum to a validator, or creating a new validator with same info as an active validator, it does not return an error message, neither in hmy or with 
./hmy failures staking --node="https://api.s0.os.hmny.io"
{
  "id": "0",
  "jsonrpc": "2.0",
  "result": []
}

**To Reproduce**
1. delegate over the validator's maximum
2. create a new validator with same info as an active validator

**Expected behavior**
Should show the error as expected

**Additional context**
Verified by Soph too.

**Comment by rlan35** [comment]
This is a feature in implementation by @Daniel-VDM . Let's come back to this issue once it's finished.

**Comment by sophoah** [comment]
@fxfactorial mentioned on telegram the feature was not added to this version? Maybe double check what is the status. @Daniel-VDM

**Comment by Daniel-VDM** [comment]
Implementing this is requiring more refactoring that I had originally anticipated. The optimistic goal for me is to have PR done by Tuesday, assuming no major distractions. It may take longer as I need to carefully test the refactored tx-pool. Track the progress here https://github.com/Daniel-VDM/harmony/commits/staking-tx-pool

**Comment by mindstyle85** [comment]
tried this one with today's version, but it still doesnt provide any error messages:

./hmy failures staking --node="https://api.s0.os.hmny.io"
{
  "id": "0",
  "jsonrpc": "2.0",
  "result": []
}


version: Harmony (C) 2020. hmy, version v274-6fc64db (deploy@harmony.one 2020-02-15T09:23:59+0100)
luka@ubuntu:

**Comment by rlan35** [comment]
@Daniel-VDM please take a look.

**Comment by Daniel-VDM** [comment]
Tested every day, seems to be working.

**Comment by mindstyle85** [comment]
confirmed :)
