### ISSUE TITLE
Hmy cli throws out different char sizes as expected from the testing sheet

### ISSUE THREAD

**Issue by mindstyle85** [harmony-one/harmony#2200]
**Describe the bug**

for identity chars:
./hmy --node="https://api.s0.os.hmny.io" staking edit-validator --validator-addr one1s7fp0jrmd97estwye3mhkp7xsqf42vn5x2sfqy --name mind --identity mindmindmindmindmindmindmindmindmindmindmindmindmindmindmindmindmindmindmindmindmindmindmindmindmindmindmindmindmindmindmindmindmindmindmindmindmindmindmindmindmindmindmindmindmind  --website mind@harmony.one --security-contact mamapangaea --details "pink pony node runners" --rate 0.1 --min-self-delegation 5 --max-total-delegation 1000 --remove-bls-key e429cbf74e8ab28ed295999d179ad79827c7febe0208a6145aa91bbb60b68a0b1907de4c38573352cafe00c8105b1116 --add-bls-key e429cbf74e8ab28ed295999d179ad79827c7febe0208a6145aa91bbb60b68a0b1907de4c38573352cafe00c8105b1116 --chain-id testnet --passphrase
Enter the bls passphrase:
**commit: v246-c28ff50, error: exceeds maximum length of 3000 characters for description field identity**

./hmy --node="https://api.s0.os.hmny.io" stakingedit-validator --validator-addr one1s7fp0jrmd97estwye3mhkp7xsqf42vn5x2sfqy --name mindmindmindmindmindmindmindmindmindmindmindmindmindmindmindmindmindmindmindmindmindmindmindmindmindmindmindmindmindmindmindmindmindmindmindmindmindmindmindmindmindmindmindmindmind --identity mind --website mind@harmony.one --security-contact mamapangaea --details "pink pony node runners" --rate 0.1 --min-self-delegation 5 --max-total-delegation 1000 --remove-bls-key e429cbf74e8ab28ed295999d179ad79827c7febe0208a6145aa91bbb60b68a0b1907de4c38573352cafe00c8105b1116 --add-bls-key e429cbf74e8ab28ed295999d179ad79827c7febe0208a6145aa91bbb60b68a0b1907de4c38573352cafe00c8105b1116 --chain-id testnet --passphrase
Enter the bls passphrase:
**commit: v246-c28ff50, error: exceeds maximum length of 70 characters for description field name**

Expected should be 140 chars as in the testing sheet?

**Comment by rlan35** [comment]
Seems a CLI message mistakes.

**Comment by gupadhyaya** [comment]
Fixed.
https://github.com/harmony-one/go-sdk/commit/3debac3b01bab11ade0f4a9fff2124da09f3269e
