### ISSUE TITLE
hmy - when mistakenly only using one " it just hangs indefinitely until stopping manually

### ISSUE THREAD

**Issue by mindstyle85** [harmony-one/harmony#2201]
**Describe the bug**
So i made a mistake and forgot to remove the " or add the second one at the end:

 ./hmy --node="https://api.s0.os.hmny.io" staking create-validator --validator-addr one1s7fp0jrmd97estwye3mhkp7xsqf42vn5x2sfqy --name **"mindmindmindmindmindmindmindmindmindmindmindmindmindmindmindmindmindmindmindmindmindmindmindmindmindmindmindmindmindmindmindmindmindmindmindmindmindmindmindmindmindmindmindmindmind** --identity mind --website mind@harmony.one --security-contact mamapangaea --details "pink pony node runners" --rate 0.1 --max-rate 0.5 --max-change-rate 0.05 --min-self-delegation 5 --max-total-delegation 1000 --bls-pubkeys e429cbf74e8ab28ed295999d179ad79827c7febe0208a6145aa91bbb60b68a0b1907de4c38573352cafe00c8105b1116 --amount 10 --chain-id testnet
> 
> 
> 
> 
> 
> ^C

This didnt throw out any errors which i think it should and it just hangs indefinitely until manually stopping it with ctrlc

**Comment by Daniel-VDM** [comment]
There isn't anything we can really do here. This is just the nature of the command line. If there is an open quote, it will parse everything until a close quote as a string. But if there is no close quote, it will keep accepting input until it sees a close quote, thus the hanging.
