### ISSUE TITLE
hmy doesnt return an error when expected

### ISSUE THREAD

**Issue by mindstyle85** [harmony-one/harmony#2205]
FIXED 

./hmy --node="https://api.s0.os.hmny.io" staking create-validator --validator-addr one1s7fp0jrmd97estwye3mhkp7xsqf42vn5x2sfqy --name mind --identity mind --website mind@harmony.one --security-contact mamapangaea --details "pink pony node runners" --rate 0.1 --max-rate 0.5 --max-change-rate 0.05 **--min-self-delegation 999999** --max-total-delegation 100000000 --bls-pubkeys e429cbf74e8ab28ed295999d179ad79827c7febe0208a6145aa91bbb60b68a0b1907de4c38573352cafe00c8105b1116 **--amount 5** --chain-id testnet
Enter the bls passphrase:
{"transaction-receipt":"0x157eaa2f95dbe5fd960e64b578cb9e75f02a8709a4a760428384c90707f3d4ef"}

no error here while this one does produce an error:

./hmy --node="https://api.s0.os.hmny.io" staking create-validator --validator-addr one1s7fp0jrmd97estwye3mhkp7xsqf42vn5x2sfqy --name mind --identity mind --website mind@harmony.one --security-contact mamapangaea --details "pink pony node runners" --rate 0.1 --max-rate 0.5 --max-change-rate 0.05 --min-self-delegation 5 **--max-total-delegation 1** --bls-pubkeys e429cbf74e8ab28ed295999d179ad79827c7febe0208a6145aa91bbb60b68a0b1907de4c38573352cafe00c8105b1116 **--amount 10** --chain-id testnet
Enter the bls passphrase:
commit: v246-c28ff50, error: max_total_delegation can not be less than min_self_delegation

**Comment by mindstyle85** [comment]
another one:

./hmy --node="https://api.s0.os.hmny.io" staking create-validator --validator-addr one1s7fp0jrmd97estwye3mhkp7xsqf42vn5x2sfqy --name mind --identity mind --website mind@harmony.one --security-contact mamapangaea --details "pink pony node runners" --rate 0.1 --max-rate 0.5 --max-change-rate 0.05 **--min-self-delegation 10 --max-total-delegation 0** --bls-pubkeys e429cbf74e8ab28ed295999d179ad79827c7febe0208a6145aa91bbb60b68a0b1907de4c38573352cafe00c8105b1116 --amount 10 --chain-id testnet
Enter the bls passphrase:
{"transaction-receipt":"0xb1bab87ffb6987b72aa851ffcdde370ea4439b32335a69b8bf0f5fc941326ab4"}

**Comment by mindstyle85** [comment]
and another one:

./hmy --node="https://api.s0.os.hmny.io" staking create-validator --validator-addr one1s7fp0jrmd97estwye3mhkp7xsqf42vn5x2sfqy --name mind --identity mind --website mind@harmony.one --security-contact mamapangaea --details "pink pony node runners" --rate 0.1 --max-rate 0.5 --max-change-rate 0.05 --min-self-delegation 5 **--max-total-delegation 10** --bls-pubkeys e429cbf74e8ab28ed295999d179ad79827c7febe0208a6145aa91bbb60b68a0b1907de4c38573352cafe00c8105b1116 **--amount 100** --chain-id testnet
Enter the bls passphrase:
{"transaction-receipt":"0xd73713895483d2022d0b5b17417d14605869186a862492abb17663282c2aad8c"}

**Comment by mindstyle85** [comment]
this one too? (duplicate bls key)

./hmy --node="https://api.s0.os.hmny.io" staking create-validator --validator-addr one1s7fp0jrmd97estwye3mhkp7xsqf42vn5x2sfqy --name mind --identity mind --website mind@harmony.one --security-contact mamapangaea --details "pink pony node runners" --rate 0.1 --max-rate 0.5 --max-change-rate 0.05 --min-self-delegation 5 --max-total-delegation 100 --bls-pubkeys **e429cbf74e8ab28ed295999d179ad79827c7febe0208a6145aa91bbb60b68a0b1907de4c38573352cafe00c8105b1116 e429cbf74e8ab28ed295999d179ad79827c7febe0208a6145aa91bbb60b68a0b1907de4c38573352cafe00c8105b1116** --amount 10 --chain-id testnet
Enter the bls passphrase:
{"transaction-receipt":"0x33ff2dc18014126e55eaee394c278223949a7eac4595a779eedffbc2179425b0"}

**Comment by rlan35** [comment]
CLI staking logic usability issue.

**Comment by sophoah** [comment]
@gupadhyaya CV46 also not displaying any error message, validator not created so that is good:
./hmy --node="https://api.s0.os.hmny.io" staking create-validator --validator-addr one1ahj9rklrqt40f7ctfnffnrj884x7z3pj0r6cdw --name Soph_CV46_test_amount_1100_accounthas_1000 --identity Soph --website Soph@harmony.one --security-contact Soph --details "test" --rate 0.1 --max-rate 0.5 --max-change-rate 0.05 --min-self-delegation 5 --max-total-delegation 2000 --bls-pubkeys 415ab78653ca61c1f0ba48b3ec385f1989a45666e0a3bc9562350cedf1be6787ad09c5b6126d9fa670c4c9dc26782c0c --amount 1100 --chain-id testnet
Enter the bls passphrase:
{"transaction-receipt":"0x18ff233bcfed31d48b50591b77565243023a501ad07c26747361d7fd9994c44d"}

cc: @mindstyle85

**Comment by mindstyle85** [comment]
./hmy --node="https://api.s0.os.hmny.io" staking edit-validator --validator-addr one1s7fp0jrmd97estwye3mhkp7xsqf42vn5x2sfqy --rate 0.51 --chain-id testnet --passphrase
Enter passphrase:
Repeat the passphrase:

{"transaction-receipt":"0x2bbea809fd4ebae423b3ae1a6dc530654167842fdbe9bc873c876ea833abfcb2"}


If going over max rate of 0.5 with setting rate 0.5 the expected outcome is an error message, which doesnt happen (the rate is NOT accepted though)

**Comment by mindstyle85** [comment]
also no error message when trying to edit a non existent validator:

./hmy --node="https://api.s0.os.hmny.io" stakingedit-validator --validator-addr one1675d7adqu9egn0ehd9fx4f6jmdjfynw3gkr48q --rate 0.13 --chain-id testnet --passphrase
Enter passphrase:
Repeat the passphrase:

{"transaction-receipt":"0xf166ccbdc19d94feb38375560497b74ff2fe2ca86ba4e6f7dde5d2e1568bcb95"}

**Comment by mindstyle85** [comment]
editing minselfdelegation to a number higher than my actual self delegation (10), also provides no error message:

./hmy --node="https://api.s0.os.hmny.io" staking edit-validator --validator-addr one1s7fp0jrmd97estwye3mhkp7xsqf42vn5x2sfqy --min-self-delegation 200 --chain-id testnet --passphrase
Enter passphrase:
Repeat the passphrase:

{"transaction-receipt":"0x1f24ff34f58500e280921a9fcb431dedeb1e7a5e6c10a7e0d7be3d25443333f4"}

**Comment by mindstyle85** [comment]
for adding a duplicate bls key to edit validator, no error message either:

./hmy--node="https://api.s0.os.hmny.io" staking edit-validator --validator-addr one1s7fp0jrmd97estwye3mhkp7xsqf42vn5x2sfqy --add-bls-key e429cbf74e8ab28ed295999d179ad79827c7febe0208a6145aa91bbb60b68a0b1907de4c38573352cafe00c8105b1116 --chain-id testnet --passphrase
Enter the bls passphrase:
Enter passphrase:
Repeat the passphrase:

{"transaction-receipt":"0x85e68f85abc4b71763bd2f3566ed05126bd9b7d71e337b136716c1853ab89ccc"}

**Comment by mindstyle85** [comment]
removing a bls key slot that is not even there also returns no error message:

 ./hmy --node="https://api.s0.os.hmny.io" stakingedit-validator --validator-addr one1s7fp0jrmd97estwye3mhkp7xsqf42vn5x2sfqy --remove-bls-key 75b92d038fd0e96df21ee45c88bc27baa60e113e55b2a81b16f7b34289fc8083b6812d08f36b92b372545fb522aeff11 --chain-id testnet --passphrase
Enter passphrase:
Repeat the passphrase:

{"transaction-receipt":"0x1657815560971a1c6c4ded7f363741e698828c6c9d70f12de96ef97646aab68e"}

**Comment by mindstyle85** [comment]
if creating validator with higher amount than account balance, theres also no error message:

./hmy --node="https://api.s0.os.hmny.io" staking create-validator --validator-addr one1s7fp0jrmd97estwye3mhkp7xsqf42vn5x2sfqy --name mindmindmindmindmindmindmindmindmindmindmindmindmindmindmindmindmin --identity mind --website mind@harmony.one --security-contact mamapangaea --details "pink pony node runners" --rate 0.1 --max-rate 0.5 --max-change-rate 0.05 --min-self-delegation 5 --max-total-delegation 1000000000000000 --bls-pubkeys e429cbf74e8ab28ed295999d179ad79827c7febe0208a6145aa91bbb60b68a0b1907de4c38573352cafe00c8105b1116 --amount 1000000000 --chain-id testnet
Enter the bls passphrase:
{"transaction-receipt":"0xf75989d598e9114d8f4813c589fb1808e9438c775cc957a823541cf9503809db"}

**Comment by mindstyle85** [comment]
when trying to collect rewards with an address that didnt delegate also no error messages:

./hmy --node="https://api.s0.os.hmny.io" staking collect-rewards --delegator-addr one1675d7adqu9egn0ehd9fx4f6jmdjfynw3gkr48q --chain-id testnet --passphrase
Enter passphrase:
Repeat the passphrase:

{"transaction-receipt":"0xa84f67e36bae8365985c1a8cb5f02f2cb5da6c8e304b922b252b2905973a71d4"}

**Comment by sophoah** [comment]
when trying to undelegate a bigger amount that was available : 
```
./hmy -n https://api.s0.os.hmny.io blockchain delegation by-validator one1pjusejwj3xug79tag35jxyrvl4zj0xma0dpemq
{
  "id": "0",
  "jsonrpc": "2.0",
  "result": [
    {
      "Undelegations": [],
      "amount": 1e+21,
      "delegator_address": "one1mcverl6yrcsy0xdrmf3mltm28kk6kux3nwtvxd",
      "reward": 1.926201496529999e+21,
      "validator_address": "one1pjusejwj3xug79tag35jxyrvl4zj0xma0dpemq"
    }
  ]
}
```
```
./hmy --node="https://api.s0.os.hmny.io" staking undelegate --delegator-addr one1mcverl6yrcsy0xdrmf3mltm28kk6kux3nwtvxd --validator-addr one1pjusejwj3xug79tag35jxyrvl4zj0xma0dpemq --amount 1005 --chain-id tes
tnet
{"transaction-receipt":"0x40f85e64b2c67f5a44175c0a21a6699634fa0207a9ba9ef203f9bb76e3a48718"}
```

**Comment by mindstyle85** [comment]
no error message while trying to delegate to a non-existent validator either:

./hmy --node="https://api.s0.os.hmny.io" staking delegate --delegator-addr one1675d7adqu9egn0ehd9fx4f6jmdjfynw3gkr48q --validator-addr one1675d7adqu9egn0ehd9fx4f6jmdjfynw3gkr48q --amount 100 --chain-id testnet --passphrase
Enter passphrase:
Repeat the passphrase:

{"transaction-receipt":"0x21b01def9bf273836d7841e918aba21ee131ad75f19b534541b44482858614e8"}

**Comment by mindstyle85** [comment]
no error message for delegating over the validators max-total:

./hmy --node="https://api.s0.os.hmny.io" staking delegate --delegator-addr one1675d7adqu9egn0ehd9fx4f6jmdjfynw3gkr48q --validator-addr one1s7fp0jrmd97estwye3mhkp7xsqf42vn5x2sfqy --amount 9850 --chain-id testnet --passphrase
Enter passphrase:
Repeat the passphrase:

{"transaction-receipt":"0xb4e457fc14557aba500d8a54178859beab43f35c88a1ed6f183eaf1dacbfd17e"}

**Comment by mindstyle85** [comment]
delegating more than a delegator has also shows no error message:

./hmy --node="https://api.s0.os.hmny.io" staking delegate --delegator-addr one1675d7adqu9egn0ehd9fx4f6jmdjfynw3gkr48q --validator-addr one1s7fp0jrmd97estwye3mhkp7xsqf42vn5x2sfqy --amount 989999950 --chain-id testnet --passphrase
Enter passphrase:
Repeat the passphrase:

{"transaction-receipt":"0xd55e0b1c0c58821b4b70c59a8e6f818d29a14b542933e9f496e3fa48e561edb0"}

**Comment by mindstyle85** [comment]
trying to undelegate when there is nothing to undelegate also has no error message:

./hmy --node="https://api.s0.os.hmny.io" staking undelegate --delegator-addr one13rpucsxhzny2hy2rtd5udsshhu4jevnxqwrfwe --validator-addr one1s7fp0jrmd97estwye3mhkp7xsqf42vn5x2sfqy --amount 100 --chain-id testnet --passphrase
Enter passphrase:
Repeat the passphrase:

{"transaction-receipt":"0x014f84eaa84d14e1952cb43664f288f27495af69663b59c80fa0d2f37b7289d2"}

**Comment by sophoah** [comment]
delegating more than the users fund + what is currently being undelegated
```
./hmy --node="https://api.s0.os.hmny.io" staking delegate --delegator-addr one186nc0pslageyqcmuerxydnhgvt2x5qg63kv2gh --validator-addr one1u6c4wer2dkm767hmjeehnwu6tqqur62gx9vqsd --amount 1000 --chain-id testnet
{"transaction-receipt":"0x58bc6e38ccfee4ac40242d8eea0f339ede24e615eda11faabdeccffa4ca0d493"}
```
cc : @mindstyle85 so you don't double it :)

**Comment by sophoah** [comment]
D9 - specify small gas limit to cause "txn out of gas" -> delegating all the wallet available fund
```
./hmy --node="https://api.s0.os.hmny.io" staking delegate --delegator-addr one186nc0psla
geyqcmuerxydnhgvt2x5qg63kv2gh --validator-addr one1u6c4wer2dkm767hmjeehnwu6tqqur62gx9vqsd --amount 59.999828672000000000
 --chain-id testnet
{"transaction-receipt":"0x19bd948f1bde71409df10330a2471e52f90c7f7a8e88447fc8322f71cdb605eb"}
```

cc: @mindstyle85

**Comment by sophoah** [comment]
U9 - specify small gas limit to cause "txn out of gas" -> undelegation staking operation with 0 ONE in wallet : 
```
./hmy -n https://api.s0.os.hmny.io balances one186nc0pslageyqcmuerxydnhgvt2x5qg63kv2gh
[
  {
    "shard": 0,
    "amount": 0.000000000000000000
  },
  {
    "shard": 1,
    "amount": 0.000000000000000000
  },
  {
    "shard": 2,
    "amount": 0.000000000000000000
  }
]
```
```
./hmy--node="https://api.s0.os.hmny.io" staking undelegate --delegator-addr one186nc0pslageyqcmuerxydnhgvt2x5qg63kv2gh --validator-addr one1u6c4wer2dkm767hmjeehnwu6tqqur62gx9vqsd --amount 10 --chain-id testnet
{"transaction-receipt":"0x87be84feb84b7432e0567773fc1fad49d63b913427e8aa5a140742c566eadcdb"}
```
cc : @mindstyle85

**Comment by sophoah** [comment]
CR4 - specify small gas limit to cause "txn out of gas" -> empty delegator wallet and try to claim reward

./hmy --node="https://api.s0.os.hmny.io" staking collect-rewards --delegator-addr one186nc0pslageyqcmuerxydnhgvt2x5qg63kv2gh
{"transaction-receipt":"0x87157d943d30d6e5bde4ec4c554ee7b705d1831f777d15c8f47e72adb20c0054"}

cc: @mindstyle85

**Comment by sophoah** [comment]
CR3 - no rewards to collect 
```
./hmy --node="https://api.s0.os.hmny.io" staking collect-rewards --delegator-addr one10ph98cj7nveklqyr5ha5l3uk4as2mgy0fek6vm
{"transaction-receipt":"0x6a3cd415b6d45871508fd022e58396b1b95a8c672cdeedde3fc0b61a9bbeb6d9"}
```
cc @mindstyle85

**Comment by sophoah** [comment]
EV30 - specify small gas limit to cause "txn out of gas" - empty validator wallet and edit validator
```
./hmy --node="https://api.s0.os.hmny.io" staking edit-validator --validator-addr one1ahj9rklrqt40f7ctfnffnrj884x7z3pj0r6cdw --name Soph_CV47_edited --chain-id testnet
{"transaction-receipt":"0xc53e0f2a52779fa6aafaf76daaeecfe698884e0cae0551029933100be2b6bd83"}
```
cc @mindstyle85

**Comment by sophoah** [comment]
edit max-total-delegation so amount > MaxTotalDelegation (below amount was 1000)

```
./hmy --node="https://api.s0.os.hmny.io" staking edit-validator --validator-addr one186nc0pslageyqcmuerxydnhgvt2x5qg63kv2gh --max-total-delegation 999 --chain-id testnet
{"transaction-receipt":"0x5fc739e899b83ebde6508cbae6f08c495e1e773e2a530d23f7d36bb9eb7e7086"}
```
cc @mindstyle85 EV24

**Comment by Daniel-VDM** [comment]
For reference, #2236 should help with a lot of these bugs. CLI changes to hook into changes made by PR have already been merged, just waiting on #2236.

**Comment by mindstyle85** [comment]
some have been fixed, this one though shows the wrong error message:

./hmy --node="https://api.s0.os.hmny.io" staking create-validator --validator-addr one1s7fp0jrmd97estwye3mhkp7xsqf42vn5x2sfqy --name mind --identity mind --website mind@harmony.one --security-contact mamapangaea --details "pink pony node runners" --rate 0.1 --max-rate 0.5 --max-change-rate 0.05 --min-self-delegation 5 --max-total-delegation -100 --bls-pubkeys e429cbf74e8ab28ed295999d179ad79827c7febe0208a6145aa91bbb60b68a0b1907de4c38573352cafe00c8105b1116 --amount 10 --chain-id testnet
Enter the bls passphrase:
commit: v274-6fc64db, error: max-self-delegation can not be less than 1 ONE

**Comment by mindstyle85** [comment]
negative amounts return this:

commit: v246-c28ff50, error: rlp: cannot encode negative *big.Int

might want to change to a more generalised text, such as --amount cannot be negative? etc

**Comment by sophoah** [comment]
CV41 HMY_Validator_Creation_no_bls_key_specified
```
./hmy --node=https://api.s0.os.hmny.io staking create-validator --validator-addr one1u6c4wer2dkm767hmjeehnwu6tqqur62gx9vqsd --name John --identity john --website john@harmony.one --security-contact Alex --details 'John the validator' --rate 0.1 --max-rate 0.9 --max-change-rate 0.05 --min-self-delegation 2 --max-total-delegation 30 --bls-pubkeys --amount 3 --chain-id testnet
```
shows this error:
```
commit: v282-5d54265, error: required flag(s) "amount" not set
```
we should have : 
```
error: required flag(s) "bls-pubkeys" not set
```

**Comment by gupadhyaya** [comment]
@sophoah 
The --amount flag is read into `bls-pubkeys` flag in case of empty value for `bls-pubkeys`, hence the error message `amount not set`. I don't think we can fix this. One thing you could do is, `--bls-pubkeys= --amount 3`. In this case empty is read into bls-pubkeys without consuming `--amount`.

**Comment by mindstyle85** [comment]
@sophoah i updated mine with FIXED/NOT FIXED, can you do the same for yours?

**Comment by mindstyle85** [comment]
> CV41 HMY_Validator_Creation_no_bls_key_specified
> 
> ```
> ./hmy --node=https://api.s0.os.hmny.io staking create-validator --validator-addr one1u6c4wer2dkm767hmjeehnwu6tqqur62gx9vqsd --name John --identity john --website john@harmony.one --security-contact Alex --details 'John the validator' --rate 0.1 --max-rate 0.9 --max-change-rate 0.05 --min-self-delegation 2 --max-total-delegation 30 --bls-pubkeys --amount 3 --chain-id testnet
> ```
> 
> shows this error:
> 
> ```
> commit: v282-5d54265, error: required flag(s) "amount" not set
> ```
> 
> we should have :
> 
> ```
> error: required flag(s) "bls-pubkeys" not set
> ```

**NOT FIXED**

**Comment by mindstyle85** [comment]
> @sophoah
> The --amount flag is read into `bls-pubkeys` flag in case of empty value for `bls-pubkeys`, hence the error message `amount not set`. I don't think we can fix this. One thing you could do is, `--bls-pubkeys= --amount 3`. In this case empty is read into bls-pubkeys without consuming `--amount`.

how come it doesnt recognize the -- as a new attribute?
