### ISSUE TITLE
Is median stake value on staking explorer correct ?

### ISSUE THREAD

**Issue by sophoah** [harmony-one/harmony#2210]
**Describe the bug**
The median stake currently shown on the staking explorer doesn't seems correct. see here (currently  : 30000000000000000000 ONE) : https://imgur.com/a/a2DVl5c or check on the staking explorer https://staking.harmony.one/validators

**To Reproduce**
https://staking.harmony.one/validators

**Expected behavior**
even in wei the amount would be only 30 so definitely something not right

**Screenshots**

**Environment (please complete the following information):**

**Additional context**

**Comment by sophoah** [comment]
hmy cli also show the same median stake
root@vmi334486:/tmp/harmony# ./hmy blockchain median-stake -n https://api.s0.os.hmny.io
{
  "id": "0",
  "jsonrpc": "2.0",
  "result": 30000000000000000000
}root@vmi334486:/tmp/harmony#

**Comment by mindstyle85** [comment]
guessing this is wei, current median at the moment of writing in this case is 50 ONEs on devnet, is this correct?

**Comment by sophoah** [comment]
median stake are now displayed in normal currency and seems to be correctly computed. Closing this now.
@rlan35 feel free to move this to done.
