### ISSUE TITLE
Active validator state doesn't work as expected

### ISSUE THREAD

**Issue by sophoah** [harmony-one/harmony#2211]
**Describe the bug**
As part of the staking test, I created fake validator (ie they have no active node running with the associated BLS). Despite not being active, they are being shows in both staking explorer and the CLI that they are active.

**To Reproduce**
1. Generate a new bls key
2. Create a new account, and fund it
3. create a valid validator with the above
4. verify in staking explorer or the hmy cli it is marked as active
5. make sure not to start the node

**Expected behavior**
In the output of ./hmy -n https://api.s0.os.hmny.io blockchain validator all-active I shouldn't see the one address use above for the validator creation

**Screenshots**
N/A

**Environment (please complete the following information):**
N/A

**Additional context**

**Comment by mindstyle85** [comment]
i think someone from the team already mentioned that the hmy command and seems the dashboards as well shows all validators, even if theyre not "active". I do think this needs to be fixed though

**Comment by rlan35** [comment]
This is a usability and naming issue. The "Active" is overloaded. Being selected and being actively running is different. So in the CLI/explorer, the "active" really means it's being selected in the committee. We don't have categorical definition for nodes that's actually running or not.
Anyway, this is still an issue on the naming that we need to fix.

**Comment by sophoah** [comment]
@rlan35 during my delegation testing, i delegated to a non running node, hence my fund were blocked there and undelegation take 7 epoch, in mainnet it would 7 days. Would be nice to add that as a feature which for now can only be detected by looking at whether the delegator in that validator has an increase of reward ..

question, since you mentioned active means selected in the committee, would that active tag switch to offline or inactive if his bid is not enough to make it to the committee ? This is something we have to test as well but I am not sure for now what is the number of seat in our current testing network.

**Comment by sophoah** [comment]
@rlan35 I just tested edit a validator and put it put the active flag to false. Is that action related what you mentioned (aka being selected to be part of the committee)

I am asking because I tried to change the active flag of a validator to false but nothing happened even after the new epoch happened
```
./hmy staking edit-validator --validator-addr one1ahj9rklrqt40f7ctfnffnrj884x7z3pj0r6cdw --active false
{"transaction-receipt":"0x5913c60a8b9818904133e19565a369ed2ddb22f149a7f1cbd3928f874172645f"}
```
```
./hmy -n https://api.s0.os.hmny.io blockchain transaction-receipt 0x5913c60a8b9818904133e19565a369ed2ddb22f149a7f1cbd3928f874172645f
{
  "id": "0",
  "jsonrpc": "2.0",
  "result": {
    "blockHash": "0x8739f9a841ee522ccc5cc3f1740833bb5829bcda980eeee597591f969297ab6c",
    "blockNumber": "0x6637",
    "contractAddress": null,
    "cumulativeGasUsed": "0x5b54",
    "gasUsed": "0x5b54",
    "logs": [],
    "logsBloom": "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
    "sender": "one1ahj9rklrqt40f7ctfnffnrj884x7z3pj0r6cdw",
    "status": "0x1",
    "transactionHash": "0x5913c60a8b9818904133e19565a369ed2ddb22f149a7f1cbd3928f874172645f",
    "transactionIndex": "0x0",
    "type": 1
  }
```
```
./hmy -n https://api.s0.os.hmny.io blockchain validator all-active | grep one1ahj9rklrqt40f7ctfnffnrj884x7z3pj0r6cdw
    "one1ahj9rklrqt40f7ctfnffnrj884x7z3pj0r6cdw",
```

if this is not supposed to happen, let me know I can create a seperate issue to track that as well.

**Comment by BrunoMarshall** [comment]
I confirm this issue.
we have this issue that i think is related to this one : https://github.com/harmony-one/harmony/issues/2235

**Comment by sophoah** [comment]
now fixed in 
```
/harmony --version
Harmony (C) 2020. harmony, version v5621-master-20191208.0-244-g268fbd25
```

@rlan35 can be moved to done.
