### ISSUE TITLE
staking explorer validator uptime shows 0%

### ISSUE THREAD

**Issue by sophoah** [harmony-one/harmony#2212]
**Describe the bug**
my node has been online for 24h already and with no outage, however https://staking.harmony.one/validators/one1u6c4wer2dkm767hmjeehnwu6tqqur62gx9vqsd is showing me 0% uptime

**To Reproduce**
have a working node validator created and verify the validator page for uptime

**Expected behavior**
at least not 0%

**Screenshots**
N/A

**Environment (please complete the following information):**
 - OS: [Linux, MacOS]
- Go environment [ ```go env``` ]

**Additional context**

**Comment by mindstyle85** [comment]
is it shard 0 node? if so then its the same issue as with the devnet before where i reported this bug

**Comment by mikedoan** [comment]
@sophoah we are looking into this

**Comment by rlan35** [comment]
@sophoah can you confirm whether you have earned reward or not?

**Comment by sophoah** [comment]
@rlan35 think that one is duplicate with @mindstyle85 with the availability signing
