### ISSUE TITLE
hmy cli hangs if setting double negative value to create validator tx

### ISSUE THREAD

**Issue by mindstyle85** [harmony-one/harmony#2213]
**Describe the bug**

i left this command running for about 15min and it didnt give me any error messages, it just hang so i had to manually stop it:

./hmy --node="https://api.s0.os.hmny.io/" staking create-validator --validator-addr one1s7fp0jrmd97estwye3mhkp7xsqf42vn5x2sfqy --name mind --identity mind --website mind@harmony.one --security-contact mamapangaea --details "pink pony node runners" --rate 0.1 --max-rate 0.5 --max-change-rate 0.05 **--min-self-delegation -101 --max-total-delegation -100** --bls-pubkeys e429cbf74e8ab28ed295999d179ad79827c7febe0208a6145aa91bbb60b68a0b1907de4c38573352cafe00c8105b1116 --amount 10 --chain-id testnet

**Comment by janet-harmony** [comment]
@mindstyle85 
Not able to reproduce the issue. Copied your exact command, but changed validator address & bls pubkey
What version of the CLI are you on?
```
$ ./hmy --node="https://api.s0.os.hmny.io/" staking create-validator --validator-addr one1tqhlq4eemklv0l4qarlugt7qv8q6vdjssvuh6x --name mind --identity mind --website mind@harmony.one --security-contact mamapangaea --details "pink pony node runners" --rate 0.1 --max-rate 0.5 --max-change-rate 0.05 --min-self-delegation -101 --max-total-delegation -100 --bls-pubkeys 43795bb17418e6497ae0fe54e4ea13e3d4ff9f35d4d88e794623ba5b35bc604bb66818568c87edc7be3f48a796dec509 --amount 10 --chain-id testnet
For bls public key: 43795bb17418e6497ae0fe54e4ea13e3d4ff9f35d4d88e794623ba5b35bc604bb66818568c87edc7be3f48a796dec509
Enter the absolute path to the encrypted bls private key file:
Enter the bls passphrase:
commit: v258-cbdd3b7, error: min_self_delegation has to be greater than 1 ONE
check hmy cookbook for valid examples or try adding a `--help` flag
```

**Comment by mindstyle85** [comment]
this is odd, i cant reproduce now either, i now get the same error message as you (copy pasted my own command).

Version: ./hmy version
Harmony (C) 2020. hmy, version v246-c28ff50 (edgar@harmony.one 2020-02-04T17:32:58-0800)

we can then close this one and reopen if it happens again?
