### ISSUE TITLE
hmy: max-total-delegation nil or 0 does not work

### ISSUE THREAD

**Issue by mindstyle85** [harmony-one/harmony#2215]
**Describe the bug**

./hmy--node="https://api.s0.os.hmny.io" staking create-validator --validator-addr one1s7fp0jrmd97estwye3mhkp7xsqf42vn5x2sfqy --name mind --identity mind --website mind@harmony.one --security-contact mamapangaea --details "pink pony node runners" --rate 0.1 --max-rate 0.5 --max-change-rate 0.05 --min-self-delegation 5 --bls-pubkeys e429cbf74e8ab28ed295999d179ad79827c7febe0208a6145aa91bbb60b68a0b1907de4c38573352cafe00c8105b1116 --amount 10 --chain-id testnet
commit: v246-c28ff50, error: required flag(s) "max-total-delegation" not set

so omitting it like in CV37 test case does not default to 0 (infinite). 

Setting max-tota-delegation to 0 also does not work:

./hmy --node="https://api.s0.os.hmny.io" staking create-validator --validator-addr one1675d7adqu9egn0ehd9fx4f6jmdjfynw3gkr48q --name "mind2 --identity mind2 --website mind2@harmony.one --security-contact mamapangaea2 --details "2pink pony node runners" --rate 0.1 --max-rate 0.5 --max-change-rate 0.05 --min-self-delegation 5 --max-total-delegation 0 --bls-pubkeys 1c57c3282714e412d974a5c1c5712f1f6062d3253d9a080580abf4342805e3311c19f81bef5b1a903fe282650b767a12 --amount 10 --chain-id testnet
>
>
>

Hmy just hangs here again.

**Comment by Daniel-VDM** [comment]
It looks like you are missing a close quote, `--name "mind2`. All command-line commands require a close quote if there is an open quote. It will blindly take input until it sees the close quote, therefore it appears as though hmy is hanging.

**Comment by mindstyle85** [comment]
Sorry for the quote, the first command is valid though, so this is an issue. 

For the second one:

./hmy --node="https://api.s0.os.hmny.io" staking create-validator --validator-addr one1675d7adqu9egn0ehd9fx4f6jmdjfynw3gkr48q --name mind2 --identity mind2 --website mind2@harmony.one --security-contact mamapangaea2 --details "2pink pony node runners" --rate 0.1 --max-rate 0.5 --max-change-rate 0.05 --min-self-delegation 5 --max-total-delegation 0 --bls-pubkeys 1c57c3282714e412d974a5c1c5712f1f6062d3253d9a080580abf4342805e3311c19f81bef5b1a903fe282650b767a12 --amount 10 --chain-id testnet

Enter the bls passphrase:
{"transaction-receipt":"0x358bde370d7e5499706207c63af47c417362e7b7b3546f66e706727d97316400"}

second try:
./hmy --node="https://api.s0.os.hmny.io" staking create-validator --validator-addr one1675d7adqu9egn0ehd9fx4f6jmdjfynw3gkr48q --name mind2 --identity mind2 --website mind2@harmony.one --security-contact mamapangaea2 --details "2pink pony node runners" --rate 0.1 --max-rate 0.5 --max-change-rate 0.05 --min-self-delegation 5 --max-total-delegation 0 --bls-pubkeys 1c57c3282714e412d974a5c1c5712f1f6062d3253d9a080580abf4342805e3311c19f81bef5b1a903fe282650b767a12 --amount 10 --chain-id testnet
Enter the bls passphrase:
{"transaction-receipt":"0x358bde370d7e5499706207c63af47c417362e7b7b3546f66e706727d97316400"}


NOTE: the tx failed twice so even setting it to 0 does not work properly

**Comment by mindstyle85** [comment]
please reopen

**Comment by Daniel-VDM** [comment]
Ah i see, reopened

**Comment by janet-harmony** [comment]
No longer possible to set unlimited max_total_delegation & protocol will not accept "0" as input to max_total_delegation.

Changed CLI to reflect these changes. ([go-sdk#138](https://github.com/harmony-one/go-sdk/pull/138)) Need to re-upload CLI binaries to S3.
