### ISSUE TITLE
Loose "commit: v246-c28ff50" part in hmy error responses

### ISSUE THREAD

**Issue by JB273** [harmony-one/harmony#2219]
**Describe the bug**
Every ./hmy command which is not correct returns an error message, in front of this message is a "commit: v246-c28ff50, " part, this looks not nice.

**To Reproduce**
1. Run any hmy command that can return an error:
    For example:
    ./hmy --node=https://api.s0.os.hmny.io staking create-validator --validator-addr one1gjsxmewzws9mt3fn65jmdhr3e4hel9xza8wd6t --name JB273-OpenStaking --identity JB273 --website JB273.harmony.one --security-contact JB273 --details "OpenStaking made possible by JB273" --rate 1.1 --max-rate 0.5 --max-change-rate -0.05 --min-self-delegation 5 --max-total-delegation 1000 --bls-pubkeys a689b39bb1de4f1591e29094b91d00596b0f371ea16fadf8b4143c680a1f9aff3e805e167eda2c583827ed0e7c8c9882 --amount 10 --chain-id testnet
Enter the bls passphrase:
commit: v246-c28ff50, error: commission rate, change rate and max rate should be within 0-100 percent

**Expected behavior**
It's nice to throw an error, but this needs to be something like:
Error: Commission rate, change rate and max rate should be within 0-100 percent

**Screenshots**
![image](https://user-images.githubusercontent.com/54506968/74074396-25a83680-4a0e-11ea-8c87-1a268e55ef73.png)

**Environment (please complete the following information):**
 - OS: Ubuntu 18.04

**Comment by janet-harmony** [comment]
The commit version for the CLI is included, so that it's easier to debug when someone pastes a CLI error message.

**Comment by JB273** [comment]
Ok, that's understandable!
Will we loose this when we go into production phase then?

**Comment by fxfactorial** [comment]
Not an issue.

**Comment by rlan35** [comment]
@JB273 we will keep it until CLI is very stable and no new feature dev.
