### ISSUE TITLE
Shard 1 on the testnet (b.hmny.io) is potentially stuck

### ISSUE THREAD

**Issue by SebastianJ** [harmony-one/harmony#2221]
**Describe the bug**
It appears as if shard 1 on the testnet - https://explorer.testnet.harmony.one/#/shard/1 - got stuck at block `167201` and has been stuck for 6+ hours.

The explorer isn't reporting any blocks past `167201` and if you check using hmy it reports the same block as well:
```
$ ./hmy blockchain latest-header --node https://api.s1.b.hmny.io
{
  "id": "0",
  "jsonrpc": "2.0",
  "result": {
    "blockHash": "0x923f75ac5e295b501dece7357ea22927ba8083aa2ab359a4f024da115cdf4cf9",
    "blockNumber": 167201,
    "epoch": 371,
    "lastCommitBitmap": "ff03",
    "lastCommitSig": "32c2a69d2208f48cc9cab37500d40f75f4d0219a7d5e80b3aa3dd7eaedc371cf605d94311914f3ba98d0937409299c1171a3aaf302070fc2376d0838174484d6440eb0239d9dc9664b2db8929043e8813602f634514d3446102de095041aa013",
    "leader": "one1mmnz9gyuuasz529mmtzc32cs7vpvadd05tp7uj",
    "shardID": 1,
    "timestamp": "2020-02-07 22:46:27 +0000 UTC",
    "unixtime": 1581115587,
    "viewID": 167210
  }
}
```

Oddly enough - the watchdog is reporting increasing blocks (currently at `170003`) - so not 100% sure what's going on.

**EDIT:** It seems that only 3/11 shard 1 nodes are stuck on `167201` - so could very well be that it's just the observer nodes supplying data to the API nodes + Explorer UI that got stuck?

**To Reproduce**
I'm not sure if this is related to me running my testing framework (it executes the pre-swap token tx test cases P-OPS got assigned), but the last transactions on shard 1 were sent by my framework.

If you need/want to execute the test cases:

```
mkdir -p harmony-tx-tests && cd harmony-tx-tests
bash <(curl -s -S -L https://raw.githubusercontent.com/SebastianJ/harmony-tx-tests/master/scripts/install.sh)

nano keys/testnet/private_keys.txt (insert one or several valid testnet private keys here)
./harmony-tx-tests
```

**Expected behavior**
Shard 1 should be as tough and resilient as Chuck Norris

**Comment by yelllowsin** [comment]
@SebastianJ i think this issue can be closed, no? Just checked, and shard is back:

`./hmy blockchain latest-header --node https://api.s1.b.hmny.io`
