### ISSUE TITLE
Explorer for staking network is not displaying the transaction history

### ISSUE THREAD

**Issue by sophoah** [harmony-one/harmony#2227]
**Describe the bug**
Accessing an account on the explorer doesn't show the transaction history https://explorer.os.hmny.io/#/address/one1mcverl6yrcsy0xdrmf3mltm28kk6kux3nwtvxd

**To Reproduce**
1. make transaction in and out from an account
2. access that account on the explorer : https://explorer.os.hmny.io/#/address/one1mcverl6yrcsy0xdrmf3mltm28kk6kux3nwtvxd

**Expected behavior**
see the list of transaction like in the current dev testnet https://explorer.testnet.harmony.one/#/address/one1zksj3evekayy90xt4psrz8h6j2v3hla4qwz4ur

**Screenshots**
N/A

**Environment (please complete the following information):**
 - OS: win10

**Additional context**
N/A

**Comment by rlan35** [comment]
@mikedoan can you work with Vlad to make sure staking transactions are displayed in explorer.

**Comment by denniswon** [comment]
@flicker-harmony what is the RPC endpoint to use for fetching staking txns? (we already have this right?) so just need to additionally fetch not just regular txns, but also staking txns to be displayed on the explorer side

**Comment by denniswon** [comment]
done
