### ISSUE TITLE
Create Validator staking operation doesn't need any gas (CV47)

### ISSUE THREAD

**Issue by sophoah** [harmony-one/harmony#2228]
**Describe the bug**
I was working on test CV47 : specify small gas limit to cause "txn out of gas" and decided to try create a validator with the full available ONE in the wallet. the validator creation went through without issue, full amount available in the wallet is used for staking.

**To Reproduce**
1. Create a new validator with the full amount available in the wallet

**Expected behavior**
Create validator should have failed with the error : "failure: "out of gas"

**Screenshots**
N/A

**Environment (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by janet-harmony** [comment]
Changed CLI to include default 1 NANO gas for all staking transactions. ([go-sdk 139](https://github.com/harmony-one/go-sdk/pull/139))
Currently, you don't have to pay gas for staking transactions to be processed. This will be added soon.
