### ISSUE TITLE
setting gas limit to 1 doesnt make edit validator tx fail

### ISSUE THREAD

**Issue by mindstyle85** [harmony-one/harmony#2229]
**Describe the bug**

Per test case EV30 setting a low gas limit (default is 21000), the tx should have failed which it did not.

./hmy --node="https://api.s0.os.hmny.io" staking edit-validator --validator-addr one1s7fp0jrmd97estwye3mhkp7xsqf42vn5x2sfqy --name mindischeap --gas-limit 1 --chain-id testnet --passphrase
Enter passphrase:
Repeat the passphrase:

{"transaction-receipt":"0x183f54133c924a70293d23a22abcefadf023e2e6aa15387c4f749069bfa0fdce"}

setting gas limit to 0 also does not make the tx fail:

./hmy--node="https://api.s0.os.hmny.io" staking edit-validator --validator-addr one1s7fp0jrmd97estwye3mhkp7xsqf42vn5x2sfqy **--name mindischeap69 --gas-limit 0** --chain-id testnet --passphrase
Enter passphrase:
Repeat the passphrase:

{"transaction-receipt":"0xf95fc2d12a9de9ed0661fb92a6432dc58e05ae277ccdb1440f8732e83a946207"}

./hmy blockchain validator information one1s7fp0rmd97estwye3mhkp7xsqf42vn5x2sfqy --node="https://api.s0.os.hmny.io"
{
  "id": "0",
  "jsonrpc": "2.0",
  "result": {
    "active": true,
    "bls-public-keys": [
      "e429cbf74e8ab28ed295999d179ad79827c7febe0208a6145aa91bbb60b68a0b1907de4c38573352cafe00c8105b1116"
    ],
    "commission": {
      "max-change-rate": "0.050000000000000000",
      "max-rate": "0.500000000000000000",
      "rate": "0.130000000000000000"
    },
    "creation-height": 6970,
    "description": {
      "details": "mindmindmindmindmindmindmindmindmindmindmindmindmindmindmindmindmindmindmindmindmindmindmindmindmindmindmindmindmindmindmindmindmindmindmindmindmindmindmindmindmindmindmindmindmind ",
      "identity": "mind",
      "name": "**mindischeap69**",
      "security_contact": "mamapangaea",
      "website": "mind@harmony.one"
    },
    "max-total-delegation": 11642099651136455000,
    "min-self-delegation": 2000000000000000000,
    "one-address": "one1s7fp0jrmd97estwye3mhkp7xsqf42vn5x2sfqy"
  }
}

**Comment by janet-harmony** [comment]
Protocol doesn't enforce gas on staking transactions right now.

**Comment by sophoah** [comment]
@janet-harmony most likely that one can be closed after your fix on #2228 for the fees of 1 nano.

**Comment by mindstyle85** [comment]
closing it yes :)

**Comment by rlan35** [comment]
please double check it's fixed.

**Comment by mindstyle85** [comment]
@rlan35 checked and works as intended:

./hmy --node="https://api.s0.os.hmny.io" staking edit-validator --validator-addr one1s7fp0jrmd97estwye3mhkp7xsqf42vn5x2sfqy --name mindischeap --gas-limit 1 --chain-id testnet --passphrase
Enter passphrase:
Repeat the passphrase:

[EditValidator] transaction gas is 1: intrinsic gas too low -- 2020-02-25 02:50:10 +0100 CET
commit: v287-06220f9, error: staking transaction error
