### ISSUE TITLE
[Feature] Validator and delegator deletion/deactivation

### ISSUE THREAD

**Issue by mindstyle85** [harmony-one/harmony#2230]
# Problem/limitation At Hand

Currently we do not have a command to disable/delete a validator completely so that it is removed from the validator lists. The only one there is is to set the validator to inactive which does not delete it or remove from the list of validators. 

A delete/remove feature would be great to have so that there wont be too many validators on the list like we have now on devnet.

**Comment by sophoah** [comment]
we have the same problem/limitation for the delegator through delegation/undelegation. in bold below is an inactive delegator
```
./hmy -n https://api.s0.os.hmny.io blockchain delegation by-validator one1u6c4wer2dkm76hmjeehnwu6tqqur62gx9vqsd
{
  "id": "0",
  "jsonrpc": "2.0",
  "result": [
    {
      "Undelegations": [],
      "amount": 4.927848283596894e+21,
      "delegator_address": "one1u6c4wer2dkm767hmjeehnwu6tqqur62gx9vqsd",
      "reward": 2.6008299799382095e+22,
      "validator_address": "one1u6c4wer2dkm767hmjeehnwu6tqqur62gx9vqsd"
    },
    **{
      "Undelegations": [],
      "amount": 0,
      "delegator_address": "one10ph98cj7nveklqyr5ha5l3uk4as2mgy0fek6vm",
      "reward": 0,
      "validator_address": "one1u6c4wer2dkm767hmjeehnwu6tqqur62gx9vqsd"
    },**
    {
      "Undelegations": [],
      "amount": 1e+21,
      "delegator_address": "one1mcverl6yrcsy0xdrmf3mltm28kk6kux3nwtvxd",
      "reward": 79431173668959220000,
      "validator_address": "one1u6c4wer2dkm767hmjeehnwu6tqqur62gx9vqsd"
    }
  ]
}
```

**Comment by rlan35** [comment]
This will be a more comprehensive design on the state usage of idle validators. Adding a delete feature won't help, because we can't expect all the idle validators to delete themselves. It's similar to the empty account issue in Ethereum. We can introduce the logic to clean up idle validator/delegators later tho. This FR is not a launch blocker.

**Comment by mindstyle85** [comment]
deactivation was added, should we close this one @rlan35 ?
