### ISSUE TITLE
Disallow negative values for creating/editing validator

### ISSUE THREAD

**Issue by JB273** [harmony-one/harmony#2232]
**Describe the bug**
At this moment it is possible to give negative values ("- 10") to some of the fields in creating/editing a validator. It throws an error, which is essentialy correct, but it would be better to not allow this or to change the error message into something else when negative values are added.

**To Reproduce**
1. Example:
 ./hmy --node=https://api.s0.os.hmny.io staking create-validator --validator-addr one1gjsxmewzws9mt3fn65jmdhr3e4hel9xza8wd6t --name JB273-OpenStaking --identity JB273 --website JB273.harmony.one --security-contact JB273 --details "OpenStaking made possible by JB273" --rate 0.1 --max-rate 0.5 --max-change-rate 0.05 --min-self-delegation 10 --max-total-delegation **-100** --bls-pubkeys a689b39bb1de4f1591e29094b91d00596b0f371ea16fadf8b4143c680a1f9aff3e805e167eda2c583827ed0e7c8c9882 --amount 10 --chain-id testnet
Enter the bls passphrase:
commit: v260-0153511, error: max_self_delegation has to be greater than 1 ONE
check hmy cookbook for valid examples or try adding a `--help` flag

**Expected behavior**
A message stating it's not allowed to put a negative value for the field that has actually the negative value filled in.
In the example this would be:
Error: max-self-delegation cannot have a negative value

**Screenshots**

**Environment (please complete the following information):**
 - OS: Ubuntu 18.04

**Additional context**
This also goes for the following options:
- --rate
- --max-rate 
- --max-change-rate
- --min-self-delegation 
- --max-total-delegation

**Comment by Daniel-VDM** [comment]
I think the way it handles it now is fine, might be cleaner if CLI checks for this case as an initial parse for all related args, but functionally it's fine. Closing this, but feel free to make it a FR on the go-sdk repo.

**Comment by rlan35** [comment]
@Daniel-VDM please double check and make sure all 
--rate
--max-rate
--max-change-rate
--min-self-delegation
--max-total-delegation
is good for negative value handling.

Thanks

**Comment by mindstyle85** [comment]
@janet-harmony can this be closed?

**Comment by Daniel-VDM** [comment]
Fixed on CLI by reporting of error sink. But with staking refactor, we will hook into the sanity check done in the main repo.
