### ISSUE TITLE
Delegation by - validator hmy command show values in wei

### ISSUE THREAD

**Issue by BrunoMarshall** [harmony-one/harmony#2233]
If we check in the delegation by validator the command will report the value in wei (18 zeros), instead of 1 "one"
Here the command used:
./hmy -n https://api.s0.os.hmny.io blockchain delegation by-validator one1km7xg8e3xjys7azp9f4p8hkw79vm2h3f2lade

Output:
  "id": "0",
  "jsonrpc": "2.0",
  "result": [
    {
      "Undelegations": [],
      "amount": 80000000000000000000,
      "delegator_address": "one1km7xg8e3xjys7azp9f4xp8hkw79vm2h3f2lade",
      "reward": 0,
      "validator_address": "one1km7xg8e3xjys7azp9f4xp8hkw79vm2h3f2lade"
    }

## Proposal

the proposal is to show the values delegated in "one" not in wei, in this case 80 instead of 80000000000000000000

**Comment by Daniel-VDM** [comment]
currently, the CLI only dumps what the RPC responds with (which has all values in Atto/Wei). So we would either have to change the RPC output at the node level (which we should *not* do) or change the output at the CLI level, which provides some inconsistencies (a bad thing). 

Instead, we should have a 'pretty' version of all commands (possibly enabled by default) where we can do such changes. But the underlying JSON output should not change at the CLI level.

**Comment by sophoah** [comment]
@Daniel-VDM I like your proposal to do a pretty print/conversion of the value

**Comment by rlan35** [comment]
Agree with Daniel. If we want to change to output format, we should change consistently across all rpcs, but for now, the consistent format is in wei. We will keep it for now until we have time to revamp the whole thing.

**Comment by BrunoMarshall** [comment]
I will close this issue, based on the Daniel´s comment.
Thank you
