### ISSUE TITLE
Validator with --active false still showed up in staking active dashboard 

### ISSUE THREAD

**Issue by BrunoMarshall** [harmony-one/harmony#2235]
**Describe the bug**
The validator with --active false still be shown in the staking explorer dashboard

from the hmy  blockchain validator all-active  is gone, but in the explorer still there

**To Reproduce**
1. create a validator, (in my case the BrunoMarshall_testnet_06_____140 one19zj0y47t54qhkqz3d8f2llnuhav9fw2dxyhlg7)
2. edit the validator with "--active false"
example:
./hmy --node="https://api.s0.os.hmny.io" staking edit-validator --validator-addr one19zj0y47t54qhkqz3d8f2llnuhav9fw2dxyhlg7 --active false --remove-bls-key dd49b1b440ec1ab10668191c4baa28ec632219d0d31eb2ee65fcb87a22fb8943cfbfded86f46f60c9cf894028339be04 --add-bls-key dd49b1b440ec1ab10668191c4baa28ec632219d0d31eb2ee65fcb87a22fb8943cfbfded86f46f60c9cf894028339be04

3. check in the all-active validators, if still there:
 ./hmy --node="https://api.s0.os.hmny.io" blockchain validator all-active

![image](https://user-images.githubusercontent.com/35432495/74110782-ae021500-4b8f-11ea-8c98-ed802e490624.png)

4.Check in the staking dashbord if is there: https://staking.harmony.one/validators
![image](https://user-images.githubusercontent.com/35432495/74110800-ca05b680-4b8f-11ea-9a48-5d3046a04e8d.png)

**Expected behavior**
The validator should not be there in the staking dashboard active validators

**Comment by sophoah** [comment]
something to take note the validator information still has the flag as active :
```
./hmy blockchain validator information one19zj0y47t54qhkqz3d8f2llnuhav9fw2dxyhlg7 -n https://api.s0.os.hmny.io
{
  "id": "0",
  "jsonrpc": "2.0",
  "result": {
    "active": true,
    "bls-public-keys": [
      "dd49b1b440ec1ab10668191c4baa28ec632219d0d31eb2ee65fcb87a22fb8943cfbfded86f46f60c9cf894028339be04"
    ],
```
not sure if that flag is the same

**Comment by BrunoMarshall** [comment]
The issue still happening, from my list of validators only 2 are running a node and are having bingos, not 4:
![image](https://user-images.githubusercontent.com/35432495/74911387-c3134b00-53bc-11ea-84a4-89427931a6ce.png)

**Comment by BrunoMarshall** [comment]
Its seems like after create a validator the status is True, independently if the node of that validator is running or not. Should be the opposite. After created is active:false and if the node reach consensus switch to active: True

**Comment by rlan35** [comment]
The active field of the validator is a field to indicate whether it's up for participating in the EPoS, not whether the validator is actually validating blocks. We should change the "status" field in the explorer or the field in backend to avoid confusion.

**Comment by sophoah** [comment]
@BrunoMarshall I think that one can be closed. Now it seems like when the flag active is false we are not elected, and we are elected when that flag is true.

**Comment by BrunoMarshall** [comment]
I confirm, with the latest version this issue is gone, Thank you all! highly appreciate!
i will close this issue
