### ISSUE TITLE
5 seconds BINGO

### ISSUE THREAD

**Issue by err0r711** [harmony-one/harmony#2237]
getting 5 seconds BINGO, mostly it's 8 seconds

{"level":"info","port":"9000","ip":,"blockNum":48513,"epochNum":612,"ViewId":48513,"blockHash":"0xda994cd1fcf0403ee3a4d1cece8cdae980d664dc2a2a677887297095a27e6d68","numTxns":0,"numStakingTxns":0,"caller":"/home/leochen/go/src/github.com/harmony-one/harmony/node/node_handler.go:410","time":"2020-02-10T11:51:31.136842508+01:00","message":"BINGO !!! Reached Consensus"}

{"level":"info","port":"9000","ip":","blockNum":48514,"epochNum":612,"ViewId":48514,"blockHash":"0x9098fd88466bfddc0a48120511f05b9d3638abbfaf6e1d4cf37089bab7c609f9","numTxns":0,"numStakingTxns":0,"caller":"/home/leochen/go/src/github.com/harmony-one/harmony/node/node_handler.go:410","time":"2020-02-10T11:51:36.878186598+01:00","message":"BINGO !!! Reached Consensus"}

shard 2

Kubuntu 18.04.3

**Comment by Daniel-VDM** [comment]
im running a node on shard 2 and I don't see this issue, can you reproduce it with latest?

**Comment by err0r711** [comment]
on shard 0 now, no 5 second blocks

**Comment by rlan35** [comment]
This could be a machine network specific issue. The first block may be delayed to your node so it appeared that block internal for next block is shorter than normal. If not reproducible. I will just close it for now.
