### ISSUE TITLE
Generating an excessive amount of validators (2,400+) potentially broke consensus on shard 0 on the staking network

### ISSUE THREAD

**Issue by SebastianJ** [harmony-one/harmony#2239]
**Describe the bug**
I wrote some new code for my testing framework that programmatically creates new validators.

I managed to create about 2,400 or so validators before consensus stopped on shard 0. The ~2,400 validators were created over the span of a couple of hours (averaging about 10 new validators every ~3 minutes or so).

**To Reproduce**
Mass create validators and keep on creating them, e.g. using a bash script + hmy or using a custom solution.

I won't be able to commit the code I've used until a couple of hours from now - I'll update the ticket as soon as this has been done.

**Expected behavior**
Shard 0 should withstand an increasing amount of validators and increasing usage of the shard 0-specific staking commands.

**Comment by fxfactorial** [comment]
Cause of the crash later found and fixed here https://github.com/harmony-one/harmony/commit/3c4d5074ae2b04a12d0c52bfe481fb3706a9d540

Closing but still need to continue doing large scale validator creation
