### ISSUE TITLE
Open staking validator node crash at start.

### ISSUE THREAD

**Issue by rlan35** [harmony-one/harmony#2241]
oroutine 1 [running]:
github.com/harmony-one/harmony/shard/committee.partialStakingEnabled.GetCommitteePublicKeys(0x0, 0x0, 0x1734bc0, 0xc000124da0)
        /home/leochen/go/src/github.com/harmony-one/harmony/shard/committee/assignment.go:226 +0x26
github.com/harmony-one/harmony/node.(*Node).InitConsensusWithValidators(0xc00023b180, 0xc000f66b40, 0x1f)
        /home/leochen/go/src/github.com/harmony-one/harmony/node/node.go:589 +0x240
main.setupConsensusAndNode(0xc00024e000, 0x0)
        /home/leochen/go/src/github.com/harmony-one/harmony/cmd/harmony/main.go:400 +0x75c
main.main()
        /home/leochen/go/src/github.com/harmony-one/harmony/cmd/harmony/main.go:539 +0x981
node.sh: node process finished with status 2
node.sh: restarting in 10s...
node.sh: ############### Running Harmony Process ###############
Staking mode; node key a689b39bb1de4f1591e29094b91d00596b0f371ea16fadf8b4143c680a1f9aff3e805e167eda2c583827ed0e7c8c9882 -> shard 0
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x888806]

**Comment by JB273** [comment]
When removing the "harmony_db_0" directory all works fine again, but then need to get into sync first, which could take some time when having a large DB...

**Comment by yelllowsin** [comment]
@rlan35 haven't had any issue with panic runtime error in the last versions of OSNT. Others might confirm it, but per my view this issue can be closed.

**Comment by janet-harmony** [comment]
Saw this error again while trying to upgrade Shard2 on OSTN (3/2).
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x890896]

goroutine 1 [running]:
github.com/harmony-one/harmony/shard/committee.partialStakingEnabled.GetCommitteePublicKeys(0x0, 0x0, 0x15ac0e0, 0xc000124ea0)
	/home/ec2-user/harmony/shard/committee/assignment.go:226 +0x26
github.com/harmony-one/harmony/node.(*Node).InitConsensusWithValidators(0xc000255880, 0xc000235ae0, 0x20)
	/home/ec2-user/harmony/node/node.go:610 +0x240
main.setupConsensusAndNode(0xc00022c1e0, 0x0)
	/home/ec2-user/harmony/cmd/harmony/main.go:422 +0x773
main.main()
	/home/ec2-user/harmony/cmd/harmony/main.go:561 +0x981
```

**Comment by fxfactorial** [comment]
It’s a data consistency issue , the db was corrupted and hence cant start up right . Clearing the DB should fix it but bigger issue is graceful shutdown
