### ISSUE TITLE
Node.sh give 404 when downloading

### ISSUE THREAD

**Issue by JB273** [harmony-one/harmony#2245]
**Describe the bug**
When running "./node.sh -d" with the fresh downloaded node.sh version form master it stops with:
`curl: (22) The requested URL returned error: 404 Not Found`
`node.sh: cannot download harmony.sig (status 22)`
`node.sh: download node software failed`

**To Reproduce**
1. curl -LOs https://raw.githubusercontent.com/harmony-one/harmony/master/scripts/node.sh
2. chmod u+x node.sh
3. ./node.sh -d

>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
>   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
> 100   799  100   799    0     0   3955      0 --:--:-- --:--:-- --:--:--  3955
> diff: md5sum.txt: No such file or directory
> curl: (22) The requested URL returned error: 404 Not Found
> node.sh: cannot download harmony.sig (status 22)
> node.sh: download node software failed

**Expected behavior**
All binaries and dependencies should download correctly

**Environment (please complete the following information):**
 - OS: Ubuntu 18.04

**Additional context**

**Comment by yelllowsin** [comment]
I can confirm i got the same issue:

```
curl -LOs https://raw.githubusercontent.com/harmony-one/harmony/master/scripts/node.sh && chmod u+x node.sh && curl -LOs https://harmony.one/hmycli && mv hmycli hmy && chmod u+x hmy
root@harmony-testing:/home/mariston_tantra# ./node.sh -d
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   799  100   799    0     0   6549      0 --:--:-- --:--:-- --:--:--  6549
diff: md5sum.txt: No such file or directory
curl: (22) The requested URL returned error: 404 Not Found
node.sh: cannot download harmony.sig (status 22)
node.sh: download node software failed
```

Environment (please complete the following information):

**OS: Debian 10 x64**

**Comment by SebastianJ** [comment]
This is related to the new signature functionality introduced [here](https://github.com/harmony-one/harmony/commit/c5d51951c1724434298b38220c577b8d1162da45)

Using latest commit:
```
$ curl -LOs https://raw.githubusercontent.com/harmony-one/harmony/master/scripts/node.sh && chmod u+x node.sh && ./node.sh -d
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   799  100   799    0     0   3733      0 --:--:-- --:--:-- --:--:--  3733
diff: md5sum.txt: No such file or directory
curl: (22) The requested URL returned error: 404 Not Found
node.sh: cannot download harmony.sig (status 22)
node.sh: download node software failed
```

Using the latest commit before PR #2155 was merged (also the workaround for now):
```
$ curl -LOs https://raw.githubusercontent.com/harmony-one/harmony/9dcae26f8add7aadf214cd723c97a85660ddf1ce/scripts/node.sh && chmod u+x node.sh && ./node.sh -d
diff: md5sum.txt: No such file or directory
node.sh: downloaded harmony
node.sh: downloaded wallet
node.sh: downloaded bootnode
node.sh: downloaded libmcl.so
node.sh: downloaded libbls384_256.so
node.sh: downloaded files are in staging direectory
```

**Comment by LeoHChen** [comment]
The signature verification is optional now. Use "-Y" to verify signature on official release.  Engineering build doesn't need to verify the signature.
