### ISSUE TITLE
Shard 0 is missing/ not shown ; api-endpoint down??

### ISSUE THREAD

**Issue by BrunoMarshall** [harmony-one/harmony#2259]
**Describe the bug**
when i check the balance for this account one1km7xg8e3xjys7azp9f4xp8hkw79vm2h3f2lade  the balance in shard 0 is not show/is missing

Example commands

./hmy balances one1km7xg8e3xjys7azp9f4xp8hkw79vm2h3f2lade
[,{"shard":1, "amount":0.000000000000000000},{"shard":2, "amount":0.000000000000000000}]
[ec2-user@ip-172-31-38-220 ~]$ ^C

OR

./hmy --node=https://api.s0.os.hmny.io/ balances one1km7xg8e3xjys7azp9f4xp8hkw79vm2h3f2lade
commit: v267-0d819bd, error: http status code not 200, received: 502
check hmy cookbook for valid examples or try adding a `--help` flag

**Expected behavior**
some minutes ago was working properly, showing the balance in all shards.

**Environment (please complete the following information):**
 - OS: [Linux AWS Red Hat
Harmony (C) 2020. hmy, version v267-0d819bd (edgar@harmony.one 2020-02-11T16:59:15-0800)

**tail -n 100 latest/zerolog*.log
{"level":"info","port":"9000","ip":"18.184.223.63","blockNum":18502,"hash":"0xc8f05b198d245b6a2d763c008d81368a73304a9bd3d88737de13f3fd5d26e972","caller":"/home/deploy/go/src/github.com/harmony-one/harmony/node/node_handler.go:423","time":"2020-02-12T21:37:40.998343275Z","message":"Added New Block to Blockchain!!!"}
{"level":"info","port":"9000","ip":"18.184.223.63","blockNum":18502,"epochNum":246,"ViewId":18502,"blockHash":"0xc8f05b198d245b6a2d763c008d81368a73304a9bd3d88737de13f3fd5d26e972","numTxns":0,"numStakingTxns":0,"caller":"/home/deploy/go/src/github.com/harmony-one/harmony/node/node_handler.go:446","time":"2020-02-12T21:37:40.998375388Z","message":"BINGO !!! Reached Consensus"}
{"level":"info","port":"9000","ip":"18.184.223.63","caller":"/home/deploy/go/src/github.com/harmony-one/harmony/node/node_handler.go:235","time":"2020-02-12T21:37:40.998402021Z","message":"broadcasting new block 18502, group hmy/testnet/0.0.1/client/beacon"}
{"level":"debug","port":"9000","ip":"18.184.223.63","count":0,"caller":"/home/deploy/go/src/github.com/harmony-one/harmony/core/tx_pool.go:469","time":"2020-02-12T21:37:40.998449584Z","message":"Reinjecting stale transactions"}
{"level":"info","port":"9000","ip":"18.184.223.63","shardNum":3,"myShardID":0,"blockNum":18502,"caller":"/home/deploy/go/src/github.com/harmony-one/harmony/node/node_cross_shard.go:36","time":"2020-02-12T21:37:41.013247837Z","message":"[BroadcastCXReceipts]"}
{"level":"info","port":"9000","ip":"18.184.223.63","toShardID":1,"myShardID":0,"blockNum":18502,"caller":"/home/deploy/go/src/github.com/harmony-one/harmony/node/node_cross_shard.go:49","time":"2020-02-12T21:37:41.013946995Z","message":"[BroadcastCXReceiptsWithShardID]"}
{"level":"info","port":"9000","ip":"18.184.223.63","ToShardID":1,"numCXReceipts":0,"caller":"/home/deploy/go/src/github.com/harmony-one/harmony/node/node_cross_shard.go:53","time":"2020-02-12T21:37:41.014033419Z","message":"[CXMerkleProof] No receipts found for the destination shard"}
{"level":"info","port":"9000","ip":"18.184.223.63","toShardID":2,"myShardID":0,"blockNum":18502,"caller":"/home/deploy/go/src/github.com/harmony-one/harmony/node/node_cross_shard.go:49","time":"2020-02-12T21:37:41.014042104Z","message":"[BroadcastCXReceiptsWithShardID]"}
{"level":"info","port":"9000","ip":"18.184.223.63","ToShardID":2,"numCXReceipts":0,"caller":"/home/deploy/go/src/github.com/harmony-one/harmony/node/node_cross_shard.go:53","time":"2020-02-12T21:37:41.014080607Z","message":"[CXMerkleProof] No receipts found for the destination shard"}
{"level":"debug","port":"9000","ip":"18.184.223.63","myEpoch":246,"myBlock":18503,"myViewID":18503,"phase":2,"mode":"Normal","Phase":"Commit","caller":"/home/deploy/go/src/github.com/harmony-one/harmony/consensus/consensus_service.go:199","time":"2020-02-12T21:37:41.014122587Z","message":"[ResetState] Resetting consensus state"}
{"level":"info","port":"9000","ip":"18.184.223.63","myEpoch":246,"myBlock":18503,"myViewID":18503,"phase":0,"mode":"Normal","From":18502,"To":18503,"caller":"/home/deploy/go/src/github.com/harmony-one/harmony/consensus/consensus_v2.go:285","time":"2020-02-12T21:37:41.014144375Z","message":"[TryCatchup] Caught up!"}
{"level":"debug","port":"9000","ip":"18.184.223.63","myEpoch":246,"myBlock":18503,"myViewID":18503,"phase":0,"mode":"Normal","caller":"/home/deploy/go/src/github.com/harmony-one/harmony/consensus/validator.go:301","time":"2020-02-12T21:37:41.014594392Z","message":"[OnCommitted] Start consensus timer"}
{"level":"debug","port":"9000","ip":"18.184.223.63","myEpoch":246,"myBlock":18503,"myViewID":18503,"phase":0,"mode":"Normal","caller":"/home/deploy/go/src/github.com/harmony-one/harmony/consensus/consensus_v2.go:331","time":"2020-02-12T21:37:42.338922875Z","message":"[ConsensusMainLoop] Ticker"}

**Comment by BrunoMarshall** [comment]
I´m still having bingos with the validator address one1km7xg8e3xjys7azp9f4xp8hkw79vm2h3f2lade

{"level":"info","port":"9000","ip":"18.184.223.63","blockNum":18521,"epochNum":246,"ViewId":18521,"blockHash":"0x0775a1a7b48a56b945eb7c2493cd02e9157cfff85fd207a85a9ff672523da995","numTxns":0,"numStakingTxns":0,"caller":"/home/deploy/go/src/github.com/harmony-one/harmony/node/node_handler.go:446","time":"2020-02-12T21:40:44.05051709Z","message":"BINGO !!! Reached Consensus"

**Comment by CryptosWolfOfAllStreets** [comment]
New Instance started - node running fine on Shard 1 - Upon creating a new validator now the following error is received : error: http status code not 200, received: 502

**Comment by AndyBoWu** [comment]
looks like one node is offline (or terminated by AWS, hopefully not)

34.207.70.140

**Comment by AndyBoWu** [comment]
@rlan35 @fxfactorial this is the error I fetched from e0 on OSTN
`
goroutine 11533838 [semacquire, 1 minutes]:
sync.runtime_SemacquireMutex(0xc00630bdac, 0x10f0c00, 0x1)
        /usr/local/go/src/runtime/sema.go:71 +0x47
sync.(*Mutex).lockSlow(0xc00630bda8)
        /usr/local/go/src/sync/mutex.go:138 +0xfc
sync.(*Mutex).Lock(...)
        /usr/local/go/src/sync/mutex.go:81
github.com/harmony-one/harmony/hmy.(*APIBackend).GetMedianRawStakeSnapshot(0xc00630bda0, 0x0)
        /home/ec2-user/harmony/hmy/api_backend.go:336 +0x5e0
github.com/harmony-one/harmony/internal/hmyapi/apiv1.(*PublicBlockChainAPI).GetMedianRawStakeSnapshot(0xc006121750, 0x0, 0x0, 0x0)
        /home/ec2-user/harmony/internal/hmyapi/apiv1/blockchain.go:509 +0x5a
reflect.Value.call(0xc00686e1e0, 0xc0060745a8, 0x13, 0x121f933, 0x4, 0xc0410097c8, 0x1, 0x1, 0x116b8c0, 0xc0063ce301, ...)
        /usr/local/go/src/reflect/value.go:460 +0x5f6
reflect.Value.Call(0xc00686e1e0, 0xc0060745a8, 0x13, 0xc0410097c8, 0x1, 0x1, 0x111f0c0, 0x40b6ed, 0xc0410097b8)
        /usr/local/go/src/reflect/value.go:321 +0xb4
github.com/ethereum/go-ethereum/rpc.(*Server).handle(0xc0068620f0, 0x15cae60, 0xc055214780, 0x15d6fa0, 0xc025b85950, 0xc047305560, 0xc025b859c0, 0x0, 0x10810c0)
        /home/ec2-user/go/pkg/mod/github.com/ethereum/go-ethereum@v1.8.27/rpc/server.go:309 +0x6b1
github.com/ethereum/go-ethereum/rpc.(*Server).exec(0xc0068620f0, 0x15cae60, 0xc055214780, 0x15d6fa0, 0xc025b85950, 0xc047305560)
        /home/ec2-user/go/pkg/mod/github.com/ethereum/go-ethereum@v1.8.27/rpc/server.go:330 +0x1c4
github.com/ethereum/go-ethereum/rpc.(*Server).serveRequest(0xc0068620f0, 0x15caf20, 0xc0125112c0, 0x15d6fa0, 0xc025b85950, 0xc05b38ca01, 0x1, 0x0, 0x0)
        /home/ec2-user/go/pkg/mod/github.com/ethereum/go-ethereum@v1.8.27/rpc/server.go:192 +0x3ff
github.com/ethereum/go-ethereum/rpc.(*Server).ServeSingleRequest(...)
        /home/ec2-user/go/pkg/mod/github.com/ethereum/go-ethereum@v1.8.27/rpc/server.go:223
github.com/ethereum/go-ethereum/rpc.(*Server).ServeHTTP(0xc0068620f0, 0x15c66a0, 0xc0484f36c0, 0xc042c65700)
        /home/ec2-user/go/pkg/mod/github.com/ethereum/go-ethereum@v1.8.27/rpc/http.go:257 +0x5a4
github.com/rs/cors.(*Cors).Handler.func1(0x15c66a0, 0xc0484f36c0, 0xc042c65700)
        /home/ec2-user/go/pkg/mod/github.com/rs/cors@v1.7.0/cors.go:219 +0x1b8
net/http.HandlerFunc.ServeHTTP(0xc0068970c0, 0x15c66a0, 0xc0484f36c0, 0xc042c65700)
        /usr/local/go/src/net/http/server.go:2007 +0x44
github.com/ethereum/go-ethereum/rpc.(*virtualHostHandler).ServeHTTP(0xc0068970e0, 0x15c66a0, 0xc0484f36c0, 0xc042c65700)
        /home/ec2-user/go/pkg/mod/github.com/ethereum/go-ethereum@v1.8.27/rpc/http.go:330 +0x1c1
net/http.serverHandler.ServeHTTP(0xc000217ce0, 0x15c66a0, 0xc0484f36c0, 0xc042c65700)
        /usr/local/go/src/net/http/server.go:2802 +0xa4
net/http.(*conn).serve(0xc05839e500, 0x15cae60, 0xc05128df00)
        /usr/local/go/src/net/http/server.go:1890 +0x875
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:2928 +0x384
`

**Comment by AndyBoWu** [comment]
@BrunoMarshall can you try again?

**Comment by BrunoMarshall** [comment]
yes, is working, will close this issue
