### ISSUE TITLE
hmy_getTransactionsHistory doesn't work on master

### ISSUE THREAD

**Issue by flicker-harmony** [harmony-one/harmony#2266]
**Describe the bug**
hmy_getTransactionsHistory returns empty array for any address now on master and works okay on s3. Checking out logs of explorer node with [Explorer] tag on master it only shows:
{"level":"error","port":"9099","ip":"127.0.0.1","caller":"/Users/vladlazarus/go/src/github.com/harmony-one/harmony/node/node_explorer.go:51","time":"2020-02-13T11:14:51.755087+03:00","message":"[Explorer] not have enough signature power"}
And
{"level":"error","port":"9099","ip":"127.0.0.1","msgBlock":3,"caller":"/Users/vladlazarus/go/src/github.com/harmony-one/harmony/node/node_explorer.go:62","time":"2020-02-13T11:14:19.041871+03:00","message":"[Explorer] Failed to verify the multi signature for commit phase"}
Which means it doesn't commit any blocks into explorer storage.

Instead it should show logs [Explorer] Adding new block for explorer node or [Explorer] Committing block into explorer DB.

The only differences in implementation where it fails and might be related to staking protocol upgrade is:
master: https://github.com/harmony-one/harmony/blob/master/node/node_explorer.go#L50 
s3: https://github.com/harmony-one/harmony/blob/s3/node/node_explorer.go#L52

**To Reproduce**
Just run localnet on master and checkout zerolog for node with 9099 port - explorer node. You can find explorer logs with [Explorer] in log messages.

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: [Linux, MacOS]
- Go environment [ ```go env``` ]

**Additional context**

**Comment by gupadhyaya** [comment]
I have come across this bug before. Mainly for non-shard-0-explorer is set to shard-0 config by default here: https://github.com/harmony-one/harmony/blob/master/cmd/harmony/main.go#L260

We can initialize account using shardID: `initialAccount = &genesis.DeployAccount{ShardID: uint32(*shardID)}`
here: https://github.com/harmony-one/harmony/blob/master/cmd/harmony/main.go#L117
