### ISSUE TITLE
[Feature] use user defined signal to trigger graceful shutdown during rolling update

### ISSUE THREAD

**Issue by LeoHChen** [harmony-one/harmony#2271]
# Problem/limitation At Hand

WE need to gracefully shutdown the node program so that the DB cache can be flushed to disk.  This is especially needed for rolling update.  In addition to system signal, we can define a USER signal, so that we can just trigger the user signal to the node, before we do any shutdown operation.

**Which component?**

- [ ] consensus
- [ ] deploy script
- [ ] wallet
- [ ] explorer
- [x] node program
- [ ] test automation
- [ ] demo app
- [ ] others ...
- [x] rolling update script

# Proposed Solution

# Alternatives Considered

# Additional Context

**Comment by yelllowsin** [comment]
Graceful shutdown is working correctly on OSNT, you can close this issue @LeoHChen
