### ISSUE TITLE
hmy timeout/wait-for-confirmation doesn't return straight away when the error is available

### ISSUE THREAD

**Issue by sophoah** [harmony-one/harmony#2276]
**Describe the bug**
wait for confirmation for a staking tx 40s has been implemented by default. Issue is that when testing a failure scenarios, the 40s or the timeout set (tested with 3, 8, 10, 20, 30, 60, 120) never stop before (when error is available) and always run until the timeout setting.  

verified with a timeout of 2 min and while waiting, I've verified a new error message appeared in : ``` ./hmy failures staking --node="https://api.s0.os.hmny.io"```

Final result is always the same : 
```
Could not confirm 0xfe635a8014a6c1f80eba178ba934844da017ba91299793be63e08615e08ca3c7 even after 40 seconds
error: one1u6c4wer2dkm767hmjeehnwu6tqqur62gx9vqsd: staking validator already exists
```
so the error is shown correctly at the end, however whatever timeout we use, that timeout is never cut short.

**To Reproduce**
1. do a failed staking tx 
2. verify in the failure staking contain the error
3. verify the timeout is not cut short

**Expected behavior**
when the error is available in the staking error pool, don't wait until for the full timeout

**Screenshots**
N/A

**Environment (please complete the following information):**
 - hmy ```v282-5d54265```

**Additional context**
note that normal tx doesn't have such problem, the below happens fast:
```
./hmy transfer --from-shard 2 --to-shard 0 --from one1u6c4wer2dkm767hmjeehnwu6tqqur62gx9vqsd --to one1pdv9lrdwl0rg5vglh4xtyrv3wjk3wsqket7zxy --amount 1000000
{
  "errors": [
    "[2020-02-18 12:32:26.589305] [Plain transaction] insufficient balance of 89999.999979000000000000 in shard 2 for the requested transfer of 1000000.000000000000000000 -- 2020-02-18 13:32:26 +0100 CET",
    "[2020-02-18 12:32:26.589309] transaction has bad parameters",
    "[2020-02-18 12:32:26.589335] Failed to confirm transaction"
  ],
  "time-signed-utc": "2020-02-18 12:32:26.493350"
}
commit: v282-5d54265, error: Failed to confirm transaction
check hmy cookbook for valid examples or try adding a `--help` flag
```

**Comment by mindstyle85** [comment]
can confirm this

**Comment by Daniel-VDM** [comment]
fixed in latest version of CLI
