### ISSUE TITLE
Could not find error message - tx looks like failed

### ISSUE THREAD

**Issue by mindstyle85** [harmony-one/harmony#2278]
./hmy --node="https://api.s0.os.hmny.io" staking delegate --delegator-addr one1675d7adqu9egn0ehd9fx4f6jmdjfynw3gkr48q --validator-addr one1s7fp0jrmd97estwye3mhkp7xsqf42vn5x2sfqy --amount 90000 --chain-id testnet --passphrase

Enter passphrase:
Repeat the passphrase:

Could not confirm 0x56f05d27ef58be3ba20c348e55b0a96afe7fe4e7638582fa5d6f264fe4a1d11e even after 40 seconds
could not find error msg
Try increasing the wait-for-confirm

**Comment by Daniel-VDM** [comment]
I think this is fine. The error message doesn't say that the tx failed. I added a message to suggest looking up the tx by hash and also changed the tx logic to look for a tx receipt b4 looking for errors and trying again

**Comment by mindstyle85** [comment]
problem is this tx is odd, i dont find it in explorer and by querying i get this (note that from and to addresses are not the same as above)

./hmy --node="https://api.s0.os.hmny.io" blockchain transaction-receipt 0x56f05d27ef58be3ba20c348e55b0a96afe7fe4e7638582fa5d6f264fe4a1d11e 
{
  "id": "0",
  "jsonrpc": "2.0",
  "result": {
    "blockHash": "0xb9c83df8dc8f1ef968c092d5463761a1d2fde947da89ff7ed00a61597fd86346",
    "blockNumber": "0x130a",
    "contractAddress": null,
    "cumulativeGasUsed": "0x5208",
    "from": "one1rr5afef0her5e4l08325mtcx3qdg3ja0c0kfgs",
    "gasUsed": "0x5208",
    "logs": [],
    "logsBloom": "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
    "shardID": 0,
    "status": "0x1",
    "to": "one1jxklaf47q0cdzy93e8pzd6wdeszq8cm284xdfz",
    "transactionHash": "0x56f05d27ef58be3ba20c348e55b0a96afe7fe4e7638582fa5d6f264fe4a1d11e",
    "transactionIndex": "0x0"
  }
}

**Comment by mindstyle85** [comment]
this one is odd, i cant find the tx hash on explorer, and if i query it via hmy, i get two completely different addresses than the ones i used:


./hmy --node="https://api.s0.os.hmny.io" blockchain transaction-receipt 0x56f05d27ef58be3ba20c348e55b0a96afe7fe4e7638582fa5d6f264fe4a1d11e
{
  "id": "0",
  "jsonrpc": "2.0",
  "result": {
    "blockHash": "0xb9c83df8dc8f1ef968c092d5463761a1d2fde947da89ff7ed00a61597fd86346",
    "blockNumber": "0x130a",
    "contractAddress": null,
    "cumulativeGasUsed": "0x5208",
    "from": "one1rr5afef0her5e4l08325mtcx3qdg3ja0c0kfgs",
    "gasUsed": "0x5208",
    "logs": [],
    "logsBloom": "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
    "shardID": 0,
    "status": "0x1",
    "to": "one1jxklaf47q0cdzy93e8pzd6wdeszq8cm284xdfz",
    "transactionHash": "0x56f05d27ef58be3ba20c348e55b0a96afe7fe4e7638582fa5d6f264fe4a1d11e",
    "transactionIndex": "0x0"
  }
}

**Comment by mindstyle85** [comment]
this is also strange, tried collecting rewards:

./hmy --node="https://api.s0.os.hmny.io" staking collect-rewards --delegator-addr one1675d7adqu9egn0ehd9fx4f6jmdjfynw3gkr48q --chain-id testnet --passphrase
Enter passphrase:
Repeat the passphrase:

Could not confirm 0x9351601af8dc7bc42788e9020cdb337a16b4f60d31836583e697c85ad27f7408 even after 40 seconds
could not find error msg
Try increasing the wait-for-confirm


while this should have return a positive confirmation, since the address is delegating:

./hmy blockchain delegation by-delegator one1675d7adqu9egn0ehd9fx4f6jmdjfynw3gkr48q --node="https://api.s0.os.hmny.io"
{
  "id": "0",
  "jsonrpc": "2.0",
  "result": [
    {
      "Undelegations": [],
      "amount": 9.985e+22,
      "delegator_address": "one1675d7adqu9egn0ehd9fx4f6jmdjfynw3gkr48q",
      "reward": 102795104204089100000,
      "validator_address": "one1s7fp0jrmd97estwye3mhkp7xsqf42vn5x2sfqy"
    }
  ]
}

**Comment by CryptosWolfOfAllStreets** [comment]
Trying to replicate Mindstyles first test above : 

./hmy --node="https://api.s0.os.hmny.io" staking delegate --delegator-addr one1pjusejwj3xug79tag35jxyrvl4zj0xma0dpemq	--validator-addr one1p89hf0zc594jckj3twz6hdxnth2vlhkfpwe6f0 --amount 90000 --chain-id testnet --passphrase

Enter passphrase:
Repeat the passphrase:

received the following error: 
Could not confirm 0xb2d8ef39d76b4330a60edae8b349050c9f7959c693a5b2d8e3900d09773e9291 even after 40 seconds
error: total-delegated 0 own-current-balance 99979000000000000 amount-to-delegate 90000000000000000000: insufficient balance to stake


Even after reducing stake amount to 9000 then 900 then 90 then 9 received the same error balance insufficient - the balance is actually fully funded 100k

**Comment by CryptosWolfOfAllStreets** [comment]
for the collecting of rewards i confirm the same error : 

root@WOLF18FEB:~# ./hmy --node="https://api.s0.os.hmny.io" staking collect-rewards --delegator-addr one1p89hf0zc594jckj3twz6hdxnth2vlhkfpwe6f0 --chain-id testnet --passphrase
Enter passphrase:
Repeat the passphrase:

Could not confirm 0x4ac17f333f08315fa46f40b169effeeb59d8342b3eddaf9ea35eb53f440e55ee even after 40 seconds
could not find error msg
Try increasing the wait-for-confirm
root@WOLF18FEB:~#

**Comment by Daniel-VDM** [comment]
Ah, that CLI function calls `hmy_getTransactionByHash` RPC which is not `hmy_getStakingTransactionByHash` (specific for staking). But upon closing inspection, I noticed that the getTxByHash gave wrong txn back, notice how the hashes don't match:

![image](https://user-images.githubusercontent.com/31291913/74781539-7f063600-5256-11ea-80bc-5ad6717dae76.png)

Will add functionality to get staking tx by hash / get staking tx receipt. But will need to look into this first issue. This is partially also why Wolf's txns are giving weird responses.

**Comment by mindstyle85** [comment]
ah i see, so nothing that serious after all :)

**Comment by mindstyle85** [comment]
though how is it possible it found the same hash as a tx then? if yourre separating staking txs and regular ones, shouldnt they never cross over?

**Comment by Daniel-VDM** [comment]
> though how is it possible it found the same hash as a tx then? if yourre separating staking txs and regular ones, shouldnt they never cross over?

I think it has to do with staking logic (like transaction done internally). Will ask RJ to confirm this, and escalate if needed.
