### ISSUE TITLE
TUI not showing BINGO

### ISSUE THREAD

**Issue by err0r711** [harmony-one/harmony#2291]
2020-02-21T10:29:29.294658635+01:00","message":"BINGO !!! Reached Consensus"}
2020-02-21T10:30:59.611401684+01:00","message":"BINGO !!! Reached Consensus"}

![tui](https://user-images.githubusercontent.com/31262326/75022935-3db09900-5497-11ea-9198-7a791ef5b372.jpeg)

kubtuntu 18.04

**Comment by BrunoMarshall** [comment]
Hi @err0r711 , did you have again this issue?
I couldn´t succeed to recreate this issue, the only explanation is that there is a gap/delay between the hmy and TUI, aparently TUI is only sync X Time

**Comment by err0r711** [comment]
it's always on my tui like that.
