### ISSUE TITLE
[Feature] cross-shard transaction history

### ISSUE THREAD

**Issue by LeoHChen** [harmony-one/harmony#2300]
# Problem/limitation At Hand

To our exchange and wallet partners, they need to query one API to return all the tx records for one address in a certain shard.  The use case, for example, user has an account in B exchange, B exchange runs on shard0.  The user transferred token from his shard3 account to shard0. The balance is correct on B exchange during the query, but there is no tx history can be queried in shard0, as shard0 is the receiving shard, not the sending shard.  Only the sending shard has the tx history right now.  We need to find a solution to build one query/end point, so that user can query the tx record even from cross-shard transaction.  This is need for every shard as well as receiving shard.

**Which component?**

- [x] RPC
- [x] cross-shard tx
- [ ] consensus
- [ ] deploy script
- [ ] wallet
- [ ] explorer
- [ ] node script
- [ ] test automation
- [ ] demo app
- [ ] others ...

# Proposed Solution

# Alternatives Considered

# Additional Context

**Comment by rlan35** [comment]
The rpc should first check the destination shard (e.g. shard 0) for the cross-shard receipt. And if there is a receipt for the transaction, then go to the corresponding source shard (e.g. shard 1) to get the raw transaction content.

**Comment by flicker-harmony** [comment]
@rlan35 it saves tx for both receiver and sender, so there shouldn't be a problem considering that cross shard tx is included in both shards blocks right?

**Comment by flicker-harmony** [comment]
I see, raw cross shard tx is included only on sender end. I'd make separate API to get cross-shard tx receipts history, which should be included on both ends. Then devs can query raw tx from corresponding shard if needed.
