### ISSUE TITLE
[Feature] Add RPC to get avg price of txs in tx pool. 

### ISSUE THREAD

**Issue by Daniel-VDM** [harmony-one/harmony#2319]
# Problem/limitation At Hand

When the tx pool gets filled (from say txs that have too high of a nonce), the default gas on all of our tools won't be enough. This presents some usability issues. We should provide an RPC to get avg price of txs in the pool. 

**Which component?**
Transaction Pool & RPC

# Additional Context

During the stress test on 2/26/20, we had tx pool fill up and had to manually set gas price for new transactions to go through.

**Comment by LeoHChen** [comment]
already supported via ethereum api
