### ISSUE TITLE
Expand slashing unit testing 

### ISSUE THREAD

**Issue by fxfactorial** [harmony-one/harmony#2330]
slashing unit tests currently check at the slash rate of 2% and 80%. 

Need to expand this to slashing rates of (2, 100]% testings. 

basically just need to programmatically make more scenarios and loop over the 2-100% logic, 

see here for an example of how to kick it off, just need to make more scenarios

https://github.com/harmony-one/harmony/blob/master/staking/slash/double-sign_test.go#L463

**Comment by denniswon** [comment]
need to do a scenario where you have the block header which has slashed and apply it to state like how blocks are verified in general via state process
