### ISSUE TITLE
Staking explorer - with harmony extension - yellow text difficult to read

### ISSUE THREAD

**Issue by BrunoMarshall** [harmony-one/harmony#2345]
## Summary
If we need to stake all tokens to a validator, the error message is difficult to read because of the yellow color:

![image](https://user-images.githubusercontent.com/35432495/75611154-2e28f400-5b18-11ea-9c78-ce0b3ae04bb8.png)

**** Also average user doesn't want to discount the fees to send the max amount, bad design if you can add the fees automatically to the sum

**Comment by yelllowsin** [comment]
We currently have two different logics on how to deal with fees when signing txs on dashboard. First one that is shown by @BrunoMarshall above asks for the user to calculate the fees whenever he want's to send the max amount. The other one, which is in my view the best one and correct, is when the dashboard calculates the fee automatically for you and adds it to the tx.



Parts that are OK (good design):

- Claim Rewards
- Unstake

Example of Unstake working nicely (fees calculates automatically):
![undelegate](https://user-images.githubusercontent.com/7217595/75611434-3a518900-5af9-11ea-81cd-1355648e6d63.jpg)
![image](https://user-images.githubusercontent.com/7217595/75611470-93212180-5af9-11ea-8f2a-60de8ebd8ac1.png)

Parts that are NOT OK (bad design):

- Transfer funds
- Stake

Example of Transfer funds where fees are not calculated automatically:

![image](https://user-images.githubusercontent.com/7217595/75611503-cd8abe80-5af9-11ea-911b-c74e7d664a4b.png)

**The best solution would be implement the same design on Transfer Funds and Stake and thus get rid of the yellow annoying message as it will not be needed anymore.** @mikedoan

**Comment by mikedoan** [comment]
fixed
