### ISSUE TITLE
[staking dashboard] voting power calculated incorrectly

### ISSUE THREAD

**Issue by gizemcakil** [harmony-one/harmony#2349]
**Describe the bug**
Voting power field in the validator list shows different voting power for similar stake volumes.

**Screenshots**

<img width="1103" alt="image" src="https://user-images.githubusercontent.com/45907268/75614812-636e1b80-5af1-11ea-9295-51cf54498a37.png">

**Comment by fxfactorial** [comment]
it matters whether total one staked is pre or post EPoSed processing

**Comment by BrunoMarshall** [comment]
Here the voting power from 03-03-2020
![image](https://user-images.githubusercontent.com/35432495/75756551-1e382c80-5d31-11ea-965c-022a88555e71.png)
I seems that this voting power is within the shard, if the validator "R" is alone in his specific shard, then the values probably are correct.
is required more testing

**Comment by mikedoan** [comment]
the new calculation by discussing with rj - is to take the sum of voting-power returned by hmy_getSuperCommittees  in all shards (4 shards) and divide it by 4.

**Comment by BrunoMarshall** [comment]
Thank you @mikedoan

**Comment by mindstyle85** [comment]
@mikedoan current voting power seems broken:

![screens](https://user-images.githubusercontent.com/55639830/75884162-9d5a5d00-5e24-11ea-93cf-1d11f0d2c413.png)

**Comment by yelllowsin** [comment]
Steps to reproduce the issue:

1. Access page: https://staking.harmony.one/validators with a signed account.
![glitch](https://user-images.githubusercontent.com/7217595/75897785-e1933080-5e17-11ea-817f-79ebbfd66665.jpg)
2. Now click in any of the validators list and then hit the Back button on the browser. You are left with voting power changing:
![voting_power](https://user-images.githubusercontent.com/7217595/75897896-0be4ee00-5e18-11ea-9842-b0c22e1fe541.jpg)
