### ISSUE TITLE
GetStakingInfo unable to decode: rlp: too few elements for struct

### ISSUE THREAD

**Issue by mindstyle85** [harmony-one/harmony#2359]
**Describe the bug**

got this today:

node.sh: ############### Running Harmony Process ###############
Staking mode; node key e429cbf74e8ab28ed295999d179ad79827c7febe0208a6145aa91bbb60b68a0b1907de4c38573352cafe00c8105b1116 -> shard 2
GetStakingInfo unable to decode: rlp: too few elements for struct { Epoch *big.Int; NumBlocksToSign *big.Int "rlp:\"nil\""; NumBlocksSigned *big.Int "rlp:\"nil\"" }, decoding into (types.ValidatorWrapper).Snapshot
GetStakingInfo unable to decode: rlp: too few elements for struct { Epoch *big.Int; NumBlocksToSign *big.Int "rlp:\"nil\""; NumBlocksSigned *big.Int "rlp:\"nil\"" }, decoding into (types.ValidatorWrapper).Snapshot
GetStakingInfo unable to decode: rlp: too few elements for struct { Epoch *big.Int; NumBlocksToSign *big.Int "rlp:\"nil\""; NumBlocksSigned *big.Int "rlp:\"nil\"" }, decoding into (types.ValidatorWrapper).Snapshot

Harmony (C) 2020. harmony, version v5606-v1.3.2-0-g42db637c (deploy@ 2020-03-02T18:19:43+0100)

somehow i get the v5606 version even though i got v5617 before with the same commands:
bash <(curl -sSL https://raw.githubusercontent.com/SebastianJ/harmony-tools/master/install/install.sh) --staking --node

after this i also do ./node.sh -d

**Comment by fxfactorial** [comment]
This is dated , method getstakinginfo shouldn’t exist anymore , something is outdated

**Comment by mindstyle85** [comment]
yeah i figured as much, but no idea how seb's tool downloaded me this version, when it successfully downloaded me v5617 just a few hours before
