### ISSUE TITLE
node.sh stopped bingoing v5637

### ISSUE THREAD

**Issue by mindstyle85** [harmony-one/harmony#2381]
**Describe the bug**

I ran my validator with multibls (2 keys) on shard 2, with binary v5637 on Ubuntu 16.04. It worked for a while then stopped producing bingos, this is the log errors:

`{"level":"info","port":"9000","ip":"XXXXXX","error":"leveldb: not found","dataLen":0,"caller":"/mnt/jenkins/workspace/harmony-release/harmony/core/blockchain.go:1967","time":"2020-03-05T00:44:23.433997701+01:00","message":"ReadPendingCrossLinks"}`

`{"level":"warn","port":"9000","ip":"XXXXXX","hostID":"QmQTgbRiX9zLyhGVrokji2pWf9NnaKTZH1WPto3k4NK5hd","error":"failed to dial : all dials failed\n  * [/ip4/164.68.120.87/tcp/9000] dial tcp4 0.0.0.0:9000->164.68.120.87:9000: i/o timeout","peer":{"IP":"164.68.120.87","Port":"9000","ConsensusPubKey":{},"Addrs":null,"PeerID":"QmTFpz25pwPcTQ8zLsSHicgzUGDcWCJKLfvbe9vp9AQHoa"},"caller":"/mnt/jenkins/workspace/harmony-release/harmony/p2p/host/hostv2/hostv2.go:307","time":"2020-03-05T00:40:10.694024041+01:00","message":"can't connect to peer"}`

then i tried to restart the node and got:

```
node.sh: ############### Running Harmony Process ###############
Staking mode; node key 1c57c3282714e412d974a5c1c5712f1f6062d3253d9a080580abf4342805e3311c19f81bef5b1a903fe282650b767a12e429cbf74e8ab28ed295999d179ad79827c7febe0208a6145aa91bbb60b68a0b1907de4c38573352cafe00c8105b1116 -> shard 2
ERROR cannot configure node: cannot create P2P network host: cannot initialize libp2p host: failed to listen on any addresses: [listen tcp4 0.0.0.0:9000: listen: address already in use]
node.sh: node process finished with status 1
```

stopped it again and started it with sudo, finally worked, got bingos, but also error messages:

`{"level":"info","port":"9000","ip":"XXXXX","blockNum":2209,"epochNum":29,"ViewId":2209,"blockHash":"0xd746aeca70bc8dc8b20142237d09f0ad1e361180ca8a7586afb673b90424c0a0","numTxns":0,"numStakingTxns":0,"caller":"/mnt/jenkins/workspace/harmony-release/harmony/node/node_handler.go:437","time":"2020-03-05T00:59:08.692945224+01:00","message":"BINGO !!! Reached Consensus"}`

```
{"level":"error","port":"9000","ip":"XXXXXX","shardID":2,"error":"cannot open chain database: resource temporarily unavailable","caller":"/mnt/jenkins/workspace/harmony-release/harmony/node/node.go:234","time":"2020-03-05T00:59:30.493342494+01:00","message":"cannot get shard chain"}
{"level":"error","port":"9000","ip":"XXXXXX","error":"cannot open chain database: resource temporarily unavailable","caller":"/mnt/jenkins/workspace/harmony-release/harmony/node/node.go:243","time":"2020-03-05T00:59:30.493379436+01:00","message":"cannot get beaconchain"}
```

**Comment by AndyBoWu** [comment]
@gupadhyaya  for your attention

**Comment by gupadhyaya** [comment]
@mindstyle85 steps to reproduce?

**Comment by mindstyle85** [comment]
@gupadhyaya 

basically what above, but this is not due to multi bls i believe,  this is a node.sh issue and not using sudo on the launch command. 

I was able to reproduce it today basically the same way, ubuntu 16.04 OS -> v5637 binary and node.sh, start it without sudo. In the logs you should see the tcp errors. 

Then next, this error below is due to graceful shutdown not completely shutting down it seems (or takes some time to fully shut down):
```
node.sh: ############### Running Harmony Process ###############
Staking mode; node key 1c57c3282714e412d974a5c1c5712f1f6062d3253d9a080580abf4342805e3311c19f81bef5b1a903fe282650b767a12e429cbf74e8ab28ed295999d179ad79827c7febe0208a6145aa91bbb60b68a0b1907de4c38573352cafe00c8105b1116 -> shard 2
ERROR cannot configure node: cannot create P2P network host: cannot initialize libp2p host: failed to listen on any addresses: [listen tcp4 0.0.0.0:9000: listen: address already in use]
node.sh: node process finished with status 1
```

Lastly i tried again  with sudo on node launch command and it worked. Sorry i dont have anything more but this is how it happened to me, hope its enough to check.

**Comment by gupadhyaya** [comment]
@mindstyle85 can you check again to confirm if this is not fixed? Thanks.

**Comment by mindstyle85** [comment]
@gupadhyaya seems this is not happening anymore for the last few versions, so closing this for now
