### ISSUE TITLE
inactive validator with 100 keys was in comittee but didnt sign any blocks at all

### ISSUE THREAD

**Issue by mindstyle85** [harmony-one/harmony#2388]
**Describe the bug**

So this validator that was created a few hours ago was in the comittee for a few hours, till epoch 97 (height over 7k blocks), while it was created at block height 4052. It has 1 ONE staked and 100 bls keys attached, so it brought down the median to 0.01 ONE, all the while it signed NO blocks. For reference, this validator was created by @SebastianJ 

./hmy -n https://api.s0.os.hmny.io blockchain validator information one1llgdrgxmtu2xwa7q72h2dxugawl72f3sa69gzp
{
  "id": "0",
  "jsonrpc": "2.0",
  "result": {
    "active": false,
    "address": "one1llgdrgxmtu2xwa7q72h2dxugawl72f3sa69gzp",
    "availability": {
      **"num-blocks-signed": 0,
      "num-blocks-to-sign": 5377**
    },
    "banned": false,
    "bls-public-keys": [
100 keys here
  **"creation-height": 4052,**
    "delegations": [
      {
        "amount": 1000000000000000000,
        "delegator-address": "one1llgdrgxmtu2xwa7q72h2dxugawl72f3sa69gzp",
        "reward": 0,
        "undelegations": []
      }
    ],
    "details": "https://www.youtube.com/watch?v=QQNL83fhWJU",
    "identity": "MrBubz",
    **"last-epoch-in-committee": 97,**
    "max-change-rate": "0.050000000000000000",
    "max-rate": "0.500000000000000000",
    "max-total-delegation": 1e+21,
    "min-self-delegation": 1000000000000000000,
    "name": "Bubz",
    "rate": "0.100000000000000000",
    "security-contact": "Bubz Hacker Legion",
    "update-height": 4052,
    "website": "https://i.imgur.com/G6Mruca.jpg"
  }
}

**Comment by mindstyle85** [comment]
bump @fxfactorial @rlan35

**Comment by fxfactorial** [comment]
Should be fixed in https://github.com/harmony-one/harmony/pulls

**Comment by mindstyle85** [comment]
so fixed upon next restart/upgrade?

**Comment by fxfactorial** [comment]
Yes should be
