### ISSUE TITLE
median stake is wrong

### ISSUE THREAD

**Issue by mindstyle85** [harmony-one/harmony#2389]
**Describe the bug**
 
this derives from https://github.com/harmony-one/harmony/issues/2388

After @SebastianJ made another bubz validator with 100 keys and 1 ONE stake, and this validator left comittee after several hours, the median stake is still left at 0.01 ONE:

./hmy blockchain median-stake --node="https://api.s0.os.hmny.io"
{
  "id": "0",
  "jsonrpc": "2.0",
  "result": 10000000000000000
}

the bubz validator is out of comittee for about 2 hours now, but the median stake is from right now

**Comment by mindstyle85** [comment]
to update, the median stake is still at 0.01

**Comment by mindstyle85** [comment]
on today's version v5650 it happened again.. @SebastianJ created a few non active validators which caused median stake to go below 1, now that those validators are kicked out of comittee (20-30min after), the median is still below 1 @fxfactorial @rlan35

**Comment by SebastianJ** [comment]
This issue is still possible to reproduce, even after the new OSTN release using master/commit `51d5280e`

**Comment by SebastianJ** [comment]
This is still possible to reproduce on latest versions of OSTN - 1 self-stake validators with 200 bls keys (1/200 = 0.005 stake) will set the median stake to 0.005 for the entire network (which will appear as 0 effective median stake on the staking explorer).

**Comment by mindstyle85** [comment]
@SebastianJ can you try this on STN now?
