### ISSUE TITLE
Reduce RPC API codebase

### ISSUE THREAD

**Issue by flicker-harmony** [harmony-one/harmony#2395]
## Summary

Using interfaces and golang struct "inheritance" remove common methods from v1 and v2 versions.

## Current Design

Right now many methods are just common and copied for both v1 and v2 versions.

## Problems

Double codebase makes adding features more difficult and supporting both APIs. Even though we will use just v2 version in future, still double v1 codebase is bad.

## Proposal

Using interfaces and golang struct "inheritance" remove common methods from v1 and v2 versions. Make 3 interfaces. General API interface. v1 and v2 interfaces for different methods. Then 3 structs. General API struct. And derived v1 and v2 API structs with different methods. It will reduce API codebase by at least 30%.

**Comment by LeoHChen** [comment]
already done
