### ISSUE TITLE
Support different passwords for multi BLS keys

### ISSUE THREAD

**Issue by yelllowsin** [harmony-one/harmony#2398]
Currently latest `node.sh` version only supports one password to load all BLS keys using parameter -M. As discussed on Discord @gupadhyaya, please add support for a different password on each BLS key. Command used to run the node:

`./node.sh -M -N staking -z -S`

Node Version:

```
./node.sh -V
Harmony (C) 2020. harmony, version v5637-master-20191208.0-260-g285e1423 (jenkins@ 2020-03-04T19:09:09+0000)
```

**Comment by BrunoMarshall** [comment]
have the same issue. I´m doing different passwords for different BLS keys.
Running the node is only asking 1 password.

**Currently ALL BLS keys inside the folder need to have the same password**
- Solution founded was to create new BLS keys with the same password. 

Question: do we really need password for BLS keys? Based in the fact that the wallet creation has the option to add password

**Comment by yelllowsin** [comment]
Minor design improvement. When this is implemented, if you could also break the line for every BLS keys used when running the node for better visualization it would be nice:

![image](https://user-images.githubusercontent.com/7217595/76337977-ddaf5480-62d6-11ea-9cae-14fc8258e01b.png)
