### ISSUE TITLE
Validator becomes non-elected if I try to do multiBLS with keys from different shards, attaching to same instance

### ISSUE THREAD

**Issue by gizemcakil** [harmony-one/harmony#2403]
**Describe the bug**
MultiBLS wrong use causes validator to be kicked out completely

**To Reproduce**
- Validator has been running with 1 BLS key
- Generated 2 new BLS keys and ran the staking node within the same tmux window
- BLS keys are in different shards: 1 key is in shard-1, 1 key is shard-3
Output: 
- Explorer shows 3 nodes in my validator account
- Validator became 'not-elected' after adding the BLS key in different shard (validator still should have enough stake per node to be elected)

@Daniel-VDM 

**Expected behavior**

**Screenshots**
<img width="1601" alt="Screen Shot 2020-03-05 at 8 22 30 PM" src="https://user-images.githubusercontent.com/45907268/76051272-1a69fd00-5f1f-11ea-8de7-0ac1e642b80c.png">

**Environment (please complete the following information):**
 - OS: [Linux, MacOS]
- Go environment [ ```go env``` ]

**Additional context**

**Comment by Daniel-VDM** [comment]
Protocol won't allow you to have a validator with keys for different shards now.
