### ISSUE TITLE
separate ops environments for testnets vs mainnet 

### ISSUE THREAD

**Issue by lijiang2087** [harmony-one/harmony#2412]

**Comment by LeoHChen** [comment]
The mainnet devop host is setup with mainnet environment. The next step is to add harmony-node.pub to all the legacy nodes `~/.ssh/authorized_keys` file, then we can just use one key to access all mainnet nodes.  

The `harmony-node.pub` key is right now in mainnet devhost `/usr/local/confg/` directory. Please checkout the latest nodedb, and append this pubkey to all legacy nodes.

**Comment by AndyBoWu** [comment]
I have added `harmony-node.pub` to every single legacy node on the mainnet. Also, I did some QA on my side to make sure the pub key did get added into the file.
