### ISSUE TITLE
S0 syncing is really long for staking network

### ISSUE THREAD

**Issue by Daniel-VDM** [harmony-one/harmony#2425]
**Describe the bug**
Syncing a node on shard 0 of the open staking network is taking a really long time. Compared to non-beacon shards. I presume it has to do with replaying the staking transactions.

**To Reproduce**
1. Create a new validator on OSTN and make sure that you have a s0 BLS key.
2. Start syncing and check progress with `./hmy blockchain latest-header` 

**Expected behavior**
Faster syncing for shard 0.

**Timestamps of syncing**
* 5:59 PM block 0 
* 6:01 PM block 1652
* 7:23 PM block 18913
* 7:30 PM block 20163
* 7:47 PM block 23014
* 7:55 PM block 24485 (done)

**Comment by mindstyle85** [comment]
I can confirm, we have already  talked about this with @fxfactorial , basically when syncing i see something named validator snapshot (a huge wall of text afterwards), those take a long time to sync and usually pause after each snapshot. Took me about 30min to sync 8k blocks at that time

**Comment by rlan35** [comment]
@SebastianJ can you help do a CPU profiling on a sync'ing node? @Daniel-VDM can post more logs on the sync'ing.

**Comment by Daniel-VDM** [comment]
Some logs of a new node syncing [here](https://gist.github.com/Daniel-VDM/732bb2330d16f8e522c91422398f05f2).

**Comment by LeoHChen** [comment]
we shall at least limit the debug log to save some I/O time.

**Comment by SebastianJ** [comment]
I've started memory (allocs/heap) and cpu profiling on a shard 0 OSTN node, it will export PDF profiling dumps every 5 minutes:

```
mkdir -p pprof/memory pprof/cpu
while true; do timestamp=$(date +%s); go tool pprof --pdf http://localhost:6070/debug/pprof/allocs > pprof/memory/allocs-${timestamp}.pdf; sleep 300; done
while true; do timestamp=$(date +%s); go tool pprof --pdf http://localhost:6070/debug/pprof/heap > pprof/memory/heap-${timestamp}.pdf; sleep 300; done
while true; do timestamp=$(date +%s); go tool pprof --pdf http://localhost:6070/debug/pprof/profile?seconds=60 > pprof/cpu/profile-${timestamp}.pdf; sleep 300; done
```

I'll let it run for a few hours and will report back my findings + upload the profiles somewhere.

**Comment by sophoah** [comment]
confirming the slow sync as well here reported by volunteers and also tested on a my vps. It gets slower and slower as the blocks gets added to it

**Comment by SebastianJ** [comment]
Here are the profiling reports: [pprof.tar.gz](http://tools.harmony.one.s3.amazonaws.com/pprof.tar.gz)

A common denominator for both the memory and CPU reports is that they seem to indicate that chain.AccumulateRewards is using both a lot of memory as well as CPU.

**Comment by sophoah** [comment]
Issue is still here in ```Harmony (C) 2020. harmony, version v5659-master-20191208.0-282-g51d5280e (jenkins@ 2020-03-11T01:01:50+0000)```

**Comment by LeoHChen** [comment]
do we still see the issue with the latest code?

**Comment by LeoHChen** [comment]
on mitigation we used in our mainnet is to have rclone to sync the initial snapshot of the DB and keep syncing the latest code.

**Comment by sophoah** [comment]
@LeoHChen this is better however still much slower than the other shard, for instance here 5k blocks takes around 10 min. Shouldn't that be faster ? I am on  ```version v5730-v1.3.5-39-ga429d020```

**Comment by sophoah** [comment]
For info, shard 3 fully sync of 20k block took me less than 5 min

**Comment by JB273** [comment]
After restart of my shard 0 node, I don't even get "in sync" anymore!?

Restarted syncing shard 0 now ` version v5736-v1.3.5-45-ga817cbe9`

12:26 - block 0 (start)
12:45 - block 7600
12:55 - block 11861

**Comment by sophoah** [comment]
```version v5737-v1.3.5-46-gd65afe3d``` report
s0 600 blocks took 2 min
s3 600 blocks took 15s

**Comment by LeoHChen** [comment]
@sophoah , do you have any updated data on the sync. up time of s0 and other shard?

**Comment by CryptosWolfOfAllStreets** [comment]
@LeoHChen Currently testing this on s0
deleted db and restarted node at 14:07 today 
reached 10k blocks by 14:37 so 30 mins to get to 10k 
current leader height 40k so at this rate and speed the current sync time is 2 hours.

Will add a further comment with the exact time taken to achieve full sync

**Comment by sophoah** [comment]
Hi @LeoHChen, tested on ```v5765-v1.3.5-74-g7394956d```
S1 39k - 15 min
S0 39k - 2h45

**Comment by mindstyle85** [comment]
i can confirm, s0 takes about 30min per 10k blocks, while s2 takes about 4min or so per 10k blocks

**Comment by LeoHChen** [comment]
yes, so it is expected that s0 taking long time to sync as the block rewards per block calculation takes time.  One mitigation for us is to build a snapshot of the blockchain db, so that new node runner can start with the prebuilt snapshot and quickly catchup.
