### ISSUE TITLE
Explanation of cause of 03/07/2020 broken consensus

### ISSUE THREAD

**Issue by fxfactorial** [harmony-one/harmony#2435]
This past Saturday a series of cascading failures caused consensus to break. The following is my working theory: 

The opening staking testnet (OSTN) was on commit 87963bb791d9ce7e5113ba05718ead6ac6db2950 at time of issue and blockchain history already had records of successful slashes applied to double signing done by some validators.  

1. Shard 0 leader ran out of disk space and the logger hung because could not write
2. Shard 0 went into view change
3. View change was successful and new leader began proposal. 
4. New leader proposed the slashes that it had in memory 
5. Verification of the slash failed because the slash was from epoch ~390 and current epoch was ~500
6. Failure of slash verification caused block proposal to stop
7. Rotation of leader happened again and this bad loop ensued because (4) happened again. 

This is a realization of a corner case that I left as // TODO and which RJ also pointed out. The fixes for this are in https://github.com/harmony-one/harmony/pull/2396 which was already done before the corner case occurred.

**Comment by lijiang2087** [comment]
so the fix is done, but not merged?

**Comment by fxfactorial** [comment]
Correct

**Comment by AndyBoWu** [comment]
Is there any reason why the leader 0 consumed the 15 GB of space that quick? 

IIRC, it really takes a while for a small network like OSTN. And, it should happen to a non-zero shard first, cuz for any other shards, they have to store 2 DB (one for its own shard, one for shard 0).

**Comment by fxfactorial** [comment]
Because there was a 100-BLS key validator which was marshalled to JSON on every block
