### ISSUE TITLE
[RPC] Validator Information error, leveldb: not found

### ISSUE THREAD

**Issue by janet-harmony** [harmony-one/harmony#2442]
**Describe the bug**

```
$ ./hmy blockchain validator information one1amjd96uxckt8qm048n5etl3d5jl60kczzqpcgf
commit: v312-2fcc715, error: Catch all RPC error: leveldb: not found
check hmy cookbook for valid examples or try adding a `--help` flag
```

**To Reproduce**
1. Download latest CLI
2. Query for validator information 

**Expected behavior**
Correct validator information return.

**Environment (please complete the following information):**
 - OS: Linux

**Additional context**
Problem resolves on next epoch.

**Comment by fxfactorial** [comment]
Fixed in https://github.com/harmony-one/harmony/pull/2396

**Comment by sophoah** [comment]
confirmed I have the issue as well
```
./hmy -n https://api.s0.os.hmny.io blockchain validator information  one1u6c4wer2dkm767hmjeehnwu6tqqur62gx9vqsd
commit: v312-2fcc715, error: Catch all RPC error: leveldb: not found
```
