### ISSUE TITLE
[Explorer] Missing Shard 2/3 transactions from Explorer account page

### ISSUE THREAD

**Issue by janet-harmony** [harmony-one/harmony#2444]
**Describe the bug**
Transactions from Shard 3 missing on account page on Explorer.

Address: https://explorer.harmony.one/#/address/one12wd4crsczqg969red0mvm2t4mhtvk5m328yxkx
Transactions: https://explorer.harmony.one/#/tx/0xce2636bfec2ea3cc7da42bc1fcbf21181d943c3fe34227460b198fd53ea95831
https://explorer.harmony.one/#/tx/0x75c3e87909296b8869006b25e9df18629d96e6f16ea03cbeeaa5d5d1cd3975eb

Address: https://explorer.harmony.one/#/address/one1yt0a97xvrlkvtktuw46qgvw7ls88nrh0mefggz
Transactions: https://explorer.harmony.one/#/tx/0xdea0e617e08b3437ce4fe581bc117d770ed61065f3b2b6d9f846839fcf4c9636
https://explorer.harmony.one/#/tx/0x3394acaa7ddb0c7dda79ef908c935686d74d42688f11be970c9e4cec9c034288 
https://explorer.harmony.one/#/tx/0xab5697c27d45af270a00f95c7414dede10a5f450902b6507f19f52dab12d6784
https://explorer.harmony.one/#/tx/0xdc39046e8721525fc7bf8793c34e2db83b21c0705d8ddc333c1848b180a83df1
t

**To Reproduce**
1. Send transaction from shard 3 to anywhere.
2. Check transaction success on Explorer for transaction hash.
3. Check to see if transaction hash is in list of transactions on account page.

**Expected behavior**
To see a transaction.

**Screenshots**

**Environment (please complete the following information):**
 - OS: [Linux, MacOS]
- Go environment [ ```go env``` ]

**Additional context**
Checked `hmy_getTransactionsHistory`, the hashes don't show up when querying on https://api.s3.t.hmny.io

**Comment by LeoHChen** [comment]
@AndyBoWu , can you check the availability of the shard3 end point?

**Comment by AndyBoWu** [comment]
@janet-harmony @LeoHChen 

I have checked the both target groups pointing to the alb for shard 3. Both instances are **healthy** from AWS's perspective. 

Let me ssh into the instances to check it out.

**Comment by AndyBoWu** [comment]
![Screen Shot 2020-03-10 at 9 41 13 AM](https://user-images.githubusercontent.com/5258417/76336500-54d2f180-62b3-11ea-8fd2-1340732586c1.png)

**Comment by AndyBoWu** [comment]
on the first exp node, we have "blockNumber":2612864, - service is up and blockNumber is increasing. So all good.

**Comment by AndyBoWu** [comment]
on the second exp node, we have "blockNumber":2612885," - service is up and blockNumber is increasing too. So it looks good in general.

**Comment by AndyBoWu** [comment]
Related to this https://github.com/harmony-one/harmony-ops/issues/402 @janet-harmony ?

Can you try the same api call on postman? My guess is that you can get the expected result from Postman.

**Comment by AndyBoWu** [comment]
Did some troubleshooting on my side. 

The results returned by Postman only filter the result `to` address for this address `one12wd4crsczqg969red0mvm2t4mhtvk5m328yxkx` on postman for `hmy_getTransactionsHistory` api call. Any transaction send from this address is not listed. 

Sounds like an api design error? @janet-harmony @LeoHChen , can you please verify this?

**Comment by AndyBoWu** [comment]
![Screen Shot 2020-03-10 at 10 13 50 AM](https://user-images.githubusercontent.com/5258417/76339842-e17fae80-62b7-11ea-9558-44c1f2b06f95.png)

**Comment by janet-harmony** [comment]
My test transactions were to & from the same address. `one12wd4crsczqg969red0mvm2t4mhtvk5m328yxkx`

**Comment by AndyBoWu** [comment]
I noticed that part too. can you try to send to a different address? @janet-harmony

**Comment by janet-harmony** [comment]
Doesn't show up in either account page & doesn't show up for `hmy_getTransactionsHistory` for either account
https://explorer.harmony.one/#/tx/0xbfd7b6c91917682f53b703daa56c7b5b30a6d3e6c8f1b65bf79fe55958762d60

Also checked API call through Postman

**Comment by LeoHChen** [comment]
we should test probably all the shards.  @janet-harmony , can you check on shard 1/2 as well?

**Comment by janet-harmony** [comment]
https://explorer.harmony.one/#/address/one12wd4crsczqg969red0mvm2t4mhtvk5m328yxkx
The top 2 transactions are cross shard 1 & 2 to 0. They show up.

**Comment by LeoHChen** [comment]
let me clarify, did the tx went through shard 3? and just didn't show up in explorer?

**Comment by janet-harmony** [comment]
The transaction itself shows up on explorer & the transaction succeeded, but it doesn't show up in the list of transactions by account.

**Comment by LeoHChen** [comment]
confirmed the bug. For example, on this account page, we can't see transaction on shard 2 and 3.
![image](https://user-images.githubusercontent.com/4513927/76675517-7e23a400-6577-11ea-9aea-f9b6aa61c9c1.png)

**Comment by LeoHChen** [comment]
However, on the front page of the explorer, we can see clearly there are transactions on shard 2 and 3 for the same account. 

![image](https://user-images.githubusercontent.com/4513927/76675532-a4494400-6577-11ea-8057-6d7cd616898d.png)

**Comment by LeoHChen** [comment]
No transaction shows on the account page.
https://explorer.harmony.one/#/address/one12wgnwzfnudzyg0jj9ef0hjhx4vm8fka73uvuym

However, there are transaction for this account. Look at the front page of the explorer.

![image](https://user-images.githubusercontent.com/4513927/76695940-5fd6aa80-6642-11ea-81ac-c66d6cf86b32.png)

**Comment by LeoHChen** [comment]
Resolved after restart explorer nodes in archival mode.
