### ISSUE TITLE
Chrome extension - Unable to stake

### ISSUE THREAD

**Issue by mirrormirage0** [harmony-one/harmony#2446]
**Describe the bug**
Unable to send staking transactions. Chain-ID error

**To Reproduce**
1. Install 0.0.7 version of chrome extension.
2. Try to Stake tokens.
3. Fails with error.  **"txnHash": "transaction failed:current chain id:3: invalid chain id for signer"**

**Expected behavior**
Staking Transaction completes successfully.

**Screenshots**
![image](https://user-images.githubusercontent.com/29485946/76306398-3df6c400-62e0-11ea-9d7f-e61841661880.png)

**Environment (please complete the following information):**
 - Chrome Extension 0.0.7

**Comment by sophoah** [comment]
@mirrormirage0 think you can close that one now
