### ISSUE TITLE
hmy_cli chain-id required for localhost nodes

### ISSUE THREAD

**Issue by yelllowsin** [harmony-one/harmony#2447]
In the latest hmy_cli version chain-id is aked when doing a transfer using localhost:

`./hmy transfer --from one170xqsfzm4xdmuyax54t5pvtp5l5yt66u50ctrp --to one170xqsfzm4xdmuyax54t5pvtp5l5yt66u50ctrp --from-shard 0 --to-shard 0 --amount 1`

Output:

```
{
  "errors": [
    "[2020-03-10 15:11:43.688509] Catch all RPC error: current chain id:3: invalid chain id for signer",
    "[2020-03-10 15:11:43.688526] Failed to confirm transaction"
  ],
  "time-signed-utc": "2020-03-10 15:11:43.627040"
}
commit: v312-2fcc715, error: Failed to confirm transaction
check hmy cookbook for valid examples or try adding a `--help` flag
```

Accordingly to @fxfactorial this is not an expected behavior because the same chain-id is not asked when we use --node as a parameter (example of a transfer on OSTN):

`./hmy --node="https://api.s0.os.hmny.io" transfer --from one170xqsfzm4xdmuyax54t5pvtp5l5yt66u50ctrp --to one170xqsfzm4xdmuyax54t5pvtp5l5yt66u50ctrp --from-shard 0 --to-shard 0 --amount 1`

Output:

```
{
  "transaction-hash": "0xbd9510fbed07ee8b17468c34c59674ffa235670464eb92bb001f8ddcea70d42c",
  "blockchain-receipt": {
    "blockHash": "0x4003ed2d25e7dd4dd406d6aa60924679a7c5d9e71b138354348e22404a4d0d2a",
    "blockNumber": "0x18bd",
    "contractAddress": null,
    "cumulativeGasUsed": "0xa410",
    "from": "one170xqsfzm4xdmuyax54t5pvtp5l5yt66u50ctrp",
    "gasUsed": "0x5208",
    "logs": [],
    "logsBloom": "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
    "shardID": 0,
    "status": "0x1",
    "to": "one170xqsfzm4xdmuyax54t5pvtp5l5yt66u50ctrp",
    "transactionHash": "0xbd9510fbed07ee8b17468c34c59674ffa235670464eb92bb001f8ddcea70d42c",
    "transactionIndex": "0x1"
  },
  "time-signed-utc": "2020-03-10 15:13:04.217243"
}
```

Somehow the hmy_cli is not detecting automatically the chain-id when using a localhost node.

**Comment by CryptosWolfOfAllStreets** [comment]
performing the same transfer i was able to get a result by adding --chain-id pangaea and also by using the --node feature too. 
This worked; 
./hmy --node="https://api.s0.os.hmny.io" transfer --from one10jvjrtwpz2sux2ngktg3kq7m3sdz5p5au5l8c8 --to one1vam2vq93j0ea7t4vhy9d7dx636r70y6thn68rz --from-shard 0 --to-shard 0 --amount 5000

as did this : 
./hmy transfer --from one10jvjrtwpz2sux2ngktg3kq7m3sdz5p5au5l8c8 --from-shard 0 --to one1vam2vq93j0ea7t4vhy9d7dx636r70y6thn68rz  --to-shard 0 --amount 5000 --chain-id pangaea   

this FAILED and returned the exact same error as above that yelllowsin faces: 
./hmy transfer --from one10jvjrtwpz2sux2ngktg3kq7m3sdz5p5au5l8c8 --to one1vam2vq93j0ea7t4vhy9d7dx636r70y6thn68rz  --from-shard 0 --to-shard 0 --amount 5000

ERROR: 

{
  "errors": [
    "[2020-03-10 17:11:43.688509] Catch all RPC error: current chain id:3: invalid chain id for signer",
    "[2020-03-10 17:11:43.688526] Failed to confirm transaction"
  ],
  "time-signed-utc": "2020-03-10 17:11:43.627040"
}
commit: v312-2fcc715, error: Failed to confirm transaction

**Comment by fxfactorial** [comment]
This PR will improve the error message to include chain ID given, https://github.com/harmony-one/harmony/pull/2396

**Comment by sophoah** [comment]
I confirmed issue is still present in ```Harmony (C) 2020. hmy, version v318-dd0caea (ubuntu@harmony.one 2020-03-11T05:51:46+0000)```

**Comment by LeoHChen** [comment]
PR is merged. pending release by @Daniel-VDM . Please close this issue once it is released.

**Comment by Daniel-VDM** [comment]
released
