### ISSUE TITLE
slashing, EPoS w/ edgar

### ISSUE THREAD

**Issue by NiteeshHarmony** [harmony-one/harmony#2475]

**Comment by sophoah** [comment]
@fxfactorial what are we trying to implement here ?

**Comment by fxfactorial** [comment]
Don’t know. I woke up and 30 new issues posted.

**Comment by mindstyle85** [comment]
@NiteeshHarmony what is this? even the devs dont know... if you open up issues here they should be explained in detail so they at least know what to do.. otherwise its just more useless open github issues and makes tracking real issues hard.

**Comment by lijiang2087** [comment]
sorry guys, let's close these.
