### ISSUE TITLE
Validator node goes inactive then become active at first sync and validator creation

### ISSUE THREAD

**Issue by sophoah** [harmony-one/harmony#2481]
**Describe the bug**

**To Reproduce**
1) start the node and sync (non shard 0)
2) once fully sync I am creating the validator
3) validator info shows my epos-eligibility-status to active
4) waiting for epoch change
5) got BINGO however my validator info epos-status is inactive
6) verified and I didn't earn reward
7) after a while validator info shows my epos-eligibility-status to active (without having to edit it to active) and I am earning bingo normally

Validator is in sync:
```
root@scw-vigorous-herschel:~# ./hmy  blockchain latest-header | grep blockNumber
    "blockNumber": 6421,
root@scw-vigorous-herschel:~# ./hmy -n https://api.s1.os.hmny.io blockchain latest-header | grep blockNumber
    "blockNumber": 6422,
```
create the delegator and show its information (epos status is active
```
root@scw-vigorous-herschel:~# ./hmy -n https://api.s0.os.hmny.io blockchain validator information  one1t4p6x5k7zw59kers7hwmjh3kymj0n6spr02qnf
{
  "id": "0",
  "jsonrpc": "2.0",
  "result": {
    "current-epoch-signing-percent": {
      "current-epoch-signed": 0,
      "current-epoch-to-sign": 0,
      "percentage": "0.000000000000000000"
    },
    "current-epoch-voting-power": [],
    "validator": {
      "address": "one1t4p6x5k7zw59kers7hwmjh3kymj0n6spr02qnf",
      "availability": {
        "num-blocks-signed": 0,
        "num-blocks-to-sign": 0
      },
      "bls-public-keys": [
        "1ac25c5d6c9a3ccba7f4fb18592f590eab0ad072f4b8a75d2ea0cce6d08b92c2733ef3b657e3f54b88fb91f191d88911"
      ],
      "creation-height": 5151,
      "delegations": [
        {
          "amount": 5e+21,
          "delegator-address": "one1t4p6x5k7zw59kers7hwmjh3kymj0n6spr02qnf",
          "reward": 0,
          "undelegations": []
        }
      ],
      "details": "Soph P-OPS Validator node #2",
      ***"epos-eligibility-status": "active",***
      "identity": "Soph",
      "last-epoch-in-committee": 0,
      "max-change-rate": "0.050000000000000000",
      "max-rate": "0.900000000000000000",
      "max-total-delegation": 1e+24,
      "min-self-delegation": 2000000000000000000,
      "name": "Soph P-OPS Validator node #2",
      "rate": "0.100000000000000000",
      "security-contact": "Soph",
      "update-height": 5151,
      "website": "soph.harmony.one"
    }
  }
}
```

I am waitng for epoch change and BINGOs :
```
root@scw-vigorous-herschel:~# tail -f latest/zero*.log | grep BINGO
{"level":"info","port":"9000","ip":"212.47.xxx.xxx","blockNum":6524,"epochNum":69,"ViewId":6524,"blockHash":"0x264a22e9c6ce6f7c4bc93932d0f05562d12a711f91a9e886b953899d369d7a0e","numTxns":0,"numStakingTxns":0,"caller":"/mnt/jenkins/workspace/harmony-release/harmony/node/node_handler.go:466","time":"2020-03-11T15:36:53.055057761Z","message":"BINGO !!! Reached Consensus"}
^C
```
At that time time there are no reward and my epos status is inactive as shown below (also notice that I am not signing block despite the BINGO i had above:
```
root@scw-vigorous-herschel:~# ./hmy -n https://api.s0.os.hmny.io blockchain validator information  one1t4p6x5k7zw59kers7hwmjh3kymj0n6spr02qnf
{
  "id": "0",
  "jsonrpc": "2.0",
  "result": {
    "current-epoch-signing-percent": {
      "current-epoch-signed": 0,
      "current-epoch-to-sign": 8,
      "percentage": "0.000000000000000000"
    },
    "current-epoch-voting-power": [
      {
        "effective-stake": "7760160000000000000000.000000000000000000",
        "shard-id": 1,
        "voting-power-adjusted": "0.058657846754338245",
        "voting-power-raw": "0.183305771107307017"
      }
    ],
    "validator": {
      "address": "one1t4p6x5k7zw59kers7hwmjh3kymj0n6spr02qnf",
      "availability": {
        "num-blocks-signed": 0,
        "num-blocks-to-sign": 8
      },
      "bls-public-keys": [
        "1ac25c5d6c9a3ccba7f4fb18592f590eab0ad072f4b8a75d2ea0cce6d08b92c2733ef3b657e3f54b88fb91f191d88911"
      ],
      "creation-height": 5151,
      "delegations": [
        {
          "amount": 5e+21,
          "delegator-address": "one1t4p6x5k7zw59kers7hwmjh3kymj0n6spr02qnf",
          "reward": 0,
          "undelegations": []
        }
      ],
      "details": "Soph P-OPS Validator node #2",
      "epos-eligibility-status": "inactive",
      "identity": "Soph",
      "last-epoch-in-committee": 69,
      "max-change-rate": "0.050000000000000000",
      "max-rate": "0.900000000000000000",
      "max-total-delegation": 1e+24,
      "min-self-delegation": 2000000000000000000,
      "name": "Soph P-OPS Validator node #2",
      "rate": "0.100000000000000000",
      "security-contact": "Soph",
      "update-height": 5151,
      "website": "soph.harmony.one"
    }
  }
}
```

then after a while (not sure how long), everything looks ok:
```
./hmy -n https://api.s0.os.hmny.io blockchain validator information  one1t4p6x5k7zw59kers7hwmjh3kymj0n6spr02qnf
{
  "id": "0",
  "jsonrpc": "2.0",
  "result": {
    "current-epoch-signing-percent": {
      "current-epoch-signed": 25,
      "current-epoch-to-sign": 33,
      "percentage": "0.757575757575757576"
    },
    "current-epoch-voting-power": [
      {
        "effective-stake": "7760160000000000000000.000000000000000000",
        "shard-id": 1,
        "voting-power-adjusted": "0.058657846754338245",
        "voting-power-raw": "0.183305771107307017"
      }
    ],
    "validator": {
      "address": "one1t4p6x5k7zw59kers7hwmjh3kymj0n6spr02qnf",
      "availability": {
        "num-blocks-signed": 25,
        "num-blocks-to-sign": 33
      },
      "bls-public-keys": [
        "1ac25c5d6c9a3ccba7f4fb18592f590eab0ad072f4b8a75d2ea0cce6d08b92c2733ef3b657e3f54b88fb91f191d88911"
      ],
      "creation-height": 5151,
      "delegations": [
        {
          "amount": 5e+21,
          "delegator-address": "one1t4p6x5k7zw59kers7hwmjh3kymj0n6spr02qnf",
          "reward": 146627448871470250000,
          "undelegations": []
        }
      ],
      "details": "Soph P-OPS Validator node #2",
      "epos-eligibility-status": "active",
      "identity": "Soph",
      "last-epoch-in-committee": 69,
      "max-change-rate": "0.050000000000000000",
      "max-rate": "0.900000000000000000",
      "max-total-delegation": 1e+24,
      "min-self-delegation": 2000000000000000000,
      "name": "Soph P-OPS Validator node #2",
      "rate": "0.100000000000000000",
      "security-contact": "Soph",
      "update-height": 5151,
      "website": "soph.harmony.one"
    }
  }
}
```

**Expected behavior**
no weird period where BINGO is working, no signing block and auto switch to epos statut active without doing anything

**Screenshots**
N/A

**Environment (please complete the following information):**
hmy : ```Harmony (C) 2020. hmy, version v312-2fcc715 (ubuntu@harmony.one 2020-03-10T00:45:16+0000)```
node : ```Harmony (C) 2020. harmony, version v5659-master-20191208.0-282-g51d5280e (jenkins@ 2020-03-11T01:01:50+0000)```

**Additional context**

**Comment by CryptosWolfOfAllStreets** [comment]
my findings are as follows: 

1) start the node and sync shard 3 
2) once fully sync i am creating the validator
3) validator info shows my epos-eligibility-status to inactive
4) waitng for epoch change
5) got BINGO however my validator info epos-status is inactive
6) reward showing using 
root@Wolfie:~# ./hmy --node https://api.s0.os.hmny.io blockchain validator information one10jvjrtwpz2sux2ngktg3kq7m3sdz5p5au5l8c8
{
  "id": "0",
  "jsonrpc": "2.0",
  "result": {
    "current-epoch-signing-percent": {
      "current-epoch-signed": 17,
      "current-epoch-to-sign": 45,
      "percentage": "0.377777777777777778"
    },
    "current-epoch-voting-power": [
      {
        "effective-stake": "10000000000000000000000.000000000000000000",
        "shard-id": 3,
        "voting-power-adjusted": "0.064439477234740933",
        "voting-power-raw": "0.201373366358565416"
      }
    ],
    "validator": {
      "address": "one10jvjrtwpz2sux2ngktg3kq7m3sdz5p5au5l8c8",
      "availability": {
        "num-blocks-signed": 17,
        "num-blocks-to-sign": 45
      },
      "bls-public-keys": [
        "8342345142dcd0fbfde1ddf0df10de9d3b5f24b6ddc8ed282e2aef96283826ea06fc17c325b4ce45a6bbb89c9aa9970b"
      ],
      "creation-height": 5323,
      "delegations": [
        {
          "amount": 1e+22,
          "delegator-address": "one10jvjrtwpz2sux2ngktg3kq7m3sdz5p5au5l8c8",
          "reward": 109534017633902300000,
          "undelegations": []
        }
      ],
      "details": "CryptoWolfs Validation Station",
      "epos-eligibility-status": "inactive",
      "identity": "CryptoWolf",
      "last-epoch-in-committee": 71,
      "max-change-rate": "0.050000000000000000",
      "max-rate": "0.900000000000000000",
      "max-total-delegation": 1e+27,
      "min-self-delegation": 2000000000000000000,
      "name": "CryptoWolf",
      "rate": "0.100000000000000000",
      "security-contact": "Wolf",
      "update-height": 5323,
      "website": "CryptoWolf@harmony.one"
    }
  }
}

shortly after this i was kicked from election and bingo also stopped epos eligibility changed to active.

**Comment by CryptosWolfOfAllStreets** [comment]
at the next epoch Bingo started again and i was again elected BUT status of eligibility now inactive :

"/mnt/jenkins/workspace/harmony-release/harmony/node/node_handler.go:466","time":"2020-03-11T16:20:05.698143282Z","message":"BINGO !!! Reached Consensus"}
{"level":"info","port":"9000","ip":"144.202.105.13","blockNum":6866,"epochNum":73,"ViewId":6866,"blockHash":"0x6bd6941b1aab5fedf20d4c98ea5eea92c961902e0da55634924ffd602d9901c7","numTxns":0,"numStakingTxns":0,"caller":"/mnt/jenkins/workspace/harmony-release/harmony/node/node_handler.go:466","time":"2020-03-11T16:20:13.632654553Z","message":"BINGO !!! Reached Consensus"}
root@Wolfie:~# ./hmy --node https://api.s0.os.hmny.io blockchain validator information one10jvjrtwpz2sux2ngktg3kq7m3sdz5p5au5l8c8
{
  "id": "0",
  "jsonrpc": "2.0",
  "result": {
    "current-epoch-signing-percent": {
      "current-epoch-signed": 5,
      "current-epoch-to-sign": 28,
      "percentage": "0.178571428571428571"
    },
    "current-epoch-voting-power": [
      {
        "effective-stake": "10000000000000000000000.000000000000000000",
        "shard-id": 3,
        "voting-power-adjusted": "0.052540480623979942",
        "voting-power-raw": "0.164189001949937320"
      }
    ],
    "validator": {
      "address": "one10jvjrtwpz2sux2ngktg3kq7m3sdz5p5au5l8c8",
      "availability": {
        "num-blocks-signed": 51,
        "num-blocks-to-sign": 103
      },
      "bls-public-keys": [
        "8342345142dcd0fbfde1ddf0df10de9d3b5f24b6ddc8ed282e2aef96283826ea06fc17c325b4ce45a6bbb89c9aa9970b"
      ],
      "creation-height": 5323,
      "delegations": [
        {
          "amount": 1e+22,
          "delegator-address": "one10jvjrtwpz2sux2ngktg3kq7m3sdz5p5au5l8c8",
          "reward": 322650265964695000000,
          "undelegations": []
        }
      ],
      "details": "CryptoWolfs Validation Station",
      "epos-eligibility-status": "inactive",
      "identity": "CryptoWolf",
      "last-epoch-in-committee": 73,
      "max-change-rate": "0.050000000000000000",
      "max-rate": "0.900000000000000000",
      "max-total-delegation": 1e+27,
      "min-self-delegation": 2000000000000000000,
      "name": "CryptoWolf",
      "rate": "0.100000000000000000",
      "security-contact": "Wolf",
      "update-height": 5323,
      "website": "CryptoWolf@harmony.one"
    }
  }
}

**Comment by BrunoMarshall** [comment]
Same here in shard 2
![image](https://user-images.githubusercontent.com/35432495/76439410-a87d3200-63bc-11ea-8158-5969b72a7d35.png)
![image](https://user-images.githubusercontent.com/35432495/76439452-b29f3080-63bc-11ea-837d-4a9ae5c0d191.png)
![image](https://user-images.githubusercontent.com/35432495/76439472-b8951180-63bc-11ea-950a-b5fe7e1ad59b.png)
here was the procedure: 
1) start the node and sync (shard 2)
2) once fully sync i am creating the validator
3) validator info shows my epos-eligibility-status to active
4) waiting for epoch change
5) got BINGO however my validator info epos-status is inactive
6) verified and i didn't earn reward

**Comment by mindstyle85** [comment]
i think this doesnt happen anymore @BrunoMarshall @sophoah ?

**Comment by lijiang2087** [comment]
closing it for now @mindstyle85 @BrunoMarshall @sophoah
