### ISSUE TITLE
It's possible to create validators with ~200+ BLS keys

### ISSUE THREAD

**Issue by SebastianJ** [harmony-one/harmony#2482]
**Describe the bug**
It's currently possible to create validators with up to a maximum of around 200 BLS keys (possibly even more if you minimize the other create validator payload data so that the tx stays <32kb).

Here's an example of such a validator:
`./hmy --node https://api.s0.os.hmny.io blockchain validator information one1a7ymxzys5te4rlam2966kmrzannsy3zrwpdvnz`

These transactions with ~200 also significantly slow down shard 0 if sent in bulk/concurrently - I managed to increase the block time 4x when I was doing around 70-80 validators every ~60s or so.

**To Reproduce**
Ubuntu:
1. `rm -rf harmony-stress && mkdir -p harmony-stress && cd harmony-stress`
2. `bash <(curl -s -S -L https://raw.githubusercontent.com/SebastianJ/harmony-stress/master/scripts/install.sh)`
3. `./stress create-validators --from YOUR_FUNDED_ADDRESS --infinite --pool-size 10 --network pangaea`

**Expected behavior**
There probably isn't a need for a validator to run with 200 BLS keys - it should definitely be restricted to a sensible amount of maximum BLS keys.

**Comment by fxfactorial** [comment]
should be fixed in https://github.com/harmony-one/harmony/pull/2484
