### ISSUE TITLE
Harmony Website JS issue 

### ISSUE THREAD

**Issue by CryptosWolfOfAllStreets** [harmony-one/harmony#2483]
Seems like messenger property on harmony js object didn’t get set right.

![image](https://user-images.githubusercontent.com/41840990/76442636-24757b00-63b9-11ea-8154-3adc140c7f60.png)

**Comment by mindstyle85** [comment]
this is because of the old extension

**Comment by sophoah** [comment]
yes agree so i'm closing that one.
