### ISSUE TITLE
Unify Staking Transactions With Plain Transactions (cleverness with custom decode) 

### ISSUE THREAD

**Issue by fxfactorial** [harmony-one/harmony#2486]
This mistake in design from last fall is causing lots of byte thrashing and heavily contributing to OOM issues.

**Comment by fxfactorial** [comment]
Basically in `staking/types/transaction.go` we have:
 
```go
type txdata struct {
    Directive
    StakeMsg     interface{}
    AccountNonce uint64   `json:"nonce"      gencodec:"required"`
    Price        *big.Int `json:"gasPrice"   gencodec:"required"`
    GasLimit     uint64   `json:"gas"        gencodec:"required"`
    // Signature values
    V *big.Int `json:"v" gencodec:"required"`
    R *big.Int `json:"r" gencodec:"required"`
    S *big.Int `json:"s" gencodec:"required"`
    // This is only used when marshaling to JSON.
    Hash *common.Hash `json:"hash" rlp:"-"`
}
```

And this is the mistake: 
```go
 Directive
 StakeMsg     interface{}
```

`txdata` used here: 

```go

type StakingTransaction struct {
    data txdata
    // caches
    hash atomic.Value
    size atomic.Value
    from atomic.Value
}
```


So the solution is to use concrete types explicitly. 

```go
type txDataCommon struct {
    AccountNonce uint64   `json:"nonce"      gencodec:"required"`
    Price        *big.Int `json:"gasPrice"   gencodec:"required"`
    GasLimit     uint64   `json:"gas"        gencodec:"required"`
    // Signature values
    V *big.Int `json:"v" gencodec:"required"`
    R *big.Int `json:"r" gencodec:"required"`
    S *big.Int `json:"s" gencodec:"required"`
    // This is only used when marshaling to JSON.
    Hash *common.Hash `json:"hash" rlp:"-"`
}

type txdataCreateValidator struct {
    txDataCommon
    ValidatorAddress   common.Address `json:"validator-address"`
    Description        `json:"description"`
    CommissionRates    `json:"commission"`
    MinSelfDelegation  *big.Int             `json:"min-self-delegation"`
    MaxTotalDelegation *big.Int             `json:"max-total-delegation"`
    SlotPubKeys        []shard.BlsPublicKey `json:"slot-pub-keys"`
    SlotKeySigs        []shard.BLSSignature `json:"slot-key-sigs"`
    Amount             *big.Int             `json:"amount"`
}

type txdataCollectReward struct {
    txDataCommon
    DelegatorAddress common.Address `json:"delegator_address"`
}

type TransactionCreateValidator struct {
    data txdataCreateValidator
    // caches
    hash atomic.Value
    size atomic.Value
    from atomic.Value
}

type TransactionCollectReward struct {
    data txdataCollectReward
    // caches
    hash atomic.Value
    size atomic.Value
    from atomic.Value
}
```

 Also Consider how the data type sounds when coming off the package. Although this package named `types`, we always alias the import to `staking`, so `staking.TransactionCollectReward` is a good sound while `staking.StakingTransactionCollectReward` is name punting. Keep this kind of naming consideration in mind when making the associated functions for these new data types.

**Comment by fxfactorial** [comment]
Note that this will means downstream changes in trustwallet, hmy cli, staking dashboard , rpc level

**Comment by denniswon** [comment]
@fxfactorial could you link the pr that made the design change?

**Comment by fxfactorial** [comment]
This is the original way we did the staking transactions from Fall 2019.

**Comment by sophoah** [comment]
@fxfactorial could you explain for non advanced programmer why 
```go
 Directive
 StakeMsg     interface{}
```
is a mistake?

**Comment by fxfactorial** [comment]
The usage of this field causes many unnecessary encoding/decoding round trips which can be entirely avoided. These round trips eat up CPU and memory for the many temporary byte arrays created during rlp encoding /decoding process

**Comment by fxfactorial** [comment]
UPDATE: 

After talking with RJ offline, we realized that actually need to go in the other direction. 

That is, we need to unify StakingTransaction with Plain transactions because the current existence of staking transactions as a separate slice in the block is a hack (aka the shared usage of nonce). 

Therefore we must endorse the polymorphic approach intent of staking transactions but this time CORRECTLY implement the tagged marker approach and this time unified with plain transactions. That is, need to have a single transaction type with the tagged enum marker ahead of an interface and have the custom Decode/Encoder do the business logic of custom encoding/decoding.

**Comment by gupadhyaya** [comment]
https://github.com/harmony-one/harmony/pull/2869 and https://github.com/harmony-one/harmony/pull/2868
