### ISSUE TITLE
Mainnet (version v5036-v1.2.4-2-gd116332a), Mainnet (versions v5036-v1.2.4-2-gd116332a and v5036-v1.2.4-2-gd116332a)

### ISSUE THREAD

**Issue by lijiang2087** [harmony-one/harmony#2491]
janet, on /status

can you add the network version next to the word like this, instead of putting it below. it's just a visual change.

Mainnet (version v5036-v1.2.4-2-gd116332a)
Mainnet (versions v5036-v1.2.4-2-gd116332a and v5036-v1.2.4-2-gd116332a)

**Comment by yelllowsin** [comment]
I think this can be closed @lijiang2087 , right? I already see the version here: http://watchdog.hmny.io/status
I have just checked and it matches the version on Watchdog.

![image](https://user-images.githubusercontent.com/7217595/77261951-03424380-6c71-11ea-91fb-630781e61765.png)

**Comment by janet-harmony** [comment]
<img width="1219" alt="Screen Shot 2020-03-24 at 2 42 51 AM" src="https://user-images.githubusercontent.com/56005637/77411126-2c4dfb80-6d79-11ea-9541-40446220e742.png">
 
Fixed in updated version.
