### ISSUE TITLE
the validator command on CLI has too many fields

### ISSUE THREAD

**Issue by lijiang2087** [harmony-one/harmony#2493]
too many unnecessary fields

**Comment by gizemcakil** [comment]
I believe this one needs to go under go-sdk

**Comment by fxfactorial** [comment]
All the fields are directly from the data needed to create a validator. What field(s) do you think are extra ?

**Comment by mindstyle85** [comment]
@gizemcakil @lijiang2087 this is what i mean by creating extra disorder and confusion...

@fxfactorial i believe this was just biz demonstration on how to open a ticket.. they should also show how to close it.
