### ISSUE TITLE
hmy_getTransactionsHistory returns only shard 1 transactions on mainnet

### ISSUE THREAD

**Issue by denniswon** [harmony-one/harmony#2504]
**Describe the bug**
![Screen Shot 2020-03-14 at 12 01 21 PM](https://user-images.githubusercontent.com/3278577/76689181-8d930380-65f0-11ea-8c63-3c438c7196e9.png)

**To Reproduce**
```
curl --location --request POST 'https://api.s1.t.hmny.io/' --header 'Content-Type: application/json' --data-raw '{
"jsonrpc": "2.0",
    "method": "hmy_getTransactionsHistory",
    "params": [{
        "address": "one1ysack4ympjqrycww3ptygs8yrmwtna7fxlgsnk",
        "pageIndex": 0,
        "pageSize": 1000,
        "fullTx": true,
        "txType": "ALL",
        "order": "ASC"
    }],
    "id": 1
}'

```
**Expected behavior**
Other shard txns valid are also returned by rpc api.

**Screenshots**

![Screen Shot 2020-03-14 at 12 01 21 PM](https://user-images.githubusercontent.com/3278577/76689208-c29f5600-65f0-11ea-8ac1-7441bbbcf84b.png)

**Comment by LeoHChen** [comment]
resolved after restart explorer nodes in archival mode.
