### ISSUE TITLE
Generating an excessive amount of validators on stressnet broke shard 0 consensus

### ISSUE THREAD

**Issue by SebastianJ** [harmony-one/harmony#2505]
**Describe the bug**
I generated around ~48k validators on shard 0 on the stressnet - shard 0 ended up losing consensus and never recovered.

Exact number of validators created when consensus stopped working: 47895
Block height: 14403
Estimated time for when consensus stopped working: 2020-03-14 12:15 PM UTC

---

**To Reproduce**
```
rm -rf harmony-stress && mkdir -p harmony-stress && cd harmony-stress
bash <(curl -s -S -L https://raw.githubusercontent.com/SebastianJ/harmony-stress/master/scripts/install.sh)
./stress create-validators --from ADDRESS --infinite --pool-size 10 --network stressnet
```

---

**Expected behavior**
Shard 0 shouldn't break - it should definitely be able to handle ~50k validators. This is not an unreasonable number and a normal non-stressnet network could end up having this amount of validators (including inactive/stale/old validators that might not get started) without having any issues.

**Comment by rlan35** [comment]
When the consensus is broken is there any real validator running to support the consensus?

**Comment by rlan35** [comment]
This should have been fixed since the latest OSTN withstood 60k+ validators in last test.
