### ISSUE TITLE
node syncing issue: beaconchain-is-nil:true shardchain-is-nil:t

### ISSUE THREAD

**Issue by lijiang2087** [harmony-one/harmony#2507]
after i ssh into my node, and then run the 1st command in the documentation here: https://docs.harmony.one/home/validators/managing-your-validator/resetting-your-node

./node.sh -S -c -I -N staking -z -k [BLS KEY FILE].key

I get the following error: beaconchain-is-nil:true shardchain-is-nil:t

from @fxfactorial 
we've seen this before on other people: beaconchain-is-nil:true shardchain-is-nil:t
is the issue. I don't know exact cause but my theory: 

1) Could be that other harmony process is still locked with the DB, hence new process could not attain system wide lock on the DB (like how you can't have two sudo apt-get install at the same time) 

2) DB is corrupted (not sure how that could come about)

Edgar | HarmonyToday at 9:47 AM
Obviously we need to fix. Just issue of who can dedicate time to investigate and fix.

**Comment by LeoHChen** [comment]
try `pgrep harmony` to see if there is any harmony process running.  If yes, do `sudo pkill harmony` to terminate them and use the `node.sh` like above to start from fresh again.

**Comment by BrunoMarshall** [comment]
Can you close this issue? was this related to the solved syncing issue: https://github.com/harmony-one/harmony/issues/2500
Thank you

**Comment by mindstyle85** [comment]
@BrunoMarshall this is not due to syncing issue

**Comment by lijiang2087** [comment]
I have not been able to replicate this issue or seen in the last week, so going to close it for now @mindstyle85 @BrunoMarshall @LeoHChen
