### ISSUE TITLE
[Feature] Add Keybase Integration to Harmony protocol 

### ISSUE THREAD

**Issue by Chainode** [harmony-one/harmony#2515]
# Problem/limitation At Hand

The current method for a validator to publish its logo is pretty inconvenient by forking the repository and then submitting an issue with your validator address. If the address changes or you add another validator, then another PR with the address. 

# Proposed Solution

Integration with keybase and then use the pgp key of an account to publish validator logo on the staking dashboard.
This has to be implemented in the hmy client and add an extra flag in the validator creation and edit, e.g.: --keybase-sig=“E34BF744FF5BA8A9”

By doing this, a validator can add and change the logo by using the hmy client at convenience in an easy and clean manner.

**Comment by yelllowsin** [comment]
I agree, this is a much better/flexible solution than doing a PR. @Daniel-VDM since you are the owner of the HMY, what do you think about this solution?

**Comment by Chainode** [comment]
Closing this issue as is more relevant for go-sdk: https://github.com/harmony-one/go-sdk/issues/183
