### ISSUE TITLE
having 1/3 bls keys inactive marks you as inactive and not elected

### ISSUE THREAD

**Issue by mindstyle85** [harmony-one/harmony#2516]
**Describe the bug**

So having 2 active bls keys and being in comittee, i was signing 100% of blocks. Then i edited my validator and added another bls key WITHOUT restarting the node.sh (intentional). What I found out is that since there is one key inactive you sign less blocks than expected, so after an epoch i got marked inactive, and after another one my status on dashboard is "not elected". While I am still bingoing with the 2 bls keys that are active. So this is a bug where my validator should not be marked as inactive just because one bls key is not signing.

 ./hmy blockchain validator information one1s7fp0jrmd97estwye3mhkp7xsqf42vn5x2sfqy --node="https://api.s0.os.hmny.io"{
  "id": "0",
  "jsonrpc": "2.0",
  "result": {
    **"current-epoch-signing-percent": {
      "current-epoch-signed": 98,
      "current-epoch-to-sign": 142,
      "percentage": "0.690140845070422535"**
    },
    ],
    "validator": {
      "address": "one1s7fp0jrmd97estwye3mhkp7xsqf42vn5x2sfqy",
      "availability": {
        "num-blocks-signed": 12286,
        "num-blocks-to-sign": 12454
      },
      "bls-public-keys": [
        "e429cbf74e8ab28ed295999d179ad79827c7febe0208a6145aa91bbb60b68a0b1907de4c38573352cafe00c8105b1116",
        "1c57c3282714e412d974a5c1c5712f1f6062d3253d9a080580abf4342805e3311c19f81bef5b1a903fe282650b767a12",
        "a11bb4202ecad06799b50dd04f5c2ec631bf411789ade7e62237f698ad3a17dfa90b60354f153404d3886e753f622086"
      ],
      "details": "pink pony node runners",
      **"epos-eligibility-status": "active",**
      "identity": "mind",
      "last-epoch-in-committee": 101,
      "max-change-rate": "0.050000000000000000",
      "max-rate": "0.500000000000000000",
      "max-total-delegation": 1e+26,
      "min-self-delegation": 5000000000000000000,
      "name": "mind #P-OPS",
      "rate": "0.100000000000000000",
      "security-contact": "mamapangaea",
      "update-height": 740,
      "website": "mind@harmony.one"
    }
  }
}

here is where i get inactive, but im still in comittee for one more epoch:

 ./hmy blockchain validator information one1s7fp0jrmd97estwye3mhkp7xsqf42vn5x2sfqy --node="https://api.s0.os.hmny.io"
{
  "id": "0",
  "jsonrpc": "2.0",
  **"result": {
    "current-epoch-signing-percent": {
      "current-epoch-signed": 58,
      "current-epoch-to-sign": 87,
      "percentage": "0.666666666666666667"**
    }
    "validator": {
      "address": "one1s7fp0jrmd97estwye3mhkp7xsqf42vn5x2sfqy",
      "availability": {
        "num-blocks-signed": 12396,
        "num-blocks-to-sign": 12619
      },
      "bls-public-keys": [
        "e429cbf74e8ab28ed295999d179ad79827c7febe0208a6145aa91bbb60b68a0b1907de4c38573352cafe00c8105b1116",
        "1c57c3282714e412d974a5c1c5712f1f6062d3253d9a080580abf4342805e3311c19f81bef5b1a903fe282650b767a12",
        "a11bb4202ecad06799b50dd04f5c2ec631bf411789ade7e62237f698ad3a17dfa90b60354f153404d3886e753f622086"
      ],
      "creation-height": 740,      ],
      "details": "pink pony node runners",
      **"epos-eligibility-status": "inactive",**
      "identity": "mind",
      "last-epoch-in-committee": 102,
      "max-change-rate": "0.050000000000000000",
      "max-rate": "0.500000000000000000",
      "max-total-delegation": 1e+26,
      "min-self-delegation": 5000000000000000000,
      "name": "mind #P-OPS",
      "rate": "0.100000000000000000",
      "security-contact": "mamapangaea",
      "update-height": 740,
      "website": "mind@harmony.one"
    }
  }
}

this is the latest bingo, timestamp is right now (about 20min after i got thrown out):

{"level":"info","port":"9000","ip":"93.103.119.129","blockNum":7945,"epochNum":104,"ViewId":7945,"blockHash":"0x453d85efdadd60066c4fdaf04f35ef3860b27bbf36e87552615d985c2439f2a9","numTxns":0,"numStakingTxns":0,"caller":"/mnt/jenkins/workspace/harmony-release/harmony/node/node_handler.go:466","time":"**2020-03-17T14:42:46.60113469+01:00","message":"BINGO !!! Reached Consensus"**}

To reproduce: have an active node with at least 1 bls key, bingoing and elected. Then edit validator and add another key without restarting the node. 

If this is the case where all bls keys together need to sign 66% blocks (each bls key adds additional blocks to sign), then i should either stay active and elected since 2/3 bls keys are signing, or get kicked out because i sign less than 66% AND i should NOT bingo anymore, like i do now. I will further test this and add a 4th bls key -> since the 4th would mean i sign with 3/4 bls keys so i should stay elected even if 4th bls key isnt active (i never restart node.sh to activate it).

**Comment by mindstyle85** [comment]
ok so i get why i went inactive, since the 2 bls keys signing couldnt go over/stay at 66%, what i dont understand is why i was still bingoing when i should not?

**Comment by mindstyle85** [comment]
ok just went below 66% on 3 active and 1 non active key, looks like there are still some random issues with signing blocks..

"current-epoch-signing-percent": {
      "current-epoch-signed": 105,
      "current-epoch-to-sign": 164,
      "percentage": "0.640243902439024390"

**Comment by rlan35** [comment]
@mindstyle85 non-active key are not counted into the percentage. The percentage only counts the keys that's elected and should sign blocks.

**Comment by mindstyle85** [comment]
> @mindstyle85 non-active key are not counted into the percentage. The percentage only counts the keys that's elected and should sign blocks.

yeh realised that, all my keys were/are elected though, so if 3/4 keys are signing (4th key isnt even active, meaning i didnt restart node.sh nor added it to the bls subfolder), i can expect a 75% sign rate.. however even that was random and dropped down as much as to 60%.

From the original post you can see that i got flagged inactive while i signed just above 66% blocks, and while my status was inactive and not elected on the dashboard, i was still bingoing (unfortunately i did not check if i was receiving rewards, but i was deff still bingoing).

**Comment by rlan35** [comment]
yea, the bingo printout is not simply saying you received a confirmed block, it actually doesn't say whether you signed (got reward) or not.
