### ISSUE TITLE
restarting node: curl: (23) Failed writing body (0 != 10024) node.sh: cannot download harmony (status 23) node.sh: initial node software update failed

### ISSUE THREAD

**Issue by lijiang2087** [harmony-one/harmony#2518]
when i run:
./node.sh -S -c -I -N staking -z -k c1862b5b975a69612946d57a0649c9ed266511f6ea5653886af12782f73911f0907be7848d9d28ec69ca97c13f3e9594.key

i get this error message:
curl: (23) Failed writing body (0 != 10024)
node.sh: cannot download harmony (status 23)
node.sh: initial node software update failed

**Comment by john-harmony** [comment]
You may need to update your node.sh 
Please see https://docs.harmony.one/home/validators/first-time-setup/running-a-node
```
curl -LO https://raw.githubusercontent.com/harmony-one/harmony/master/scripts/node.sh && chmod a+x node.sh
```

**Comment by lijiang2087** [comment]
thanks, it's currently up. will know this in the future.

**Comment by mindstyle85** [comment]
think this can be closed? :)

**Comment by lijiang2087** [comment]
yes
