### ISSUE TITLE
current-epoch-blocks-left overflow error

### ISSUE THREAD

**Issue by mindstyle85** [harmony-one/harmony#2520]
**Describe the bug**

"current-epoch-signing-percent": {
        **"current-epoch-blocks-left": 18446744073709552000,**
        "current-epoch-signed": 44,
        "current-epoch-signing-percentage": "0.458333333333333333",
        "current-epoch-to-sign": 96

**Comment by mikedoan** [comment]
can you please elaborate on this issue?

**Comment by mindstyle85** [comment]
you dont see the abnormally high (bolded) curren-epoch-blocks-left number? @fxfactorial can explain better, but that number is wrong and WAY too high, @fxfactorial said its an overflow issue

**Comment by mindstyle85** [comment]
it also shows too small of a number for blocks to sign:

"current-epoch-performance": {
      "current-epoch-signing-percent": {
        **"current-epoch-blocks-left": 20,**
        "current-epoch-signed": 18,
        "current-epoch-signing-percentage": "1.000000000000000000",
        "current-epoch-to-sign": 18

after that counter hits zero, the above mentioned abnormally high number appears

@mikedoan

**Comment by mikedoan** [comment]
@mindstyle85 got. it. this should be assigned to @fxfactorial
