### ISSUE TITLE
node.sh swallows the stack trace, print it out always 

### ISSUE THREAD

**Issue by fxfactorial** [harmony-one/harmony#2539]
Currently node.sh swallows the errors of the harmony binary. It should print out the actual errors because otherwise our pangaea volunteers have an extra burden of finding the actual stack trace as opposed to just copy pasting the thing on their screen. 

![Screenshot from 2020-03-19 14-02-04](https://user-images.githubusercontent.com/3036816/77114760-56ef2b80-69ea-11ea-9d31-be08e7db9537.png)

**Comment by LeoHChen** [comment]
@mindstyle85 , please provide some more details on the OS.  I run the node.sh with Amazon Linux 2 and I tried to trigger panic and the stack trace was print out to my console.  

You can also try to use `pkill -SIGABORT harmony` to trigger a trace dump to check.

Another thing you may try to use `ulimit -c unlimited` to enable core dump on the system.

**Comment by mindstyle85** [comment]
@LeoHChen this was edgar's, i just added the label, and the user was a volunteer but i will try to get the OS at least

**Comment by mindstyle85** [comment]
the volunteer got this on Vultr Ubuntu 18.04, unfortunately it was just one time and he is now using Linux Mint - says he doesnt have any issues anymore

**Comment by LeoHChen** [comment]
it's easy to test using 

`pkill -SIGABORT harmony` to trigger a trace dump.  I am closing this ticket, let me know if you can help me diagnose more.

**Comment by fxfactorial** [comment]
@LeoHChen Sorry I didn't get back on this, actually the person let me ssh into their machine and the signal wasn't SIGABORT but was SIGBUS which was super weird and I couldn't figure out at the time. I think the arch of the machine or the CPU itself didn't have some instructions, maybe. Anyway that validator was able to continue on another machine
