### ISSUE TITLE
Rename state.StateDB → state.DB

### ISSUE THREAD

**Issue by harmony-ek** [harmony-one/harmony#255]
This is in response to the following golint warning:

    core/state/statedb.go:60:6:warning: type name will be used as state.StateDB by other packages, and that stutters; consider calling this DB (golint)

**Comment by mikedoan** [comment]
@harmony-ek is this fixed?

**Comment by mindstyle85** [comment]
@mikedoan @LeoHChen can we close this one?

**Comment by lijiang2087** [comment]
@mikedoan @mindstyle85 @LeoHChen from jan 2019? and no one actively working on it. i'm closing this.
