### ISSUE TITLE
Proposal to deny/reject delegation

### ISSUE THREAD

**Issue by BrunoMarshall** [harmony-one/harmony#2550]
Proposal for validators to deny or decrease delegations.

the proposal is to give the power to validator to decrease or deny delegation, this is an important tool for validators to be able to be in the near the median, in case that the median decrease.

For exemple:
currently i will like to decrease the stake in my validator to be near the median, but i can´t because i have delegations in place:
![image](https://user-images.githubusercontent.com/35432495/77150762-e6511900-6a94-11ea-96bd-349ed86a573a.png)

I would like to reject or decrease this delegations to my validator

**Comment by sophoah** [comment]
what process flow would you see that working ? like a request for a delegation that the validator needs to approve? if already delegated, i think it is tough to undelegate on the delegator behalf :)

**Comment by mindstyle85** [comment]
i dont think this is doable tbh, in a decentralized network everyone should be allowed to delegate anywhere.. if at some point you dont want more delegations you can change fees to be higher or set max_delegation to something you are comfortable with imo..

these two options plus multibls is perfectly good i think

**Comment by mindstyle85** [comment]
can we close this?

**Comment by BrunoMarshall** [comment]
will close this proposal, thank you all
