### ISSUE TITLE
Total Effective stake is incorrect. Node with 1 token staked, earning 25k+ rewards, always elected.

### ISSUE THREAD

**Issue by mirrormirage0** [harmony-one/harmony#2551]
**Describe the bug**
1) Validator node has only 1 $ONE token staked.
2) Is always in the committee
3) Earning an insane amount of rewards.

 **"total-effective-stake": "8740125000000000000000.000000000000000000"**

**To Reproduce**
1. Create a validator with 1 $ONE token staked.
2. Get elected  / Activate node.

**Expected behavior**
1. Since there are 30 other nodes with higher amounts staked and possibly better signing percentage, this node should be kicked and not in committee
2. Total effective stake calculation should be fixed.

**Screenshots**
![image](https://user-images.githubusercontent.com/29485946/77152956-5752f980-6ab2-11ea-910e-a9856aa4e174.png)

**Environment (please complete the following information):**

**Additional context**
```
{
  "id": "0",
  "jsonrpc": "2.0",
  "result": {
    "current-epoch-performance": {
      "current-epoch-signing-percent": {
        "current-epoch-blocks-left": 30,
        "current-epoch-signed": 8,
        "current-epoch-signing-percentage": "1.000000000000000000",
        "current-epoch-to-sign": 8
      }
    },
    "currently-in-committee": true,
    "epos-status": "currently elected and signing enough blocks to be eligible for election next epoch",
    "metrics": {
      "by-shard": [
        {
          "bls-public-key": "4c114982081e609c090fd2084fc7d562b0670ac2ed1d3ec2fd99e07ae21469c0df7f1f6cd6f7c96f61dea9e4c626a409",
          "earning-account": "one1vfqqagdzz352mtvdl69v0hw953hm993n6v26yl",
          "effective-stake": "8740125000000000000000.000000000000000000",
          "group-percent": "0.092351644461820300",
          "overall-percent": "0.029552526227782516",
          "shard-id": 1
        }
      ],
      "current-apr": "0.000000000000000000",
      "total-effective-stake": "8740125000000000000000.000000000000000000"
    },
    "total-delegation": 1000000000000000000,
    "validator": {
      "address": "one1vfqqagdzz352mtvdl69v0hw953hm993n6v26yl",
      "bls-public-keys": [
        "4c114982081e609c090fd2084fc7d562b0670ac2ed1d3ec2fd99e07ae21469c0df7f1f6cd6f7c96f61dea9e4c626a409"
      ],
      "creation-height": 547,
      "delegations": [
        {
          "amount": 1000000000000000000,
          "delegator-address": "one1vfqqagdzz352mtvdl69v0hw953hm993n6v26yl",
          "reward": 2.5919546991656015e+22,
          "undelegations": []
        }
      ],
      "details": "mirrormirage0",
      "identity": "mirrormirage0",
      "last-epoch-in-committee": 151,
      "lifetime": {
        "blocks": {
          "signed": 5272,
          "to-sign": 5280
        },
        "reward-accumulated": 2.5919546991656015e+22
      },
      "max-change-rate": "0.050000000000000000",
      "max-rate": "0.500000000000000000",
      "max-total-delegation": 1000000000000000000,
      "min-self-delegation": 1000000000000000000,
      "name": "MirrorMirage P-OPS ",
      "rate": "0.100000000000000000",
      "security-contact": "mirrormirage0",
      "update-height": 547,
      "website": "mirrormirage0@harmony.one"
    }
  }
}
```

**Comment by BrunoMarshall** [comment]
Just to mention that the median at that time range (7 hours) was changed between 10000  and  80000.
Incredible is that that validator is in the the top 10 validator
![image](https://user-images.githubusercontent.com/35432495/77154011-2d420d00-6a9b-11ea-9385-3808ba310247.png)

**Comment by sophoah** [comment]
@mirrormirage0 that is really nice finding. Current median stake is 10300 (might be a bit lower when you executed the validator information) so if we follow the effective stake formula:
![image](https://user-images.githubusercontent.com/35721420/77153821-73b45d80-6ad5-11ea-860c-0775054f1f15.png)
it looks like the code is doing the correct maths : 
```
c=0.15
median_stake = 10300
actual_stake  = 1

min((1+c) * median_stake, actual_stake) = min (1.15 *10300, 1) = 1
es = max (min((1+c) * median_stake, actual_stake), (1-c) * median_stake)
es = max (1, 0.85 * 10300) = max (1, 8755) = 8755
```
so I don't think this was the expected behavior ... formula should be : 
```
es = min (min((1+c) * median_stake, actual_stake), (1-c) * median_stake)
```
I also verified all other validator that are below 0.85*median_stake has the same effective stake of 8755.

@fxfactorial @lijiang2087 @rlan35  for info

**Comment by fxfactorial** [comment]
Dump the median stake computation breakdown while doing this investigation as well: hmy blockchain median-stake

**Comment by sophoah** [comment]
@fxfactorial let you relook at that later in your day. this is the effective stake that we are talking about here

**Comment by mirrormirage0** [comment]
`hmy blockchain median-stake
{
  "id": "0",
  "jsonrpc": "2.0",
  "result": {
    "epos-median-stake": "17000000000000000000000.000000000000000000",
    "epos-slot-candidates": [
      {
        "keys-at-auction": [
          "5bde9d28af81e43faf13f1ccdb2b3e8f6cbe9f76930ba6b79647476e228ef6380c15699658c4d615d474460225de8d12"
        ],
        "percentage-of-total-auction-stake": "0.010791295357851551",
        "stake": 9.999999e+22,
        "validator": "one1rhkl7c0jz09c9ffp2pncyr4uwamfpmcr83ufkr"
      },
      {
        "keys-at-auction": [
          "e6791a7fd6ad130035dc16cb9a463bc6932f782d3599b7317873b76e137df0d4b23903d93655efec4067442e8f532c09"
        ],
        "percentage-of-total-auction-stake": "0.033453018954641703",
        "stake": 3.1e+23,
        "validator": "one1c9h3u72czs6sk755tjyse7x5t70m38ppnkx922"
      },
      {
        "keys-at-auction": [
          "72d1d938e5743e625b14c9926e1a7fe57fe25591ff8de4abdc51c6a7f5215a816f117a64bd0a416aa9e06e2355887c0a"
        ],
        "percentage-of-total-auction-stake": "0.001079021730733750",
        "stake": 9.999e+21,
        "validator": "one1gjhqdsgqt0dc2a8zrdyu7z8jv2kal86jcpkr2f"
      },
      {
        "keys-at-auction": [
          "6b109edaae955a8ca4e158011bbca0bd0006a3b8fe696469f5ba967954631d2250d5f31729ba11df1392bff7d498ca0f"
        ],
        "percentage-of-total-auction-stake": "0.000971216679328307",
        "stake": 9e+21,
        "validator": "one1a8avzz3hcvhfrh2tp7rdprpvwt838y9um9c2q7"
      },
      {
        "keys-at-auction": [
          "2e573ffa6ae3e166a266757a3f28c1365d589f10a2b95a2bee4500a322fba988b8bfe6065369e2117fde92dca523b213"
        ],
        "percentage-of-total-auction-stake": "0.102625229115691159",
        "stake": 9.51e+23,
        "validator": "one1wz9fmjrwua3le0c8qxv058p3wpdg4ctjyc3ha4"
      },
      {
        "keys-at-auction": [
          "7694c414807f6e54636364831e4bef0b905bfbe1a8490ab8c20d2739b6a09834e507b2aaf3e39d427cd8fb75fbf09c11"
        ],
        "percentage-of-total-auction-stake": "0.001823729097849822",
        "stake": 1.69e+22,
        "validator": "one1t4p6x5k7zw59kers7hwmjh3kymj0n6spr02qnf"
      },
      {
        "keys-at-auction": [
          "72b674a1c58ecf2fa9990c5765f4b4692a355e9140fc1d2a37088f62d1b582d12ab07537ec6117d8b139060a11451e06"
        ],
        "percentage-of-total-auction-stake": "0.001079021730733750",
        "stake": 9.999e+21,
        "validator": "one1cr5q35dwd2svwutwm3wg4tf6xpqn0xkt0qqh78"
      },
      {
        "keys-at-auction": [
          "afc4d81ab636323b04893c23d3404f38e95e9291b3d5299dade3d03822edd3a2b799bd6d64265a9a9cac025d5dbd600c"
        ],
        "percentage-of-total-auction-stake": "0.001079042234196980",
        "stake": 9.99919e+21,
        "validator": "one1m6j80t6rhc3ypaumtsfmqwjwp0mrqk9ff50prh"
      },
      {
        "keys-at-auction": [
          "47cabe5f9a7d03d56fd42857ef3746af6d33685566e8ebea9cd86da935bffbdabc8655ae619cb98daaf602d5ba093002"
        ],
        "percentage-of-total-auction-stake": "0.001079021730733750",
        "stake": 9.999e+21,
        "validator": "one1aqa8tj8fs7wkwnclxgzmau2zc24jzhhlnypjfq"
      },
      {
        "keys-at-auction": [
          "1a7e720cd8f67390ba16907ef52b4b80421fa4bcd34957a242b08c98db6dfc07436d15f1297ce7568b2367d273edc482"
        ],
        "percentage-of-total-auction-stake": "0.001107726579256120",
        "stake": 1.0265e+22,
        "validator": "one1xqsanwfj98ffuvjjz9uk40qnzghcmhlyszl52u"
      },
      {
        "keys-at-auction": [
          "2e5a73960c496b63c4c41e14b49fe3c4e09e85ecde40da234cdd669f51bd6ca3e4d933a851a4e46c06fb7d8fa5fe3d0f"
        ],
        "percentage-of-total-auction-stake": "0.005719387111600033",
        "stake": 5.3e+22,
        "validator": "one1uvt0yl7dxyt9rh37gzm49vy3pgf0c3aud4k5p5"
      },
      {
        "keys-at-auction": [
          "7df0c7950e7cf1fcfad9e8177ac9ab89a81fee46448543075b957a69954309944abc74404af78b27ebf35620aac8f091"
        ],
        "percentage-of-total-auction-stake": "0.001079129643698119",
        "stake": 1e+22,
        "validator": "one1qyvwqh6klj2cfnzk4mcrlwae3790dm33jgy6kw"
      },
      {
        "keys-at-auction": [
          "718b9ead7b9aaa9cb70570450c6256937c86f08978c8a48b536c2a849f61ff52f1b78b39014064cefc5f223efd45a080"
        ],
        "percentage-of-total-auction-stake": "0.033129280061532267",
        "stake": 3.07e+23,
        "validator": "one1ekup98s5tqxtr5hdzsz664cfy579jpq6w5smrr"
      },
      {
        "keys-at-auction": [
          "90462265e64b5d5b39d5831e44840d89a525ee8c7ebd8cfb07ab381a02a97f4f8da63b663deab59c63b6073db9cf4314"
        ],
        "percentage-of-total-auction-stake": "0.001079129643698119",
        "stake": 1e+22,
        "validator": "one17tj2jjehdlg8xfgp48xpeyqur2qf6nvs88jvyu"
      },
      {
        "keys-at-auction": [
          "e429cbf74e8ab28ed295999d179ad79827c7febe0208a6145aa91bbb60b68a0b1907de4c38573352cafe00c8105b1116",
          "1c57c3282714e412d974a5c1c5712f1f6062d3253d9a080580abf4342805e3311c19f81bef5b1a903fe282650b767a12"
        ],
        "percentage-of-total-auction-stake": "0.002158259287396239",
        "stake": 2e+22,
        "validator": "one1s7fp0jrmd97estwye3mhkp7xsqf42vn5x2sfqy"
      },
      {
        "keys-at-auction": [
          "a6e2ae873327f2c5fc11c94bdb874ba82344a33cad8d0081600063278bd2822024d905e6338a2b8a8f84eef15f20fa14"
        ],
        "percentage-of-total-auction-stake": "0.011978339045049126",
        "stake": 1.11e+23,
        "validator": "one10jvjrtwpz2sux2ngktg3kq7m3sdz5p5au5l8c8"
      },
      {
        "keys-at-auction": [
          "7a4a5b3881a9f64851c9b5ec5c449b293ce567dec39bd3e80b9726cc12825e0eec0ef2bc682114e2f123ad7e1bcc6b99"
        ],
        "percentage-of-total-auction-stake": "0.051797143767866035",
        "stake": 4.7999e+23,
        "validator": "one17d60e5nvjnzechwl56y38ze6w49wejhtanncra"
      },
      {
        "keys-at-auction": [
          "6d5c07ee92b7caff12c245724cc065a8274113ae815c45f257f3c3f81017ab1f401bf76ca11c23f9fe7d0a375245648b"
        ],
        "percentage-of-total-auction-stake": "0.118704260806793138",
        "stake": 1.1e+24,
        "validator": "one12d5a58rcpyf8chlcd2my8r8ns572uppetmxqrx"
      },
      {
        "keys-at-auction": [
          "394d726edbb908fa71bdb2b417dd0fe7c77d9f86b3a0b1e1b51d11e26dd1cddb4e21269c3e1d08e75d43ec98ff4ca582"
        ],
        "percentage-of-total-auction-stake": "0.158693244274421241",
        "stake": 1.470567e+24,
        "validator": "one18vn078vyp5jafma8q7kek6w0resrgex9yufqws"
      },
      {
        "keys-at-auction": [
          "95b7f81b4ad71a93e866c918a122a8754cf6db02c0f3df93d00e6651b77323d527ac39fc3e990f9c2f6e1e3ea9d15112"
        ],
        "percentage-of-total-auction-stake": "0.104459749509977962",
        "stake": 9.68e+23,
        "validator": "one1km7xg8e3xjys7azp9f4xp8hkw79vm2h3f2lade"
      },
      {
        "keys-at-auction": [
          "0ad7f33c63497d22393aa16139b8d09f65ff188c52b391565faad739c9c3f0b5cfbcdf00c53cbe5e2d0137fd90a2dc92"
        ],
        "percentage-of-total-auction-stake": "0.001089920940135101",
        "stake": 1.01e+22,
        "validator": "one10qq0uqa4gvgdufqjph89pp7nj6yeatz94xdjrt"
      },
      {
        "keys-at-auction": [
          "66647c9c6c313c1438b4f2b1c165ed69ca67158f1ac15c89b97b2aba25b0506159d21c61c5f6cb4b24d241ec670fd201"
        ],
        "percentage-of-total-auction-stake": "0.010791188524016825",
        "stake": 9.9999e+22,
        "validator": "one1j33qtvx86j4ugy0a8exwwhtldm5wv4daksrwsl"
      },
      {
        "keys-at-auction": [
          "a2232487bbf16dd01c5743700712819984d036bf3e39960c85045920784ba0d24149c93591dd4017ada3155e8105d402"
        ],
        "percentage-of-total-auction-stake": "0.001079129643698119",
        "stake": 1e+22,
        "validator": "one1vzsj3julf0ljcj3hhxuqpu6zvadu488zfrtttz"
      },
      {
        "keys-at-auction": [
          "4f6a446f223531e2ab6d7af2f083be68e2768162c61e18933b59d4bb39264bb7893cb1bed8a3309673c627176f88a799"
        ],
        "percentage-of-total-auction-stake": "0.010791296436981194",
        "stake": 1e+23,
        "validator": "one1k9577lnpfx7z76zslc6r8gdmsp5kqgpll7cpk9"
      },
      {
        "keys-at-auction": [
          "d90b4af4db279822edc6b4aa6a2b083512d0b6a873d8e71c814b7994e0f32b97f6a6d81d21344d7fa85e76f76af5e783"
        ],
        "percentage-of-total-auction-stake": "0.107912964369811944",
        "stake": 1e+24,
        "validator": "one1egemh5e9xjy3x8d3cq0kq7mw4sw4jjwgkc7axs"
      },
      {
        "keys-at-auction": [
          "a689b39bb1de4f1591e29094b91d00596b0f371ea16fadf8b4143c680a1f9aff3e805e167eda2c583827ed0e7c8c9882",
          "842d27a14584d18fdf53951f0c24cc3a6a55ae0b4e639cbf9db15e675a6aa0f87819b78fb5d51ccf3b8bc2aefb47e186"
        ],
        "percentage-of-total-auction-stake": "0.003669040788573606",
        "stake": 3.4e+22,
        "validator": "one1gjsxmewzws9mt3fn65jmdhr3e4hel9xza8wd6t"
      },
      {
        "keys-at-auction": [
          "2c0dc11699853c0169202997d55820f8fec38f953dbd9c15c20dc98efaf24b29acc27fa63d545f777470f69f466ae503"
        ],
        "percentage-of-total-auction-stake": "0.000010791296436981",
        "stake": 100000000000000000000,
        "validator": "one1yjtrsq78t02qgjcwn56x96kwkduwhmc8wnenfw"
      },
      {
        "keys-at-auction": [
          "7ab21e88f5d17712e30dfc9a7acdb7e0e784fabf2bf76d5f83d8a0269dd47f38d8f454cb7ece5921027a9b68d806578f",
          "bd8a0ab99bc6468b10992846f74b9f4c23ed1ce9a89848a4edba15bbef10906091880e9f10b3b0e53000c2b4f934cb97"
        ],
        "percentage-of-total-auction-stake": "0.073272902807102310",
        "stake": 6.79e+23,
        "validator": "one1tpxl87y4g8ecsm6ceqay49qxyl5vs94jjyfvd9"
      },
      {
        "keys-at-auction": [
          "4c114982081e609c090fd2084fc7d562b0670ac2ed1d3ec2fd99e07ae21469c0df7f1f6cd6f7c96f61dea9e4c626a409"
        ],
        "percentage-of-total-auction-stake": "0.000000107912964370",
        "stake": 1000000000000000000,
        "validator": "one1vfqqagdzz352mtvdl69v0hw953hm993n6v26yl"
      },
      {
        "keys-at-auction": [
          "26f5128639f480843e52a8328bb37d9c0b74e4dab75e8945dbcb4977c5995b3cc29807181a5a64d2c433ac4ed81e7d81"
        ],
        "percentage-of-total-auction-stake": "0.002535954662690581",
        "stake": 2.35e+22,
        "validator": "one1la07f5wduc3379ffzlpqrl4rcvlchyvtwf3uyj"
      },
      {
        "keys-at-auction": [
          "516ed79377753aafeb17a06b219375ccb1a3fdbb6cf1659b055d5946f4432ec35deec920a11c83d8c5045f60fde81082"
        ],
        "percentage-of-total-auction-stake": "0.001079021730733750",
        "stake": 9.999e+21,
        "validator": "one1vusgu2vytafhfczp7kqj6jvquvgx7nequ2zcjz"
      },
      {
        "keys-at-auction": [
          "a44b20c5c9fa3acf1a06f690b6b3c37b71860ddc196247d86ca2f4a4fd6524eb0190068467fb218f8e0493eeb96a600e"
        ],
        "percentage-of-total-auction-stake": "0.128912827236177348",
        "stake": 1.1946e+24,
        "validator": "one1dsy63tatz7avdrl24y5clramvgur9hsarglcdl"
      },
      {
        "keys-at-auction": [
          "2a8d3687d34ae1aca7ca00db66feedccd845282f348b11246d53b092b4e902f20f897a3d60acbe8e4b1c984be1223f05"
        ],
        "percentage-of-total-auction-stake": "0.000971216679328307",
        "stake": 9e+21,
        "validator": "one1tewvfjk0d4whmajpqvcvzfpx6wftrh0gagsa7n"
      },
      {
        "keys-at-auction": [
          "5e5ccd77a8d7d630f52d9572d8d63694ccfd18e7013729294365df154493cf481b6aa5ae18ba21bba345bfaf1d641e10"
        ],
        "percentage-of-total-auction-stake": "0.013996311478656696",
        "stake": 1.29699999999e+23,
        "validator": "one1dcmp24uqgwszcvmm8n6r5dvhqhuukdj86pkg6n"
      },
      {
        "keys-at-auction": [
          "becd65dfdcb41486187b5e9c4e1b0758ff30c302b0bfb29b57e92278c4c55a869c3d9d176b9b4339787b1e961e306c14"
        ],
        "percentage-of-total-auction-stake": "0.000001079129643698",
        "stake": 10000000000000000000,
        "validator": "one1jm28f73rmg7lnca7duuyuqrhkp4ahfzdvzzdsf"
      }
    ],
    "epos-slot-winners": [
      {
        "bls-public-key": "394d726edbb908fa71bdb2b417dd0fe7c77d9f86b3a0b1e1b51d11e26dd1cddb4e21269c3e1d08e75d43ec98ff4ca582",
        "eposed-stake": "19550000000000000000000.000000000000000000",
        "slot-owner": "one18vn078vyp5jafma8q7kek6w0resrgex9yufqws"
      },
      {
        "bls-public-key": "a44b20c5c9fa3acf1a06f690b6b3c37b71860ddc196247d86ca2f4a4fd6524eb0190068467fb218f8e0493eeb96a600e",
        "eposed-stake": "19550000000000000000000.000000000000000000",
        "slot-owner": "one1dsy63tatz7avdrl24y5clramvgur9hsarglcdl"
      },
      {
        "bls-public-key": "6d5c07ee92b7caff12c245724cc065a8274113ae815c45f257f3c3f81017ab1f401bf76ca11c23f9fe7d0a375245648b",
        "eposed-stake": "19550000000000000000000.000000000000000000",
        "slot-owner": "one12d5a58rcpyf8chlcd2my8r8ns572uppetmxqrx"
      },
      {
        "bls-public-key": "d90b4af4db279822edc6b4aa6a2b083512d0b6a873d8e71c814b7994e0f32b97f6a6d81d21344d7fa85e76f76af5e783",
        "eposed-stake": "19550000000000000000000.000000000000000000",
        "slot-owner": "one1egemh5e9xjy3x8d3cq0kq7mw4sw4jjwgkc7axs"
      },
      {
        "bls-public-key": "95b7f81b4ad71a93e866c918a122a8754cf6db02c0f3df93d00e6651b77323d527ac39fc3e990f9c2f6e1e3ea9d15112",
        "eposed-stake": "19550000000000000000000.000000000000000000",
        "slot-owner": "one1km7xg8e3xjys7azp9f4xp8hkw79vm2h3f2lade"
      },
      {
        "bls-public-key": "2e573ffa6ae3e166a266757a3f28c1365d589f10a2b95a2bee4500a322fba988b8bfe6065369e2117fde92dca523b213",
        "eposed-stake": "19550000000000000000000.000000000000000000",
        "slot-owner": "one1wz9fmjrwua3le0c8qxv058p3wpdg4ctjyc3ha4"
      },
      {
        "bls-public-key": "7a4a5b3881a9f64851c9b5ec5c449b293ce567dec39bd3e80b9726cc12825e0eec0ef2bc682114e2f123ad7e1bcc6b99",
        "eposed-stake": "19550000000000000000000.000000000000000000",
        "slot-owner": "one17d60e5nvjnzechwl56y38ze6w49wejhtanncra"
      },
      {
        "bls-public-key": "7ab21e88f5d17712e30dfc9a7acdb7e0e784fabf2bf76d5f83d8a0269dd47f38d8f454cb7ece5921027a9b68d806578f",
        "eposed-stake": "19550000000000000000000.000000000000000000",
        "slot-owner": "one1tpxl87y4g8ecsm6ceqay49qxyl5vs94jjyfvd9"
      },
      {
        "bls-public-key": "bd8a0ab99bc6468b10992846f74b9f4c23ed1ce9a89848a4edba15bbef10906091880e9f10b3b0e53000c2b4f934cb97",
        "eposed-stake": "19550000000000000000000.000000000000000000",
        "slot-owner": "one1tpxl87y4g8ecsm6ceqay49qxyl5vs94jjyfvd9"
      },
      {
        "bls-public-key": "e6791a7fd6ad130035dc16cb9a463bc6932f782d3599b7317873b76e137df0d4b23903d93655efec4067442e8f532c09",
        "eposed-stake": "19550000000000000000000.000000000000000000",
        "slot-owner": "one1c9h3u72czs6sk755tjyse7x5t70m38ppnkx922"
      },
      {
        "bls-public-key": "718b9ead7b9aaa9cb70570450c6256937c86f08978c8a48b536c2a849f61ff52f1b78b39014064cefc5f223efd45a080",
        "eposed-stake": "19550000000000000000000.000000000000000000",
        "slot-owner": "one1ekup98s5tqxtr5hdzsz664cfy579jpq6w5smrr"
      },
      {
        "bls-public-key": "5e5ccd77a8d7d630f52d9572d8d63694ccfd18e7013729294365df154493cf481b6aa5ae18ba21bba345bfaf1d641e10",
        "eposed-stake": "19550000000000000000000.000000000000000000",
        "slot-owner": "one1dcmp24uqgwszcvmm8n6r5dvhqhuukdj86pkg6n"
      },
      {
        "bls-public-key": "a6e2ae873327f2c5fc11c94bdb874ba82344a33cad8d0081600063278bd2822024d905e6338a2b8a8f84eef15f20fa14",
        "eposed-stake": "19550000000000000000000.000000000000000000",
        "slot-owner": "one10jvjrtwpz2sux2ngktg3kq7m3sdz5p5au5l8c8"
      },
      {
        "bls-public-key": "4f6a446f223531e2ab6d7af2f083be68e2768162c61e18933b59d4bb39264bb7893cb1bed8a3309673c627176f88a799",
        "eposed-stake": "19550000000000000000000.000000000000000000",
        "slot-owner": "one1k9577lnpfx7z76zslc6r8gdmsp5kqgpll7cpk9"
      },
      {
        "bls-public-key": "5bde9d28af81e43faf13f1ccdb2b3e8f6cbe9f76930ba6b79647476e228ef6380c15699658c4d615d474460225de8d12",
        "eposed-stake": "19550000000000000000000.000000000000000000",
        "slot-owner": "one1rhkl7c0jz09c9ffp2pncyr4uwamfpmcr83ufkr"
      },
      {
        "bls-public-key": "66647c9c6c313c1438b4f2b1c165ed69ca67158f1ac15c89b97b2aba25b0506159d21c61c5f6cb4b24d241ec670fd201",
        "eposed-stake": "19550000000000000000000.000000000000000000",
        "slot-owner": "one1j33qtvx86j4ugy0a8exwwhtldm5wv4daksrwsl"
      },
      {
        "bls-public-key": "2e5a73960c496b63c4c41e14b49fe3c4e09e85ecde40da234cdd669f51bd6ca3e4d933a851a4e46c06fb7d8fa5fe3d0f",
        "eposed-stake": "19550000000000000000000.000000000000000000",
        "slot-owner": "one1uvt0yl7dxyt9rh37gzm49vy3pgf0c3aud4k5p5"
      },
      {
        "bls-public-key": "26f5128639f480843e52a8328bb37d9c0b74e4dab75e8945dbcb4977c5995b3cc29807181a5a64d2c433ac4ed81e7d81",
        "eposed-stake": "19550000000000000000000.000000000000000000",
        "slot-owner": "one1la07f5wduc3379ffzlpqrl4rcvlchyvtwf3uyj"
      },
      {
        "bls-public-key": "a689b39bb1de4f1591e29094b91d00596b0f371ea16fadf8b4143c680a1f9aff3e805e167eda2c583827ed0e7c8c9882",
        "eposed-stake": "17000000000000000000000.000000000000000000",
        "slot-owner": "one1gjsxmewzws9mt3fn65jmdhr3e4hel9xza8wd6t"
      },
      {
        "bls-public-key": "842d27a14584d18fdf53951f0c24cc3a6a55ae0b4e639cbf9db15e675a6aa0f87819b78fb5d51ccf3b8bc2aefb47e186",
        "eposed-stake": "17000000000000000000000.000000000000000000",
        "slot-owner": "one1gjsxmewzws9mt3fn65jmdhr3e4hel9xza8wd6t"
      },
      {
        "bls-public-key": "7694c414807f6e54636364831e4bef0b905bfbe1a8490ab8c20d2739b6a09834e507b2aaf3e39d427cd8fb75fbf09c11",
        "eposed-stake": "16900000000000000000000.000000000000000000",
        "slot-owner": "one1t4p6x5k7zw59kers7hwmjh3kymj0n6spr02qnf"
      },
      {
        "bls-public-key": "1a7e720cd8f67390ba16907ef52b4b80421fa4bcd34957a242b08c98db6dfc07436d15f1297ce7568b2367d273edc482",
        "eposed-stake": "14450000000000000000000.000000000000000000",
        "slot-owner": "one1xqsanwfj98ffuvjjz9uk40qnzghcmhlyszl52u"
      },
      {
        "bls-public-key": "0ad7f33c63497d22393aa16139b8d09f65ff188c52b391565faad739c9c3f0b5cfbcdf00c53cbe5e2d0137fd90a2dc92",
        "eposed-stake": "14450000000000000000000.000000000000000000",
        "slot-owner": "one10qq0uqa4gvgdufqjph89pp7nj6yeatz94xdjrt"
      },
      {
        "bls-public-key": "7df0c7950e7cf1fcfad9e8177ac9ab89a81fee46448543075b957a69954309944abc74404af78b27ebf35620aac8f091",
        "eposed-stake": "14450000000000000000000.000000000000000000",
        "slot-owner": "one1qyvwqh6klj2cfnzk4mcrlwae3790dm33jgy6kw"
      },
      {
        "bls-public-key": "a2232487bbf16dd01c5743700712819984d036bf3e39960c85045920784ba0d24149c93591dd4017ada3155e8105d402",
        "eposed-stake": "14450000000000000000000.000000000000000000",
        "slot-owner": "one1vzsj3julf0ljcj3hhxuqpu6zvadu488zfrtttz"
      },
      {
        "bls-public-key": "e429cbf74e8ab28ed295999d179ad79827c7febe0208a6145aa91bbb60b68a0b1907de4c38573352cafe00c8105b1116",
        "eposed-stake": "14450000000000000000000.000000000000000000",
        "slot-owner": "one1s7fp0jrmd97estwye3mhkp7xsqf42vn5x2sfqy"
      },
      {
        "bls-public-key": "1c57c3282714e412d974a5c1c5712f1f6062d3253d9a080580abf4342805e3311c19f81bef5b1a903fe282650b767a12",
        "eposed-stake": "14450000000000000000000.000000000000000000",
        "slot-owner": "one1s7fp0jrmd97estwye3mhkp7xsqf42vn5x2sfqy"
      },
      {
        "bls-public-key": "90462265e64b5d5b39d5831e44840d89a525ee8c7ebd8cfb07ab381a02a97f4f8da63b663deab59c63b6073db9cf4314",
        "eposed-stake": "14450000000000000000000.000000000000000000",
        "slot-owner": "one17tj2jjehdlg8xfgp48xpeyqur2qf6nvs88jvyu"
      },
      {
        "bls-public-key": "afc4d81ab636323b04893c23d3404f38e95e9291b3d5299dade3d03822edd3a2b799bd6d64265a9a9cac025d5dbd600c",
        "eposed-stake": "14450000000000000000000.000000000000000000",
        "slot-owner": "one1m6j80t6rhc3ypaumtsfmqwjwp0mrqk9ff50prh"
      },
      {
        "bls-public-key": "72d1d938e5743e625b14c9926e1a7fe57fe25591ff8de4abdc51c6a7f5215a816f117a64bd0a416aa9e06e2355887c0a",
        "eposed-stake": "14450000000000000000000.000000000000000000",
        "slot-owner": "one1gjhqdsgqt0dc2a8zrdyu7z8jv2kal86jcpkr2f"
      },
      {
        "bls-public-key": "516ed79377753aafeb17a06b219375ccb1a3fdbb6cf1659b055d5946f4432ec35deec920a11c83d8c5045f60fde81082",
        "eposed-stake": "14450000000000000000000.000000000000000000",
        "slot-owner": "one1vusgu2vytafhfczp7kqj6jvquvgx7nequ2zcjz"
      },
      {
        "bls-public-key": "72b674a1c58ecf2fa9990c5765f4b4692a355e9140fc1d2a37088f62d1b582d12ab07537ec6117d8b139060a11451e06",
        "eposed-stake": "14450000000000000000000.000000000000000000",
        "slot-owner": "one1cr5q35dwd2svwutwm3wg4tf6xpqn0xkt0qqh78"
      },
      {
        "bls-public-key": "47cabe5f9a7d03d56fd42857ef3746af6d33685566e8ebea9cd86da935bffbdabc8655ae619cb98daaf602d5ba093002",
        "eposed-stake": "14450000000000000000000.000000000000000000",
        "slot-owner": "one1aqa8tj8fs7wkwnclxgzmau2zc24jzhhlnypjfq"
      },
      {
        "bls-public-key": "2a8d3687d34ae1aca7ca00db66feedccd845282f348b11246d53b092b4e902f20f897a3d60acbe8e4b1c984be1223f05",
        "eposed-stake": "14450000000000000000000.000000000000000000",
        "slot-owner": "one1tewvfjk0d4whmajpqvcvzfpx6wftrh0gagsa7n"
      },
      {
        "bls-public-key": "6b109edaae955a8ca4e158011bbca0bd0006a3b8fe696469f5ba967954631d2250d5f31729ba11df1392bff7d498ca0f",
        "eposed-stake": "14450000000000000000000.000000000000000000",
        "slot-owner": "one1a8avzz3hcvhfrh2tp7rdprpvwt838y9um9c2q7"
      },
      {
        "bls-public-key": "2c0dc11699853c0169202997d55820f8fec38f953dbd9c15c20dc98efaf24b29acc27fa63d545f777470f69f466ae503",
        "eposed-stake": "14450000000000000000000.000000000000000000",
        "slot-owner": "one1yjtrsq78t02qgjcwn56x96kwkduwhmc8wnenfw"
      },
      {
        "bls-public-key": "becd65dfdcb41486187b5e9c4e1b0758ff30c302b0bfb29b57e92278c4c55a869c3d9d176b9b4339787b1e961e306c14",
        "eposed-stake": "14450000000000000000000.000000000000000000",
        "slot-owner": "one1jm28f73rmg7lnca7duuyuqrhkp4ahfzdvzzdsf"
      },
      {
        "bls-public-key": "4c114982081e609c090fd2084fc7d562b0670ac2ed1d3ec2fd99e07ae21469c0df7f1f6cd6f7c96f61dea9e4c626a409",
        "eposed-stake": "14450000000000000000000.000000000000000000",
        "slot-owner": "one1vfqqagdzz352mtvdl69v0hw953hm993n6v26yl"
      }
    ],
    "max-external-slots": 200
  }
}
`

median-stake

**Comment by mindstyle85** [comment]
@fxfactorial i believe the calc is correct but please do verify.. this is a corner case here since its a test network and many seats available so a stake of 1 token is making a huge gap.. 

Basically top validator would get median stake + 15% of median stake as his effective stake and
bottom validator would get median stake - 15% of median stake as its effective stake, which is a big number in this case since the validator only stakes 1 ONE, but this wont happen on mainnet.

**Comment by sophoah** [comment]
Ok so after discussing with @mindstyle85 the formula actually give correctly the effective stake define by the upper and lower band of the median-stake and protocol parameter c. However, I think issue was that the effective stake was used to calculate the voting power:
```
      "by-shard": [
        {
          "bls-public-key": "4c114982081e609c090fd2084fc7d562b0670ac2ed1d3ec2fd99e07ae21469c0df7f1f6cd6f7c96f61dea9e4c626a409",
          "earning-account": "one1vfqqagdzz352mtvdl69v0hw953hm993n6v26yl",
          "effective-stake": "8740125000000000000000.000000000000000000",
          "group-percent": "0.092351644461820300",
          "overall-percent": "0.029552526227782516",
          "shard-id": 1
        }
```
and not the actual stake of 1 ? 1 ONE and having an over percent of 2.9% is a lot ...

**Comment by sophoah** [comment]
ok thanks to @mindstyle85, this is the actual objective of EPOS to have those low validator stake to have an effective stake higher than they have, here 1 ONE, so effectively that issue is not an issue :)

**Comment by mindstyle85** [comment]
ok we talked it over with @sophoah so effective stake is ok, and apr and rewards are based on that, it just confused everyone since theres such a small stake in this case due to testnet.. not realistic that such a high gap between median and lowest tier validator will be on mainnet
