### ISSUE TITLE
change hardcoded 25 minutes of the blskey cache

### ISSUE THREAD

**Issue by LeoHChen** [harmony-one/harmony#2559]
## Summary

In this PR, we have set a 25 minutes hardcoded number to invalidate the cache in the following PR.
https://github.com/harmony-one/harmony/pull/2546

This number is just an initial heuristic number.  It has to be a number based on the epoch and block time. So, we need to revisit this number before we launch mainnet.

**Comment by fxfactorial** [comment]
Yep. A few other similar places , later we can factor them all out into a runtime performance characteristic yaml config
