### ISSUE TITLE
StateDB.GetOrNewStateObject() returns a private type

### ISSUE THREAD

**Issue by harmony-ek** [harmony-one/harmony#256]
This triggers the following golint warning:

    core/state/statedb.go:452:66:warning: exported method GetOrNewStateObject returns unexported type *state.stateObject, which can be annoying to use (golint)

Note that this is nontrivial to fix: Renaming `stateObject` → `StateObject` triggers a bunch of public-type-related golint warnings.

**Comment by astralblue** [comment]
Please review for #255 fix; working on #256.
