### ISSUE TITLE
is it a standard behaviour, that a new generated wallet passphrase will be reset to nil when you doing a complete remove for making a hard reset

### ISSUE THREAD

**Issue by scraido** [harmony-one/harmony#2568]
**Describe the bug**
Before when i try to created 1 validator with given wallet passphrase at account creation on a running Multi BLS Node, i found that i couldn't making the validator, even i have type my passphrase or pasting it, it still not gave me validator issue https://github.com/harmony-one/staking-dashboard/issues/228

then i found out my self that my wallet passphrase is reset to nil, i just have to type enter, enter to do the validator

**To Reproduce**
1. create a new CLI wallet, save the 24 mnemonic key
2. remove $ sudo rm -rf bootnode .dht* harmony* hmy .hmy* latest lib* md5* node.sh staging *.rlp wallet
3. download the CLI, node.sh and file needed to run it on ubuntu again
4. prepare or make a new 5 BLS with same passphrase but in this P2 i just reproduce it with 1 BLS
5. run the node
6. restore the wallet that has been erased before using mnemonic
7. create a validator and put --passphrase there, if you can't do that so your wallet pass has been erased, and you can just try it again now when asking for passphrase just press enter, enter

**Expected behavior**
here i asked if it's really a standard behaviour that a new generated wallet passphrase will be reset to nil when you doing a complete remove for making a hard reset, so we can closed this or else this is a bug, expected is when you type the given wallet passphrase it should be worked

**Screenshots**
btw my balance when this happen were;
![balance-now](https://user-images.githubusercontent.com/44559893/76931516-6c495480-691b-11ea-89f7-a3887c2ec326.png)

details with 5 BLS node run;
![validator-fail](https://user-images.githubusercontent.com/44559893/76931579-913dc780-691b-11ea-939d-426bcf3d26d3.png)

details with 1 BLS node run;
![reset-to-nil](https://user-images.githubusercontent.com/44559893/77221189-03abe300-6b7a-11ea-897b-b3c635d3445d.png)

**Environment (please complete the following information):**
 - OS: ubuntu 18.04
 - Go environment
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/root/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build000170528=/tmp/go-build -gno-record-gcc-switches"

**Comment by sophoah** [comment]
@scraido i answered that in #2570 basically by default when you import your wallet using mnemonic there won't be any passphrase. Thanks for closing this.

**Comment by scraido** [comment]
ty mindstyle for closing it in advance, btw as i mention on another thread i'll continue to update the git issue after i take a break, so it's leave me still have 6 issue open, after i get back, i'm glad you've been administering it in advance, so ty

for the update; yeah i can define my pass with --passphrase after try to recover my wallet back,,

but when i try to used the pass for action, it's gave me this, will try it again after rest and update here and also on excel spread, ty;
![new-err](https://user-images.githubusercontent.com/44559893/77237204-b6bb2180-6bf8-11ea-92c6-0981fa426da4.png)

**Comment by scraido** [comment]
yup, i can confirm it's succeed now, ty
