### ISSUE TITLE
getting kickoff signing because my node consume much of cpu and memory that make my machines slow and fall behind

### ISSUE THREAD

**Issue by scraido** [harmony-one/harmony#2569]
**Describe the bug**
Before i got interesting graph of cpu and memory take to run the node, and then not far a long, my elected node became not elected

$ ps -aux result
root     25664 78  4.7 5000152 391460 pts/8  Sl+  05:42 164:11 ./harmony -bootnodes /ip4/54.86.xxx.xx/tcp/9867/p2p/Qmdfjtk6hPoyrH1zVD9PEH4zfWLo38dP2mDvvKXfh3xxxx,

root     28164 11.5  0.2 1153604 20132 pts/12  Sl+  06:44  28:23 tui --address=one1qcr7jj9emvz46kuj3rexuh50vfvvtlhcmfpm0r --env=local -telegramToken=xxx

**To Reproduce**
1. i just run like usually after server resetting, but now it gave me much cpu consume, coz i also using tui, so i know it, as edgar said, that's cpu and memory consume make me kickoff signing from elected to not elected

**Expected behavior**
before it couldn't take cpu% like this, the standard is below 20%

**Screenshots**
better details are on the video;
https://youtu.be/jYisNCBc9sk

**Environment (please complete the following information):**
 - OS: 18.04
 - Go environment:
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/root/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build000170528=/tmp/go-build -gno-record-gcc-switches"

**Additional context**
the --active true value doesn't gave any affect
![active-true](https://user-images.githubusercontent.com/44559893/77180283-47f89e00-6afc-11ea-890d-876c4fe0b2de.png)

**Comment by scraido** [comment]
this make me creates 3 validator;
the first is with my one address created with new chrome extension, end with "ysu" and then i try the active true above
and then i do hard reset "remove all", and activate the wallet again using mnemonic, i also have stopped the tui for "ysu" 
the second one i use my one address created when the pangaea begin again at dec 19, end with "m0r", and started the tui, it same make me delegate a while before being kicked off at the next epoch
the third i using my P1 wallet again, coz now i found how to use it again, the pass has reset to nil, so to being validator i doesn't have to input the pass, just enter, enter

**Comment by scraido** [comment]
btw as soph mention on another git report, i use contabo VPS S ssd 200GB with Intel Xeon E5-2620v3 2,4Ghz 4vCPU and 8GB of RAM

**Comment by sophoah** [comment]
ok so first of all, i think TUI cpu is not really great because it shows you only 1 cpu. try using htop and you'll see 4 different cpu and they won't be as busy as it is shown in TUI.

Lots of machine including mine are having the same issue signing at the beginning, you issue is most likely link to #2500 where dev are actively working on it. Edit validator active a few/lots of tim would usually help to bring your validator node in the committee and signing correctly.

also in the previous issue i was asking the command ```ps aux``` full result, so we can see if your memory and cpu are not being used by some OS system component or software. Your TUI video could be an aggregate of multiple software using your memory and cpu

**Comment by sophoah** [comment]
@scraido you can verify yourself eventually in ps aux and htop if you have any other processes that may be eating your memory and cpu. please just close that issue as i do think it is highly link to #2500 and hence this issue could be closed.

**Comment by mindstyle85** [comment]
i am closing thiss issue as it is because of the block signing issue that is already opened like Soph reported above.

**Comment by scraido** [comment]
thank you for your answer, yup my ps aux said the node consume 78% of cpu; 

root 25664 78 4.7 5000152 391460 pts/8 Sl+ 05:42 164:11 ./harmony -bootnodes /ip4/54.86.xxx.xx/tcp/9867/p2p/Qmdfjtk6hPoyrH1zVD9PEH4zfWLo38dP2mDvvKXfh3xxxx,

i'll try your suggestion soph to see with htop, hope it fixed sooner, because my spec is above the min, and i couldn't elected till now, ty
