### ISSUE TITLE
couldn't do self unstake, using CLI on not elected validator

### ISSUE THREAD

**Issue by scraido** [harmony-one/harmony#2571]
**Describe the bug**
Before i reported it coz my un-elected validator couldn't do unstake on issue report here;
https://github.com/harmony-one/staking-dashboard/issues/245 and then i try to do it with CLI it gaves me same problem, also after soph mention me to not use --passphrase (because i don't use passphrase for this wallet), it also not worked, even now it said i didn't have any to unstake, after i reset it issue number https://github.com/harmony-one/harmony/issues/2570

**To Reproduce**
1. you must have wallet created with new google chrome ext.
2. run the node and tui
3. stake, try to unstake from dashboard coz you get kickoff from signing
5. do unstake using CLI with or without --passphrase

**Expected behavior**
it should you can do unstake, even you put "--passphrase" there (just by press enter, enter)

**Screenshots**
here the CLI picture update, using enter, enter and without passphrase
![with-without](https://user-images.githubusercontent.com/44559893/77221640-f4c72f80-6b7d-11ea-9758-cfad2ca398e4.png)

i also do it on dashboard with no luck issue number; https://github.com/harmony-one/staking-dashboard/issues/245

**Environment (please complete the following information):**
 - OS: ubuntu 18.04
 - Go environment:
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/root/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build000170528=/tmp/go-build -gno-record-gcc-switches"

**Comment by mindstyle85** [comment]
there is a min-self delegation that needs to stay in.. and by the looks of it youre trying to unstake in full??

**Comment by scraido** [comment]
ty for replied, i have succeed undelegate it by leave a small balance as i set on the min-self delegation, i also have closed the dashboard version, i split this because soph ask me to do that, ty
