### ISSUE TITLE
Proposal: Make people couldn't see another people balances by type it on CLI

### ISSUE THREAD

**Issue by scraido** [harmony-one/harmony#2572]
**Describe the bug**
I found it for privacy that we should couldn't see another balance using CLI, coz someone can targeted another wallet that have bigger amount of balance  

**To Reproduce**
1. ./hmy balances (someone balances)

**Expected behavior**
it should something either like you didn't have the privilage or the wallet you seek is not present on server or else

**Screenshots**
./hmy balances one1km7xg8e3xjys7azp9f4xp8hkw79vm2h3f2lade (bruno marshall balances)
![brunomarshall](https://user-images.githubusercontent.com/44559893/77225935-864a9780-6ba6-11ea-9cb8-46bebdaa15e8.png)

**Comment by mindstyle85** [comment]
this is something that is available everywhere, its  the same as searching in explorer where you can see each address' balance - on all chains basically if theyre not private. Please close this one.

**Comment by sophoah** [comment]
@scraido what you are proposing here is a core functionality of all the privacy coin. It is a nice feature but not a must since harmony is not a privacy coin.

**Comment by BrunoMarshall** [comment]
Are you proposing to hide/add privacy to validator addresses? In your exemple you know that it's my adresses because you saw it in the staking explorer, are you proposing to hide it there? Knowing a balance of a address don't give you the info of the owner

**Comment by scraido** [comment]
thankyou for answer guys, i just have a conversation before on chat room (tg), that i think i found an out-breach, that after doing full remove, many not known we must set the --passphrase again, coz it not tell in cookbook, yeah people now is just do what it shown, maybe you can edit the cookbook and add the --passphrase there as there were new comer come,,

so as mindstyle and shop have been told before, that i need to add this --pass, and no one know it, and i also didn't know before, even i guess it reset to nil, so yeah i think culprit can use this to see bigger balance on ONE address, and try the luck in case they didn't use --pass,,

that's why i think it should we can hide our balance, but yeah i just realize we must also put the UTC wallet on our server by importing it, the seed is your pass, the wallet pass is the second layer, but when there do one that can configure to breach the pass, they just can try enter, enter for the second layer isn't it?

if it hide, they'll don't now which address more precious,, btw i don't see name when try that, just random see the stake amount = more reward didn't claim as a person will not claim it every hrs,,

don't miss understand it, when i think i found it, i said it first on chat group, and immediately tried it, and would update if it worked, and that not worked as i tell it first in group, before decide to post it here, all for your safety, i just thing of that, i want the network really safe, coz this is the purpose of this testnets, ty all
