### ISSUE TITLE
node.sh didnt auto update

### ISSUE THREAD

**Issue by mindstyle85** [harmony-one/harmony#2573]
**Describe the bug**
with the last rolling upgrade on OSTN, my node didnt auto upgrade, it only did so when i restarted it while testing some things.. Got confirmation from other POPS about this too.

my node.sh version:
node.sh: version: v1 20200313.0

My run command: ./node.sh -S -M -N staking -z -R localhost:6070 (-r localhost is just for pprof, should have no affect)

note that John Whitton has the same node.sh version on his sentry nodes and those did auto update

**Comment by LeoHChen** [comment]
did you remove any md5sum file or staging directory?

**Comment by LeoHChen** [comment]
also, you are not using static binary, right now, we are switch to static binary, please add `-I` option to your node.sh command line.

Please monitor the results and let me know for the next rolling upgrade. Thanks.

**Comment by mindstyle85** [comment]
Didnt remove anything.

And used dynamic since static was sigseving for me before but i just switched to static today, so will monitor this rolling upgrade and let you know/close the ticket

**Comment by LeoHChen** [comment]
please provide some update on this issue. If no problem anymore, please close it.

**Comment by Dewansahil** [comment]
@mindstyle85 please let us know if we can close this?

**Comment by mindstyle85** [comment]
@Dewansahil @LeoHChen 

im waiting for a rolling upgrade so i can verify, we only had hard restarts since, so i had no chance yet

**Comment by lijiang2087** [comment]
how about now @mindstyle85 ?

**Comment by mindstyle85** [comment]
there was another hard restart so couldnt test again, i believe today/tomorrow we should have a rolling upgrade and i will be able to verify @lijiang2087

**Comment by mindstyle85** [comment]
closing this one for now since there hasnt been a rolling upgrade for long
