### ISSUE TITLE
Signing blocks with BLS from two diffrent shards

### ISSUE THREAD

**Issue by err0r711** [harmony-one/harmony#2590]
./hmy -n https://api.s0.os.hmny.io blockchain validator information one1c9h3u72czs6sk755tjyse7x5t70m38ppnkx922
{
  "id": "0",
  "jsonrpc": "2.0",
  "result": {
    "current-epoch-performance": {
      "current-epoch-signing-percent": {
        "current-epoch-blocks-left": 0,
        "current-epoch-signed": 31,
        "current-epoch-signing-percentage": "0.815789473684210526",
        "current-epoch-to-sign": 38

   "bls-public-keys": [
        "e6791a7fd6ad130035dc16cb9a463bc6932f782d3599b7317873b76e137df0d4b23903d93655efec4067442e8f532c09", s1
        "25ba99368cce424fbe14d75ad664ad3690c09bf3d613e9f1073641ee286ff8bb583d579c41764e93fb6c3cc201029506" s2

gets kicked in second epoch

v5736-v1.3.5-45-ga817cbe9 (jenkins@ 2020-03-24T00:27:01+0000)

**Comment by mindstyle85** [comment]
so to put context to this, error edited his validator and added a s2 bls key (his original was s1 bls key, while s1 is kinda rekt).. he then restarted node.sh with just the s2 bls key and didnt remove the s1 bls key, but his signing % are kinda high for just one bls key? Unless s1 bls key isnt even registered now since s1 is rekt?

**Comment by mindstyle85** [comment]
oh and it looks like it only works for 1 epoch (the signing(, then he gets kicked out, but it shouldnt be 81%

**Comment by gupadhyaya** [comment]
@mindstyle85 we need to update `current-epoch-to-sign`, `current-epoch-signing-percentage`, etc to accommodate multi-bls. Right now it only shows per bls key until 38 (#blocks per epoch) and then increases if validator has more bls keys signing. This is also the issue why,  `current-epoch-to-sign` shows overflowed numbers. Will fix it soon.

**Comment by mindstyle85** [comment]
@gupadhyaya ah that makes sense, thanks for letting us know :)

**Comment by gupadhyaya** [comment]
@mindstyle85 investigated this further. looks like the percentage should be computed correctly even in case of multi-bls as these computations treat individual keys and aggregate the counters for all the keys associated with the validator. could you please reproduce this again and let me know? thanks.

**Comment by sophoah** [comment]
@gupadhyaya i put in discord a screenshot of that screnario that runs with no issue for me. maybe if @mindstyle85, @err0r711, @yelllowsin  still have problem, we might need to look at the vps specs. I'll check with them how they did and the difference with their setup and mine

**Comment by mindstyle85** [comment]
@sophoah this was a different issue than what you think, check the two bls keys that are attached to the validator, and there was just one node.. 

@err0r711 can you try replicate it please?

**Comment by sophoah** [comment]
@mindstyle85 yeah @err0r711 clarified that to me yesterday. At the first place, the node should not be able to run keys that belongs to different shard.

now if we try to replicate, the node won't start and tell you your keys are running into 2 different shard. I tried that 2 days ago.

if node was able to run, we have to expect that one of the 2 BLS would fail to sign and drop us from the committee since we are not satisfying the 66% valid signature

**Comment by err0r711** [comment]
"current-epoch-blocks-left": 18446744073709552000,
        "current-epoch-signed": 33,
        "current-epoch-signing-percentage": "0.500000000000000000",
        "current-epoch-to-sign": 66
      }
    },
    "currently-in-committee": true,
    "epos-status": "currently elected and signing enough blocks to be eligible for election next epoch",
    "lifetime": {
      "apr": "0.008366063404393574",
      "blocks": {
        "signed": 19134,
        "to-sign": 20130
      },
      "reward-accumulated": 2.635928445052019e+22
    },
    "metrics": {
      "by-shard": [
        {
          "bls-public-key": "e6791a7fd6ad130035dc16cb9a463bc6932f782d3599b7317873b76e137df0d4b23903d93655efec4067442e8f532c09",
          "earning-account": "one1c9h3u72czs6sk755tjyse7x5t70m38ppnkx922",
          "effective-stake": "14073225050000000000000000.000000000000000000",
          "group-percent": "0.058647369886040008",
          "overall-percent": "0.018767158363532803",
          "shard-id": 1
        },
        {
          "bls-public-key": "25ba99368cce424fbe14d75ad664ad3690c09bf3d613e9f1073641ee286ff8bb583d579c41764e93fb6c3cc201029506",
          "earning-account": "one1c9h3u72czs6sk755tjyse7x5t70m38ppnkx922",
          "effective-stake": "14073225050000000000000000.000000000000000000",
          "group-percent": "0.040554198474072589",
          "overall-percent": "0.012977343511703228",
          "shard-id": 2

all working fine now, closing this issue
