### ISSUE TITLE
[Analysis] classify the zerolog in different category for OSTN

### ISSUE THREAD

**Issue by LeoHChen** [harmony-one/harmony#2604]
# Problem/limitation At Hand

we have generated a huge amount of data in our zerolog and we'd like to do some more analysis on it.

One initial thinking is to  do some basic stats on different level of log, like "error", "warning", "debug", "info", and then zoom into the "error", we care most right now.

For error logs, they shall all start with "error" as the key in the json format. We'd further classify them into different category of errors. There could be some common pattern, some common string, we may dive deeper into very specify error messages.

Some basic stats can be collected at IP level, overall network level, timestamp, etc.
We can do some more iteration on the analysis once we have the pipeline and basic.

**Which component?**

- [ ] consensus
- [ ] deploy script
- [ ] wallet
- [ ] explorer
- [ ] node script
- [ ] test automation
- [ ] demo app
- [x] data analysis

# Proposed Solution

We will do twice or three times a day to collect the logs from nodes of OSTN and those logs will be put into a common s3 bucket. We can put them into folders based on date, so that it will easier to build pipeline and automation.

**Comment by LeoHChen** [comment]
@Daniel-VDM , we can setup a cron job in devop machine to pull the logs from OSTN and upload them to a bucket, folder structure like year/month/day.  We may also need to remove the old logs from the machine after the download/upload.

**Comment by ivorytowerdds** [comment]
@LeoHChen We have errors in four levels, do we need to get analysis on both 4 levels, or only "error" level itself? 

Here is an example of the basic analysis for level: error.  
I think the next step is to further classify and name the error. 
![image](https://user-images.githubusercontent.com/34232522/77577514-2b5dbc80-6e94-11ea-861c-ea7883a26db0.png)
![image](https://user-images.githubusercontent.com/34232522/77577519-30bb0700-6e94-11ea-8e12-ddf737aa367b.png)


Here is some basic analysis for 4 levels
![image](https://user-images.githubusercontent.com/34232522/77578137-4250de80-6e95-11ea-9a7b-d2fb47f33933.png)

![image](https://user-images.githubusercontent.com/34232522/77577708-78da2980-6e94-11ea-8a0b-bab215af1a45.png)

**Comment by LeoHChen** [comment]
very nice! error is just one level.

**Comment by LeoHChen** [comment]
the rpc error warning can be classified into one; just different IP address

**Comment by LeoHChen** [comment]
is it based on lastest log of OSTN?  how long is the period of the log? one day, or just one node?

**Comment by ivorytowerdds** [comment]
> is it based on lastest log of OSTN? how long is the period of the log? one day, or just one node?

Not latest. It's OSTN 03/19 about 3-4 hours data.  And it's for s0 leader.  Just use this as an example to write the script. 

I currently have 03/20's 21 hours' data (almost a day), I can analyze on that now. For newer data, Daniel is currently working on helping me set up the pipeline for logs. Once he finishes, we can get the newest data and longer period.

**Comment by LeoHChen** [comment]
nice, we have more data to be analyzed on a daily basis. Thanks
