### ISSUE TITLE
Shards of OSTN are out of Consensus Right After Release

### ISSUE THREAD

**Issue by AndyBoWu** [harmony-one/harmony#2607]
**Describe the bug**
Right after the latest release on OSTN, shard 1, 2 and 3 lost consensus after a short while.  Shard 1, 2, 3 are stuck at the 61st, 71st, 58th blocks, respectively. 

**Version number** 
[ec2-user@ip-172-31-93-165 ~]$ LD_LIBRARY_PATH=. ./harmony -version
Harmony (C) 2020. harmony, version v5720-v1.3.5-29-g4d282235 (ec2-user@ 2020-03-26T03:10:36+0000)

I went to the leader nodes of shard 2 and 3, and found similar patter.

Right before those shards gave up on consensus, I saw the following error log entries
`
{"level":"error","port":"9000","ip":"34.226.139.174","myEpoch":1,"myBlock":58,"myViewID":58,"phase":1,"mode":"Normal","error":"slot signer not this slot's subcommittee","caller":"/home/ec2-user/harmony/consensus/checks.go:203","time":"2020-03-26T03:27:57.247380236Z","message":"[VIEWCHANGE] VerifySenderKey Failed"}
`

**Comment by lijiang2087** [comment]
assign this to rj?

**Comment by mindstyle85** [comment]
@rlan35 can this one be closed? guessing we are already passed this with so many new releases
