### ISSUE TITLE
STN/stressnet: Consensus lost on shard 0 after multiple (25+) double-signing tests on shard 1

### ISSUE THREAD

**Issue by SebastianJ** [harmony-one/harmony#2615]
**Describe the bug**
After running multiple double-signing tests on shard 1 on STN shard 0 eventually lost consensus.

This is quite weird and concerning since shard 0 was merely used to fund validator and delegator accounts and for creating validators and sending delegations.

All double-signing activity happened on shard 1 - I don't think I even tested it once on shard 0.

**To Reproduce**
I ran this 25-30 times:
```
bash <(curl -sSL https://raw.githubusercontent.com/SebastianJ/harmony-tools/master/double-signing/setup.sh) --network stress --shard 1 --address ADDRESS_WITH_FUNDS
```

**Expected behavior**
Shard 0 shouldn't lose consensus.

**Additional info**
Adding this for the sake of reference:
`{"level":"error","port":"9000","ip":"xxx.xxx.xxx.xxx","error":"cannot finalize block: [ComputeAndMutateEPOSStatus] failed update validator info: have 9800000000000000000000 want 10000000000000000000000: self delegation can not be less than min_self_delegation","caller":"/home/ec2-user/harmony/node/node_newblock.go:78","time":"2020-03-28T06:04:59.350967974Z","message":"!!!!!!!!!Failed Proposing New Block!!!!!!!!!"}
`

The issue seems to be that the validator gets slashed and that its self-stake/self-delegated tokens goes below 10k as a consequence. The validator has a balance of 9800 after getting slashed which is below the minimum required self delegation limit of 10000, which eventually leads to blocks not being able to be proposed properly.

**Comment by sophoah** [comment]
@SebastianJ the slash is done towards the same validator right ? so there should still be enough node to participate into consensus, or do i miss anything ?

**Comment by SebastianJ** [comment]
@sophoah the issue seems to be that the protocol can't deal with the fact that one or several validators have their self-stake set lower than the minimum required self-delegation (because they got slashed).

Because of that bug, it seems that new blocks can't be proposed because the node can't figure out the correct state for the validators participating in the committee.

**Comment by sophoah** [comment]
Ok technically the min-self-delegation shouldn't be taking into consideration during EPOS or consensus and only used during the validator creation.

**Comment by JB273** [comment]
@SebastianJ @sophoah  If the validator falls below min-self-delegation due to slashing, is this going to be solved by messaging a validator so one can make the validator compliant to the rules of EpOS? So if slashing sets your self-stake below the 10000, the validator self should first refill at least until the minimum value before able to participate again in committee selection!?

**Comment by sophoah** [comment]
@JB273 the min-self-delegation measure of 10k is just to avoid spams. Once it is created, and even if it goes to 0, for me it shouldn't be an issue. Remember we talked about having 1 ONE symbolic for the validator and delegate all our one token to it ? 

being below the min-self-delegation shouldn't bring prevent the epos election. EPOS election should only depends on the total-stake you have (your-self-delegation and all the delegation). Slashing currently applies to the entire total-delegation)

**Comment by SebastianJ** [comment]
Looks like it's solved 🎉
