### ISSUE TITLE
wrong error message for trying to undelegate fully from your validator

### ISSUE THREAD

**Issue by scraido** [harmony-one/harmony#2620]
**Describe the bug**

EDITED by mindstyle: this user tried to undelegate his full amount from his validator, which ofcourse isnt working as there is a min-self delegation that cannot be undelegated.

**Expected behavior**
it should when you can't do unstake the message is related to why you couldn't do it if you have balance staked, instead of show that you didn't have the balance that you own and want to unstake

**Screenshots**
here the CLI picture update, using enter, enter and without passphrase
![with-without](https://user-images.githubusercontent.com/44559893/77221640-f4c72f80-6b7d-11ea-9758-cfad2ca398e4.png)

but dashboard still show it;
![dashboardshow](https://user-images.githubusercontent.com/44559893/77221707-bbdb8a80-6b7e-11ea-8a74-0498ccc829d7.png)

**Additional context**
This really a serious issue, how if that happen to your 10mm? when you try to undelegate using CLI, it show messages; have 0 want 1xxxx, it's can make heart attack, how to report if this happen on mainnet, lucky on my case we still used testnet token and also on dashboard it still show the messages

thankyou

**Comment by mindstyle85** [comment]
@janet-harmony can we close this one? seems that with the newer versions, validators are able to undelegate fully anyways?

**Comment by janet-harmony** [comment]
Confirmed that full undelegation works on latest OSTN version.
