### ISSUE TITLE
Change block signing logic to include view ID in the signed content

### ISSUE THREAD

**Issue by rlan35** [harmony-one/harmony#2630]
Previously, the consensus signatures are signed on blockHeight+blockHash.

We need to include also viewID in the signed data, which is required by the new slashing logic.

Search for "signature on hash+blockNum+viewID (add a hard fork)" in the code base and find all the places where viewID needs to be added into the signature.

Need to add the new logic as a fork at staking epoch.

**Comment by fxfactorial** [comment]
@Daniel-VDM this will be a big PR, lots of work here
