### ISSUE TITLE
STN/Stressnet: double-signing leads to corrupt blocks: BAD BLOCK / invalid merkle root

### ISSUE THREAD

**Issue by SebastianJ** [harmony-one/harmony#2632]
**Describe the bug**
I ran a set of double-signing tests on shard 0 on a freshly restarted STN network (commit: https://github.com/harmony-one/harmony/commit/74a5eda7)

Somehow after triggering double-signing using a shard 0 validator no newly joined nodes can sync past a given block that has ended up getting corrupted:

`
{"level":"error","port":"9000","ip":"xxx.xxx.xxx.xxx","caller":"/home/deploy/go/src/github.com/SebastianJ/harmony/core/blockchain.go:1530","time":"2020-03-30T12:26:26.799088982+02:00","message":"\n########## BAD BLOCK #########\nChain config: {ChainID: 5 EIP155: 0 CrossTx: 0 Staking: 2 CrossLink: 2 ReceiptLog: 0}\n\nNumber: 9620\nEpoch: 253\nNumTxn: 0\nNumStkTxn: 0\nHash: 0xa0596aa1431a9452cb590454980f14f9ad9d0a5397fa51d14b340fc14716dc12\n\n\nError: invalid merkle root (remote: e0f7d104850897ef6dd94f4ab6f454f5aa97d37ad4e12c9d4e9534265fbdfe5e local: 189142edb1f6b052d302072c14c74fbbb9ba540e9119885edb51f873a62c9374, rlp dump f9032187486d6e79546764827633f90313a0c932362096b4bb2ec33871bd981c77d8758fb61a8e9f95d7e1dddafebbb5ee1d943f6e680ec5456f540a833e77df4c8ed20a20f274a0e0f7d104850897ef6dd94f4ab6f454f5aa97d37ad4e12c9d4e9534265fbdfe5ea056e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421a056e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421a056e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421a056e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421b90100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000008225948404c4b40080845e81b97180a0000000000000000000000000000000000000000000000000000000000000000082259481fd80b8602e2252c1dfbe65b08449296ae21e18b06a00faaa0366336e95c11082d9e1e3213c601595ae8e41b106d6d45060d6de0359af9eff4f7cba615ec510903d04ff7285ee81f3eed269b9848e63e49f712ae64bd1d01d53e7fed722bda142a2a3630a84ffffff3f808080b892f890f88ea0c60a713f2085037384cdd6b919eaf66dc612336a021bb3fbd11a265cd6fbddaf82258fb86050492f8cb1a4c2d76a7c6577ed003f4901060001f061a277beb5347448ac7511ab1e5af7d4ff590ba2b3cb9375792e00ec1c93c200cdfd2b0b9701a037a1068e357c78ec00a333d7c74ee9899e7bb842006cba3db74f9d5d32d82c111a62609184ffffff7f0181fd80)\n##############################\n"}
`

`
{"level":"error","port":"9000","ip":"xxx.xxx.xxx.xxx","error":"invalid merkle root (remote: e0f7d104850897ef6dd94f4ab6f454f5aa97d37ad4e12c9d4e9534265fbdfe5e local: 189142edb1f6b052d302072c14c74fbbb9ba540e9119885edb51f873a62c9374, rlp dump f9032187486d6e79546764827633f90313a0c932362096b4bb2ec33871bd981c77d8758fb61a8e9f95d7e1dddafebbb5ee1d943f6e680ec5456f540a833e77df4c8ed20a20f274a0e0f7d104850897ef6dd94f4ab6f454f5aa97d37ad4e12c9d4e9534265fbdfe5ea056e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421a056e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421a056e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421a056e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421b90100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000008225948404c4b40080845e81b97180a0000000000000000000000000000000000000000000000000000000000000000082259481fd80b8602e2252c1dfbe65b08449296ae21e18b06a00faaa0366336e95c11082d9e1e3213c601595ae8e41b106d6d45060d6de0359af9eff4f7cba615ec510903d04ff7285ee81f3eed269b9848e63e49f712ae64bd1d01d53e7fed722bda142a2a3630a84ffffff3f808080b892f890f88ea0c60a713f2085037384cdd6b919eaf66dc612336a021bb3fbd11a265cd6fbddaf82258fb86050492f8cb1a4c2d76a7c6577ed003f4901060001f061a277beb5347448ac7511ab1e5af7d4ff590ba2b3cb9375792e00ec1c93c200cdfd2b0b9701a037a1068e357c78ec00a333d7c74ee9899e7bb842006cba3db74f9d5d32d82c111a62609184ffffff7f0181fd80)","caller":"/home/deploy/go/src/github.com/SebastianJ/harmony/api/service/syncing/syncing.go:577","time":"2020-03-30T12:26:26.79927846+02:00","message":"[SYNC] UpdateBlockAndStatus: Error adding new block to blockchain 9620 0"}
`

`
{"level":"debug","port":"9000","ip":"xxx.xxx.xxx.xxx","block":{"ReceivedAt":"0001-01-01T00:00:00Z","ReceivedFrom":null},"caller":"/home/deploy/go/src/github.com/SebastianJ/harmony/api/service/syncing/syncing.go:585","time":"2020-03-30T12:26:26.799480328+02:00","message":"[SYNC] UpdateBlockAndStatus: Rolling back current block!"}
`

`{"level":"error","port":"9000","ip":"xxx.xxx.xxx.xxx","error":"invalid merkle root (remote: e0f7d104850897ef6dd94f4ab6f454f5aa97d37ad4e12c9d4e9534265fbdfe5e local: 189142edb1f6b052d302072c14c74fbbb9ba540e9119885edb51f873a62c9374, rlp dump f9032187486d6e79546764827633f90313a0c932362096b4bb2ec33871bd981c77d8758fb61a8e9f95d7e1dddafebbb5ee1d943f6e680ec5456f540a833e77df4c8ed20a20f274a0e0f7d104850897ef6dd94f4ab6f454f5aa97d37ad4e12c9d4e9534265fbdfe5ea056e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421a056e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421a056e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421a056e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421b90100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000008225948404c4b40080845e81b97180a0000000000000000000000000000000000000000000000000000000000000000082259481fd80b8602e2252c1dfbe65b08449296ae21e18b06a00faaa0366336e95c11082d9e1e3213c601595ae8e41b106d6d45060d6de0359af9eff4f7cba615ec510903d04ff7285ee81f3eed269b9848e63e49f712ae64bd1d01d53e7fed722bda142a2a3630a84ffffff3f808080b892f890f88ea0c60a713f2085037384cdd6b919eaf66dc612336a021bb3fbd11a265cd6fbddaf82258fb86050492f8cb1a4c2d76a7c6577ed003f4901060001f061a277beb5347448ac7511ab1e5af7d4ff590ba2b3cb9375792e00ec1c93c200cdfd2b0b9701a037a1068e357c78ec00a333d7c74ee9899e7bb842006cba3db74f9d5d32d82c111a62609184ffffff7f0181fd80)","caller":"/home/deploy/go/src/github.com/SebastianJ/harmony/api/service/syncing/syncing.go:801","time":"2020-03-30T12:26:26.799792287+02:00","message":"[SYNC] ProcessStateSync failed (isBeacon: false, ShardID: 0, otherHeight: 10126, currentHeight: 9618)"}
`

Here's a screenshot from a node/double-signing test that I left for an hour trying to get past block 9618:
![block 9618](https://i.imgur.com/dAz99e9.png)

So the internal nodes that had already made it past 9618 could continue to sync and consensus could stay intact - but any new node would just get stuck on 9618 and could never get past it.

I tested on three separate VPS:es and all of the nodes got stuck on `########## BAD BLOCK #########`

**To Reproduce**
On Ubuntu/Debian:
`bash <(curl -sSL https://raw.githubusercontent.com/SebastianJ/harmony-tools/master/double-signing/setup.sh) --network stress --shard 0 --address ADDRESS_WITH_FUNDS`

**Comment by fxfactorial** [comment]
This might not be issue since latest stress net commit which fixed other consensus issue as well

**Comment by rlan35** [comment]
yea, likely a non-issue but an incompatible binary thing. @SebastianJ can you confirm that the new node's binary is the same as the nodes in consensus?

**Comment by SebastianJ** [comment]
Yeah, was a binary mismatch - closing.
