### ISSUE TITLE
Can't check validator information for the local test network

### ISSUE THREAD

**Issue by Road00** [harmony-one/harmony#2634]
**Describe the bug**
Can't check validator information for the local test network

`
root@8069ce907413:~/go/src/github.com/harmony-one/harmony# hmy blockchain validator  all
{
  "id": "0",
  "jsonrpc": "2.0",
  "result": []
`

**To Reproduce**
1. Run localnet based on the docker image
2. Wait for staking epoch

**Comment by rlan35** [comment]
@Road00 did you create any validator in the local net? If not, then the empty result is expected.

**Comment by fxfactorial** [comment]
The docker image doesn't create a validator for you, you are to make one. 

this is Open Staking test network right now. 
```
hmy -n https://api.s0.os.hmny.io  blockchain validator all 
```

...so the docker image is more for development. To run a node, see this documentation: 
https://docs.harmony.one/home/validators/first-time-setup/running-a-node

(Soon I will make a docker image so easy to just run a node on OSTN without using node.sh as in docs)
