### ISSUE TITLE
is bls generation random? i just got shard 2, 4 times in a row

### ISSUE THREAD

**Issue by lijiang2087** [harmony-one/harmony#2637]
[ec2-user@ip-172-31-17-98 ~]$ ./hmy keys generate-bls-key --passphrase
Enter passphrase:
Repeat the passphrase:

{
  "public-key": "115c71debb8883a737057d812e9e32986b495781467458e2d5bf6dea966f574c6bed4ae4f1f5988f925e92cd6d9c1002",
  "private-key": "358607410289b6de2d188db4d3b27a4045b5901287692afaeb24133ba5777d70",
  "encrypted-private-key-path": "/home/ec2-user/115c71debb8883a737057d812e9e32986b495781467458e2d5bf6dea966f574c6bed4ae4f1f5988f925e92cd6d9c1002.key"
}
[ec2-user@ip-172-31-17-98 ~]$ ./hmy --node="https://api.s0.os.hmny.io" utility shard-for-bls 115c71debb8883a737057d812e9e32986b495781467458e2d5bf6dea966f574c6bed4ae4f1f5988f925e92cd6d9c1002
{"shard-id":2}
[ec2-user@ip-172-31-17-98 ~]$ ./hmy keys generate-bls-key --passphrase
Enter passphrase:
Repeat the passphrase:

{
  "public-key": "5c66bb31ddeca342d1e3f06efd3f6c69f11387546248e46a22f43108bd934399e66e7c09533f67d8bb80f9aab6539418",
  "private-key": "37fa9b8a1271b0537a39b53cb5efd7f12dfda5b9a0367cb06c10b1495592050a",
  "encrypted-private-key-path": "/home/ec2-user/5c66bb31ddeca342d1e3f06efd3f6c69f11387546248e46a22f43108bd934399e66e7c09533f67d8bb80f9aab6539418.key"
}
[ec2-user@ip-172-31-17-98 ~]$ ./hmy --node="https://api.s0.os.hmny.io" utility shard-for-bls 115c71debb8883a737057d812e9e32986b495781467458e2d5bf6dea966f574c6bed4ae4f1f5988f925e92cd6d9c1002
{"shard-id":2}
[ec2-user@ip-172-31-17-98 ~]$ ./hmy keys generate-bls-key --passphrase
Enter passphrase:
Repeat the passphrase:

{
  "public-key": "3cdde445c84ea2773b89c9974cbe12fe442fa6752dcfa74906b5e9f28eae2e237b8f7f12c7a9beebc7e1a0abdabe0507",
  "private-key": "1db3cf5742150d6235b31380288338f83785384461bd7ad606160e09fdd6c46b",
  "encrypted-private-key-path": "/home/ec2-user/3cdde445c84ea2773b89c9974cbe12fe442fa6752dcfa74906b5e9f28eae2e237b8f7f12c7a9beebc7e1a0abdabe0507.key"
}
[ec2-user@ip-172-31-17-98 ~]$ ./hmy --node="https://api.s0.os.hmny.io" utility shard-for-bls 115c71debb8883a737057d812e9e32986b495781467458e2d5bf6dea966f574c6bed4ae4f1f5988f925e92cd6d9c1002
{"shard-id":2}
[ec2-user@ip-172-31-17-98 ~]$ ./hmy keys generate-bls-key --passphrase
Enter passphrase:
Repeat the passphrase:

{
  "public-key": "5811ea5053216e7b402d54e0d603438882e43272a0f34260d66232a1ba558fb0663e5a8e5170495a6a81aff104f5ce96",
  "private-key": "fd7672cc0a0122944e59a250db563e01a66e686fc1c7e5dc6f1876afab7f0051",
  "encrypted-private-key-path": "/home/ec2-user/5811ea5053216e7b402d54e0d603438882e43272a0f34260d66232a1ba558fb0663e5a8e5170495a6a81aff104f5ce96.key"
}
[ec2-user@ip-172-31-17-98 ~]$ ./hmy --node="https://api.s0.os.hmny.io" utility shard-for-bls 115c71debb8883a737057d812e9e32986b495781467458e2d5bf6dea966f574c6bed4ae4f1f5988f925e92cd6d9c1002
{"shard-id":2}

**Comment by gupadhyaya** [comment]
bls key generation is random, but key to shard assignment is less random as it is based on simple modulus.

**Comment by fxfactorial** [comment]
exactly. key to shard is not random but the key itself is. 

Also `hmy` is from `go-sdk` so methinks better to open issues there for `hmy`
