### ISSUE TITLE
TXs not working on OSTN

### ISSUE THREAD

**Issue by mindstyle85** [harmony-one/harmony#2651]
**Describe the bug**

Looks like regular transactions dont work correctly on OSTN now (looks like tx is attempted to send out but in the end it is not, just tx fee is taken):

1. this is the address ive sent to (balance is 10k for the receiver): https://explorer.os.hmny.io/#/address/one1cnemlekm45ur3e5vc55xacf3xgs8gay8d0fcmg

2. this is the tx i did (balance is 30M for the sender): https://explorer.os.hmny.io/#/tx/0x2db5079a95fc7449213ca434886f13986ee2b9a36f84ba3a5e91e4e36ff888c4

3. tx status:
./hmy --node="https://api.s0.os.hmny.io" transfer --from one1675d7adqu9egn0ehd9fx4f6jmdjfynw3gkr48q --to one1cnemlekm45ur3e5vc55xacf3xgs8gay8d0fcmg --from-shard 0 --to-shard 0 --amount 888888
{
  "transaction-hash": "0x2db5079a95fc7449213ca434886f13986ee2b9a36f84ba3a5e91e4e36ff888c4",
  "blockchain-receipt": {
    "blockHash": "0xa046130f1f80c144bf7cbb8564738949376cf71614fb6bdc179896ef7b6a37cc",
    "blockNumber": "0x297c",
    "contractAddress": null,
    "cumulativeGasUsed": "0x5208",
    "from": "one1675d7adqu9egn0ehd9fx4f6jmdjfynw3gkr48q",
    "gasUsed": "0x5208",
    "logs": [],
    "logsBloom": "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
    "shardID": 0,
    "status": "0x0",
    "to": "one1cnemlekm45ur3e5vc55xacf3xgs8gay8d0fcmg",
    "transactionHash": "0x2db5079a95fc7449213ca434886f13986ee2b9a36f84ba3a5e91e4e36ff888c4",
    "transactionIndex": "0x0"
  },
  "time-signed-utc": "2020-03-31 18:30:44.517263"
}

4. balance on my address (initial was 30M):
./hmy balances one1675d7adqu9egn0ehd9fx4f6jmdjfynw3gkr48q --node="https://api.s0.os.hmny.io"
[
  {
    "shard": 0,
    "amount": 29999999.999979000000000000
  },
  {
    "shard": 1,
    "amount": 0.000000000000000000
  },
  {
    "shard": 2,
    "amount": 0.000000000000000000
  },
  {
    "shard": 3,
    "amount": 0.000000000000000000
  }
]

**Comment by mindstyle85** [comment]
this one works though, sent it to one of my own addresses:
https://explorer.os.hmny.io/#/tx/0x8f049c5ad5b366e22af4a01fa67ee572f73841453c56253ce9a79701a549cf1d

is there a chance theres something wrong with that address we were sending to? that one called the faucet for funds and got them, then there were 3 attempts to send funds to it and all didnt arrive but are visible in tx history (the 100k transfer, the 999 transfer and my 888888 transfer)

**Comment by mindstyle85** [comment]
so just  to update, even though Daniel already knows, the one1cnemlekm45ur3e5vc55xacf3xgs8gay8d0fcmg address seems to be running a smart contract (supposedly faucet), and it rejects all transactions to it (except when he used the real faucet)

**Comment by mindstyle85** [comment]
update: so smart contract addresses want more gas, thats why the transactions failed because default gas isnt enough.

Daniel will check into a way to find out if an address is running a smart contract (and possibly return an error message for these kind of txs)

**Comment by Daniel-VDM** [comment]
With a bumped gas limit and gas price I was able to send a transaction and have it reflected on the addr. https://explorer.os.hmny.io/#/tx/0x13e2bbb263b20092b2d08dc0177c4423cc073429a10d1488a951bcc9260a99d0
