### ISSUE TITLE
panic while sync the block with binary release

### ISSUE THREAD

**Issue by songgeng87** [harmony-one/harmony#2662]
**Describe the bug**
panic while sync the block 

the release version is:
Harmony (C) 2019. harmony, version v5036-v1.2.4-2-gd116332a (jenkins@ 2020-02-25T04:39:57+0000)

start the node with supervisor:
harmony -bootnodes /ip4/100.26.90.187/tcp/9874/p2p/Qmdfjtk6hPoyrH1zVD9PEH4zfWLo38dP2mDvvKXfh3tnEv,/ip4/54.213.43.194/tcp/9874/p2p/QmZJJx6AdaoEkGLrYG4JeLCKeCKDjnFz2wfHNHxAqFSGA9,/ip4/13.113.101.219/tcp/12019/p2p/QmQayinFSgMMw5cSpDUiD9pQ2WeP6WNmGxpZ6ou3mdVFJX,/ip4/99.81.170.167/tcp/12019/p2p/QmRVbTpEYup8dSaURZfF6ByrMTSKa4UyUzJhSjahFzRqNj -ip 127.0.0.1 -port 9000 -is_genesis -network_type=mainnet -dns_zone=t.hmny.io -blacklist=/hbdata/one/shard-0/blacklist.txt -is_archival=true -db_dir /hbdata/one/shard-0/data -keystore /hbdata/one/shard-0/keystore -log_folder /hbdata/one/shard-0/logs -shard_id 0 -node_type=explorer

the error message:
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xc247f8]

goroutine 615 [running]:
github.com/ethereum/go-ethereum/ethdb.(*LDBDatabase).NewBatch(...)
        /var/lib/jenkins/go/pkg/mod/github.com/ethereum/go-ethereum@v1.8.27/ethdb/database.go:352
github.com/harmony-one/harmony/api/service/explorer.(*Storage).Dump(0xc0003ac1f8, 0xc001b6a460, 0x2bcf11)
        /mnt/jenkins/workspace/harmony-release/harmony/api/service/explorer/storage.go:97 +0x98
github.com/harmony-one/harmony/node.(*Node).commitBlockForExplorer(0xc00038e400, 0xc001b6a460)
        /mnt/jenkins/workspace/harmony-release/harmony/node/node_explorer.go:140 +0x135
github.com/harmony-one/harmony/node.(*Node).ExplorerMessageHandler(0xc00038e400, 0xc0016fc2c6, 0x148, 0x15a)
        /mnt/jenkins/workspace/harmony-release/harmony/node/node_explorer.go:81 +0x789
github.com/harmony-one/harmony/node.(*Node).HandleMessage(0xc00038e400, 0xc0016fc2c5, 0x149, 0x15b, 0xc0088cd830, 0x22)
        /mnt/jenkins/workspace/harmony-release/harmony/node/node_handler.go:97 +0x117
github.com/harmony-one/harmony/msgq.(*Queue).HandleMessages(0xc00018a7e0, 0x16ac620, 0xc00038e400)
        /mnt/jenkins/workspace/harmony-release/harmony/msgq/msgq.go:52 +0xda
created by github.com/harmony-one/harmony/node.(*Node).startRxPipeline
        /mnt/jenkins/workspace/harmony-release/harmony/node/node.go:409 +0x62

**Environment (please complete the following information):**
 - OS: Ubuntu 16.04.5 LTS

**Comment by mindstyle85** [comment]
this is a very very old version, closing
