### ISSUE TITLE
[Feature] create validator name and identity 

### ISSUE THREAD

**Issue by mindstyle85** [harmony-one/harmony#2665]
# Problem/limitation At Hand

I was thinking about the current validator creation system (i have not checked other networks yet) but since name and identity fields arent unique, we could have random validators trying to fake/impersonate a staking pool, binance etc.. (logos are also on the internet so not hard to fetch those too).

# Proposed Solution

Make name and identity unique, although that doesnt fully solve the problem.

# Alternatives Considered

any possible way to "verify" each validator somehow?

**Comment by fxfactorial** [comment]
Not really. Only way to be really verified is cryptographically.

**Comment by sophoah** [comment]
what about the validator one account ? that should be unique right ?

**Comment by mindstyle85** [comment]
> Not really. Only way to be really verified is cryptographically.

yeah, just not sure how others solve this.. because theres already a problem if someone registers a validator with say Binance or Sesameseed name first, basically stealing their most general name.. 

@sophoah yes one address is unique but only with that you cant verify if binance is really binance

**Comment by fxfactorial** [comment]
When validator creates their BLS keys, they have to validate with a verification of a signing. So maybe the validator (on their website) provides some signed value by the BLS key and we also expose what they signed on initial entry. This way could verify validator really is associated with those BLS keys

**Comment by fxfactorial** [comment]
@gupadhyaya what do you think?

**Comment by mindstyle85** [comment]
> When validator creates their BLS keys, they have to validate with a verification of a signing. So maybe the validator (on their website) provides some signed value by the BLS key and we also expose what they signed on initial entry. This way could verify validator really is associated with those BLS keys

i like it, only thing that might be a problem is the website - not sure every validator will have it, unless we only care about staking service providers which would make sense.. otherwise maybe we can do the verification list directly on harmony website?

**Comment by Chainode** [comment]
I also don't think everyone will have a website. I think one possible solution is to verify identity with keybase. There is actually a proposal to use keybase for validator logo. This could also be an unique identifier for the identity, so 2 rabbits in one shot:
https://github.com/harmony-one/staking-dashboard/issues/212 

Keybase is something which is used by Cosmos(Tendermint chains) and Solana to identify validators: 
https://github.com/solana-labs/solana/issues/5187

**Comment by sophoah** [comment]
@mindstyle85 with the latest update, at least the identity has to be unique, not entirely what was requested but we are getting there, should we close that :)
