### ISSUE TITLE
always prompts me to type in my passphrase

### ISSUE THREAD

**Issue by MaggieWang-Harmony** [harmony-one/harmony#2677]
![image](https://user-images.githubusercontent.com/55899206/78196583-b6602900-7437-11ea-82fa-9b4ff9f95c67.png)

When I attempt to run a node, it always prompts me to type in my passphrase. After I do so, it always leads to authentication failed. So I must create a new BLS key, which always leads to this

The tool appears to be buggy. I also suggest they implement some automated error collection mechanisms, so I don't have to report these findings to you. Instead, the program should collect user information and contact details, and they should reach out to the user when the bug is fixed, or if additional information is required

So I looked at the source code of your command line tools at https://github.com/harmony-one/go-sdk/blob/master/cmd/subcommands/root.go and traced the chain of functions which the error was originated, It is because hmy requires an active local node `an active local node is not possible to be established, because of the authentication error as shown in earlier discussions`

![image](https://user-images.githubusercontent.com/55899206/78199311-2bcff780-7440-11ea-875a-fbb8ffe723ce.png)
he has an ancient version of the node running locally
It means you had a node running on port 9500
Because that http resp can only come from the harmony node binary which one way to explain why it didn’t have that method is that it’s ancient

The response to the prompt "Remove old database/logs? (Y/n)" is messing up the passphrase
Make it a command-line flag instead?

**Comment by fxfactorial** [comment]
There is lots of implied context here but I think @janet-harmony knows enough and what to fix about that `remove old` database/logs?` thing
