### ISSUE TITLE
ERROR when loading bls key, err :cipher: message authentication failed

### ISSUE THREAD

**Issue by yelllowsin** [harmony-one/harmony#2689]
Currently, node.sh is not loading correctly when using BLS keys with passphrases. It is throwing the error bellow when i input the passphrase, though i double checked and it is correct.

```
./node.sh -S -N staking -z -I -c -k 7de69afe9c8f1c39cd245396b3f9a6402d423a2dadd404c340399f866bc488855b01deb62072e0f615fe2f5c3ff88500.key
node.sh: using manually specified BLS key file: 7de69afe9c8f1c39cd245396b3f9a6402d423a2dadd404c340399f866bc488855b01deb62072e0f615fe2f5c3ff88500.key
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   799  100   799    0     0   2201      0 --:--:-- --:--:-- --:--:--  2201
node.sh: binaries did not change
node.sh: public IP address autodetected: 13.85.9.199
node.sh: cleaning up old database/logs (-c)
Remove old database/logs? (Y/n)
Enter passphrase for the BLS key file 7de69afe9c8f1c39cd245396b3f9a6402d423a2dadd404c340399f866bc488855b01deb62072e0f615fe2f5c3ff88500.key:
node.sh: ############### Running Harmony Process ###############
ERROR when loading bls key, err :cipher: message authentication failed
node.sh: node process finished with status 100
node.sh: restarting in 10s...
```

If i copy the same BLS key to .hmy/blskeys and create a corresponding .pass file, it loads correctly using -M. So the issue is when using -k and prompting the passphrase via terminal.

I am using the latest versions of `hmy` and `node.sh` on OSTN:

```
./hmy version
Harmony (C) 2020. hmy, version v352-eaa4d2a (root@harmony.one 2020-04-01T22:40:56+0000)

./node.sh -V
Harmony (C) 2020. harmony, version v5783-v1.3.5-92-g888c10ac (jenkins@ 2020-04-02T21:08:18+0000)

```

**Comment by janet-harmony** [comment]
@coolcottontail 
Can you take a look at this?
It broke after your AWS encrypted BLS key file change (a6929dd3).

**Comment by coolcottontail** [comment]
something is wrong with node.sh itself. the blspass file is not passed in to run harmony: 

./node.sh -S -N staking -z -I -c -k dc7f3e48e5a43254e5c76c16751533fd2e205c65183905eae4fde7b84f9196aeae868cb70add4dfb282a51dbadbdcb80.key
node.sh: using manually specified BLS key file: dc7f3e48e5a43254e5c76c16751533fd2e205c65183905eae4fde7b84f9196aeae868cb70add4dfb282a51dbadbdcb80.key
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   799  100   799    0     0   4672      0 --:--:-- --:--:-- --:--:-- 15365
node.sh: binaries did not change
node.sh: public IP address autodetected: 18.191.150.124
node.sh: cleaning up old database/logs (-c)
Remove old database/logs? (Y/n) y

Enter passphrase for the BLS key file dc7f3e48e5a43254e5c76c16751533fd2e205c65183905eae4fde7b84f9196aeae868cb70add4dfb282a51dbadbdcb80.key: 
node.sh: ############### Running Harmony Process ###############
./harmony -bootnodes /ip4/54.86.126.90/tcp/9867/p2p/Qmdfjtk6hPoyrH1zVD9PEH4zfWLo38dP2mDvvKXfh3tnEv,/ip4/52.40.84.2/tcp/9867/p2p/QmbPVwrqWsTYXq1RxGWcxx9SWaTUCfoo1wA6wmdbduWe29 -ip 18.191.150.124 -port 9000 -is_genesis -network_type=pangaea -dns_zone=os.hmny.io -blacklist=./.hmy/blacklist.txt -is_archival=false -blskey_file dc7f3e48e5a43254e5c76c16751533fd2e205c65183905eae4fde7b84f9196aeae868cb70add4dfb282a51dbadbdcb80.key -shard_id=-1 -staking=true -blspass stdin

**Comment by coolcottontail** [comment]
if you create a password file and run it with -p option for node.sh , then it will run

 ./node.sh -S -N staking -z -I -c -k dc7f3e48e5a43254e5c76c16751533fd2e205c65183905eae4fde7b84f9196aeae868cb70add4dfb282a51dbadbdcb80.key -p mypass.txt
node.sh: using manually specified BLS key file: dc7f3e48e5a43254e5c76c16751533fd2e205c65183905eae4fde7b84f9196aeae868cb70add4dfb282a51dbadbdcb80.key
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   799  100   799    0     0   5748      0 --:--:-- --:--:-- --:--:--  5748
node.sh: binaries did not change
9000/tcp:            22502
node.sh: public IP address autodetected: 18.191.150.124
node.sh: cleaning up old database/logs (-c)
Remove old database/logs? (Y/n) y

node.sh: ############### Running Harmony Process ###############
./harmony -bootnodes /ip4/54.86.126.90/tcp/9867/p2p/Qmdfjtk6hPoyrH1zVD9PEH4zfWLo38dP2mDvvKXfh3tnEv,/ip4/52.40.84.2/tcp/9867/p2p/QmbPVwrqWsTYXq1RxGWcxx9SWaTUCfoo1wA6wmdbduWe29 -ip 18.191.150.124 -port 9000 -is_genesis -network_type=pangaea -dns_zone=os.hmny.io -blacklist=./.hmy/blacklist.txt -is_archival=false -blskey_file dc7f3e48e5a43254e5c76c16751533fd2e205c65183905eae4fde7b84f9196aeae868cb70add4dfb282a51dbadbdcb80.key -shard_id=-1 -staking=true -blspass file:mypass.txt
Staking mode; node key dc7f3e48e5a43254e5c76c16751533fd2e205c65183905eae4fde7b84f9196aeae868cb70add4dfb282a51dbadbdcb80 -> shard 0

**Comment by coolcottontail** [comment]
added fix for this issue in https://github.com/harmony-one/harmony/pull/2695
