### ISSUE TITLE
validator informations shows very outdated effective stake

### ISSUE THREAD

**Issue by mindstyle85** [harmony-one/harmony#2697]
**Describe the bug**
 so with what @gupadhyaya was saying i re-tested upper bound stake and that is correct now via median-stake query. However when using validator information query, the effective stake does not change at all. My belief is that the effective stake displayed here is the one from when the validator got first elected.

I think this design is wrong and the validator information should also show current effective stake that belongs to current epoch (median).

My tests:
I checked validator information with median stake 150k, 158k and 252k, each time the result is the same (115k on a 4,7M stake validator - upper bound)

./hmy blockchain validator information one1syx0rmtttr8jehlxvnkpyx4hvrlevmcx3tcghy --node="https://api.s0.os.hmny.io"
{
  "id": "0",
  "jsonrpc": "2.0",
  "result": {
    "current-epoch-performance": {
      "current-epoch-signing-percent": {
        "current-epoch-signed": 18,
        "current-epoch-signing-percentage": "1.000000000000000000",
        "current-epoch-to-sign": 18,
        "num-beacon-blocks-until-next-epoch": 21
      }
    },
    "currently-in-committee": true,
    "epos-status": "currently elected",
    "lifetime": {
      "apr": "0.000000000000000000",
      "blocks": {
        "signed": 7235,
        "to-sign": 7235
      },
      "reward-accumulated": 8.681017440825588e+21
    },
    "metrics": {
      "by-bls-key": [
        {
          "earned-reward": 8.679516275324422e+21,
          "key": {
            "bls-public-key": "02760cadc6ef3d3c1f8b66adbe182ebc252b451178efc168e856870311c8a7005c7060d28ea72c6c7adfab606989f413",
            "earning-account": "one1syx0rmtttr8jehlxvnkpyx4hvrlevmcx3tcghy",
            **"effective-stake": "115000000000000000000000.000000000000000000",**
            "group-percent": "0.053559547571523619",
            "overall-percent": "0.017139055222887558",
            "shard-id": 3
          }
        }
      ],
      "total-effective-stake": "115000000000000000000000.000000000000000000"
    },
    "total-delegation": 4.701e+24,
    "validator": {
      "address": "one1syx0rmtttr8jehlxvnkpyx4hvrlevmcx3tcghy",
      "bls-public-keys": [
        "02760cadc6ef3d3c1f8b66adbe182ebc252b451178efc168e856870311c8a7005c7060d28ea72c6c7adfab606989f413"
      ],
      "creation-height": 1192,
      "delegations": [
        {
          "amount": 4.7e+24,
          "delegator-address": "one1syx0rmtttr8jehlxvnkpyx4hvrlevmcx3tcghy",
          "reward": 8.679702001621614e+21,
          "undelegations": []
        },
        {
          "amount": 1e+21,
          "delegator-address": "one149x673ga5xh58qpgr4c6r8wpqxaaptzwpjarjl",
          "reward": 1315439203973098200,
          "undelegations": []
        }
      ],
      "details": "StakeServe",
      "identity": "StakeServe",
      "last-epoch-in-committee": 222,
      "max-change-rate": "0.500000000000000000",
      "max-rate": "1.000000000000000000",
      "max-total-delegation": 1e+26,
      "min-self-delegation": 1e+22,
      "name": "StakeServe",
      "rate": "0.100000000000000000",
      "security-contact": "security@stakserve.com",
      "update-height": 1192,
      "website": "stakeserve.com"
    }
  }
}

**Comment by gupadhyaya** [comment]
@mindstyle85: the validator information metrics is based on EPoS for the current epoch (which is computed in the last block of the previous epoch) and it is not based on the latest data (stakes). This is appropriate as the reward earned (accumulated and per-key reward) are also corresponds to EPoS of the current epoch. 

Note that, GetMedianRawStakeSnapshot computes EPoS (effective stake, median) using the latest data (stakes), not specifically for the current epoch or the next epoch. If you want to cross-verify the validator information against this data, you should time the test for the last block of every epoch, where you get the median information from GetMedianRawStakeSnapshot and check the bound of effective stakes (obtained from all validator informations).

**Comment by mindstyle85** [comment]
@gupadhyaya yes i understand that part, all i am saying is the effective stake in the validator information never changes, at all. It stays like it is indefinetly.

case in point: current median is around 500k:

 "metrics": {
      "by-bls-key": [
        {
          "earned-reward": 9.587708240453163e+21,
          "key": {
            "bls-public-key": "02760cadc6ef3d3c1f8b66adbe182ebc252b451178efc168e856870311c8a7005c7060d28ea72c6c7adfab606989f413",
            "earning-account": "one1syx0rmtttr8jehlxvnkpyx4hvrlevmcx3tcghy",
            "effective-stake": "115000000000000000000000.000000000000000000",
            "group-percent": "0.053559547571523619",
            "overall-percent": "0.017139055222887558",
            "shard-id": 3

this validator has still 115k effective stake, the number does NOT change at any point in time from the start of the validator

**Comment by fxfactorial** [comment]
gotcha, so I'll have the effective-stake of this validator shown if it was in epos auction exactly at that moment, and the current one is like the one they had when they won the epos auction. Will try to include today

**Comment by mindstyle85** [comment]
> gotcha, so I'll have the effective-stake of this validator shown if it was in epos auction exactly at that moment, and the current one is like the one they had when they won the epos auction. Will try to include today

agreed on the first part.. for the second part it looks like the number shown when he first won the auction, and not for any subsequent auctions after that

**Comment by lijiang2087** [comment]
can we either close this or decide it's not a blocker for p2? @rlan35 @fxfactorial cc @Dewansahil @stephen-tse

**Comment by rlan35** [comment]
Not a blocker. I will close for now. The live effective stake info can be queries from other rpc.
