### ISSUE TITLE
Sent two Tx's with success over extension, only one on chain

### ISSUE THREAD

**Issue by err0r711** [harmony-one/harmony#2707]
https://explorer.os.hmny.io/#/tx/0xada57a75e3a1d170d87e34edaa86f1759e579b058ec5f7d3cc032005c3a609f7

https://explorer.os.hmny.io/#/tx/0xd89261fdb685075a6ebdab90abdf389a11aa2c878f0cbe14fb7cadd506e47004

./hmy --node=https://api.s0.os.hmny.io/ balances one1ka33uq8ht6c5wg43u52hg32fkvhx8mnap3mm4r
[
  {
    "shard": 0,
    "amount": 29999.994655276000000000

version v5797-v1.3.5-106-g56d19d2a (jenkins@ 2020-04-04T01:23:16+0000)

@denniswon @janet-harmony @Daniel-VDM

**Comment by lijiang2087** [comment]
"can remove it, its not an issue" from @mindstyle85

**Comment by mindstyle85** [comment]
so this is not an issue, the volunteer whose one1ka33uq8ht6c5wg43u52hg32fkvhx8mnap3mm4r is has in the mean time created a validator, hence why it looks like theres a tx missing, @err0r711 also thought he managed to get funds from the faucet but the facuet doesnt work
