### ISSUE TITLE
Persist keys and peerstore

### ISSUE THREAD

**Issue by LeoHChen** [harmony-one/harmony#271]
In our host structure, we need to persist the pub/private key and the peerstore of each host to disk.  So that when we restart a node, it can read the keys from the disk, no need to regenerate a random one.

**Comment by LeoHChen** [comment]
This is partially fixed by https://github.com/harmony-one/harmony/pull/307

**Comment by mindstyle85** [comment]
@LeoHChen can this be closed?

**Comment by lijiang2087** [comment]
over a year old, closing for now @LeoHChen @mindstyle85
