### ISSUE TITLE
Merge newnode class and handling into node class

### ISSUE THREAD

**Issue by LeoHChen** [harmony-one/harmony#272]
newnode is now used only for beacon chain connection.  It is causing problem for me now and I have to workaround.

when a new host is started, its selfPeer will generate multiaddress and the keypair. However, since didn't persist the keys, I have to pass it to the real node host.  It is related to the issue #271 . 

If we persist the keys, there won't be a problem when the real node host launched.  We have to merge newnode with node class with one time init of the host structure.  Either way, that's the right fix of the redundant newnode.

**Comment by alajko** [comment]
This will be addressed in the beaconchain design document.

**Comment by alajko** [comment]
https://github.com/harmony-one/harmony/pull/292

**Comment by LeoHChen** [comment]
not needed anymore.
