### ISSUE TITLE
Node stuck at block 0 with Cannot finalize block: cannot pay block reward

### ISSUE THREAD

**Issue by sophoah** [harmony-one/harmony#2748]
**Describe the bug**
Network version: 
```
./harmony --version
Harmony (C) 2020. harmony, version v5807-v1.0-20200405.5-0-g0c46e086 (jenkins@ 2020-04-06T04:46:06+0000)
```
I am starting from scratch : 
```
root@vmi360560:~/harmony# rm -rf md5sum.txt* hmy-docs harmony harmony_db_* bootnode
root@vmi360560:~/harmony# ./node.sh -S -z -I -N staking -M -R localhost:6070
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   799  100   799    0     0  11750      0 --:--:-- --:--:-- --:--:-- 11750
diff: md5sum.txt: No such file or directory
node.sh: downloaded harmony
node.sh: downloaded bootnode
node.sh: public IP address autodetected: 62.171.168.81
node.sh: ############### Running Harmony Process ###############
Staking mode; node key c583a63bf41246d48be23eb22bbd583e81c639d188ec1bbd5632d0c0f1a2eaf65369ee56d29de831ded3fde8dc09a481eaf2ca8784b0f15be
0de551c863181f2ff9e697dd9bae6a194e5dfa555fbc21c22f0e4997a1005a2245940c27b1b6d99ee88face84967bdfa624baaf62d304f19452a907169c6bbe5eac50fea
5ddbfd116eb37a35b0eee72652f501e0cd02e01f3d26daceb31d022172e210b03a78f01e6e5e6255a0b8cd6678ceaf053779f9f567ff311eb58883db711b9c9e4fc4201
-> shard 1
```

currently my shard 1 can't sync and will be stuck with those error message in the log: 
```
{"level":"error","port":"9000","ip":"x","error":"[Process] Cannot finalize block: cannot pay block reward: cannot set group sig mask bits: mismatching bitmap lengths, providedBitmapLength=0, expectedBitmapLength=8","caller":"/mnt/jenkins/workspace/harmony-release/harmony/api/service/syncing/syncing.go:577","time":"2020-04-06T07:59:19.289357406+02:00","message":"[SYNC] UpdateBlockAndStatus: Error adding new block to blockchain 1 1"}
{"level":"debug","port":"9000","ip":"x","block":{"ReceivedAt":"0001-01-01T00:00:00Z","ReceivedFrom":null},"caller":"/mnt/jenkins/workspace/harmony-release/harmony/api/service/syncing/syncing.go:585","time":"2020-04-06T07:59:19.289390959+02:00","message":"[SYNC] UpdateBlockAndStatus: Rolling back current block!"}
{"level":"error","port":"9000","ip":"x","error":"[Process] Cannot finalize block: cannot pay block reward: cannot set group sig mask bits: mismatching bitmap lengths, providedBitmapLength=0, expectedBitmapLength=8","caller":"/mnt/jenkins/workspace/harmony-release/harmony/api/service/syncing/syncing.go:801","time":"2020-04-06T07:59:19.289726348+02:00","message":"[SYNC] ProcessStateSync failed (isBeacon: false, ShardID: 1, otherHeight: 578, currentHeight: 0)"}
{"level":"debug","port":"9000","ip":"x","caller":"/mnt/jenkins/workspace/harmony-release/harmony/api/service/syncing/syncing.go:790","time":"2020-04-06T07:59:19.466882381+02:00","message":"[SYNC] Node is Not in Sync (isBeacon: false, ShardID: 1, otherHeight: 580, currentHeight: 0)"}
```

my local shard 0 is syncing ok.

**To Reproduce**
1 start the node as per normal

**Expected behavior**
Should sync

**Screenshots**

**Environment (please complete the following information):**
 - OS: [Linux, MacOS]
- Go environment [ ```go env``` ]

**Additional context**

**Comment by BrunoMarshall** [comment]
Same with shard 2 , can't sync and with error message in the log:
{"level":"error","port":"9000","ip":"18.184.223.63","error":"[Process] Cannot finalize block: cannot pay block reward: cannot set group sig mask bits: mismatching bitmap lengths, expectedBitmapLength=8, providedBitmapLength=0","caller":"/mnt/jenkins/workspace/harmony-release/harmony/api/service/syncing/syncing.go:577","time":"2020-04-06T06:10:54.324265535Z","message":"[SYNC] UpdateBlockAndStatus: Error adding new block to blockchain 1 2"}
{"level":"debug","port":"9000","ip":"18.184.223.63","block":{"ReceivedAt":"0001-01-01T00:00:00Z","ReceivedFrom":null},"caller":"/mnt/jenkins/workspace/harmony-release/harmony/api/service/syncing/syncing.go:585","time":"2020-04-06T06:10:54.324396025Z","message":"[SYNC] UpdateBlockAndStatus: Rolling back current block!"}
{"level":"error","port":"9000","ip":"18.184.223.63","error":"[Process] Cannot finalize block: cannot pay block reward: cannot set group sig mask bits: mismatching bitmap lengths, expectedBitmapLength=8, providedBitmapLength=0","caller":"/mnt/jenkins/workspace/harmony-release/harmony/api/service/syncing/syncing.go:801","time":"2020-04-06T06:10:54.3248595Z","message":"[SYNC] ProcessStateSync failed (isBeacon: false, ShardID: 2, otherHeight: 669, currentHeight: 0)"}
{"level":"info","port":"9000","ip":"18.184.223.63","myEpoch":1,"myBlock":1,"myViewID":1,"phase":0,"mode":"Syncing","caller":"/mnt/jenkins/workspace/harmony-release/harmony/consensus/consensus_service.go:459","time":"2020-04-06T06:10:54.324893039Z","message":"[UpdateConsensusInformation] Updating....."}
{"level":"info","port":"9000","ip":"18.184.223.63","myEpoch":1,"myBlock":1,"myViewID":1,"phase":0,"mode":"Syncing","headerNum":0,"caller":"/mnt/jenkins/workspace/harmony-release/harmony/consensus/consensus_service.go:465","time":"2020-04-06T06:10:54.324916667Z","message":"Epoch updated for nextEpoch curEpoch"}
{"level":"error","port":"9000","ip":"18.184.223.63","error":"failed to read shard state from DB: leveldb: not found, epoch=1","shard":2,"caller":"/mnt/jenkins/workspace/harmony-release/harmony/consensus/consensus_service.go:474","time":"2020-04-06T06:10:54.324942167Z","message":"Error retrieving nextEpoch shard state"}
{"level":"debug","port":"9000","ip":"18.184.223.63","caller":"/mnt/jenkins/workspace/harmony-release/harmony/api/service/syncing/syncing.go:790","time":"2020-04-06T06:10:54.469952009Z","message":"[SYNC] Node is Not in Sync (isBeacon: false, ShardID: 2, otherHeight: 671, currentHeight: 0)"}

**Comment by fxfactorial** [comment]
most likely fixed here: https://github.com/harmony-one/harmony/pull/2749
