### ISSUE TITLE
OSTN - Collect reward not working

### ISSUE THREAD

**Issue by sophoah** [harmony-one/harmony#2752]
**Describe the bug**
Collecting reward is not working, we have the below error message: 
```
./hmy --node="https://api.s0.os.hmny.io" staking collect-rewards --delegator-addr one1u6c4wer2dkm767hmjeehnwu6tqqur62gx9vqsd
[CollectRewards] no rewards to collect -- 2020-04-06 11:09:57 +0000 UTC
commit: v333-80a4f42, error: staking transaction error
```

I verified validator information and confirmed I have reward to collect

Collecting via staking explorer will show 0 ONE to collect

**To Reproduce**
1. Collect reward CLI or staking explorer

**Expected behavior**
Should be able to collect reward when there is reward to collect

**Screenshots**

**Environment (please complete the following information):**
```
./harmony --version
Harmony (C) 2020. harmony, version v5808-v1.0-20200405.6-0-ga876df67 (jenkins@ 2020-04-06T07:10:08+0000)
```

**Additional context**

**Comment by BrunoMarshall** [comment]
Testing with **Staking Explorer:**
Reward
![image](https://user-images.githubusercontent.com/35432495/78605209-69c38600-785b-11ea-834f-8e6e341d7850.png)

Collecting rewards: 
![image](https://user-images.githubusercontent.com/35432495/78605355-a7c0aa00-785b-11ea-8873-ad47cf7246ff.png)

Testing with **CLI**
![image](https://user-images.githubusercontent.com/35432495/78605504-f2422680-785b-11ea-9978-7c6078e8ca48.png)

**Comment by rlan35** [comment]
Should be fixed in latest ostn
