### ISSUE TITLE
signing 91% then between epoch transition i see bad uptime status, then im back in

### ISSUE THREAD

**Issue by mindstyle85** [harmony-one/harmony#2754]
**Describe the bug**

**so i was checking my signage:**
"result": {
    "booted-status": null,
    "current-epoch-performance": {
      "current-epoch-signing-percent": {
        "current-epoch-signed": 31,
        "current-epoch-signing-percentage": "0.911764705882352941",
        "current-epoch-to-sign": 34,
        "num-beacon-blocks-until-next-epoch": 6
      }
    },
    "currently-in-committee": true,
    "epos-status": "currently elected",
    "epos-winning-stake": "171781250000000000000000.000000000000000000",
    "lifetime": {
      "apr": "5.634542764137066146",
      "blocks": {
        "signed": 588,
        "to-sign": 827

**next try was right between the epochs and got this:**

"result": {
    "booted-status": "bad uptime",
    "current-epoch-performance": null,
    "currently-in-committee": false,
    "epos-status": "eligible to be elected next epoch",
    "epos-winning-stake": null,
    "lifetime": {
      "apr": "5.043668220573240525",
      "blocks": {
        "signed": 593,
        "to-sign": 832
      },

**and in the new epoch:**
"result": {
    "booted-status": null,
    "current-epoch-performance": {
      "current-epoch-signing-percent": {
        "current-epoch-signed": 4,
        "current-epoch-signing-percentage": "0.666666666666666667",
        "current-epoch-to-sign": 6,
        "num-beacon-blocks-until-next-epoch": 34
      }
    },
    "currently-in-committee": true,
    "epos-status": "currently elected",
    "epos-winning-stake": "133235714285714285714285.714285714285714286",
    "lifetime": {
      "apr": "5.043668220573240525",
      "blocks": {
        "signed": 596,
        "to-sign": 837

**Comment by rlan35** [comment]
Fixed in latest version.
