### ISSUE TITLE
hmy_getTransactionsCount logic should be separated into regular txns vs staking txns

### ISSUE THREAD

**Issue by denniswon** [harmony-one/harmony#2759]
The current hmy_getTransactionsCount uses account nonce to figure out the txns count for an account. As nonce is incremented both by regular and staking txns, using nonce is not the right way to return the regular and staking txns count separately.

Harmony block explorer displays txns and staking txns separately. 
https://github.com/harmony-one/harmony-dashboard-backend/issues/35

Instead of nonce, hmy_getTransactionsCount and hmy_getStakingTransactionsCount will loop through the txns histories to count the counts for each. (For now, seems most probable approach)

cc: @fxfactorial

**Comment by fxfactorial** [comment]
true, but i think we can limit the changes just to this one RPC which will just give back results for both. Just ignore the field you don't need
