### ISSUE TITLE
node.sh SIGSEV

### ISSUE THREAD

**Issue by mindstyle85** [harmony-one/harmony#2770]
**Describe the bug**

So the node.sh sigsev'd overnight without any user action on current OSTN network.
Run command: ./node.sh -S -N staking -z -M

![photo_2020-04-07_13-18-48](https://user-images.githubusercontent.com/55639830/78663501-818a2100-78d2-11ea-89e9-99f296a1463d.jpg)

**Environment (please complete the following information):**
node.sh: version: v1 20200407.0
Harmony (C) 2020. harmony, version v5809-v1.0-20200406.1-0-g1ca1f0d6 (jenkins@ 2020-04-07T01:06:47+0000)

**Comment by mindstyle85** [comment]
Passphrase is temporarely saved to: ./.hmy/blskeys/69c69773a6e2d74ced5272e6b1c30c54d4542146128049c75016ba9b9f6b39756a2fef3ef8283d3ed7cedbaf5dc02d18.pass
Enter passphrase for the BLS key file ./.hmy/blskeys/d13f8a662cfbc4ff7ca2e2ff143fbbf8182be674f24131a3e1ff9b5a4633df12a3863d96ec27cfbb72d16d02b65d7604.key:
Passphrase is temporarely saved to: ./.hmy/blskeys/d13f8a662cfbc4ff7ca2e2ff143fbbf8182be674f24131a3e1ff9b5a4633df12a3863d96ec27cfbb72d16d02b65d7604.pass
Enter passphrase for the BLS key file ./.hmy/blskeys/fe3f51ed2071c047d85558ef4278d4d6e331224006b24c251a5172537ca873c29edb1f3a69c6940e13f6b598d347b390.key:
Passphrase is temporarely saved to: ./.hmy/blskeys/fe3f51ed2071c047d85558ef4278d4d6e331224006b24c251a5172537ca873c29edb1f3a69c6940e13f6b598d347b390.pass
Do you wish to delete the saved passphrase files after successful start of node? (y|n):y
node.sh: ############### Running Harmony Process ###############
Staking mode; node key 662ae286fcdb966a35827b6cc8c37821cd7cedf8fe818bada8af202b88c6f4bd4f8e89faea9000f4a32f8b282677ad8069c69773a6e2d74ced5272e6b1c30c54d4542146128049c75016ba9b9f6b39756a2fef3ef8283d3ed7cedbaf5dc02d18d13f8a662cfbc4ff7ca2e2ff143fbbf8182be674f24131a3e1ff9b5a4633df12a3863d96ec27cfbb72d16d02b65d7604fe3f51ed2071c047d85558ef4278d4d6e331224006b24c251a5172537ca873c29edb1f3a69c6940e13f6b598d347b390 -> shard 0
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0xbb9175]

goroutine 653 [running]:
github.com/harmony-one/harmony/consensus.(*Consensus).validatorSanityChecks(0xc0000af900, 0xc015675db0, 0x13a)
        /mnt/jenkins/workspace/harmony-release/harmony/consensus/checks.go:15 +0x85
github.com/harmony-one/harmony/consensus.(*Consensus).handleMessageUpdate(0xc0000af900, 0xc00e147e06, 0x121, 0x13a)
        /mnt/jenkins/workspace/harmony-release/harmony/consensus/consensus_v2.go:70 +0x3d1
github.com/harmony-one/harmony/consensus.(*Consensus).Start.func1(0xc0000af900, 0xc0003b9080, 0xc000c98840, 0xc0003b8d80, 0xc000c987e0)
        /mnt/jenkins/workspace/harmony-release/harmony/consensus/consensus_v2.go:475 +0x5ae
created by github.com/harmony-one/harmony/consensus.(*Consensus).Start
        /mnt/jenkins/workspace/harmony-release/harmony/consensus/consensus_v2.go:313 +0x67
node.sh: node process finished with status 2
node.sh: restarting in 10s...
Enter passphrase for the BLS key file ./.hmy/blskeys/662ae286fcdb966a35827b6cc8c37821cd7cedf8fe818bada8af202b88c6f4bd4f8e89faea9000f4a32f8b282677ad80.key:

[node] 0:bash*                                                                "OpenStakingVM2" 11:30 07-Apr-20

**Comment by gupadhyaya** [comment]
@mindstyle85 definitely exploded due to protobuf changes, you have the latest harmony binary right? Also, cleaned db? @fxfactorial

**Comment by mindstyle85** [comment]
Im not sure about the db since it was a volunteer case and he was a bit confused about it.. deff had latest binary though (posted it)

**Comment by fxfactorial** [comment]
Aware - will fix

**Comment by fxfactorial** [comment]
Will be hard to replicate but very confident that will be fixed in https://github.com/harmony-one/harmony/pull/2773
