### ISSUE TITLE
Having BINGO but number of signature doesn't increment

### ISSUE THREAD

**Issue by sophoah** [harmony-one/harmony#2771]
**Describe the bug**
My node is currently having issue signing so I had two terminals :
1.  tail -f latest/zero*.log | grep BINGO
2.  Each time I saw a BINGO in 1, I executed ```date && ./hmy -n https://api.s0.os.hmny.io blockchain validator information one1t4p6x5k7zw59kers7hwmjh3kymj0n6spr02qnf | jq '.["result"]["current-epoch-performance"]'```

so for troubleshooting I was checking if I had any BINGO and compared that with my signature and discover that it seems like not all BINGO were accounted in signature count

screenshot 1
![image](https://user-images.githubusercontent.com/35721420/78687456-c344b700-7926-11ea-9017-001a8cebdc22.png)

screenshot 2
![image](https://user-images.githubusercontent.com/35721420/78686634-df942400-7925-11ea-9099-4b80ff385abb.png)

This is affecting my current epoch performance preventing me stay elected 

**To Reproduce**
edit validator active and repeat 1 and 2 above

**Expected behavior**
All BINGO should account for 1 signature and increment it accordingly

**Screenshots**
See above

**Environment (please complete the following information):**
```
root@scw-vigorous-herschel:~# ./harmony --version
Harmony (C) 2020. harmony, version v5809-v1.0-20200406.1-0-g1ca1f0d6 (jenkins@ 2020-04-07T01:06:47+0000)
```
**Additional context**
Validator seat are currently all taken 200. when i am edit validator active i am taking other BLS slots, not sure if that has any effect.

**Comment by rlan35** [comment]
Thanks for the report. The BINGO actually doesn't mean the signature is collected. It only means you are part of the committee and you got a newly committed block.

Definitely something to think through and make less confusing.

**Comment by sophoah** [comment]
@rlan35 ok but this is still a bug causing me not to be elected at the end.
