### ISSUE TITLE
Mainnet: node.sh sigsev

### ISSUE THREAD

**Issue by mindstyle85** [harmony-one/harmony#2781]
**Describe the bug**

OS version: debian 9 (64bit)
so this version:
 ./node.sh -v
node.sh: version: v1 20200407.0 (reproduced on 14.01. version too - 20200114 on the same machine)

Seems to have some problems, looks like it downloads the harmony binary than then needs to be chmodded (user ran node.sh with sudo), then after that there is a path issue and node.sh sigsevs:

![unknown (1)](https://user-images.githubusercontent.com/55639830/78788217-c33aca80-79ab-11ea-96de-0d68f84adcb4.png)
![unknown](https://user-images.githubusercontent.com/55639830/78788227-c6ce5180-79ab-11ea-92e8-c76b421c28d7.png)

He also gets sigsev on his machine for this only: root@vmi340451:~/harmony# LD_LIBRARY_PATH=. ./harmony -version
Segmentation fault

And also a question: how come mainnet node.sh downloads all files (libs, md5 and binaries) into staging too? If you do ./node.sh -d it checks and/or downloads the files to staging directory instead of "home".

**Comment by LeoHChen** [comment]
are you using static binary?  If static binary, no need to do LD_LIBRARY_PATH, 

what's the configuration of the VM? Please do `cat /proc/cpuinfo`

**Comment by LeoHChen** [comment]
he is running as root, no need to do `sudo`

**Comment by LeoHChen** [comment]
Also, noted the version of our mainnet node.sh is 
```
$ ./scripts/node.sh -v
node.sh: version: v1 20200327.0
```

**Comment by fxfactorial** [comment]
leo i think this is hte same issue I posted like three weeks ago about node.sh, i wrote about checking the core dump. The signal was unusal , was a memory alignment thing, need to find the issue, i wrote the exact signal being sent.

**Comment by LeoHChen** [comment]
some VM without latest CPU virtualization may see this problem.  I've see people was trying to run nodes on Pentium CPU and got crash.  Our BLS library was optimized to use some latest CPU instruction and won't work on older CPU.

**Comment by fxfactorial** [comment]
makessss sense - how can we catch that though ? I mean, like check if that wil happen on host machine and not even run the binary

**Comment by mindstyle85** [comment]
@LeoHChen @fxfactorial 

some more info, he is using Contabo, launches only with node.sh, no -I for static binary and result is the same with or without sudo

not sure about node.sh version, his is the latest one from harmony.one/node.sh and mine is from january when i switched to state prune

machine info:
core id         : 2
cpu cores       : 4
apicid          : 2
initial apicid  : 2
fpu             : yes
fpu_exception   : yes
cpuid level     : 13
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon rep_good nopl xtopology pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single ssbd ibrs ibpb kaiser fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm rdseed adx smap xsaveopt arat
bugs            : cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs taa itlb_multihit
bogomips        : 4399.99
clflush size    : 64
cache_alignment : 64
address sizes   : 40 bits physical, 48 bits virtual
power management:

processor       : 3
vendor_id       : GenuineIntel
cpu family      : 6
model           : 79
model name      : Intel(R) Xeon(R) CPU E5-2630 v4 @ 2.20GHz
stepping        : 1
microcode       : 0x1
cpu MHz         : 2199.998
cache size      : 16384 KB
physical id     : 0
siblings        : 4
core id         : 3
cpu cores       : 4
apicid          : 3
initial apicid  : 3
fpu             : yes
fpu_exception   : yes
cpuid level     : 13
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon rep_good nopl xtopology pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single ssbd ibrs ibpb kaiser fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm rdseed adx smap xsaveopt arat
bugs            : cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs taa itlb_multihit
bogomips        : 4399.99
clflush size    : 64
cache_alignment : 64
address sizes   : 40 bits physical, 48 bits virtual
power management:

**Comment by mindstyle85** [comment]
closing this for now, seems it was due to a wrong node.sh version, Leo fixed the vanity links
