### ISSUE TITLE
Staking Dashboard - Undelegate from "not elected" validator is 1 epoch not 7 epoch waiting time

### ISSUE THREAD

**Issue by BrunoMarshall** [harmony-one/harmony#2782]
In Staking Dashboard if we undelegate from a "not elected" validator, in the undelegations area appears 7 epoch, but we receive the funds after 1 epoch
![image](https://user-images.githubusercontent.com/35432495/78783315-bca85500-79a3-11ea-8398-5af68188693d.png)

How to recreate the issue:
-delegate to a validator
-Undelegate from a Validator **"not elected"**
in the Undelegation will appears 7 epochs, but after one the undelegation fund is received and the validator erased from the undelegations area

**Comment by BrunoMarshall** [comment]
Moved to main repo due to concerns that this issue could be at protocol level

**Comment by mindstyle85** [comment]
@fxfactorial @gupadhyaya @rlan35 there was no update about it but is this an intended fix so delegators can get their funds out earlier in case the validator isnt elected?

**Comment by rlan35** [comment]
It's not exactly 7 epochs. Its 7 epochs after the last epoch the unelected validator was elected. So for a just unelected validator last epoch. The lock time is still 7 epoch.

The Undelegation section here clarifies that: https://medium.com/harmony-one/the-definitive-guide-to-harmony-open-staking-6c78976a7d63

**Comment by rlan35** [comment]
But yea, seems it's still a UI issue. @mikedoan

**Comment by mindstyle85** [comment]
@rlan35 undelegation via CLI also takes just 1 epoch so its not dashboard issue at all i think

**Comment by sophoah** [comment]
@mindstyle85 nop I still don't get it, the undelegation was only initiated at epoch 0, so would being inactive count as being undelegated?

**Comment by mindstyle85** [comment]
Seems like if a validator is inactive for a few epochs, that already counts for the undelegation too.. so once a validator is inactive for 7+ epochs, the undelegation should basically be instant as per what RJ said
