### ISSUE TITLE
add more tests for internal/utils/utils.go

### ISSUE THREAD

**Issue by LeoHChen** [harmony-one/harmony#279]
The Save/Load functions have no test coverage.

**Comment by Avni-Sharma** [comment]
I would like to work on this

**Comment by alajko** [comment]
Welcome to Harmony @Avni-Sharma! Please make a pull request and the harmony team will help you out!  This link will guide you through the process: https://github.com/harmony-one/harmony/blob/master/CONTRIBUTING.md
