### ISSUE TITLE
[Feature] more accurate lifetime uptime by adding the non-elected epoch blocks

### ISSUE THREAD

**Issue by sophoah** [harmony-one/harmony#2791]
# Problem/limitation At Hand
Current lifetime uptime is calculated based on the lifetime blocks the validator is supposed to signed vs those it didn't signed.

example:
```
    "lifetime": {
      "apr": "13.522844421866951247",
      "blocks": {
        "signed": 28409,
        "to-sign": 29568
      },
```
==> `96,08%`

issue here is that when the validator is not elected, the lifetime "to-sign" doesn't increment. That can falsely tell the delegator that the validator has a good uptime while in reality it is not.

**Which component?**

- [ ] consensus
- [ ] deploy script
- [ ] wallet
- [ ] explorer
- [ ] node script
- [ ] test automation
- [ ] demo app
- [ X ] Staking protocol

# Proposed Solution
Make sure that the lifetime "to-sign" also include the non-elected epoch numbers of blocks.

# Alternatives Considered
no change to current uptime logic

# Additional Context

**Comment by rlan35** [comment]
This is working as intended. We don't expect all validators to be able to get elected all the time. For those unelected validators, it will be unfair to still count their liveness, because it will literally make all unelected validators uptime close to 0%.

**Comment by rlan35** [comment]
The uptime tells the delegator how good the validator is when it's obligated to sign blocks. When it's not elected, it's not obligated to sign.

**Comment by BrunoMarshall** [comment]
The proposal to have 2 diferent fields in the staking explorer is here: https://github.com/harmony-one/staking-dashboard/issues/362
Proposal:
Add 2 different fields:
-Signed Blocks: *(number of blocks signed / number of blocks able to be signed) X 100
-Uptime : (number of epochs since validation creation / last Epoch number) X 100

**Comment by fxfactorial** [comment]
-Signed Blocks: we already have this right? 
-Uptime: you have the block number that the validator was created it, but now also want the epoch that block number correponds to?

**Comment by mindstyle85** [comment]
why would you show uptime based on downtime too, what if a validator decided to go inactive for an epoch or two? he didnt really lose any uptime since he decided to go inactive.. i  think showing uptime as it is, is ok?

**Comment by sophoah** [comment]
this is because now the delegator are losing money for 2 epoch. What if he goes offline more than 2 epoch ... Also why would he purposely go inactive ? Wouldn't he want to stay elected as much as possible?

A validator that has been online 100% for 100 epoch, would be more trusted than another validator that has started at the same time but was elected only for 10 epoch with 100% uptime.

the challenge here is that the validator need to work on its marketing as well to ensure it has enough delegation. And yes, it would be unfair for small validator that can't stay elected but you don't want a delegator to be misguided by just looking at the uptime.

**Comment by mindstyle85** [comment]
ok so from current situation, where many validators got kicked out of comittee due to smaller bids, i do not think they should also be punished with lower uptime because they are not in current epoch
