### ISSUE TITLE
RPC wrong booted-status message

### ISSUE THREAD

**Issue by mindstyle85** [harmony-one/harmony#2796]
**Describe the bug**
so once my validator got booted i only see this, not the real booted reason:

"booted-status": "not booted",
    "current-epoch-performance": null,
    "currently-in-committee": false,
    "epos-status": "not eligible to be elected next epoch",
    "epos-winning-stake": null,
    "lifetime": {
      "apr": "1.925327287961566561",
      "blocks": {
        "signed": 24664,
        "to-sign": 24928

**Comment by gupadhyaya** [comment]
fixed in https://github.com/harmony-one/harmony/pull/2822

**Comment by gupadhyaya** [comment]
@mindstyle85 please close after verifying in the next rolling upgrade.

**Comment by mindstyle85** [comment]
tested, working now
