### ISSUE TITLE
RPC: shows wrong number of blocks

### ISSUE THREAD

**Issue by mindstyle85** [harmony-one/harmony#2797]
**Describe the bug**

rpc always returns 35 instead of 38 total blocks within an epoch:

"current-epoch-signed": 0,
        "current-epoch-signing-percentage": "0.000000000000000000",
        "current-epoch-to-sign": 32,
        "num-beacon-blocks-until-next-epoch": 3

"current-epoch-signed": 0,
        "current-epoch-signing-percentage": "0.000000000000000000",
        "current-epoch-to-sign": 13,
        "num-beacon-blocks-until-next-epoch": 22

**Comment by john-harmony** [comment]
Also may want to check that the current-epoch signed values are correct - This was from a validator in Shard 1. If I read it correctly it's saying there were 102 blocks produced in Shard 1 to the 38 blocks produced in Shard 0 (beacon chain)

```
        "current-epoch-performance": {
            "current-epoch-signing-percent": {
                "current-epoch-signed": 102,
                "current-epoch-to-sign": 102,
                "num-beacon-blocks-until-next-epoch": 1,
                "current-epoch-signing-percentage": "1.000000000000000000"
            }
        },
```

**Comment by gupadhyaya** [comment]
`num-beacon-blocks-until-next-epoch` field is creating more confusions, as it need not be equal to `(BlocksPerEpoch - current-epoch-to-sign)`. Further, in case of multiple keys per validator, the two counters `current-epoch-signed` and `current-epoch-to-sign` can be multiples of `BlocksPerEpoch`. To make this consistent and useful, we could use:

`num-blocks-until-next-epoch` = `BlocksPerEpoch - (current-epoch-to-sign / num-bls-keys-currently-signing)`

however, this would be approximately correct only when all the keys are same shard. If they are on different shards, it will again be wrong.

best would be to change the validator wrapper counters to maintain per bls key based, which requires hard-refresh.

@rlan35 @fxfactorial how should we go about with this?

**Comment by fxfactorial** [comment]
let's just remove this field, its a derived value anyway and causing more hassle than benefit

**Comment by gupadhyaya** [comment]
@fxfactorial you mean just remove `num-beacon-blocks-until-next-epoch`?
