### ISSUE TITLE
Invalid Bloom on beacon sync after crashed node got sync'ed again.

### ISSUE THREAD

**Issue by rlan35** [harmony-one/harmony#2802]
Nodes in shard 2 crashed without graceful shutdown, so the blocks are lost and need resync.

The node immediate see errors below in beacon sync after restart.

Similar node which didn't crash didn't see the error.

Suspect it's related to offchain data inconsistency due to crash.

\nError: invalid bloom (remote: 00000000000000000000000000000000000000000000000000000000000000000000000000008000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000200000000000000000000400000010000000000000000000000000000800000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000  local: 00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000)\n##############################\n"}

**Comment by LeoHChen** [comment]
The db snapshot of shard2 is uploaded here. s3://pub.harmony.one/ostn/crash/0409/hmydb.tgz

**Comment by rlan35** [comment]
Fixed.
