### ISSUE TITLE
delegator earned way too much tokens

### ISSUE THREAD

**Issue by mindstyle85** [harmony-one/harmony#2813]
**Describe the bug**
A delegator (one1zxknrp0yth9m4wq4g24dd09zs7dlnrkgdghkvx) had delegated 1,3M tokens to this validator: https://staking.harmony.one/validators/one1fjr4y3nwsg2fmxklh7vf6xl9u3tl4vsdevcg4t

tx is here: https://explorer.os.hmny.io/#/stakingTx/0xfc0d8345c372233a7392441651315c99342cd41d9e400f8fd8becec81a88c779

it has earned 4,8k tokens in just 3 epochs to him, so im guessing something went wrong here, because he earned way too much

![photo_2020-04-12_02-40-59](https://user-images.githubusercontent.com/55639830/79057925-2015d980-7c67-11ea-89bf-fce63f488f72.jpg)

to me it looks like he got a boost in % on the first epoch, since the validator had high % even though that shouldnt have happened?

delegation happened at 02:12 CEST while he notified me at 02:22 CEST 

thanking LordClick for notifying about this!

**Comment by rlan35** [comment]
His current reward as of block 19714 is 

{
                    "delegator-address": "one1zxknrp0yth9m4wq4g24dd09zs7dlnrkgdghkvx",
                    "amount": 1334567000000000000000000,
                    "reward": 5045079731469366547204,
                    "undelegations": []
                }

he delegation at block 18866. 

I calculated he is getting roughly 0.3 ONE per block as of now, which is reasonable amount.

Actually this delegator delegated way early on at block 2492: https://explorer.os.hmny.io/#/stakingTx/0xff135fc4aad4f6b97e40f368c97903c16c6e89e65dc6e479c5487b24bfbe87fd

So the reward amount seems reasonable.

**Comment by mindstyle85** [comment]
yeah the old delegation he did explains it, sorry i missed that and gave you some extra work..

**Comment by rlan35** [comment]
That's fine. :)
