### ISSUE TITLE
Staking Dashboard only shows 15 delegators on portfolio page

### ISSUE THREAD

**Issue by MaggieWang-Harmony** [harmony-one/harmony#2815]
![image](https://user-images.githubusercontent.com/55899206/79061546-1fb91680-7c46-11ea-93b9-0ab8274c0bb5.png)

![image](https://user-images.githubusercontent.com/55899206/79061596-ac63d480-7c46-11ea-8ac6-52066909137b.png)

On portfolio page
Staking dashboard only shows up to 15 delegations. I have delegated to 16 validators but only 15 show up. The same issue also met by other delegators.

**Comment by sophoah** [comment]
hey @MaggieWang-Harmony there is already a similar issue opened here : https://github.com/harmony-one/staking-dashboard/issues/333
