### ISSUE TITLE
Bug about the query  transaction-by-hash in localnet

### ISSUE THREAD

**Issue by Road00** [harmony-one/harmony#2820]
I run the harmony localnet in the docker

and then I create a transaction from one129r9pj3sk0re76f7zs3qz92rggmdgjhtwge62k to one103q7qe5t2505lypvltkqtddaef5tzfxwsse4z7 ,from shard 1 to shard 0, amount is 0.01

after get the transaction receipt, I sent a query using `hmy blockchain transaction-by-hash` but I got a null result.

but `hmy blockchain transaction-by-hash`  seem to work well to query the transaction from shard 0 to shard 1

Result:

root@e6bb89eede59:`~/keystore# hmy balances one103q7qe5t2505lypvltkqtddaef5tzfxwsse4z7`

[
    {
       "shard": 0,
       "amount": 72.390952380952380960
    },
    {
       "shard": 1,
       "amount": 0.000000000000000000
    }
]

root@e6bb89eede59:`~/keystore# hmy balances one129r9pj3sk0re76f7zs3qz92rggmdgjhtwge62k`

[
  {
    "shard": 0,
    "amount": 0.000000000000000000
  },
  {
    "shard": 1,
    "amount": 77.704264714285714294
  }
]

root@e6bb89eede59:`~/keystore# hmy transfer --node="http://localhost:9500" \`
`--from one129r9pj3sk0re76f7zs3qz92rggmdgjhtwge62k \`
`--to one103q7qe5t2505lypvltkqtddaef5tzfxwsse4z7 \`
`--from-shard 1 --to-shard 0 --amount 0.01`

{
  "transaction-receipt": "0x219f2406a72ea77a2119a933e26d1ef54f0e812fb9450f4b7e3f0871e51fec18",
  "time-signed-utc": "2020-04-13 07:56:18.081211"
}

root@e6bb89eede59:`~/keystore# hmy blockchain transaction-by-hash 0x219f2406a72ea77a2119a933e26d1ef54f0e812fb9450f4b7e3f0871e51fec18`

{
  "id": "0",
  "jsonrpc": "2.0",
  "result": null
}

**Comment by mindstyle85** [comment]
@Road00 im not sure how old the localnet config is, but we have a live testnet, i would kindly invite you to try it there: https://docs.harmony.one/home/validators
