### ISSUE TITLE
Explorer node restart will accumulate redundant txn history data

### ISSUE THREAD

**Issue by rlan35** [harmony-one/harmony#2831]
1. Explorer goes through all blocks and process them again everytime explorer node is restarted.
2. it was fine before because there is no cummulative data to store, but now it doesn't work because we added txn history data, which append new txns to the existing data.
3. If we don't remove the explorer db , then every restart will double the txn history data on the addresses. Making it more and more likely to OOM

Request:
1. We need to add checkpoint of processed blocks so as to not process them again
2. Need to change the txn history logic to avoid adding duplicate txns.
3. We need to store the txns data separately. rather than appending raw txn data together for txn history.

**Comment by AndyBoWu** [comment]
for @john-harmony , the explorer DB is located in the home dir with name pattern like `explorer_storage_<ip>`. you can remove the old data by issue the cmd `sudo rm -rd explorer_storage_<ip>`. This db folder is NOT the harmony db folder we refer to. 

LMK if you have any questions.
