### ISSUE TITLE
[Feature] multikey - rpc for signing stats on each key separately

### ISSUE THREAD

**Issue by mindstyle85** [harmony-one/harmony#2847]
It would be great if we can add signage stats by bls key to the validator information rpc, so that multibls runners can easily identify which bls key might be undersigning (in case of multi shard or multi node via 1 validator)

**Comment by fxfactorial** [comment]
You have that already indirectly by the rewards per key , which one is under signing is the one with lower rewards or non increasing rewards

**Comment by mindstyle85** [comment]
ah, let me check that as soon as we are able to spin a multi shard multi bls validator @fxfactorial , then ill close this one myself if it works out ok :)

**Comment by sophoah** [comment]
@fxfactorial I guess P-OPS are looking at an RPC that could tell us when our node failed to sign a specific block ? do you think this is something we can have? Right now based on the reward of each BLS we can't really say if the issue is due to failure to sign a block

**Comment by mindstyle85** [comment]
Just to iterate - we checked the rewards earned and since s0 is currently lagging behind its producing less rewards, so cant really fully help with checking if a bls key is undersigning (because in this case its not even though rewards are lesser)
