### ISSUE TITLE
[submission] Validators Information Portal - Website - History - Metrics

### ISSUE THREAD

**Issue by BrunoMarshall** [harmony-one/harmony#2850]
# Linked bounty:
https://github.com/harmony-one/harmony/issues/2716
# Description of the product/tool
This is a website where i will collect the validators information that Harmony release in social Media and also the information/Metrics available on the Harmony Blockchain.
the main idea is to show the more reliable/trusted validators
website: www.harmonyvalidators.com
(the website(metrics area) is currently under-construction

# Perceived impact to another user or the organization
The impact is free publicity for validators

**Comment by gizemcakil** [comment]
One idea to make the platform even stronger > do we have to keep it Harmony specific or maybe open platform is a better solution?

**Comment by JB273** [comment]
If it's going to be more public then the site name needs to change for sure....
I like the initiative, is there more (mockup) of what you want to do with it in the future?
How do you check the reliable validators, are you going to give them a rating and based on what or how?

**Comment by CryptosWolfOfAllStreets** [comment]
Still a work in progress but we have the opportunity to make something great here.

**Comment by BrunoMarshall** [comment]
@JB273 

>  If it's going to be more public then the site name needs to change for sure.... 
A: What do you mean with site name? instead of Hamony validators? sure we can add another name

> is there more (mockup) of what you want to do with it in the future?
A: this website serves to show validators information and to give them publicity showing information to delegators, we need to add metrics to the website, we need to figur how and what to show

> How do you check the reliable validators, are you going to give them a rating and based on what or how?
A: there is a section where we will show the verified validators and all partners that harmony suggest, currently we have only P-Ops validator there in the (Verified validators section). I think the rating could be something to add to the metrics, need to talk to @sophoah maybe he has some ideas

**Comment by mindstyle85** [comment]
@gizemcakil will let you or the team handle this one since its a team member, ok?

**Comment by mindstyle85** [comment]
@BrunoMarshall will you continue this, seems its stopped now?
