### ISSUE TITLE
the boot status of the validator who is eligible to be elected is nil

### ISSUE THREAD

**Issue by ivorytowerdds** [harmony-one/harmony#2851]
**Describe the bug**
The boot status will only be nil when the validator is elected. However I noticed a validator who is eligible to be elected but not elected also has nil boot status. 

**To Reproduce**
1. run the jupyter notebook in the vm: http://analytics.hmny.io/notebooks/harmony-log-analysis/notebooks/economic-test/old_version_test/bug_report.ipynb
2. It will output the epos-status classification who all validators with nil boot status, if you see epos-status are not only `currently elected`, you can stop the for loop, and quickly run `df[(df['boot-status'].isna()) & (df['epos-status'] == 'eligible to be elected next epoch')]` to get the one address of the exception.
3. run `getValidatorInfo(address)` you will see the bug in the screenshot. 

**Expected behavior**
The boot status will only be nil when the validator is elected. 

**Screenshots**
![image](https://user-images.githubusercontent.com/34232522/79610130-d08f3d80-80ac-11ea-92d1-1649f109bc33.png)

**Environment (please complete the following information):**
- OS:  Ubuntu

**Comment by gupadhyaya** [comment]
@ivorytowerdds is this bug still reproducible?
