### ISSUE TITLE
[Feature] Add import keyStore functionality on Harmony Chrome Extension

### ISSUE THREAD

**Issue by fmanea** [harmony-one/harmony#2864]
# Problem/limitation At Hand

**Which component?**

- [ ] consensus
- [ ] deploy script
- [ X] wallet
- [ ] explorer
- [ ] node script
- [ ] test automation
- [ ] demo app
- [ ] others ...

# Proposed Solution

Give the possibility for the user to import a KeyStore, that will be decrypted with a password, in order to unlock an Account. I have attached a high-level design with Mock-ups.

[ANH-HarmonyHighLevelDesign-Ankr-Interoperibility-.pdf](https://github.com/harmony-one/harmony/files/4508021/ANH-HarmonyHighLevelDesign-Ankr-Interoperibility-.pdf)

**Comment by denniswon** [comment]
https://github.com/harmony-one/wallet-extension/pull/41
