### ISSUE TITLE
[Feature] support libp2p autonat

### ISSUE THREAD

**Issue by LeoHChen** [harmony-one/harmony#2865]
# Problem/limitation At Hand

Please look into the libp2p autonat support in harmony node, so that it can work in private network automatically.

https://github.com/libp2p/go-libp2p-autonat

**Which component?**

- [x] libp2p
- [ ] consensus
- [ ] deploy script
- [ ] wallet
- [ ] explorer
- [ ] node script
- [ ] test automation
- [ ] demo app
- [ ] others ...

# Proposed Solution

We had a way to run harmony node within NAT with manual setup, the document is like there.
https://docs.google.com/document/d/1Pq4hrrBAKDaRGQYQC0da--S5TGIzyfi5u5j67RXh-jo/edit#heading=h.4a85pam05xgm

I expect the autonat library will help node runners to run node within nat without manual configuration, or just one time configuration.

**Comment by jz0000** [comment]
I have created a new issue: 2959 "enable NAT traversal for simple 1-level NAT situation with UPNP support: connecting local host validator behind a NAT to public leaders" to track the 1st step solution of this general issue. 

Basically for the 1st step we don't need to apply libp2p_autonat so generally, as libp2p_autonat is a framework to set up public relay nodes to help nodes behind all possible NAT structure to talk to each other through pre-configured relay public nodes. For our current harmony network, it might not be so urgent, but we can monitor how harmony's networking environment changes in the future.

**Comment by jz0000** [comment]
https://github.com/harmony-one/harmony/issues/2959
