### ISSUE TITLE
Shard 0 Sync problem

### ISSUE THREAD

**Issue by sophoah** [harmony-one/harmony#2867]
**Describe the bug**
Shard 0 get stuck at random blocks:
node #1 - block 68193 - for this one I had DB deleted and let it resync from scratch and woke up to see it was stuck at block 68193
node #2 - block 65287 - this one has 181 BLS key running but I don't think so it this has anything to do with the sync issue. this one seems to be block when I was trying fast sync node #1 by stopping #2 , do a backup of harmony_db_0, then restart, since then it has been blocked at block 65287

on node #1, at the time I was building #2 for the first time I did the same to fast sync node #2 and it worked but I forgot to restart the #1 and 2h later when I restarted #1, I discovered it had sync issue and was stuck from where i stopped it (block was around 5xxxx).

**To Reproduce**
- method 1
1. start a sync from scratch by deleting shard 0 DB

- method 2
1. stop / start a current shard 0 working node

**Expected behavior**
no sync issue should happened

**Screenshots**
Here are the zerolog:
- node #1 : https://gist.github.com/sophoah/864b78870842a3d88cfade8f2186ea51
- node #2 : https://gist.github.com/sophoah/8a51d0e7704d2f2b9f672bf7e3322d11

**Environment (please complete the following information):**
 - OS: [Linux, MacOS]
- Go environment [ ```go env``` ]

**Additional context**
I'll also try to stop / start on a non shard 0, shard and it worked fine. So issue seems to be on shard 0 chain only, maybe that is why

**Comment by yelllowsin** [comment]
I am having a similar issue on shard 0 as well with one of my nodes. Mine has stuck on block 66606. I see many messages like this on the zerolog file:

`{"level":"info","port":"9000","ip":"13.68.198.187","curBlockNum":66606,"receivedBlockNum":71136,"caller":"/mnt/jenkins/workspace/harmony-release/harmony/api/service/syncing/syncing.go:543","time":"2020-04-22T01:16:30.830267043Z","message":"[SYNC] Inappropriate block number, ignore!"}`

Here is a more complete Gist file:

https://gist.github.com/yelllowsin/581be4a730a368054cff8286dd228d2e

**Comment by rlan35** [comment]
@sophoah for your nodes, they are stuck at block sync'ing:

```{"level":"debug","port":"9000","ip":"y.y.y.y","caller":"/root/go/src/github.com/harmony-one/harmony/api/service/syncing/syncing.go:784","time":"2020-04-22T02:40:17.732629411+02:00","message":"[SYNC] Node is OUT OF SYNC (isBeacon: false, ShardID: 0, otherHeight: 70890, currentHeight: 65287)"}
{"level":"error","port":"9000","ip":"y.y.y.y","error":"rpc error: code = Unknown desc = [SYNC] GetBlockHashes Request cannot find startHash 0x2dbdd9a1518d917f3adb703eeb593ce86e7bf9ebd2b5a9be9914f8ea2ee845ca","target":"54.196.12.99:6000","caller":"/root/go/src/github.com/harmony-one/harmony/api/service/syncing/downloader/client.go:52","time":"2020-04-22T02:40:17.827652624+02:00","message":"[SYNC] GetBlockHashes query failed"}```

They are requesting for a blockHash but the other side couldn't find it. But I didn't find the corresponding block in RPC. Did you try restarting your node and see if the problem disappear?

**Comment by rlan35** [comment]
@yelllowsin for your log, I see it's already sync'ing pass block 66606. Seems it should have sync'ed up by itself?

**Comment by sophoah** [comment]
> @sophoah for your nodes, they are stuck at block sync'ing:
> 
> ```
> {"level":"error","port":"9000","ip":"y.y.y.y","error":"rpc error: code = Unknown desc = [SYNC] GetBlockHashes Request cannot find startHash 0x2dbdd9a1518d917f3adb703eeb593ce86e7bf9ebd2b5a9be9914f8ea2ee845ca","target":"54.196.12.99:6000","caller":"/root/go/src/github.com/harmony-one/harmony/api/service/syncing/downloader/client.go:52","time":"2020-04-22T02:40:17.827652624+02:00","message":"[SYNC] GetBlockHashes query failed"}```
> 
> They are requesting for a blockHash but the other side couldn't find it. But I didn't find the corresponding block in RPC. Did you try restarting your node and see if the problem disappear?
> ```

yes I tried @rlan35 before, and i also just retried. same issues stuck at the same block

**Comment by yelllowsin** [comment]
> @yelllowsin for your log, I see it's already sync'ing pass block 66606. Seems it should have sync'ed up by itself?

Well, actually i was checking using ./hmy blockchain latest-headers and it was stuck on this block, not increasing. Now it is back, working again...saw that you commented on Discord the issue was related to DNS.

**Comment by sophoah** [comment]
@rlan35 closing this case since it is also fixed for me and the 2 nodes.
