### ISSUE TITLE
Unify all logging into singleton

### ISSUE THREAD

**Issue by mikedoan** [harmony-one/harmony#287]
## Current Design

Currently, node logging uses its own object, consensus logging uses its own. Some code uses built-in log.

## Problems

Logging practice wasn't consistent over the code base. Some places use built-in logs

## Proposal

Unify all logging into singleton logging

**Comment by mikedoan** [comment]
@LeoHChen what do you think?

**Comment by LeoHChen** [comment]
Is it done or not? @mikedoan

**Comment by harmony-ek** [comment]
Nope.  Adding this to bounty.

**Comment by LeoHChen** [comment]
This is obsolete as we have moved to zerolog everything.
