### ISSUE TITLE
bad error message if querying validator information locally on a non s0 node

### ISSUE THREAD

**Issue by mindstyle85** [harmony-one/harmony#2872]
**Describe the bug**
So i tried fetching validator information via my local node since it was synced, expecting to see the information. Instead got this:

./hmy blockchain validator information one1muk6dvsezrhp9z5sqst8jfhftsnwnq7xyk25ge
commit: v374-1fa1722, error: validator address not found: one1muk6dvsezrhp9z5sqst8jfhftsnwnq7xyk25ge
check hmy cookbook for valid examples or try adding a `--help` flag

i then tried querying my own info too (my validator on this node is elected and 100% uptime):
./hmy blockchain validator information one1ck0z2umfwy73wdsjy3cleznamakxejmx5asfaf
commit: v374-1fa1722, error: validator address not found: one1ck0z2umfwy73wdsjy3cleznamakxejmx5asfaf
check hmy cookbook for valid examples or try adding a `--help` flag

it works with any of the endpoints, but since my node is synced up i would expect it to work with my local node too

**Comment by Daniel-VDM** [comment]
Could you check again? I was not able to reproduce. Note that validator RPC is only valid on a s0 node. Maybe we should change the CLI or RPC error message.

**Comment by mindstyle85** [comment]
@Daniel-VDM ah yes could be that, though i thought it could fetch it since db0 is also synced.. in that case a different error message would be best yes

**Comment by sophoah** [comment]
there was a different message in the past if we were querying a non shard 0 node for staking information, now it is no longer the case. I have the same error as @mindstyle85 when querying the RPC to shard 1
```
./hmy -n https://api.s1.os.hmny.io blockchain validator information one1r5sx7e64gefzy6dzzgaurvf3wzzjeac4ya0u29
commit: v374-1fa1722, error: validator address not found: one1r5sx7e64gefzy6dzzgaurvf3wzzjeac4ya0u29
check hmy cookbook for valid examples or try adding a `--help` flag
```
