### ISSUE TITLE
Token balance error after restarting a dormant node

### ISSUE THREAD

**Issue by MannyMcoy** [harmony-one/harmony#2882]
**Describe the bug**
So I had my GC validator offline for a while now, but i had been using the funds inside the address to fund or delegate to other validators. but yesterday, I decided to restart the validator, after bringing it back online, i noticed all my delegated funds had disappeared from my portfolio, but those i delegated to still showed the funds were delegated to them from my wallet. So two things:

1. I don't earn from the delegations
2. I can't undelegate the delegated tokens, 

**To Reproduce**
1. use a dormant validator.
2. delegate to other validators before restarting the node.
3. reset the validator.

**Expected behavior**
Token balance will not reflect the delegated tokens prior to restarting the node.

**Screenshots**
N/A

**Environment (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by sophoah** [comment]
hey @MannyMcoy can you retry checking the delegation on your portfolio page ? There were some issue with staking explorer earlier on.

**Comment by MannyMcoy** [comment]
Still the same @sophoah.

**Comment by sophoah** [comment]
i think you just test when we are currently breaking the staking explorer lol :) what is your validator address, we need to confirm what you are saying via the CLI.

**Comment by MannyMcoy** [comment]
> i think you just tested when we were breaking the staking explorer lol :) what is your validator address, we need to confirm what you are saying via the CLI.

one1fxmqtjp2ujj9597mse22kxcdf0895u7c6myp42

**Comment by sophoah** [comment]
Here is the CLI command to see your own delegation: 
```
./hmy blockchain delegation by-delegator one1fxmqtjp2ujj9597mse22kxcdf0895u7c6myp42
{
  "id": "1",
  "jsonrpc": "2.0",
  "result": [
    {
      "Undelegations": [],
      "amount": 5e+24,
      "delegator_address": "one1fxmqtjp2ujj9597mse22kxcdf0895u7c6myp42",
      "reward": 1.1905293309916991e+22,
      "validator_address": "one1fxmqtjp2ujj9597mse22kxcdf0895u7c6myp42"
    },
    {
      "Undelegations": [],
      "amount": 5e+24,
      "delegator_address": "one1fxmqtjp2ujj9597mse22kxcdf0895u7c6myp42",
      "reward": 5.39365151265143e+21,
      "validator_address": "one1w0wq5jvdgnwappudspkf7xwkwzatykudhlyw2l"
    },
    {
      "Undelegations": [],
      "amount": 2e+24,
      "delegator_address": "one1fxmqtjp2ujj9597mse22kxcdf0895u7c6myp42",
      "reward": 2.6389718922015833e+21,
      "validator_address": "one164dnpgc9dhscp0swftk0ua7jexqdzzl5twytz3"
    }
  ]
}
```

also on a dashboard when it work:
![image](https://user-images.githubusercontent.com/35721420/80305294-929dc200-87ee-11ea-8f59-e56f4247ef81.png)

**Comment by sophoah** [comment]
@rlan35 looks like @MannyMcoy hit a bug.

He made quite a number of delegations using his validator address : https://explorer.os.hmny.io/#/address/one1fxmqtjp2ujj9597mse22kxcdf0895u7c6myp42 
![image](https://user-images.githubusercontent.com/35721420/80325521-12b43e00-8868-11ea-8b75-dc85383e1769.png)

issue that we are seeing here, is that the command  ./hmy blockchain delegation by-delegator one1fxmqtjp2ujj9597mse22kxcdf0895u7c6myp42 show exactly the same thing as the dashboard (see screenshot aboave) and some of its delegation doesn't show up on it.

ie : the below validator address doesnt' appears in Manny's delegation list
![image](https://user-images.githubusercontent.com/35721420/80325711-d9c89900-8868-11ea-80a6-a6918ea5ded0.png)
```
 ./hmy blockchain delegation by-delegator one1fxmqtjp2ujj9597mse22kxcdf0895u7c6myp42
{
  "id": "1",
  "jsonrpc": "2.0",
  "result": [
    {
      "Undelegations": [],
      "amount": 5e+24,
      "delegator_address": "one1fxmqtjp2ujj9597mse22kxcdf0895u7c6myp42",
      "reward": 1.503437299104304e+22,
      "validator_address": "one1fxmqtjp2ujj9597mse22kxcdf0895u7c6myp42"
    },
    {
      "Undelegations": [],
      "amount": 5e+24,
      "delegator_address": "one1fxmqtjp2ujj9597mse22kxcdf0895u7c6myp42",
      "reward": 6.583376724084819e+21,
      "validator_address": "one1w0wq5jvdgnwappudspkf7xwkwzatykudhlyw2l"
    },
    {
      "Undelegations": [],
      "amount": 2e+24,
      "delegator_address": "one1fxmqtjp2ujj9597mse22kxcdf0895u7c6myp42",
      "reward": 3.7645024391042695e+21,
      "validator_address": "one164dnpgc9dhscp0swftk0ua7jexqdzzl5twytz3"
    }
  ]
}
```
