### ISSUE TITLE
Node crash when running a node with 4 BLS key

### ISSUE THREAD

**Issue by Chainode** [harmony-one/harmony#2906]
**Describe the bug**
A node with a new address and 4  new BLS keys was started on shard 3. After some syncing, more than 1000 blocks, the node crashed, delivering:
goroutine 14243 [sleep]:
time.Sleep(0x15d3ef79800)
        /usr/local/go/src/runtime/time.go:188 +0xba
github.com/harmony-one/harmony/shard.lookupBLSPublicKeys.func1.1(0xc009a52c30, 0x42)
        /mnt/jenkins/workspace/harmony-release/harmony/shard/shard_state.go:423 +0x30
created by github.com/harmony-one/harmony/shard.lookupBLSPublicKeys.func1
        /mnt/jenkins/workspace/harmony-release/harmony/shard/shard_state.go:422 +0x1a7

goroutine 14244 [sleep]:
time.Sleep(0x15d3ef79800)
        /usr/local/go/src/runtime/time.go:188 +0xba
github.com/harmony-one/harmony/shard.lookupBLSPublicKeys.func1.1(0xc009a53770, 0x42)
        /mnt/jenkins/workspace/harmony-release/harmony/shard/shard_state.go:423 +0x30
created by github.com/harmony-one/harmony/shard.lookupBLSPublicKeys.func1
        /mnt/jenkins/workspace/harmony-release/harmony/shard/shard_state.go:422 +0x1a7

goroutine 14245 [sleep]:
time.Sleep(0x15d3ef79800)
        /usr/local/go/src/runtime/time.go:188 +0xba
github.com/harmony-one/harmony/shard.lookupBLSPublicKeys.func1.1(0xc00978a550, 0x42)
        /mnt/jenkins/workspace/harmony-release/harmony/shard/shard_state.go:423 +0x30
created by github.com/harmony-one/harmony/shard.lookupBLSPublicKeys.func1
        /mnt/jenkins/workspace/harmony-release/harmony/shard/shard_state.go:422 +0x1a7

**To Reproduce**
1. Create new ONE address;
2. Create 4 BLS keys for shard 3;
3. start the node in tmux with ./node.sh -S -c -z -I -N staking -M

After the first crash, the DB as well as  .dht* and  md5sum.txt were deleted and the node was started again. After some sync it crashed again. 

**Node version**
Harmony (C) 2020. harmony, version v5885-v1.3.8-8-gd255efb7 (jenkins@ 2020-04-29T17:50:03+0000)

**Screenshots**
![image](https://user-images.githubusercontent.com/53407923/80718554-971def80-8afa-11ea-8971-1e3888ee5101.png)

**Environment (please complete the following information):**
 - OS: Linux Ubuntu 18.04.4 LTS 
 - System: 6 core, 16 GB RAM, 400 SSD

**Comment by Daniel-VDM** [comment]
I am unable to reproduce this error. Tested it on a fresh machine. 

I suspect that we had a bad version of the shard 0 db on the rclone. This would be an issue as the `-c` option automatically downloads the s0 db via rclone.
