### ISSUE TITLE
Potential node storage issue with recent RPC Implementation hmy_getValidatorAllInformationByBlock

### ISSUE THREAD

**Issue by sophoah** [harmony-one/harmony#2907]
**Describe the bug**
Validator all information is stored on a local DB of the node after discussion with @gupadhyaya That could potentially leads to disk space issue and eventually stopped the node.

**Comment by gupadhyaya** [comment]
`hmy_getValidatorInformationByBlock` does not add additional storage beyond what `hmy_getValidatorInformation` already has. That is, 1) validator information at each state root (on-chain), 2) validator snapshot at each epoch (off-chain), and 3) validator snapshot only latest, no history (off-chain). None of these components can be removed, hence it is safe to say that, `hmy_getValidatorInformationByBlock` does not add additional storage overhead beyond `hmy_getValidatorInformation`. @sophoah

**Comment by rlan35** [comment]
please close if this is not a issue. @gupadhyaya

**Comment by gupadhyaya** [comment]
@sophoah closing for now. if you disagree, please feel free to reopen.

**Comment by sophoah** [comment]
@gupadhyaya where is the off-chain data store on the hard disk ? can that be an issue over time since we are storing the info for each block?
