### ISSUE TITLE
[m1 upgrade] view change failed after upgrade of one node

### ISSUE THREAD

**Issue by LeoHChen** [harmony-one/harmony#2939]
[viewchange.failed.s3.log](https://github.com/harmony-one/harmony/files/4591180/viewchange.failed.s3.log)

**Describe the bug**
I upgraded one node in dryrun network shard3 using the new version. t3.dryrun.

Original version: https://github.com/harmony-one/harmony/commit/2b4abe2d365633546d12cb608d1413632a487bc8

Upgraded version: https://github.com/harmony-one/harmony/commit/1d8cf999

During the upgrade, we lost consensus which is expected, after the upgrade, can't reach consensus.  Even after I restarted the entire shard 3, still can reach consensus anymore.

Attached is the snippets of logs.

**Comment by LeoHChen** [comment]
I downgraded the node to the old version, after restart, the shard consensus resumed.

**Comment by LeoHChen** [comment]
All the logs of this shard have been uploaded to
s3://harmony-benchmark/logs/dryrun/20/05/07/10:04:21

**Comment by LeoHChen** [comment]
The node I upgraded is 52.205.127.193

**Comment by LeoHChen** [comment]
![image](https://user-images.githubusercontent.com/4513927/81359197-50e20680-908d-11ea-8245-6d066449fc87.png)

Doing upgrade now, this is the status of the dryrun network as fo now. All four shards are up and running.

**Comment by LeoHChen** [comment]
I am going to upgrade this node. `54.245.195.96`

**Comment by LeoHChen** [comment]
The code to be deployed
```
commit 3a12cd804bd6e5e1ffe6c8d1b5f98145e98b5520 (HEAD -> t3.dryrun)
Author: Leo Chen <leo@harmony.one>
Date:   Wed May 6 15:38:58 2020 -0700

    [dryrun] update sharding instance

    Signed-off-by: Leo Chen <leo@harmony.one>

```

```
$ ga -s
building cmd/harmony/main.go
# command-line-arguments
/tmp/go-link-756148360/000008.o: In function `_cgo_26061493d47f_C2func_getaddrinfo':
cgo_unix.cgo2.c:(.text+0x81): warning: Using 'getaddrinfo' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
Harmony (C) 2020. harmony, version v5923-v1.3.8-46-g3a12cd80 (lc@ 2020-05-08T01:01:42+0000)
building cmd/bootnode/main.go
# command-line-arguments
/tmp/go-link-300236258/000004.o: In function `_cgo_26061493d47f_C2func_getaddrinfo':
cgo_unix.cgo2.c:(.text+0x81): warning: Using 'getaddrinfo' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
Harmony (C) 2019. bootnode, version v5923-v1.3.8-46-g3a12cd80 (lc@ 2020-05-08T01:01:42+0000)
~/go/src/github.com/harmony-one/harmony/bin ~/go/src/github.com/harmony-one/harmony
~/go/src/github.com/harmony-one/harmony
[01:01] lc @ ip-172-31-37-52: ~/go/src/github.com/harmony-one/harmony [t3.dryrun]: Untracked
$ . ~/bin/dry.profile
WHOAMI=DRYRUN
HMY_PROFILE=dryrun
[01:03] lc @ ip-172-31-37-52: ~/go/src/github.com/harmony-one/harmony [t3.dryrun]: Untracked
$ ga -s upload
upload: bin/harmony to s3://unique-bucket-bin/DRYRUN/static/harmony
upload: bin/bootnode to s3://unique-bucket-bin/DRYRUN/static/bootnode
upload: scripts/node.sh to s3://unique-bucket-bin/DRYRUN/static/node.sh
upload: bin/md5sum.txt to s3://unique-bucket-bin/DRYRUN/static/md5sum.txt
[01:03] lc @ ip-172-31-37-52: ~/go/src/github.com/harmony-one/harmony [t3.dryrun]: Untracked
$ ga -s release
upload: bin/harmony to s3://pub.harmony.one/release/linux-x86_64/DRYRUN/static/harmony
upload: bin/bootnode to s3://pub.harmony.one/release/linux-x86_64/DRYRUN/static/bootnode
upload: scripts/node.sh to s3://pub.harmony.one/release/linux-x86_64/DRYRUN/static/node.sh
upload: bin/md5sum.txt to s3://pub.harmony.one/release/linux-x86_64/DRYRUN/static/md5sum.txt
```

**Comment by LeoHChen** [comment]
Version is:

```
Harmony (C) 2020. harmony, version v5917-v1.3.8-40-gf2f6bdb2 (lc@ 2020-05-08T01:10:19+0000)
```

**Comment by LeoHChen** [comment]
```
./restart_node.sh -p dryrun -y -t 0 -r 0 -R 0 -U -K 54.245.195.96
```

**Comment by LeoHChen** [comment]
![image](https://user-images.githubusercontent.com/4513927/81359678-abc82d80-908e-11ea-8f91-83253f04edf1.png)

Shard 3 consensus was stuck, the rolling upgrade didn't make it on one node.

**Comment by LeoHChen** [comment]
Restarting the shard 3.

**Comment by LeoHChen** [comment]
```
./run_on_shard.sh -yp dryrun 3 'tac latest/zero*.log | grep -m3 OnAnn'


--- BEGIN 54.245.195.96 stdout ---
{"level":"debug","port":"9000","ip":"54.245.195.96","myEpoch":175,"myBlock":3201194,"myViewID":3201299,"phase":0,"mode":"Normal","MsgViewID":3201298,"MsgBlockNum":3201194,"caller":"/hom
e/lc/go/src/github.com/harmony-one/harmony/consensus/validator.go:54","time":"2020-05-08T01:18:12.75373096Z","message":"[OnAnnounce] ViewID check failed"}
{"level":"debug","port":"9000","ip":"54.245.195.96","myEpoch":175,"myBlock":3201194,"myViewID":3201299,"phase":0,"mode":"Normal","MsgViewID":3201298,"MsgBlockNum":3201194,"caller":"/hom
e/lc/go/src/github.com/harmony-one/harmony/consensus/validator.go:36","time":"2020-05-08T01:18:12.753718838Z","message":"[OnAnnounce] Announce message Added"}
{"level":"debug","port":"9000","ip":"54.245.195.96","myEpoch":175,"myBlock":3201194,"myViewID":3201299,"phase":0,"mode":"Normal","leaderKey":"7ca453b4916f08e7316cb9e0a80e03336ee70d364dc
cbab09496590da8807d01cef2cd07187a7d2c946d500936449a98","caller":"/home/lc/go/src/github.com/harmony-one/harmony/consensus/checks.go:129","time":"2020-05-08T01:18:12.753698916Z","message
":"[OnAnnounce] Announce message received again"}
--- END 54.245.195.96 stdout ---
--- BEGIN 54.176.161.72 stdout ---
{"level":"info","port":"9000","ip":"54.176.161.72","blockHash":"54b937d642ed8058018f0097014a097368db8fa37b8a216cc217b3e262906256","caller":"/home/leochen/go/src/github.com/harmony-one/h
armony/consensus/consensus_v2.go:311","time":"2020-05-08T01:18:12.848585416Z","message":"[OnAnnounce] Sent Prepare Message!!"}
{"level":"info","port":"9000","ip":"54.176.161.72","blockHash":"54b937d642ed8058018f0097014a097368db8fa37b8a216cc217b3e262906256","caller":"/home/leochen/go/src/github.com/harmony-one/h
armony/consensus/consensus_v2.go:311","time":"2020-05-08T01:18:12.845259219Z","message":"[OnAnnounce] Sent Prepare Message!!"}
{"level":"info","port":"9000","ip":"54.176.161.72","blockHash":"54b937d642ed8058018f0097014a097368db8fa37b8a216cc217b3e262906256","caller":"/home/leochen/go/src/github.com/harmony-one/h
armony/consensus/consensus_v2.go:311","time":"2020-05-08T01:18:12.841813381Z","message":"[OnAnnounce] Sent Prepare Message!!"}
--- END 54.176.161.72 stdout ---

```

**Comment by LeoHChen** [comment]
I'll try to upgrade the entire shard now.

**Comment by LeoHChen** [comment]
ec2-user@ip-172-31-37-52 pipeline (master) $ cat logs/dryrun/shard3.txt | xargs -I% -P50 bash -c './restart_node.sh -yp dryrun -t 0 -r 0 -R 0 -U -K %'

**Comment by LeoHChen** [comment]
ec2-user@ip-172-31-37-52 pipeline (master) $ ./hard-reset.sh -yp dryrun 3 soft_reset

**Comment by LeoHChen** [comment]
Hit many viewID error

```
--- BEGIN 52.12.53.185 stdout ---
{"level":"debug","port":"9000","ip":"52.12.53.185","myEpoch":175,"myBlock":3201196,"myViewID":3201301,"phase":0,"mode":"Normal","MsgViewID":3201302,"MsgBlockNum":3201197,"caller":"/home/lc/go/src/github.com/harmony-one/harmony/consensus/validator.go:54","time":"2020-05-08T01:25:29.901290181Z","message":"[OnAnnounce] ViewID check failed"}
--- END 52.12.53.185 stdout ---
--- BEGIN 18.237.22.64 stdout ---
{"level":"debug","port":"9000","ip":"18.237.22.64","myEpoch":175,"myBlock":3201196,"myViewID":3201301,"phase":0,"mode":"Normal","MsgViewID":3201302,"MsgBlockNum":3201197,"caller":"/home/lc/go/src/github.com/harmony-one/harmony/consensus/validator.go:54","time":"2020-05-08T01:25:29.90118799Z","message":"[OnAnnounce] ViewID check failed"}
--- END 18.237.22.64 stdout ---
```

**Comment by LeoHChen** [comment]
All 18 nodes were updated.

![image](https://user-images.githubusercontent.com/4513927/81360290-4e34e080-9090-11ea-8434-b7058e87546d.png)

**Comment by gupadhyaya** [comment]
@LeoHChen @rlan35 I did some investigation. The shard3 leader did not broadcast cross links and was shutdown right after sending committed message that was not received by validators. When the validators restarted they did not get the last committed block hence stayed at `"myBlock":3201196`, whereas leader after coming back up sent announce for new block `"MsgBlockNum":3201197` which is why validators failed with `[OnAnnounce] ViewID check failed`. Now the question is why is crosslink epoch is shown in the watchdog as `178`? Did you set that?

**Comment by gupadhyaya** [comment]
if the crosslink epoch is expected, I don't see any problem from the logs. Tried restart again? @LeoHChen

**Comment by LeoHChen** [comment]
@gupadhyaya , the crosslink epoch was set in the PR. https://github.com/harmony-one/harmony/pull/2936/files, please take a look.

**Comment by LeoHChen** [comment]
I'll try to upgrade one node in shard1 this time. 54.212.161.175

**Comment by LeoHChen** [comment]
./restart_node.sh -p dryrun -y -t 0 -r 0 -R 0 -U -K 54.212.161.175

Before the upgrade, 

![image](https://user-images.githubusercontent.com/4513927/81371705-6404ce80-90ad-11ea-8d13-988b011c33fc.png)

**Comment by LeoHChen** [comment]
It seems okay this time. First successful rolling upgrade of one single node.

![image](https://user-images.githubusercontent.com/4513927/81371924-ef7e5f80-90ad-11ea-952d-3fb869432409.png)

**Comment by LeoHChen** [comment]
updated the 3rd one, 18.233.171.16, it stuck in view change mode now.

**Comment by LeoHChen** [comment]
![image](https://user-images.githubusercontent.com/4513927/81372897-513fc900-90b0-11ea-8558-5e19bcb334ef.png)

**Comment by LeoHChen** [comment]
restarted shard1 for shard recovery.

**Comment by LeoHChen** [comment]
![image](https://user-images.githubusercontent.com/4513927/81374512-49822380-90b4-11ea-9e9f-a4e6eec5b9e1.png)

**Comment by LeoHChen** [comment]
The viewID has been fixed in this PR. https://github.com/harmony-one/harmony/pull/2958

I'm going to update the dryrun network with latest dryrun branch including this PR. https://github.com/harmony-one/harmony/commit/a0765436fbfe14d201cc5418f48004ddf38b313b

**Comment by LeoHChen** [comment]
version to be deployed to dryrun: 
`Harmony (C) 2019. harmony, version v5111-v1.2.5-28-ga0765436 (leochen@ 2020-05-08T20:08:31+0000)`

**Comment by LeoHChen** [comment]
updated dryrun, shard0/3 still out of consensus. will do a soft reset of shard0/3.

![image](https://user-images.githubusercontent.com/4513927/81446518-edf57b80-912f-11ea-8dc2-399a8d200c2a.png)

**Comment by LeoHChen** [comment]
recovered shard0 after copied the db to all nodes.

**Comment by LeoHChen** [comment]
unable to restore shard3, with the following errors on all nodes.
```
{"level":"warn","port":"9000","ip":"54.184.153.92","error":"[VerifySeal] Unable to verify aggregated signature from last block, lastBlockNum=0x30d8ac, lastBlockHash=[156 152 23 128 117 142 205 171 175 159 98 89 227 184 162 134 109 79 185 115 111 55 231 91 148 34 216 5 86 150 208 156]","inChain":"3201196","MsgBlockNum":"3201197","caller":"/home/leochen/go/src/github.com/harmony-one/harmony/consensus/consensus_v2.go:228","time":"2020-05-08T21:31:06.660388807Z","message":"[OnAnnounce] Block content is not verified successfully"}
```

**Comment by LeoHChen** [comment]
try to use a new snapshot to recover shard3.

**Comment by LeoHChen** [comment]
used 0505 snapshot to recovery shard3, and copied db to all nodes.

**Comment by LeoHChen** [comment]
seems shard3 is recovered, restarting watchdog,

![image](https://user-images.githubusercontent.com/4513927/81453578-c6f27600-913e-11ea-904c-91d0e36b8c05.png)

**Comment by LeoHChen** [comment]
preparing t3.dryrun, since s0 has moved to 177, set prestaking to 178 now.
https://github.com/harmony-one/harmony/commit/844641e59efb9d0098ae49a6ba6e1402f4ae8aee

**Comment by LeoHChen** [comment]
The version to be released is: `Harmony (C) 2020. harmony, version v5919-v1.3.8-42-g844641e5 (lc@ 2020-05-08T22:18:11+0000)`

**Comment by LeoHChen** [comment]
rolling upgrade on shard0 / shard1 at the same time.

```
./rolling_restart_shard.sh -p dryrun -s 1 -t 90 0
./rolling_restart_shard.sh -p dryrun -s 1 -t 90 0
```

**Comment by LeoHChen** [comment]
making progress,
![image](https://user-images.githubusercontent.com/4513927/81454187-5f3d2a80-9140-11ea-8181-55058d44ade8.png)

**Comment by LeoHChen** [comment]
shard1 failed in consensus, trying to upgrade all nodes on shard1 now.

**Comment by LeoHChen** [comment]
![image](https://user-images.githubusercontent.com/4513927/81454373-f0140600-9140-11ea-9e31-43079999bade.png)

**Comment by LeoHChen** [comment]
```cat logs/dryrun/shard1.txt | xargs -I% -P50 bash -c './restart_node.sh -p dryrun -y -t 0 -r 0 -R 0 -U -K %'```

**Comment by LeoHChen** [comment]
```$ ./hard-reset.sh -p dryrun -y 1 soft_reset```

**Comment by LeoHChen** [comment]
shard1 recovered. 
![image](https://user-images.githubusercontent.com/4513927/81454561-7af50080-9141-11ea-8725-77d0d18391ff.png)

**Comment by LeoHChen** [comment]
shard1 seems doing view change now and succeeded.

![image](https://user-images.githubusercontent.com/4513927/81454678-d0c9a880-9141-11ea-91fd-1ea2c8f46ee3.png)

**Comment by LeoHChen** [comment]
shard0 rolling updated succeeded on 7 nodes and lost consensus then. I will do a batch update on shard0.

```
cat logs/dryrun/shard0.txt | xargs -I% -P50 bash -c './restart_node.sh -p dryrun -y -t 0 -r 0 -R 0 -U -K %'
```

**Comment by LeoHChen** [comment]
after a soft reset of shard0, it seems it is recovered as well. 
![image](https://user-images.githubusercontent.com/4513927/81455034-c9ef6580-9142-11ea-9e4e-3a528b9863f5.png)

**Comment by LeoHChen** [comment]
I am doing batch update on shard2/3 now.  Seems rolling upgrade will fail anyway.

**Comment by LeoHChen** [comment]
```
$ cat logs/dryrun/shard${shard}.txt | xargs -I% -P50 bash -c './restart_node.sh -p dryrun -y -t 0 -r 0 -R 0 -U -K %' && ./hard-reset.sh -yp dryrun $shard soft_reset
```

**Comment by LeoHChen** [comment]
all nodes are updated, shard 0/1/3 are doing strong, shard2 seems stuck. 
![image](https://user-images.githubusercontent.com/4513927/81455341-d45e2f00-9143-11ea-9ea2-1f59ae86fb0d.png)

**Comment by LeoHChen** [comment]
restarted shard2, leader seems missing its own prepare message.

```
$ ./run_on_shard.sh -p dryrun -y 2 'tac latest/zerolog*.log | grep -m1 OnAnn'
```

**Comment by gupadhyaya** [comment]
why shutdown after receiving commit signature? 
```
{"level":"info","port":"9000","ip":"54.191.216.77","validatorPubKey":"fdea152c37f765192363a85b9d6ab9c113b13646a90a11db5824f416e10c6ea2acec3d54912c506693b6ea55784e9792","MsgViewID":3234123,"MsgBlockNum":3234003,"numReceivedSoFar":168,"caller":"/home/leochen/go/src/github.com/harmony-one/harmony/consensus/consensus_v2.go:752","time":"2020-05-08T22:47:05.701926834Z","message":"[OnCommit] Received new commit message"}
{"level":"debug","port":"9000","ip":"54.191.216.77","caller":"/home/leochen/go/pkg/mod/github.com/rs/zerolog@v1.14.3/log.go:370","time":"2020-05-08T22:47:07.58695992Z","message":"Got terminated signal. Gracefully shutting down...\n"}
```
