### ISSUE TITLE
[m1 upgrade] view change failed for shard 3 on dryrun network

### ISSUE THREAD

**Issue by LeoHChen** [harmony-one/harmony#2945]
**Describe the bug**
I found one node upgrade doesn't work on dryrun network shard3.  So, I have decided to upgrade all nodes on shard3 using the latest t3.dryrun branch (master + a few config change)

![image](https://user-images.githubusercontent.com/4513927/81285894-0e7ce300-9015-11ea-99a8-eaa80156406f.png)

The view change failed on this shard, error messages found in the logs for all nodes.
```
{"level":"error","port":"9000","ip":"54.184.153.92","myEpoch":175,"myBlock":3202313,"myViewID":3202417,"phase":1,"mode":"Normal","error":"[VerifyNewBlock] Cannot verify shard state for the new block","caller":"/home/lc/go/src/github.com/harmony-one/harmony/consensus/checks.go:182","time":"2020-05-07T10:38:02.002246336Z","message":"[OnPrepared] Block verification failed"}
--- END 54.184.153.92 stdout ---
--- BEGIN 3.14.255.178 stdout ---
{"level":"error","port":"9000","ip":"3.14.255.178","myEpoch":175,"myBlock":3202313,"myViewID":3202417,"phase":1,"mode":"Normal","error":"[VerifyNewBlock] Cannot verify shard state for the new block","caller":"/home/lc/go/src/github.com/harmony-one/harmony/consensus/checks.go:182","time":"2020-05-07T10:38:01.813264706Z","message":"[OnPrepared] Block verification failed"}
```

All logs have been uploaded to 
s3://harmony-benchmark/logs/dryrun/20/05/07/10:46:16

**Comment by LeoHChen** [comment]
related to https://github.com/harmony-one/harmony/issues/2939

**Comment by rlan35** [comment]
Is there any successful consensus after upgrade? I calculated this block 3202313 is not a epoch block, so it shouldn't have shard state in it, which is weird that it failed on shard state verification.

**Comment by LeoHChen** [comment]
there is consensus after upgrade.  I have tried to restart the entire shard, but no consensus can be reach, I assume view change didn't work in this case.

**Comment by gupadhyaya** [comment]
@rlan35 there is no log related to https://github.com/harmony-one/harmony/commit/78eee0962d3553d58a97ce3b3c5525355d105254

**Comment by rlan35** [comment]
@LeoHChen seems  the beacon chain sync in shard 3 is not setup correctly.

{"level":"info","port":"9000","ip":"18.188.238.166","caller":"/home/lc/go/src/github.com/harmony-one/harmony/api/service/syncing/syncing.go:760","time":"2020-05-07T10:21:07.987240164Z","message":"[SYNC] Node is now IN SYNC! (isBeacon: true, ShardID: 0, otherHeight: 3226771, currentHeight: 3262629)"}

Basically the beacon chain in the shard 3 leader is likely copied from latest mainnet (3262629), while the actually dryrun beacon chain is way behind (3226771). Since at block 3262629 beacon chain is already pass staking epoch. So the leader proposed the shard state in beacon chain, but actually the beacon chain is not really doing staking thing. That's why it's messed up. 

Fixing the beacon chain data for the shards to be consistent with dryrun beacon should fix the problem.

**Comment by LeoHChen** [comment]
however, when I tested the rolling upgrade yesterday, I don't think it has passed the staking epoch though.  Let me try to get the beacon chain data back to sync anyway.

**Comment by rlan35** [comment]
The log I posted is from the time when the problem happens. That explained why there is a shard state proposed even in the middle of a epoch.

**Comment by LeoHChen** [comment]
make sense, let me bring them sync to the same height.

**Comment by LeoHChen** [comment]
after I reset the db again, and restart the shard, hit the following error on the original leader.

```
--- BEGIN 3.86.161.62 stdout ---
{"level":"warn","port":"9000","ip":"3.86.161.62","error":"key not found","caller":"/home/leochen/go/src/github.com/harmony-one/harmony/consensus/consensus_v2.go:139","time":"2020-05-07T22:20:39.335530411Z","message":"[Announce] Leader prepareBitmap SetKey failed"}
```

@gupadhyaya , since all nodes have 10 keys, how do we determine which key is used as the leader to sign the block?

**Comment by LeoHChen** [comment]
```
{"level":"warn","port":"9000","ip":"18.224.64.164","error":"[BytesToBlsPublicKey] bytes is empty","caller":"/home/leochen/go/src/github.com/harmony-one/harmony/consensus/fbft_log.go:260","time":"2020-05-07T22:43:52.646224388Z","message":"ParseViewChangeMessage failed to parse senderpubkey"}
{"level":"warn","port":"9000","ip":"18.224.64.164","caller":"/home/leochen/go/src/github.com/harmony-one/harmony/consensus/view_change.go:151","time":"2020-05-07T22:43:52.646231518Z","message":"[onViewChange] Unable To Parse Viewchange Message"}
{"level":"info","port":"9000","ip":"18.224.64.164","TotalIn":348008,"RateIn":6873.702155507352,"caller":"/home/leochen/go/src/github.com/harmony-one/harmony/node/node_handler.go:77","time":"2020-05-07T22:43:52.650122631Z","message":"[metrics][p2p] traffic in in bytes"}
{"level":"info","port":"9000","ip":"18.224.64.164","TotalIn":348008,"RateIn":6873.702155507352,"caller":"/home/leochen/go/src/github.com/harmony-one/harmony/node/node_handler.go:77","time":"2020-05-07T22:43:52.652125298Z","message":"[metrics][p2p] traffic in in bytes"}
{"level":"warn","port":"9000","ip":"18.224.64.164","error":"[BytesToBlsPublicKey] bytes is empty","caller":"/home/leochen/go/src/github.com/harmony-one/harmony/consensus/fbft_log.go:260","time":"2020-05-07T22:43:52.652286339Z","message":"ParseViewChangeMessage failed to parse senderpubkey"}
{"level":"warn","port":"9000","ip":"18.224.64.164","caller":"/home/leochen/go/src/github.com/harmony-one/harmony/consensus/view_change.go:151","time":"2020-05-07T22:43:52.652293451Z","message":"[onViewChange] Unable To Parse Viewchange Message"}

```

**Comment by gupadhyaya** [comment]
did you change any key for that node?

**Comment by LeoHChen** [comment]
no, all the nodes have the same set of keys when we launch the network, didn't change after that.

**Comment by LeoHChen** [comment]
3.86.161.62 is the orginal leader, it has the bls index 0 key, it trys to send our announcement message, and hit the error.

**Comment by LeoHChen** [comment]
This is the original dryrun branch, s3 + config change. 
![Screen Shot 2020-05-07 at 3 20 23 PM](https://user-images.githubusercontent.com/4513927/81351863-1de24780-907a-11ea-85de-35ab76043d4b.png)

**Comment by LeoHChen** [comment]
https://github.com/harmony-one/harmony/commit/7b095f06

**Comment by gupadhyaya** [comment]
> after I reset the db again, and restart the shard, hit the following error on the original leader.
> 
> ```
> --- BEGIN 3.86.161.62 stdout ---
> {"level":"warn","port":"9000","ip":"3.86.161.62","error":"key not found","caller":"/home/leochen/go/src/github.com/harmony-one/harmony/consensus/consensus_v2.go:139","time":"2020-05-07T22:20:39.335530411Z","message":"[Announce] Leader prepareBitmap SetKey failed"}
> ```
> 
> @gupadhyaya , since all nodes have 10 keys, how do we determine which key is used as the leader to sign the block?

By going over the public keys of the node and picking the matching key with consensus.LeaderPubKey. But the error happened at the place where we SubmitVote and SetKey using all keys of the leader (not only the LeaderPubKey). I suspect the keys are not loaded. Do you have logs from starting the harmony binary?

**Comment by LeoHChen** [comment]
Can you login to the node to look? from devop machine using, `node_ssh.sh 3.86.161.62`

**Comment by LeoHChen** [comment]
```
"level":"debug","port":"9000","ip":"3.86.161.62","blockNum":3220984,"numTxs":0,"crossShardReceipts":0,"caller":"/home/leochen/go/src/github.com/harmony-one/harmony/node/node_newblock.go:62","time":"2020-05-07T21:56:28.67837016Z","message":"=========Successfully Proposed New Block=========="}
{"level":"info","port":"9000","ip":"3.86.161.62","MsgBlockNum":3220984,"caller":"/home/leochen/go/src/github.com/harmony-one/harmony/consensus/consensus_v2.go:1163","time":"2020-05-07T21:56:28.678413367Z","message":"[ConsensusMainLoop] Received Proposed New Block!"}
{"level":"debug","port":"9000","ip":"3.86.161.62","numTxs":0,"startTime":"2020-05-07T21:56:28.678417964Z","publicKeys":250,"caller":"/home/leochen/go/src/github.com/harmony-one/harmony/consensus/consensus_v2.go:1248","time":"2020-05-07T21:56:28.678427827Z","message":"[ConsensusMainLoop] STARTING CONSENSUS"}
{"level":"debug","port":"9000","ip":"3.86.161.62","myEpoch":176,"myBlock":3220984,"myViewID":3221063,"phase":0,"mode":"Normal","senderKey":"ca23704be46ce9c4704681ac9c08ddc644f1858a5c28ce236e1b5d9dee67c1f5a28075b5ef089adeffa8a372c1762007","caller":"/home/leochen/go/src/github.com/harmony-one/harmony/consensus/consensus_service.go:71","time":"2020-05-07T21:56:28.678735241Z","message":"[populateMessageFields]"}
{"level":"debug","port":"9000","ip":"3.86.161.62","MsgBlockHash":"0xe7718aefbf88a48934403d3ad893eec468c32a54c11a827cc61d5c4420d00d40","MsgViewID":3221063,"MsgBlockNum":3220984,"caller":"/home/leochen/go/src/github.com/harmony-one/harmony/consensus/consensus_v2.go:130","time":"2020-05-07T21:56:28.679892023Z","message":"[Announce] Added Announce message in FPBT"}
{"level":"warn","port":"9000","ip":"3.86.161.62","error":"key not found","caller":"/home/leochen/go/src/github.com/harmony-one/harmony/consensus/consensus_v2.go:139","time":"2020-05-07T21:56:28.680859939Z","message":"[Announce] Leader prepareBitmap SetKey failed"}
```

**Comment by LeoHChen** [comment]
All the shards show the same issue, something weird.

**Comment by gupadhyaya** [comment]
I did and could not find

**Comment by LeoHChen** [comment]
when the node is started, I think it find all the 10 keys. I used `journalctl -eu harmony` to check the output.
```
May 07 22:19:38 ip-172-31-81-66.ec2.internal harmony[14440]: node.sh: public IP address autodetected: 3.86.161.62
May 07 22:19:38 ip-172-31-81-66.ec2.internal harmony[14440]: node.sh: ############### Running Harmony Process ###############
May 07 22:19:38 ip-172-31-81-66.ec2.internal harmony[14440]: node.sh: not enabling p2p trace
May 07 22:19:39 ip-172-31-81-66.ec2.internal harmony[14440]: My Genesis Account: one1q5wduaywa2sg4z559wtp79ewavzypenyp3zqr8/3c991ee15a9ffe98be4bc9bfbf0b52fd6e27f2a74a5
May 07 22:19:39 ip-172-31-81-66.ec2.internal harmony[14440]: My Genesis Account: one1wfr4azaaaqy2wtf50m4tludtfn4f0p3xk2zamg/4c5a11004797783cbed49f9f0819f5eda76a6e05323
May 07 22:19:39 ip-172-31-81-66.ec2.internal harmony[14440]: My Genesis Account: one13ar9c7czmg5j26fcpwqckj5kx5kyk02j0nqvjr/7e5f9270132f34b5c9dc6c79644bf79a790a42baa1b
May 07 22:19:39 ip-172-31-81-66.ec2.internal harmony[14440]: My Genesis Account: one19rdv5vngkdga0mpyrwtw4gvh9kv0ywwhfzgqs7/909db0568d9dfef14adc538c880ab9d5a5e994f93ac
May 07 22:19:39 ip-172-31-81-66.ec2.internal harmony[14440]: My Genesis Account: one19lp6lj7j5efhtv6f4mjwyu3c50ey84ajnfntsa/a2219d19d547f78fa04282f1e3d55d28d7b8f04ea6f
May 07 22:19:39 ip-172-31-81-66.ec2.internal harmony[14440]: My Genesis Account: one16dllsrjr04uhzsuw7raaq4cszpkt3g997yev2s/aeab90cb890d1419bd6d215e65f473b73efae07a968
May 07 22:19:39 ip-172-31-81-66.ec2.internal harmony[14440]: My Genesis Account: one1prmemfp0txxqmf0rh6an5w5hc4mmcghnlc0pn3/b5cb74f26c0fefc937fe1a6d38bc5c9571f95607f02
May 07 22:19:39 ip-172-31-81-66.ec2.internal harmony[14440]: My Genesis Account: one1gh043zc95e6mtutwy5a2zhvsxv7lnlklkj42ux/ca23704be46ce9c4704681ac9c08ddc644f1858a5c2
May 07 22:19:39 ip-172-31-81-66.ec2.internal harmony[14440]: My Genesis Account: one1tmxgqudfnzuy5y9wf7gsntwv6f768878r3q8q6/deec63912e755be51ad225d9feccc89a97dcb02b404
May 07 22:19:39 ip-172-31-81-66.ec2.internal harmony[14440]: My Genesis Account: one1g4g72jk5cumlmnkzzslzhlv9vwp85clx2mmzau/f296c15a7015503a346f542a9da87eec2fe5c06036c
```

**Comment by gupadhyaya** [comment]
@LeoHChen can you retry the flow again and see if you get the same error?

**Comment by LeoHChen** [comment]
I have fixed the issue related to the SetKey by removing all the .pass files from .hmy/blskeys directory.  The .pass files are required for master branch, but I don't know why it is breaking s3/dryrun right now.

**Comment by LeoHChen** [comment]
I created another issue to keep track of the key/pass issue. https://github.com/harmony-one/harmony/issues/2954

Will keep testing the rolling upgrade now.

**Comment by mindstyle85** [comment]
@LeoHChen close this if its not relevant anymore, will let you decide
