### ISSUE TITLE
OSTN integration test

### ISSUE THREAD

**Issue by JackyWYX** [harmony-one/harmony#2978]
Go over the integration test process on OSTN.

- [ ] Go through all test cases, including staking and normal transactions
- [ ] Go through stress test cases.

Note: OSTN are currently undergoing p2p spamming and a bunch of iterations. So the test result may vary and may not be meaningful at the moment.

**Comment by JackyWYX** [comment]
Working environment: AWS m5.Large instance, spinned up by Daniel (`ubuntu@ec2-3-228-14-216.compute-1.amazonaws.com`)

**Comment by JackyWYX** [comment]
`hmy` binary preparation:

Obtain from OSTN watchdog: 
```
binary Version: Harmony (C) 2020. hmy, version v5952-v1.3.8-75-ga7913813 (ec2-user@ 2020-05-11T23:56:57+0000)
```

Since this Linux binary version is not included in `node.sh`, obtained binary from `devops` server `devop.hmny.io`. Got binary sha256 hash:

```
$ sha256sum hmy
61e7441ee6e95262b2ed85e9bd8b06bed405be30433cf6aff2f15dbe980b950f  hmy
```

**Comment by JackyWYX** [comment]
Follow the [instruction doc](https://gist.github.com/SebastianJ/4999a1c72c12236a654ae38f7851756e#harmony-tests) to run test.

Address used: `one1jvk4aexr5u0w99sfn4h4wydtej7w9n0cg6vhnf` from [keys doc](https://docs.google.com/spreadsheets/d/1AQ3XoP4exPd1cYyqw-EBe5O-lM-Tm54so4ATyFGOaf4/edit#gid=0).

Encountered unexpected error:

```
[2020-05-12 01:25:21] WARNING - Funding account HarmonyTF_Pangaea_FundingAccount, address: one1jvk4aexr5u0w99sfn4h4wydtej7w9n0cg6vhnf wasn't funded properly in shard 1, attempting to fund it
2020/05/12 01:27:25 failed to retrieve expected balance 100.100000000000000000 for address one1jvk4aexr5u0w99sfn4h4wydtej7w9n0cg6vhnf in shard 1
```

**Comment by JackyWYX** [comment]
Issue is also proposed: https://github.com/harmony-one/harmony/issues/2983

**Comment by JackyWYX** [comment]
OSTN binary version changed. Currently Harmony (C) 2020. harmony, version v5929-v1.3.8-52-gc2f089f6 (ec2-user@ 2020-05-12T01:49:10+0000), which is able to be obtained from node.sh

```
./node.sh -d -N staking
```

**Comment by JackyWYX** [comment]
Removed old data and pull the binaries.

```
rm -rf harmony-tests && mkdir -p harmony-tests && cd harmony-tests
bash <(curl -s -S -L https://raw.githubusercontent.com/SebastianJ/harmony-tests/master/scripts/install.sh)
```

**Comment by JackyWYX** [comment]
Used the same account address yesterday, found error in output:

```
[2020-05-12 19:02:22] BALANCE - The current balance for the funding account HarmonyTF_Pangaea_FundingAccount / one1jvk4aexr5u0w99sfn4h4wydtej7w9n0cg6vhnf in shard 0 is: 0.000000000000000000
2020/05/12 19:02:22 Somehow the funding account HarmonyTF_Pangaea_FundingAccount, address: one1jvk4aexr5u0w99sfn4h4wydtej7w9n0cg6vhnf wasn't funded properly in shard 0 - please make sure that you've added funded keystore files to keys/pangaea or that you've added funded private keys to keys/pangaea/private_keys.txt
```

Use another funded account for testing/

**Comment by JackyWYX** [comment]
Found a valid address with initial fund: one1qd2huslrjxsaf9tmxvp26zcc4kmtf9h0vghmpf. Running command 

```
./tests --network staking --address one1qd2huslrjxsaf9tmxvp26zcc4kmtf9h0vghmpf
```

**Comment by JackyWYX** [comment]
Still frozen when funding different shards.

```
ubuntu@ip-172-31-14-98:~/harmony-tests$ ./tests --network staking --address one1qd2huslrjxsaf9tmxvp26zcc4kmtf9h0vghmpf

	Starting Harmony TF v0.0.1 - Network: Pangaea (API mode) - Nodes: https://api.s0.os.hmny.io, https://api.s1.os.hmny.io, https://api.s2.os.hmny.io, https://api.s3.os.hmny.io
Found a total of 164 test case files
Found a total of 0 keystore file(s) in /home/ubuntu/harmony-tests/keys/pangaea to import to the keystore
[2020-05-12 19:08:50] BALANCE - The current balance for the funding account HarmonyTF_Pangaea_FundingAccount / one1qd2huslrjxsaf9tmxvp26zcc4kmtf9h0vghmpf in shard 1 is: 0.000000000000000000
[2020-05-12 19:08:50] WARNING - Funding account HarmonyTF_Pangaea_FundingAccount, address: one1qd2huslrjxsaf9tmxvp26zcc4kmtf9h0vghmpf wasn't funded properly in shard 1, attempting to fund it
2020/05/12 19:10:54 failed to retrieve expected balance 100.100000000000000000 for address one1qd2huslrjxsaf9tmxvp26zcc4kmtf9h0vghmpf in shard 1
```

**Comment by JackyWYX** [comment]
When importing BLS keys

```
./hmy keys import-private-key 1222c1885753c9b086c2b97bb303b55e37c0362584b8a14fcd58521127d612a2
```

```
Internal nodes need to have blspass to decrypt blskey
```

The problem is that using an internal binary instead of the customed one for testing. Redownload binary from script and run again.

**Comment by JackyWYX** [comment]
Using mindstyle's pub to run tests. Test start to run

```
./tests --network staking --address one1675d7adqu9egn0ehd9fx4f6jmdjfynw3gkr48q
```

Time begin: 12:29 p.m 05/12/2020

**Comment by CryptosWolfOfAllStreets** [comment]
Hey JackyWYX results of my test running on Ubuntu 18.04 with specs: 
CPU:
16 vCore
RAM:
65536 MB
Storage:
1280 GB SSD

CSV attached :) 

[Staking TX.txt](https://github.com/harmony-one/harmony/files/4618141/Staking.TX.txt)

**Comment by CryptosWolfOfAllStreets** [comment]
summary : 

Summary:
--------------------------------------------------
Successful: 58
Failed: 30
Dismissed: 0

**Comment by JackyWYX** [comment]
Finished: 13:05 05/12/2020

```
Summary:
--------------------------------------------------
Successful: 81
Failed: 83
Dismissed: 0
--------------------------------------------------
```

Detailed logging is attached:

[test_result.txt](https://github.com/harmony-one/harmony/files/4618220/test_result.txt)

**Comment by JackyWYX** [comment]
The test result has high failure rates since a network restart happens during the test. Thus 145 tests are not meaningful. Will do the test again after OSTN gets stable.

**Comment by JackyWYX** [comment]
After p2p spamming on OSTN, OSTN becomes extremely unstable and volatile. Try testing on a more stable network PSTN just started. Closing.
