### ISSUE TITLE
MAINNET/OSTN/DRY RUN - slow txs issue

### ISSUE THREAD

**Issue by mindstyle85** [harmony-one/harmony#2983]
**Describe the bug**

after trying some tests, we found out on current OSTN, txs are slow, which might be a CLI problem, not a network problem. Staking txs are also slow, i tested manual edit validator txs which i had to bump in gas price to make it go through.

an example of regular tx being too slow (normal network this works):
[2020-05-11 18:25:51] ERROR - Account CreateValidatorSpammer_Account_9_1589214339700612192, address: one1df0qgp5hpaqh52r5cp8y6yasac779cz0ysqgqp hasn't been funded properly in shard 0. Current balance is 0.000000000000000000, expected balance is 10000.010000000000000000.

**Comment by mindstyle85** [comment]
regression tests are also bad now, might be connected: https://github.com/harmony-one/harmony/issues/2995

**Comment by sophoah** [comment]
I am doing staking test in the dry network and the average time is now 15-20s.
```
[POPS-EPOS] [2020-05-13 15:39:34,650] Adding bls key: 413b59b9366d0c6596ff1f40c1ecff85aaf9c0544fea0d928a8ecf042fccae4b8ac66a6b1d4cb331a7dd48a70ca66985 to validator: one1u6c4wer2dkm767hmjeehnwu6tqqur62gx9vqsd
[POPS-EPOS] [2020-05-13 15:39:50,080] Edit-validator transaction response: {
  "id": "18",
```
```
[POPS-EPOS] [2020-05-13 15:39:50,081] Adding bls key: 914dcf311208919ca46caa784ad59e75e0ca1633418fc980eae0045cf13d6b29378f081437b7b77bf697fe1377718d05 to validator: one1u6c4wer2dkm767hmjeehnwu6tqqur62gx9vqsd
[POPS-EPOS] [2020-05-13 15:40:10,825] Edit-validator transaction response: {
```

**Comment by JackyWYX** [comment]
On dryrun network, the block time in last 100 blocks is between 8.00 ~ 8.40 s, as expected.

100 Blocks diff

Shard 0: 8.13
Shard 1: 8.36
Shard 2: 8.06
Shard 3: 8.23

**Comment by janet-harmony** [comment]
@sophoah Can you confirm around when you were running the tests. Average block time on Shard 0 for the past ~7 hours is around 8.3 seconds.

```
Start block time: 5/13 12:48 PM UTC
End block time: 5/13 19:44 PM UTC

Start: 3227244
End: 3230244
Shard: 0
Average Block Time: 8.324441480493498
Unique block times: [(8, 2285), (9, 656), (14, 19), (10, 13), (15, 12), (13, 7), (16, 5), (17, 2)]
```

**Comment by JackyWYX** [comment]
Wrote a script and run about 100 Txns and the average processing time of processing a txn request is 8.65s

**Comment by mindstyle85** [comment]
@janet-harmony just now:

./hmy --node="https://api.s0.dry.hmny.io" staking edit-validator --validator-addr one1sgcpjc405ueglhp5udsskjxcn8crrc2lmuf35c --add-bls-key b1bfc485e0a643dd332a7780cd31e5f28a817e62804439a036a5ff4c5ab49f0976cfafc84c4777e90d19e99a118c7214 --chain-id mainnet
Enter the bls passphrase:
Try increasing the `timeout` or look for the transaction receipt with `hmy blockchain transaction-receipt <txHash>`
commit: v374-1fa1722, error: could not confirm 0x1a319bd35fdb06df7bf37d95e34dc1d0fb344554d9e843bd80ce83f3dd64a9cb even after 40 seconds

**Comment by mindstyle85** [comment]
after testing it without the rpc endpoint it works perfectly, so looks like the endpoints are slow and flaky (not all the time, its a bit random) 

@Daniel-VDM is checking it

**Comment by Daniel-VDM** [comment]
I'm actually unable to reproduce this. I'm getting tx response between 8 - 17 seconds (which is acceptable since a tx could be submitted right after a block is proposed).

If you see any slow transactions or are trying to get slow transactions, could you print me the output with the `--verbose` with the latest CLI and post it here (or link to gist)?

**Comment by mindstyle85** [comment]
@Daniel-VDM will do if i get to it, didnt manage to test dryrun a lot yet but ill try this weekend

**Comment by mindstyle85** [comment]
it seems to be caused by the endpoints randomly being flaky or falling down? Seems to be the case on mainnet too, but it is random. So closing this issue for now
