### ISSUE TITLE
[Feature] print out p2p metrics less frequently or accumulate it somewhere using a rpc call

### ISSUE THREAD

**Issue by jz0000** [harmony-one/harmony#2985]
# Problem/limitation At Hand

the p2p metrics can be bit noisy, maybe print out the log less frequent, or to add a rpc call to retrieve the accumulated metrics

**Which component?**
- [x] p2p
- [ ] consensus
- [ ] deploy script
- [ ] wallet
- [ ] explorer
- [ ] node script
- [ ] test automation
- [ ] demo app
- [ ] others ...

# Proposed Solution

# Alternatives Considered

# Additional Context

**Comment by LeoHChen** [comment]
set debug log level instead of info
