### ISSUE TITLE
[dryrun] hard-reset dryrun network

### ISSUE THREAD

**Issue by LeoHChen** [harmony-one/harmony#2988]
# Problem/limitation At Hand

We need to reset the dryrun network to s3, so that we can redo the upgrade/pre-staking/staking test.

The gist I used to reset the dryrun network.
https://gist.github.com/LeoHChen/3e4fecc39b4225e720a85510a26c4e4b

We need to 
- [x] build latest dryrun branch
- [x] update all dryrun nodes using latest s3 build 
- [x] reset the mainnet DB snapshot on all shards
- [x] ensure all shards on dryrun network reached consensus using mainnet DB snapshots
- [x] batch upgrade nodes in dryrun network to the latest t3.dryrun branch
- [x] one-hour per epoch
- [x] fund the faucet account
- [x] fund all team and p-ops accounts
- [x] a short gist about how to create validator, start node on dryrun network
- [x] setup dryrun network snapshot on 4 shards (once an hour)

**Comment by LeoHChen** [comment]
force updated dryrun branch on top of latest s3 branch.
https://github.com/harmony-one/harmony/tree/dryrun
https://github.com/harmony-one/harmony/commit/041f71d16296248cbcb59d73270df45fad2fab71

**Comment by LeoHChen** [comment]
Version to be reset: `Harmony (C) 2019. harmony, version v5113-v1.2.7-3-g041f71d1 (lc@ 2020-05-12T19:40:03+0000)`

**Comment by LeoHChen** [comment]
PR to update specific DB: https://github.com/harmony-one/experiment-deploy/pull/324

**Comment by LeoHChen** [comment]
PR to do upgrade during soft_reset: https://github.com/harmony-one/experiment-deploy/pull/325

**Comment by LeoHChen** [comment]
in `devop` machine, 
```
cd ~/go/src/github.com/harmony-one/experiment-deploy/pipeline
. ~/bin/dry.profile
./hard-reset.sh -Uyp dryrun all soft_reset
```

All nodes in the dryrun network are updated.
![image](https://user-images.githubusercontent.com/4513927/81740483-e1d02d80-9451-11ea-8517-8346ca624c73.png)

**Comment by rlan35** [comment]
Updated t3.dryrun with latest master without the p2p throttling change, which is not stable yet.

https://github.com/harmony-one/harmony/pull/2990

**Comment by LeoHChen** [comment]
resetting the DB snapshots on all shards.

```
$ ./run_on_shard.sh -p dryrun -Ty 0 'curl -sSfL https://haochen-harmony-pub.s3.amazonaws.com/pub/db_snapshot/install.sh | bash -s main.s0.0501.json'
$ ./run_on_shard.sh -p dryrun -Ty 1 'curl -sSfL https://haochen-harmony-pub.s3.amazonaws.com/pub/db_snapshot/install.sh | bash -s main.s0.0501.json'
$ ./run_on_shard.sh -p dryrun -Ty 2 'curl -sSfL https://haochen-harmony-pub.s3.amazonaws.com/pub/db_snapshot/install.sh | bash -s main.s0.0501.json'
$ ./run_on_shard.sh -p dryrun -Ty 3 'curl -sSfL https://haochen-harmony-pub.s3.amazonaws.com/pub/db_snapshot/install.sh | bash -s main.s0.0501.json'
```

**Comment by LeoHChen** [comment]
resetting DB snapshots on shard1/2/3.

```
./run_on_shard.sh -p dryrun -Ty 1 'curl -sSfL https://haochen-harmony-pub.s3.amazonaws.com/pub/db_snapshot/install.sh | bash -s main.s1.0504.json'
./run_on_shard.sh -p dryrun -Ty 2 'curl -sSfL https://haochen-harmony-pub.s3.amazonaws.com/pub/db_snapshot/install.sh | bash -s main.s2.0505.json'
./run_on_shard.sh -p dryrun -Ty 3 'curl -sSfL https://haochen-harmony-pub.s3.amazonaws.com/pub/db_snapshot/install.sh | bash -s main.s3.0505.json'
```

**Comment by LeoHChen** [comment]
Restart all shards.

```
$ ./hard-reset.sh -p dryrun -y all soft_reset
```

**Comment by LeoHChen** [comment]
didn't reach consensus on all shards, looking

![image](https://user-images.githubusercontent.com/4513927/81746707-cc600100-945b-11ea-8cc0-5fb6b79d62b1.png)

**Comment by LeoHChen** [comment]
After checking the logs, found a known bug, https://github.com/harmony-one/harmony/issues/2954

I have to remove all the .pass files from .hmy/blskeys directory.
```
for s in {0..3}; do ./run_on_shard.sh -p dryrun -Ty ${s} 'sudo systemctl stop harmony; rm .hmy/blskeys/*.pass; rm -rf latest/*.gz'; done
```

**Comment by LeoHChen** [comment]
Soft reset all the shards on dryrun network and consensus reached!

![image](https://user-images.githubusercontent.com/4513927/81747394-e3532300-945c-11ea-96e7-656aef3fd04e.png)

**Comment by LeoHChen** [comment]
Shard0 is in the middle of epoch 176, the next epoch is expected 15 hours later. Current ETA is `Wed May 13 05:41:45 PDT`

**Comment by LeoHChen** [comment]
Need to try another shard0 snapshot, hopefully, close to the end of one epoch.

**Comment by LeoHChen** [comment]
We can also do a hard fork of the epoch calculation to move to the next epoch faster on the dryrun network.  @rlan35 is working on a PR for the fork on t3.dryrun.
https://github.com/harmony-one/harmony/pull/2992

**Comment by LeoHChen** [comment]
build latest t3.dryrun branch, the version to be updated:
`Harmony (C) 2020. harmony, version v5939-v1.3.8-62-ga54a8f37 (lc@ 2020-05-12T22:11:48+0000)`

**Comment by LeoHChen** [comment]
![image](https://user-images.githubusercontent.com/4513927/81750871-2d3f0780-9463-11ea-9a4b-e20dba4fa662.png)

Ready do a batch update, before the update.

**Comment by LeoHChen** [comment]
```
./hard-reset.sh -yp dryrun -U all soft_reset
```
All nodes updated,
![image](https://user-images.githubusercontent.com/4513927/81750996-6e371c00-9463-11ea-9d5c-4ce343fd3837.png)

**Comment by LeoHChen** [comment]
Seems all shards are making progress, the batch upgrade is succeeded.

![image](https://user-images.githubusercontent.com/4513927/81751100-9c1c6080-9463-11ea-9e34-edf26181fca2.png)

**Comment by LeoHChen** [comment]
The expected pre-staking epoch should start from block 3221570 on shard0, which is around 3:50pm PDT.

**Comment by LeoHChen** [comment]
I am funding the faucet account using block rewards.
https://explorer.ps.hmny.io/#/address/one1zksj3evekayy90xt4psrz8h6j2v3hla4qwz4ur

**Comment by LeoHChen** [comment]
The rclone snapshot can be used to setup validator nodes.
https://gist.github.com/LeoHChen/8ec00763e4203b155f1c1b5ff9795fab
```
## rclone setup/installation, rclone.conf
https://nodes.harmony.one/foundational-node-playbook/fast-state-syncing/fast-state-syncing-using-rclone
Noted for all non-beacon shard, the node need to sync both shard0 and their own shard's db.

## shard0
rclone sync mainnet:pub.harmony.one/mainnet.min/snapshot.20200501/harmony_db_0 harmony_db_0

## shard1
rclone sync mainnet:pub.harmony.one/mainnet.min/snapshot.20200504/harmony_db_1 harmony_db_1

## shard2
rclone sync mainnet:pub.harmony.one/mainnet.min/snapshot.20200505/harmony_db_2 harmony_db_2

## shard3
rclone sync mainnet:pub.harmony.one/mainnet.min/snapshot.20200505/harmony_db_3 harmony_db_3
```

**Comment by LeoHChen** [comment]
Upgrade dryrun network with the latest t3.dryrun branch.

```
commit 0bbdc4cf979f41b3953ccf04a493c24f10d2877d (HEAD -> t3.dryrun, origin/t3.dryrun)
Author: Rongjian Lan <rongjian.lan@gmail.com>
Date:   Tue May 12 16:09:41 2020 -0700

    fix crash on parsed block (#2994)
```

**Comment by LeoHChen** [comment]
The version to be updated.
`
Harmony (C) 2020. harmony, version v5940-v1.3.8-63-g0bbdc4cf (lc@ 2020-05-12T23:11:53+0000)
`

**Comment by LeoHChen** [comment]
Before the upgrade, 
![image](https://user-images.githubusercontent.com/4513927/81754926-32ed1b00-946c-11ea-8839-6b1182da4249.png)

**Comment by LeoHChen** [comment]
after the upgrade,

![image](https://user-images.githubusercontent.com/4513927/81754958-4dbf8f80-946c-11ea-8b6a-c6724dc3d220.png)

**Comment by LeoHChen** [comment]
https://gist.github.com/Daniel-VDM/788647bb71284aa6ac0f78b8059fd139

**Comment by LeoHChen** [comment]
@Daniel-VDM , please help do a batch update of dryrun network with this new change merged in t3.dryrun branch. https://github.com/harmony-one/harmony/pull/2999

**Comment by LeoHChen** [comment]
![image](https://user-images.githubusercontent.com/4513927/81784216-60a88300-94b1-11ea-9c94-b234c49544a6.png)

updated dryrun network

**Comment by LeoHChen** [comment]
https://s3.console.aws.amazon.com/s3/buckets/pub.harmony.one/dryrun/?region=us-west-1

**Comment by denniswon** [comment]
@LeoHChen For drynet explorer firestore db, it is too big to be cleared using hard_reset script (that uses firebase cli to delete all collections at once). Just on last OSTN which was only ~100K blocks, the command to delete all collections at once failed, and needs each collections to be deleted separately. But bigger concern is that even for each collection deletion, for ~100K blocks worth of explorer data on firestore, it took > 4 hours to delete.

**Comment by LeoHChen** [comment]
@denniswon , we need to support the switch to a new firestore db in this case, using a different name?

**Comment by LeoHChen** [comment]
@denniswon , let's discuss the firestore db reset issue in another ticket.  this ticket is closed on hard-reset of dryrun network yesterday.
