### ISSUE TITLE
Dryrun integration test

### ISSUE THREAD

**Issue by JackyWYX** [harmony-one/harmony#2995]
Since the OSTN is currently under heavy iteration, launch tests on a more stable network Dryrun. Need t go over the following integration test process.

  - [x] Go through all test cases, including staking and normal transactions
  - [ ] Go through stress test cases.

The current dryrun code covers the latest master code - Edgar's p2p stuff.

**Comment by JackyWYX** [comment]
Integration testing scripts currently cannot run with dryrun network config. Need to coordinate with Seb for tests program upgrades.

**Comment by JackyWYX** [comment]
From @mindstyle85 get the running command. Starting to run tests on Dryrun network.

**Comment by JackyWYX** [comment]
Time start: 17:45 05/12/2020
Starting command: `./tests --network dryrun --address one1675d7adqu9egn0ehd9fx4f6jmdjfynw3gkr48q --export csv | tee test_dryrun.txt`

**Comment by mindstyle85** [comment]
ran regular tx/staking tx tests too, results arent good:

Summary:
--------------------------------------------------
Successful: 39
Failed: 37
Dismissed: 0
--------------------------------------------------

Executed test cases:
--------------------------------------------------
Testcase CAS1: failed
Testcase CAS2: failed
Testcase CAS3: failed
Testcase CAS4: success
Testcase CAS5: failed
Testcase CAS6: success
Testcase CAS7: failed
Testcase CAS8: failed
Testcase CAS9: failed
Testcase CAS10: failed
Testcase CAS11: success
Testcase CAS12: failed
Testcase CAS13: success
Testcase CAS14: failed
Testcase CAS15: failed
Testcase CAS16: failed
Testcase CAS17: failed
Testcase CAS18: success
Testcase CAS19: failed
Testcase CAS20: success
Testcase CAS21: failed
Testcase CAS22: failed
Testcase CAS23: failed
Testcase CAS24: failed
Testcase CAS25: success
Testcase CAS26: failed
Testcase CAS27: success
Testcase CAS28: failed
Testcase CBS1: success
Testcase CBS2: success
Testcase CBS3: success
Testcase CBS4: success
Testcase CBS5: success
Testcase CBS6: success
Testcase CBS7: success
Testcase CBS8: failed
Testcase CBS9: failed
Testcase CBS10: failed
Testcase CBS11: success
Testcase CBS12: failed
Testcase CBS13: success
Testcase CBS14: failed
Testcase CBS15: success
Testcase CBS16: success
Testcase CBS17: success
Testcase CBS18: success
Testcase CBS19: success
Testcase CBS20: success
Testcase CBS21: success
Testcase CBS22: failed
Testcase CBS23: failed
Testcase CBS24: failed
Testcase CBS25: success
Testcase CBS26: failed
Testcase CBS27: success
Testcase CBS28: failed
Testcase SAS1: failed
Testcase SAS2: failed
Testcase SAS3: failed
Testcase SAS4: failed
Testcase SAS5: success
Testcase SAS6: failed
Testcase SAS7: success
Testcase SAS8: failed
Testcase SAS9: success
Testcase SAS10: failed
Testcase SBS1: success
Testcase SBS2: success
Testcase SBS3: success
Testcase SBS4: success
Testcase SBS5: success
Testcase SBS6: success
Testcase SBS7: success
Testcase SBS8: success
Testcase SBS9: success
Testcase SBS10: success

link to test cases sheet: https://docs.google.com/spreadsheets/d/1cH5cwmVc6RvfUe-KKs7Zyy4wdc4bQlGz2W8Ehv3q5q8/edit#gid=1950584711

**Comment by JackyWYX** [comment]
Finish time 18:42 05/12/2020

## Summary:

Successful: 134
Failed: 30
Dismissed: 0

## Test cases

Testcase D1: failed
Testcase D2: success
Testcase D3: success
Testcase D4: success
Testcase D5: success
Testcase D6: success
Testcase D10: success
Testcase U1: failed
Testcase U3: success
Testcase U4: success
Testcase U5: success
Testcase U9: success
Testcase CV1: failed
Testcase CV2: success
Testcase CV3: success
Testcase CV4: success
Testcase CV5: success
Testcase CV6: success
Testcase CV7: success
Testcase CV8: success
Testcase CV9: failed
Testcase CV10: failed
Testcase CV11: failed
Testcase CV12: failed
Testcase CV13: failed
Testcase CV14: failed
Testcase CV15: success
Testcase CV16: success
Testcase CV17: failed
Testcase CV18: failed
Testcase CV19: failed
Testcase CV20: failed
Testcase CV21: failed
Testcase CV22: failed
Testcase CV23: success
Testcase CV24: success
Testcase CV25: success
Testcase CV26: success
Testcase CV27: success
Testcase CV28: success
Testcase CV29: failed
Testcase CV30: failed
Testcase CV31: success
Testcase CV32: success
Testcase CV33: success
Testcase CV34: success
Testcase CV35: success
Testcase CV36: success
Testcase CV37: success
Testcase CV38: success
Testcase CV39: success
Testcase CV40: failed
Testcase CV41: success
Testcase CV42: success
Testcase CV43: success
Testcase CV44: success
Testcase CV45: success
Testcase CV46: success
Testcase CV47: success
Testcase EV1: failed
Testcase EV2: failed
Testcase EV3: failed
Testcase EV4: failed
Testcase EV5: failed
Testcase EV6: failed
Testcase EV7: success
Testcase EV8: success
Testcase EV9: success
Testcase EV10: success
Testcase EV11: success
Testcase EV12: failed
Testcase EV13: success
Testcase EV14: failed
Testcase EV15: success
Testcase EV17: success
Testcase EV18: success
Testcase EV19: failed
Testcase EV20: success
Testcase EV21: success
Testcase EV22: success
Testcase EV23: failed
Testcase EV24: success
Testcase EV25: success
Testcase EV26: failed
Testcase EV27: success
Testcase EV28: failed
Testcase EV29: success
Testcase EV30: success
Testcase CAS1: success
Testcase CAS2: success
Testcase CAS3: success
Testcase CAS4: success
Testcase CAS5: success
Testcase CAS6: success
Testcase CAS7: success
Testcase CAS8: success
Testcase CAS9: success
Testcase CAS10: success
Testcase CAS11: success
Testcase CAS12: success
Testcase CAS13: success
Testcase CAS14: success
Testcase CAS15: success
Testcase CAS16: success
Testcase CAS17: success
Testcase CAS18: success
Testcase CAS19: success
Testcase CAS20: success
Testcase CAS21: success
Testcase CAS22: success
Testcase CAS23: success
Testcase CAS24: success
Testcase CAS25: success
Testcase CAS26: success
Testcase CAS27: success
Testcase CAS28: success
Testcase CBS1: success
Testcase CBS2: success
Testcase CBS3: success
Testcase CBS4: success
Testcase CBS5: success
Testcase CBS6: success
Testcase CBS7: success
Testcase CBS8: success
Testcase CBS9: success
Testcase CBS10: success
Testcase CBS11: success
Testcase CBS12: success
Testcase CBS13: success
Testcase CBS14: success
Testcase CBS15: success
Testcase CBS16: success
Testcase CBS17: success
Testcase CBS18: success
Testcase CBS19: success
Testcase CBS20: success
Testcase CBS21: success
Testcase CBS22: success
Testcase CBS23: success
Testcase CBS24: success
Testcase CBS25: success
Testcase CBS26: success
Testcase CBS27: success
Testcase CBS28: success
Testcase SAS1: success
Testcase SAS2: success
Testcase SAS3: success
Testcase SAS4: success
Testcase SAS5: success
Testcase SAS6: success
Testcase SAS7: success
Testcase SAS8: success
Testcase SAS9: success
Testcase SAS10: success
Testcase SBS1: success
Testcase SBS2: success
Testcase SBS3: success
Testcase SBS4: success
Testcase SBS5: success
Testcase SBS6: success
Testcase SBS7: success
Testcase SBS8: success
Testcase SBS9: success
Testcase SBS10: success

## Script detailed output
 
[test_dryrun.txt](https://github.com/harmony-one/harmony/files/4619342/test_dryrun.txt)

**Comment by JackyWYX** [comment]
@mindstyle85 My results seems to be quite different from yours. Are you also running at Dryrun?

**Comment by JackyWYX** [comment]
After looking into the test output, it seems that most transaction errors are given as follows:

```
[2020-05-13 01:08:03] ERROR - the required funding amount 300000000000000000000.300000000000000000 is more than what is currently available (97.799042995999999996) in the funding account HarmonyTF_Dryrun_FundingAccount, address: one1675d7adqu9egn0ehd9fx4f6jmdjfynw3gkr48q 
```

which means there is not enough balance in the account. Will run the tests again when some initial funds are added to the testing account in Dryrun network.

**Comment by JackyWYX** [comment]
Got 500K in account `one1675d7adqu9egn0ehd9fx4f6jmdjfynw3gkr48q`. Restart the test

### Start time

19:10 05/12/2020

### Start command 

```
./tests --network dryrun --address one1675d7adqu9egn0ehd9fx4f6jmdjfynw3gkr48q --export csv | tee test_dryrun.txt
```

Waiting for regression test to finish

**Comment by JackyWYX** [comment]
## Duration

Time start  19:10
Time end:  21:06
Duration:   1 hour 54 minutes

## Summary

Successful: 162
Failed: 2
Dismissed: 0

## Tests

Testcase D1: failed
Testcase D2: success
Testcase D3: success
Testcase D4: success
Testcase D5: success
Testcase D6: success
Testcase D10: success
Testcase U1: failed
Testcase U3: success
Testcase U4: success
Testcase U5: success
Testcase U9: success
Testcase CV1: success
Testcase CV2: success
Testcase CV3: success
Testcase CV4: success
Testcase CV5: success
Testcase CV6: success
Testcase CV7: success
Testcase CV8: success
Testcase CV9: success
Testcase CV10: success
Testcase CV11: success
Testcase CV12: success
Testcase CV13: success
Testcase CV14: success
Testcase CV15: success
Testcase CV16: success
Testcase CV17: success
Testcase CV18: success
Testcase CV19: success
Testcase CV20: success
Testcase CV21: success
Testcase CV22: success
Testcase CV23: success
Testcase CV24: success
Testcase CV25: success
Testcase CV26: success
Testcase CV27: success
Testcase CV28: success
Testcase CV29: success
Testcase CV30: success
Testcase CV31: success
Testcase CV32: success
Testcase CV33: success
Testcase CV34: success
Testcase CV35: success
Testcase CV36: success
Testcase CV37: success
Testcase CV38: success
Testcase CV39: success
Testcase CV40: success
Testcase CV41: success
Testcase CV42: success
Testcase CV43: success
Testcase CV44: success
Testcase CV45: success
Testcase CV46: success
Testcase CV47: success
Testcase EV1: success
Testcase EV2: success
Testcase EV3: success
Testcase EV4: success
Testcase EV5: success
Testcase EV6: success
Testcase EV7: success
Testcase EV8: success
Testcase EV9: success
Testcase EV10: success
Testcase EV11: success
Testcase EV12: success
Testcase EV13: success
Testcase EV14: success
Testcase EV15: success
Testcase EV17: success
Testcase EV18: success
Testcase EV19: success
Testcase EV20: success
Testcase EV21: success
Testcase EV22: success
Testcase EV23: success
Testcase EV24: success
Testcase EV25: success
Testcase EV26: success
Testcase EV27: success
Testcase EV28: success
Testcase EV29: success
Testcase EV30: success
Testcase CAS1: success
Testcase CAS2: success
Testcase CAS3: success
Testcase CAS4: success
Testcase CAS5: success
Testcase CAS6: success
Testcase CAS7: success
Testcase CAS8: success
Testcase CAS9: success
Testcase CAS10: success
Testcase CAS11: success
Testcase CAS12: success
Testcase CAS13: success
Testcase CAS14: success
Testcase CAS15: success
Testcase CAS16: success
Testcase CAS17: success
Testcase CAS18: success
Testcase CAS19: success
Testcase CAS20: success
Testcase CAS21: success
Testcase CAS22: success
Testcase CAS23: success
Testcase CAS24: success
Testcase CAS25: success
Testcase CAS26: success
Testcase CAS27: success
Testcase CAS28: success
Testcase CBS1: success
Testcase CBS2: success
Testcase CBS3: success
Testcase CBS4: success
Testcase CBS5: success
Testcase CBS6: success
Testcase CBS7: success
Testcase CBS8: success
Testcase CBS9: success
Testcase CBS10: success
Testcase CBS11: success
Testcase CBS12: success
Testcase CBS13: success
Testcase CBS14: success
Testcase CBS15: success
Testcase CBS16: success
Testcase CBS17: success
Testcase CBS18: success
Testcase CBS19: success
Testcase CBS20: success
Testcase CBS21: success
Testcase CBS22: success
Testcase CBS23: success
Testcase CBS24: success
Testcase CBS25: success
Testcase CBS26: success
Testcase CBS27: success
Testcase CBS28: success
Testcase SAS1: success
Testcase SAS2: success
Testcase SAS3: success
Testcase SAS4: success
Testcase SAS5: success
Testcase SAS6: success
Testcase SAS7: success
Testcase SAS8: success
Testcase SAS9: success
Testcase SAS10: success
Testcase SBS1: success
Testcase SBS2: success
Testcase SBS3: success
Testcase SBS4: success
Testcase SBS5: success
Testcase SBS6: success
Testcase SBS7: success
Testcase SBS8: success
Testcase SBS9: success
Testcase SBS10: success

## Report 
[test_dryrun.txt](https://github.com/harmony-one/harmony/files/4619759/test_dryrun.txt)

**Comment by JackyWYX** [comment]
Run stress network with the following command:

```
./stress delegations generate --from one1675d7adqu9egn0ehd9fx4f6jmdjfynw3gkr48q --count 100000000 --concurrency 5 --amount 1000 --network dryrun
```

Time start: 22:50

**Comment by JackyWYX** [comment]
After the initial run, found that there is not enough balance in the account. Giving error like following:

```
[2020-05-13 05:52:18] ERROR - Available funding amount in the funding account learn-imported, address: one1675d7adqu9egn0ehd9fx4f6jmdjfynw3gkr48q is too low! Account has a balance of 479.132014733781305718, required balance is 47000.470000000000000000
[2020-05-13 05:52:18] ERROR - Error ocurred while trying to generate and fund a new account - error: the balance in the funding account is too low
```

**Comment by mindstyle85** [comment]
> ## Duration
> Time start 19:10
> Time end: 21:06
> Duration: 1 hour 54 minutes
> 
> ## Summary
> Successful: 162
> Failed: 2
> Dismissed: 0
> 
> ## Tests Results
> (Also added to [google docs](https://docs.google.com/spreadsheets/d/1cH5cwmVc6RvfUe-KKs7Zyy4wdc4bQlGz2W8Ehv3q5q8/edit?pli=1#gid=701383503))
> 
> Testcase D1: failed
> Testcase D2: success
> Testcase D3: success
> Testcase D4: success
> Testcase D5: success
> Testcase D6: success
> Testcase D10: success
> Testcase U1: failed
> Testcase U3: success
> Testcase U4: success
> Testcase U5: success
> Testcase U9: success
> Testcase CV1: success
> Testcase CV2: success
> Testcase CV3: success
> Testcase CV4: success
> Testcase CV5: success
> Testcase CV6: success
> Testcase CV7: success
> Testcase CV8: success
> Testcase CV9: success
> Testcase CV10: success
> Testcase CV11: success
> Testcase CV12: success
> Testcase CV13: success
> Testcase CV14: success
> Testcase CV15: success
> Testcase CV16: success
> Testcase CV17: success
> Testcase CV18: success
> Testcase CV19: success
> Testcase CV20: success
> Testcase CV21: success
> Testcase CV22: success
> Testcase CV23: success
> Testcase CV24: success
> Testcase CV25: success
> Testcase CV26: success
> Testcase CV27: success
> Testcase CV28: success
> Testcase CV29: success
> Testcase CV30: success
> Testcase CV31: success
> Testcase CV32: success
> Testcase CV33: success
> Testcase CV34: success
> Testcase CV35: success
> Testcase CV36: success
> Testcase CV37: success
> Testcase CV38: success
> Testcase CV39: success
> Testcase CV40: success
> Testcase CV41: success
> Testcase CV42: success
> Testcase CV43: success
> Testcase CV44: success
> Testcase CV45: success
> Testcase CV46: success
> Testcase CV47: success
> Testcase EV1: success
> Testcase EV2: success
> Testcase EV3: success
> Testcase EV4: success
> Testcase EV5: success
> Testcase EV6: success
> Testcase EV7: success
> Testcase EV8: success
> Testcase EV9: success
> Testcase EV10: success
> Testcase EV11: success
> Testcase EV12: success
> Testcase EV13: success
> Testcase EV14: success
> Testcase EV15: success
> Testcase EV17: success
> Testcase EV18: success
> Testcase EV19: success
> Testcase EV20: success
> Testcase EV21: success
> Testcase EV22: success
> Testcase EV23: success
> Testcase EV24: success
> Testcase EV25: success
> Testcase EV26: success
> Testcase EV27: success
> Testcase EV28: success
> Testcase EV29: success
> Testcase EV30: success
> Testcase CAS1: success
> Testcase CAS2: success
> Testcase CAS3: success
> Testcase CAS4: success
> Testcase CAS5: success
> Testcase CAS6: success
> Testcase CAS7: success
> Testcase CAS8: success
> Testcase CAS9: success
> Testcase CAS10: success
> Testcase CAS11: success
> Testcase CAS12: success
> Testcase CAS13: success
> Testcase CAS14: success
> Testcase CAS15: success
> Testcase CAS16: success
> Testcase CAS17: success
> Testcase CAS18: success
> Testcase CAS19: success
> Testcase CAS20: success
> Testcase CAS21: success
> Testcase CAS22: success
> Testcase CAS23: success
> Testcase CAS24: success
> Testcase CAS25: success
> Testcase CAS26: success
> Testcase CAS27: success
> Testcase CAS28: success
> Testcase CBS1: success
> Testcase CBS2: success
> Testcase CBS3: success
> Testcase CBS4: success
> Testcase CBS5: success
> Testcase CBS6: success
> Testcase CBS7: success
> Testcase CBS8: success
> Testcase CBS9: success
> Testcase CBS10: success
> Testcase CBS11: success
> Testcase CBS12: success
> Testcase CBS13: success
> Testcase CBS14: success
> Testcase CBS15: success
> Testcase CBS16: success
> Testcase CBS17: success
> Testcase CBS18: success
> Testcase CBS19: success
> Testcase CBS20: success
> Testcase CBS21: success
> Testcase CBS22: success
> Testcase CBS23: success
> Testcase CBS24: success
> Testcase CBS25: success
> Testcase CBS26: success
> Testcase CBS27: success
> Testcase CBS28: success
> Testcase SAS1: success
> Testcase SAS2: success
> Testcase SAS3: success
> Testcase SAS4: success
> Testcase SAS5: success
> Testcase SAS6: success
> Testcase SAS7: success
> Testcase SAS8: success
> Testcase SAS9: success
> Testcase SAS10: success
> Testcase SBS1: success
> Testcase SBS2: success
> Testcase SBS3: success
> Testcase SBS4: success
> Testcase SBS5: success
> Testcase SBS6: success
> Testcase SBS7: success
> Testcase SBS8: success
> Testcase SBS9: success
> Testcase SBS10: success
> 
> ## Report
> [test_dryrun.txt](https://github.com/harmony-one/harmony/files/4619759/test_dryrun.txt)

the two that failed here seem to fail by default, i think those 2 are are a script problem.. so looks good!

**Comment by JackyWYX** [comment]
Mainnet already launched. No need for stress tests. Closing
