### ISSUE TITLE
[dryrun] hard-reset dryrun network to re-test prestaking epoch

### ISSUE THREAD

**Issue by LeoHChen** [harmony-one/harmony#3005]
We need to reset the dryrun network to `dryrun` branch so that we can redo the upgrade/pre-staking/staking test.

We need to 
- [x] build/upload/release the dryrun branch
- [x] update all dryrun nodes using latest dryrun branch build 
- [ ] reset the mainnet DB snapshot on all shards
- [ ] ensure all shards on dryrun network reached consensus using mainnet DB snapshots
- [ ] batch upgrade nodes in dryrun network to the latest t3.dryrun branch
- [ ] one-hour per epoch
- [ ] fund the faucet account
- [ ] fund all team and p-ops accounts
- [x] a short gist about how to create validator, start node on dryrun network
- [x] setup dryrun network snapshot on 4 shards (once an hour)
- [ ] team/p-ops create validators in pre-staking epoch and test staking dashboard

**Comment by LeoHChen** [comment]
* build/upload/release dryrun branch binary

* remove all the .pass files, prepare for downgrade
```bash
for s in {0..3}; do
 ./run_on_shard.sh -p dryrun -Ty ${s} 'sudo systemctl stop harmony; rm .hmy/blskeys/*.pass; rm -rf latest/*.gz';
done
```

* reset harmony binary
```bash
cd ~/go/src/github.com/harmony-one/experiment-deploy/pipeline
. ~/bin/dry.profile
./hard-reset.sh -Uyp dryrun all soft_reset
```

* hard-reset mainnet db snapshot on shard0
```bash
for s in {0..3}; do
 ./run_on_shard.sh -p dryrun -Ty $s 'curl -sSfL https://haochen-harmony-pub.s3.amazonaws.com/pub/db_snapshot/install.sh | bash -s main.s0.0501.json'
done
```

* hard-reset mainnet db snapshot on shard1/2/3
```bash
./run_on_shard.sh -p dryrun -Ty 1 'curl -sSfL https://haochen-harmony-pub.s3.amazonaws.com/pub/db_snapshot/install.sh | bash -s main.s1.0504.json'
./run_on_shard.sh -p dryrun -Ty 2 'curl -sSfL https://haochen-harmony-pub.s3.amazonaws.com/pub/db_snapshot/install.sh | bash -s main.s2.0505.json'
./run_on_shard.sh -p dryrun -Ty 3 'curl -sSfL https://haochen-harmony-pub.s3.amazonaws.com/pub/db_snapshot/install.sh | bash -s main.s3.0505.json'
```

* restart all shards
```bash
./hard-reset.sh -p dryrun -y all soft_reset
```

**Comment by LeoHChen** [comment]
Previous hard-reset process is tracked in this ticket. https://github.com/harmony-one/harmony/issues/2988

**Comment by rlan35** [comment]
version built:

`Harmony (C) 2020. harmony, version v5943-v1.3.8-66-g08800f8e (ec2-user@ 2020-05-13T23:20:09+0000)`

**Comment by rlan35** [comment]
Binary uploaded to all nodes.

**Comment by rlan35** [comment]
reset db.

**Comment by rlan35** [comment]
db on all shards are reset.

**Comment by rlan35** [comment]
`cat logs/dryrun/shard?.txt | xargs -i% -P50 bash -c './restart_node.sh -yp dryrun -t 0 -r 0 -R 0 -K %'`

Used to update blspass files for nodes.
