### ISSUE TITLE
[enhancement] staking tx shard agnostic

### ISSUE THREAD

**Issue by mindstyle85** [harmony-one/harmony#3017]
**Describe the bug**

To make hmy shard-agnostic, if the staking tx is received by a node on a non-beacon chain shard (currently shard #1, #2 or #3), it should broadcast this transaction to shard 0. This prevents awkward situations, such as the validator not being able to use his own node to send staking transactions.

**Comment by JackyWYX** [comment]
This feature has already been deal with in hmycli (go-sdk).

When handling staking transactions, if queried node is not running a beacon shard, the cli will ask the shard structure and send the transaction message to the beacon shard. After manual test, the feature is already implemented and passed test.

**Comment by mindstyle85** [comment]
ok, closing
