### ISSUE TITLE
[mainnet] dns nodes on shard0 stuck again

### ISSUE THREAD

**Issue by LeoHChen** [harmony-one/harmony#3025]
Seems all DNS nodes on shard0 are stuck again.

![image](https://user-images.githubusercontent.com/4513927/82125569-b30ccc80-975b-11ea-8e63-db2d54d1dcd2.png)

**Comment by LeoHChen** [comment]
I updated DNS record just now to mitigate the problem.

python3 r53update.py t 0 54.188.156.67 52.55.50.233 34.221.104.186 35.165.160.63 34.210.74.9 3.249.231.134 54.198.155.66 13.113.243.118

**Comment by Daniel-VDM** [comment]
On one of the old DNS node, `3.112.24.0` found too many files open:

Journal
```
May 16 17:01:23 ip-172-31-12-252.ap-northeast-1.compute.internal node.sh[10245]: 2020/05/16 17:01:23 http: Accept error: accept tcp [::]:9500: accept4: too many open files; retrying in 80ms
May 16 17:01:23 ip-172-31-12-252.ap-northeast-1.compute.internal node.sh[10245]: 2020/05/16 17:01:23 http: Accept error: accept tcp [::]:9500: accept4: too many open files; retrying in 160ms
```

And in logs
```
{"level":"warn","port":"9000","ip":"3.112.24.0","error":"rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing dial tcp 34.244.225.2:6000: socket: too many open files\"","peerIP":"34.244.225.2","peerPort":"6000","caller":"/mnt/jenkins/workspace/harmony-release/harmony/api/service/syncing/syncing.go:732","time":"2020-05-16T17:00:39.49978139Z","message":"[Sync]GetBlockChainHeight failed"}
```

**Comment by LeoHChen** [comment]
@Daniel-VDM , please restart all the nodes that got stuck. The DNS record is updated.

```
[lc@ip-172-31-4-194 pipeline]$ dig s0.t.hmny.io

; <<>> DiG 9.11.4-P2-RedHat-9.11.4-9.P2.amzn2.0.2 <<>> s0.t.hmny.io
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 39261
;; flags: qr rd ra; QUERY: 1, ANSWER: 8, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;s0.t.hmny.io.                  IN      A

;; ANSWER SECTION:
s0.t.hmny.io.           3547    IN      A       54.198.155.66
s0.t.hmny.io.           3547    IN      A       52.55.50.233
s0.t.hmny.io.           3547    IN      A       35.165.160.63
s0.t.hmny.io.           3547    IN      A       34.210.74.9
s0.t.hmny.io.           3547    IN      A       34.221.104.186
s0.t.hmny.io.           3547    IN      A       3.249.231.134
s0.t.hmny.io.           3547    IN      A       13.113.243.118
s0.t.hmny.io.           3547    IN      A       54.188.156.67
```

**Comment by LeoHChen** [comment]
Okay, I saw nodes are catching up now.

**Comment by rlan35** [comment]
we see similar issue in OSTN when lots of traffic goes. Guess the DNS nodes are overloaded so they get out of sync themselves. @Leo | Harmony 🏃🏻  can we increase the number of DNS nodes?

**Comment by rlan35** [comment]
@Daniel-VDM made all nodes in shard DNS nodes in OSTN and it seems to work @Daniel-VDM right?

**Comment by Daniel-VDM** [comment]
@rlan35 Actually I never made all the node DNS nodes, but I did increase the number of DNS nodes for s0. (from 4 -> 6)

**Comment by LeoHChen** [comment]
Already increased the number of DNS nodes in shard0. All nodes are caught up.

![image](https://user-images.githubusercontent.com/4513927/82125914-f49e7700-975d-11ea-90c3-5a5f3aba1333.png)

**Comment by LeoHChen** [comment]
I am adding more DNS nodes to shard0 now

**Comment by LeoHChen** [comment]
increased from 5 to 13 shard0 DNS nodes.

**Comment by LeoHChen** [comment]
restarted 3.112.24.0

**Comment by fxfactorial** [comment]
What is the downside of upping the dns node count

**Comment by LeoHChen** [comment]
found the `too many open files` in the journal on many nodes.  I need to restart them.

**Comment by LeoHChen** [comment]
restarted 10 nodes on shard0, checking shard1

**Comment by Daniel-VDM** [comment]
So I took a look at max number of open on s0 with:
```
./run_on_shard.sh -y -p s3 -T 0 'cat /proc/sys/fs/file-max' > s0_max_open.txt
```

got

```
profile: s3
execute: cat /proc/sys/fs/file-max
794529
794529
794255
794536
794529
794529
794536
794262
785442
785443
785060
785442
785442
785077
785085
785085
374451
2097152
374451
374451
374451
374452
374451
374451
374444
374452
374452
377319
377318
377319
374452
374452
374452
374452
377319
374451
374452
377319
374451
374451
374452
374452
377319
377319
374452
377319
374452
374452
374451
374452
377318
374451
374451
377318
374451
377319
377318
377318
374452
374452
377319
374452
374451
```

However, we specify to increase the max file size as part of our node.sh to: `sysctl -w fs.file-max=2097152`

I wonder if we never set things up for our internal nodes.

**Comment by LeoHChen** [comment]
found on shard1 as well, I think all the DNS nodes had this issue.

**Comment by LeoHChen** [comment]
@Daniel-VDM , I think you are right, that part of the sysctl may never being executed on our internal nodes, as it requires root permission and our nodes are not running under root user now.

**Comment by LeoHChen** [comment]
let's do a sysctl setting change now on all nodes.

**Comment by LeoHChen** [comment]
@Daniel-VDM , can you handle it? thanks.

**Comment by Daniel-VDM** [comment]
sure lets do `./run_on_shard.sh -y -p s3 -T 0 'sudo ~/node.sh -s'` ?

**Comment by LeoHChen** [comment]
no need to off the nodes, please try to run the command and check the max-op again. thanks.

**Comment by LeoHChen** [comment]
we shall change the sysctl on all shards

**Comment by Daniel-VDM** [comment]
Ran the command above and that increases the limit.
Checked with the command mentioned above:

```
profile: s3
execute: cat /proc/sys/fs/file-max
2097152
2097152
2097152
2097152
2097152
2097152
2097152
2097152
2097152
2097152
2097152
2097152
2097152
2097152
2097152
2097152
2097152
2097152
2097152
2097152
2097152
2097152
2097152
2097152
2097152
2097152
2097152
2097152
2097152
2097152
2097152
2097152
2097152
2097152
2097152
2097152
2097152
2097152
2097152
2097152
2097152
2097152
2097152
2097152
2097152
2097152
2097152
2097152
2097152
2097152
2097152
2097152
2097152
2097152
2097152
2097152
2097152
2097152
2097152
2097152
2097152
2097152
2097152
```

**Comment by Daniel-VDM** [comment]
doing all shards now

**Comment by Daniel-VDM** [comment]
restarted 3.249.231.134 first

**Comment by Daniel-VDM** [comment]
All shards now have file-max at 2097152

**Comment by Daniel-VDM** [comment]
can we add `sudo ./node.sh -s` as part of our TF node deployment? @LeoHChen

**Comment by LeoHChen** [comment]
That's the right thing to do.

**Comment by LeoHChen** [comment]
Eventually, we should have a separate sysctl.conf file and keep it in the /etc/ directory, so it will be effective after a reboot of the machine as well.

**Comment by LeoHChen** [comment]
can you open a ticket on this?  Can assign to @jhd2best to follow up

**Comment by fxfactorial** [comment]
I thought I asked for the node.sh script to be used, because I spent time fine tuning the 45+ sysctl kernel tweaks.

**Comment by LeoHChen** [comment]
@fxfactorial , node.sh will be used as Daniel said, but after reboot of the machine, we need to update those parameters again?  Any other recommendation other than the config file?  The config file will be based on node.sh anyway?

**Comment by fxfactorial** [comment]
Sure , if you can have it under /etc/conf or via the sysctl command, either way, but if former then ya, i guess needs to be updated in deploy pipeline? and I guess only at init?

**Comment by Daniel-VDM** [comment]
DNS Nodes out of sync again
![image](https://user-images.githubusercontent.com/31291913/82129500-3b00cf80-9778-11ea-898d-c32d4efe2b29.png)

will add more nodes to DNS

```
python3 r53update.py t 0 34.212.183.107 34.251.240.119 3.249.223.182 34.244.166.68 34.245.66.23 34.253.235.135 13.113.243.118 34.254.64.112 3.0.19.33 63.35.225.140 18.191.20.230 34.240.243.212 52.49.152.225 34.91.37.42 54.212.72.201 34.247.38.171 3.81.83.110 54.95.2.231
```

**Comment by Daniel-VDM** [comment]
![image](https://user-images.githubusercontent.com/31291913/82133871-b5941400-97a5-11ea-8732-2da966a5eb7c.png)

will change DNS node to recover asap

```
python3 r53update.py t 0 54.189.61.183 3.112.219.248 34.241.105.181 54.184.18.215 3.1.102.81 3.112.24.0 34.247.38.1 18.144.3.149 52.88.253.85 34.229.207.114 52.212.32.116
```

**Comment by Daniel-VDM** [comment]
Restarted machines that had too many files open from the list of old DNS nodes

**Comment by Daniel-VDM** [comment]
some of the old DNS nodes had `BAD BLOCK` in logs, probably due to too many files open crash. Had to rclone new DB and resync from there.

**Comment by Daniel-VDM** [comment]
removed explorer from DNS pool

**Comment by Daniel-VDM** [comment]
removed leader from DNS pool

**Comment by Daniel-VDM** [comment]
installed cron job to restart DNS nodes every hour

```bash
minute=0
for ip in $(cat shard0_dns_nodes.ips); do
    echo "setting up restart job for $ip"
    echo "$minute * * * * sudo systemctl restart harmony" | ./node_ssh.sh $ip "cat - > cronjob"
    ./node_ssh.sh $ip "crontab cronjob && crontab -l"
    (( minute += 2 ))
done
```
