### ISSUE TITLE
Too many open files on DNS nodes

### ISSUE THREAD

**Issue by LeoHChen** [harmony-one/harmony#3029]
Found too many open files on DNS nodes in shard0

```
nal node.sh[10245]: 2020/05/16 17:01:23 http: Accept error: accept tcp [::]:9500: accept4: too many open files; retrying in 80ms
May 16 17:01:23 ip-172-31-12-252.ap-northeast-1.compute.internal node.sh[10245]: 2020/05/16 17:01:23 http: Accept error: accept tcp [::]:9500: accept4: too many open files; retrying in 160ms
```

**Comment by LeoHChen** [comment]
https://blog.cloudflare.com/exposing-go-on-the-internet/

**Comment by LeoHChen** [comment]
It happens on non-DNS node as well.

https://harmonyone.pagerduty.com/incidents/PRAAX33

**Comment by LeoHChen** [comment]
https://github.com/grpc/grpc/pull/20808

**Comment by LeoHChen** [comment]
The opened files are mostly from syncing grpc
I login to one of the dns node and do the following,
```
sudo lsof | grep harmony > h.file

# the unique linked IP
[ec2-user@ip-172-31-8-136 ~]$ awk -F'[>:]' ' { print $3 } '  h.file  | sort -u  | wc
    479     478   11922

# all the open files
[ec2-user@ip-172-31-8-136 ~]$ awk -F'[>:]' ' { print $3 } '  h.file  | sort | wc
  14448   13512  342816

# sample of the h.file
armony   20287             ec2-user   15u     IPv4            3739364       0t0        TCP ip-172-31-8-136.us-west-1.compute.internal:x11->23.106.248.138:llsurfup-http (ESTABLISHED)
harmony   20287             ec2-user   16u     IPv4            3739517       0t0        TCP ip-172-31-8-136.us-west-1.compute.internal:x11->23.19.61.165:39808 (ESTABLISHED)
harmony   20287             ec2-user   18u     IPv4            3714319       0t0        TCP *:x11 (LISTEN)
harmony   20287             ec2-user   20u     IPv4            3740164       0t0        TCP ip-172-31-8-136.us-west-1.compute.internal:x11->45.77.188.44.vultr.com:aviva-sna (ESTABLISHED)
harmony   20287             ec2-user   23u     IPv4            3715109       0t0        TCP ip-172-31-8-136.us-west-1.compute.internal:cslistener->vmi300673.contaboserver.net:cslistener (ESTABLISHED)
harmony   20287             ec2-user   24u     IPv4            3739288       0t0        TCP ip-172-31-8-136.us-west-1.compute.internal:x11->ec2-52-53-228-249.us-west-1.compute.amazonaws.com:41842 (ESTABLISHED)
harmony   20287             ec2-user   25u     IPv4            3714321       0t0        TCP ip-172-31-8-136.us-west-1.compute.internal:cslistener->ec2-54-213-43-194.us-west-2.compute.amazonaws.com:9874 (ESTABLISHED)
harmony   20287             ec2-user   26u     IPv4            3714322       0t0        TCP ip-172-31-8-136.us-west-1.compute.internal:cslistener->ec2-100-26-90-187.compute-1.amazonaws.com:9874 (ESTABLISHED)
harmony   20287             ec2-user   27u     IPv4            3739369       0t0        TCP ip-172-31-8-136.us-west-1.compute.internal:x11->23.106.248.137:mlsn (ESTABLISHED)
harmony   20287             ec2-user   28u     IPv4            3722653       0t0        TCP ip-172-31-8-136.us-west-1.compute.internal:cslistener->95.168.180.237:cslistener (ESTABLISHED)
harmony   20287             ec2-user   29u     IPv4            3740180       0t0        TCP ip-172-31-8-136.us-west-1.compute.internal:x11->68.183.92.166:54018 (ESTABLISHED)
```

Out of all the connections, 10k are syncing connection, 3k are 9000 base port  connection.
```
[ec2-user@ip-172-31-8-136 ~]$ grep cslistener h.file | awk -F'[>:]' ' { print $3 } ' | sort -u | wc
    128     127    3930
# 128 are libp2p connection of base port


[ec2-user@ip-172-31-8-136 ~]$ grep x11 h.file | awk -F'[>:]' ' { print $3 } ' | sort -u | wc
    406     405    9309

# 406 are grpc connection of state syncing
```

**Comment by LeoHChen** [comment]
I copied the h.file to s3://harmony-benchmark/logs/leo/debug/h.file.gz

**Comment by LeoHChen** [comment]
I checked the open connections on all nodes in shard0, some interesting findings.

34.218.48.95  in us-west-2 has 91 libp2p connections
18.202.228.50 in eu-west-1 has 724 libp2p connections

both of them in sync, and the network traffic of those two nodes.

![image](https://user-images.githubusercontent.com/4513927/82508692-b3d69300-9aba-11ea-92a3-8f87d0722d41.png)

![image](https://user-images.githubusercontent.com/4513927/82508976-83432900-9abb-11ea-87ef-8a294ee49f2b.png)

**Comment by LeoHChen** [comment]
There is no significant difference between those two nodes even though the number of connections are very different.

**Comment by JackyWYX** [comment]
> There is no significant difference between those two nodes even though the number of connections are very different.

Sync is done through GRPC sessions instead of libp2p connections. I guess it is more likely the GRPC sessions causing this traffic.

**Comment by LeoHChen** [comment]
yes, that's what I think so. We need a better understanding on how to control the open files/sockets on grpc server. By default, I think gRpc are long live tcp streams. We need control on both biz logic and network timeout.

**Comment by JackyWYX** [comment]
@LeoHChen When I am reading sync code, I found one potential problem might have some relation with this problem

During syncing process, client node will query all DNS nodes about latest chain height, headers, adn blocks instead of one of them. Thus cause increasing DNS node number does not distribute the traffic, but increase the traffic. E.g, when having 2 DNS nodes, the client node will ask both of them for latest height instead either of them. Do you think this might be a potential fix?

```
// api/service/syncing/syncing.go:724
func (ss *StateSync) getMaxPeerHeight(isBeacon bool) uint64 {
	maxHeight := uint64(0)
	var wg sync.WaitGroup
	ss.syncConfig.ForEachPeer(func(peerConfig *SyncPeerConfig) (brk bool) {
		wg.Add(1)
		go func() {
			defer wg.Done()
			//debug
			// utils.Logger().Debug().Bool("isBeacon", isBeacon).Str("peerIP", peerConfig.ip).Str("peerPort", peerConfig.port).Msg("[Sync]getMaxPeerHeight")
			response, err := peerConfig.client.GetBlockChainHeight()
			if err != nil {
				utils.Logger().Warn().Err(err).Str("peerIP", peerConfig.ip).Str("peerPort", peerConfig.port).Msg("[Sync]GetBlockChainHeight failed")
				return
			}
			ss.syncMux.Lock()
			if response != nil && maxHeight < response.BlockHeight {
				maxHeight = response.BlockHeight
			}
			ss.syncMux.Unlock()
		}()
		return
	})
	wg.Wait()
	return maxHeight
}
```

**Comment by LeoHChen** [comment]
This is the original design to make sure we have the majority of the right block.  This can definitely be improved to just randomly choose a set of DNS node to query, instead of all of them.  @JackyWYX

**Comment by JackyWYX** [comment]
Currently how many explorer nodes for mainnet beacon chain is deployed? Do you think half of the DNS peers being asked for sync will be a reasonable ratio to start with?

**Comment by LeoHChen** [comment]
half of them is a good number to start, if half is less than 3, then we can choose 3, if half is more than 5, then we can choose 5, how about that?

**Comment by JackyWYX** [comment]
So how many DNS nodes is there at endpoint s0.t.hmy.io?

**Comment by LeoHChen** [comment]
use `dig` to check, 8 for now, but we can increase it then.

```bash
dig s0.t.hmny.io

s0.t.hmny.io.           2072    IN      A       34.253.235.135
s0.t.hmny.io.           2072    IN      A       3.112.24.0
s0.t.hmny.io.           2072    IN      A       52.55.50.233
s0.t.hmny.io.           2072    IN      A       35.246.20.148
s0.t.hmny.io.           2072    IN      A       18.144.3.149
s0.t.hmny.io.           2072    IN      A       13.113.243.118
s0.t.hmny.io.           2072    IN      A       34.218.48.95
s0.t.hmny.io.           2072    IN      A       34.241.213.180

```

**Comment by LeoHChen** [comment]
adding a tool to check opened sockets on node.
https://github.com/harmony-one/experiment-deploy/pull/336

**Comment by LeoHChen** [comment]
This is also related to https://github.com/harmony-one/harmony/issues/3050

**Comment by LeoHChen** [comment]
https://github.com/harmony-one/harmony/pull/3072

**Comment by LeoHChen** [comment]
Run an query on all nodes and still find the issue on the DNS nodes. Most recently was from yesterday before rolling upgrade.  So, since rolling upgrade will restart the harmony process, it didn't get a cascading issues on the network.
```
./run_on_shard.sh -yp s3 3 'journalctl -rn 500 --no-pager -u harmony | grep -m 2 "too many open"'
```

**Comment by LeoHChen** [comment]
we've made a few changes on the DNS nodes, including sysctl to adjust the limit of file open, and increase number of dns nodes, and randomize the dns server query. I did a query on all mainnet nodes, there is no too many file open errors found recently.  I am going to close this ticket for now.
