### ISSUE TITLE
reuse the stream in p2p

### ISSUE THREAD

**Issue by LeoHChen** [harmony-one/harmony#303]
## Summary

Reuse the stream for p2p communication.

## Current Design

In current p2p/host library, the sendmessage create new stream for every message sent to peer, this is very inefficient.

https://github.com/harmony-one/harmony/blob/8edebd2250b38247fe2fb4c4ddd9cf6073e44ddf/p2p/host/hostv2/hostv2.go#L111

## Problems

We saw frequent sendmessage failure due to 'dail backoff' etc.  I doubt this is due to the newstream call for each message sent.  

## Proposal

I propose to remember the stream for a certain connection, and just reuse the stream handler with reader/writer for each communication.  This will be much efficient.  The reader/writer can be a list within p2p.Peer structure.

**Comment by harmony-ek** [comment]
Let's use the following connection rules, modeled after RFC 4271 (BGP) connection collision detection/resolution:

* When a connection is first made/accepted, it is in `NASCENT` state.  A `NASCENT` connection cannot carry application traffic yet.
* A `NASCENT` connection goes through collision detection/resolution, then moves into `MATURE` state, and starts carrying application traffic.
* A host initiates a connection to another host only if it has no other connection(s) from/to the other host, either in `NASCENT` or `MATURE` state.
* On the other hand, a host accepts an incoming `NASCENT` connection at any time.
    * When a local host accepts a `NASCENT` connection from a remote host while there already exists another `NASCENT` connection that the local host accepted from the same remote host, the local host keeps the new one and closes the old one.
        * This may happen when only the remote host detects a connection error on the first `NASCENT` connection and makes a second one.
* This implies that there can at most be two `NASCENT` connections between two hosts (one outgoing and one incoming).
* The two hosts exchange and figure out each other's host ID (libp2p peer ID for example).
* **Collision detection:** If an incoming `NASCENT` connection and an outgoing `NASCENT` connection from/to the same remote host exist at the same time…
    * **Collision resolution:** The one initiated by the one with higher host ID (libp2p peer ID) advances to the `MATURE` state, and the other one gets closed.
* There may be at most one `MATURE` connection.  While there exists a `MATURE` connection, incoming `NASCENT` connections from the same remote host is closed without further consideration.
* Keepalive mechanisms are used, using two timing parameters: `KeepaliveTime` and `HoldTime`.
    * If no data has been received over a connection for `HoldTime` (default 15s), the host closes the connection.
    * If no data has been sent over a connection for `KeepaliveTime` (default 5s, `HoldTime / 3` per RFC 4271), the host sends a no-op (keepalive) message over the connection.
    * Keepalive mechanism is particularly important because a `MATURE` connection wins over any new incoming `NASCENT` connection.  If a `MATURE` connection is hung without keepalive and one host only reads from the hung connection but does not write to it, the reader host may never detect the problem and keep the hung connection indefinitely; the writer host may never be able to reconnect to the reader, because the reader host will reject incoming `NASCENT` connections as long as it holds onto the hung but “`MATURE`” connection.

**Comment by LeoHChen** [comment]
not needed anymore.
