### ISSUE TITLE
[mainnet] not elected validator is still earning rewards

### ISSUE THREAD

**Issue by mindstyle85** [harmony-one/harmony#3038]
**Describe the bug**

on dashboard it looks like unelected validators are actually earnings rewards, see:

https://staking.harmony.one/validators/one14xkvsj8gnwl2tnu9wahfru35x8ppveaqdx5cnf

**Comment by mindstyle85** [comment]
actually this one looks not elected, but is probably using bls key in a new validator which is elected, i already reported this bug as its a really confusing one for the dashboard.

here is brunos report: https://github.com/harmony-one/staking-dashboard/issues/438
and mine: https://github.com/harmony-one/staking-dashboard/issues/390

**Comment by BrunoMarshall** [comment]
This Validator still increasing signing blocks: 
![image](https://user-images.githubusercontent.com/35432495/82230690-5f051200-992c-11ea-9b48-45f5ab6acd83.png)

1 minute after: 
![image](https://user-images.githubusercontent.com/35432495/82230789-7f34d100-992c-11ea-83c6-dd656cc739a9.png)

**Comment by sophoah** [comment]
Here is another issue that we think may be linked,

This is a validator that is elected but not earning  and its bls are not found in the epos candidate list : 
```
root@vmi334486:~/harmony# ./hmy -n https://api.s0.t.hmny.io blockchain validator information one129gp9e7ghsyecxevp4che033dmk0sew7swvk66 | jq
{
  "id": "0",
  "jsonrpc": "2.0",
  "result": {
    "booted-status": null,
    "current-epoch-performance": {
      "current-epoch-signing-percent": {
        "current-epoch-signed": 0,
        "current-epoch-signing-percentage": "0.000000000000000000",
        "current-epoch-to-sign": 0
      }
    },
    "currently-in-committee": true,
    "epos-status": "currently elected",
    "epos-winning-stake": "3002000000000000000000000.000000000000000000",
    "lifetime": {
      "apr": "0.000000000000000000",
      "blocks": {
        "signed": 0,
        "to-sign": 0
      },
      "reward-accumulated": 0
    },
    "metrics": {
      "by-bls-key": [
        {
          "earned-reward": 0,
          "key": {
            "bls-public-key": "ff64e929ee6bf37983e13f495437665416c0f6e7862b56c0caa84f932ff48fe68c379e4d483e6088198d25023e949b87",
            "earning-account": "one129gp9e7ghsyecxevp4che033dmk0sew7swvk66",
            "effective-stake": "1501000000000000000000000.000000000000000000",
            "group-percent": "0.013300847609762530",
            "overall-percent": "0.004256271235124010",
            "raw-stake": "1501000000000000000000000.000000000000000000",
            "shard-id": 3
          }
        },
        {
          "earned-reward": 0,
          "key": {
            "bls-public-key": "614e8d1344bff19f5e1a6e7886355beba087cdc0947d2b5ad1eec36caa18325e0585534dd20a37546bf11d44f1e31e13",
            "earning-account": "one129gp9e7ghsyecxevp4che033dmk0sew7swvk66",
            "effective-stake": "1501000000000000000000000.000000000000000000",
            "group-percent": "0.013300847609762530",
            "overall-percent": "0.004256271235124010",
            "raw-stake": "1501000000000000000000000.000000000000000000",
            "shard-id": 3
          }
        }
      ]
    },
    "total-delegation": 3.002e+24,
    "validator": {
      "address": "one129gp9e7ghsyecxevp4che033dmk0sew7swvk66",
      "bls-public-keys": [
        "614e8d1344bff19f5e1a6e7886355beba087cdc0947d2b5ad1eec36caa18325e0585534dd20a37546bf11d44f1e31e13",
        "ff64e929ee6bf37983e13f495437665416c0f6e7862b56c0caa84f932ff48fe68c379e4d483e6088198d25023e949b87"
      ],
```
the two BLS are not found in the epos-candidate list available in the median-stake rpc: 
```
root@vmi334486:~/harmony# ./hmy -n https://api.s0.t.hmny.io blockchain median-stake | grep 614e8d1344bff19f5e1a6e7886355beba087cdc0947d2b5ad1eec36caa18325e0585534dd20a37546bf11d44f1e31e13
root@vmi334486:~/harmony# ./hmy -n https://api.s0.t.hmny.io blockchain median-stake | grep ff64e929ee6bf37983e13f495437665416c0f6e7862b56c0caa84f932ff48fe68c379e4d483e6088198d25023e949b87
```

**Comment by mindstyle85** [comment]
this one is earning rewards too: https://staking.harmony.one/validators/one1hlxe68d7trza48k0n4y77antwaken3x99pgw75

**Comment by nickvasilich7** [comment]
I can provide more input what have been done with my node and bls keys in shard 3

**Comment by wjdfx** [comment]
> Here is another issue that we think may be linked,
> 
> This is a validator that is elected but not earning and its bls are not found in the epos candidate list :
> 
> ```
> root@vmi334486:~/harmony# ./hmy -n https://api.s0.t.hmny.io blockchain validator information one129gp9e7ghsyecxevp4che033dmk0sew7swvk66 | jq
> {
>   "id": "0",
>   "jsonrpc": "2.0",
>   "result": {
>     "booted-status": null,
>     "current-epoch-performance": {
>       "current-epoch-signing-percent": {
>         "current-epoch-signed": 0,
>         "current-epoch-signing-percentage": "0.000000000000000000",
>         "current-epoch-to-sign": 0
>       }
>     },
>     "currently-in-committee": true,
>     "epos-status": "currently elected",
>     "epos-winning-stake": "3002000000000000000000000.000000000000000000",
>     "lifetime": {
>       "apr": "0.000000000000000000",
>       "blocks": {
>         "signed": 0,
>         "to-sign": 0
>       },
>       "reward-accumulated": 0
>     },
>     "metrics": {
>       "by-bls-key": [
>         {
>           "earned-reward": 0,
>           "key": {
>             "bls-public-key": "ff64e929ee6bf37983e13f495437665416c0f6e7862b56c0caa84f932ff48fe68c379e4d483e6088198d25023e949b87",
>             "earning-account": "one129gp9e7ghsyecxevp4che033dmk0sew7swvk66",
>             "effective-stake": "1501000000000000000000000.000000000000000000",
>             "group-percent": "0.013300847609762530",
>             "overall-percent": "0.004256271235124010",
>             "raw-stake": "1501000000000000000000000.000000000000000000",
>             "shard-id": 3
>           }
>         },
>         {
>           "earned-reward": 0,
>           "key": {
>             "bls-public-key": "614e8d1344bff19f5e1a6e7886355beba087cdc0947d2b5ad1eec36caa18325e0585534dd20a37546bf11d44f1e31e13",
>             "earning-account": "one129gp9e7ghsyecxevp4che033dmk0sew7swvk66",
>             "effective-stake": "1501000000000000000000000.000000000000000000",
>             "group-percent": "0.013300847609762530",
>             "overall-percent": "0.004256271235124010",
>             "raw-stake": "1501000000000000000000000.000000000000000000",
>             "shard-id": 3
>           }
>         }
>       ]
>     },
>     "total-delegation": 3.002e+24,
>     "validator": {
>       "address": "one129gp9e7ghsyecxevp4che033dmk0sew7swvk66",
>       "bls-public-keys": [
>         "614e8d1344bff19f5e1a6e7886355beba087cdc0947d2b5ad1eec36caa18325e0585534dd20a37546bf11d44f1e31e13",
>         "ff64e929ee6bf37983e13f495437665416c0f6e7862b56c0caa84f932ff48fe68c379e4d483e6088198d25023e949b87"
>       ],
> ```
> 
> the two BLS are not found in the epos-candidate list available in the median-stake rpc:
> 
> ```
> root@vmi334486:~/harmony# ./hmy -n https://api.s0.t.hmny.io blockchain median-stake | grep 614e8d1344bff19f5e1a6e7886355beba087cdc0947d2b5ad1eec36caa18325e0585534dd20a37546bf11d44f1e31e13
> root@vmi334486:~/harmony# ./hmy -n https://api.s0.t.hmny.io blockchain median-stake | grep ff64e929ee6bf37983e13f495437665416c0f6e7862b56c0caa84f932ff48fe68c379e4d483e6088198d25023e949b87
> ```

I think I've found some possibilities. because the shard0 is backward with shard0, my validator in the shard3, so use this:
hmy --node=https://api.s0.t.hmny.io/ blockchain validator information one129gp9e7ghsyecxevp4che033dmk0sew7swvk66
check status by shard0. but Shard0 will lag behind shard3

-- Bit Cat validator

**Comment by wjdfx** [comment]
> Here is another issue that we think may be linked,
> 
> This is a validator that is elected but not earning and its bls are not found in the epos candidate list :
> 
> ```
> root@vmi334486:~/harmony# ./hmy -n https://api.s0.t.hmny.io blockchain validator information one129gp9e7ghsyecxevp4che033dmk0sew7swvk66 | jq
> {
>   "id": "0",
>   "jsonrpc": "2.0",
>   "result": {
>     "booted-status": null,
>     "current-epoch-performance": {
>       "current-epoch-signing-percent": {
>         "current-epoch-signed": 0,
>         "current-epoch-signing-percentage": "0.000000000000000000",
>         "current-epoch-to-sign": 0
>       }
>     },
>     "currently-in-committee": true,
>     "epos-status": "currently elected",
>     "epos-winning-stake": "3002000000000000000000000.000000000000000000",
>     "lifetime": {
>       "apr": "0.000000000000000000",
>       "blocks": {
>         "signed": 0,
>         "to-sign": 0
>       },
>       "reward-accumulated": 0
>     },
>     "metrics": {
>       "by-bls-key": [
>         {
>           "earned-reward": 0,
>           "key": {
>             "bls-public-key": "ff64e929ee6bf37983e13f495437665416c0f6e7862b56c0caa84f932ff48fe68c379e4d483e6088198d25023e949b87",
>             "earning-account": "one129gp9e7ghsyecxevp4che033dmk0sew7swvk66",
>             "effective-stake": "1501000000000000000000000.000000000000000000",
>             "group-percent": "0.013300847609762530",
>             "overall-percent": "0.004256271235124010",
>             "raw-stake": "1501000000000000000000000.000000000000000000",
>             "shard-id": 3
>           }
>         },
>         {
>           "earned-reward": 0,
>           "key": {
>             "bls-public-key": "614e8d1344bff19f5e1a6e7886355beba087cdc0947d2b5ad1eec36caa18325e0585534dd20a37546bf11d44f1e31e13",
>             "earning-account": "one129gp9e7ghsyecxevp4che033dmk0sew7swvk66",
>             "effective-stake": "1501000000000000000000000.000000000000000000",
>             "group-percent": "0.013300847609762530",
>             "overall-percent": "0.004256271235124010",
>             "raw-stake": "1501000000000000000000000.000000000000000000",
>             "shard-id": 3
>           }
>         }
>       ]
>     },
>     "total-delegation": 3.002e+24,
>     "validator": {
>       "address": "one129gp9e7ghsyecxevp4che033dmk0sew7swvk66",
>       "bls-public-keys": [
>         "614e8d1344bff19f5e1a6e7886355beba087cdc0947d2b5ad1eec36caa18325e0585534dd20a37546bf11d44f1e31e13",
>         "ff64e929ee6bf37983e13f495437665416c0f6e7862b56c0caa84f932ff48fe68c379e4d483e6088198d25023e949b87"
>       ],
> ```
> 
> the two BLS are not found in the epos-candidate list available in the median-stake rpc:
> 
> ```
> root@vmi334486:~/harmony# ./hmy -n https://api.s0.t.hmny.io blockchain median-stake | grep 614e8d1344bff19f5e1a6e7886355beba087cdc0947d2b5ad1eec36caa18325e0585534dd20a37546bf11d44f1e31e13
> root@vmi334486:~/harmony# ./hmy -n https://api.s0.t.hmny.io blockchain median-stake | grep ff64e929ee6bf37983e13f495437665416c0f6e7862b56c0caa84f932ff48fe68c379e4d483e6088198d25023e949b87
> ```

I found some possibilities. Is it because the height of shard0 and shard3 blocks are different？
My validator blskey on the shard3.

**Comment by rlan35** [comment]
@mindstyle85 for the reported issue of unelected validator still earning reward. it's caused by the crosslink backlog issue which basically delayed the rewards for the validators when they were still elected. It should be such a serious issue once the crosslink backlog are all processed and crosslink are relative in pace with shard block confirmations.

**Comment by Schmandre** [comment]
> > Here is another issue that we think may be linked,
> > This is a validator that is elected but not earning and its bls are not found in the epos candidate list :
> > ```
> > root@vmi334486:~/harmony# ./hmy -n https://api.s0.t.hmny.io blockchain validator information one129gp9e7ghsyecxevp4che033dmk0sew7swvk66 | jq
> > {
> >   "id": "0",
> >   "jsonrpc": "2.0",
> >   "result": {
> >     "booted-status": null,
> >     "current-epoch-performance": {
> >       "current-epoch-signing-percent": {
> >         "current-epoch-signed": 0,
> >         "current-epoch-signing-percentage": "0.000000000000000000",
> >         "current-epoch-to-sign": 0
> >       }
> >     },
> >     "currently-in-committee": true,
> >     "epos-status": "currently elected",
> >     "epos-winning-stake": "3002000000000000000000000.000000000000000000",
> >     "lifetime": {
> >       "apr": "0.000000000000000000",
> >       "blocks": {
> >         "signed": 0,
> >         "to-sign": 0
> >       },
> >       "reward-accumulated": 0
> >     },
> >     "metrics": {
> >       "by-bls-key": [
> >         {
> >           "earned-reward": 0,
> >           "key": {
> >             "bls-public-key": "ff64e929ee6bf37983e13f495437665416c0f6e7862b56c0caa84f932ff48fe68c379e4d483e6088198d25023e949b87",
> >             "earning-account": "one129gp9e7ghsyecxevp4che033dmk0sew7swvk66",
> >             "effective-stake": "1501000000000000000000000.000000000000000000",
> >             "group-percent": "0.013300847609762530",
> >             "overall-percent": "0.004256271235124010",
> >             "raw-stake": "1501000000000000000000000.000000000000000000",
> >             "shard-id": 3
> >           }
> >         },
> >         {
> >           "earned-reward": 0,
> >           "key": {
> >             "bls-public-key": "614e8d1344bff19f5e1a6e7886355beba087cdc0947d2b5ad1eec36caa18325e0585534dd20a37546bf11d44f1e31e13",
> >             "earning-account": "one129gp9e7ghsyecxevp4che033dmk0sew7swvk66",
> >             "effective-stake": "1501000000000000000000000.000000000000000000",
> >             "group-percent": "0.013300847609762530",
> >             "overall-percent": "0.004256271235124010",
> >             "raw-stake": "1501000000000000000000000.000000000000000000",
> >             "shard-id": 3
> >           }
> >         }
> >       ]
> >     },
> >     "total-delegation": 3.002e+24,
> >     "validator": {
> >       "address": "one129gp9e7ghsyecxevp4che033dmk0sew7swvk66",
> >       "bls-public-keys": [
> >         "614e8d1344bff19f5e1a6e7886355beba087cdc0947d2b5ad1eec36caa18325e0585534dd20a37546bf11d44f1e31e13",
> >         "ff64e929ee6bf37983e13f495437665416c0f6e7862b56c0caa84f932ff48fe68c379e4d483e6088198d25023e949b87"
> >       ],
> > ```
> > 
> > 
> > the two BLS are not found in the epos-candidate list available in the median-stake rpc:
> > ```
> > root@vmi334486:~/harmony# ./hmy -n https://api.s0.t.hmny.io blockchain median-stake | grep 614e8d1344bff19f5e1a6e7886355beba087cdc0947d2b5ad1eec36caa18325e0585534dd20a37546bf11d44f1e31e13
> > root@vmi334486:~/harmony# ./hmy -n https://api.s0.t.hmny.io blockchain median-stake | grep ff64e929ee6bf37983e13f495437665416c0f6e7862b56c0caa84f932ff48fe68c379e4d483e6088198d25023e949b87
> > ```
> 
> I found some possibilities. Is it because the height of shard0 and shard3 blocks are different？
> My validator blskey on the shard3.
> 
> I can almost confirm that there is a delay in the result of this command：
> hmy --node=https://api.s0.t.hmny.io/ blockchain validator information one129gp9e7ghsyecxevp4che033dmk0sew7swvk66

I think me and my team have the same problem. We have one BLS Key in different shards, but we all doesnt sign blocks :( Ideas?

`administrator@ab-s-node:~$ ./hmy -n https://api.s0.t.hmny.io blockchain validator information one10lev28xhn3a0es5ee07sqps0e3khw83a6sm57j
{
  "id": "0",
  "jsonrpc": "2.0",
  "result": {
    "booted-status": "not booted",
    "current-epoch-performance": null,
    "currently-in-committee": false,
    "epos-status": "eligible to be elected next epoch",
    "epos-winning-stake": null,
    "lifetime": {
      "apr": "0.000000000000000000",
      "blocks": {
        "signed": 0,
        "to-sign": 0
      },
      "reward-accumulated": 0
    },
    "metrics": null,
    "total-delegation": 2.0234222623e+22,
    "validator": {
      "address": "one10lev28xhn3a0es5ee07sqps0e3khw83a6sm57j",
      "bls-public-keys": [
        "4de08c21ef1df0daf0daea6055eaf68dff01f6bf2cb4aa0874a735134e6154a1585382f1ab50f6532009d1126f0a5e94"
      ],
      "creation-height": 3381189,
      "delegations": [
        {
          "amount": 2.0234222623e+22,
          "delegator-address": "one10lev28xhn3a0es5ee07sqps0e3khw83a6sm57j",
          "reward": 0,
          "undelegations": []
        }
      ],
      "details": "Stake with us",
      "identity": "Andre",
      "last-epoch-in-committee": 0,
      "max-change-rate": "0.100000000000000000",
      "max-rate": "0.100000000000000000",
      "max-total-delegation": 1e+26,
      "min-self-delegation": 1e+22,
      "name": "Schmandre",
      "rate": "0.050000000000000000",
      "security-contact": "ab@jetstake.com",
      "update-height": 3382668,
      "website": "jetstake.com"
    }
  }
}
`

**Comment by mindstyle85** [comment]
it seems theres a crosslink delay @Schmandre .. i think the other validator fixed that by actually launching new instance/node for his, so i guess it has to do with syncing too. Maybe try that yourself, keep the original nodes up and spin up backup ones and use rclone to get them in sync, then observe if uptime starts to show.
