### ISSUE TITLE
Consider using exponentially weighted moving average (EMA) instead of simple moving average (SMA) to calculate expected return and uptime averages

### ISSUE THREAD

**Issue by samhsiung** [harmony-one/harmony#3073]
# Problem/limitation At Hand

Shard 0 validators have experienced significant downtime in the last few days and it's hard to catch up with other validators uptime despite many of us experiencing 100% uptime within the last day after the beacon chain for other shards caught up.

**Which component?**

- [ ] consensus
- [ ] deploy script
- [ ] wallet
- [ x ] explorer
- [ ] node script
- [ ] test automation
- [ ] demo app
- [ ] others ...

# Proposed Solution
I think harmony should consider using an exponentially weighted moving average instead of a simple moving average to compute average expected return and uptime.

An EMA would weight the metrics from a more recent epoch higher than the older epochs. This way node operators are still accountable for an entire month of activity but delegators will have a more accurate picture of what their recent uptime or return would look like since recent data is a better predictor of the future.

Use the EMA formula described in https://www.investopedia.com/terms/e/ema.asp to compute averages for uptime and expected return.

# Alternatives Considered

# Additional Context

This was discussed earlier in discord and it was proposed by @LeoHChen to create an issue for it.

**Comment by spitus** [comment]
Hi guys,
Why don't we show the current uptime of the validators like this page:
https://monitor.hmny.io/validators

showing real uptime in current epoch can be even more usefull for delegators than an average of the past epochs.

What do you think?

**Comment by samhsiung** [comment]
I agree @spitus that could be a simple solution to this problem. It would encourage delegators to spread their ONES to other validators and give smaller validators a better chance. Maybe the explorer could just sort by uptime and expected returns for the current epoch. The average can still be displayed and accessible elsewhere.
