### ISSUE TITLE
[Feature] API for all addresses on the blockchain

### ISSUE THREAD

**Issue by SmartStake** [harmony-one/harmony#3087]
# Problem/limitation At Hand
I want to build some features in the smart stake dashboard for harmony @ harmony.smartstake.io. For some of the features, I need to have details of all addresses in the blockchain

There is no easy way to obtain address data for all non-staking addresses.

**Which component?**

- [ ] consensus
- [ ] deploy script
- [ ] wallet
- [X ] explorer
- [ ] node script
- [ ] test automation
- [ ] demo app
- [ ] others ...

# Proposed Solution
a pagination based API providing listing of all addresses in the network along with the address balance

# Alternatives Considered

# Additional Context

**Comment by rlan35** [comment]
This can be achieved by using Graph Indexer.
