### ISSUE TITLE
[defensive] nil pointer has to be handled for block header package

### ISSUE THREAD

**Issue by LeoHChen** [harmony-one/harmony#3090]
**Describe the bug**

Found a nil pointer crash during a release test.
https://github.com/harmony-one/harmony/issues/3088

While reviewing the code in the following file `block/v2/header.go`, found that nil pointer wasn't handled at all.

I fixed a few cases in this PR. https://github.com/harmony-one/harmony/pull/3089

There could be other cases not found during the test.  We need to review the code carefully to fix the potential nil pointer crashes.

**Comment by LeoHChen** [comment]
One more fix of nil pointer, https://github.com/harmony-one/harmony/pull/3091

**Comment by LeoHChen** [comment]
https://github.com/harmony-one/harmony/pull/3030

**Comment by JackyWYX** [comment]
After go over though the consensus module, there doesn't seem to have unhandled nil block or nil header. Closing.
