### ISSUE TITLE
mainnet consensus log analysis

### ISSUE THREAD

**Issue by LeoHChen** [harmony-one/harmony#3097]
we need automation to do some more time analysis on the logs for consensus.

A few keywords can be searched from the log. Need to find the timestamp of those key messages.

# leader's log
* PROPOSING NEW BLOCK
* [OnCommit] 2/3 Enough commits
* [OnCommit] 100% Enough commits received
* [OnCommit] Commit Grace Period Ended
* HOORAY

**Comment by ivorytowerdds** [comment]
Some results from using ElasticSearch. 
- PROPOSING NEW BLOCK
![image](https://user-images.githubusercontent.com/34232522/85169090-1f2d9500-b220-11ea-8b13-1bfafe9dd756.png)
- [OnCommit] 2/3 Enough commits & 100% Enough commits received & commit grace period ended
![image](https://user-images.githubusercontent.com/34232522/85169312-792e5a80-b220-11ea-965d-55f84d8e86ea.png)
