### ISSUE TITLE
BAD BLOCK on internal nodes

### ISSUE THREAD

**Issue by gupadhyaya** [harmony-one/harmony#3098]
During on-call I noticed several nodes going out-of-sync with following two BAD BLOCK errors.

```wrap
130873:{"level":"error","port":"9000","ip":"18.188.53.42","caller":"/mnt/jenkins/workspace/harmony-release/harmony/core/blockchain.go:1571","time":"2020-05-25T13:16:43.724770245Z","message":"\n########## BAD BLOCK #########\nChain config: {ChainID: 1 EIP155: 28 CrossTx: 28 Staking: 186 CrossLink: 186 ReceiptLog: 101}\n\nNumber: 3449461\nEpoch: 190\nNumTxn: 0\nNumStkTxn: 0\nHash: 0x8f40537916d05b3b4a069f2291484a9b56acd128c944389eb66826e036f7a270\n\n\nError: invalid merkle root (remote: 56204bb047754e00891f10f4aa5207298e7dd6a4313d270bd4ec03510eebe25a local: d35ae01820ff148b773d89b73a562af55a6bb019057c90b162963bc7cfccf6f0, rlp dump f904c387486d6e79546764827633f904b5a0229e52be385eff68a376a9a6c69b7685a5ea65707a6bfb95cdfff45871c81dfa94e5dc9dbd0b93231e5d0bf998669463fe990a7211a056204bb047754e00891f10f4aa5207298e7dd6a4313d270bd4ec03510eebe25aa056e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421a056e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421a056e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421a056e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421b90100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000008334a2758404c4b40080845ecbc3f180a000000000000000000000000000000000000000000000000000000000000000008334a2e781be80b8609431fbcb4ca80b6943347c7b1ff5aa5a4f5dbc9e53c5765d81c5922b3daf29ee388d7c3bf0de878beace89484d46bd17c149ab9f241b017704bbde3955cf0c9d4b6788b7529990e6b74e57600ee6629c2ea0e86385c58ce28d8af70d643882149fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff07808080b90216f90213f8afa0f759ca082eb20e50002c3823bbdcb4f9b4c8599e1f10c33100385f6dd4f40986833390d98333916eb8608d3d87e157912cca7bc30e307d32e6f595214f88a96382aa72461285c255697682e42594a99b0eabe5666dab34e9de170010406bb19e39c84aa1717ada874b56ca9a62d6194304b2ddbf4b14253d70b3bd70e7c8d566ebd9919d1f2ac8fb5090a0ffdffffbffffffffffffffffffffffffffffffffbfffffffffffffffffffff0f0181bef8afa08a09a419c4058717830b02313ec10da4be675d7211a18894ca9b72cf92cab90f83342ec983342f4fb860703dc0550efd995fdab733eb413fc07c7570b63d8d428aa9489fd17ec573b840a88d419dc92938f696a353a6de28c4013b512da7cc50a6bcd95ffb2234931a4d11b4b7a262c3f74cf082e45a6a32a2007dd8ffc72c88e82f3b7f76d752416586a0ffffffffffffffffffbfbffffffffffffffffffffffdffffffffffffffffff070281bef8afa072afa931509c1367f70b312bb0444b02f9d39d271bc28145e1280e220234fe498333fb578333fbccb860a9271213d4482841a02fab3fd502a3cdfea6ce8ecd9076b0cf5781bcc87f84577dcbd03ca919163b77124b3db3ccf20068149362e805b4f1cc275bbb2cba2a7b4cdb0f5521885e48b1bf172f21de064e80cab9e943392009217a731bef7f3b01a0ffffffff7ffffffffffffffffffffff7fffffffffffdffffffffffffffffff3f0381be80)\n##############################\n"}

133742:{"level":"error","port":"9000","ip":"18.188.53.42","caller":"/mnt/jenkins/workspace/harmony-release/harmony/core/blockchain.go:1571","time":"2020-05-25T13:26:24.369127316Z","message":"\n########## BAD BLOCK #########\nChain config: {ChainID: 1 EIP155: 28 CrossTx: 28 Staking: 186 CrossLink: 186 ReceiptLog: 101}\n\nNumber: 3449549\nEpoch: 190\nNumTxn: 0\nNumStkTxn: 1\nHash: 0xb9f95fb5efa1b5372ef63f65f195d15002d8e63f3787684d81e213bba0ff2521\n\n\nError: address not present in state\n##############################\n"}
```

Most of the time simple restart would fix the problem. A couple of times, I had to rclone the snapshot. 

Need to take a look further.

**Comment by rlan35** [comment]
likely due to the state.ValidatorWrapper caching and race conditions.

**Comment by rlan35** [comment]
{"level":"info","port":"9000","ip":"18.188.53.42","validator-snapshot":{"bls-public-keys":["323bd3f38afce4f27e35e5e1c7a6cd4f3f024817fc180fd73e3880e26fdd8824092f9707d216a1c7d278c6bef71b1493"],"last-epoch-in-committee":191,"min-self-delegation":10000000000000000000000,"max-total-delegation":100000000000000000000000000,"rate":"0.050000000000000000","max-rate":"0.200000000000000000","max-change-rate":"0.100000000000000000","update-height":3405985,"name":"FireStack Validator","identity":"FireStack Validator","website":"https://firestack.one/","security-contact":"yuxiaolang2008@163.com","details":"fireStack validator for all stakers","creation-height":3405985,"address":"one1kd2tq5rsywz6x28g7v9jaa85e67hgu2nr9lte6","delegations":[{"delegator-address":"one1kd2tq5rsywz6x28g7v9jaa85e67hgu2nr9lte6","amount":0,"reward":81993070662625639725,"undelegations":[{"amount":601900000000000000000000,"epoch":191}]},{"delegator-address":"one1m68ye842jh4l27uhfae4thakz0klzjwumrf2ls","amount":0,"reward":1700926881365882503238,"undelegations":[{"amount":2010603000000000000000000,"epoch":191}]},{"delegator-address":"one1kuu877arheztzhy9xvyeafasayujsdtm5h8hm6","amount":0,"reward":1194855722637431792253,"undelegations":[{"amount":593954000000000000000000,"epoch":191}]},{"delegator-address":"one1vy49dqugujq9ghjh79pkwmn67g7dd4agn3dtzg","amount":0,"reward":83940836987370964332,"undelegations":[{"amount":151738000000000000000000,"epoch":191}]},{"delegator-address":"one1yy96kgumhfw6tjwdkxtspju4qf0sc9ay4tf50s","amount":0,"reward":0,"undelegations":[{"amount":390176000000000000000000,"epoch":191}]}]},"caller":"/mnt/jenkins/workspace/harmony-release/harmony/internal/chain/reward.go:94","time":"2020-05-28T07:47:29.375059605Z","message":"zero total delegation during AddReward delegation payout"}

This is seen at the first block after epoch transition. at a node in shard 2 (18.188.53.42)

**Comment by rlan35** [comment]
Close for now as we don't see this anymore.
