### ISSUE TITLE
support gometalinter

### ISSUE THREAD

**Issue by mikedoan** [harmony-one/harmony#311]
**Describe the bug**
There is no bug but the current code base does not pass gometalinter.

**To Reproduce**

Install gometalinter
Run at root of our code base
```
gometalinter  ./...
```

Can you ignore all vendor code.

**Expected behavior**

We are looking to increase our code base to the next level. Currently we only have golint checker in travis-ci.

We need help to:
1/ Refactor our code to pass gometalinter
2/ add travis checker for gometalinter after the refactor.

**Comment by harmony-ek** [comment]
I have ~/bin/gml which reads:

    #!/bin/sh
    exec gometalinter --vendor --enable-gc --tests --aggregate --disable=gotype "$@"

Flags:

* `--vendor` – skip vendor directory
* `--enable-gc` – enable garbage collection; helps scanning large repos
* `--tests` – also analyze test files
* `--aggregate` – if multiple linters report similar issues on the same line, aggregate them
* `--disable=gotype` – do not run gotype linter; it is known to be too aggressive (and slow)

**Comment by abitrolly** [comment]
There are more alternatives to `golint` https://github.com/topics/linter?l=go

The main reason to get rid of `golint` is that it doesn't support exclusion masks, which makes CI [more](https://github.com/harmony-one/harmony/blob/master/scripts/golint.sh) [complicated](https://github.com/harmony-one/harmony/blob/master/scripts/list_harmony_go_files.sh) than necessary.

**Comment by lijiang2087** [comment]
@mikedoan no work on this since march 2019? closing for now. cc @LeoHChen
