### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by lcgogo** [harmony-one/harmony#3115]
**Describe the bug**

[one-dockerfile.txt](https://github.com/harmony-one/harmony/files/4701747/one-dockerfile.txt)

When start docker self-build harmony, met followed error:
 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x11296ec]

goroutine 1 [running]:
main.createGlobalConfig(0x7ffddd239f83, 0x7, 0x14589d1)
	/harmony-src/harmony/cmd/harmony/main.go:388 +0x14c
main.main()
	/harmony-src/harmony/cmd/harmony/main.go:698 +0x816

**To Reproduce**
1. Check out code with "sha1" commit
2. Build
3. run local test using "...." commands

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: [debian burst]
- Go environment [ ```1.14``` ]

**Additional context**
VER=2.1.2
docker run -d --name one-${VER} -v /data/one:/data/one -p 9500:9500 one:${VER}-golang1.14-debian  -node_type explorer -blsfolder /data/one/ -network_type=mainnet

**Comment by LeoHChen** [comment]
This is an explorer node, please add `-shard_id=0` to the command line, to specify the shard number.

**Comment by LeoHChen** [comment]
because harmony node will determine the shard id based on the blskey, however, since it is an explorer node, there is no blskey needed (just a dummy one), so you have to specify the shard id explicitly in the cli.

**Comment by lcgogo** [comment]
> because harmony node will determine the shard id based on the blskey, however, since it is an explorer node, there is no blskey needed (just a dummy one), so you have to specify the shard id explicitly in the cli.

Thanks. I can run harmony explorer node now.
