### ISSUE TITLE
Non-critical errors reported from validator nodes

### ISSUE THREAD

**Issue by rlan35** [harmony-one/harmony#3120]
Errors found on Harmony nodes and external validator nodes:

`validator 0xB7a4400cd65B21f66e8627E30046f7a7CdA317D9, min_self_delegation 10000000000000000000000, amount 0: self delegation can not be less than min_self_delegation`

`Invalid pending crosslink RLP decoding`

Not critical error that breaks things. But should dig further to see what's the cause and fix.

If they are expected, we should consider changing the log level away from errors.

**Comment by gupadhyaya** [comment]
```
min_self_delegation 10000000000000000000000, amount 0: self delegation can not be less than min_self_delegation
```
the above error is not harmful, it is happening when the validator is trying to do edit-validator by setting `--active true`. The validator first have to increase their self stake to at least 10k before trying to set it to active. Hence, we are seeing this error repeatedly. 

the `Invalid pending crosslink RLP decoding` should be a different issue though.

**Comment by nyetwurk** [comment]
Note that I had to edit the code to get it to print the validator address; may want to audit all of the txn errors to log the address (and translated to one1xx).

Also it should likely be logged as a json object and not embedded in the error message string

**Comment by nyetwurk** [comment]
> is it possible to update your shard0 db from snapshot?

This did not appear to fix the RLP error so far but I will keep an eye on it.

**Comment by nyetwurk** [comment]
I have resynced shard2 as well and it does not help. My transactions.rlp is zero length.

After debugging some, it seems that `bc.pendingCrossLinksCache.Get()` is returning a zero length byte array.

**Comment by nyetwurk** [comment]
or maybe not :(

Does `DecodeBytes()` modify bytes?

**Comment by nyetwurk** [comment]
looks like bytes[] is short and either ReadPending() or LinksCache.Get() is running out of data

**Comment by nyetwurk** [comment]
it looks like the shard2 db via rclone is wrong. my other shard2 db on another node is drastically different.

**Comment by nyetwurk** [comment]
the clone ends at MANIFEST-117363 but my working shard2 node is MANIFEST-083923
