### ISSUE TITLE
StateDB iteration benchmark

### ISSUE THREAD

**Issue by JackyWYX** [harmony-one/harmony#3160]
### Description

In order to test the state iteration performance, pick a state on mainnet to iterate and see the benchmark.

Tested code here: https://github.com/JackyWYX/harmony/tree/bench_stateIter

**Comment by JackyWYX** [comment]
Run on devop machine with beacon chain, seems to take super quick to iterate over the state:

```
bench testing on block  3434809
elapsed time: 646.816516ms 3854
```

Iterate over 3854 state objects uses 646ms. Seems fast enough for now.

**Comment by rlan35** [comment]
Actually for 3854 nodes, I am surprised it took 0.64s. It's actually slow per node. How did you iterate the state?

**Comment by JackyWYX** [comment]
Sorry, it's 3854 state objects. 

Pasted benchmark here:

```
func (db *DB) BenchIter() {
	timeStart := time.Now()
	it := trie.NewIterator(db.trie.NodeIterator(nil))

	i := 0
	for it.Next() {
		i++
		enc := it.Value
		var acc Account
		rlp.DecodeBytes(enc, &acc)
		db.db.ContractCode(crypto.Keccak256Hash(it.Key[:]), common.BytesToHash(acc.CodeHash))
	}
	elapsed := time.Since(timeStart)
	fmt.Printf("elapsed time: %v %v\n", elapsed, i)
}
```
