### ISSUE TITLE
[Explorer] Explorer nodes behind our rpc endpoint returns different data

### ISSUE THREAD

**Issue by rlan35** [harmony-one/harmony#3190]
So our endpoint have two nodes behind it and one of the node fall behind in synchronization with a few blocks, causing brief data difference between the nodes. 

We should add more health check and monitoring on the rpc endpoint and the explorer node to avoid the data inconsistency issue.

**Comment by janet-harmony** [comment]
Suggestion from TrustWallet: 
> We recommend that you use a minimum of 3 nodes.  And also build a monitoring system sync-state.  It is also quite easy to implement nginx balancing with the active-healthcheck plugin.  And constantly compare on which block of nodes, if any, and so on.

Will look into using NGINX for load balancing.
I think we should run 3 explorer nodes for shard 0, due to high traffic.

**Comment by LeoHChen** [comment]
We can use the following automation to help address the issue.
The entire system can be run from a Jenkins job, executed every 10 minutes or so.

Assuming we are monitoring the nodes on shard0, while we can configured to monitor the end points of different shard.

We can setup 3 explorer nodes, especially for shard 0.

The automation will check the block height of all the explorer nodes, if we found any node is fall behind in terms of block height. The node will be taken away from the target group of the ELB.  Continuously monitor the explorer node, if it caught up on the block height, it can be added back to the target group of the ELB.

For each target group configuration, the target group addition/deletion can be automated.

**Comment by LeoHChen** [comment]
> Suggestion from TrustWallet:
> 
> > We recommend that you use a minimum of 3 nodes.  And also build a monitoring system sync-state.  It is also quite easy to implement nginx balancing with the active-healthcheck plugin.  And constantly compare on which block of nodes, if any, and so on.
> 
> Will look into using NGINX for load balancing.
> I think we should run 3 explorer nodes for shard 0, due to high traffic.

We don't do the nginx load balancing ourselves.  The AWS ELB is the tool we used to do load balancing. It has API to automate end point add/remove.

**Comment by rlan35** [comment]
Also need to monitor disk space.

**Comment by janet-harmony** [comment]
@rlan35 We have space monitoring with Grafana

**Comment by LeoHChen** [comment]
I can setup two more nodes for RPC endpiont, so that TW can use it.
@janet-harmony Can you create the ELB and certificate?

We can use api1.s0.t.hmny.io and api2.s0.t.hmny.io
each target group wil just need one node right now.

**Comment by LeoHChen** [comment]
https://github.com/harmony-one/harmony/issues/3194
