### ISSUE TITLE
Please stop using my unmerged code 

### ISSUE THREAD

**Issue by fxfactorial** [harmony-one/harmony#3213]
Please stop copy pasting code from my unmerged PRs. 

https://github.com/harmony-one/harmony/pull/2948

https://github.com/harmony-one/harmony/pull/2984

Code from these PRs keeps getting piecemeal merged in and I do not appreciate it being merged with no attribution. 

It is fine to use them as inspiration - but there have been many PRs since then have keep copy pasting in my code without attribution. This is not the open source way, it is shameless.

**Comment by rlan35** [comment]
Please be specific about which PR that merged your code? We will attribute to your contribution if the code highly overlap with yours.

**Comment by fxfactorial** [comment]
I can go through the already merged PRs of course, the record is plain and open. 

Here is a contemporary example: 

https://github.com/harmony-one/harmony/pull/2984/files#diff-697b58a8ad3efb7d1ebbd09bcf39efb0R172
![Screenshot from 2020-07-10 11-24-55](https://user-images.githubusercontent.com/3036816/87186257-0acd3d00-c2a0-11ea-8ddb-2ce2d8450d29.png)

And now in this open PR opened 10 hours ago 

https://github.com/harmony-one/harmony/pull/3212/files#diff-697b58a8ad3efb7d1ebbd09bcf39efb0R40

![Screenshot from 2020-07-10 11-26-22](https://user-images.githubusercontent.com/3036816/87186393-47993400-c2a0-11ea-9380-acca7c2101d2.png)

https://github.com/harmony-one/harmony/pull/2984/files#diff-697b58a8ad3efb7d1ebbd09bcf39efb0R37

![Screenshot from 2020-07-10 11-27-26](https://user-images.githubusercontent.com/3036816/87186448-60a1e500-c2a0-11ea-92c4-e91a959b242b.png)

It is literally copy paste. 



Here is an already merged PR that messed up on the copy paste, forgot this init code
![Screenshot from 2020-07-10 11-28-45](https://user-images.githubusercontent.com/3036816/87186586-9d6ddc00-c2a0-11ea-95a1-72576d10af02.png)

https://github.com/harmony-one/harmony/pull/3179/files#diff-42af4b8374f46c9b89aa08fe877a9304R766

take verbatim (with a single word adjustment) from 
https://github.com/harmony-one/harmony/pull/2984/files#


![Screenshot from 2020-07-10 11-34-34](https://user-images.githubusercontent.com/3036816/87187029-5a603880-c2a1-11ea-8728-591998048f20.png)


BootstrapConsensus is a method name introduced for first time to code base in my unmerged PRs. 

I can show at least 10 more examples.

**Comment by fxfactorial** [comment]
Resolved with RJ offline - I am content now.
