### ISSUE TITLE
 running gcc failed: exit status 1

### ISSUE THREAD

**Issue by ShallMate** [harmony-one/harmony#3214]
When I try to allow the project locally (ubuntu18.04) or docker, the following problems occur. May I ask what caused it?

 /root/.gimme/versions/go1.14.1.linux.amd64/pkg/tool/linux_amd64/link: running gcc failed: exit status 1
/tmp/go-link-961815564/000008.o: In function `_cgo_26061493d47f_C2func_getaddrinfo':
cgo_unix.cgo2.c:(.text+0x81): warning: Using 'getaddrinfo' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/root/go/src/github.com/harmony-one/bls/lib/libbls384_256.a(bls_c384_256.o): In function `mclBnFr_setLittleEndian':
/root/go/src/github.com/harmony-one/mcl/include/mcl/fp.hpp:356: undefined reference to `mcl::fp::copyAndMask(unsigned long*, void const*, unsigned long, mcl::fp::Op const&, mcl::fp::MaskMode)'
/root/go/src/github.com/harmony-one/bls/lib/libbls384_256.a(bls_c384_256.o): In function `mclBnFr_setLittleEndianMod':
/root/go/src/github.com/harmony-one/mcl/include/mcl/fp.hpp:337: undefined reference to `mcl::fp::copyAndMask(unsigned long*, void const*, unsigned long, mcl::fp::Op const&, mcl::fp::MaskMode)'
/root/go/src/github.com/harmony-one/bls/lib/libbls384_256.a(bls_c384_256.o): In function `mclBnFr_setByCSPRNG':
/root/go/src/github.com/harmony-one/mcl/include/mcl/fp.hpp:356: undefined reference to `mcl::fp::copyAndMask(unsigned long*, void const*, unsigned long, mcl::fp::Op const&, mcl::fp::MaskMode)'
/root/go/src/github.com/harmony-one/bls/lib/libbls384_256.a(bls_c384_256.o): In function `mclBnFr_setHashOf':
/root/go/src/github.com/harmony-one/mcl/include/mcl/fp.hpp:356: undefined reference to `mcl::fp::copyAndMask(unsigned long*, void const*, unsigned long, mcl::fp::Op const&, mcl::fp::MaskMode)'
/root/go/src/github.com/harmony-one/bls/lib/libbls384_256.a(bls_c384_256.o): In function `mclBnFp_setLittleEndian':
/root/go/src/github.com/harmony-one/mcl/include/mcl/fp.hpp:356: undefined reference to `mcl::fp::copyAndMask(unsigned long*, void const*, unsigned long, mcl::fp::Op const&, mcl::fp::MaskMode)'
/root/go/src/github.com/harmony-one/bls/lib/libbls384_256.a(bls_c384_256.o):/root/go/src/github.com/harmony-one/mcl/include/mcl/fp.hpp:337: more undefined references to `mcl::fp::copyAndMask(unsigned long*, void const*, unsigned long, mcl::fp::Op const&, mcl::fp::MaskMode)' follow
/root/go/src/github.com/harmony-one/bls/lib/libbls384_256.a(bls_c384_256.o): In function `mcl::fp::Op::~Op()':
/root/go/src/github.com/harmony-one/mcl/include/mcl/op.hpp:262: undefined reference to `mcl::fp::Op::destroyFpGenerator(mcl::fp::FpGenerator*)'
/root/go/src/github.com/harmony-one/bls/lib/libbls384_256.a(bls_c384_256.o): In function `mcl::FpT<mcl::bn::local::FpTag, 384ul>::init(bool*, int, __gmp_expr<__mpz_struct [1], __mpz_struct [1]> const&, mcl::fp::Mode)':
/root/go/src/github.com/harmony-one/mcl/include/mcl/fp.hpp:133: undefined reference to `mcl::fp::Op::init(__gmp_expr<__mpz_struct [1], __mpz_struct [1]> const&, unsigned long, int, mcl::fp::Mode, unsigned long)'
/root/go/src/github.com/harmony-one/bls/lib/libbls384_256.a(bls_c384_256.o): In function `mcl::FpT<mcl::bn::local::FrTag, 256ul>::init(bool*, int, __gmp_expr<__mpz_struct [1], __mpz_struct [1]> const&, mcl::fp::Mode)':
/root/go/src/github.com/harmony-one/mcl/include/mcl/fp.hpp:133: undefined reference to `mcl::fp::Op::init(__gmp_expr<__mpz_struct [1], __mpz_struct [1]> const&, unsigned long, int, mcl::fp::Mode, unsigned long)'
/root/go/src/github.com/harmony-one/bls/lib/libbls384_256.a(bls_c384_256.o): In function `void mcl::FpT<mcl::bn::local::FpTag, 384ul>::setArray<unsigned char>(bool*, unsigned char const*, unsigned long, mcl::fp::MaskMode)':
/root/go/src/github.com/harmony-one/mcl/include/mcl/fp.hpp:337: undefined reference to `mcl::fp::copyAndMask(unsigned long*, void const*, unsigned long, mcl::fp::Op const&, mcl::fp::MaskMode)'
/root/go/src/github.com/harmony-one/bls/lib/libbls384_256.a(bls_c384_256.o): In function `void mcl::Fp2T<mcl::FpT<mcl::bn::local::FpTag, 384ul> >::setArray<unsigned char>(bool*, unsigned char const*, unsigned long)':
/root/go/src/github.com/harmony-one/mcl/include/mcl/fp.hpp:337: undefined reference to `mcl::fp::copyAndMask(unsigned long*, void const*, unsigned long, mcl::fp::Op const&, mcl::fp::MaskMode)'
/root/go/src/github.com/harmony-one/mcl/include/mcl/fp.hpp:337: undefined reference to `mcl::fp::copyAndMask(unsigned long*, void const*, unsigned long, mcl::fp::Op const&, mcl::fp::MaskMode)'
/root/go/src/github.com/harmony-one/bls/lib/libbls384_256.a(bls_c384_256.o): In function `bool mcl::SquareRoot::get<mcl::FpT<mcl::bn::local::FpTag, 384ul> >(mcl::FpT<mcl::bn::local::FpTag, 384ul>&, mcl::FpT<mcl::bn::local::FpTag, 384ul> const&) const':
/root/go/src/github.com/harmony-one/mcl/include/mcl/fp.hpp:337: undefined reference to `mcl::fp::copyAndMask(unsigned long*, void const*, unsigned long, mcl::fp::Op const&, mcl::fp::MaskMode)'
/root/go/src/github.com/harmony-one/bls/lib/libbls384_256.a(bls_c384_256.o): In function `mcl::FpT<mcl::bn::local::FpTag, 384ul>::squareRoot(mcl::FpT<mcl::bn::local::FpTag, 384ul>&, mcl::FpT<mcl::bn::local::FpTag, 384ul> const&)':
/root/go/src/github.com/harmony-one/mcl/include/mcl/fp.hpp:337: undefined reference to `mcl::fp::copyAndMask(unsigned long*, void const*, unsigned long, mcl::fp::Op const&, mcl::fp::MaskMode)'
/root/go/src/github.com/harmony-one/bls/lib/libbls384_256.a(bls_c384_256.o):/root/go/src/github.com/harmony-one/mcl/include/mcl/fp.hpp:356: more undefined references to `mcl::fp::copyAndMask(unsigned long*, void const*, unsigned long, mcl::fp::Op const&, mcl::fp::MaskMode)' follow
collect2: error: ld returned 1 exit status

**Comment by sophoah** [comment]
Hi, can you retry what you are doing using : https://hub.docker.com/r/harmonyone/main ?

I believe this is an environment issue,

**Comment by ShallMate** [comment]
@sophoah  Sorry to bother you, I tried to use the docker image you sent me. Still the same problem, I followed the operation on the README. This will be the case when operating to test/debug.sh, is there any other possibility that would cause this situation?

**Comment by sophoah** [comment]
@ShallMate can you post everything that you were doing (all commands) that leads to the error. When you use the test/debug.sh do you have the same error ?

**Comment by sophoah** [comment]
@ShallMate i will close the issue for now, Feel free to reopen if you still have issues
