### ISSUE TITLE
[optimization] duplicated commit message signature verification consumed quite a lot of CPU on leader

### ISSUE THREAD

**Issue by LeoHChen** [harmony-one/harmony#3225]
## Summary

Seemingly duplicated commit message signature verification consumed lots of CPU.

## Current Design

When the leader is handling the consensus messages, the leader always do a senderKeySanityChecks call for every message,
https://github.com/harmony-one/harmony/blob/14e017defc18d712a854f70104e173e6eea9c058/consensus/checks.go#L41

However, during the process of commit/prepare message, the leader will check the signature of the commit messages again, 
https://github.com/harmony-one/harmony/blob/14e017defc18d712a854f70104e173e6eea9c058/consensus/leader.go#L192

## Problems

Duplicated deserialized and verification consumed a lot of leader's CPU, which leads to slow consensus and can't collect 100% of signatures from all validators on time.

## Proposal

Deep dive and reduce duplicated signature verification.

**Comment by rlan35** [comment]
The two signatures are serving different purpose. Once is signing on the p2p message to make sure that the sender is legit. the other signature is signed on the block to make sure it's a valid consensus signature.

We can think about clever way to avoid the first type of signature checking possibly by tagging on the second type.

**Comment by LeoHChen** [comment]
Thanks @rlan35  for the explanation.  So, the main purpose of the first check is to make sure the message sender is legit.

In this regard, I don't think we need to verify or even do the first signature to serve the purpose.  As our network is an open network, anyone can send any messages to the p2p network, we didn't have any protection before at p2p layer. The verification logic is already in the application layer.

Also, the current p2p messages are encrypted already at p2p layer.  If we intend to filter out invalid senders, it should be done at the peer discovery service to prevent them from connecting to the p2p network. Like using some advanced logic at boot node.

Since the signature verification is quite heavy using bls signing, it is actually becoming the weakest link if we have to verify every single message.  A valid defense in this case would be like PoW. Taking quite some effort to sign the message and minimal effort to verify it.  Right now, in our case, to verify the sign take most of the time/cpu as RJ benchmarked in https://github.com/harmony-one/harmony/pull/3211, which didn't' serve the purpose of defense.

So, I suggest we shall remove the first sanity check and only keep the second one to make sure the payload is signed properly.  This can save quite some CPU time of leader, especially during the final commit phase.

**Comment by LeoHChen** [comment]
And we already have the 2nd check, which means illegal sender still can't compromise the consensus.  That's good enough.

**Comment by LeoHChen** [comment]
Looking at the message.proto (https://github.com/harmony-one/harmony/blob/14e017defc18d712a854f70104e173e6eea9c058/api/proto/message/message.proto#L38), the key payload in the message is the `request`, which is verified in onCommit (https://github.com/harmony-one/harmony/blob/14e017defc18d712a854f70104e173e6eea9c058/consensus/leader.go#L242).

The only additional content in the p2p message is just the service type and message type.  I don't think there are additional values to do duplicated verification here.

**Comment by LeoHChen** [comment]
I run my PR on the leader node (after viewchange) on shard2 of mainnet, we can see that the consensus can be reached within 2 seconds with 100% commits collected.


```
[ec2-user@ip-172-31-14-184 ~]$ tail -f latest/zerolog-validator-18.182.14.198-9000.log | grep -E 'PROP|NumCommits'
{"level":"info","port":"9000","ip":"18.182.14.198","blockNum":3970286,"caller":"/home/lc/go/src/github.com/harmony-one/harmony/node/node_newblock.go:49","time":"2020-07-16T09:00:05.298930882Z","message":"PROPOSING NEW BLOCK ------------------------------------------------"}
{"level":"info","port":"9000","ip":"18.182.14.198","myBlock":3970286,"myViewID":3970440,"phase":2,"mode":"Normal","NumCommits":252,"caller":"/home/lc/go/src/github.com/harmony-one/harmony/consensus/consensus_v2.go:105","time":"2020-07-16T09:00:07.402840154Z","message":"[finalizeCommits] Finalizing Block"}
{"level":"info","port":"9000","ip":"18.182.14.198","blockNum":3970287,"caller":"/home/lc/go/src/github.com/harmony-one/harmony/node/node_newblock.go:49","time":"2020-07-16T09:00:13.29899408Z","message":"PROPOSING NEW BLOCK ------------------------------------------------"}
{"level":"info","port":"9000","ip":"18.182.14.198","myBlock":3970287,"myViewID":3970441,"phase":2,"mode":"Normal","NumCommits":252,"caller":"/home/lc/go/src/github.com/harmony-one/harmony/consensus/consensus_v2.go:105","time":"2020-07-16T09:00:14.940862377Z","message":"[finalizeCommits] Finalizing Block"}
{"level":"info","port":"9000","ip":"18.182.14.198","blockNum":3970288,"caller":"/home/lc/go/src/github.com/harmony-one/harmony/node/node_newblock.go:49","time":"2020-07-16T09:00:21.299092107Z","message":"PROPOSING NEW BLOCK ------------------------------------------------"}
{"level":"info","port":"9000","ip":"18.182.14.198","myBlock":3970288,"myViewID":3970442,"phase":2,"mode":"Normal","NumCommits":252,"caller":"/home/lc/go/src/github.com/harmony-one/harmony/consensus/consensus_v2.go:105","time":"2020-07-16T09:00:23.064898822Z","message":"[finalizeCommits] Finalizing Block"}
{"level":"info","port":"9000","ip":"18.182.14.198","blockNum":3970289,"caller":"/home/lc/go/src/github.com/harmony-one/harmony/node/node_newblock.go:49","time":"2020-07-16T09:00:29.299159031Z","message":"PROPOSING NEW BLOCK ------------------------------------------------"}
{"level":"info","port":"9000","ip":"18.182.14.198","myBlock":3970289,"myViewID":3970443,"phase":2,"mode":"Normal","NumCommits":252,"caller":"/home/lc/go/src/github.com/harmony-one/harmony/consensus/consensus_v2.go:105","time":"2020-07-16T09:00:31.024328509Z","message":"[finalizeCommits] Finalizing Block"}
```

**Comment by LeoHChen** [comment]
The CPU of the leader on shard2 didn't exceed 30% on average.

![image](https://user-images.githubusercontent.com/4513927/87651984-7c761280-c708-11ea-937f-fe8339c7edc4.png)
