### ISSUE TITLE
Dev Environment Setup

### ISSUE THREAD

**Issue by Avni-Sharma** [harmony-one/harmony#323]
While Dev Environment Setup there was a command go get ./...
but it wasn't able to execute fully since the package btcsuite/btcd needs to run this command explicitly GO111MODULE=on go install -v . ./cmd/...
When I was trying to run go get ./... , then by default for this package it was taking GO111MODULE = auto hence resulting in a failure to get this package.
Instead we can make a makefile that gets this package and explicitly runs that command
and do go get -u https://github.com/btcsuite/btcd
Or the document can be updated with this scenario

**Comment by LeoHChen** [comment]
@Avni-Sharma , what's the error you seen when you run "go get ./..."?   Can you put your output of "go env" command?

I think maybe you are using go 1.11 by default and our environment setting was tested on 1.10, which has no module support.

**Comment by Avni-Sharma** [comment]
Yes, I am using go lang version 1.11.4

**Comment by Avni-Sharma** [comment]
![screenshot from 2019-01-26 22-34-20](https://user-images.githubusercontent.com/18097007/51790405-d6081b80-21ba-11e9-882b-dde71aafb211.png)

**Comment by LeoHChen** [comment]
Thanks. What's the error message you seen?

**Comment by alajko** [comment]
@Avni-Sharma do you mind sharing the error message, so we can better assist you :)

**Comment by Avni-Sharma** [comment]
I resolved it by doing go get -u https://github.com/btcsuite/btcd,  and getting this on my system by going through their documentation. I am unable to reproduce the error since I resolved it.
