### ISSUE TITLE
Address data type bug 

### ISSUE THREAD

**Issue by vikramIde** [harmony-one/harmony#3233]
**Describe the bug**
in smart contract we have 

addresse: datatype 

It only accept ethereum address  ```0ex```

Are you guys able to use ```one``` in this?

**To Reproduce**

So I have a smart contract which has an admin account address 

Truffle didn't let me add Harmony address so i converted it to equivalent address of eth and added

Next, when I tried to update the smart contract as admin it says the account doesn't match
Because it's checking the from part of the transaction which is trying to make the changes.
And that from part has Harmony one account

**Expected behavior**
In truffle I should be able to set Harmony account address as admin account for smart contracts

**Smart Contract to test**
https://github.com/Vishwas1/hinr-contract

@gupadhyaya

**Comment by ajaya-man** [comment]
@vikramIde Which tool you are using to make the contracts upgradeable?

**Comment by adsorptionenthalpy** [comment]
The issue has been open for 3 years without followup from the author. Closing.
