### ISSUE TITLE
[OPS] Explorer get overwhelmed by RPC 

### ISSUE THREAD

**Issue by JackyWYX** [harmony-one/harmony#3236]
Shard 0 explorer node is behaving abnormal between 10:30 ~ 11:30 these days. 

CPU usage:

![Screen Shot 2020-07-17 at 11 13 14 PM](https://user-images.githubusercontent.com/40162696/87846214-1d88d880-c883-11ea-9bb5-1057b8abbe6c.png)

We can see a CPU usage spike at around 10:00 p.m. 

Looking at the logs, it seems that a lot of RPC requests are handled during this period. Just for two RPC calls `GetStakingTransactionsCount` and `GetTransactionCount`, **274** requests are made in 8 minutes (between 2020-07-18T05:46:45 and 2020-07-18T05:54:00). Among all these requests, a single address is queried multiple times (Randomly choose an address being requested, 18 times in 8 minutes). 

So is there any possibility that our app program or external partners are querying the explorer node too frequently?

**Comment by JackyWYX** [comment]
After seperated the explorer backend from public endpoint, only the explorer backend node is having high CPU usage in the second day. So it should be explorer cronjob stuff. Please Yuriy take a lot at this issue.

**Comment by rlan35** [comment]
Fixed by Jacky's rpc change.
