### ISSUE TITLE
[DISCUSS] Shall we move kernel env setting to harmony binary?

### ISSUE THREAD

**Issue by JackyWYX** [harmony-one/harmony#3257]
## Description

This is the technical discussion about whether to move the `sysctl` kern parameter settings to harmony binary file. When I am doing the project `remove node.sh`, the following code block is currently in script `node.sh`.

```
function setup_env
{
   check_root
   ### KERNEL TUNING ###
   # Increase size of file handles and inode cache
   sysctl -w fs.file-max=2097152
   # Do less swapping
   sysctl -w vm.swappiness=10
   ...
}
```

This code block is executed when user is running node.sh as root user to fine tune the Linux kernel parameters. However, there should be both advantage and disadvantages to move this code logic into the binary file:

### Advantage

1. Node operators does not need to know exactly what the kernel configuration is, and can achieve best performance as long as node operator use recommended instance configurations.

### Disadvantage

1. `harmony` binary is basically an application by nature. An application program shall never hijack kernel settings and do decisions that should be only made by human users.
2. If we write this logic to binary file, we are actually enforcing our kernel settings on the node operators' system. If user want to do some customized kernel settings which collides with our setting fields, users' settings will be overwritten every time the binary is started, which is a very bad idea.
3. Our parameters are only valid for a specific system and only optimized for our recommended configuration. However, the Golang binary is expected to be cross-platform. 

So here are several solutions:

### Solution 1

Add os-wise kernel settings in harmony binary. If operating system is "linux" and the command is executed as root user, apply predefine kernel settings.

### Solution 2

Do not add kernel setting in harmony binary. Provide the kernel params tuning along with the recommended instance configuration. Leave it for users to configure it themselves. 

> Note: node.sh can still be the running source for our hosting node and be shared with our users as an alternative to run node with all predefined kernel params.

Please let me know your idea about this topic. @rlan35 @LeoHChen @SebastianJ @gupadhyaya @Daniel-VDM

**Comment by Daniel-VDM** [comment]
As you mention, the `harmony` binary is an application, so I don't think it should modify kernel configs. Instead, I think we should keep the functionality at the `node.sh` level. We could also go one step ahead and allow the user to save the tunes in the `sysctl.conf` file so that it persists through system resets.

**Comment by JackyWYX** [comment]
> As you mention, the `harmony` binary is an application, so I don't think it should modify kernel configs. Instead, I think we should keep the functionality at the `node.sh` level. We could also go one step ahead and allow the user to save the tunes in the `sysctl.conf` file so that it persists through system resets.

Thank you for you comment, and I cannot agree more. I especially like the conf file idea, but only one concern in my mind: Is this config file making node.sh more complexer for node operators? Users used to download one file for starting node, but now, need download 2. What's your idea on this?

**Comment by sophoah** [comment]
@JackyWYX so just to share with you how P-OPS are doing. We have our own set of kernel settings that match our system. it is done once when the node is installed at the beginning and will persist at reboot. Like this we never have to run node.sh with root privilege. 
Now, I agree with Daniel, Harmony binary shouldn't update the kernel. Maybe when harmony binary start, you could do a simple test to detect if kernel was updated and let the user know how he can improve the performance. (ie we would have a simple bash script that does the kernel change like today with the node.sh)

**Comment by JackyWYX** [comment]
@sophoah Thanks for sharing your ideas. Your idea is great: to inform user about there could be potential optimization resources. But there is two questions to answer:
1. What is the component where we shall put these logics. As far as I see, the ops related settings should not couple with the application itself. So I would recommend to put it into the wrapper of harmony binary like auto node.
2. Whether to provide the scripts or commands. It's actually a common practice to share commands instead of providing scripts for security concerns. I know providing a script is a lot easier for users, but a downside of it is that it is also a common practice for hackers to hijack your computer - providing a malicious script. So in very rare cases I see a mature enterprise would configure the kernel settings for users. Instead, providing a recommended would be a better practice.
