### ISSUE TITLE
[DISCUSS] Broadcast invalid transaction

### ISSUE THREAD

**Issue by JackyWYX** [harmony-one/harmony#3263]
## Summary

Currently, there is an option in command line interface to choose whether to broadcast invalid transactions. This option should be always turned off in the production network, since a malicious attacker is able to easily paralyze the whole network when composing a lot of random transactions. So in the long term, the broadcast invalid transaction option should be default to false and be removed.

Another problem here is whether setting this flag to false will really preventing broadcasting invalid transaction. According to my understanding of the code, the answer is no. The flag value determines whether to broadcast at the transaction pool. However, the message is still be broadcasted in pubsub since there is no rejection in the p2p validation. Actually in current implementation, the txn broadcast is triggered twice:

1. Pubsub forwarding message in node.Start.
2. After added to local transaction pool, broadcast again.

The first broadcast takes O(n) network and CPU resource while the second broadcast takes O(n^2) network and CPU resource. And the flag is only disabling the second broadcasting and have nothing to do with the first one. So in order to totally address this problem, code modification in pubsub validation should be taken place. 

So here is the design ideas for discussion:

1. Since invalid txns will be broadcasted to the whole network even if the flag is set to false, the flag can be removed and have no service interruption. 
2. TxPool should validate the transaction message at pubsub validation. Provide the flag here to determine the message forwarding logic, whether to Reject, Ignore or Accept.
3. Investigate how to get rid of all services' dependency on broadcast invalid transaction feature.

Please let me know your ideas @SebastianJ @LeoHChen @rlan35 @LeoHChen @Daniel-VDM . Thanks

**Comment by rlan35** [comment]
The BroadcastInvalidTx flag is actually only meant for the txns submitted through RPC. So if a user submit a invalid txn to our explorer node (or any nodes), the explorer node won't broadcast it into p2p layer. 

Currently there is no code that sends a constructed txn directly into p2p layer. 

The original reason why it's a flag broadcastInvalidTx not directly hard coded to false, is because in some case the node is out of sync and thus can mark a valid txn invalid, thus blocking it from sending into the network.

**Comment by JackyWYX** [comment]
> Currently there is no code that sends a constructed txn directly into p2p layer.

You are right. So there can be come interruption of the existing service if remove this flag. Better to keep this flag for non-interruption of the existing services.

> The original reason why it's a flag broadcastInvalidTx not directly hard coded to false, is because in some case the node is out of sync and thus can mark a valid txn invalid, thus blocking it from sending into the network.

I see the point. But this is not a valid production blockchain behavior, so vulnerable to attacks. Might investigate later.
