### ISSUE TITLE
node.sh fails to auto restart and grab new binary

### ISSUE THREAD

**Issue by mindstyle85** [harmony-one/harmony#3264]
**Describe the bug**

either on tmux or systemd, a node with auto update enabled, will download the new binary, but the node.sh wont restart so we have a running version that is older, as seen here:

./node.sh -V
Binary  Version: Harmony (C) 2020. harmony, version v6154-v2.3.1-0-g16c1b062 (jenkins@ 2020-07-28T21:17:17+0000)
Running Version: Harmony (C) 2020. harmony, version v6065-v2.1.7-0-g6b435a8d (jenkins@ 2020-06-22T20:38:09+0000)

**Comment by LeoHChen** [comment]
Please provide your command line option on how you start `node.sh`

**Comment by LeoHChen** [comment]
Please provide the running version of `node.sh` as well, using`node.sh -v`

**Comment by mindstyle85** [comment]
its run with: node.sh -S -z -M

./node.sh -v
node.sh: version: v1 20200723.0 

the older node.sh version doesnt output "running version" anyways, just binary version
