### ISSUE TITLE
Rcclone not working 

### ISSUE THREAD

**Issue by zillabytes** [harmony-one/harmony#3280]
this is the error
 rclone -P sync mainnet:pub.harmony.one/mainnet.min/harmony_db_0 harmony_db_0
2020/08/04 08:27:17 Failed to load config file "/root/.config/rclone/rclone.conf": could not parse line: cat<<-EOF > ~/.config/rclone/rclone.conf

here's the config of rclone.conf
cat<<-EOF >> ~/.config/rclone/rclone.conf
[mainnet]
type = s3
provider = AWS
env_auth = false
region = us-west-1
acl = public-read
server_side_encryption = AES256
storage_class = REDUCED_REDUNDANCY
EOF

**Comment by sophoah** [comment]
@zillabytes was your issue fixed ? content of the rclone.conf should only be 
[mainnet]
type = s3
provider = AWS
env_auth = false
region = us-west-1
acl = public-read
server_side_encryption = AES256
storage_class = REDUCED_REDUNDANCY

**Comment by LeoHChen** [comment]
closed, unless further issues reported.
