### ISSUE TITLE
Funds lost in transactions to Contract with low gas

### ISSUE THREAD

**Issue by mirrormirage0** [harmony-one/harmony#3282]
**Describe the bug**
Trying to send a transaction to a contract with low gas, deducts the amount from sender, but is not credited to the smart contract.
Transaction status shows as success.

**To Reproduce**
1. Use harmony wallet and send a transaction to one1dpeksrqq4t7eqrrjqvy6ftcp2nhpyyzj6c5jxp. (This is a contract address)
2. Transaction will confirm and be available on explorer. https://explorer.pops.one/#/tx/0xe82fbb2f4f4d87bff17dba432669d87c26fc5923b324ee9eba7c2033b8bf6aba
3. Amount is deducted from sender.(https://explorer.pops.one/#/address/one1s0g5tt3se3qfwv9fn4zwtwvj4fdvefxvxn4nwh)  But not credited to the receiver contract address.
4. Try to send a second transaction with higher gas (0.000126), transaction confirms https://explorer.pops.one/#/tx/0xec4086245c9ffd4ae079350bb799565a5bdc2a4122911c65beef1a64b0d757d3 and fund is credited to the contract.

Optional:
5. A second attempt was done through harmony wallet. (https://explorer.pops.one/#/tx/0x9f7551099b77addb64ba45bf5bd1a9e3c1d63a4bc4d5beba6af7eeb623725d57) . This transaction confirmed as well. Funds were deducted. (https://explorer.pops.one/#/tx/0x9f7551099b77addb64ba45bf5bd1a9e3c1d63a4bc4d5beba6af7eeb623725d57). But not credited to the receiving contract. 

Summary:
There were 3 transactions, 10K , 1K , 10K. but the receiving contract has only received 10K 
Only the high gas transaction confirmed. For the others, the fund is lost from the sender.

**Comment by rlan35** [comment]
What does the contract look like? 

This part of the code is based on EVM and I just looked at the code and didn't find anything suspicious. Could you try the same in Ethereum and see if there is any difference?

**Comment by mirrormirage0** [comment]
It looks like something has been updated in the ONE-Wallet UI

Now, it gives me a - cannot confirm transaction error on the UI, if there is low gas.

There is no longer a deduction from sender's wallet as is the case above.

Only gas is deducted for the failed transaction. This is expected behavior.

Hence the issue can now be considered as a Dashboard UI issue , rather than funds being lost. Still not sure on how the first case occurred of funds being lost.

The dashboard however still shows the transaction status as success which is very misleading.


Contract address -> 0x6873680c00aaFd900c720309a4Af0154Ee121052
Contract's wallet address -> one1dpeksrqq4t7eqrrjqvy6ftcp2nhpyyzj6c5jxp
New Sender -> one19atfrdn44c3jh5etvugw3a7vmzhtpaxasap987
Initial balance = 10,000 (https://explorer.testnet.harmony.one/#/tx/0x8bab01e887c2ec603d54c9092d41b2b7a96bf5d0d7bccc01150e214d266dea69)

Did some tests with 5K transfer.
Doing a test again to document 

Receiver Contract's balance - 495001
![image](https://user-images.githubusercontent.com/29485946/89633982-ae1c6c80-d8b5-11ea-8b52-5becaa06e54c.png)
https://explorer.testnet.harmony.one/#/address/one1dpeksrqq4t7eqrrjqvy6ftcp2nhpyyzj6c5jxp

Doing a transfer of 1000 from one19atfrdn44c3jh5etvugw3a7vmzhtpaxasap987 to contract wallet.
This time the ONE wallet UI threw an error - cannot confirm transaction. (This is different from the previous behaviour where the transaction was showing as success. Not sure if something changed in ONE wallet)

But if we check the explorer, can see that the transaction is succesful. (Misleading bug)
https://explorer.pops.one/#/tx/0x60a8976923b7db2d8e7fdd7717ad219d6e59b9b5a02541a6fa57cdc92715715c

Checking balance of contract - 495001 (Balance is unchanged)
Checking balance of sender - 9999 (10K-gas fees). As expected. good!

Which means , the above transaction which shows as success never succeeded. 
https://explorer.pops.one/#/tx/0x60a8976923b7db2d8e7fdd7717ad219d6e59b9b5a02541a6fa57cdc92715715c

Hence, this is now a Dashboard UI issue of failed transactions appearing as success both on wallet balance and individual transaction address, and not related to the core transaction send/receive of contracts/wallets.


**Contract Source code**
```
pragma solidity ^0.6.0;

import "@openzeppelin/contracts-ethereum-package/contracts/access/Ownable.sol";
import "@openzeppelin/contracts-ethereum-package/contracts/Initializable.sol";

contract HarmonyFaucet  is OwnableUpgradeSafe {

    //Variables
	mapping(address => uint256) public requestedAddressMapping;
    uint256 public sendAmount;
    uint256 public blockHeight;

    // Events
    event EtherRequested(address indexed fromAddress, uint256 indexed sentAmount);
    event EtherSent(address indexed toAddress);
    event EtherReceived(address Sender, uint amount);
    event Log(string msg);

    function initialize() public initializer {
        sendAmount = 5000000000000000000000;
        blockHeight = 17280;
    }

    function transferAmount(address receiverAddress) public {
        uint256 currentBlock = block.number;
        require(requestedAddressMapping[receiverAddress] == 0 || currentBlock - requestedAddressMapping[receiverAddress] >= blockHeight,
                "Address has been funded within the last hour");
        require(address(this).balance > sendAmount, "Not enough funds in faucet");
        requestedAddressMapping[receiverAddress] = currentBlock;
        address payable receiver = address(uint160(receiverAddress));
		receiver.transfer(sendAmount);
        emit EtherSent(receiverAddress);
	}

    function setRate(uint256 _sendAmount) public onlyOwner {
		sendAmount = _sendAmount;
	}

    function setBlockHeight(uint256 _blockHeight) public onlyOwner {
		blockHeight = _blockHeight;
	}

    receive() external payable {
        emit EtherReceived(msg.sender, msg.value);
    }
}
```

**Comment by LeoHChen** [comment]
@mirrormirage0 , is it still an issue with onewallet?

**Comment by mirrormirage0** [comment]
Closing this, since its no longer an issue.

Use ONE Wallet version 1.0.7
While transferring funds to Contract address (e.g. one1k7let7z38xrnyvgtzsfd7gr4c5tl0f08ycysxh) on testnet, modify the gas limit from 25000 to 260000. 
Transaction goes through. Explorer shows status as "Success". Contract balance is updated.

**Comment by mirrormirage0** [comment]
Re-test with ONE Wallet 1.0.7 

Attempt with default gas fees (which used to fail before, succeeds now)

Wallet Balance - 5,992,392.8290
Contract Address - one1k7let7z38xrnyvgtzsfd7gr4c5tl0f08ycysxh
Contract Balance - 1094300
Amount Transferred - 1000
Gas Limit (Default) - 25000
Tx - https://explorer.pops.one/#/tx/0xc4061f49fcc9e4e4f2329468f5929effdd34989217d0f22f83c7493af1e8db2e
TX shows status as "Success"
Wallet Balance - 5,991,392.8290 (1000 $ONE deducted)
Contract Balance - 1095300.00000 (added 1000 $ONE)

Attempt with extremely low gas (Want it to fail)
Wallet Balance - 5,991,392.8290
Contract Balance - 1095300.00000
Try with Gas Limit 25.
Gets a valid Error Message "Error: Transaction confirm failed. Network fee is not enough or something went wrong."
Good!

Attempt with 2500 Gas Fees.
Gets valid error message "Error: Transaction confirm failed. Network fee is not enough or something went wrong."
Good!
