### ISSUE TITLE
[Feature] Return VM error

### ISSUE THREAD

**Issue by JackyWYX** [harmony-one/harmony#3284]
# Problem/limitation At Hand

Currently, if a smart contract call fails, the vm error will not show up and the call / transaction just fail silently. This is because the vmerr is not returned at function `ApplyMessage`:

```
// core/state_transition.go:265
return ret, st.gasUsed(), vmerr != nil, err
```

Notice that only success/failed is returned but not the specific error. On the other side, Ethereum code returns the vmerror explicitly:

```
return &ExecutionResult{
	UsedGas:    st.gasUsed(),
	Err:        vmerr,
	ReturnData: ret,
}, nil
```

So we need to return this error explicitly, and further error sink vmerr as well.

**Which component?**

* consensus
* evm
* RPC
* All SDK

# Proposed Solution

1. Return the error as Ethereum does in `ApplyMessage`. Wrap the result with a structure. (Having too many return values is not favored).
2. Update all function call signatures of the `ApplyMessage` in consensus miner and RPC.
3. Update all SDK for new vmErr as return value.

# Additional Context

For temporary solution:
1. Add fmt.Println(vmerr) in code.
1. Compile and run a local node.

**Comment by rlan35** [comment]
vmerr is added to ExecutionResult in Harmony now. Closing this.
