### ISSUE TITLE
Add unit tests for crypto/bls/bls.go

### ISSUE THREAD

**Issue by rlan35** [harmony-one/harmony#329]

**Comment by animesh371** [comment]
I think this can be closed. I have added tests in crypto/bls/bls.go as a part of https://github.com/harmony-one/harmony/pull/499. 

Test Coverage :- 
github.com/harmony-one/harmony/crypto/bls/bls.go:10:			init					100.0%
github.com/harmony-one/harmony/crypto/bls/bls.go:15:			AggregateSig				100.0%
github.com/harmony-one/harmony/crypto/bls/bls.go:34:			NewMask					100.0%
github.com/harmony-one/harmony/crypto/bls/bls.go:57:			Mask					100.0%
github.com/harmony-one/harmony/crypto/bls/bls.go:64:			Len					100.0%
github.com/harmony-one/harmony/crypto/bls/bls.go:71:			SetMask					83.3%
github.com/harmony-one/harmony/crypto/bls/bls.go:92:			SetBit					100.0%
github.com/harmony-one/harmony/crypto/bls/bls.go:111:			GetPubKeyFromMask			100.0%
github.com/harmony-one/harmony/crypto/bls/bls.go:130:			IndexEnabled				100.0%
github.com/harmony-one/harmony/crypto/bls/bls.go:141:			KeyEnabled				100.0%
github.com/harmony-one/harmony/crypto/bls/bls.go:151:			SetKey					100.0%
github.com/harmony-one/harmony/crypto/bls/bls.go:162:			CountEnabled				100.0%
github.com/harmony-one/harmony/crypto/bls/bls.go:176:			CountTotal				100.0%
github.com/harmony-one/harmony/crypto/bls/bls.go:181:			AggregateMasks				100.0%
github.com/harmony-one/harmony/crypto/bls/bls.go:210:			Check					100.0%
github.com/harmony-one/harmony/crypto/bls/bls.go:222:			NewThresholdPolicy			100.0%
github.com/harmony-one/harmony/crypto/bls/bls.go:228:			Check					100.0%
