### ISSUE TITLE
{Testnet} syncing issues

### ISSUE THREAD

**Issue by mindstyle85** [harmony-one/harmony#3292]
**Describe the bug**

1. i tried it with rclone for testned and also syncing from scratch
2. in both cases i got stuck at some point, with the same error messages. The block at which it gets stuck is:

 "block-number": 626999,
      "epoch": 16499,
      "shard-id": 0,
      "view-id": 627012

if using rclone it has more blocks than this, but same error and issue, it doesnt not sync further than what rclone provided.

the erros:

`{"level":"error","error":"invalid merkle root (remote: c90764b75d0a37754cbb9d8adff17358fefb5edfa14b1b97fbe3e85d70b5400c local: f1170a3e0dfcbb3dcca48382de18863347d449dcf6aa935b4e519b2300743cad, rlp dump some long hash)","caller":"/home/yx/go/src/github.com/harmony-one/harmony/api/service/syncing/syncing.go:832","time":"2020-08-12T13:30:34.440312272+02:00","message":"[SYNC] ProcessStateSync failed (isBeacon: false, ShardID: 0, otherHeight: 906434, currentHeight: 626999)"`

`{"level":"warn","error":"mismatching bitmap lengths expectedBitmapLength 2 providedBitmapLength 1","caller":"/home/yx/go/src/github.com/harmony-one/harmony/internal/chain/sig.go:38","time":"2020-08-12T13:21:52.739912915+02:00","message":"mask.SetMask failed"}`
`{"level":"warn","myBlock":627000,"myViewID":627013,"phase":0,"mode":"Listening","caller":"/home/yx/go/src/github.com/harmony-one/harmony/consensus/validator.go:124","time":"2020-08-12T13:21:52.739990366+02:00","message":"[OnPrepared] Quorum Not achieved"}`

these happen on either the current binary or the new one from jacky, so i guess this is a network issue. I used ubuntu 18.04 and i had my ulimit set (also dont have any open files error)

**Comment by mirrormirage0** [comment]
Confirmed. Issue exists. Re-tested with fresh sync on Ubuntu 18.04 LTS, Shard 0, testnet. Reached block `626999` after 2.5 hrs and stuck.
`{"level":"error","error":"invalid merkle root (remote: c90764b75d0a37754cbb9d8adff17358fefb5edfa14b1b97fbe3e85d70b5400c local:`
