### ISSUE TITLE
CLI overhaul release -Option to check installed version + running version / or implement it in go-sdk 

### ISSUE THREAD

**Issue by BrunoMarshall** [harmony-one/harmony#3293]
With the  "old" node.sh -V we could double check the binary version installed and the binary running version. But with the ./harmony --version we see only the binary installed.

![image](https://user-images.githubusercontent.com/35432495/90062496-0dc8ac80-dce8-11ea-9e15-5a001f8b0279.png)

Feature request:
Implement it in go-sdk or other option

Just to mention that the option to check the "running and installed version" saved a lot of signing issues in mainnet validators, so we should keep an option available to confirm it easely.

Binary version: Harmony (C) 2020. harmony, version v6260-v2.3.3-48-g32d99b75 (yx@ 2020-08-11T21:43:10+0000)

**Comment by janet-harmony** [comment]
The binary will not update itself automatically, from it's point of view, there is only one version which is the running version.

**Comment by JackyWYX** [comment]
So can we add a simple command to go-sdk to check the running version of
the node?

**Comment by janet-harmony** [comment]
```
./hmy utility metadata
```
Will print the `getNodeMetadata` RPC, which includes the binary version

**Comment by JackyWYX** [comment]
> ```
> ./hmy utility metadata
> ```
> 
> Will print the `getNodeMetadata` RPC, which includes the binary version

@BrunoMarshall Does this sound like a solution?
