### ISSUE TITLE
Testnet v6272 - External validators -are not requested to sign blocks

### ISSUE THREAD

**Issue by BrunoMarshall** [harmony-one/harmony#3307]
**Describe the bug**
I have validators (externally validators) running in testnet v6272-v2.3.4-4-g75dff620, (shard1) but currently are not signing blocks, they don´t receive blocks to sign.
![image](https://user-images.githubusercontent.com/35432495/90831653-7e08ab00-e344-11ea-9f95-3573fbd61433.png)
this issue started some days ago, but i thought that was related to sync issue with shard0. currently the node is full synced and the issue remains.
![image](https://user-images.githubusercontent.com/35432495/90832202-8c0afb80-e345-11ea-80a3-921090a42209.png)

**To Reproduce**
1. Run a node in testnet
2. Check is the node sync and create a validator
3. When the validator is elected check how many blocks the validator need to sign.

**Expected behavior**
is expected that the validator recieve blocks to sign

![image](https://user-images.githubusercontent.com/35432495/90831601-63363680-e344-11ea-9e78-bf37ddf66669.png)

**Comment by LeoHChen** [comment]
Can you check the log to see if this node has received the announcement message?

**Comment by LeoHChen** [comment]
search for string in the log like, "OnAnnounce"

**Comment by LeoHChen** [comment]
also, you may enable more debug message, to start the node.sh using `-L5` option
