### ISSUE TITLE
PubSub Refactor

### ISSUE THREAD

**Issue by JackyWYX** [harmony-one/harmony#3322]
## Issue

Currently, PubSub handle logic are written in function `node.Start` as a whole. This function is the core part of harmony p2p, but the code is not well designed and structured so all code logic from different modules exist in a single function. This is a blocker for adding more features in the pub sub handling logic. Thus we need to refactor this piece of code to give it a bit more extensibility for new features.

The refactor has 4 requirements:

1. Different message handling logics are decoupled in different implementation of interface `PubSubHandler`.
2. `PubSubHandler` can be added, started, stopped and removed dynamically for extensibility.
3. Do not change the code logic, so that the code should work exactly the same as the current implementation.
4. After change, the code can resist the existing attacks.

## Phases

The refactor will take 3 phases, each phase will have a PR with the change.

### Phase 1: Refactor pub sub handling logic

This is basically add feature to p2p `Host` to have the capability of handling `PubSubHandlers` to meet the requirements 1. In this step, only adding new modules and do not edit the existing code logic.

### Phase 2: Implement different handlers

Decouple the existing message handling logic into different handlers, which is to implement `consensusChainHandler`, `nodeHandler`, `beaconChainHandler`. In this phase, write new code and do not edit the existing code logic.

### Phase 3: Make them a whole

Using the code in Phase 1 and 2, replace the existing code logic.

Do all the tests:
1. Normal use cases
2. Stress use cases (attacks)

**Comment by rlan35** [comment]
can we close this now?
