### ISSUE TITLE
Staking Dashboard - Undelegate from "not elected" validator shows negative numbers instead of 1 epoch waiting time

### ISSUE THREAD

**Issue by BrunoMarshall** [harmony-one/harmony#3348]
## Summary

With the current version the staking dashboard: https://staking.harmony.one showns negative numbers for undelegation from "not elected" validator,  instead of 1 epoch waiting time

## Current Design
![image](https://user-images.githubusercontent.com/35432495/93295985-94dcd900-f7ee-11ea-93ce-7b8ea4aaac35.png)

## Proposal

the proposal is to show 1 epoch when the value is negative >7

**Comment by BrunoMarshall** [comment]
@potvik  i think this is because that specific validator was not elected on the last epochs, and shows the qty of epoch that passed after was elected

**Comment by rlan35** [comment]
@BrunoMarshall is this fixed?

**Comment by rlan35** [comment]
Closing for now. Please reopen if it's still a issue.
