### ISSUE TITLE
[DB] Improve DB sizes on shard 0

### ISSUE THREAD

**Issue by rhazberries** [harmony-one/harmony#3382]
## Summary

Shard 0 DB is growing too fast

## Current Design

Due to staking, validator information is being saved per block.

## Problems

DB growth is unscalable.

## Proposal

The data dump into the DB needs to be revisited & made more efficient.

**Comment by rlan35** [comment]
Rather than fully refactoring the structure of validator information storage. One easier solution is to modify the state trie storage logic to not repeatedly store the validator address's trie node in archival mode.

**Comment by JackyWYX** [comment]
This might be problematic since there can be `missing trie node` error. To resolve this issue, there can be the same amount of modification on validator information storage. I still believe the refactoring the storage might be the right path. Let me dig a little bit into this.
