### ISSUE TITLE
[regression] view change during epoch change is broken

### ISSUE THREAD

**Issue by LeoHChen** [harmony-one/harmony#3399]
**Describe the bug**
I was testing the new synchronous view change algorithm, especially for view change at the first block of the epoch change. 
Then I found the view change doesn't work during the epoch change.

**Expected behavior**

The expected behavior is to always return to the validator index 0 after epoch change.
However, the latest code on `main` branch doesn't exhibit this behavior.
The leader remains the same one before the epoch change.

**To Reproduce**

This problem happened on the latest `main` branch, but I think I have pinpointed to this PR (https://github.com/harmony-one/harmony/pull/3352), especially the `commitBlock` function.

I've tested the code on (https://github.com/harmony-one/harmony/pull/3388), the view change exhibited the expected behavior.

To reproduce the behavior on `stn` shard0, after updated the code to a certain build.
Refer to this gist on `stn` testing, https://gist.github.com/LeoHChen/f8eb8593092c65a12cb1c78f4569fba2

- stop the current leader, normally the node index 0 on shard 0
- watch the leader change to node index 2, and get hooray
- resume the node index 0, node index 2 is still the leader, node index 0 becomes a normal validator
- wait for epoch change, after epoch change, node index 2 is still the leader. The expected behavior is node index 0 should become the new leader after epoch change.

**Logs**

I've captured some logs of the node index 2 after epoch change, on two different build in this gist,
https://gist.github.com/LeoHChen/34dc4c30968e70396a67a151bc5dd24f

**Comment by JackyWYX** [comment]
Addressed in #3400. Closing
