### ISSUE TITLE
Harmony Stream protocol phase 1 proposal

### ISSUE THREAD

**Issue by JackyWYX** [harmony-one/harmony#3401]
# Description

This is the brief proposal for harmony stream protocol design. 

Currently, all nodes are using centralized sync based on GRPC if left behind in consensus. However this centralized sync will cause a lot of runtime issues such as for network with limited syncing nodes, DNS nodes has to be leader node to have the latest block. Thus we will need a decentralized syncing service provider which relies on libp2p streaming. The ultimate goal of this proposal is to totally get rid of the sync module and could probably provide some extra functionalities to be further used in consensus module.

### Outlines

This phase will propose following component changes:

1. Move `NetworkInfo` service (discovery) and embed it to HostV2. (Done)
2. Use `WithDiscovery` opt for pubsub peer discovery. (Done)
3. Stream protocol discovery with a new topic. (Done)
4. Stream handler: initial handshake and rpc calls: "getBlockByNumber", and "getBlockHeaderByEpoch" (Optional). (Ongoing)
6. Stream peer management. (On going)
7. Rate limiter as middleware to protect from ddos attacks.
8. Load balancer for rpc calls (dummy in this phase).

**Comment by rlan35** [comment]
The design is done. Closing this.
