### ISSUE TITLE
gracefully shutdown node after certain block

### ISSUE THREAD

**Issue by LeoHChen** [harmony-one/harmony#3416]
## Summary

We need a mechanism to gracefully shutdown the node program when certain conditions are met. This can be used to upgrade the node.

## Current Design

During the upgrade of the node, we just call `systemctl stop harmony` to stop the harmony node program.  The node program can be stopped at any moment.  We do have a `graceful` shutdown handler to make sure the blockchain data are written to the disk.

## Problems

The node can be stopped at any moment, so that it may trigger an unnecessary view change. It also increases the risk of the un-deterministic state of the node.

## Proposal

We want to gracefully shutdown the node at a certain block and after the consensus is reached. So that to provide a better upgrade experience to the entire network. The pre-condition can be sent to the node via an RPC call.  And when the condition is met, the node will exit gracefully after sync all the states to the local disk DB.

Noted, this RPC call should only come from the localhost to avoid remote attacks. Or it has to be signed by certain keys.

**Comment by rlan35** [comment]
The most critical shutdown issue is with the leader. So the leader better shutdown after consensus is finished to avoid dangling state on the leader node.

For validator node, it's less of a problem as validators don't mess up consensus state itself.

**Comment by LeoHChen** [comment]
https://github.com/harmony-one/harmony/pull/3483
