### ISSUE TITLE
[Rosetta] Implement the /call endpoint in Rosetta 1.5.x

### ISSUE THREAD

**Issue by Daniel-VDM** [harmony-one/harmony#3428]
## Context
In the latest version of the specification, the `/call` endpoint was added (in [this PR](https://github.com/coinbase/rosetta-specifications/pull/55)), which allows composable calls between multiple Rosetta API implementation (say an HRC-20 specific rosetta implementation on top of the harmony core rosetta implementation) as well as allow a Rosetta user to call any RPC method using the Rosetta framework.

## Proposal
We should forward *contract* and *staking information* RPCs **only** to the `/call` endpoint since any other RPC would be a duplication of functionalities that already exist in the rosetta spec/implementation. 

## Examples
Rosetta released their eth [implementation](http://github.com/coinbase/rosetta-ethereum/), which relies on the `/call` endpoint to make contracts work.

**Comment by MaxMustermann2** [comment]
Closed by #3708
