### ISSUE TITLE
[Rosetta] Implement Staking Transaction Construction

### ISSUE THREAD

**Issue by Daniel-VDM** [harmony-one/harmony#3431]
## Issue

We currently only support plain transaction construction (cross-shard, same-shard, and contract creation of native transactions). For completion, we need to also support contraction creation.

## Proposal

First, we must implement #3427 for the correct balance tracking. Then the construction operations will be the minimal subset of operations to express a staking transaction.

All BLS key information (needed [here](https://github.com/harmony-one/harmony/blob/3a8125666817149eaf9cea7870735e26cfe49c87/staking/types/validator.go#L480-L501))  can be added as a field in the [transaction metadata](https://github.com/harmony-one/harmony/blob/3a8125666817149eaf9cea7870735e26cfe49c87/rosetta/services/tx_construction.go#L16) used by the `/construction/preprocess` endpoint.

All data that is needed to execute a staking operation needs to be present in the operation's metadata. Here is a list of each staking operation's metadata: https://github.com/harmony-one/harmony/blob/0b2faeb7e6992d2796ef55b6a4e40bae2771e2d5/rosetta/common/operations.go#L83-L96

#### Delegation special case
For redelegation, the order that the delegations are processed in is determined by the chain, therefore the balance changes of the sub-accounts proposed in #3427 is not be needed for the construction of the transaction, however, the exact amount deducted from the delegator's canonical balance (no sub-account balance) needs to be correct in the `value` of the delegation of the operation. The total amount to delegate to the validator needs to be specified in the metadata of the delegation operation (as seen in any delegation transaction fetch by the `/block/transaction` endpoint).

For undelegations, the undelegation operation should have the `value` set to 0 since the undelegation payout does not happen until another 'special' transaction in a future block. The intended value of the undelegation needs to be specified in the metadata of the undelegation operation. 

#### Special case for collect rewards staking transaction
Since the `value` of the 'collect rewards' operation is not known until the transaction is finalized, we should enforce that the `value` is set to 0. By definition of the collect rewards tx, we cannot pass any construction checks from the rosetta CLI, since we can not state the value of the intended operation.

**Comment by MaxMustermann2** [comment]
Closed by #3664
