### ISSUE TITLE
Removing an empty " " BLS key leads to error: could not confirm XXXXXXXX even after 40 seconds

### ISSUE THREAD

**Issue by Chainode** [harmony-one/harmony#3462]
**Describe the bug**
When the user tries to remove a BLS key but due to a certain reason, e.g. the key isn't copied into the command -> then the user callsl the command with an empty " " BLS key, it will deliver the error below:
"commit: v402-ec0a498, error: encoding/hex: invalid byte: U+002D '-'
check hmy cookbook for valid examples or try adding a `--help` flag"

As a next step the user will make sure the key is inserted in the remove BLS key command and then the following error is thrown:
Try increasing the `timeout` or look for the transaction receipt with `hmy blockchain transaction-receipt <txHash>`
{"transaction-hash":"0xb399cc2ffc6c2a15f9cd5849943790825a366e1bbda72a946de7483272960656"}
commit: v402-ec0a498, error: could not confirm 0xb399cc2ffc6c2a15f9cd5849943790825a366e1bbda72a946de7483272960656 even after 40 seconds

This is the second time I received the error and is reproduceable. Last time I had the same error but it disappeared after a couple of days, probably it expired from the memory pool. 

The workaround is to use "--true-nonce --gas-price xx" until is possible to run commands again without using these 2 flags. 

**To Reproduce**
 1. hmy --node="https://api.s0.t.hmny.io" staking edit-validator --validator-addr <validator_address> --remove-bls-key  --passphrase
The following error is thrown: 
commit: v402-ec0a498, error: encoding/hex: invalid byte: U+002D '-'
check hmy cookbook for valid examples or try adding a `--help` flag
2.  hmy --node="https://api.s0.t.hmny.io" staking edit-validator --validator-addr <validator_address> --remove-bls-key <bls_key>  --passphrase
The following error is thrown:
Try increasing the `timeout` or look for the transaction receipt with `hmy blockchain transaction-receipt <txHash>`
{"transaction-hash":"0xb399cc2ffc6c2a15f9cd5849943790825a366e1bbda72a946de7483272960656"}

**Expected behavior**
The hmy cli should check for empty strings and simply don't create a tx if the required fields are not filled. Is actually not possible to remove or add an " " BLS key. 

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04

**Comment by Daniel-VDM** [comment]
This is ultimately an issue with how the CLI is implemented. Cobra (the CLI library that our CLI is built with) doesn't easily support option parsing as we would want for our specific use case. 

In a sense, we overload the options to input all the args for our transactions. In hindsight, we should have probably made this process interactive, with an option to give it a config file for scripting purposes.  Nevertheless, I've added a check for the BLS key in the PR above. This should fix this bug.

This is just one of the many design issues with the current CLI, and we should really redesign it (maybe using Rosetta 😄 ). It's actually one of this we hope someone is willing to do in our upcoming hackathon.
