### ISSUE TITLE
bootstrap failure

### ISSUE THREAD

**Issue by LeoHChen** [harmony-one/harmony#3484]
**Describe the bug**
I was doing a test on my change https://github.com/harmony-one/harmony/pull/3483 on STN. 
After I restarted the shard0, 3 nodes can't enter the view change mode.

The consensus timer wasn't never started, thus no view change was triggered.
Seems like block height difference and missing bootstrap timeout caused the problem.

The node keep dumping log like the following and nothing else
```
{"level":"info","OtherHeight1":1437986,"OtherHeight2":1437986,"lastHeight":1437986,"currentHeight":1437986,"caller":"/home/lc/go/src/github.com/harmony-one/harmony/api/service/syncing/syncing.go:988","time":"2020-12-10T05:54:05.773474642Z","message":"[SYNC] Checking sync status"}
```

**Comment by ONECasey** [comment]
Issue has been fixed
