### ISSUE TITLE
[Stream] stream protocol dry run mode

### ISSUE THREAD

**Issue by JackyWYX** [harmony-one/harmony#3590]
## Problem/limitation At Hand

For stream sync protocol deployment on mainnet, we probably need TWO steps for safer production launch:

1. As an internal update, all nodes running new stream sync server, but use legacy DNS sync for client. Deploy another "probe" node running full stream sync logic. Thus the downloader logic can be verified on the probe node while not effecting existing logic.
2. As the testing with probe node finished, we can update all nodes to adopt the new downloader logic and publicly release later.

## Feature request

1. Add hidden flag `--sync.dryrun` to dry-run sync protocol.

**Comment by LeoHChen** [comment]
As to the first step, we may even enable the stream sync server mode on all nodes *by default* including internal and external nodes.

We can deploy one or a few internal nodes to enable downloader logic, and engage a few external validators in downloading mode, to have a better coverage.

* not a dry-run IMO, maybe `--sync.downloader` option

**Comment by JackyWYX** [comment]
> As to the first step, we may even enable the stream sync server mode on all nodes _by default_ including internal and external nodes.
> 
> We can deploy one or a few internal nodes to enable downloader logic, and engage a few external validators in downloading mode, to have a better coverage.
> 
> * not a dry-run IMO, maybe `--sync.downloader` option

Sure, great thanks for your advice.

**Comment by JackyWYX** [comment]
Created branch https://github.com/harmony-one/harmony/pull/3595 and added --sync.downloader feature. 

The code is now merged in stn_stream_main branch and deployed to stn. Note: Unstable consensus feature is disabled since for legacy DNS client, the consensus might be forever stuck since DNS nodes could possibly contain lagging data.

Also ran a local node connecting to stressnet running downloader module. And it shows the node run syncing successfully.

```
./harmony --datadir stn --sync.downloader --sync.legacy.client=false --network stn
``` 

We can set stn to use downloader module by default after stn runs good till tomorrow.

**Comment by JackyWYX** [comment]
Also noted that local node fails sync at block number 14628. This might be caused by some nasty historical "forks" at stressnet. Better clean start stn sometime later.

**Comment by JackyWYX** [comment]
The flags and corresponding updates are already merged in this PR: https://github.com/harmony-one/harmony/pull/3595. Clsoing
