### ISSUE TITLE
Consensus stuck during view change on stressnet. 

### ISSUE THREAD

**Issue by JackyWYX** [harmony-one/harmony#3601]
## Describe the bug

@LeoHChen Another view change stuck in shard 1 is observed on stress-net. The network is now left as it is. (https://watchdog.hmny.io/report-stn)

## Codebase

The code deployed has an error injected in consensus. There is some possibility that the node skips `tryCatchup` logic to cause node left behind in consensus as intended. The node shall pick up what is left behind and catch up through sync module.

```
func (consensus *Consensus) tryCatchup() error {
	if rand.Intn(20) == 0 {
		return errors.New("skipped intended")
	}
	...
```

## Observation

Some nodes in shard 1 is not in view change mode as expected. Basically, there shall be some problem from the consensus mode update after a successful download task. Following is a deduction:

1. Node fails to insert a block in `tryCatchup` (as intended)
2. Node realizes it is left behind when doing consensus for the next block and triggers downloader task. Node's mode is set to Syncing.
3. Consensus timeout is stopped at `consensus/consensus_v2.go:323` since consensus mode is syncing. Then `checkExpire` always return false.
4. When sync finished, the current mode is set to "normal" but there is no mechanism to start the consensus timeout counting if consensus does not keeps going.

## Suggested logic edits

1. Consensus should keeps going regardless of syncing. Probably we can remove the "Syncing" mode totally in consensus. So consensus will go as it is for view change / process blocks.
2. Another alternative is to temporarily fix the problem. Start timeout counting at `UpdateConsensusInformation` if all timeout has stopped.

**Comment by LeoHChen** [comment]
good bug found, the syncing mode messed up with consensus is a long term tech debt.  I'll take a closer look. Thanks.

**Comment by LeoHChen** [comment]
When the sync finished, and the mode return to normal, the consensus timer actually should reset, so as to restart the consensus timeout.

**Comment by LeoHChen** [comment]
```golang
         case <-consensus.syncReadyChan:
            consensus.getLogger().Info().Msg("[ConsensusMainLoop] syncReadyChan")
            consensus.mutex.Lock()
            if consensus.blockNum < consensus.Blockchain.CurrentHeader().Number().Uint64()+1 {
               consensus.SetBlockNum(consensus.Blockchain.CurrentHeader().Number().Uint64() + 1)
               consensus.SetViewIDs(consensus.Blockchain.CurrentHeader().ViewID().Uint64() + 1)
               mode := consensus.UpdateConsensusInformation()
               consensus.current.SetMode(mode)
               consensus.getLogger().Info().Msg("[syncReadyChan] Start consensus timer")
               consensus.consensusTimeout[timeoutConsensus].Start()
               consensus.getLogger().Info().Str("Mode", mode.String()).Msg("Node is IN SYNC")
               consensusSyncCounterVec.With(prometheus.Labels{"consensus": "in_sync"}).Inc()
            } else if consensus.Mode() == Syncing {
               mode := consensus.UpdateConsensusInformation()
               consensus.SetMode(mode)
            }
            consensus.mutex.Unlock()
```

When the node is in sync, it should trigger syncReadyChan and restart the consensusTimeout timer, so the node can go back to consensus normal mode and trigger view change eventually.

After discussion with Jacky, we found this could be the root cause.

**Comment by JackyWYX** [comment]
The root cause is actually the downloader is stuck in one short range task. So a node will never send signal to syncReadyChan to start the timeout counting.

An easy fix is to add a timeout for each short range sync.

A more in-depth debug into why the short range sync fails at the first place need a little more investigation.

**Comment by JackyWYX** [comment]
This is actually a corner case of data race of insertChain between `downloader` and `consensus`. Logs as follows:

1. Short range sync started:

```
{"level":"info","module":"downloader","current number":196697,"shard ID":1,"caller":"/home/yx/go/src/github.com/harmony-one/harmony/hmy/downloader/downloader.go:244","time":"2021-03-22T00:27:35.921712521Z","message":"start short range sync"}
```

2. After short range sync started, a block is committed (note the block hash):

```
{"level":"info","blockNum":196698,"epochNum":8376,"ViewId":218469,"blockHash":"0xd9e1ee0ec5b1be71c479225e3a6242056a3c20202bd99eaee271c41939d0be02","numTxns":0,"numStakingTxns":0,"numSignatures":1,"caller":"/home/yx/go/src/github.com/harmony-one/harmony/node/node_handler.go:353","time":"2021-03-22T00:27:36.508309193Z","message":"BINGO !!! Reached Consensus"}
```

3. Meanwhile, downloader does not have block 0xd9e1ee during start, so it will also start syncing. We can tell from the following log that downloader is requesting the same block hash.

```
{"level":"debug","module":"request manager","error":"no more available streams","request":"REQUEST [GetBlocksByHashes: d9e1ee0ec5b1be71c479225e3a6242056a3c20202bd99eaee271c41939d0be02]","caller":"/home/yx/go/src/github.com/harmony-one/harmony/p2p/stream/common/requestmanager/requestmanager.go:292","time":"2021-03-22T00:27:36.082581769Z","message":"Pick available streams."}

4. Consensus finish insertion first, and downloader finished sync later. So in consensus handling this signal, it will go to the `else if consensus.Mode() == Syncing` condition, and `consensusTimeout` is not started, which is the problem causing the node being stuck in normal mode.

```
			case <-consensus.syncReadyChan:
				consensus.getLogger().Info().Msg("[ConsensusMainLoop] syncReadyChan")
				consensus.mutex.Lock()
				if consensus.blockNum < consensus.Blockchain.CurrentHeader().Number().Uint64()+1 {
					consensus.SetBlockNum(consensus.Blockchain.CurrentHeader().Number().Uint64() + 1)
					consensus.SetViewIDs(consensus.Blockchain.CurrentHeader().ViewID().Uint64() + 1)
					mode := consensus.UpdateConsensusInformation()
					consensus.current.SetMode(mode)
					consensus.getLogger().Info().Msg("[syncReadyChan] Start consensus timer")
					consensus.consensusTimeout[timeoutConsensus].Start()
					consensus.getLogger().Info().Str("Mode", mode.String()).Msg("Node is IN SYNC")
					consensusSyncCounterVec.With(prometheus.Labels{"consensus": "in_sync"}).Inc()
				} else if consensus.Mode() == Syncing {
					mode := consensus.UpdateConsensusInformation()
					consensus.SetMode(mode)
				}
```

**Comment by JackyWYX** [comment]
Just got it fixed in PR https://github.com/harmony-one/harmony/pull/3606. It shall resolve this kind of consensus stuck.
