### ISSUE TITLE
Testnet sync stuck

### ISSUE THREAD

**Issue by JackyWYX** [harmony-one/harmony#3611]
**Describe the bug**

Testnet DNS sync stuck.

https://watchdog.hmny.io/report-testnet

**Comment by JackyWYX** [comment]
The error message in sync appears to be DNS node does not have contain the given block hash

```
{"level":"error","error":"rpc error: code = Unknown desc = [SYNC] GetBlockHashes Request cannot find startHash 0xa159a5e925161e0f54076d2db4fe9f541c7a9a4584700bf7dcc9972b7502496a","target":"35.204.212.111:6000","caller":"/home/yx/go/src/github.com/harmony-one/harmony/api/service/syncing/downloader/client.go:55","time":"2021-02-22T17:17:44.133478477Z","message":"[SYNC] GetBlockHashes query failed"}
```

**Comment by JackyWYX** [comment]
Looked deeper into blocks of the error node 161.97.154.182 vs a normal node 207.244.238.196, found the two nodes has forked somehow:

Error node:

```
{
  "id": "0",
  "jsonrpc": "2.0",
  "result": {
    "difficulty": 0,
    "epoch": "0x11f61",
    "extraData": "0x",
    "gasLimit": "0x4c4b400",
    "gasUsed": "0x0",
    "hash": "0x8982d0506d29ab18f3b8d35ee0a85e02b83a17ac5a3222b0e3d0be3838c13e66",
    "logsBloom": "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
    "miner": "one1vjywuur8ckddmc4dsyx6qdgf590eu07ag9fg4a",
    "mixHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
    "nonce": 0,
    "number": "0x70edd1",
    "parentHash": "0x0dfac48732c15ef980047aeacf828cc276a2abaeacb6bff68d677536def2dc3c",
    "receiptsRoot": "0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421",
    "size": "0x2a8",
    "stakingTransactions": [],
    "stateRoot": "0x24e4afa1f8843f380c082eb356e028541177afdec3e4ab2322a8352dbeaefb6f",
    "timestamp": "0x605a4c62",
    "transactions": [],
    "transactionsRoot": "0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421",
    "uncles": [],
    "viewID": "0x70f664"
  }
}
[yx@ip-172-31-37-52 hmy]$ ./hmy --node=161.97.154.182:9500 blockchain block-by-number 7400912
{
  "id": "0",
  "jsonrpc": "2.0",
  "result": {
    "difficulty": 0,
    "epoch": "0x11f61",
    "extraData": "0x",
    "gasLimit": "0x4c4b400",
    "gasUsed": "0x0",
    "hash": "0x0dfac48732c15ef980047aeacf828cc276a2abaeacb6bff68d677536def2dc3c",
    "logsBloom": "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
    "miner": "one1vjywuur8ckddmc4dsyx6qdgf590eu07ag9fg4a",
    "mixHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
    "nonce": 0,
    "number": "0x70edd0",
    "parentHash": "0x229684391a978446de61140c79bceb1748983c12ac50d811f93205f59242745c",
    "receiptsRoot": "0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421",
    "size": "0x2a8",
    "stakingTransactions": [],
    "stateRoot": "0x24e4afa1f8843f380c082eb356e028541177afdec3e4ab2322a8352dbeaefb6f",
    "timestamp": "0x605a4c60",
    "transactions": [],
    "transactionsRoot": "0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421",
    "uncles": [],
    "viewID": "0x70f663"
  }
}
```

On the other hand, on synced node

```
{
  "id": "0",
  "jsonrpc": "2.0",
  "result": {
    "difficulty": 0,
    "epoch": "0x11f61",
    "extraData": "0x",
    "gasLimit": "0x4c4b400",
    "gasUsed": "0x0",
    "hash": "0x44acae7c605fcacd51de158cadae6e2a7bc3003cd8d020da5614bec8407c5c07",
    "logsBloom": "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
    "miner": "one13yp54e9kynzw57g42878vhtrzu2hfw3nn8gy83",
    "mixHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
    "nonce": 0,
    "number": "0x70edd1",
    "parentHash": "0x4dc2dbcdf53e3cf524fd426257e70fc095cc1bd35f75c2b0d0f71a0a7536fd01",
    "receiptsRoot": "0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421",
    "size": "0x12c4",
    "stakingTransactions": [],
    "stateRoot": "0x24e4afa1f8843f380c082eb356e028541177afdec3e4ab2322a8352dbeaefb6f",
    "timestamp": "0x605a4cca",
    "transactions": [],
    "transactionsRoot": "0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421",
    "uncles": [],
    "viewID": "0x70f666"
  }
}
[yx@ip-172-31-37-52 hmy]$ ./hmy --node=207.244.238.196:9500 blockchain block-by-number 7400912
{
  "id": "0",
  "jsonrpc": "2.0",
  "result": {
    "difficulty": 0,
    "epoch": "0x11f61",
    "extraData": "0x",
    "gasLimit": "0x4c4b400",
    "gasUsed": "0x0",
    "hash": "0x4dc2dbcdf53e3cf524fd426257e70fc095cc1bd35f75c2b0d0f71a0a7536fd01",
    "logsBloom": "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
    "miner": "one13yp54e9kynzw57g42878vhtrzu2hfw3nn8gy83",
    "mixHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
    "nonce": 0,
    "number": "0x70edd0",
    "parentHash": "0xefe1172909fd5b9c944fe109a9b985bc6729cf4482c410dbf49e1df4b0a80e6c",
    "receiptsRoot": "0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421",
    "size": "0x2a8",
    "stakingTransactions": [],
    "stateRoot": "0x24e4afa1f8843f380c082eb356e028541177afdec3e4ab2322a8352dbeaefb6f",
    "timestamp": "0x605a4cc8",
    "transactions": [],
    "transactionsRoot": "0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421",
    "uncles": [],
    "viewID": "0x70f665"
  }
}
```

We can see that the two nodes has forked in the past.

**Comment by JackyWYX** [comment]
So there are two questions to be discussed now:

1. Why the fork at the first place?
2. Why the fork with less voting power is able to carry on from 7399997 to 7400913?

**Comment by LeoHChen** [comment]
need to check with @sophoah on how did he recover the shard3

**Comment by LeoHChen** [comment]
@sophoah confirmed no actions taken from their side and shard recovered automatically.

**Comment by LeoHChen** [comment]
As to question number 2, I think there is a network partition that happened. So there are two networks, each of them has 2 internal nodes, and at least 1 external node.  The two internal nodes have 30% voting power, and the one external node has 40% voting power.  So both of them can proceed to some block.

**Comment by LeoHChen** [comment]
I did more deep analysis of the logs on shard2 node 195.  The two internal nodes 193, 195 lost consensus and lagged behind the other nodes in shard2, while they kept doing view change.  On block 7382906, there are other external nodes that are also lagged behind did a successful view change together and one consensus was reached.  However, during the following state syncing check, those nodes realized that they are out of sync of the top of the chain, and then they were stuck.

**Comment by LeoHChen** [comment]
will need to do further checking on shard3 nodes.

**Comment by LeoHChen** [comment]
I reverted the node 195 in shard2 to 7282899 using `./harmony --revert.to 7282900 --revert.do-before 7382910 --run.legacy --network testnet`

Now it has the same block chain as the other node.

```
pops@PTN_S2_4:~$ ./hmy --node=127.0.0.1:9500 blockchain block-by-number 7282899
{
  "id": "0",
  "jsonrpc": "2.0",
  "result": {
    "difficulty": 0,
    "epoch": "0x11f55",
    "extraData": "0x",
    "gasLimit": "0x4c4b400",
    "gasUsed": "0x0",
    "hash": "0x67e724ee8a63bfa5c374ae9e5c3ed7c02ca63d519fc33df7d70075952072fcb2",
    "logsBloom": "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
    "miner": "one1shzkj8tty2wu230wsjc7lp9xqkwhch2ea7sjhc",
    "mixHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
    "nonce": 0,
    "number": "0x6f20d3",
    "parentHash": "0x2619693c54b26f971b75881470dc1754e21a61ba5f7442c7a89a0548860a940b",
    "receiptsRoot": "0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421",
    "size": "0x2a8",
    "stakingTransactions": [],
    "stateRoot": "0x506e433ca24009fde822eeb54c68f0f4fd4fc764e9d0459d08aa231c8bc4950b",
    "timestamp": "0x60573663",
    "transactions": [],
    "transactionsRoot": "0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421",
    "uncles": [],
    "viewID": "0x6f4bbd"
  }
}


pops@PTN_S2_4:~$ ./hmy --node=161.97.154.176:9500 blockchain block-by-number 7282899
{
  "id": "0",
  "jsonrpc": "2.0",
  "result": {
    "difficulty": 0,
    "epoch": "0x11f55",
    "extraData": "0x",
    "gasLimit": "0x4c4b400",
    "gasUsed": "0x0",
    "hash": "0x67e724ee8a63bfa5c374ae9e5c3ed7c02ca63d519fc33df7d70075952072fcb2",
    "logsBloom": "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
    "miner": "one1shzkj8tty2wu230wsjc7lp9xqkwhch2ea7sjhc",
    "mixHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
    "nonce": 0,
    "number": "0x6f20d3",
    "parentHash": "0x2619693c54b26f971b75881470dc1754e21a61ba5f7442c7a89a0548860a940b",
    "receiptsRoot": "0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421",
    "size": "0x2a8",
    "stakingTransactions": [],
    "stateRoot": "0x506e433ca24009fde822eeb54c68f0f4fd4fc764e9d0459d08aa231c8bc4950b",
    "timestamp": "0x60573663",
    "transactions": [],
    "transactionsRoot": "0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421",
    "uncles": [],
    "viewID": "0x6f4bbd"
  }
}
```

However, it still can't sync to new blocks.

**Comment by rlan35** [comment]
@JackyWYX saw this error on shard 3 node:   207.244.238.196

Did we enable stream sync in testnet already?

{"level":"info","Protocol":"harmony/sync/testnet/0/1.0.0","ID":"QmVgPt3H23-255","Remote Protocol":"harmony/sync/testnet/0/1.0.0","StreamID":"QmVgPt3H23-255","caller":"/mnt/jenkins/workspace/harmony-release/harmony/p2p/stream/protocols/sync/stream.go:58","time":"2021-03-23T14:45:34.845673113-05:00","message":"running sync protocol on stream"}
{"level":"info","module":"request manager","streamID":"QmVgPt3H23-255","caller":"/mnt/jenkins/workspace/harmony-release/harmony/p2p/stream/common/requestmanager/requestmanager.go:358","time":"2021-03-23T14:45:34.845792536-05:00","message":"add new stream"}
{"level":"info","caller":"/mnt/jenkins/workspace/harmony-release/harmony/node/node_handler.go:79","time":"2021-03-23T14:45:35.911177985-05:00","message":"Beacon block being handled by block channel: 7442502"}
{"level":"info","caller":"/mnt/jenkins/workspace/harmony-release/harmony/internal/chain/reward.go:491","time":"2021-03-23T14:45:35.915495519-05:00","message":"Commit sigs are ready"}
{"level":"info","blockNum":7400007,"shardID":3,"caller":"/mnt/jenkins/workspace/harmony-release/harmony/core/offchain.go:165","time":"2021-03-23T14:45:35.917242133-05:00","message":"[insertChain/crosslinks] Cross Link Added to Beaconchain"}
{"level":"info","number":"7442502","hash":"0x6197f3d89bfc85a801ee0b4fec49a998cdd8e1e44edf6263a9d7a0dbf0c734ec","uncles":0,"txs":0,"stakingTxs":0,"gas":0,"elapsed":"3.446ms","caller":"/mnt/jenkins/workspace/harmony-release/harmony/core/blockchain.go:1482","time":"2021-03-23T14:45:35.918204927-05:00","message":"Inserted new block"}
{"level":"info","blocks":1,"txs":0,"mgas":0,"elapsed":"3.483ms","mgasps":0,"number":"7442502","hash":"0x6197f3d89bfc85a801ee0b4fec49a998cdd8e1e44edf6263a9d7a0dbf0c734ec","cache":"5.28 MiB","caller":"/mnt/jenkins/workspace/harmony-release/harmony/core/blockchain.go:1554","time":"2021-03-23T14:45:35.918247776-05:00","message":"Imported new chain segment"}
{"level":"info","blockHeight":7442502,"blockEpoch":73569,"blockHex":"0x6197f3d89bfc85a801ee0b4fec49a998cdd8e1e44edf6263a9d7a0dbf0c734ec","ShardID":0,"caller":"/mnt/jenkins/workspace/harmony-release/harmony/api/service/legacysync/syncing.go:809","time":"2021-03-23T14:45:35.918290066-05:00","message":"[SYNC] UpdateBlockAndStatus: New Block Added to Blockchain"}
{"level":"info","module":"request manager","streamID":"QmbQkceiQU-247","caller":"/mnt/jenkins/workspace/harmony-release/harmony/p2p/stream/common/requestmanager/requestmanager.go:362","time":"2021-03-23T14:45:37.456721035-05:00","message":"remove stream"}
{"level":"error","Protocol":"harmony/sync/testnet/3/1.0.0","ID":"QmbQkceiQU-247","Remote Protocol":"harmony/sync/testnet/3/1.0.0","error":"stream reset","caller":"/mnt/jenkins/workspace/harmony-release/harmony/p2p/stream/protocols/sync/stream.go:72","time":"2021-03-23T14:45:37.456917972-05:00","message":"failed to close sync stream"}
{"level":"info","Protocol":"harmony/sync/testnet/3/1.0.0","ID":"QmbQkceiQU-247","Remote Protocol":"harmony/sync/testnet/3/1.0.0","StreamID":"QmbQkceiQU-247","caller":"/mnt/jenkins/workspace/harmony-release/harmony/p2p/stream/protocols/sync/stream.go:64","time":"2021-03-23T14:45:37.456953499-05:00","message":"end running sync protocol on stream"}
{"level":"info","Protocol":"harmony/sync/testnet/3/1.0.0","stream":"QmdgoD3cVJ-237-21752","caller":"/mnt/jenkins/workspace/harmony-release/harmony/p2p/stream/protocols/sync/protocol.go:157","time":"2021-03-23T14:45:37.493667478-05:00","message":"handle new sync stream"}
{"level":"info","Protocol":"harmony/sync/testnet/3/1.0.0","stream":"Qmd167beAs-224-21750","caller":"/mnt/jenkins/workspace/harmony-release/harmony/p2p/stream/protocols/sync/protocol.go:157","time":"2021-03-23T14:45:37.493769978-05:00","message":"handle new sync stream"}
{"level":"warn","Protocol":"harmony/sync/testnet/3/1.0.0","error":"stream already exist","stream ID":"QmdgoD3cVJ-237","caller":"/mnt/jenkins/workspace/harmony-release/harmony/p2p/stream/protocols/sync/protocol.go:162","time":"2021-03-23T14:45:37.493850288-05:00","message":"failed to add new stream"}
{"level":"warn","Protocol":"harmony/sync/testnet/3/1.0.0","error":"stream already exist","stream ID":"Qmd167beAs-224","caller":"/mnt/jenkins/workspace/harmony-release/harmony/p2p/stream/protocols/sync/protocol.go:162","time":"2021-03-23T14:45:37.49393708-05:00","message":"failed to add new stream"}
{"level":"info","Protocol":"harmony/sync/testnet/3/1.0.0","stream":"QmYuVNBxs1-53-21751","caller":"/mnt/jenkins/workspace/harmony-release/harmony/p2p/stream/protocols/sync/protocol.go:157","time":"2021-03-23T14:45:37.496104537-05:00","message":"handle new sync stream"}
{"level":"warn","Protocol":"harmony/sync/testnet/3/1.0.0","error":"stream already exist","stream ID":"QmYuVNBxs1-53","caller":"/mnt/jenkins/workspace/harmony-release/harmony/p2p/stream/protocols/sync/protocol.go:162","time":"2021-03-23T14:45:37.496233077-05:00","message":"failed to add new stream"}
{"level":"info","caller":"/mnt/jenkins/workspace/harmony-release/harmony/node/node_handler.go:79","time":"2021-03-23T14:45:37.910618091-05:00","message":"Beacon block being handled by block channel: 7442503"}

**Comment by rlan35** [comment]
From shard 3 log. I found:

1. The two stuck nodes were participating in consensus normally and had the last BINGO at block 7399996 at around 2021-03-23T14:45:06. But after that, there is no "OnAnnounce" or "OnPrepared" received. Suspecting there is a network partition happening.
2. The Leader 161.97.154.177 at that time was able to continue the consensus without the two stuck node (total 30% voting power) by reaching 70% consensus.
3. The stuck nodes started view change and the view change succeeded at around 2021-03-23T14:46:01. And elected one of the stuck nodes as a duplicate leader. And checking on the un-stuck nodes, they don't receive any view change or NewView messages around the same time (another evidence of network partition). This also implies that either 1) the view change logic could cause "fork" leaders, or 2), there are duplicate validators that contributed to the votes.  For 1), we need to check the log on external validators to see if there nodes participated in this rogue view change while doing consensus on the normal chain.

**Comment by LeoHChen** [comment]
Some more analysis. The node 207.244.236.5 finished the last bingo at 14:45:06 and then it didn't receive the consensus message and till 14:45:33 timeout.  This may be due to the network partition.  Instead of doing state syncing to catch up with the other nodes which are already doing consensus to new blocks, it tries to start a view change and successfully partition the network into two due to a redundant set of external validators.  Since we don't have the DNS records at that moment now, we can guess that the DNS was pointing to the two nodes that are lagged behind, so that they created a new quorum.

With a streaming-based syncing, it shouldn't rely on DNS, but the risk of a network partition is still there.


```json
{"level":"info","blockNum":7399996,"epochNum":73569,"ViewId":7402191,"blockHash":"0xd180204e976577ba0277a7236cc105454728406dfb1a928cd701fa23fd439f88","numTxns":0,"numStakingTxns":0,"numSignatures":2,"caller":"/mnt/jenkins/workspace/harmony-release/harmony/node/node_handler.go:353","time":"2021-03-23T14:45:06.587833889-05:00","message":"BINGO !!! Reached Consensus"}
...

{"level":"warn","myBlock":7399997,"myViewID":7402192,"phase":"Announce","mode":"Normal","caller":"/mnt/jenkins/workspace/harmony-release/harmony/consensus/consensus_v2.go:345","time":"2021-03-23T14:45:33.809439444-05:00","message":"[ConsensusMainLoop] Ops Consensus Timeout!!!"}
```

**Comment by JackyWYX** [comment]
> @JackyWYX saw this error on shard 3 node: 207.244.238.196
> 
> Did we enable stream sync in testnet already?
> 
> {"level":"info","Protocol":"harmony/sync/testnet/0/1.0.0","ID":"QmVgPt3H23-255","Remote Protocol":"harmony/sync/testnet/0/1.0.0","StreamID":"QmVgPt3H23-255","caller":"/mnt/jenkins/workspace/harmony-release/harmony/p2p/stream/protocols/sync/stream.go:58","time":"2021-03-23T14:45:34.845673113-05:00","message":"running sync protocol on stream"}
> {"level":"info","module":"request manager","streamID":"QmVgPt3H23-255","caller":"/mnt/jenkins/workspace/harmony-release/harmony/p2p/stream/common/requestmanager/requestmanager.go:358","time":"2021-03-23T14:45:34.845792536-05:00","message":"add new stream"}
> {"level":"info","caller":"/mnt/jenkins/workspace/harmony-release/harmony/node/node_handler.go:79","time":"2021-03-23T14:45:35.911177985-05:00","message":"Beacon block being handled by block channel: 7442502"}
> {"level":"info","caller":"/mnt/jenkins/workspace/harmony-release/harmony/internal/chain/reward.go:491","time":"2021-03-23T14:45:35.915495519-05:00","message":"Commit sigs are ready"}
> {"level":"info","blockNum":7400007,"shardID":3,"caller":"/mnt/jenkins/workspace/harmony-release/harmony/core/offchain.go:165","time":"2021-03-23T14:45:35.917242133-05:00","message":"[insertChain/crosslinks] Cross Link Added to Beaconchain"}
> {"level":"info","number":"7442502","hash":"0x6197f3d89bfc85a801ee0b4fec49a998cdd8e1e44edf6263a9d7a0dbf0c734ec","uncles":0,"txs":0,"stakingTxs":0,"gas":0,"elapsed":"3.446ms","caller":"/mnt/jenkins/workspace/harmony-release/harmony/core/blockchain.go:1482","time":"2021-03-23T14:45:35.918204927-05:00","message":"Inserted new block"}
> {"level":"info","blocks":1,"txs":0,"mgas":0,"elapsed":"3.483ms","mgasps":0,"number":"7442502","hash":"0x6197f3d89bfc85a801ee0b4fec49a998cdd8e1e44edf6263a9d7a0dbf0c734ec","cache":"5.28 MiB","caller":"/mnt/jenkins/workspace/harmony-release/harmony/core/blockchain.go:1554","time":"2021-03-23T14:45:35.918247776-05:00","message":"Imported new chain segment"}
> {"level":"info","blockHeight":7442502,"blockEpoch":73569,"blockHex":"0x6197f3d89bfc85a801ee0b4fec49a998cdd8e1e44edf6263a9d7a0dbf0c734ec","ShardID":0,"caller":"/mnt/jenkins/workspace/harmony-release/harmony/api/service/legacysync/syncing.go:809","time":"2021-03-23T14:45:35.918290066-05:00","message":"[SYNC] UpdateBlockAndStatus: New Block Added to Blockchain"}
> {"level":"info","module":"request manager","streamID":"QmbQkceiQU-247","caller":"/mnt/jenkins/workspace/harmony-release/harmony/p2p/stream/common/requestmanager/requestmanager.go:362","time":"2021-03-23T14:45:37.456721035-05:00","message":"remove stream"}
> {"level":"error","Protocol":"harmony/sync/testnet/3/1.0.0","ID":"QmbQkceiQU-247","Remote Protocol":"harmony/sync/testnet/3/1.0.0","error":"stream reset","caller":"/mnt/jenkins/workspace/harmony-release/harmony/p2p/stream/protocols/sync/stream.go:72","time":"2021-03-23T14:45:37.456917972-05:00","message":"failed to close sync stream"}
> {"level":"info","Protocol":"harmony/sync/testnet/3/1.0.0","ID":"QmbQkceiQU-247","Remote Protocol":"harmony/sync/testnet/3/1.0.0","StreamID":"QmbQkceiQU-247","caller":"/mnt/jenkins/workspace/harmony-release/harmony/p2p/stream/protocols/sync/stream.go:64","time":"2021-03-23T14:45:37.456953499-05:00","message":"end running sync protocol on stream"}
> {"level":"info","Protocol":"harmony/sync/testnet/3/1.0.0","stream":"QmdgoD3cVJ-237-21752","caller":"/mnt/jenkins/workspace/harmony-release/harmony/p2p/stream/protocols/sync/protocol.go:157","time":"2021-03-23T14:45:37.493667478-05:00","message":"handle new sync stream"}
> {"level":"info","Protocol":"harmony/sync/testnet/3/1.0.0","stream":"Qmd167beAs-224-21750","caller":"/mnt/jenkins/workspace/harmony-release/harmony/p2p/stream/protocols/sync/protocol.go:157","time":"2021-03-23T14:45:37.493769978-05:00","message":"handle new sync stream"}
> {"level":"warn","Protocol":"harmony/sync/testnet/3/1.0.0","error":"stream already exist","stream ID":"QmdgoD3cVJ-237","caller":"/mnt/jenkins/workspace/harmony-release/harmony/p2p/stream/protocols/sync/protocol.go:162","time":"2021-03-23T14:45:37.493850288-05:00","message":"failed to add new stream"}
> {"level":"warn","Protocol":"harmony/sync/testnet/3/1.0.0","error":"stream already exist","stream ID":"Qmd167beAs-224","caller":"/mnt/jenkins/workspace/harmony-release/harmony/p2p/stream/protocols/sync/protocol.go:162","time":"2021-03-23T14:45:37.49393708-05:00","message":"failed to add new stream"}
> {"level":"info","Protocol":"harmony/sync/testnet/3/1.0.0","stream":"QmYuVNBxs1-53-21751","caller":"/mnt/jenkins/workspace/harmony-release/harmony/p2p/stream/protocols/sync/protocol.go:157","time":"2021-03-23T14:45:37.496104537-05:00","message":"handle new sync stream"}
> {"level":"warn","Protocol":"harmony/sync/testnet/3/1.0.0","error":"stream already exist","stream ID":"QmYuVNBxs1-53","caller":"/mnt/jenkins/workspace/harmony-release/harmony/p2p/stream/protocols/sync/protocol.go:162","time":"2021-03-23T14:45:37.496233077-05:00","message":"failed to add new stream"}
> {"level":"info","caller":"/mnt/jenkins/workspace/harmony-release/harmony/node/node_handler.go:79","time":"2021-03-23T14:45:37.910618091-05:00","message":"Beacon block being handled by block channel: 7442503"}

We enabled stream server server on testnet, but the downloader is still not up.

```
Stream Server: ON
Stream Client (downloader): OFF
DNS Server: ON
DNS Client: ON
```

**Comment by rlan35** [comment]
Is this still an issue?

**Comment by sophoah** [comment]
@rlan35 it's been a while testnet hasn't been stuck. I'll close that ticket for now
