### ISSUE TITLE
v4.0.0 dropped signatures

### ISSUE THREAD

**Issue by michaelotis** [harmony-one/harmony#3641]
It could just be an anomaly, but I upgraded to 4.0.0 and dropped thousands of signatures over a few hours. I heard that Shard 0 may have been having issues at this time. After restarting the service, it started signing but then stopped and received the following error:

`ERROR        basichost        failed to resolve local interface addresses        {"error": "route ip+net: no such network interface"}
`

However, I did not see that error again, but it dropped signatures for a few hours before dropping to zero, I did not modify anything besides restarting the service one time. You can see in the image where I switched the binary out.

![image](https://user-images.githubusercontent.com/34221002/113772793-c8c80f00-96ea-11eb-90db-ee191207c126.png)

**Comment by LeoHChen** [comment]
@michaelotis did you check your CPU load of the server you used?  We have noticed CPU usage increased with the recent release and increased number of slots. https://github.com/harmony-one/harmony/issues/3661

You may want to switch to a beefy machine for your validator to keep up the signing rate. LMK the result.

**Comment by michaelotis** [comment]
> @michaelotis did you check your CPU load of the server you used? We have noticed CPU usage increased with the recent release and increased number of slots. #3661
> 
> You may want to switch to a beefy machine for your validator to keep up the signing rate. LMK the result.

No, CPU never maxes out nor does memory. However, while this occurrence seems to be an anomaly, I do tend to drop quite a few sigs from a box with a 2 CPU/8 gig setup, I assume it's most likely related to the box itself. I'll close this issue as it doesn't seem to be pinpointed.
