### ISSUE TITLE
CPU usage increased on non-beacon shard

### ISSUE THREAD

**Issue by LeoHChen** [harmony-one/harmony#3661]
**Describe the bug**
A clear pattern that the CPU usage had increased recently with the upgrade of the release, on non-beacon shard, which had no change on traffic. This has to be fixed, otherwise, there is an increasing risk of node underpower.

![image](https://user-images.githubusercontent.com/4513927/114631451-74d0a380-9c71-11eb-9306-d68e043ae2da.png)

**Comment by LeoHChen** [comment]
![image](https://user-images.githubusercontent.com/4513927/115620925-aa494280-a2aa-11eb-825a-524dce47a453.png)

![image](https://user-images.githubusercontent.com/4513927/115621029-d1077900-a2aa-11eb-95e3-4e5d5282b0dd.png)

I restarted s3.19

**Comment by LeoHChen** [comment]
![image](https://user-images.githubusercontent.com/4513927/115621327-30658900-a2ab-11eb-9500-c0426b086403.png)

I restarted s1.21

![image](https://user-images.githubusercontent.com/4513927/115621412-53903880-a2ab-11eb-8b6f-2b1910f8bb4d.png)


I restarted s1.25

**Comment by LeoHChen** [comment]
![image](https://user-images.githubusercontent.com/4513927/115621530-820e1380-a2ab-11eb-9272-f8304a6c3b2b.png)

I restarted s1.33

![image](https://user-images.githubusercontent.com/4513927/115621615-9e11b500-a2ab-11eb-97ee-6539bc833d87.png)

I restarted s1.37

**Comment by LeoHChen** [comment]
check the latest CPU consumption and found the CPU spike every one or two minutes. Highly suspect there are periodic goroutines hike up the CPU usage.

![image](https://user-images.githubusercontent.com/4513927/117261307-dd401a00-ae04-11eb-8926-143bec6ece2e.png)

**Comment by LeoHChen** [comment]
![image](https://user-images.githubusercontent.com/4513927/117945323-107e1f80-b2c3-11eb-9813-55e8e2dc2d01.png)

I rebooted 34.239.158.91 w/o updating software, and noticed CPU usage dropped significantly. I doubt it may be due to constant garbage collector after running the node for a while. 

The node 3.23.105.44 was rebooted with updated software using https://github.com/harmony-one/harmony/pull/3699, let's wait and see if the Cpu usage will increase later in a few days.

**Comment by LeoHChen** [comment]
![image](https://user-images.githubusercontent.com/4513927/118031260-36cfa980-b31b-11eb-83d7-097fb7d92a90.png)

Another data point after 10 hours, the CPU usage is increasing gradually.

**Comment by rlan35** [comment]
Not an issue anymore based on latest grafana CPU metrics.
