### ISSUE TITLE
./hmy utility metadata returns incorrect  block number

### ISSUE THREAD

**Issue by mirrormirage0** [harmony-one/harmony#3662]
**Describe the bug**
./hmy utility metadata returns stale blocknum.
If I restart the node , then the right blocknum is retrieved. 

**To Reproduce**
1. Run `./hmy utility metadata` on a node
2. It will display an old block number.
3. However, checking the logs, the node is syncing new blocks. 
4. If the node is restarted, then the command will return latest block number. Then any further calls to `./hmy utility metadata` will display the same number 

 
**Expected behavior**
The latest block number of node should be displayed.

**Screenshots**
![image](https://user-images.githubusercontent.com/29485946/114699537-7d88ae80-9d31-11eb-8cd1-e2905ddae18f.png)

**Environment (please complete the following information):**
 - OS: Ubuntu 18.04
 -

**Comment by LeoHChen** [comment]
@JackyWYX can also take a look at the data returned by the RPC.

**Comment by mirrormirage0** [comment]
This issue is back again. Try on **any explorer node.**

![image](https://user-images.githubusercontent.com/29485946/120244161-8e0dcd80-c27a-11eb-86f4-e5869822d642.png)

Block numbers are increasing in the log file.

**Comment by JackyWYX** [comment]
Please take a look at this PR: https://github.com/harmony-one/harmony/pull/3667, and use

```
.hmy utility metadata | grep current-block-number
```

instead.

**Comment by mirrormirage0** [comment]
`current-block-number` works.
