### ISSUE TITLE
slashing revisit

### ISSUE THREAD

**Issue by LeoHChen** [harmony-one/harmony#3691]
## Summary

we need to revisit the design and implementation of the slashing protection in the network if we are going to 100% externalize the network.

## Current Design

all validators can detect double signing of validators and double proposal from the leader.

## Problems

redundant nodes situation is not handled, need deep dive on ethereum2

```By being an attester and sign an attestation that “surrounds” another one.```

This situation shall be slashed.

## Proposal

The following is the ethereum2 slashing design. I believe we have handled the 1st and 3rd one, but not the 2nd one.

```
There are three ways a validator can gain the slashed condition:

By being a proposer and sign two different beacon blocks for the same slot.

By being an attester and sign an attestation that “surrounds” another one.

By being an attester and sign two different attestations having the same target.
```

## Reference

https://consensys.net/blog/codefi/rewards-and-penalties-on-ethereum-20-phase-0/

**Comment by ONECasey** [comment]
@sunwavesun Please take note of this issue and close when finished.
