### ISSUE TITLE
create validator FAQ document

### ISSUE THREAD

**Issue by LeoHChen** [harmony-one/harmony#3697]
Please update or create a validator FAQ document with commonly asked questions from all the supporting channels.

**Comment by LeoHChen** [comment]
yes, I've created an issue for JB to improve the dashboard. https://github.com/harmony-one/harmony-ops-priv/issues/22

**Comment by yelllowsin** [comment]
@LeoHChen reorganized the FAQ staking here: https://docs.harmony.one/home/network/delegator/staking/staking-faq
