### ISSUE TITLE
Test plan for features in next release in June 2021

### ISSUE THREAD

**Issue by rlan35** [harmony-one/harmony#3719]
# VRF

- [x] Deploy the following contract and check that the VRF result can be read by calling vrf() and the results vary for every block.

```
contract VRFReader {
  function vrf() public view returns (bytes32 result) {
  	bytes32 input;
  	assembly {
  		let memPtr := mload(0x40)
                if iszero(staticcall(not(0), 0xff, input, 32, memPtr, 32)) {
        	        invalid()
                }
                result := mload(memPtr)
        }
  }
}
```

# Min Delegation of 100 ONE: [proposal](https://governance.harmony.one/#/staking-mainnet/proposal/Qmf5k8GH3ZBAze6uru8Qk85jpDaMjzqQbXunVXji5upg7N)

- [ ] Send Delegate transaction with 1 ONE and expect failure
- [ ] Send Delegate transaction with 99 ONE and expect failure
- [ ] Send Delegate transaction with 100 ONE and expect success
- [ ] Send Delegate transaction with 500 ONE and expect success
- [ ] Send Delegate transaction with 1000 ONE and expect success

# EPoS bound parameter c = 0.35: [proposal](https://governance.harmony.one/#/staking-mainnet/proposal/QmdmnVwW6ob5UfB9hNYxKsRXAyM52jQpNXsV5Vw4fNbiqa)

- [ ] Update your validator stake so it goes **above** median_stake * 1.35 and check RPC to see your effective stake equals median_stake * 1.35.
- [ ] Update your validator stake so it goes **below** median_stake * 0.65 and check RPC to see your effective stake equals median_stake * 0.65.
- [ ] Update your validator stake so it it's between upper and lower bound of effective stake (0.65, 1.35) and check RPC to see your effective stake equals your raw stake.
- [ ] Check staking dashboard to make sure the threshold are updated correctly

# Min commission fee set to 5%: [proposal](https://governance.harmony.one/#/staking-mainnet/proposal/QmYbBQuDSZbMVa6RBi3kzFiNkXxv8PMp9rrT25drkxQnTb)

- [ ] Create a new validator and get it elected, and set its commission fee to 0% and 4.5% during the first 10 epoch after it's first elected.
- [ ] After the 10th epochs after your validator was first elected, check that its commission fee is automatically updated to 5%.
- [ ] Create another new validator and set it's commission fee to 6%, after the 10th epochs after your validator was first elected, check that its commission fee is still 6%.
- [ ] After the 10th epochs after your validator was first elected, try EditValidator to set commission fee below 5% and expect failure.
- [ ] After the 10th epochs after your validator was first elected, try EditValidator to set commission fee equal to or larger than 5% and expect success.

**Comment by sophoah** [comment]
@rlan35 I tested the min delegation with hmy cli and no issue, all work as expected. However, we will need some update on the staking dashboard. Transaction is not even sent to the network. cc @potvik @hypnagonia

**Comment by rachit2501** [comment]
VRF deployment: contract address: one1dr4wpjk9pkz8psfwzxl455upc79c9nwlzpc2gk
First all: 0xb167ad78f531dfffab420b4510f49dfdc5982adea730d9134ced89caeaf6487d
Second call: 0xbf45c641b81d4d336db6eb928c617eae70b538fe22184174bee4820fd2d40ad2
Third call: 0x9b8b883db7dbe273736f14fba4b6948b87783ce8d705ca00085ca135f7214783

Tests are all passing.

**Comment by mirrormirage0** [comment]
Deployed and Tested VRF ->  https://youtu.be/hP9X8ZYsuD4

Deploy Tx 0xcd080693cbc0e0c6263b7e173c4f52f9e911cd085ac9924ea211bf181d42d637
Read 1 
0x283d4e8cf269e21377cfbe6b6fb34291230d7c4fbff55b8350685c848231b718
Read 2 
0x009b044606956bb4d4973eff21ddecae80c81817045f662138dc8f902d29c6cd
Read 3
0x8f8ec63614ff2254012034b038a56fb5ef5ae67b69c841f457b58675fed6618b

**Comment by mindstyle85** [comment]
Tested: all passed

EPOS c=0.35 
 OK Update your validator stake so it goes above median_stake * 1.35 and check RPC to see your effective stake equals median_stake * 1.35.
OK Update your validator stake so it goes below median_stake * 0.65 and check RPC to see your effective stake equals median_stake * 0.65.
OK Update your validator stake so it it's between upper and lower bound of effective stake (0.65, 1.35) and check RPC to see your effective stake equals your raw stake.

Min fee of 5%
 Create a new validator and get it elected, and set its commission fee to 0% and 4.5% during the first 10 epoch after it's first elected - done - no issue changing fee below 5%
 After the 10th epochs after your validator was first elected, check that its commission fee is automatically updated to 5%. - done - the fees changed automatically to 5%
 Create another new validator and set it's commission fee to 6%, after the 10th epochs after your validator was first elected, check that its commission fee is still 6%. - done
OK After the 10th epochs after your validator was first elected, try EditValidator to set commission fee below 5% and expect failure - done
OK After the 10th epochs after your validator was first elected, try EditValidator to set commission fee equal to or larger than 5% and expect success - done
OK existing validator before feature activation can't set fee below 5%, expect failure - done --> error is Catch all RPC error: commission rate can not be lower than min rate of 5%!

**Comment by rlan35** [comment]
@mirrormirage0 @mindstyle85 Thanks for testing guys. So everything looks good? Any issues?
