### ISSUE TITLE
[testnet] [min delegation] delegation below 1000 ONEs should work in the latest code

### ISSUE THREAD

**Issue by sophoah** [harmony-one/harmony#3721]
**Describe the bug**
in `v7057-v4.0.1-58-g6d45fdec` the minimum delegation has been reduced to 100, however testing shows it doesn't work.

**To Reproduce**
```
./hmy --node="https://api.s0.b.hmny.io" staking delegate --delegator-addr one1u6c4wer2dkm767hmjeehnwu6tqqur62gx9vqsd --validator-addr one1u6c4wer2dkm767hmjeehnwu6tqqur62gx9vqsd --amount 200
commit: v417-bc3f026, error: Catch all RPC error: minimum delegation amount for a delegator has to be greater than or equal to 1000 ONE
```
**Expected behavior**
1) amount of 200 should work
2) amount below 100 shouldn't work

**Screenshots**
NA

**Environment (please complete the following information):**
NA

**Additional context**
NA

**Comment by MaxMustermann2** [comment]
Can we close this @sophoah ?
