### ISSUE TITLE
Ledger Nano S Broken on Chrome Version 91

### ISSUE THREAD

**Issue by DavidWhicker** [harmony-one/harmony#3724]
**Describe the bug**
The latest version of Chrome ( 91 ) has broken support for Ledger Nano S connecting to the both One Wallet and staking.harmony.one

**To Reproduce**
Staking site no longer sees the ledger is connected when trying to sign in to staking.harmony.one

**Expected behavior**
Sign in button followed by standard sign in procedure on the Ledger.

**Screenshots**
https://imgur.com/DfVvlKw
https://imgur.com/ZCKiOH6

**Environment (please complete the following information):**
- Mac but believed to be widespead to anyone on the latest version of Chrome

**Additional context**
I believe Chrome removed support for U2F connections.
Ledger have suggested using Firefox however staking.harmony.one doesn't allow sign in with a ledger via firefox either.

**Comment by DavidWhicker** [comment]
https://www.reddit.com/r/harmony_one/comments/nnh73u/chrome_91_brave_ledger_harmony_one_wallet_woes/gzum9pc/?utm_source=share&utm_medium=ios_app&utm_name=iossmf&context=3

Here is some more information on a holder trying to use the One Wallet  - only solution right now is to use an older version of Chrome

**Comment by LeoHChen** [comment]
@yelllowsin can you reproduce the issue?

**Comment by yelllowsin** [comment]
> @yelllowsin can you reproduce the issue?

@LeoHChen Yes, i can confirm it no longer works with Chrome on latest version. i am getting this:
`NotFoundError: The device was disconnected.`

Ledger Firmware: 2.0.0
Chrome: Version 91.0.4472.77 (Official Build) (x86_64)
Harmony One App: 1.0.3

**Comment by sukantag** [comment]
@LeoHChen @yelllowsin I see the same problem and @yelllowsin has been working with me , I have another Mac with an older version fo the Chrome where it works, Don't remember which version though

**Comment by DavidWhicker** [comment]
Not sure if it helps but this is MetaMasks response and fix for using the ledger on their wallet:

"As of Chrome version 91, the API that enabled our Ledger support (U2F) no longer supports hardware wallets. MetaMask has implemented a new Ledger Live support that allows you to continue to connect to your Ledger device via the Ledger Live desktop app.

You can enable Ledger Live support by clicking Settings > Advanced > Use Ledger Live.

When interacting with your Ledger account in MetaMask, a new tab will open and you will be asked to open the Ledger Live app. Once the app opens, you'll be asked to allow a WebSocket connection to your MetaMask account. That's all!

5/26/2021"

**Comment by LeoHChen** [comment]
This is a big change we need to implement though. @gupadhyaya , we shall consider open a bounty program to have the ledger live desktop support on onewallet.

**Comment by LeoHChen** [comment]
![image](https://user-images.githubusercontent.com/4513927/120745854-d8798f00-c4b2-11eb-8bce-a9e556793700.png)


The message received on metamask.  We shall make the same change on our onewallet, IMO.

**Comment by DavidWhicker** [comment]
@LeoHChen Sounds great. I don't suppose you have a rough timeframe in mind to implement the change? Just so we can inform those who are already locked out.

**Comment by yelllowsin** [comment]
The best workaround I found so far is using an old version of Brave Browser just for staking like this one: https://github.com/brave/brave-browser/releases/tag/v1.24.82

I would not recommend using it for anything else since its outdated.

**Comment by DavidWhicker** [comment]
I know you guys are working on it and likely already know but I have determined that Mac OS is the only operating system affected. Windows is still operational. 

Chrome Version 91.0.4472.77 (Official Build) (x86_64)
Windows: Works
Mac: Does not work

**Comment by DavidWhicker** [comment]
FIXED ON CHROME VERSION : Version 91.0.4472.101 (Official Build) (x86_64)

**Comment by LeoHChen** [comment]
nice. Thanks for the update.
