### ISSUE TITLE
Pushgateway Error in Logs

### ISSUE THREAD

**Issue by Stakeridoo** [harmony-one/harmony#3725]
Mainnet Release 4.0.0 ARM Version on Raspberry Pi 4; 1.8GHz; 8GB RAM with Ubuntu 20.04 LTS. Fibre Optic Network with 3ms Latency and 100mb/s.

From time to time the Node miss some sign requests.

Tried to optimase the Hardware by increasing the CPU speed and switched off swap. But still missing some blocks.

After I checked the Harmony Log File I the following Error which repeats often. Validity confirmed to have the same error in his logs.

```bash
{"level":"warn","error":"unexpected status code 504 while pushing to https://gateway.harmony.one/metrics/job@base64/bWFpbm5ldC92Mg/instance/QmVkmo8bfYHjcoeU9RMnf4zzR1GHVPWDWbMG6dvP8uascN: <html>\r\n<head><title>504 Gateway Time-out</title></head>\r\n<body>\r\n<center><h1>504 Gateway Time-out</h1></center>\r\n</body>\r\n</html>\r\n","caller":"/home/ec2-user/actions-runner/_work/harmony/harmony/harmony/api/service/prometheus/service.go:150","time":"2021-06-02T16:39:06.643632266+02:00","message":"Pushgateway Error"}
 ```

A second message shows this
```bash
{"level":"warn","error":"unexpected status code 504 while pushing to https://gateway.harmony.one/metrics/job@base64/bWFpbm5ldC92Mg/instance/QmVkmo8bfYHjcoeU9RMnf4zzR1GHVPWDWbMG6dvP8uascN: <!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.1//EN\" \"http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd\">\n\n<html xmlns=\"http://www.w3.org/1999/xhtml\" xml:lang=\"en\">\n    <head>\n        <title>The page is temporarily unavailable</title>\n        <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\" />\n        <style type=\"text/css\">\n            /*<![CDATA[*/\n            body {\n                background-color: #fff;\n                color: #000;\n                font-size: 0.9em;\n                font-family: sans-serif,helvetica;\n                margin: 0;\n                padding: 0;\n            }\n            :link {\n                color: #c00;\n            }\n            :visited {\n                color: #c00;\n            }\n            a:hover {\n                color: #f50;\n            }\n            h1 {\n                text-align: center;\n                margin: 0;\n                padding: 0.6em 2em 0.4em;\n                background-color: #294172;\n                color: #fff;\n                font-weight: normal;\n                font-size: 1.75em;\n                border-bottom: 2px solid #000;\n            }\n            h1 strong {\n                font-weight: bold;\n                font-size: 1.5em;\n            }\n            h2 {\n                text-align: center;\n                background-color: #3C6EB4;\n                font-size: 1.1em;\n                font-weight: bold;\n                color: #fff;\n                margin: 0;\n                padding: 0.5em;\n                border-bottom: 2px solid #294172;\n            }\n            h3 {\n                text-align: center;\n                background-color: #ff0000;\n                padding: 0.5em;\n                color: #fff;\n            }\n            hr {\n                display: none;\n            }\n            .content {\n                padding: 1em 5em;\n            }\n            .alert {\n                border: 2px solid #000;\n            }\n\n            img {\n                border: 2px solid #fff;\n                padding: 2px;\n                margin: 2px;\n            }\n            a:hover img {\n                border: 2px solid #294172;\n            }\n            .logos {\n                margin: 1em;\n                text-align: center;\n            }\n            /*]]>*/\n        </style>\n    </head>\n\n    <body>\n        <h1><strong>nginx error!</strong></h1>\n\n        <div class=\"content\">\n\n            <h3>The page you are looking for is temporarily unavailable.  Please try again later.</h3>\n\n            <div class=\"alert\">\n                <h2>Website Administrator</h2>\n                <div class=\"content\">\n                    <p>Something has triggered an error on your\n                    website.  This is the default error page for\n                    <strong>nginx</strong> that is distributed with\n                    Amazon Linux 2.  It is located\n                    <tt>/usr/share/nginx/html/50x.html</tt></p>\n\n                    <p>You should customize this error page for your own\n                    site or edit the <tt>error_page</tt> directive in\n                    the <strong>nginx</strong> configuration file\n                    <tt>/etc/nginx/nginx.conf</tt>.</p>\n\n                </div>\n            </div>\n\n            <div class=\"logos\">\n                <a href=\"http://nginx.net/\"><img\n                    src=\"/nginx-logo.png\"\n                    alt=\"[ Powered by nginx ]\"\n                    width=\"121\" height=\"32\" /></a>\n\n                <a href=\"https://amazonlinux.com/\"><img \n                    src=\"/poweredby.png\"\n                    alt=\"[ Powered by Amazon Linux 2 ]\" \n                    width=\"88\" height=\"31\" /></a>\n            </div>\n        </div>\n    </body>\n</html>\n","caller":"/home/ec2-user/actions-runner/_work/harmony/harmony/harmony/api/service/prometheus/service.go:150","time":"2021-06-02T16:40:06.822162484+02:00","message":"Pushgateway Error"}
 ```

The third message shows this
```bash
{"level":"warn","error":"unexpected status code 502 while pushing to https://gateway.harmony.one/metrics/job@base64/bWFpbm5ldC92Mg/instance/QmVkmo8bfYHjcoeU9RMnf4zzR1GHVPWDWbMG6dvP8uascN: <!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.1//EN\" \"http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd\">\n\n<html xmlns=\"http://www.w3.org/1999/xhtml\" xml:lang=\"en\">\n    <head>\n        <title>The page is temporarily unavailable</title>\n        <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\" />\n        <style type=\"text/css\">\n            /*<![CDATA[*/\n            body {\n                background-color: #fff;\n                color: #000;\n                font-size: 0.9em;\n                font-family: sans-serif,helvetica;\n                margin: 0;\n                padding: 0;\n            }\n            :link {\n                color: #c00;\n            }\n            :visited {\n                color: #c00;\n            }\n            a:hover {\n                color: #f50;\n            }\n            h1 {\n                text-align: center;\n                margin: 0;\n                padding: 0.6em 2em 0.4em;\n                background-color: #294172;\n                color: #fff;\n                font-weight: normal;\n                font-size: 1.75em;\n                border-bottom: 2px solid #000;\n            }\n            h1 strong {\n                font-weight: bold;\n                font-size: 1.5em;\n            }\n            h2 {\n                text-align: center;\n                background-color: #3C6EB4;\n                font-size: 1.1em;\n                font-weight: bold;\n                color: #fff;\n                margin: 0;\n                padding: 0.5em;\n                border-bottom: 2px solid #294172;\n            }\n            h3 {\n                text-align: center;\n                background-color: #ff0000;\n                padding: 0.5em;\n                color: #fff;\n            }\n            hr {\n                display: none;\n            }\n            .content {\n                padding: 1em 5em;\n            }\n            .alert {\n                border: 2px solid #000;\n            }\n\n            img {\n                border: 2px solid #fff;\n                padding: 2px;\n                margin: 2px;\n            }\n            a:hover img {\n                border: 2px solid #294172;\n            }\n            .logos {\n                margin: 1em;\n                text-align: center;\n            }\n            /*]]>*/\n        </style>\n    </head>\n\n    <body>\n        <h1><strong>nginx error!</strong></h1>\n\n        <div class=\"content\">\n\n            <h3>The page you are looking for is temporarily unavailable.  Please try again later.</h3>\n\n            <div class=\"alert\">\n                <h2>Website Administrator</h2>\n                <div class=\"content\">\n                    <p>Something has triggered an error on your\n                    website.  This is the default error page for\n                    <strong>nginx</strong> that is distributed with\n                    Amazon Linux 2.  It is located\n                    <tt>/usr/share/nginx/html/50x.html</tt></p>\n\n                    <p>You should customize this error page for your own\n                    site or edit the <tt>error_page</tt> directive in\n                    the <strong>nginx</strong> configuration file\n                    <tt>/etc/nginx/nginx.conf</tt>.</p>\n\n                </div>\n            </div>\n\n            <div class=\"logos\">\n                <a href=\"http://nginx.net/\"><img\n                    src=\"/nginx-logo.png\"\n                    alt=\"[ Powered by nginx ]\"\n                    width=\"121\" height=\"32\" /></a>\n\n                <a href=\"https://amazonlinux.com/\"><img \n                    src=\"/poweredby.png\"\n                    alt=\"[ Powered by Amazon Linux 2 ]\" \n                    width=\"88\" height=\"31\" /></a>\n            </div>\n        </div>\n    </body>\n</html>\n","caller":"/home/ec2-user/actions-runner/_work/harmony/harmony/harmony/api/service/prometheus/service.go:150","time":"2021-06-02T16:46:25.458399378+02:00","message":"Pushgateway Error"}
 ```

**Comment by Omnibotzzzz** [comment]
Harmony (C) 2020. harmony, version v6933-v4.0.0-0-g78759217 (runner@ 2021-04-06T00:31:18+0000)

Here are a few timeout errors I see on digital ocean/vultr

502 error:

`{"level":"warn","error":"unexpected status code 502 while pushing to https://gateway.harmony.one/metrics/job@base64/bWFpbm5ldC92MA/instance/QmRCFuq9ZXJuzTgy9ep47nCAJmk12ozsnZjSYMRhEwfLtK: <!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.1//EN\" \"http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd\">\n\n<html xmlns=\"http://www.w3.org/1999/xhtml\" xml:lang=\"en\">\n    <head>\n        <title>The page is temporarily unavailable</title>\n        <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\" />\n        <style type=\"text/css\">\n            /*<![CDATA[*/\n            body {\n                background-color: #fff;\n                color: #000;\n                font-size: 0.9em;\n                font-family: sans-serif,helvetica;\n                margin: 0;\n                padding: 0;\n            }\n            :link {\n                color: #c00;\n            }\n            :visited {\n                color: #c00;\n            }\n            a:hover {\n                color: #f50;\n            }\n            h1 {\n                text-align: center;\n                margin: 0;\n                padding: 0.6em 2em 0.4em;\n                background-color: #294172;\n                color: #fff;\n                font-weight: normal;\n                font-size: 1.75em;\n                border-bottom: 2px solid #000;\n            }\n            h1 strong {\n                font-weight: bold;\n                font-size: 1.5em;\n            }\n            h2 {\n                text-align: center;\n                background-color: #3C6EB4;\n                font-size: 1.1em;\n                font-weight: bold;\n                color: #fff;\n                margin: 0;\n                padding: 0.5em;\n                border-bottom: 2px solid #294172;\n            }\n            h3 {\n                text-align: center;\n                background-color: #ff0000;\n                padding: 0.5em;\n                color: #fff;\n            }\n            hr {\n                display: none;\n            }\n            .content {\n                padding: 1em 5em;\n            }\n            .alert {\n                border: 2px solid #000;\n            }\n\n            img {\n                border: 2px solid #fff;\n                padding: 2px;\n                margin: 2px;\n            }\n            a:hover img {\n                border: 2px solid #294172;\n            }\n            .logos {\n                margin: 1em;\n                text-align: center;\n            }\n            /*]]>*/\n        </style>\n    </head>\n\n    <body>\n        <h1><strong>nginx error!</strong></h1>\n\n        <div class=\"content\">\n\n            <h3>The page you are looking for is temporarily unavailable.  Please try again later.</h3>\n\n            <div class=\"alert\">\n                <h2>Website Administrator</h2>\n                <div class=\"content\">\n                    <p>Something has triggered an error on your\n                    website.  This is the default error page for\n                    <strong>nginx</strong> that is distributed with\n                    Amazon Linux 2.  It is located\n                    <tt>/usr/share/nginx/html/50x.html</tt></p>\n\n                    <p>You should customize this error page for your own\n                    site or edit the <tt>error_page</tt> directive in\n                    the <strong>nginx</strong> configuration file\n                    <tt>/etc/nginx/nginx.conf</tt>.</p>\n\n                </div>\n            </div>\n\n            <div class=\"logos\">\n                <a href=\"http://nginx.net/\"><img\n                    src=\"/nginx-logo.png\"\n                    alt=\"[ Powered by nginx ]\"\n                    width=\"121\" height=\"32\" /></a>\n\n                <a href=\"https://amazonlinux.com/\"><img \n                    src=\"/poweredby.png\"\n                    alt=\"[ Powered by Amazon Linux 2 ]\" \n                    width=\"88\" height=\"31\" /></a>\n            </div>\n        </div>\n    </body>\n</html>\n","caller":"/home/runner/work/harmony/harmony/harmony/api/service/prometheus/service.go:150","time":"2021-06-02T21:04:18.784210043Z","message":"Pushgateway Error"}`

504 error:

`{"level":"warn","error":"unexpected status code 504 while pushing to https://gateway.harmony.one/metrics/job@base64/bWFpbm5ldC92MA/instance/QmRCFuq9ZXJuzTgy9ep47nCAJmk12ozsnZjSYMRhEwfLtK: <!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.1//EN\" \"http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd\">\n\n<html xmlns=\"http://www.w3.org/1999/xhtml\" xml:lang=\"en\">\n    <head>\n        <title>The page is temporarily unavailable</title>\n        <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\" />\n        <style type=\"text/css\">\n            /*<![CDATA[*/\n            body {\n                background-color: #fff;\n                color: #000;\n                font-size: 0.9em;\n                font-family: sans-serif,helvetica;\n                margin: 0;\n                padding: 0;\n            }\n            :link {\n                color: #c00;\n            }\n            :visited {\n                color: #c00;\n            }\n            a:hover {\n                color: #f50;\n            }\n            h1 {\n                text-align: center;\n                margin: 0;\n                padding: 0.6em 2em 0.4em;\n                background-color: #294172;\n                color: #fff;\n                font-weight: normal;\n                font-size: 1.75em;\n                border-bottom: 2px solid #000;\n            }\n            h1 strong {\n                font-weight: bold;\n                font-size: 1.5em;\n            }\n            h2 {\n                text-align: center;\n                background-color: #3C6EB4;\n                font-size: 1.1em;\n                font-weight: bold;\n                color: #fff;\n                margin: 0;\n                padding: 0.5em;\n                border-bottom: 2px solid #294172;\n            }\n            h3 {\n                text-align: center;\n                background-color: #ff0000;\n                padding: 0.5em;\n                color: #fff;\n            }\n            hr {\n                display: none;\n            }\n            .content {\n                padding: 1em 5em;\n            }\n            .alert {\n                border: 2px solid #000;\n            }\n\n            img {\n                border: 2px solid #fff;\n                padding: 2px;\n                margin: 2px;\n            }\n            a:hover img {\n                border: 2px solid #294172;\n            }\n            .logos {\n                margin: 1em;\n                text-align: center;\n            }\n            /*]]>*/\n        </style>\n    </head>\n\n    <body>\n        <h1><strong>nginx error!</strong></h1>\n\n        <div class=\"content\">\n\n            <h3>The page you are looking for is temporarily unavailable.  Please try again later.</h3>\n\n            <div class=\"alert\">\n                <h2>Website Administrator</h2>\n                <div class=\"content\">\n                    <p>Something has triggered an error on your\n                    website.  This is the default error page for\n                    <strong>nginx</strong> that is distributed with\n                    Amazon Linux 2.  It is located\n                    <tt>/usr/share/nginx/html/50x.html</tt></p>\n\n                    <p>You should customize this error page for your own\n                    site or edit the <tt>error_page</tt> directive in\n                    the <strong>nginx</strong> configuration file\n                    <tt>/etc/nginx/nginx.conf</tt>.</p>\n\n                </div>\n            </div>\n\n            <div class=\"logos\">\n                <a href=\"http://nginx.net/\"><img\n                    src=\"/nginx-logo.png\"\n                    alt=\"[ Powered by nginx ]\"\n                    width=\"121\" height=\"32\" /></a>\n\n                <a href=\"https://amazonlinux.com/\"><img \n                    src=\"/poweredby.png\"\n                    alt=\"[ Powered by Amazon Linux 2 ]\" \n                    width=\"88\" height=\"31\" /></a>\n            </div>\n        </div>\n    </body>\n</html>\n","caller":"/home/runner/work/harmony/harmony/harmony/api/service/prometheus/service.go:150","time":"2021-06-02T21:11:21.465554591Z","message":"Pushgateway Error"}
`

**Comment by LeoHChen** [comment]
@sophoah please take a look at the gateway server. It is in our lightsail servers of prod account. I doubt it is overloaded, then we need to upgrade it.

**Comment by jhd2best** [comment]
seems the CPU usage has been around 40%, which exceeds the sustainable zone of Lightsail and needs to be upgraded. the snapshot is currently being created for subsequent upgrade steps

**Comment by jhd2best** [comment]
already setup a new instance(4C16G). it works now
