### ISSUE TITLE
Wallet Issues 

### ISSUE THREAD

**Issue by rachit2501** [harmony-one/harmony#3731]
**Describe the bug**
Two bugs are there currently:
1. Metamask: Cannot send tokens from one wallet to another wallet address. Contract interactions work fine. ( High priority )
2. OneWallet: UI issue. The UI flow gets stuck at the tx page when sending tokens from one shard to another. ( Low priority )

**To Reproduce**
1.  Metamask: Send funds from your wallet  to another wallet address ( address format should be 0x type )>
2. OneWallet: Try sending funds from one shard to another.

**Expected behavior**
1. Metamask should send funds, instead of throwing ether-js error.
2. One Wallet: Ui should move to the entry page after cross-shard tx is sent successfully to the network.

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browers: Chrome, Brave

**Comment by LeoHChen** [comment]
it should be related to the RPC issues we had.  closing this one

let's monitor the progress in the other ticket. https://github.com/harmony-one/harmony/issues/3755
