### ISSUE TITLE
Dashboard and snapshot app displaying wrong or no balances

### ISSUE THREAD

**Issue by mindstyle85** [harmony-one/harmony#3738]
As said both sites sometimes display smaller balances than validators have, sometimes 0 and sometimes normal. The same is within the portfolio page.

a reference: https://twitter.com/stakeridoo/status/1400455031103520774

**Comment by LeoHChen** [comment]
will deploy the latest version to mainnet to check

**Comment by LeoHChen** [comment]
with the latest deployment, it seems working fine now

```
$ node get-total-staking-single.js
Total validators:  229 Total staked for one14l4lst4qnm9fecv38450upfjym00s4ejz9mgdc:  217694602
Total validators:  229 Total staked for one14l4lst4qnm9fecv38450upfjym00s4ejz9mgdc:  217694602
```
