### ISSUE TITLE
Unable to unlock coins completely

### ISSUE THREAD

**Issue by rakeshpatibanda** [harmony-one/harmony#3742]
**Describe the bug**
I delegated my coins with https://staking.harmony.one/validators/mainnet/one1mxjrugqety8t6v23m3et0j4zfussf4v8ktycur and undelegated 10k coins about 8 days ago.

After the 7 EPOCHs have passed, the cycle seems to be repeating and it says I still have 4 EPOCHs left for the coins to unlock completely.

**To Reproduce**
1. Perhaps delegate coins with https://staking.harmony.one/validators/mainnet/one1mxjrugqety8t6v23m3et0j4zfussf4v8ktycur and undelegate them to observe a similar behaviour maybe?
2. It may also be worthwhile to try delegating with another validator and undelegate them. This could also give insight about if this behaviour only happens when undelegating from one validator (https://staking.harmony.one/validators/mainnet/one1mxjrugqety8t6v23m3et0j4zfussf4v8ktycur).

**Additional context**
I undelegated 2k coins recently from the same validator and I was able to unlock the coins completely fine.

**Comment by LeoHChen** [comment]
Is it still an issue? we had some RPC issues last week.  It should be working fine now.  Please let us know if it is still a problem.

**Comment by rlan35** [comment]
Most likely a UI or user mistake. Closing for now. Feel free to reopen if the problem persists.
