### ISSUE TITLE
additional metrics on network dashboard

### ISSUE THREAD

**Issue by LeoHChen** [harmony-one/harmony#3776]
## Summary

To provide a better network dashboard

## Current Design

https://monitor.hmny.io/status displays more insight of the status of the network consensus, block number, running version, and so on.

## Problems

We need to have more metrics of the network level dashboard

## Proposal

* add block latency, and latest consensus time to the dashboard
* add number of tx, TPS, tx per day

**Comment by jhd2best** [comment]
[explorer v2](https://explorer.harmony.one) already support metrics above
