### ISSUE TITLE
harmony scan internal ip port 9000

### ISSUE THREAD

**Issue by lcgogo** [harmony-one/harmony#3788]
**Describe the bug**
I have a honey pot in the internal VPC to capture unusual scanning message.

The honey pot reports that the server running harmony try to connect its port 9000 today.

Think the same issue like in an old version
https://github.com/harmony-one/harmony/issues/2940

Now I use harmony 4.1.5 in ubuntu 18.04

**Comment by roulettista** [comment]
Similar issue and it is causing my service provider (Hetzner) to send me abuse messages. I am using Harmony together with NodePilot and blocking local subnets via UFW did nothing to stop the abuse messages from Hetzner. I know many others hosting on Hetzner are in the same situation and some are already being shut down by them. None of the other chain nodes I run act like this (ETH, FUSE, AVAX, etc.)

**Comment by MaxMustermann2** [comment]
Clsoed by #4286
