### ISSUE TITLE
S0 archival node is growing too fast

### ISSUE THREAD

**Issue by sophoah** [harmony-one/harmony#3805]
**Describe the bug**
An archival node was built a month ago, at that time the DB was ~7.5 TB in size, today on the 29 June we reached 8.4TB, almost 1TB in a month.

**To Reproduce**
N/A

**Expected behavior**
1TB per month is too much. it should be lower.

**Screenshots**
Almost 20% increase in one month
![image](https://user-images.githubusercontent.com/35721420/123740380-8cafdf00-d8d2-11eb-9a8e-51ab0078b1ea.png)

**Environment (please complete the following information):**
 - OS: [Linux, MacOS]
- Go environment [ ```go env``` ]

**Additional context**

**Comment by yelllowsin** [comment]
Besides the explorer nodes on shard 0 that have been increasing a lot lately, i see some people started to complain about current size of shard 0 for the validators nodes which has reached 94GB recently.

**Comment by ONECasey** [comment]
Fixed.
