### ISSUE TITLE
Docker image not working (missing dependency?)

### ISSUE THREAD

**Issue by Severino** [harmony-one/harmony#3806]
**Describe the bug**
When I try to run the dockerfile

OS: Ubuntu 20.04.2 LTS

Shell: GNU bash, version 4.4.0(1)-release (x86_64-unknown-linux-gnu)

Docker: Docker version 20.10.7, build f0df350

**To Reproduce**

Follor the steps as described in the Readme.md of this repo
to setup the project.

Try to launch the localnet on docker by executing the commands 
at section **Dev Docker Image**: 

```
cd $(go env GOPATH)/src/github.com/harmony-one/harmony
make clean
docker build -t harmony .
```

Result:

Installation seems to work fine until step 38/57.

```
Step 38/57 : RUN eval "\$(~/bin/gimme ${GIMME_GO_VERSION})" ; scripts/go_executable_build.sh -S
 ---> Running in 3192770892e7
go version go1.16.3 linux/amd64
building ./cmd/harmony
api/service/legacysync/syncing.go:14:2: missing go.sum entry for module providing package github.com/Workiva/go-datastructures/queue (imported by github.com/harmony-one/harmony/api/service/legacysync); to add:
	go get github.com/harmony-one/harmony/api/service/legacysync
...
The command '/bin/bash -c eval "$(~/bin/gimme ${GIMME_GO_VERSION})" ; scripts/go_executable_build.sh -S' returned a non-zero code: 1
```

**Expected behavior**
Create a docker image and run a docker instance as specified within the Dockerfile.

**Environment (please complete the following information):**
OS: Ubuntu 20.04.2 LTS

Shell: GNU bash, version 4.4.0(1)-release (x86_64-unknown-linux-gnu)

Docker: Docker version 20.10.7, build f0df350

Go verison: go version go1.16.3 linux/amd64

**Additional context**

I think I tested it on Mac, Linux and Windows. Same behaviour on all 3 platforms. 
I just realized that the path is asking for a GIMME_GO_VERSION that is supplied by [travis_cli/gimme](
https://github.com/travis-ci/gimme)
Therefore it may be that travis_CLI is a requirement for this to work.

**Comment by matthewwoop** [comment]
Hey, I was trying to build the Docker image this morning and experienced the same problem.

The problem + fix is similar in nature to #3804 -- go deps need to be downloaded prior to building the binaries. My PR simply updates the Dockerfile to include `go mod tidy` prior to building.

**Comment by Severino** [comment]
Nice, will try it tomorrow. Thanks 😎👍

**Comment by Severino** [comment]
Nice, it works!!! 😄 

But, correct me if I'm wrong, the linked pull request only changes one line in README.md
