### ISSUE TITLE
eth_getLogs/hmy_getLogs rpcs fail with json error for larger block ranges

### ISSUE THREAD

**Issue by gupadhyaya** [harmony-one/harmony#3817]
**Describe the bug**
`eth_getLogs` RPC throws json error while querying for more than 8k blocks. This RPC works correctly in ethereum and other eth compatible chains.

**To Reproduce**
* Try the following example RPC
```
{ 
"method": "eth_getLogs", 
"params": [ 
    { 
         "fromBlock": "0x0", 
         "toBlock": "latest", 
         "address": "0x596b8b79cd8afe859411a7cb1777997e16fbe0fc", 
         "topics": [ "0xc06755e812d0c0a45e23816224e410bd6a63a0ff2b33bdcd5bc6d411c3522fc9" ] 
    } 
 ]
}
```

**Expected behavior**
`eth_getLogs` or `hmy_getLogs` should return the returns even when queries for large block ranges.

**Comment by JackyWYX** [comment]
Please note: This will create a huge load at server end and can be potentially be a spamming endpoint. If other chains does not have this limit, it will be very easy to paralyze the node through spamming.

**Comment by gupadhyaya** [comment]
@AlexiaChen can you investigate this issue? basically, we want to support getting logs for large block ranges. This is how ethereum works, but on harmony we only are able to query for 8-10k block range. Let me know if you have any questions. thanks.

**Comment by AlexiaChen** [comment]
Hey @gupadhyaya , this requirement just conflict with new @JackyWYX 's PR already merged (5 hours ago).   https://github.com/harmony-one/harmony/pull/3830/files#diff-f8e17b115e5fb7f93b9f4f6e5f595d892353b56e2e3e0b0d6edaba857afd0293R388

it just limit block range


Could you Please take a look for this issue ?   @rlan35 @JackyWYX

**Comment by gupadhyaya** [comment]
@AlexiaChen can you investigate how go-ethereum allows querying for large block ranges?

**Comment by JackyWYX** [comment]
> @AlexiaChen can you investigate how go-ethereum allows querying for large block ranges?

Ethereum does not have this limitation since Ethereum do not provide public API services. Infura is a permission service provider that will limit this heavy load by limit the usage per user.

**Comment by AlexiaChen** [comment]
> 
> 
> @AlexiaChen can you investigate how go-ethereum allows querying for large block ranges?

Agreed with @JackyWYX , ETH does not fully expose their RPCs to public network,  here are stronger evidence from official issue replied from ETH contributor:

- https://github.com/ethereum/go-ethereum/issues/22567#issuecomment-871434958
- https://github.com/ethereum/go-ethereum/issues/22529#issuecomment-804988407

**Comment by rlan35** [comment]
Fixed with jacky's range limit.
