### ISSUE TITLE
slow RPC responses

### ISSUE THREAD

**Issue by LeoHChen** [harmony-one/harmony#3831]
**Describe the bug**
Based on the dashboard data for RPC canary, there are a few RPC requests have very slow response time.  Those handlers may block or slow down the endpoint when responding to the request.  They may potentially be used by spammers to attack the RPC endpoint. 

A few data points,

![image](https://user-images.githubusercontent.com/4513927/126832151-0abd8550-0981-4155-909e-af0f0fde4355.png)

![image](https://user-images.githubusercontent.com/4513927/126832417-8f0b3c0d-94a1-41f3-bcab-cfdaebae7791.png)

![image](https://user-images.githubusercontent.com/4513927/126832553-e7cade58-c61b-42ad-a616-3dc222b6f199.png)

**Comment by LeoHChen** [comment]
![rpc](https://user-images.githubusercontent.com/4513927/126832898-246f00a6-40d9-44e5-95f2-4b277c29904b.png)

**Comment by rlan35** [comment]
@AlexiaChen please work with soph to clarify the metrics. The data used may be wrong.

**Comment by AlexiaChen** [comment]
@rlan35    Yes, already clarified with Soph on Discord

**Comment by AlexiaChen** [comment]
> 
> 
> @AlexiaChen please work with soph to clarify the metrics. The data used may be wrong.

I re-confirmed with @sophoah  those data come from the canary test, directly from AWS. it's not a measurement done on the node itself..   So, it's not a data with  wrong used the metrics I provided.   Thats weird.
