### ISSUE TITLE
List assets API

### ISSUE THREAD

**Issue by hashmesan** [harmony-one/harmony#3835]
# Problem/limitation At Hand

In order to query the account's ERC20/721/1155 balances, we need to know the list of assets associated to the account. Otherwise we would be querying a lot of non-relevant assets, making query time too long or unusable. Currently the assets API are on the [Explorer backend](https://github.com/harmony-one/explorer-v2-backend).  It is not reliable enough to use for wallets/ dapps application.

Wallet developer & Dapps developer will greatly benefit from this api. 
The explorer assets responsiveness and reliability will be improved from this api.

**Which component?**

- [ ] consensus
- [ ] deploy script
- [X] wallet
- [X] explorer
- [ ] node script
- [ ] test automation
- [ ] demo app
- [ ] others ...

# Proposed Solution

Based on my research (see Context) stellar and cardano provides such api as part of their official api. Usually these are part of separate API service that just specializes in block synchronization and indexing.  I propose it to be available on the api.harmony.one or this repo.  It could piggy back to any existing block synchronization code.  With listAssets api, we can use an eth-balance-checker like smart contract to query the balances.

# Alternatives Considered

The alternative is a metamask approach of making the user enter the token address which is not a good user experience. 
The harmony explorer hasn't been reliable enough, and fetchTokens doesn't function well.  IMO synchronization code should be on blocking languages like golang instead of nodejs.
 
# Additional Context

**ETHEREUM**

Ethereum rpc does not provide token balances. It’s usually provided on the secondary api such as etherscan or web3api.
Metamask has a smart contract to get balances given account, and token addresses:
https://github.com/metamask/metamask-extension/blob/5bac055ba62bb93da28784c2beabb268256b4cf7/app/scripts/controllers/detect-tokens.js#L9
https://github.com/wbobeirne/eth-balance-checker

Etherscan indexes all the tokens transactions:
https://etherscan.io/apis#accounts
Web3api provides an api
https://medium.com/amberdata/how-do-i-get-a-list-of-my-ethereum-erc20-tokens-tutorial-part-2-df1aafef3eed

**STELLAR**
Stellar API indexes all the tokens: https://developers.stellar.org/api/resources/accounts/object/

**Cardano**
Cardano has official API: https://input-output-hk.github.io/cardano-wallet/api/edge/#operation/listAssets

**Comment by polymorpher** [comment]
Yes, this would be very useful, especially for client side applications. I use an on-chain approach to track tokens in smart contract wallet: https://github.com/polymorpher/one-wallet/wiki/Token-Tracking . I was asked to also share it here

**Comment by LeoHChen** [comment]
Can this be converted to a bounty? @rlan35
