### ISSUE TITLE
cannot build bootnode 

### ISSUE THREAD

**Issue by Moscovi** [harmony-one/harmony#3841]
**Describe the bug**
Cannot build bootnode when trying to use make command
Added screenshot

**To Reproduce**
1. Check out code with "sha1" commit
2. Build
3. run local test using "...." commands

**Expected behavior**

**Screenshots**
<img width="1439" alt="Screen Shot 2021-08-05 at 14 25 44" src="https://user-images.githubusercontent.com/73650080/128343365-89341e27-8d81-41b7-8c4f-fd6751a18ac8.png">

**Environment (please complete the following information):**
 - OS: [Linux, MacOS]
- Go environment [ ```go env``` ]

Using MacOS Big Sur 11.3 with M1 Chip

GO111MODULE=""
GOARCH="arm64"
GOBIN=""
GOCACHE="/Users/mosco/Library/Caches/go-build"
GOENV="/Users/mosco/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/mosco/Documents/go-workspace/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/mosco/Documents/go-workspace"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_arm64"
GOVCS=""
GOVERSION="go1.16.6"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/mosco/go/src/github.com/harmony-one/harmony/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/cv/7ykp91l13rq6qhsw6df9gwl40000gn/T/go-build3381683292=/tmp/go-build -gno-record-gcc-switches -fno-common"

**Additional context**

**Comment by LeoHChen** [comment]
what's the build make you used?

I can build it using

```
go mod tidy
make
```

**Comment by ONECasey** [comment]
Fixed.
