### ISSUE TITLE
[Feature] Support fetching previous block VRF values on chain for secure random number generation

### ISSUE THREAD

**Issue by gmulhearn** [harmony-one/harmony#3846]
# Problem/limitation At Hand

The ability to use VRF values of the current block on chain is extremely powerful for creating secure randomness dApps. 
However, using the VRF values in contracts is only secure if your usage is secure. It is well known that using only current block information (timestamp, blocknumber, VRF value) as a source of randomness within a contract is NOT secure because a malicious user could create a contract that knows an outcome of that randomness before calling on your vulnerable contract.

The only secure way to generate secure random numbers, in any blockchain, is with a commit-resolve process. E.g. A user will commit to using the randomness of block X in the future, and then they will use the randomness (e.g. the VRF value) of block X to determine the outcome of their commitment when it becomes available. 

A commit-resolve process for harmony using VRF is potentially one of the most secure implementations of a random number generator on ANY blockchain. HOWEVER, there is still a hole in commit-resolve VRF implementations, and it's due to the fact that you can **only** obtain the CURRENT block's VRF. 

To demonstrate the issue, take the following example:

**Block # 10:** 
> * User uses a contract to commit their 5 ONE as a 'bet' on the outcome of the VRF value of block # 11.
> * Contract notes their bet and selected block.

**Block # 11:** 
> * User sees it is block # 11 and makes a transaction to the contract to request to resolve the bet. The contract is designed such that if the current block number is the block the user originally committed to, the block's VRF value will be used to determine the outcome.
> * Malicious leader sees that the user will win if the transaction goes through on this block, and decides not to include it in the block.

**Block # 12:**
> * Leader decides to include the transaction now
> * Contract receives the transaction, however since it is not block # 11 anymore, the contract has no way of verifying whether the user maliciously sent their transaction late for a different outcome, or if it was a genuine delay, therefore it would be insecure for the contract to base the outcome of the bet off of this block (block # 12) and the contract has no way of knowing what the VRF of the committed block (block # 11) was.

There are numerous ways this process can be front-run (both by the user themselves, or by the leader, or both), and there is no way to guarantee secureness and fairness for the user.

The only way to secure this process is if contracts are able to fetch VRF values of previous blocks, therefore allowing for this commit-resolve process to work.

I believe this would be huge for harmony, as FWIK, it would be the only chain that supports a **native** (i.e. not depend on chainlink VRF), **secure**, and **verifiable** random number generation process - which is **extremely** useful for dApps.

**Which component?**

- [ ] consensus
- [ ] deploy script
- [ ] wallet
- [ ] explorer
- [ ] node script
- [ ] test automation
- [ ] demo app
- [x] others ...
- [x] precompile contracts

# Proposed Solution

An approach for this would be to expand the capabilities of the precompile vrf contract (introduced in #3703) to let the function's input value be the requested block number (instead of just ignoring the input value), and then use this requested block number to inject that requested block's VRF as the return value.

I am not familiar with golang or the intricacies of harmony's codebase, however I have included a possible way of doing this in my draft PR #3847 . However, there are likely other ways.

If there are optimization concerns about making validators/leaders reach far into the blockchain history to retrieve an old block's VRF, then there could be a constraint implemented such that the requested block must be within **x** blocks from the current block. This constraint would be similar to the `BLOCKHASH()` EVM OpCode, which only allows blockhash queries up to 256 blocks ago. 
The exact constraint should be choosen with consideration for what would be reasonably fair in the commit-resolve process. For example, if the constraint was 'within 10 blocks' then the user could suffer genuine network issues during the 10 blocks that they could get their committed block's VRF, and then miss out. But if the constraint was 'within 256 blocks' the user would have 256 blocks (nearly 10 minutes) to retrieve the VRF of their committed block, if they take longer than 10minutes, it may be reasonable to assume they are malicious, and likewise, if a leader doesn't include a user's transaction within 10minutes, then the maliciousness of that leader should be **very** obvious to other nodes.

# Alternatives Considered

A possible solution that does not require any code changes, is by deploying a recognized contract on harmony which keeps a database of all block VRFs. The issue with this is that it would require the community to run the contract, and call it every single block to keep the database up to date with every block's VRF. Which is very inefficient, and there's still no guarantee a leader won't purposefully miss a block.

# Additional Context

* original implementation of VRF on chain: https://github.com/harmony-one/harmony/pull/3703

**Comment by gmulhearn** [comment]
UPDATE: added a PR showcase how the solution could be implementation. I would really appreciate feedback/contribution on the PR as I'm not very familiar with golang development.

**Comment by rlan35** [comment]
Thanks for the proposal. It is a good point on the usage of VRF in real-world Dapp situation. I agree that allowing fetching VRF from old blocks up to like 256 blocks will be significantly more convenient for Dapp developers to build fair and secure random logics.

We will work on this feature and launch it in the near-term releases.

**Comment by rlan35** [comment]
Fixed in #3850
