### ISSUE TITLE
bash scripts/install_build_tools.sh ERROR= goget.sh: jq not found

### ISSUE THREAD

**Issue by Defi-Ninja** [harmony-one/harmony#3852]
**Describe the bug**
* I can not ensure build tools are of correct versions by running `bash scripts/install_build_tools.sh`.
* I received and corrected the missing *go.sum* entry **before** ever attempting to run the above code. 
* ***Issue*** when running `bash scripts/install_build_tools.sh` I receive: 'goget.sh: jq not found'.
* I've switched Directories and I literally see *goget.sh* in the same folder but nothing I do gets a different result...

**To Reproduce**
1. After you: *Build the harmony binary & dependent libs*
2. and negotiate any *go.sum* issues
3. run `bash scripts/install_build_tools.sh`

**Expected behavior**
Expecting to get version numbers or some positive output, anything but a missing file error.

**Screenshots**
n/a

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04.3 LTS
- Go environment:
```
GO111MODULE=""
GOARCH="amd64"
GOBIN="/home/myUserName/go/bin"
GOCACHE="/home/myUserName/.cache/go-build"
GOENV="/home/myUserName/.config/go/env"
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOMODCACHE="/home/myUserName/go/pkg/mod"
GOOS="linux"
GOPATH="/home/myUserName/go"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVERSION="go1.16.3"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
GOMOD="/dev/null"
PKG_CONFIG="pkg-config"
```

**Additional context**
I read that it has something to do with Docker but I am truly stuck. I have not jumped ahead nor skipped any previous steps. All is good up until this point.

**Comment by Defi-Ninja** [comment]
I kept going with the instructions and ran `docker build -t harmony .`. Other than getting in red: `apt-utils is not installed` the process seems to have completed which is confusing and stirring my curiosity. The last two lines of output from the build command are 
```
Successfully built 0793fd19f4f1
Successfully tagged harmony:latest
```
There was a lot of red throughout the 58 steps but nearly all sounded informative rather than negative so I guess I am good to go? I really don't want to move to far forward until I have some deeper understanding of my core *issue*.

**Comment by sophoah** [comment]
hey @Defi-Ninja can you paste into a gist or pastebin the output log ? thanks

**Comment by Defi-Ninja** [comment]
@sophoah Are you referring to Ubuntu system logs so something like `dmesg |grep [keyword]`? Or similarly, the syslog file? 
Or maybe do you mean something specific to go, I am rather green concerning anything Linux. Please help me understand precisely *what* or *how* to get what you seek and I'll jump on that ASAP

Thanks for the speedy reply!

**Comment by sophoah** [comment]
just referring to the output when you run the different command.

**Comment by LeoHChen** [comment]
> @sophoah
> 
> ```
> $ bash scripts/install_build_tools.sh
> goget.sh: jq not found
> ```

please install `jq` https://stedolan.github.io/jq/

**Comment by wujiaying1** [comment]
I also encountered this problem, I would like to ask how to solve it in the end.
