### ISSUE TITLE
[RPC] Error: call revert exception

### ISSUE THREAD

**Issue by sophoah** [harmony-one/harmony#3860]
**Describe the bug**
Community has been experiencing issue while using harmony dapps, while some seems to be working better than others, or use workaround like refreshing multiple time the dex, the most obvious way to hit the issue is to use vfat for one the harmony pool https://vfat.tools/harmony/ usually, when one fails, all will fails with an error similar to this :
```
Reading smart contracts...

{
  "reason": null,
  "code": "CALL_EXCEPTION",
  "method": "poolLength()",
  "errorArgs": null,
  "errorName": null,
  "errorSignature": null,
  "address": "0x65bFeeC6E0679EB5913b25063Aab228ccab43161",
  "args": [],
  "transaction": {
    "data": "0x081e3eda",
    "to": "0x65bFeeC6E0679EB5913b25063Aab228ccab43161"
  }
}
Oops something went wrong. Try refreshing the page.
```
with the method being different 

chrome dev tool will show something similar to this : 
```
ethers_helper.af7a787ddcb3ce2d64168751f521e11f.js:271 Error: call revert exception (method="govToken()", errorArgs=null, errorName=null, errorSignature=null, reason=null, code=CALL_EXCEPTION, version=abi/5.4.0)
    at Logger.makeError (index.js_+_1_modules:238)
    at Logger.throwError (index.js_+_1_modules:249)
    at Interface.decodeFunctionResult (interface.js:524)
    at _callee6$ (index.js_+_1_modules:557)
    at l (inject_start.js:388)
    at Generator._invoke (inject_start.js:388)
    at Generator.next (inject_start.js:388)
    at fulfilled (index.js_+_1_modules:92)
```

when using DEXes, slowness or no display of the data will occurs until a refresh and chrome dev will show:
```
updater.tsx:193 Failed to fetch multicall chunk (64) [{…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}] 1666600000 Error: call revert exception (method="aggregate((address,bytes)[])", errorArgs=null, errorName=null, errorSignature=null, reason=null, code=CALL_EXCEPTION, version=abi/5.4.0)
    at e.value (index.ts:213)
    at e.value (index.ts:225)
    at e.value (interface.ts:425)
    at index.ts:332
    at l (runtime.js:63)
    at Generator._invoke (runtime.js:294)
    at Generator.next (runtime.js:119)
    at o (4.531ae6a5.chunk.js:2)
 ```
that was when visiting https://sonicswap.io/#/staking

**To Reproduce**
1. use VFAT multiple time a day until the error happens

**Expected behavior**
there shouldn't be any error all the time

**Screenshots**
NA

**Environment (please complete the following information):**
NA

**Additional context**
See community feedback;
- https://www.reddit.com/r/harmony_one/comments/pdhsi2/am_i_the_only_one_frustrated_with_the_rpc_issues/
- https://t.me/HarmonyDevs/8308

**Comment by LeoHChen** [comment]
Please try to "[CLEAR BROWSER STORAGE]" and reconnect the wallet. A simple refresh may not work in some cases. "[CLEAR BROWSER STORAGE]" may help, based on my experience.

**Comment by sophoah** [comment]
Davinci user is hitting the issue 

![image](https://user-images.githubusercontent.com/35721420/131550010-d8971b5b-0863-4e80-90d1-c079b868d481.png)

**Comment by rlan35** [comment]
seems these errors are from the Dapp or sdk level. @gupadhyaya do you have some insights?

**Comment by mirrormirage0** [comment]
Did some tests. 

Got error on vfat  when using Mainnet RPC https://api.harmony.one

![error-api](https://user-images.githubusercontent.com/29485946/131676882-f3ce3e90-d01b-422f-8998-4028422437c6.png)

Switched to new api Backup RPC https://g.s0.t.hmny.io. Error is gone, and data loads. 

![error-api-2](https://user-images.githubusercontent.com/29485946/131677029-3b190a86-8a14-4c42-bb39-950814abc50d.png)

Switched back to main rpc https://api.harmony.one . Data loads successfully. 

Ran into the error again on https://api.harmony.one (after 5 minutes)
![error-api-3](https://user-images.githubuse

Switched to backup rpc  https://g.s0.t.hmny.io . Error persists
![error-api-4](https://user-images.githubusercontent.com/29485946/131678510-ebc39fc4-acd2-4601-9791-d51512b60511.png)
rcontent.com/29485946/131678317-d030adc0-679e-44ca-a28e-38cbc6191e1f.png)

**Comment by mirrormirage0** [comment]
Did some tests with vfat tools using main rpc https://api.harmony.one and backup rpc https://g.s0.t.hmny.io 
Getting errors repeatedly.
```
{
  "reason": null,
  "code": "CALL_EXCEPTION",
  "method": "name()",
  "errorArgs": null,
  "errorName": null,
  "errorSignature": null,
  "address": "0xeb049F1eD546F8efCxxxxxxxxxxxx",
  "args": [],
  "transaction": {
    "data": "0x06fdde03",
    "to": "0xeb049F1eD546F8xxxxxxxxxxxxxxxx"
  }
}
```
Oops something went wrong. Try refreshing the page.

**Comment by BrunoMarshall** [comment]
in DaVinci seems like when transaction is reverted by EVM means that the user trying to put on sale is not the owner
maybe we can change the error message

**Comment by sophoah** [comment]
closing this issue since the recent survey shows that user are no longer having this error.
