### ISSUE TITLE
### User Story

### ISSUE THREAD

**Issue by DSBUGAY2** [harmony-one/harmony#3861]
### User Story
As a funder of a Gitcoin bounty, I want a reliable way to contact bounty applicants and workers directly while still keeping both my and their email addresses anonymous so that we can discuss the bounty and progress easily.

### Description
Funders and developers who are posting/working on bounties often need a way to message privately (ie. not in Github issues). There is already an "email" button on some Gitcoin user profiles, but the large majority of users do not display their email's publicly on Github for privacy reasons, so this is not a reliable solution as it stands. This task is to create a proxy email tool - similar to how Craigslist works, where you can email the poster of a listing, without revealing your or their email addresses. 

### Definition of Done
- Users can contact others on the platform without revealing either of their private emails
- For each bounty there should be a "contact funder" button at the top of the bounty page.
- For every "start work" or applicant there should be a "contact worker" button by each of the applicants/workers.
- Emails should indicate what user it was from (display their Gitcoin handle) in order to prevent impersonation, and so funders know which person working on their bounty is reaching out.

__Originally posted by @zacheryschiller in https://github.com/gitcoinco/web/issues/9414__

**Comment by MaxMustermann2** [comment]
Not related to Harmony.
