### ISSUE TITLE
Min commission causes validator to be stuck in active=false

### ISSUE THREAD

**Issue by AutoStake-com** [harmony-one/harmony#3871]
**Describe the bug**
If a validator has passed the threshold where they are allowed to charge 0% and is put into `--active=false` and their max comission change rate is less than the amount needed to get to 5% then that validator is stuck in `--active=false`

**To Reproduce**
1. Start validator in testnet with `--max-change-rate 0.01 --rate 0.00`
2. change validator to `--active=false`
3. wait until 0% commission period has ended
4. trying to edit validator with `--active=true` will fail

**Expected behavior**
edit validator with `--active=true` should work automatically force validator to 5% commission.

**Environment (please complete the following information):**
 - OS: [Linux]

**Comment by BlockNgine** [comment]
caused by this commit https://github.com/harmony-one/harmony/commit/b0bf39861d394e45d4ff0506bc001fee69d5fef9 which is not documented

**Comment by BlockNgine** [comment]
testnet validator https://staking.harmony.one/validators/testnet/one13nz87qrj9tvnqzu420z4vy55qp8kcl2y8tg2dt is not able to re-activate with error `commit: v1-8561dc3, error: Catch all RPC error: commission rate can not be lower than min rate of 5%!`

**Comment by BlockNgine** [comment]
Or trying to increase comission above minimum rate:

```
./hmy --node="https://api.s0.b.hmny.io" staking edit-validator --validator-addr one13nz87qrj9tvnqzu420z4vy55qp8kcl2y8tg2dt --rate=0.05 --passphrase
```

```
Warning: Using outdated version. Redownload to upgrade to v417-bc3f026
commit: v1-8561dc3, error: Catch all RPC error: change on commission rate can not be more than max change rate within the same epoch
check hmy cookbook for valid examples or try adding a `--help` flag
```

**Comment by BlockNgine** [comment]
This is just a testnet node, I can just give you the keys if you want to try for yourselves?

**Comment by sophoah** [comment]
@rlan35 this seems to be a scenario we never tested and accounted for. his validator is unelected (ie active=false) and his max change delegation is at 2% only hence :
1) he can't change to something at 5%
2) the protocol is not automatically updating his fees because he is not elected I guess and he also can't activate his validator as the fees are currently below 5
