### ISSUE TITLE
Bloated RPC method `GetAllValidatorInformation`

### ISSUE THREAD

**Issue by JackyWYX** [harmony-one/harmony#3875]
### Current design

The RPC method `GetAllValidatorInformation` is used for staking dashboard showing validator messages. The method was initially implemented with limited time and resources thus all information are put into one method for easy implementation . 

### Problem

But as harmony staking grows, the RPC is growing super excessive and bloated. On mainnet, a single query will return data as large as 10MB. This will easily cause a RPC delay exceeding 3 seconds.

### Proposal

Thus we need to deprecate this method and decompose it into several RPC methods for simplicity. The proposed solution is:

1. Add a new method `GetValidatorsByBlockNumber` which gives a list of validator addresses.
2. Developers then call `GetValidatorInformation` to get detailed information for each validator.

Please let me know if this alternative can replace the bloated RPC method. And please also write down your concerns if any. Thanks.

**Comment by sophoah** [comment]
@hypnagonia @potvik can you comment in this change proposal, I believe the staking dashboard is heavily using it.

**Comment by hypnagonia** [comment]
looks totally reasonable to me

**Comment by sophoah** [comment]
@JackyWYX staking dashboard and other monitoring dashboard tool use that RPC call to get everything in one shot. Ultimately, those tool still need of **all** validators information. That change will require them and us (staking dashboard) to make code changes.

before implementing that solution I would like to see #3874 idea to cache and freeze the validator_all_info every 64 blocks. Thanks

**Comment by JackyWYX** [comment]
Agreed. But over optimize on 64 rewards can potentially cause problem when validator send a edit validator transaction... I would better come back to this after the validatorWrapper structure is optimized.

**Comment by MaxMustermann2** [comment]
#3874
