### ISSUE TITLE
When transferring coins to stacking or transferring to another wallet, it does not work

### ISSUE THREAD

**Issue by emaejoker7477** [harmony-one/harmony#3880]
***Describe the big**
I registered on the website and received the wallet number to which I transferred the coins.
https://staking.harmony.one/portfolio/mainnet

**Expected behavior**
When transferring coins to stacking or transferring to another wallet, it does not work

**Screenshots**
![Безымянныйп](https://user-images.githubusercontent.com/91025058/133936295-35be9623-1cf9-4458-9c78-69e65fd949da.png)

**Environment (please complete the following information):**
windows 10

**Comment by emaejoker7477** [comment]
Thanks !
I do not know how you found out the address of FINANCE
Thank you very much, all the coins were returned
I am very grateful to you ...
the issue is resolved !

**Comment by sophoah** [comment]
For info, no one didn't do anything, you might have done something that triggered your fund to be returned to you.
