### ISSUE TITLE
[Feature] Allow configuring log rotation

### ISSUE THREAD

**Issue by gab-nando** [harmony-one/harmony#3888]
# Log rotation configuration

The [lumberjack logger](https://github.com/natefinch/lumberjack) allows to easily configure log retention / rotation.
Currently only the max log size can be specified leaving the logs directory growing indefinitely, if not using logrotate or similar external tools to enforce log retention.

I put together a PR to implement retention by either max number of days or number of logs to keep. Both flags default to 0 for backwards compatibility.

Go tests run via `make go-test` fail because of a missing script. At a quick look the script seems to be called `travis_go_checker.sh` but in the [test script](https://github.com/harmony-one/harmony-test/blob/master/localnet/scripts/run.sh#L60) it references `travis_checker.sh` instead.

```
building ./cmd/harmony
go: downloading github.com/pelletier/go-toml v1.9.3
go: downloading golang.org/x/sync v0.0.0-20210220032951-036812b2e83c
go: downloading google.golang.org/grpc v1.33.2
go: downloading github.com/coinbase/rosetta-sdk-go v0.6.10
go: downloading golang.org/x/time v0.0.0-20210220033141-f8bda1e9f3ba
go: downloading github.com/json-iterator/go v1.1.10
go: downloading github.com/modern-go/concurrent v0.0.0-20180306012644-bacd9c7ef1dd
go: downloading github.com/modern-go/reflect2 v1.0.1
Harmony (C) 2020. harmony, version v7174-v4.2.1-13-g04c86b97-dirty (@ 2021-09-29T18:35:00+0000)
/go/src/github.com/harmony-one/harmony/bin /go/src/github.com/harmony-one/harmony
/go/src/github.com/harmony-one/harmony
bash: ./scripts/travis_checker.sh: No such file or directory
```

**Comment by LeoHChen** [comment]
merged
