### ISSUE TITLE
[Metrics] monitor the duration of each RPC handlers in grafana

### ISSUE THREAD

**Issue by LeoHChen** [harmony-one/harmony#3903]
Alex had added the following metrics to the RPC layer to keep track of the duration of each RPC handler in the following PR. We shall add the Grafana dashboard to monitor those metrics to help us triage the RPC latency issues.

---
commit 5222a4109e3b2e4d47a429fdabebc174287de52c (alex)
Author: MathxH Chen <brainfvck@foxmail.com>
Date:   Fri Jul 30 05:25:09 2021 +0800

    [metrics] Add NewGaugeVec metric to record actual duration for RPCs (#3827)

    * [metrics] Add rpc_request_delay_gauge

    * [metrics] Adjust buckets for rpcRequestDurationVec
    *

**Comment by sophoah** [comment]
2 new panel has been added showing the all the RPC at a given time:
- 1) for a given instance
- 2) for all instances with sum per RPC 

for both, panel is similar to this: 
![image](https://user-images.githubusercontent.com/35721420/137705582-57b8ff3f-6a28-49ce-bc6d-8178cf9a2454.png)

cc @LeoHChen
