### ISSUE TITLE
[devop] build new DNS sync nodes

### ISSUE THREAD

**Issue by LeoHChen** [harmony-one/harmony#3909]
We are currently reusing validators as DNS sync nodes before we have a fully decentralized syncing solution.
In order to maintain a better separation and service, it is time to build independent DNS syncing nodes, so that it won't affect the existing validator nodes.

those nodes can run as explorer node mode using pruned DB.
let's start with shard 1/2/3 and then shard0, as we are moving towards no internal validator nodes on shard1/2/3 at first.

for shard1/2/3, I'd say 3 nodes per shard would be sufficient to serve as DNS sync node.

The initial task list,

- [x] setup new pruned explorer nodes in shard 1/2/3 as new sync nodes, 3 nodes per shard
- [x] update route53 records
- [x] setup separate monitoring dashboard
- [x] setup pagerduty for DNS sync nodes
- [x] do above the same process on shard 0

The expected timeline is by end of November.

**Comment by sophoah** [comment]
@LeoHChen this is completed, i am closing it.
