### ISSUE TITLE
node stuck - legacy node sync logic not working

### ISSUE THREAD

**Issue by sophoah** [harmony-one/harmony#3929]
**Describe the bug**
Testnet node got stuck. During the issue, there were in total 3 DNS node, and 2 out of the 3 got stuck even though the last DNS node had a higher block.

 the fix is easy as it involves removing from the DNS the two DNS node then a restart of the node will force the sync with the 3rd DNS node that is now left alone.

**To Reproduce**
Wait for the problem to happens while all the 3 nodes are DNS.

**What is the expected behavior**
it shouldn't get stuck

**Screenshots**
N/A

**Environment (please complete the following information):**
- latest harmony code : `v7195-v4.3.0-21-g42c88b55`

**Additional context**
N/A

**Comment by LeoHChen** [comment]
The logic is not a problem as we use majority voting in terms of the block height from other DNS nodes for syncing to make sure at least there is no hard-fork.  This is a known limitation in legacy syncing, for new syncing logic, it won't be a problem.  Thus I don't see a need to fix it.

**Comment by sophoah** [comment]
Noted I'll close that issue then
