### ISSUE TITLE
Validator got booted with no apparent valid reason

### ISSUE THREAD

**Issue by sophoah** [harmony-one/harmony#3940]
**Describe the bug**
Validator got booted with no apparent valid reason.

validator (one1j34kvpa66hzqmf4ywa2cyhwn4se2a03lvhxv4n) info is saying : 
```json
{
  "id": "0",
  "jsonrpc": "2.0",
  "result": {
    "active-status": "inactive",
    "booted-status": "manually turned inactive or insufficient uptime",
    "current-epoch-performance": null,
    "currently-in-committee": false,
    "epos-status": "not eligible to be elected next epoch",
    "epos-winning-stake": null,
    "lifetime": {
      "apr": "0.090319408561735133",
      "blocks": {
        "signed": 8933960,
        "to-sign": 8964942
      },
```
however, https://harmony.smartstake.io/val/411/true is showing good metric for the previous epoch 
![image](https://user-images.githubusercontent.com/35721420/142796293-aeaed850-1b21-4d43-a16b-ff7c95b32f17.png)

There is also no staking transaction to set the validator to inactive :
https://explorer.harmony.one/address/one1j34kvpa66hzqmf4ywa2cyhwn4se2a03lvhxv4n?activeTab=1

Additionally, total delegated stake is 7m and validator is using only 1 key, so shouldn't have been an issue during EPOS election phase.

**Comment by sophoah** [comment]
current self stake is also enough 
```json
"validator": {
      "address": "one1j34kvpa66hzqmf4ywa2cyhwn4se2a03lvhxv4n",
      "bls-public-keys": [
        "1fe163eb749c5ccb888aea81ed0f5431596e9419dfd6231b49f5a6dbb0fbc955b82ae4b48d42f05feb22f1da58164e15"
      ],
      "creation-height": 11204389,
      "delegations": [
        {
          "amount": 1.009961e+22,
          "delegator-address": "one1j34kvpa66hzqmf4ywa2cyhwn4se2a03lvhxv4n",
          "reward": 13849509503979450000,
````
1.009961e+22

and weirdly enough when validator is trying to set itself active he has an error :
```
./hmy --node="https://api.s0.t.hmny.io" staking edit-validator --validator-addr one1j34kvpa66hzqmf4ywa2cyhwn4se2a03lvhxv4n --active true --passphrase
```
![image](https://user-images.githubusercontent.com/35721420/142797035-978562f1-a09a-480b-a44b-b19f668103a4.png)

**Comment by sophoah** [comment]
@rlan35 when the validator is trying to add self stake he is an error saying the validator doesn't exist
![image](https://user-images.githubusercontent.com/35721420/142801655-d09df492-ca85-4e81-866a-6342bb7f31e8.png)

**Comment by rlan35** [comment]
Its min_sefl_delegation is "min-self-delegation": 20006000000000000000000    20006 ONE. His current self delegation is lower than that.
that's why he got turned inactive. He undelegated 28600 ONE last epoch: https://explorer.harmony.one/staking-tx/0x97b09f2bd286f7adf2ca16535567ff23fa69faca89fa924b4b71bae526e6df6a

**Comment by sophoah** [comment]
Thanks RJ make total sense now. I'll close the issue.
