### ISSUE TITLE
[Feature] Log slow RPC transactions

### ISSUE THREAD

**Issue by jacksteroo** [harmony-one/harmony#3943]
# Problem/limitation At Hand

Similar to MySQL slow transaction logs, RPC endpoints should log slow transactions (e.g. over 1 second).  When this occurs, log the request payload, including basic header requests (user-agent, x-forwarded-for)

Set the default threshold to 1 second, and can be changed as a startup parameter (slow-txn-log-threshold)

**Which component?**

- [ ] consensus
- [ ] deploy script
- [ ] wallet
- [ ] explorer
- [ ] node script
- [ ] test automation
- [ ] demo app
- [x] others ... RPC

# Proposed Solution

Send a log event that can be captured in the `/latest` log directory with the header and request JSON RPC payload, and an event to Prometheus

# Alternatives Considered

# Additional Context

This will help us trace the events of high CPU / memory impacts to help prioritize optimization work on the chain and RPC endpoints

**Comment by JackyWYX** [comment]
Yes. I am recently looking into this topic. Let me do this.
