### ISSUE TITLE
FIlters return filter not found

### ISSUE THREAD

**Issue by Hastatus12** [harmony-one/harmony#3950]
I'm going through the API docs [here](https://documenter.getpostman.com/view/6221615/Szt7BB28), i'm checking out the **Filter** section but i'm struggling understanding how they work. Every time i try to create a new filter, i get a `{'jsonrpc': '2.0', 'id': 1, 'error': {'code': -32000, 'message': 'filter not found'}}` error. I don't understand if it's a bug or if i'm doing something wrong.

Here is my Python 3.9 code:
```
import json
import requests

r = requests.post('https://api.s0.t.hmny.io/', json={"jsonrpc":"2.0","method":"eth_newPendingTransactionFilter","params":[],"id":1})

filter_1 = r.json()['result']

r = requests.post('https://api.s0.t.hmny.io/', json={
	    "jsonrpc": "2.0",
	    "method": "hmy_getFilterLogs",
	    "params": [
	       filter_1
	    ],
	    "id": 1
		}
	)

print(r.json())
```
Response: `{'jsonrpc': '2.0', 'id': 1, 'error': {'code': -32000, 'message': 'filter not found'}}`

**Comment by sophoah** [comment]
can you try with endpoint a.api.s0.t.hmny.io

**Comment by Davxyp** [comment]
> can you try with endpoint a.api.s0.t.hmny.io

I tried:

```
import json
import requests
import httpx

r = requests.post('https://a.api.s0.t.hmny.io', json={"jsonrpc":"2.0","method":"eth_newPendingTransactionFilter","params":[],"id":1})


filter_1 = r.json()['result']



r = requests.post('https://a.api.s0.t.hmny.io', json={
	   "jsonrpc":"2.0",
	   "method":"hmy_getFilterChanges",
	   "params":[filter_1],
	   "id":1
		}
	)

print(r.json())
```

Outpus is the same: `{'jsonrpc': '2.0', 'id': 1, 'error': {'code': -32000, 'message': 'filter not found'}}`

**Comment by sophoah** [comment]
@rlan35 what do you think ? is that a bug or ?

**Comment by OleFass** [comment]
You are using the wrong id. Do it like this:
```
data = {
            "jsonrpc": "2.0",
            "id": 73,
            "method": "hmy_newPendingTransactionFilter",
            "params": [],
        }
```
Also try to specifiy the header:
```
headers={'Content-type': 'application/json'}
```
