### ISSUE TITLE
write multiaddress to a pid file

### ISSUE THREAD

**Issue by LeoHChen** [harmony-one/harmony#396]
## Summary

The multiaddress of  beacon node, boot node , and harmony node are used in deployment script. They should be written to a pid file or something.

## Current Design

We currently output the multiaddress of beacon node, boot node, and harmony node to just log file. And the deployment script parse the log file to find the multiaddress.

## Problems

The parsing log file logic is both ugly and fragile.  We need to have have a better way, like to save the multiaddress to a pid file.

## Proposal

Save the pid/multiaddress to a pid file for each node and the deployment script can read the pid file to retrieve the multiaddress.

**Comment by mindstyle85** [comment]
@LeoHChen this still open?

**Comment by lijiang2087** [comment]
over a year old, closing until it's actively being worked on. @LeoHChen @mindstyle85
