### ISSUE TITLE
hmy_syncing & hmyv2_syncing return wrong payload

### ISSUE THREAD

**Issue by jorgecuesta** [harmony-one/harmony#3966]
**Describe the bug**
hmy_syncing & hmyv2_syncing (v1 & v2) based on the documentation should work like eth_syncing, when the node is syncing, it should return a result key with an object, when the node is sync it will return a false.

In both case here this rpc method return false even when the node is a lot behind of the shard height. In my case my node was 100k behind and it return "false" that mean "sync is done"

**To Reproduce**
1. Start a node
2. Run a curl request to it
```bash
curl -X POST --location "http://localhost:9500" \
    -H "Content-Type: application/json" \
    -d "{
        	\"jsonrpc\":\"2.0\",
        	\"method\":\"hmyv2_syncing\",
        	\"params\":[],
        	\"id\":0
        }" 
```
**Expected behavior**
Base on the documentation when the node is syncing it should return an object on the result key.
When the node sync is done, it should return false.

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04
 - Docker - `docker pull pocketfoundation/harmony` try with 4.3.1 and testnet

**Comment by rBurgett** [comment]
I have been trying to figure out how to get the syncing status as well. `eth_syncing`, `hmy-syncing`, and `hmyv2_syncing` all return the same wrong payload:
```json
{
    "jsonrpc": "2.0",
    "id": "",
    "result": false
}
```
As far as I can tell, there aren't any other means of checking whether or not the node is syncing. Very frustrating.

**Comment by jhony112** [comment]
Same issue here, Is there any resolution to this yet?
