### ISSUE TITLE
Failed RPC Calls: "rate: Wait(n=1) would exceed context deadline"

### ISSUE THREAD

**Issue by Zil-B** [harmony-one/harmony#3978]
**Describe the bug**
Various RPC calls are returning with the error:
```
rate: Wait(n=1) would exceed context deadline
```

This is occuring with regular json-rpc calls, VFAT, and Harmony Horizon Bridge from what I've seen so far.

Also being reported by users across several major dapps.

The transactions will be successful on the blockchain, but the RPC response fails.

From VFAT:
```
{

"code": -32603,

"message": "Internal JSON-RPC error.",

"data": {

"code": -32000,

"message": "rate: Wait(n=1) would exceed context deadline"

}
```

**To Reproduce**
Unable to reliably reproduce - it happens when attempting various eth_call methods.

**Expected behavior**
RPC calls should return successfully.

**Additional context**
Using RPC https://api.s0.t.hmny.io

Has also occurred on the WS endpoint.

**Comment by sophoah** [comment]
I deployed #3977 to the S0 RPC node, should be helping with the issue faced

**Comment by breezytm** [comment]
> I deployed #3977 to the S0 RPC node, should be helping with the issue faced

hello @sophoah I don't know if you recall but I did message you on discord about still seeing this error message in my log

**Comment by breezytm** [comment]
sounds good. looking forward to trying it out.

**Comment by sophoah** [comment]
Closing that issue as v4.4.x branch has a binary version without rate limits, feel free to try it https://github.com/harmony-one/harmony/releases/tag/v4.4.0

**Comment by socathie** [comment]
Same bug is happening constantly with Harmony Multisig Wallet these few days

**Comment by socathie** [comment]
![Screen Shot 2022-06-26 at 14 27 06](https://user-images.githubusercontent.com/22270063/175802397-a9bcdc0e-842a-4998-990d-63b55f3b7627.png)

**Comment by duyphanz** [comment]
I got this issue at https://api.harmony.one recently. Can I know if we have a way to reduce facing this issue from dApp side?

**Comment by jazcto86** [comment]
Yup... been seeing this for the past 48 hours or so with even basic calls like balanceOf() etc

`ValueError: {'code': -32000, 'message': 'rate: Wait(n=1) would exceed context deadline'}`
