### ISSUE TITLE
Node out of sync

### ISSUE THREAD

**Issue by COLUD4** [harmony-one/harmony#3988]
![截屏2022-01-13 下午2 46 42](https://user-images.githubusercontent.com/21240219/149279581-82219c12-95b3-4444-85f8-cdf46dd483a1.png)
The block height has always been 21651687

**Comment by jinnzy** [comment]
Me too, is there any solution?

**Comment by OleFass** [comment]
The software had problems. Check the discord for updates:
https://harmony.one/discord
Official hot fix (can also be found on the discord under 'network-announcements'):
https://docs.google.com/document/d/1OoTrTFEuLQooCkcF0goXYB36l9giOW64xw3310-g2R4/edit?usp=sharing

**Comment by ONECasey** [comment]
Fixed.
