### ISSUE TITLE
Critical metrics missing from prometheus endpoint

### ISSUE THREAD

**Issue by dirtycajunrice** [harmony-one/harmony#4008]
## Summary

Although there are a significant amount of histogram and finality metrics, there is a severe lack of basic data that would help operators in many ways. All of these metrics are available via the RPC endpoints so they should be able to be exposed.

## Current Design

Significant amount of histogram and finality metrics,

## Problems

Severe lack of basic data

## Proposal

Addition of many of the bits of information exposed via the RPC as scrapable data. Im not sure i will be able to list all of it, but examples are:

* current-block-number
* current-epoch
* dns-zone
* is-archival
* is-backup
* is-leader
* network
* node-unix-start-time
* p2p-connectivity
  * connected
  * not-connected
  * total-known-peers
 * role
 * shard-id

**Comment by SozinM** [comment]
Will add to this. Example of nicely done metrics that you could use - geth metrics

**Comment by easeev** [comment]
> Will add to this. Example of nicely done metrics that you could use - geth metrics

Adding these would be a good starting point:
- chain/head/block
- chain/head/header
- chain/head/receipt
- chain/account/reads
- chain/account/hashes
- chain/account/updates
- chain/account/commits
- chain/storage/reads
- chain/storage/hashes
- chain/storage/updates
- chain/storage/commits
- chain/snapshot/account/reads
- chain/snapshot/storage/reads
- chain/snapshot/commits
- chain/inserts
- chain/validation
- chain/execution
- chain/write

**Comment by SozinM** [comment]
These metrics are derived from ethereum metrics (https://geth.ethereum.org/docs/interface/metrics).
