### ISSUE TITLE
Blocknum jumped back to the start of the epoch

### ISSUE THREAD

**Issue by tuokiv** [harmony-one/harmony#4044]
**Describe the bug**
Shard0-validator suddenly restarted a service and jumped back to the blocknum of the start of the epoch over 6000 blocks behind.

**Environment (please complete the following information):**
Ubuntu 21.10, lowlatency kernel
AMD Ryzen 7 5700U, 16GB RAM, 1TB nvme-SSD (Bare metal)
Harmony 4.3.3 

**Additional context**
Syslog-dump attached.
[syslogdump.txt](https://github.com/harmony-one/harmony/files/7974485/syslogdump.txt)

**Comment by michaelotis** [comment]
Environment:

Two 16 core, 128 GB RAM, 3 TB NVMe dedicated boxes
One 8 core, 64 GB RAM, 3 TB NVMe dedicated box

Ubuntu 21.10
Harmony 4.3.3 / 4.4.0

Running 3 validators are run behind a nginx load balancer, validating and also providing RPC for minimal traffic (1000-1500 req per second)

Logs show no issues, block gets stuck, all three boxes are affected at various times. Service gets restarted, the service restart will time out every time and then is force shutdown. Upon coming back up, the affected node is 10-14k blocks behind, variable every time.

**Comment by sophoah** [comment]
@rlan35 could you look at the syslog dump above and see if there are anything we can do to prevent the node crash ?

**Comment by rlan35** [comment]
Didn't find any obvious issue on harmony code. More like golang or memory related issues. https://github.com/golang/go/issues/15861

One thing we can try is to revert this change https://github.com/harmony-one/harmony/pull/4019/files and see if the problem gets resolved. The increased leveldb cache could cause more memory usage and thus causing unexpected problems.
