### ISSUE TITLE
Hi, can you answer my confusion 

### ISSUE THREAD

**Issue by chinawangjh** [harmony-one/harmony#4047]
I run a validator, does it work fine to sync or run rpc without staking.
I'm running a validator without wallet staking.
Run ./hmy blockchain latest-headers block height is always the same.
After a period of synchronization, a large file is generated and is not updated.
What is the reason? 
-rw-r--r-- 1 root root   70K Feb  7 09:52 18829956.log
-rw-r--r-- 1 root root  726K Feb  7 09:52 LOG
-rw-r--r-- 1 root root   36M Feb  7 09:52 MANIFEST-18829957
-rw-r--r-- 1 root root   50K Feb  7 09:52 18829958.ldb
-rw-r--r-- 1 root root    18 Feb  7 09:52 CURRENT
-rw-r--r-- 1 root root    18 Feb  7 09:52 CURRENT.bak
-rw-r--r-- 1 root root   50K Feb  7 09:52 18829955.ldb
-rw-r--r-- 1 root root  1.1M Jan 31 01:49 LOG.old
-rw-r--r-- 1 root root   50K Jan 30 15:37 18829947.ldb

**Comment by sophoah** [comment]
Hey there, sorry for late reply

> I run a validator, does it work fine to sync or run rpc without staking.

yes

> After a period of synchronization, a large file is generated and is not updated.

multiple files are being created over time.

I'll close the issue but feel free to reopen if you have more queries which usually better be address on the harmony discord
