### ISSUE TITLE
Staking with Mobile Metamask allows signing the tx with a different wallet acct

### ISSUE THREAD

**Issue by jimbo2778** [harmony-one/harmony#4058]
**Describe the bug**
What you can't see here is there is an address mismatch. The signed in address on the left does not match the metamask acct currently being used. See the red icon on the upper right. two separate accts. I was able to sign a staking tx with address 1 using wallet address 2.
![Screenshot_20220213-123647_MetaMask](https://user-images.githubusercontent.com/83149641/153770044-1c09bbc9-ec84-4773-be6e-dc037f38527a.jpg)
![Screenshot_20220213-123718_MetaMask](https://user-images.githubusercontent.com/83149641/153770055-4f50fcae-708f-4151-be63-a7551bae9bd4.jpg)
![Screenshot_20220213-123737_MetaMask](https://user-images.githubusercontent.com/83149641/153770064-071fbe97-3e62-4196-a68a-6bc1aedc0693.jpg)
![Screenshot_20220213-123754_MetaMask](https://user-images.githubusercontent.com/83149641/153770072-51f33de2-5b70-41ff-a499-46f40f1c5b93.jpg)
![Screenshot_20220213-124534_Chrome](https://user-images.githubusercontent.com/83149641/153770094-a8c89023-f345-4708-b0b2-051fbb95af6b.jpg)

**To Reproduce**
Step1. Sign in to staking portal, start a staking tx and at the approval fail the tx.
Step2. Switch accounts in the wallet only. At this point it introduces a wallet mismatch. attempt a staking tx again and now you can sign the tx with the incorrect wallet. It does not show up as a staking tx in the explorer, but a normal tx with a weird "to" address. It also does not provide a staking amount. it does show up in your staking portfolio.
[https://explorer.harmony.one/tx/0x1e99433dfbe02be2eb369da4312d4b9591e4092c455701b9c9e5438a715e4e9e](url)
 

**Environment (please complete the following information):**
 - OS: Android

**Additional context**
Transactions were done using a Samsung Galaxy Tab S7+ with Android version 12 and the Mobile Metamask wallet.

**Comment by jimbo2778** [comment]
If this is normal behavior, feel free to close. Just wanted to bring the issue up in case it's not normal behavior.

**Comment by rlan35** [comment]
The txn is a smart contract transaction so it's not shown as staking txn. So it's normal.

I see in your screenshots that address one1k5t.... is logged in and also shown as the sender of the txn. What's wrong with the address mismatch?

**Comment by jimbo2778** [comment]
RJ so the tx was not signed with that address. However I think it may have just been a metamask ui issue with the metamask browser needing a refresh. I'm going to close this as I was unable to replicate it again with Dan at ETHDenver.
