### ISSUE TITLE
Give slashing reward to leaders to avoid front-running attacks

### ISSUE THREAD

**Issue by pkakelas** [harmony-one/harmony#4060]
## Summary

Currently, the reporting party is rewarded for making a double-sign accusation. Rewarding the reporter is not a viable option since the leader of the slot can front-run the reporter obtaining the accusation reward. 

## Problem

Consider a party V, who wishes to report a double-signing. V creates an accusation transaction that contains the double-sign proof, i.e., the offending blocks and signatures, and sends it on the network for publication. The transaction is received by all parties, including the validator VA, who is the leader of the slot after V makes the accusation. Since the double-sign proof is included in the transaction in plaintext, VA retrieves it and creates an accusation transaction of their own, which awards the reward to VA’s account. Therefore, VA effectively front-runs V in obtaining the accusation reward.

This is an instance of a larger family of attacks, directly related to “[Miner Extractable Value](https://ethereum.org/en/developers/docs/mev/)”.

## Proposal

Although this issue is not a direct security threat, it may cause confusion for users that report an offense and expect to be rewarded. A solution is to award the reporting award to the leader who includes a slashing proof in a block. In particular, regardless of which user creates the proof and/or submits the transaction that records the accusation, the slashing reward is given to the leader who publishes the transaction in a block they create. Naturally, this choice means that regular users have no incentives to report double-signing instances, apart from altruistic behavior. Nonetheless, leaders, who are a non-negligible set of participants, have such incentives and are expected to do such reporting work. Additionally, this design has the benefit of being easily implementable and of increasing the leaders’ potential revenue.

**Comment by rlan35** [comment]
This is a valid point. Since most of the actively participating nodes in the network are validators and we don't expect or design to have specialized nodes (such as fisherman nodes) to participate in the network, giving the rewards to leaders makes sense. Note it's not only the leader who are incentivized to monitor the network for slashing evidence, it's all the validators who will take turns to become the leader and gain the slashing reward if they have the slashing evidence.
