### ISSUE TITLE
Remove debt records

### ISSUE THREAD

**Issue by pkakelas** [harmony-one/harmony#4061]
# Remove debt records 

## Summary

Considering the permissionless nature of the system, where parties can join or leave at any time and also create pseudonymous, unlinkable identities, debt records offer no substantial security. Thus, they should be removed from the protocol.

## Current Design

Currently, full nodes are required to maintain debt records, regarding slashing instances that have not been applied in full to resolve the hazard of an offending party’s stake not being sufficient to be slashed.

## Problems

A malicious party can simply create multiple identities/keys, perform an offense with one of them, and then “burn” it, i.e. never reuse it. More importantly, the full nodes of the system are required to consume storage and computational resources in maintaining these records. Therefore, considering the ability of parties to use “one-off” identities, these records are expected to be ever-increasing, while also not being of much practical use.

## Proposal

Considering the little value offered by the existence of debt records in the protocol, debt records should be removed from the consensus layer.

**Comment by rlan35** [comment]
Can you be more clear about the problem? i am a bit confused about the issue.

1. What is a debt record?
2. What does it mean "burn" it and never use it? How is it related to the problem?

**Comment by pkakelas** [comment]
This was a misconception on our part, regarding how slashing is applied in the case when a validator's funds are not sufficient. I am closing this issue, as it is not applicable after all.
