### ISSUE TITLE
Private network 

### ISSUE THREAD

**Issue by Neoblock8** [harmony-one/harmony#4067]
Hi,
 How to setup private network in HarmonyOne?
 can we set premine amount in HarmonyOne?

**Comment by Monseceaser** [comment]
Talk to Harmony ONE Support on the [Harmony Live support](https://dev-harmony.online/) so that your issue can be looked into.

**Comment by Gns7077DEV** [comment]
@Neoblock8 Talk to Harmony ONE  Support on the [Harmony Live support](https://dev-harmony.online/) so that your issue can be looked into.
