### ISSUE TITLE
High memory usage at explorer node

### ISSUE THREAD

**Issue by JackyWYX** [harmony-one/harmony#4087]
**Describe the bug**

Explorer nodes were easy to fall out of sync in the last week. Here are the observations from node
:

1. The node is currently lagging behind 102622 blocks;
2. The block process time is 8+s / block
3. CPU is around 20% and is quite normal
4. From pprof data, there is no evidence there are too many incoming RPC requests.
5. Memory usage is quite high. It's 13.5GB / 15.2G
6. From pprof memory data, most of the data comes from rlp decoding in ExplorerMessageHandler.

Following is the full heap usage:

![heap](https://user-images.githubusercontent.com/40162696/157203109-19d3e582-f607-48aa-80e3-7d911f40d3ae.png)

Thus propose a PR to reduce the usage of block decoding.

**Comment by ONECasey** [comment]
Fixed.
