### ISSUE TITLE
Leader node get a dirty block in db during view change

### ISSUE THREAD

**Issue by JackyWYX** [harmony-one/harmony#4089]
**Describe the bug**

Validator node stuck during leader change. (3/7)

* The node was stuck and cannot sync with other peers.
* Restart did not resolve the issue.
* It was previously a leader node and unselected in a view change process. But it has already inserted its own block into its db so it is stuck at height 23798442.
* Resolve the issue by reverting 2 blocks.

Need to take a deeper look at the log and see how the issue is triggered in the first place.

Detailed node information please take a look at [this doc](https://docs.google.com/document/d/1_di1TwZ3hPLm7UgPdjEbgdAjuO3XunNELQHRAQ9jW6o/edit#), indexed 1.

**Comment by MaxMustermann2** [comment]
The node in question has been terminated so it is not possible to investigate this anymore. However, there have been a small number of fixes which have helped fix the problem as it has appeared on other nodes. See #4356 for example.
