### ISSUE TITLE
reduce the gas limit to 20m per block

### ISSUE THREAD

**Issue by LeoHChen** [harmony-one/harmony#4114]
I've collected a few data points from EVM compatible chains.

* Ethereum gas limit is 30m
https://etherscan.io/block/14502189

* Avalanche gas limit is 8m
https://snowtrace.io/block/12868013

* BSC gas limit is 80m
https://bscscan.com/block/16574207

* Harmony gas limit is 80m
https://explorer.harmony.one/block/0x98fcb3bf96307d46ddaf130f6807ff46273239d0991201b1ee6f55b65493c699

BSC is high centralized which is not comparable. High gas limit in Harmony resulted in higher block time, bigger blocks, and longer sync time, longer indexing time as well.  Most of the time the gas limit was only used 10-20%.

So I think we should reduce the gas limit to 20m per block to reduce the block latency and syncing time as well.

**Comment by LeoHChen** [comment]
<img width="572" alt="image" src="https://user-images.githubusercontent.com/4513927/161371607-1e10eaf6-b989-4894-b10b-bdf7ca50a446.png">

huge and full blocks drastically increased the block time

**Comment by LeoHChen** [comment]
<img width="593" alt="image" src="https://user-images.githubusercontent.com/4513927/161371843-7dde672f-6daf-4461-9a63-233304170ab7.png">

**Comment by moutikabdessabour** [comment]
Hello, so now the gas limit is 20m. I get error from ethers complaining about the gas price being too big
