### ISSUE TITLE
mainnet - slow beacon chain sync

### ISSUE THREAD

**Issue by sophoah** [harmony-one/harmony#4121]
**Describe the bug**
Multiple diverse node can't sync the shard 0 db properly. It often happens with an attached volume (DO can't make it at all for instance) but happens also on AWS node with attached EBS. it seems that increasing the instance type help even though the ressource are healthy (ie less than 25% cpu/memory usage)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**

**Additional context**

**Comment by MaxMustermann2** [comment]
Related: https://github.com/ledgerwatch/erigon and #4070
