### ISSUE TITLE
Transaction fee

### ISSUE THREAD

**Issue by BattambangReaper** [harmony-one/harmony#4125]
I tried staking the other day and it charged me 705 One for the transaction that failed and nothing was staked. So I'm out 705 One. 

Hash 0x8a2bc9a086076309147f9c8c1c440145f35c27b70991f6239742b46c2e3e38d6

**Comment by LeoHChen** [comment]
we have a PR which is already merged, https://github.com/harmony-one/harmony/commit/c9ec957b4f74fb41bfe32f219ab56ff141df2215

doing testing in eng build, waiting for final release/deployment.

**Comment by BattambangReaper** [comment]
I'm completely out of my element here. What does this mean and thank you for your time.

**Comment by BattambangReaper** [comment]
> we have a PR which is already merged, https://github.com/harmony-one/harmony/commit/c9ec957b4f74fb41bfe32f219ab56ff141df2215
> 
> 
> 
> doing testing in eng build, waiting for final release/deployment.

I'm completely out of my element here. What does this mean and thank you for your time.

**Comment by sophoah** [comment]
> > we have a PR which is already merged, [c9ec957](https://github.com/harmony-one/harmony/commit/c9ec957b4f74fb41bfe32f219ab56ff141df2215)
> > doing testing in eng build, waiting for final release/deployment.
> 
> I'm completely out of my element here. What does this mean and thank you for your time.

it means it's currently under test and the change will be effective once it has been deployed to RPC nodes
