### ISSUE TITLE
Docker image file; still have to install and configure every thing??

### ISSUE THREAD

**Issue by ONEex-protocol** [harmony-one/harmony#4127]
**Describe the bug**
Docker Image is meant to be platform agnostic, greatly minimize spin up time and effort on building the same thing 1000 times; the "core" harmony docker image seems useless. Pulled the image, ran docker to create a container, and received an entire screen filled with errors. Even errors for files not found. Files that other part of the core github repo state I should create if I want to build from source or build from something else (not sure really. Reading harmony documentation is like an hour of being violently spun in a circle). 

**To Reproduce**
1. Install Microsoft Windows [Version 10.0.19044.1586], Docker Desktop latest, ubuntu 18.04 WSL 2; VS code
2. Node.js, Make/CMake, 2017 Build tools (VS C++), GO, gcc/g++, git, GCM
3. docker pull harmonyone/harmony 
4. docker run harmonyone/harmony

**Expected behavior**
I expect that when a container is spun up from a docker image on a fully configured development workstation for that container to actually run and not immediately exit with nearly two dozen errors. I expect to NOT have to install multiple softwares/libs/etc and to NOT have to spend an hour or more doing so. I expect a docker file to do what docker files are meant to do.
There are a couple errors that or on me but the vast major is not (not surprising that yet another repo/file/image is total waste of time) 

**Screenshots**
sysctl: error setting key 'net.core.somaxconn': Read-only file system
sysctl: error: 'net.core.netdev_max_backlog' is an unknown key
sysctl: error setting key 'net.ipv4.tcp_tw_reuse': Read-only file system
sysctl: error setting key 'net.ipv4.tcp_rmem': Read-only file system
sysctl: error setting key 'net.ipv4.tcp_wmem': Read-only file system
sysctl: error: 'net.ipv4.tcp_mem' is an unknown key
grep: /etc/security/limits.conf: No such file or directory
/bin/run: line 56: /etc/security/limits.conf: No such file or directory
grep: /etc/security/limits.conf: No such file or directory
/bin/run: line 56: /etc/security/limits.conf: No such file or directory
grep: /etc/security/limits.conf: No such file or directory
/bin/run: line 56: /etc/security/limits.conf: No such file or directory
grep: /etc/security/limits.conf: No such file or directory
/bin/run: line 56: /etc/security/limits.conf: No such file or directory
grep: /etc/security/limits.conf: No such file or directory
/bin/run: line 56: /etc/security/limits.conf: No such file or directory
grep: /etc/security/limits.conf: No such file or directory
/bin/run: line 56: total 8
drwxr-xr-x    2 root     root          4096 Apr 13 12:28 .
drwxr-xr-x    1 root     root          4096 Apr 13 12:28 ..
/etc/security/limits.conf: No such file or directory
grep: /etc/security/limits.conf: No such file or directory
/bin/run: line 56: /etc/security/limits.conf: No such file or directory
grep: /etc/security/limits.conf: No such file or directory
/bin/run: line 56: /etc/security/limits.conf: No such file or directory
grep: /etc/pam.d/common-session: No such file or directory
/bin/run: line 56: /etc/pam.d/common-session: No such file or directory
run: harmony -log_folder /harmony/log -node_type validator -network_type mainnet -bootnodes /ip4/100.26.90.187/tcp/9874/p2p/Qmdfjtk6hPoyrH1zVD9PEH4zfWLo38dP2mDvvKXfh3tnEv,/ip4/54.213.43.194/tcp/9874/p2p/QmZJJx6AdaoEkGLrYG4JeLCKeCKDjnFz2wfHNHxAqFSGA9,/ip4/13.113.101.219/tcp/12019/p2p/QmQayinFSgMMw5cSpDUiD9pQ2WeP6WNmGxpZ6ou3mdVFJX,/ip4/99.81.170.167/tcp/12019/p2p/QmRVbTpEYup8dSaURZfF6ByrMTSKa4UyUzJhSjahFzRqNj -ip 20.83.119.244 -port 9000 -dns_zone t.hmny.io -blspass file:/harmony/.hmy/ -blskey_file /harmony/.hmy/ -public_rpc 
/bin/run: line 118: /bin/harmony: Permission denied

**Environment (please complete the following information):**
 - OS: [Linux, MacOS]. Install Microsoft Windows [Version 10.0.19044.1586], Docker Desktop latest, ubuntu 18.04 WSL 2; VS code
 - GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/name/.cache/go-build"
GOENV="/home/name/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/name/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/name/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.18.1"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build1275063926=/tmp/go-build -gno-record-gcc-switches"

**Additional context**
Nothing more to add

**Comment by LeoHChen** [comment]
seems our docker image is not updated.

**Comment by LeoHChen** [comment]
@jhd2best please help out.
