### ISSUE TITLE
v4.3.8 Breaking staking RPC method changes

### ISSUE THREAD

**Issue by sophoah** [harmony-one/harmony#4130]
PR #4106  and PR #4111 contains some backward compatibility changes on staking related RPCs

#4106  - Add epoch, block number to hmyv2_getValidatorInformation response -
Methods `hmy_getAllDelegationInformation` and `hmy_getAllValidatorInformation` will no longer be able to display all data in one page. Going forward pagination must be used.

#4111 - Make rpc/v1 `StakingTxReceipt` `type` field ethereum compatible and implement hmyv2_getBlockReceipts -
StakingTxReceipt `type` field has been updated to use hexa and may affect the capability to identify the type of staking transaction

**Comment by vilkinus** [comment]
Is there a way to have a deprecation period?

**Comment by potvik** [comment]
https://github.com/harmony-one/harmony/pull/4106
"hmy_getAllDelegationInformation" - already use pagination https://github.com/harmony-one/staking-dashboard/blob/master/appengine/src/services/sync/validators-info.ts#L295

"hmy_getAllValidatorInformation" - also using pagination https://github.com/harmony-one/staking-dashboard/blob/master/appengine/src/services/sync/validators-info.ts#L94

https://github.com/harmony-one/harmony/pull/4111
method "hmyv2_getBlockReceipts" - not using in staking dashboard appengine service
