### ISSUE TITLE
debug_traceBlockByHash method handler crash

### ISSUE THREAD

**Issue by jhony112** [harmony-one/harmony#4158]
**Describe the bug**
Sending request to RPC tracing a block by hash e.g on URL `https://a.api.s0.t.hmny.io`

```
{
    "jsonrpc": "2.0",
    "id": 1,
    "method": "debug_traceBlockByHash",
    "params": [
        "0x59d497bea514a9332c3581a97fa4dccd0acd7893a57ff3ed83dd4e180b52dbdc"
    ]
}
```

Result is shown below 

```
{
    "jsonrpc": "2.0",
    "id": 1,
    "error": {
        "code": -32000,
        "message": "method handler crashed"
    }
}
```

**Expected behavior**
Show block information

**Comment by NickKelly1** [comment]
This happens for me too on my private archive node.

Also happened with `debug_traceblockByNumber`.

**Comment by LeoHChen** [comment]
@peekpi please take a look

**Comment by peekpi** [comment]
this bug is most likely caused by not checking for nil pointer,  but still needs to be tested.
