### ISSUE TITLE
RPC call only run inside a docker container

### ISSUE THREAD

**Issue by MatheusMorozetti** [harmony-one/harmony#4175]
**Describe the bug**
I tryed use rpc call but I got a error: connection refused by peer, but inside my container I can do rpc call, I'm not a validator just a explorer

**To Reproduce**
1. I build a image with harmony binary
2.  Run with docker-compose with flags [   '--run=explorer' '--run.archive' '--run.shard=0'  '--db_dir=/data'' ]
3. RPC call: 
curl -X POST -H "Content-Type: application/json" --data '{"jsonrpc":"2.0","method":"eth_blockNumber","params":[],"id":1}' http://localhost:9500

**Expected behavior**
{"jsonrpc":"2.0","id":1,"result":"0x3fc"}

**Environment (please complete the following information):**
 - OS: [Linux, Ubuntu minimal focal ]
 
**Additional context**
My harmony.conf

Version = "2.1.0"

[BLSKeys]
  KMSConfigFile = ""
  KMSConfigSrcType = "shared"
  KMSEnabled = false
  KeyDir = "./.hmy/blskeys"
  KeyFiles = []
  MaxKeys = 10
  PassEnabled = true
  PassFile = ""
  PassSrcType = "auto"
  SavePassphrase = false

[DNSSync]
  Client = true
  LegacySyncing = false
  Port = 6000
  Server = true
  ServerPort = 6000
  Zone = "t.hmny.io"

[General]
  DataDir = "/data"
  IsArchival = false
  IsBeaconArchival = false
  IsOffline = false
  NoStaking = false
#  NodeType = "explorer"
#  ShardID = -1

[HTTP]
  Enabled = true
  IP = "0.0.0.0"
  Port = 9500
  RosettaEnabled = false
  RosettaPort = 9700

[Log]
  FileName = "harmony.log"
  Folder = "./latest"
  RotateSize = 100
  Verbosity = 3

  [Log.VerbosePrints]
    Config = false

[Network]
  BootNodes = ["/dnsaddr/bootstrap.t.hmny.io"]
  NetworkType = "mainnet"

[P2P]
  IP = "0.0.0.0"
  KeyFile = "./.hmykey"
  Port = 9000

[Pprof]
  Enabled = false
  ListenAddr = "127.0.0.1:6060"

[RPCOpt]
  DebugEnabled = false
  RateLimterEnabled = true
  RequestsPerSecond = 1000

[Sync]
  Concurrency = 6
  DiscBatch = 8
  DiscHardLowCap = 6
  DiscHighCap = 128
  DiscSoftLowCap = 8
  Downloader = false
  Enabled = false
  InitStreams = 8
  MinPeers = 6

[TxPool]
  BlacklistFile = "./.hmy/blacklist.txt"

[WS]
  Enabled = true
  IP = "127.0.0.1"
  Port = 9800

**Comment by MaxMustermann2** [comment]
With the container running, can you please post the output of the two commands?
```bash
docker ps -a
netstat -tulpn | grep LISTEN
```

**Comment by MatheusMorozetti** [comment]
Sure here my output

**Comment by MatheusMorozetti** [comment]
Sure here is my output 

`docker ps -a

```
CONTAINER ID   IMAGE                     COMMAND                  CREATED        STATUS        PORTS                                                                                                                                                                        NAMES
870ab5a6fc3f   kleverio/harmony:v4.3.8   "/usr/local/bin/bina…"   21 hours ago   Up 21 hours   0.0.0.0:6000->6000/tcp, :::6000->6000/tcp, 0.0.0.0:9000->9000/tcp, :::9000->9000/tcp, 0.0.0.0:9500->9500/tcp, :::9500->9500/tcp, 0.0.0.0:9800->9800/tcp, :::9800->9800/tcp   harmony-backend>6000/tcp, 0.0.0.0:9000->9000/tcp, :::9000->9000/tcp, 0.0.0.0:9500->9500/tcp, :::9500->9500/tcp, 0.0.0.0:9800->9800/tcp, :::9800->9800/tcp   harmony-backend
```
`

```
`netstat -tulpn | grep LISTEN
tcp        0      0 0.0.0.0:6000            0.0.0.0:*               LISTEN      47173/docker-proxy  
tcp        0      0 127.0.0.53:53           0.0.0.0:*               LISTEN      596/systemd-resolve 
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      637/sshd: /usr/sbin 
tcp        0      0 0.0.0.0:9500            0.0.0.0:*               LISTEN      47132/docker-proxy  
tcp        0      0 0.0.0.0:9000            0.0.0.0:*               LISTEN      47151/docker-proxy  
tcp        0      0 0.0.0.0:9800            0.0.0.0:*               LISTEN      47112/docker-proxy  
tcp6       0      0 :::6000                 :::*                    LISTEN      47179/docker-proxy  
tcp6       0      0 :::22                   :::*                    LISTEN      637/sshd: /usr/sbin 
tcp6       0      0 :::9500                 :::*                    LISTEN      47139/docker-proxy  
tcp6       0      0 :::9000                 :::*                    LISTEN      47157/docker-proxy  
tcp6       0      0 :::9800                 :::*                    LISTEN      47118/docker-proxy  
```

`
