### ISSUE TITLE
Ethereum compatible metrics always return zero 

### ISSUE THREAD

**Issue by SozinM** [harmony-one/harmony#4186]
**Describe the bug**
Metrics at localhost:9900/metrics/eth endpoint always return zero

**To Reproduce**
1. Run and sync node v4.3.9 (Or previous version) 
2. Curl http://localhost:9900/metrics/eth
3. Check that all values for metrics are zero

**Expected behavior**
I expect metrics to return actual values 

**Example of metrics from my node**
```
curl http://localhost:9900/metrics/eth
# TYPE chain_account_commits_count counter
chain_account_commits_count 0

# TYPE chain_account_commits summary
chain_account_commits {quantile="0.5"} 0

# TYPE chain_account_commits summary
chain_account_commits {quantile="0.75"} 0

# TYPE chain_account_commits summary
chain_account_commits {quantile="0.95"} 0

# TYPE chain_account_commits summary
chain_account_commits {quantile="0.99"} 0

# TYPE chain_account_commits summary
chain_account_commits {quantile="0.999"} 0

# TYPE chain_account_commits summary
chain_account_commits {quantile="0.9999"} 0

# TYPE chain_account_hashes_count counter
chain_account_hashes_count 0

# TYPE chain_account_hashes summary
chain_account_hashes {quantile="0.5"} 0

# TYPE chain_account_hashes summary
chain_account_hashes {quantile="0.75"} 0

# TYPE chain_account_hashes summary
chain_account_hashes {quantile="0.95"} 0

# TYPE chain_account_hashes summary
chain_account_hashes {quantile="0.99"} 0

# TYPE chain_account_hashes summary
chain_account_hashes {quantile="0.999"} 0

# TYPE chain_account_hashes summary
chain_account_hashes {quantile="0.9999"} 0

# TYPE chain_account_reads_count counter
chain_account_reads_count 0

# TYPE chain_account_reads summary
chain_account_reads {quantile="0.5"} 0

# TYPE chain_account_reads summary
chain_account_reads {quantile="0.75"} 0

# TYPE chain_account_reads summary
chain_account_reads {quantile="0.95"} 0

# TYPE chain_account_reads summary
chain_account_reads {quantile="0.99"} 0

# TYPE chain_account_reads summary
chain_account_reads {quantile="0.999"} 0

# TYPE chain_account_reads summary
chain_account_reads {quantile="0.9999"} 0

# TYPE chain_account_updates_count counter
chain_account_updates_count 0

# TYPE chain_account_updates summary
chain_account_updates {quantile="0.5"} 0

# TYPE chain_account_updates summary
chain_account_updates {quantile="0.75"} 0

# TYPE chain_account_updates summary
chain_account_updates {quantile="0.95"} 0

# TYPE chain_account_updates summary
chain_account_updates {quantile="0.99"} 0

# TYPE chain_account_updates summary
chain_account_updates {quantile="0.999"} 0

# TYPE chain_account_updates summary
chain_account_updates {quantile="0.9999"} 0

# TYPE chain_execution_count counter
chain_execution_count 0

# TYPE chain_execution summary
chain_execution {quantile="0.5"} 0

# TYPE chain_execution summary
chain_execution {quantile="0.75"} 0

# TYPE chain_execution summary
chain_execution {quantile="0.95"} 0

# TYPE chain_execution summary
chain_execution {quantile="0.99"} 0

# TYPE chain_execution summary
chain_execution {quantile="0.999"} 0

# TYPE chain_execution summary
chain_execution {quantile="0.9999"} 0

# TYPE chain_head_block gauge
chain_head_block 0

# TYPE chain_head_header gauge
chain_head_header 0

# TYPE chain_head_receipt gauge
chain_head_receipt 0

# TYPE chain_inserts_count counter
chain_inserts_count 0

# TYPE chain_inserts summary
chain_inserts {quantile="0.5"} 0

# TYPE chain_inserts summary
chain_inserts {quantile="0.75"} 0

# TYPE chain_inserts summary
chain_inserts {quantile="0.95"} 0

# TYPE chain_inserts summary
chain_inserts {quantile="0.99"} 0

# TYPE chain_inserts summary
chain_inserts {quantile="0.999"} 0

# TYPE chain_inserts summary
chain_inserts {quantile="0.9999"} 0

# TYPE chain_storage_commits_count counter
chain_storage_commits_count 0

# TYPE chain_storage_commits summary
chain_storage_commits {quantile="0.5"} 0

# TYPE chain_storage_commits summary
chain_storage_commits {quantile="0.75"} 0

# TYPE chain_storage_commits summary
chain_storage_commits {quantile="0.95"} 0

# TYPE chain_storage_commits summary
chain_storage_commits {quantile="0.99"} 0

# TYPE chain_storage_commits summary
chain_storage_commits {quantile="0.999"} 0

# TYPE chain_storage_commits summary
chain_storage_commits {quantile="0.9999"} 0

# TYPE chain_storage_hashes_count counter
chain_storage_hashes_count 0

# TYPE chain_storage_hashes summary
chain_storage_hashes {quantile="0.5"} 0

# TYPE chain_storage_hashes summary
chain_storage_hashes {quantile="0.75"} 0

# TYPE chain_storage_hashes summary
chain_storage_hashes {quantile="0.95"} 0

# TYPE chain_storage_hashes summary
chain_storage_hashes {quantile="0.99"} 0

# TYPE chain_storage_hashes summary
chain_storage_hashes {quantile="0.999"} 0

# TYPE chain_storage_hashes summary
chain_storage_hashes {quantile="0.9999"} 0

# TYPE chain_storage_reads_count counter
chain_storage_reads_count 0

# TYPE chain_storage_reads summary
chain_storage_reads {quantile="0.5"} 0

# TYPE chain_storage_reads summary
chain_storage_reads {quantile="0.75"} 0

# TYPE chain_storage_reads summary
chain_storage_reads {quantile="0.95"} 0

# TYPE chain_storage_reads summary
chain_storage_reads {quantile="0.99"} 0

# TYPE chain_storage_reads summary
chain_storage_reads {quantile="0.999"} 0

# TYPE chain_storage_reads summary
chain_storage_reads {quantile="0.9999"} 0

# TYPE chain_storage_updates_count counter
chain_storage_updates_count 0

# TYPE chain_storage_updates summary
chain_storage_updates {quantile="0.5"} 0

# TYPE chain_storage_updates summary
chain_storage_updates {quantile="0.75"} 0

# TYPE chain_storage_updates summary
chain_storage_updates {quantile="0.95"} 0

# TYPE chain_storage_updates summary
chain_storage_updates {quantile="0.99"} 0

# TYPE chain_storage_updates summary
chain_storage_updates {quantile="0.999"} 0

# TYPE chain_storage_updates summary
chain_storage_updates {quantile="0.9999"} 0

# TYPE chain_validation_count counter
chain_validation_count 0

# TYPE chain_validation summary
chain_validation {quantile="0.5"} 0

# TYPE chain_validation summary
chain_validation {quantile="0.75"} 0

# TYPE chain_validation summary
chain_validation {quantile="0.95"} 0

# TYPE chain_validation summary
chain_validation {quantile="0.99"} 0

# TYPE chain_validation summary
chain_validation {quantile="0.999"} 0

# TYPE chain_validation summary
chain_validation {quantile="0.9999"} 0

# TYPE chain_write_count counter
chain_write_count 0

# TYPE chain_write summary
chain_write {quantile="0.5"} 0

# TYPE chain_write summary
chain_write {quantile="0.75"} 0

# TYPE chain_write summary
chain_write {quantile="0.95"} 0

# TYPE chain_write summary
chain_write {quantile="0.99"} 0

# TYPE chain_write summary
chain_write {quantile="0.999"} 0

# TYPE chain_write summary
chain_write {quantile="0.9999"} 0

# TYPE compact_input gauge
compact_input 0

# TYPE compact_level0 gauge
compact_level0 0

# TYPE compact_memory gauge
compact_memory 0

# TYPE compact_nonlevel0 gauge
compact_nonlevel0 0

# TYPE compact_output gauge
compact_output 0

# TYPE compact_seek gauge
compact_seek 0

# TYPE compact_time gauge
compact_time 0

# TYPE compact_writedelay_counter gauge
compact_writedelay_counter 0

# TYPE compact_writedelay_duration gauge
compact_writedelay_duration 0

# TYPE db_preimage_hits gauge
db_preimage_hits 0

# TYPE db_preimage_total gauge
db_preimage_total 0

# TYPE disk_read gauge
disk_read 0

# TYPE disk_size gauge
disk_size 0

# TYPE disk_write gauge
disk_write 0

# TYPE p2p_egress gauge
p2p_egress 0

# TYPE p2p_ingress gauge
p2p_ingress 0

# TYPE trie_bloom_add gauge
trie_bloom_add 0

# TYPE trie_bloom_error gauge
trie_bloom_error 0

# TYPE trie_bloom_fault gauge
trie_bloom_fault 0

# TYPE trie_bloom_load gauge
trie_bloom_load 0

# TYPE trie_bloom_miss gauge
trie_bloom_miss 0

# TYPE trie_bloom_test gauge
trie_bloom_test 0

# TYPE trie_memcache_clean_hit gauge
trie_memcache_clean_hit 0

# TYPE trie_memcache_clean_miss gauge
trie_memcache_clean_miss 0

# TYPE trie_memcache_clean_read gauge
trie_memcache_clean_read 0

# TYPE trie_memcache_clean_write gauge
trie_memcache_clean_write 0

# TYPE trie_memcache_commit_nodes gauge
trie_memcache_commit_nodes 0

# TYPE trie_memcache_commit_size gauge
trie_memcache_commit_size 0

# TYPE trie_memcache_dirty_hit gauge
trie_memcache_dirty_hit 0

# TYPE trie_memcache_dirty_miss gauge
trie_memcache_dirty_miss 0

# TYPE trie_memcache_dirty_read gauge
trie_memcache_dirty_read 0

# TYPE trie_memcache_dirty_write gauge
trie_memcache_dirty_write 0

# TYPE trie_memcache_flush_nodes gauge
trie_memcache_flush_nodes 0

# TYPE trie_memcache_flush_size gauge
trie_memcache_flush_size 0

# TYPE trie_memcache_gc_nodes gauge
trie_memcache_gc_nodes 0

# TYPE trie_memcache_gc_size gauge
trie_memcache_gc_size 0

# TYPE txpool_invalid gauge
txpool_invalid 0

# TYPE txpool_pending_discard gauge
txpool_pending_discard 0

# TYPE txpool_pending_nofunds gauge
txpool_pending_nofunds 0

# TYPE txpool_pending_ratelimit gauge
txpool_pending_ratelimit 0

# TYPE txpool_pending_replace gauge
txpool_pending_replace 0

# TYPE txpool_queued_discard gauge
txpool_queued_discard 0

# TYPE txpool_queued_nofunds gauge
txpool_queued_nofunds 0

# TYPE txpool_queued_ratelimit gauge
txpool_queued_ratelimit 0

# TYPE txpool_queued_replace gauge
txpool_queued_replace 0

# TYPE txpool_underpriced gauge
txpool_underpriced 0
```
**Environment (please complete the following information):**
- OS: Linux
- Run using kubernetes from this docker image: https://hub.docker.com/r/chainstack/harmony-node

**Additional context**
The issue most likely linked to the PR https://github.com/harmony-one/harmony/pull/4042

**Comment by ndevmetax** [comment]
> **Describe the bug** Metrics at localhost:9900/metrics/eth endpoint always return zero
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Run and sync node v4.3.9 (Or previous version)
> 2. Curl http://localhost:9900/metrics/eth
> 3. Check that all values for metrics are zero
> 
> **Expected behavior** I expect metrics to return actual values
> 
> **Example of metrics from my node**
> 
> ```
> curl http://localhost:9900/metrics/eth
> # TYPE chain_account_commits_count counter
> chain_account_commits_count 0
> 
> # TYPE chain_account_commits summary
> chain_account_commits {quantile="0.5"} 0
> 
> # TYPE chain_account_commits summary
> chain_account_commits {quantile="0.75"} 0
> 
> # TYPE chain_account_commits summary
> chain_account_commits {quantile="0.95"} 0
> 
> # TYPE chain_account_commits summary
> chain_account_commits {quantile="0.99"} 0
> 
> # TYPE chain_account_commits summary
> chain_account_commits {quantile="0.999"} 0
> 
> # TYPE chain_account_commits summary
> chain_account_commits {quantile="0.9999"} 0
> 
> # TYPE chain_account_hashes_count counter
> chain_account_hashes_count 0
> 
> # TYPE chain_account_hashes summary
> chain_account_hashes {quantile="0.5"} 0
> 
> # TYPE chain_account_hashes summary
> chain_account_hashes {quantile="0.75"} 0
> 
> # TYPE chain_account_hashes summary
> chain_account_hashes {quantile="0.95"} 0
> 
> # TYPE chain_account_hashes summary
> chain_account_hashes {quantile="0.99"} 0
> 
> # TYPE chain_account_hashes summary
> chain_account_hashes {quantile="0.999"} 0
> 
> # TYPE chain_account_hashes summary
> chain_account_hashes {quantile="0.9999"} 0
> 
> # TYPE chain_account_reads_count counter
> chain_account_reads_count 0
> 
> # TYPE chain_account_reads summary
> chain_account_reads {quantile="0.5"} 0
> 
> # TYPE chain_account_reads summary
> chain_account_reads {quantile="0.75"} 0
> 
> # TYPE chain_account_reads summary
> chain_account_reads {quantile="0.95"} 0
> 
> # TYPE chain_account_reads summary
> chain_account_reads {quantile="0.99"} 0
> 
> # TYPE chain_account_reads summary
> chain_account_reads {quantile="0.999"} 0
> 
> # TYPE chain_account_reads summary
> chain_account_reads {quantile="0.9999"} 0
> 
> # TYPE chain_account_updates_count counter
> chain_account_updates_count 0
> 
> # TYPE chain_account_updates summary
> chain_account_updates {quantile="0.5"} 0
> 
> # TYPE chain_account_updates summary
> chain_account_updates {quantile="0.75"} 0
> 
> # TYPE chain_account_updates summary
> chain_account_updates {quantile="0.95"} 0
> 
> # TYPE chain_account_updates summary
> chain_account_updates {quantile="0.99"} 0
> 
> # TYPE chain_account_updates summary
> chain_account_updates {quantile="0.999"} 0
> 
> # TYPE chain_account_updates summary
> chain_account_updates {quantile="0.9999"} 0
> 
> # TYPE chain_execution_count counter
> chain_execution_count 0
> 
> # TYPE chain_execution summary
> chain_execution {quantile="0.5"} 0
> 
> # TYPE chain_execution summary
> chain_execution {quantile="0.75"} 0
> 
> # TYPE chain_execution summary
> chain_execution {quantile="0.95"} 0
> 
> # TYPE chain_execution summary
> chain_execution {quantile="0.99"} 0
> 
> # TYPE chain_execution summary
> chain_execution {quantile="0.999"} 0
> 
> # TYPE chain_execution summary
> chain_execution {quantile="0.9999"} 0
> 
> # TYPE chain_head_block gauge
> chain_head_block 0
> 
> # TYPE chain_head_header gauge
> chain_head_header 0
> 
> # TYPE chain_head_receipt gauge
> chain_head_receipt 0
> 
> # TYPE chain_inserts_count counter
> chain_inserts_count 0
> 
> # TYPE chain_inserts summary
> chain_inserts {quantile="0.5"} 0
> 
> # TYPE chain_inserts summary
> chain_inserts {quantile="0.75"} 0
> 
> # TYPE chain_inserts summary
> chain_inserts {quantile="0.95"} 0
> 
> # TYPE chain_inserts summary
> chain_inserts {quantile="0.99"} 0
> 
> # TYPE chain_inserts summary
> chain_inserts {quantile="0.999"} 0
> 
> # TYPE chain_inserts summary
> chain_inserts {quantile="0.9999"} 0
> 
> # TYPE chain_storage_commits_count counter
> chain_storage_commits_count 0
> 
> # TYPE chain_storage_commits summary
> chain_storage_commits {quantile="0.5"} 0
> 
> # TYPE chain_storage_commits summary
> chain_storage_commits {quantile="0.75"} 0
> 
> # TYPE chain_storage_commits summary
> chain_storage_commits {quantile="0.95"} 0
> 
> # TYPE chain_storage_commits summary
> chain_storage_commits {quantile="0.99"} 0
> 
> # TYPE chain_storage_commits summary
> chain_storage_commits {quantile="0.999"} 0
> 
> # TYPE chain_storage_commits summary
> chain_storage_commits {quantile="0.9999"} 0
> 
> # TYPE chain_storage_hashes_count counter
> chain_storage_hashes_count 0
> 
> # TYPE chain_storage_hashes summary
> chain_storage_hashes {quantile="0.5"} 0
> 
> # TYPE chain_storage_hashes summary
> chain_storage_hashes {quantile="0.75"} 0
> 
> # TYPE chain_storage_hashes summary
> chain_storage_hashes {quantile="0.95"} 0
> 
> # TYPE chain_storage_hashes summary
> chain_storage_hashes {quantile="0.99"} 0
> 
> # TYPE chain_storage_hashes summary
> chain_storage_hashes {quantile="0.999"} 0
> 
> # TYPE chain_storage_hashes summary
> chain_storage_hashes {quantile="0.9999"} 0
> 
> # TYPE chain_storage_reads_count counter
> chain_storage_reads_count 0
> 
> # TYPE chain_storage_reads summary
> chain_storage_reads {quantile="0.5"} 0
> 
> # TYPE chain_storage_reads summary
> chain_storage_reads {quantile="0.75"} 0
> 
> # TYPE chain_storage_reads summary
> chain_storage_reads {quantile="0.95"} 0
> 
> # TYPE chain_storage_reads summary
> chain_storage_reads {quantile="0.99"} 0
> 
> # TYPE chain_storage_reads summary
> chain_storage_reads {quantile="0.999"} 0
> 
> # TYPE chain_storage_reads summary
> chain_storage_reads {quantile="0.9999"} 0
> 
> # TYPE chain_storage_updates_count counter
> chain_storage_updates_count 0
> 
> # TYPE chain_storage_updates summary
> chain_storage_updates {quantile="0.5"} 0
> 
> # TYPE chain_storage_updates summary
> chain_storage_updates {quantile="0.75"} 0
> 
> # TYPE chain_storage_updates summary
> chain_storage_updates {quantile="0.95"} 0
> 
> # TYPE chain_storage_updates summary
> chain_storage_updates {quantile="0.99"} 0
> 
> # TYPE chain_storage_updates summary
> chain_storage_updates {quantile="0.999"} 0
> 
> # TYPE chain_storage_updates summary
> chain_storage_updates {quantile="0.9999"} 0
> 
> # TYPE chain_validation_count counter
> chain_validation_count 0
> 
> # TYPE chain_validation summary
> chain_validation {quantile="0.5"} 0
> 
> # TYPE chain_validation summary
> chain_validation {quantile="0.75"} 0
> 
> # TYPE chain_validation summary
> chain_validation {quantile="0.95"} 0
> 
> # TYPE chain_validation summary
> chain_validation {quantile="0.99"} 0
> 
> # TYPE chain_validation summary
> chain_validation {quantile="0.999"} 0
> 
> # TYPE chain_validation summary
> chain_validation {quantile="0.9999"} 0
> 
> # TYPE chain_write_count counter
> chain_write_count 0
> 
> # TYPE chain_write summary
> chain_write {quantile="0.5"} 0
> 
> # TYPE chain_write summary
> chain_write {quantile="0.75"} 0
> 
> # TYPE chain_write summary
> chain_write {quantile="0.95"} 0
> 
> # TYPE chain_write summary
> chain_write {quantile="0.99"} 0
> 
> # TYPE chain_write summary
> chain_write {quantile="0.999"} 0
> 
> # TYPE chain_write summary
> chain_write {quantile="0.9999"} 0
> 
> # TYPE compact_input gauge
> compact_input 0
> 
> # TYPE compact_level0 gauge
> compact_level0 0
> 
> # TYPE compact_memory gauge
> compact_memory 0
> 
> # TYPE compact_nonlevel0 gauge
> compact_nonlevel0 0
> 
> # TYPE compact_output gauge
> compact_output 0
> 
> # TYPE compact_seek gauge
> compact_seek 0
> 
> # TYPE compact_time gauge
> compact_time 0
> 
> # TYPE compact_writedelay_counter gauge
> compact_writedelay_counter 0
> 
> # TYPE compact_writedelay_duration gauge
> compact_writedelay_duration 0
> 
> # TYPE db_preimage_hits gauge
> db_preimage_hits 0
> 
> # TYPE db_preimage_total gauge
> db_preimage_total 0
> 
> # TYPE disk_read gauge
> disk_read 0
> 
> # TYPE disk_size gauge
> disk_size 0
> 
> # TYPE disk_write gauge
> disk_write 0
> 
> # TYPE p2p_egress gauge
> p2p_egress 0
> 
> # TYPE p2p_ingress gauge
> p2p_ingress 0
> 
> # TYPE trie_bloom_add gauge
> trie_bloom_add 0
> 
> # TYPE trie_bloom_error gauge
> trie_bloom_error 0
> 
> # TYPE trie_bloom_fault gauge
> trie_bloom_fault 0
> 
> # TYPE trie_bloom_load gauge
> trie_bloom_load 0
> 
> # TYPE trie_bloom_miss gauge
> trie_bloom_miss 0
> 
> # TYPE trie_bloom_test gauge
> trie_bloom_test 0
> 
> # TYPE trie_memcache_clean_hit gauge
> trie_memcache_clean_hit 0
> 
> # TYPE trie_memcache_clean_miss gauge
> trie_memcache_clean_miss 0
> 
> # TYPE trie_memcache_clean_read gauge
> trie_memcache_clean_read 0
> 
> # TYPE trie_memcache_clean_write gauge
> trie_memcache_clean_write 0
> 
> # TYPE trie_memcache_commit_nodes gauge
> trie_memcache_commit_nodes 0
> 
> # TYPE trie_memcache_commit_size gauge
> trie_memcache_commit_size 0
> 
> # TYPE trie_memcache_dirty_hit gauge
> trie_memcache_dirty_hit 0
> 
> # TYPE trie_memcache_dirty_miss gauge
> trie_memcache_dirty_miss 0
> 
> # TYPE trie_memcache_dirty_read gauge
> trie_memcache_dirty_read 0
> 
> # TYPE trie_memcache_dirty_write gauge
> trie_memcache_dirty_write 0
> 
> # TYPE trie_memcache_flush_nodes gauge
> trie_memcache_flush_nodes 0
> 
> # TYPE trie_memcache_flush_size gauge
> trie_memcache_flush_size 0
> 
> # TYPE trie_memcache_gc_nodes gauge
> trie_memcache_gc_nodes 0
> 
> # TYPE trie_memcache_gc_size gauge
> trie_memcache_gc_size 0
> 
> # TYPE txpool_invalid gauge
> txpool_invalid 0
> 
> # TYPE txpool_pending_discard gauge
> txpool_pending_discard 0
> 
> # TYPE txpool_pending_nofunds gauge
> txpool_pending_nofunds 0
> 
> # TYPE txpool_pending_ratelimit gauge
> txpool_pending_ratelimit 0
> 
> # TYPE txpool_pending_replace gauge
> txpool_pending_replace 0
> 
> # TYPE txpool_queued_discard gauge
> txpool_queued_discard 0
> 
> # TYPE txpool_queued_nofunds gauge
> txpool_queued_nofunds 0
> 
> # TYPE txpool_queued_ratelimit gauge
> txpool_queued_ratelimit 0
> 
> # TYPE txpool_queued_replace gauge
> txpool_queued_replace 0
> 
> # TYPE txpool_underpriced gauge
> txpool_underpriced 0
> ```
> 
> **Environment (please complete the following information):**
> 
> * OS: Linux
> * Run using kubernetes from this docker image: https://hub.docker.com/r/chainstack/harmony-node
> 
> **Additional context** The issue most likely linked to the PR #4042


I had similar issues days ago and i sorted it with customer support via live chat https://direct.lc.chat/14390013/
