### ISSUE TITLE
hmyv2_getTransactionReceipt's tx status

### ISSUE THREAD

**Issue by user00000001** [harmony-one/harmony#4195]
**hmyv2_getTransactionReceipt's tx status**
![image](https://user-images.githubusercontent.com/18508438/173022759-d879f6b1-e5b8-4c28-95ec-3a069fde05c7.png)
https://explorer.harmony.one/tx/0x5c5e56816ce0f51707aed31660aac51038a0500f9001c31a4f6bb34ae2f83342
https://explorer.harmony.one/tx/0x775fa5a4d14c91ace2d5afa814befb9457f95e1e309f6c443f186e20c69b01b9
### However, Harmony’s corresponding field seems to be used for other purposes, per its official API description?
```
curl -s --location --request POST 'https://a.api.s0.t.hmny.io/' --header 'Content-Type: application/json' --data-raw '{
    "jsonrpc": "2.0",
    "id": 1,
    "method": "hmyv2_getTransactionReceipt",
    "params": [
        "0x5c5e56816ce0f51707aed31660aac51038a0500f9001c31a4f6bb34ae2f83342"
    ]
}'|jq -r '.result.status'
## result is 0
```
```
curl -s --location --request POST 'https://a.api.s0.t.hmny.io/' --header 'Content-Type: application/json' --data-raw '{
    "jsonrpc": "2.0",
    "id": 1,
    "method": "hmyv2_getTransactionReceipt",
    "params": [
        "0x775fa5a4d14c91ace2d5afa814befb9457f95e1e309f6c443f186e20c69b01b9"
    ]
}'|jq -r '.result.status'
## result is 0
```
### If these two `pending` txns were failed txns, why explorer shows them by different status?

**Comment by LeoHChen** [comment]
@peekpi please take a look. is it our data issue or explorer display problem?

**Comment by peekpi** [comment]
> ### If these two `pending` txns were failed txns, why explorer shows them by different status?

The doc is wrong, this filed is the same as ethereum, the two txs failed.
It is a bug in earlier versions of the explorer, the code has been fixed, but the data may not be.

You can also use ethereun compatible RPCs, like eth_getTransactionReceipt.

**Comment by user00000001** [comment]
@LeoHChen @peekpi Thanks a lot.
