### ISSUE TITLE
[Feature] update dockerfile to support env variable 

### ISSUE THREAD

**Issue by jasonyic** [harmony-one/harmony#4211]
# Problem/limitation At Hand

`Dockerfile` under `scripts/docker` is outdated and does not support environment variable to overwrite the default value on configuration file or command line option. `env` variable is a more convenient way to run harmony node as docker, e,g, in kubernetes.

**Which component?**
- [ ] others: running harmony node as docker

# Proposed Solution

refactor `Dockerfile` to support environment variable to overwrite default `harmony.conf`. `Env` variable needs to be prefixed with `HARMONY_` and followed by `Group Name` and `Config Name`. e.g  to overwrite `NetworkType` under `Network` section in `harmony.conf`, the following environment variable should be used to overwrite default value `testnet`:
 ```
HARMONY_NETWORK_NETWORKTYPE=mainnet
```
`harmony.conf` initialised with default values for `testnet` and all configuration can be overwritten in environment variables. 

# Alternatives Considered
None

# Additional Context
None

**Comment by MaxMustermann2** [comment]
#4250
