### ISSUE TITLE
Harmony On-Chain VRF

### ISSUE THREAD

**Issue by Darlington02** [harmony-one/harmony#4242]
# Problem/limitation At Hand

Trying to implement Harmony's onchain VRF, for random numbers generation, but can't find suitable reference materials.

Other than the little code segment, in the docs, there seems to not exist any tutorial (video/blogs) to implement this.

# Proposed Solution

Would probably try writing a good blog guide on this once I'm done with my current project, but if anyone could point me to any other existing material i could reference, or code bases on github that has implemented this, I'd be grateful.

**Comment by Milydol** [comment]
> 

  I had similar issues and it was sorted out with 100%transparency using live chat https://direct.lc.chat/14345826/

**Comment by Darlington02** [comment]
Joined github 20 minutes ago, and you already had similar problems...lol

**Comment by MaxMustermann2** [comment]
See #3703 for a reference implementation. Note that it was updated later by #3850 with a block number parameter.

**Comment by Darlington02** [comment]
Thanks
