### ISSUE TITLE
sometimes eth_getTransactionReceipt response null

### ISSUE THREAD

**Issue by sylviahuang123** [harmony-one/harmony#4245]
why sometimes call eth_getTransactionReceipt response null? I use the ethhash, I can't get the tx receipt.

**Comment by MaxMustermann2** [comment]
Can you give an example of the hash that fails ?

**Comment by sylviahuang123** [comment]
endpoint: no matter postman or program
curl --location --request POST 'https://api.harmony.one/' \
--header 'Content-Type: application/json' \
--header 'Cookie: AWSALBTG=0JPdFq6ig82vugoRJ0Xo0aDtRx6vZxCuITbBa3fE7v1YwuH33nhYooYnr2/k78ql5LU2kVK7D/RNK4Y8c8nMtFdKYUpW6BYt02vUIztbfCB0JJoLfVn1oya4K66jbu9wC45yf6qsoUsqKvII4mZWK/MeFSZm+nTUJE+zBWnpdKPlaUHbGfk=; AWSALBTGCORS=0JPdFq6ig82vugoRJ0Xo0aDtRx6vZxCuITbBa3fE7v1YwuH33nhYooYnr2/k78ql5LU2kVK7D/RNK4Y8c8nMtFdKYUpW6BYt02vUIztbfCB0JJoLfVn1oya4K66jbu9wC45yf6qsoUsqKvII4mZWK/MeFSZm+nTUJE+zBWnpdKPlaUHbGfk=; DO-LB="MTAuMTA0LjAuNDo4NTAw"' \
--data-raw '{
	"jsonrpc":"2.0",
	"method":"eth_getTransactionReceipt",
	"params":[
		"0x58c51273c14895b7da597ee4421c2b14f59f01378d4a14f184e42e648f713797"
	],
	"id":1
}'

**Comment by MaxMustermann2** [comment]
You need to use archival endpoint `https://a.api.s0.t.hmny.io` instead of `https://api.harmony.one` which is _not_ archival.

**Comment by MaxMustermann2** [comment]
Correction: It works for me. Is that the transaction hash that fails? 
```bash
$ curl --location --request POST 'https://api.harmony.one/' \                                                                               ✔ 
--header 'Content-Type: application/json' \
--data-raw '{
"jsonrpc": "2.0",
"method": "eth_getTransactionReceipt",
"params": [
 "0x58c51273c14895b7da597ee4421c2b14f59f01378d4a14f184e42e648f713797"
],
"id": 1
}' | jq
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1134  100   981  100   153    407     63  0:00:02  0:00:02 --:--:--   471
{
  "jsonrpc": "2.0",
  "id": 1,
  "result": {
    "blockHash": "0xa20bf93b8e4a212dda8e75a2ea2abbfc35a7ae23e0d03d2c7fbc335ca96a04d2",
    "blockNumber": "0x4d8238",
    "contractAddress": null,
    "cumulativeGasUsed": "0x5208",
    "from": "0xd9fbc78e6d87c4681952696a1870ffc74f6abbc5",
    "gasUsed": "0x5208",
    "logs": [],
    "logsBloom": "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
    "status": "0x1",
    "to": "0x5546e923791640d88a131d7d488ebcf51f1d3cdc",
    "transactionHash": "0x58c51273c14895b7da597ee4421c2b14f59f01378d4a14f184e42e648f713797",
    "transactionIndex": "0x0"
  }
}
```

**Comment by sylviahuang123** [comment]
> Correction: It works for me. Is that the transaction hash that fails?
> 
> ```shell
> $ curl --location --request POST 'https://api.harmony.one/' \                                                                               ✔ 
> --header 'Content-Type: application/json' \
> --data-raw '{
> "jsonrpc": "2.0",
> "method": "eth_getTransactionReceipt",
> "params": [
>  "0x58c51273c14895b7da597ee4421c2b14f59f01378d4a14f184e42e648f713797"
> ],
> "id": 1
> }' | jq
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
> 100  1134  100   981  100   153    407     63  0:00:02  0:00:02 --:--:--   471
> {
>   "jsonrpc": "2.0",
>   "id": 1,
>   "result": {
>     "blockHash": "0xa20bf93b8e4a212dda8e75a2ea2abbfc35a7ae23e0d03d2c7fbc335ca96a04d2",
>     "blockNumber": "0x4d8238",
>     "contractAddress": null,
>     "cumulativeGasUsed": "0x5208",
>     "from": "0xd9fbc78e6d87c4681952696a1870ffc74f6abbc5",
>     "gasUsed": "0x5208",
>     "logs": [],
>     "logsBloom": "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
>     "status": "0x1",
>     "to": "0x5546e923791640d88a131d7d488ebcf51f1d3cdc",
>     "transactionHash": "0x58c51273c14895b7da597ee4421c2b14f59f01378d4a14f184e42e648f713797",
>     "transactionIndex": "0x0"
>   }
> }
> ```

thank you for your reply, I said just sometimes works, sometimes didn't

**Comment by MaxMustermann2** [comment]
If you can share any more logs with  `curl -vvI` when it happens, it will help. Thank you.
