### ISSUE TITLE
s0 db get stuck with harmony cli version v7558-v4.3.12-0-gf8777e0c

### ISSUE THREAD

**Issue by PkayJava** [harmony-one/harmony#4259]
**Describe the bug**
S1 Validator Node with Bigger SnapDB with Harmony (C) 2020. harmony, version v7502-v4.3.9-0-g9ca38bc5 (runner@ 2022-05-14T02:08:12+0000) works fine.
after download Download new harmony binary (https://github.com/harmony-one/harmony/releases) Harmony (C) 2020. harmony, version v7558-v4.3.12-0-gf8777e0c (runner@ 2022-08-02T14:04:59+0000)
restart harmony service
S0 Shard get stuck 
then I revert harmony binary back, it works fine.

**To Reproduce**
1. In S1 Validator Node with Bigger SnapDB. 
2. Download new harmony binary (https://github.com/harmony-one/harmony/releases) Harmony (C) 2020. harmony, version v7558-v4.3.12-0-gf8777e0c (runner@ 2022-08-02T14:04:59+0000)
3. sudo service harmony restart
4. s0 get stuck

**Expected behavior**
s0 should continue to sync

**Environment (please complete the following information):**
 - OS: Linux

**Additional context**
- shard 0 get stuck

logs :

{"level":"warn","caller":"/home/runner/work/harmony/harmony/harmony/cmd/harmony/main.go:673","time":"2022-08-08T13:49:51.776239828Z","message":"AllowedTxs setup error: open ./.hmy/allowedtxs.txt: no such file or directory"}
{"level":"error","error":"failed to read shard state from DB","blockNum":32463150,"shardID":1,"epoch":1163,"caller":"/home/runner/work/harmony/harmony/harmony/node/node.go:1161","time":"2022-08-08T13:49:54.123279341Z","message":"[InitConsensusWithValidators] Failed getting shard state"}
{"level":"warn","shardID":-1,"error":"failed to read shard state from DB","caller":"/home/runner/work/harmony/harmony/harmony/cmd/harmony/main.go:738","time":"2022-08-08T13:49:54.123285211Z","message":"InitConsensusWithMembers failed"}
{"level":"error","blockHash":"0xbf004a78fe302df502f1c7a79367f1b79894effc442e9810572a9eb8e3adf04a","error":"unknown ancestor","caller":"/home/runner/work/harmony/harmony/harmony/node/node_handler.go:357","time":"2022-08-08T13:49:57.26485644Z","message":"[VerifyNewBlock] Cannot validate header for the new block"}
{"level":"error","myBlock":32463151,"myViewID":32467063,"phase":"Announce","mode":"Syncing","error":"Block verification failed: unknown ancestor","caller":"/home/runner/work/harmony/harmony/harmony/consensus/validator.go:136","time":"2022-08-08T13:49:57.2648801Z","message":"[validateNewBlock] Block verification failed"}
{"level":"error","blockHash":"0x1a03e4bc45b8a15edba07ceef713eb911b1c4b0d1d3cef411d52431579e1d9aa","error":"unknown ancestor","caller":"/home/runner/work/harmony/harmony/harmony/node/node_handler.go:357","time":"2022-08-08T13:49:58.423450669Z","message":"[VerifyNewBlock] Cannot validate header for the new block"}
{"level":"error","myBlock":32463151,"myViewID":32467063,"phase":"Announce","mode":"Syncing","error":"Block verification failed: unknown ancestor","caller":"/home/runner/work/harmony/harmony/harmony/consensus/validator.go:136","time":"2022-08-08T13:49:58.423464899Z","message":"[validateNewBlock] Block verification failed"}

**Comment by patrickmogul** [comment]
You have to wipe shard 0 for the new version.

Let it rebuild on it's own, it only takes a few moments.

**Comment by LeoHChen** [comment]
Harmony node version:  `v7557-v4.3.12-0-g93b14ddc`

Internal explorer node on shard 2.

The logs
```
{"level":"error","error":"failed signature validation: read shard state for epoch 946: failed to read shard state from DB","caller":"/home/sp/harmony/harmony/api/service/legacysync/epoch_syncing.go:166","time":"2022-08-09T16:32:17.775794619Z","message":"[EPOCHSYNC] Removing peer peer: 18.217.74.191:6000  for invalid data"}
{"level":"error","error":"failed signature validation: read shard state for epoch 946: failed to read shard state from DB","caller":"/home/sp/harmony/harmony/api/service/legacysync/epoch_syncing.go:133","time":"2022-08-09T16:32:17.775810398Z","message":"[EPOCHSYNC] ProcessStateSync failed (isBeacon: true, ShardID: 0, otherEpoch: 1083, currentEpoch: 945)"}
```

**Comment by LeoHChen** [comment]
I guess is the new code can't sync beyond some blocks on the old harmony_db_0.  The current workaround is to stop harmony process; remove harmony_db_0 and resync harmony_db_0 from 0 with epoch block only; usually the problem can be fixed in a few minutes.

**Comment by sophoah** [comment]
Closing the issue, snapDB should only be used by S0 validator.
