### ISSUE TITLE
Testnet reset activities

### ISSUE THREAD

**Issue by sophoah** [harmony-one/harmony#4262]
This issue is created so to track all the activities required to reset the testnet with P-OPS. Target date is for this coming friday on the 19 th August.

- [x] rebase PR https://github.com/harmony-one/harmony/pull/4207 to latest main and make sure travis CI test are all green
- [x] install the latest binary to all testnet node (internal and external validator and explorer node)
- [x] make sure DNS node are only internal node
- [x] on all internal nodes (bootnode, validator and explorer node)
  - [x] delete the bootnode .dht folder to clean the connected peers if any 
  - [x] stop node, delete all DBs folder
  - [x] restart the bootnode
  - [x] restart the internal node
- [x] reset explorer dashboard DB (do with Jenya)

Network should be up and running via the internal node for 1 epoch for ~4h(PreStakingEpoch is at epoch 1), during this time, external validator can be created (StakingEpoch is at epoch 2) and will last for ~4 hours. External validator can be created after as well and since internal node are having 70% voting, it's not a **must** to have external validator online during epoch 2.
  - [ ] create and run the external validator
  - [ ] going forward, harmony engineer will have to run a testnet node as well to help with the testnet

**Comment by rlan35** [comment]
I would recommend running a "external" validator with the same infrastructure of internal nodes. The purpose of having external validator is to test the functionalities of staking, but whether it should be done by external or internal machines doesn't matter. Using internal nodes to run external validator will give us more control over the stability of the network and avoid having downtime issue like before when external validator going absent.

**Comment by JB273** [comment]
> I would recommend running a "external" validator with the same infrastructure of internal nodes. The purpose of having external validator is to test the functionalities of staking, but whether it should be done by external or internal machines doesn't matter. Using internal nodes to run external validator will give us more control over the stability of the network and avoid having downtime issue like before when external validator going absent.

I feel it's better to have "real" external validator nodes, as this will give a better view on impact of actions.
Since this now still will be a small group of validators we can still allow generic access when setting up the needed infrastructure. So I would propose we setup with user e.g. harmony and have access based on ssh-keys and maybe some other factor...

**Comment by sophoah** [comment]
> I would recommend running a "external" validator with the same infrastructure of internal nodes. The purpose of having external validator is to test the functionalities of staking, but whether it should be done by external or internal machines doesn't matter. Using internal nodes to run external validator will give us more control over the stability of the network and avoid having downtime issue like before when external validator going absent.

Have to be more precise here when you say same infrastructure, does it mean : 
- on the same node ?
- on the same DC ?
- simply the same nod specs ?

Also, right now the PR still has 70% for internal node so the external validator are not required.
