### ISSUE TITLE
Why do blocks with empty transactions exist?

### ISSUE THREAD

**Issue by ares0x** [harmony-one/harmony#4267]
When I used ethclient's BlockByNumber() to get the block details, it prompted me eth get block by number error:server returned empty transaction list but block header indicates According to the error, I found that the block's transactions were indeed empty. I would like to know what is the point of such a block's existence and what I should do when I encounter such a situation.
![image](https://user-images.githubusercontent.com/53114112/185024786-955c1f3e-8c97-49e7-81d7-33bba6924631.png)

**Comment by sophoah** [comment]
Closing this issue, some blocks contains staking transaction only and different RPC method would need to be used in order to get the staking transaction
