### ISSUE TITLE
epoch download block is not working

### ISSUE THREAD

**Issue by sophoah** [harmony-one/harmony#4407]
**Describe the bug**
epoch block are not syncing with the below error
```json
{"level":"warn","module":"downloader","ShardID":0,"mode":"long range","error":"[InsertChain]: block is not last block in epoch","target block":17885972,"block number":1,"caller":"/home/sp/harmony/harmony/hmy/downloader/longrange.go:216","time":"2023-04-18T05:04:49.196775575Z","message":"insert blocks failed in long range"}
```

**To Reproduce**
1. delete shard 0 db and restart the node

**Expected behavior**
shard 0 epoch block should download

**Screenshots**
N/A

**Environment (please complete the following information):**
- harmony version : `Harmony (C) 2023. harmony, version v8044-v2023.1.0-397-g53161ca3` from latest dev

**Additional context**

**Comment by GheisMohammadi** [comment]
The nodes in devnet are using staged stream sync, so If you don't enabled staged sync , it uses old version of stream sync which is not compatible with staged sync.

**Comment by sophoah** [comment]
thanks @GheisMohammadi closing that issue
