### ISSUE TITLE
Make metamask working for Harmony blockchain

### ISSUE THREAD

**Issue by mikedoan** [harmony-one/harmony#441]
## Summary

The goal is to make metamask working with harmony blockchain, specifically:

1/ People can use metamask to checkout balance, transfer token to another account.
2/ For "view on etherscan" feature, can people view info by getting redirected into our dashboard/explorer (not sure if do-able).
3/ Customize the metamask talking to harmony node by RPC.
4/ Provide harmony team with the requests needed to make metamask talking with harmony node.
5/ Collaborate with Harmony if you need any support to make work like https://www.thundercore.com/build-dapps-on-thundercore

We need the setup like this https://www.thundercore.com/build-dapps-on-thundercore

**Comment by lijiang2087** [comment]
this is a separate task, not a github issue, closing this one for now @mikedoan @LeoHChen
