### ISSUE TITLE
Network fails to start if dht storage corrupted.

### ISSUE THREAD

**Issue by Frozen** [harmony-one/harmony#4471]
Value log truncate required to run DB. This might result in data loss
github.com/dgraph-io/badger.init
	/go/pkg/mod/github.com/dgraph-io/badger@v1.6.2/errors.go:111
runtime.doInit
	/usr/local/go/src/runtime/proc.go:6331
runtime.doInit
	/usr/local/go/src/runtime/proc.go:6308
runtime.doInit
	/usr/local/go/src/runtime/proc.go:6308
runtime.doInit
	/usr/local/go/src/runtime/proc.go:6308
runtime.doInit
	/usr/local/go/src/runtime/proc.go:6308
runtime.main
	/usr/local/go/src/runtime/proc.go:233
runtime.goexit
	/usr/local/go/src/runtime/asm_arm64.s:1172
cannot open Badger data store at .dht-127.0.0.1-19876
github.com/harmony-one/harmony/p2p/discovery.getDataStoreOption
	/go/src/github.com/harmony-one/harmony/p2p/discovery/option.go:63
github.com/harmony-one/harmony/p2p/discovery.DHTConfig.GetLibp2pRawOptions
	/go/src/github.com/harmony-one/harmony/p2p/discovery/option.go:32
github.com/harmony-one/harmony/p2p.NewHost.func1
	/go/src/github.com/harmony-one/harmony/p2p/host.go:169
github.com/libp2p/go-libp2p/config.(*Config).NewNode
	/go/pkg/mod/github.com/libp2p/go-libp2p@v0.24.0/config/config.go:327
github.com/libp2p/go-libp2p.NewWithoutDefaults
	/go/pkg/mod/github.com/libp2p/go-libp2p@v0.24.0/libp2p.go:68
github.com/libp2p/go-libp2p.New
	/go/pkg/mod/github.com/libp2p/go-libp2p@v0.24.0/libp2p.go:54
github.com/harmony-one/harmony/p2p.NewHost
	/go/src/github.com/harmony-one/harmony/p2p/host.go:200
main.main
	/go/src/github.com/harmony-one/harmony/cmd/bootnode/main.go:129
runtime.main
	/usr/local/go/src/runtime/proc.go:250
runtime.goexit
	/usr/local/go/src/runtime/asm_arm64.s:1172
cannot initialize libp2p host
github.com/harmony-one/harmony/p2p.NewHost
	/go/src/github.com/harmony-one/harmony/p2p/host.go:203
main.main
	/go/src/github.com/harmony-one/harmony/cmd/bootnode/main.go:129
runtime.main
	/usr/local/go/src/runtime/proc.go:250
runtime.goexit
	/usr/local/go/src/runtime/asm_arm64.s:1172
cannot initialize network

**Comment by MaxMustermann2** [comment]
Closed by #4472
