### ISSUE TITLE
explorer can't search for account address generated by wallet

### ISSUE THREAD

**Issue by LeoHChen** [harmony-one/harmony#503]
**Describe the bug**

We use wallet to create new account and do token transfer. The token transfer was succeeded and the block was mined on blockchain.  However, we can't find the account address using the search function in explorer. It reports not found.

**To Reproduce**
Steps to reproduce the behavior on testnet.

1. wallet new
2. wallet getFreeToken
3. wallet transfer
4. wallet balances
5. search the account using the search box in explorer.harmony.one

**Expected behavior**

Some of the address is searchable on the explorer though.

**Screenshots**

**Environment (please complete the following information):**
 - OS: [Linux, MacOS]
- Go environment [ ```go env``` ]

**Additional context**

**Comment by LeoHChen** [comment]
In our last test, we found that after a regular transfer transaction can be searched using the account, but the smart contract call like faucet won't have the same account number.

**Comment by lzl124631x** [comment]
@LeoHChen who reported this issue? I think this is not an issue if the repro steps are like those.

**Comment by LeoHChen** [comment]
I think it's me reported it last time. If it's not an issue anymore, please close it.

**Comment by lzl124631x** [comment]
Now we know that `getFreeToken` tx won't expose the client's tx. Only when the client explicitly making a transfer will make the account searchable on explorer. Closing this as this issue doesn't repro now.

**Comment by rlan35** [comment]
Reopen this issue since the functionality of searching account address that doesn't involve a normal transfer transaction is not implemented yet.

This is pending on the account manager integration.

**Comment by rlan35** [comment]
Reopen this issue since the functionality of searching account address that doesn't involve a normal transfer transaction is not implemented yet.

This is pending on the account manager integration.
