### ISSUE TITLE
wallet peer connection error after running many times

### ISSUE THREAD

**Issue by chaosma** [harmony-one/harmony#572]
**Describe the bug**
After querying wallet commands multiple times and idle a long time, the peer returned by the peer discovery service contains no addr. 

**To Reproduce**
Use wallet and idle a long time. after that, we have grpc connection error caused by the peer returned by discovery service don't contain address

**Log**
Miss. Add it later if necessary.

**Comment by LeoHChen** [comment]
This was due to bootnode's DHT only keep the node info for up to 24 hours.  The nodes has to constantly announce itself to bootnode to keep the info up to date.  This issue was fixed in https://github.com/harmony-one/harmony/pull/590.
