### ISSUE TITLE
new node join testnet isssues

### ISSUE THREAD

**Issue by LeoHChen** [harmony-one/harmony#611]
**Describe the bug**

I launched a testnet and run txgen/wallet for consensus for some time.  When I started a new node, I can see the new node had sent ping message to network and leader received it.

However, there are two issues here.

1) I didn't see state syncing working.  
2) Also, new node didn't get pong message, that's it failed to verify the leader messages.

**Comment by chaosma** [comment]
The pong message didn't fully works. 
Test 1:  use only one new node and join the network 30s later.  Pass test
Test 2: use two new nodes, one join network after 30s and the other new node join network after 60s. The second one didn't receive pong message with leader's public key.

**Comment by LeoHChen** [comment]
The problem is solved with changes from me and chao.
