### ISSUE TITLE
Issue: ERROR[03-23|19:08:23.399] Failed to unmarshal message payload.     port=9000 ip=18.221.1.194 err="proto: field \"message.DrandRequest.sender_address\" contains inv alid UTF-8"     dRand="&{vrfs:0xc0000106b0 bitmap:0xc00121aa00 pRand:<nil> rand:<nil> ConfirmedBlockChannel:0xc002836060 PRndChannel:0xc002836360 RndChannel:0xc002

### ISSUE THREAD

**Issue by sukantag** [harmony-one/harmony#635]
latest code pull as of mar 23, 12:11PM, PST

[harmony-18.221.1.194.log](https://github.com/harmony-one/harmony/files/2999701/harmony-18.221.1.194.log)

I see this in the log file 
"WARN [03-23|19:08:50.845] Failed to verify the message signature   port=9000 ip=18.221.1.194 Error="proto: field \"message.ConsensusRequest.SenderAddress\" contains invalid UTF-8""

and the log file is attached with this issue.

Thx

**Comment by harmony-ek** [comment]
Thanks!  @rlan35 can you take a look?

**Comment by rlan35** [comment]
Hi @sukantag Thanks for the bug report. Actually this is due to the recent change on protobuf. The SenderAddress is changed to other field. So the latest code is not compatible with running testnet. We will update the testnet soon, and then this error should disappear.
