### ISSUE TITLE
Enable viewing the list of nodes connected and the transactions each processed (or at least some statistics about it)

### ISSUE THREAD

**Issue by shaimo** [harmony-one/harmony#663]
When running a node it would be nice to see that it is indeed part of the network e.g. by seeing the current list of nodes.
It would also be nice to see the transactions each node processes or at least some statistics about it. This would also be great as a CLI at the node itself, in order to be able to verify the node is indeed processing transactions.

**Comment by lzl124631x** [comment]
https://github.com/harmony-one/harmony/pull/688#issuecomment-480554912

First request shall be handled by the PR. ETA 4/13/2019
