### ISSUE TITLE
Race condition in consensus leader and no block is proposed

### ISSUE THREAD

**Issue by LeoHChen** [harmony-one/harmony#680]
**Describe the bug**

In the latest testnet test, there is a consensus timeout. After that, no new consensus can be reached even though the leader received new transaction.

some log

```
{"count":1,"ip":"54.218.247.214","lvl":"dbug","msg":"Consensus timeout, retry!","port":"9000","t":"2019-04-02T15:45:05.980251926Z"}

```

**Comment by LeoHChen** [comment]
```
"ip":"54.218.247.214","lvl":"dbug","msg":"Got more transactions","num":1,"port":"9000","t":"2019-04-03T16:00:07.029885446Z","totalPending":19061}
{"Address":"0xb900EeCF6D1638A4F9b965b816D15a23d0414182","ip":"54.218.247.214","lvl":"info","msg":"Sending Free Token to ","port":"9000","t":"2019-04-03T16:00:09.165848089Z"}
```

**Comment by LeoHChen** [comment]
Full log is here. https://s3.console.aws.amazon.com/s3/buckets/harmony-benchmark/logs/20190402.042758/leader/?region=us-west-2&tab=overview

@mikedoan

**Comment by LeoHChen** [comment]
This issue is nothing to do with timeout.
The new testnet stuck with the consensus again.  And I found consensus ongoing even after one timeout.

I've checked the log and found the consensus stuck after "Consensus sending new block to block channel".  And there is not "Consensus sent new block to block channel" after this last line of the log.  So, it seems the consensus stuck at the sending.

After that, there is no new block being proposed.

**Comment by LeoHChen** [comment]
After discussion with @rlan35 , it seems the leader stuck with 
```
 pRndAndBitmap := <-consensus.PRndChannel
```
The log file shows "Waiting for pRnd", but didn't get the next log "GOT pRnd" at the end.  So, the leader stuck to receive the block anyway.

**Comment by rlan35** [comment]
After some digging, I actually don't have clear culprit. It may be race condition between consensus and drand. For now, we can disable the drand code to unblock testnet running. This may not be a problem anymore once we work on code cleanup/refactor.
