### ISSUE TITLE
Gracefully handle unavailability of previous sharding state

### ISSUE THREAD

**Issue by harmony-ek** [harmony-one/harmony#701]
Seen in #684 and #675, sometimes a node's block syncing falls behind the consensus tip by more than a full epoch's worth, causing the previous epoch block (not synced yet) to be unavailable while processing the new epoch block from the consensus side.  There is a big fat TODO (“OMG sharding state not available; what do we do?!?!!1!11one”) that I (@harmony-ek) originally left in #679 and reassigned to @chaosma in #700.  This ticket tracks the TODO item, which is a fundamental resharding blocker issue.

**Comment by LeoHChen** [comment]
too old
