### ISSUE TITLE
[Feature] Update folder layout in pub.harmony.one

### ISSUE THREAD

**Issue by lvyelin** [harmony-one/harmony#702]
## Summary

Update folder layout in pub.harmony.one to support history.

## Current Design

release
├── 20190124
│   └── linux-x86_64
├── 20190216
│   ├── darwin-x86_64
│   └── linux-x86_64
└── banjo
    ├── darwin-x86_64
    └── linux-x86_64

## Problems

Only latest binary files on the server. not able to get old version.

## Proposal

release
├── darwin-x86_64
│   ├── banjo -> v2876
│   ├── latest -> v2876
│   └── v2876
└── linux-x86_64
    ├── banjo -> v2912
    ├── latest -> v2912
    ├── v2876
    └── v2912

**Comment by LeoHChen** [comment]
Change the scripts/go_executable_build.sh to add a "release" action, and a "-R name" option to do the upload to s3.

**Comment by lvyelin** [comment]
I think the upload should be done in jenkins build only

**Comment by LeoHChen** [comment]
fine with me.

**Comment by LeoHChen** [comment]
but we need a script to do that anyway.

**Comment by lvyelin** [comment]
We can do it in /jenkins. Not /harmony.

**Comment by LeoHChen** [comment]
fine
