### ISSUE TITLE
Resharding timing

### ISSUE THREAD

**Issue by harmony-ek** [harmony-one/harmony#706]
## Summary

This proposal aims to streamline timing of sharding state calculation.

## Current Design

The new sharding state for an epoch number *E*≥0, say *E*=1337, is calculated and broadcast unilaterally by the beacon chain leader after the corresponding epoch block *b*=10*E*, say *b*=13370) has been processed, in [`func (node *Node) PostConsensusProcessing(newBlock *types.Block)`](https://github.com/harmony-one/harmony/blob/36086113990962627ce180582be7400cc045dce5/node/node_handler.go#L306).

## Problems

1. Sharding assignment should be voted upon by the beacon committee instead.
2. Sharding assignment for an epoch should be recorded in the corresponding epoch block, so it must be known before the epoch starts.
3. When syncing blocks (and following blockchain to update state), sharding assignment should be known, e.g. in order to calculate block rewards.  Since the current broadcast is on consensus protocol level, it is lost to nodes who will be joining the network later and will have missed the broadcast message.

## Proposal

1. Beacon chain shall vote on the next epoch's (say, *E*=1337) sharding assignment for all committees, as part of consensus on the last block of the current epoch (say, *b*=13369).
2. This assignment shall propagate to other shards via block syncing.
3. Regular (non-beacon) leader shall propose to end the current epoch when it sees the resharding assignment for the new epoch on the beacon chain, by copying/echoing the local shard's resharding assignment.
4. Regular validator shall validate the leader's epoch-ending proposal by independently comparing the proposed local resharding assignment against the master copy in the beacon chain.
5. All nodes, after processing the last block of the current epoch as above, shall scatter/gather to join their next committee (many will stay put though, due to cuckoo).

### Main

- [x] Plumb sharding state field in a block header.
    * This is *for now* – sharding assignment could potentially get pretty large as the network grows (10M+ nodes == 2GiB); we will have to move out of the block header and to elsewhere before we reach that scale.
- [x] Move the resharding call to the block proposal stage of the last block of an epoch.
    - [x] Make leader include next sharding assignment.
    - [x] Make validator verify the sharding assignment.
- [ ] Make all nodes trigger resharding scatter/gather logic after processing the last block of the currently assigned committee.
    - [ ] Wait for beacon chain's last block to be available.
    - [ ] Retrieve the global resharding assignment and check new assignment.
    - [ ] If needed, move to another shard.

### Post-reshading block reward

- [ ] For rewarding signers of a block, retrieve the signer list from the corresponding sharding assignment block.
    - [ ] For genesis epoch (=0), use the hardcoded assignment.
    - [ ] For subsequent epochs (>0), use the sharding assignment in the epoch-last block of the previous epoch (that is, the parent block of the current epoch block).
        - [ ] This implies the ability to quickly locate the epoch block of an arbitrary epoch.  Add this to the DB.

**Comment by harmony-ek** [comment]
Updated the proposal/comments to reflect the latest state of code.  Resharding scatter/gather is not a hard requirement for block reward; working on the block reward part.

**Comment by LeoHChen** [comment]
close it for now. not working on resharding atm.
