### ISSUE TITLE
Get goreport to 100%

### ISSUE THREAD

**Issue by LeoHChen** [harmony-one/harmony#708]
## Summary

Looking at the go report card of Harmony report and we are doing pretty good.  The request is to get go report to 100% on every check.

https://goreportcard.com/report/github.com/harmony-one/harmony

This is the current report.

```
Results

gofmt 98%
go_vet 100%
gocyclo 95%
golint 99%
license 100%
ineffassign 96%
misspell 97%

```

**Comment by u5surf** [comment]
@LeoHChen Hi, I fixed lint in this repos except `gocyclo`.
if it looks good for you, please merge following PR.

**Comment by LeoHChen** [comment]
leave gocyclo open, closing this ticket.
