### ISSUE TITLE
[Feature] display the real block number in explorer

### ISSUE THREAD

**Issue by LeoHChen** [harmony-one/harmony#714]
# Problem/limitation At Hand

I launched a new testnet with DB persisted from the previous launch, which means the blockchain has 2000+ blocks already mined and all nodes have restored the same blockchain already.  The blockchain runs fine and can keep doing consensus with the new transaction.  However, on the explorer, I can see the block height starts from 0 again, even though on the log file, we knew the block height starts from 2000 already. 

**Which component?**

- [ ] consensus
- [ ] deploy script
- [ ] wallet
- [x] explorer
- [ ] node script
- [ ] test automation
- [ ] demo app
- [ ] others ...

# Proposed Solution

The explorer should display the real block height number from the blockchain when it display the data.

# Alternatives Considered

# Additional Context

**Comment by lzl124631x** [comment]
I suspect it's because the explorer storage (see explorer/storage.go) doesn't pick up from where it stopped. + @mikedoan to take a look. Thanks.

**Comment by LeoHChen** [comment]
A workaround fix: https://github.com/harmony-one/harmony/pull/717
