### ISSUE TITLE
Optimize the Design of S3 Log Folder Structure 

### ISSUE THREAD

**Issue by AndyBoWu** [harmony-one/harmony#719]
/*
Proposed by: Andy Bo Wu
Date: April 12, 2019

VERSION HISTORY
0.1 - created this design, attached a screenshot
"/

We need to redesign a better folder structure to store log files.

* The current log folder structure is not ideal to find a log file quickly and easily
* It is not ideal for AWS Athena to scan a folder storing all log files for each day
* Not cost optimized 

## Proposal

There will be some major changes to the folder structure, which might needs some code change. Some changes include not limited to:
* Create subfolder for Year, Month, and Day
* Add TimeStamp on the final log file which will be ideal later for AWS Athena sanning
* Add a folder to store all solider logs

See the attached screenshot for better understanding.

![Screen Shot 2019-04-11 at 11 39 25 PM](https://user-images.githubusercontent.com/5258417/56074920-dbfbaa80-5d6e-11e9-9805-9ff0017675fe.png)

**Comment by LeoHChen** [comment]
please update the PR info and close this one.

**Comment by LeoHChen** [comment]
I guess you also want to move all the soldier log, so don't close it until that part finished.

**Comment by bwu2sfu** [comment]
That's right, I need to discuss with team about how to handle this change.

**Comment by mindstyle85** [comment]
@AndyBoWu can this be closed now?
