### ISSUE TITLE
leader node out of space 

### ISSUE THREAD

**Issue by LeoHChen** [harmony-one/harmony#723]
**Describe the bug**

In one testnet we launched, when we reached around 25000 blocks, the leader node got an OUT of space error and the node program crashed.  The db/*.ldb files have an accumulated size of around 5.3G.  However, on other validator nodes, the size of the db is around 3.5GB.

All the leader/validator logs and some db logs are uploaded to s3://harmony-benchmark/broken/20190411.233531

Check the log files for details.

**Expected behavior**

We used to reach 60000 blocks and no out of space issue.

A few questions,

1) why leader has a different size of db files than the validators.
2) why leader has a bigger size of db files.
3) why the ldb file had an increased size of blocks?  
4) what's the size of each block? from the block explorer, we can see each tx in the block is around 1k, but based on the calculation, it is around 200kb per block, which is huge.

**Comment by LeoHChen** [comment]
to download the logs, just do 
aws s3 sync s3://harmony-benchmark/broken/20190411.233531 20190411.233531

**Comment by mikedoan** [comment]
offline discussed - leader wrote additional data for explorer - we'll remove it later

**Comment by mikedoan** [comment]
will answer the block size very soon

**Comment by mikedoan** [comment]
{"TPS":1.5331665731560264,"consensus":"[duty:LDR, PubKey:f6f0f3b173a1dbf55b6925d8987734c94757f0517b617fc23e8784e0ba999772e140abf1f82ec323ac9c1205f62882096d0d09471056d9e359521eaf9fa2066e9a362b1da84313fc7ddcf703adef325a010e65e49a9f0a2d61d5b20fd5d58591, ShardID:0, Address:0xAC286808E6CE0E56559d08b99a3e0e71af1f6dec, state:CommittedDone]","endTime":"2019-04-12T01:28:48+0000","ip":"34.214.145.15","lvl":"info","msg":"TPS Report","numOfTXs":1,"port":"9000","startTime":"2019-04-12T01:28:47+0000","t":"2019-04-12T01:28:48.55784741Z","timeElapsed":"652.244849ms"} 


there weren't much txs per block - it does make sense to have 200kb per block. looking into deeper

**Comment by mikedoan** [comment]
running a few local test and print out debug. it looks pretty normal.
