### ISSUE TITLE
[Feature] change harmony night build to pipeline

### ISSUE THREAD

**Issue by LeoHChen** [harmony-one/harmony#737]
# Problem/limitation At Hand

Please convert the current harmony nightly build/test to pipeline, and use stage for build/test.  And also notify the discord with the result of the nightly build/test.  The test results can include the number of shards/ consensus/ tps/ nodes.

http://jenkins.harmony.one/job/nightly-new/

**Comment by lvyelin** [comment]
Which S3 bucket is used to save nightly build binary files
