### ISSUE TITLE
Sanitize log15 context names

### ISSUE THREAD

**Issue by harmony-ek** [harmony-one/harmony#753]
## Description

We use `log15`, which support logging of named context objects in addition to plain log message.  When these are emitted in JSON-format logs, the context object names are used as JSON object keys.  Most JSON database or manipulation facilities (such as ElasticSearch and jq) expect object keys are valid Javascript identifiers (regex `[[:alpha:]_][[:alnum:]_]*`), but a few of our logging calls deviate from this convention, and the resulting log JSON objects are not usable with those tools.

Also, most time-series database tools expect the object key names to be hardcoded and invariable.  For example, in order to log a specific name-value pair, one would avoid passing them directly like this:

```go
utils.GetLogInstance().Info("saw invalid key-value pair", key, value)
```

And instead use two context variables:

```go
utils.GetLogInstance().Info("saw invalid key-value pair", "key", key, "value", value)
```

## Definition of “Done”

No `log15` logging calls with an invalid or variable context name are left behind.

**Comment by mindstyle85** [comment]
@LeoHChen this still open?

**Comment by LeoHChen** [comment]
we have switched to zerolog, no longer valid.
