### ISSUE TITLE
node explorer

### ISSUE THREAD

**Issue by LeoHChen** [harmony-one/harmony#819]
## Summary

We need a node explorer/dashboard to monitor all the testnet nodes.  We were looking into metricbeat to emit the metrics and kinana to display dashboard.

https://www.elastic.co/elk-stack

## Current Design

@harmony-ek have added metricbeat into each node we launched.  However, the dashboard wasn't really maintained and easily viewable.  We need to sort out a way for easy access with authentication.

For external node operators, if they use docker image, we can include metricbeat as part of the image. If not, we may not have a monitor for them.

**Comment by LeoHChen** [comment]
https://hubble.figment.network/cosmos/chains/cosmoshub-2

**Comment by AndyBoWu** [comment]
Problems
* dashboard UI is not user-friendly
* dashboard access authentication 

The UI (Kibana?) should be highly customizable, also I need to clearly understand what the requirements are from colleagues, and externmal users. The authentication issue can be resovled through IAM policy.

Actions Plan
* deploy metricbeat on two test EC2 instance
* UI customization

**Comment by AndyBoWu** [comment]
This comment is for myself to track this ticket.

Installed ElasticSearch and Kibana on my local workstation. See the attached screenshot. 

Questions to ponder:
1. how to easily deploy both components in our multiple instances across regions? Through CloudFormation or SSM? 
2. what data needed to be extracted and presented on our UI through Kibana?

**Comment by AndyBoWu** [comment]
[Metricbeat]

Download link: https://www.elastic.co/guide/en/beats/metricbeat/6.2/metricbeat-installation.html

**Comment by LeoHChen** [comment]
I was thinking to use prometheus to collect data now, instead of metricbeat.  Please take a look. 

https://prometheus.io/docs/prometheus/latest/installation/

**Comment by AndyBoWu** [comment]
Progress on May 20, 2019
* Gained a fairly good understanding of this chain of service: ElasticSearch, Kibana, and Metribeat
* Deployed these three components on my local iMac
* Configured each component, passed my own integration test
* all services are up and running
* Attached two screenshots

[TO-DO]
* deploy metricbeat on two testing EC2 instances
* create a new instance for hosting ElasticSearch and Kibana, this is the machine for the dashboard to monitor all test nodes


![Screen Shot 2019-05-20 at 10 05 00 PM](https://user-images.githubusercontent.com/5258417/58069752-5d531380-7b4b-11e9-829e-79513c560ea9.png)
![Screen Shot 2019-05-20 at 11 24 35 AM](https://user-images.githubusercontent.com/5258417/58069753-5d531380-7b4b-11e9-9453-a3eb05b9c64e.png)

**Comment by AndyBoWu** [comment]
Did some research about different between (ElasticSearch + Kibana + MetricBeat) VS Prometheus. 

Check out this link: https://stackoverflow.com/questions/40793901/prometheus-vs-elasticsearch-which-is-better-for-container-and-server-monitoring

and the explanations from FuzzyAmi.

`ELK is a general-purpose no-sql stack that can be used for monitoring. We've successfully deployed one on production and used it for some aspects of our monitoring system. You can ship metrics into it (if you wish) and use it to monitor them, but its not specifically designed to do that. Nor does it come with an alerting system - you'll need to setup another component for that (like Sensu).

Prometheus, on the other hand, is designed to be used for monitoring. And along with its metric-gathering clients (or other 3rd party clients like Telegraf and its service discovery options (like consul) and its alert-manager is just the right tool for this job.

Ultimately, both solutions can work, but in my opinion Elasticsearch will require more work and more upkeep (we found that ES clusters are a pain to maintain - but that depends on the amount of data you'll have).`

**Comment by AndyBoWu** [comment]
So, I think in the long run, we should go for prometheus based on my understanding. I will have another meeting with @LeoHChen tonight to discuss this design.

**Comment by AndyBoWu** [comment]
Deployed Prometheus on my iMac, seems working fine. See the attached screenshot. 

Something I do appreciate:
* very easy to deploy and set up, compared to Metribeats
* it has an embedded Alerts functionality, I think this is going to help us a lot down the road
* UI is more user-friendly I think


![Screen Shot 2019-05-22 at 11 00 27 PM](https://user-images.githubusercontent.com/5258417/58229158-c40c3480-7ce5-11e9-94d9-cac8f96a1129.png)

**Comment by AndyBoWu** [comment]
[Prometheus]

1. https://www.youtube.com/watch?v=PDxcEzu62jk

**Comment by AndyBoWu** [comment]
The reason why it is not wise to deploy `Node Exporter` using Docker.

https://github.com/prometheus/node_exporter

The node_exporter is designed to monitor the host system. It's not recommended to deploy it as a Docker container because it requires access to the host system. Be aware that any non-root mount points you want to monitor will need to be bind-mounted into the container. If you start container for host monitoring, specify path.rootfs argument. This argument must match path in bind-mount of host root. The node_exporter will use path.rootfs as prefix to access host filesystem.

**Comment by AndyBoWu** [comment]
Hi @LeoHChen, can you please create a domain name for (Prometheus + Grafana) project in Route 53?

I am thinking something like https://dashboard.harmony.one or https://nodes.harmony.one.
