### ISSUE TITLE
[Feature] one click to run a harmony node using cloudformation

### ISSUE THREAD

**Issue by LeoHChen** [harmony-one/harmony#820]
# Problem/limitation At Hand

We want to create a cloudformation recipe to start a harmony node using just one-click.

You may refer to https://github.com/aws/aws-ops-wheel

for example.

**Which component?**

- [ ] consensus
- [ ] deploy script
- [ ] wallet
- [ ] explorer
- [x] node script
- [ ] test automation
- [ ] demo app
- [ ] others ...

# Proposed Solution

We already have docker image support for harmony node. The one-click script is to enable node runner to start the node easily. This task can be extended to GCP support, and digital ocean one-click support.

# Alternatives Considered

# Additional Context

**Comment by AndyBoWu** [comment]
The link in this article is about a randomizer I think. The requirement for this task is to create a CF recipe. I think I need more info to understand the issue.

**Comment by LeoHChen** [comment]
@AndyBoWu the script in github is not to be used for our node. LoL.  It is just a way to show you what we want to archive at the end.   We should be able to launch one node, with just a click on github.  The work for sure is to do it using cloudformation recipe.

**Comment by stargeizer** [comment]
I like this simplification to run a node, gracias!

**Comment by AndyBoWu** [comment]
Terraform might be a better choice considering later on if we need to launch our infrastructure on different platforms.

[REFERENCE]
[1] https://hackernoon.com/your-infrastructure-as-code-cloudformation-vs-terraform-34ec5fb5f044

**Comment by nyetwurk** [comment]
Here is an ansible approach
https://github.com/Blockdaemon/harmony-scripts/

**Comment by hsienchiaolee** [comment]
Agreed with @AndyBoWu, I didn't know this before, but there is [provisioner](https://www.terraform.io/docs/provisioners/remote-exec.html) support.
