### ISSUE TITLE
./scripts/go_executable_build.sh error

### ISSUE THREAD

**Issue by ewnk** [harmony-one/harmony#841]
./scripts/go_executable_build.sh
./scripts/go_executable_build.sh: line 5: declare: -A: invalid option
declare: usage: declare [-afFirtx] [-p] [name[=value] ...]
./scripts/go_executable_build.sh: line 29: declare: -A: invalid option
declare: usage: declare [-afFirtx] [-p] [name[=value] ...]
./scripts/go_executable_build.sh: line 34: libbls384.dylib: syntax error: invalid arithmetic operator (error token is ".dylib")

**Comment by CRYSTERO** [comment]
How did you solve this problem?
