### ISSUE TITLE
can't connect to bootnode Retry  44,Link not up

### ISSUE THREAD

**Issue by ewnk** [harmony-one/harmony#842]
WARN [05-14|21:28:03.443] can't connect to bootnode                port=9000 ip=127.0.0.1 error="dial attempt failed: <peer.ID Qm*GaBSsB> --> <peer.ID Qm*JgbVuf> dial attempt failed: dial tcp4 127.0.0.1:9876: connect: connection refused" try=44
WARN [05-14|21:28:05.443] can't connect to bootnode                port=9000 ip=127.0.0.1 error="dial backoff"

**Comment by LeoHChen** [comment]
are you running test locally?  are you using the deploy.sh script?

**Comment by ewnk** [comment]
Yes, I'm running locally. I want to access the RPC API. How do I run it? (I'm running harmony according to github's documentation right now)

**Comment by ewnk** [comment]
> are you running test locally? are you using the deploy.sh script?

Yes, I'm running locally. I want to access the RPC API. How do I run it? (I'm running harmony according to github's documentation right now)
