### ISSUE TITLE
help: - Information disposal algorithm using erasure encoding (to be integrated)

### ISSUE THREAD

**Issue by guagualvcha** [harmony-one/harmony#865]
I see erasure encoding part is completed in the doc
`- Information disposal algorithm using erasure encoding (to be integrated)
`
but I can't find it in p2p module, can you show me in which branch or where I can find the code?

**Comment by LeoHChen** [comment]
@chaosma , can you comment on this ticket?

**Comment by LeoHChen** [comment]
and provide some reference of our test

**Comment by chaosma** [comment]
@guagualvcha  The implementation of ida is in this repo [libunison](https://github.com/harmony-one/libunison). It's a standalone component.  We haven't integrate the ida into our harmony main repo yet. Currently we use libp2p's peer discovery and p2p message passing functions in main repo.

**Comment by guagualvcha** [comment]
thks. Get that.
