### ISSUE TITLE
Empty ShardState message brings down the entire network except beacon shard

### ISSUE THREAD

**Issue by harmony-ek** [harmony-one/harmony#866]
The `ShardState` message is used until beaconchain syncing is fixed so that the network can receive the new sharding decision made by the beacon committee.  This message is sent by the beacon leader, but is not integrity-protected by the beacon leader, and no validation is done on the receiver side.  A malicious node may craft this message and send to the entire network with an empty body, which means that all receivers except for ones in beaconchain will see that their assignment is missing for the next shard and exit.

Note: This is a security issue.

**Comment by LeoHChen** [comment]
not sure if it is still relevant, assigning to @SebastianJ to try it out.

**Comment by LeoHChen** [comment]
old one, can be closed
