### ISSUE TITLE
[crash] index out of range

### ISSUE THREAD

**Issue by LeoHChen** [harmony-one/harmony#939]
**Describe the bug**

019/06/03 20:29:38 Command running ./harmony [-ip 100.24.36.232 -port 9000 -log_folder ../tmp_log/log-20190603.202718 -bootnodes /ip4/54.213.43.194/tcp/9870/p2p/QmbPVwrqWsTYXq1RxGWcxx9SWaTUCfoo1wA6wmdbduWe29,/ip4/100.26.90.187/tcp/9870/p2p/Qmdfjtk6hPoyrH1zVD9PEH4zfWLo38dP2mDvvKXfh3tnEv -min_peers 60 -is_genesis -account_index 112 -nopass]
2019/06/03 20:35:00 Stderr 2019/06/03 20:29:39 No priviate key can be loaded from filekeyfile./.hmykey
2019/06/03 20:29:39 Using random private key
panic: runtime error: index out of range

goroutine 3819 [running]:
github.com/harmony-one/bls/ffi/go/bls.(*Sign).VerifyHash.func1(0xc0030a3440, 0xc0027f25a0, 0xc006871a60, 0xc006871a58)
        /home/leochen/go/pkg/mod/github.com/harmony-one/bls@v0.0.1/ffi/go/bls/bls.go:453 +0x121
github.com/harmony-one/bls/ffi/go/bls.(*Sign).VerifyHash(0xc0030a3440, 0xc0027f25a0, 0x1cf3de0, 0x0, 0x0, 0xc9c2778a)
        /home/leochen/go/pkg/mod/github.com/harmony-one/bls@v0.0.1/ffi/go/bls/bls.go:453 +0x46
github.com/harmony-one/harmony/consensus.(*Consensus).onNewView(0xc0001602c0, 0xc004d31270)
        /home/leochen/go/src/github.com/harmony-one/harmony/consensus/view_change.go:348 +0x430
github.com/harmony-one/harmony/consensus.(*Consensus).handleMessageUpdate(0xc0001602c0, 0xc0033aa786, 0x11f, 0x13a)
        /home/leochen/go/src/github.com/harmony-one/harmony/consensus/consensus_v2.go:56 +0x15d
github.com/harmony-one/harmony/consensus.(*Consensus).Start.func1(0xc0026bc9c0, 0xc0001602c0, 0xc000083260, 0xc0026bc960)
        /home/leochen/go/src/github.com/harmony-one/harmony/consensus/consensus_v2.go:776 +0x3fc
created by github.com/harmony-one/harmony/consensus.(*Consensus).Start
        /home/leochen/go/src/github.com/harmony-one/harmony/consensus/consensus_v2.go:702 +0x68
2019/06/03 20:35:00 Command finished with error: exit status 2

**Comment by LeoHChen** [comment]
Crash after this log.

{"ip":"54.144.172.8","lvl":"dbug","msg":"onNewView received new view message","port":"9000","t":"2019-06-03T20:35:00.138494577Z"}

**Comment by chaosma** [comment]
Crash issue is fixed by the bls check. This is due to the m1 type message view change never triggered and test before. I am working on it to make view change work in that case as well. See todo list item 2 and 3 in [877](https://github.com/harmony-one/harmony/issues/877)
