### ISSUE TITLE
[crash] concurrent map write and iteration

### ISSUE THREAD

**Issue by LeoHChen** [harmony-one/harmony#961]
Latest master branch code.

---

fatal error: concurrent map iteration and map write

goroutine 113 [running]:
runtime.throw(0xfc8d8a, 0x26)
        /home/ec2-user/.gimme/versions/go1.12.linux.amd64/src/runtime/panic.go:617 +0x72 fp=0xc007fe0e88 sp=0xc007fe0e58 pc=0x432812
runtime.mapiternext(0xc0036967e0)
        /home/ec2-user/.gimme/versions/go1.12.linux.amd64/src/runtime/map.go:860 +0x520 fp=0xc007fe0f10 sp=0xc007fe0e88 pc=0x414540
runtime.mapiterinit(0xe500a0, 0xc001d4f8f0, 0xc0036967e0)
        /home/ec2-user/.gimme/versions/go1.12.linux.amd64/src/runtime/map.go:850 +0x1c9 fp=0xc007fe0f30 sp=0xc007fe0f10 pc=0x413f29
reflect.mapiterinit(0xe500a0, 0xc001d4f8f0, 0xc000277ab2)
        /home/ec2-user/.gimme/versions/go1.12.linux.amd64/src/runtime/map.go:1343 +0x54 fp=0xc007fe0f60 sp=0xc007fe0f30 pc=0x415354
reflect.Value.MapKeys(0xe500a0, 0xc00014c6a8, 0x1b5, 0x4301, 0xe500a0, 0x2)
        /home/ec2-user/.gimme/versions/go1.12.linux.amd64/src/reflect/value.go:1138 +0xc4 fp=0xc007fe0fd8 sp=0xc007fe0f60 pc=0x491c94
github.com/fjl/memsize.(*context).scanMap(0xc007fe1de0, 0xe500a0, 0xc00014c6a8, 0x1b5, 0x9306ff)
        /home/ec2-user/go/pkg/mod/github.com/fjl/memsize@v0.0.0-20180929194037-2a09253e352a/memsize.go:226 +0x10f fp=0xc007fe1088 sp=0xc007fe0fd8 pc=0x9302bf
github.com/fjl/memsize.(*context).scanContent(0xc007fe1de0, 0xc00014c6a8, 0xe500a0, 0xc00014c6a8, 0x1b5, 0xc00014c6a8)
        /home/ec2-user/go/pkg/mod/github.com/fjl/memsize@v0.0.0-20180929194037-2a09253e352a/memsize.go:143 +0x2ad fp=0xc007fe10e0 sp=0xc007fe1088 pc=0x92f6fd
github.com/fjl/memsize.(*context).scanStruct(0xc007fe1de0, 0xc00014c690, 0xf819c0, 0xc00014c690, 0x1b9, 0xc007fe1de8)
        /home/ec2-user/go/pkg/mod/github.com/fjl/memsize@v0.0.0-20180929194037-2a09253e352a/memsize.go:183 +0x1d9 fp=0xc007fe11e8 sp=0xc007fe10e0 pc=0x92fc79
github.com/fjl/memsize.(*context).scanContent(0xc007fe1de0, 0xc00014c690, 0xf819c0, 0xc00014c690, 0x1b9, 0xe6f6e0)
        /home/ec2-user/go/pkg/mod/github.com/fjl/memsize@v0.0.0-20180929194037-2a09253e352a/memsize.go:154 +0x30f fp=0xc007fe1240 sp=0xc007fe11e8 pc=0x92f75f
github.com/fjl/memsize.(*context).scan(0xc007fe1de0, 0xc00014c690, 0xf819c0, 0xc00014c690, 0x1b9, 0x101, 0x12afe40)
        /home/ec2-user/go/pkg/mod/github.com/fjl/memsize@v0.0.0-20180929194037-2a09253e352a/memsize.go:118 +0x16f fp=0xc007fe1290 sp=0xc007fe1240 pc=0x92f3bf
github.com/fjl/memsize.(*context).scanContent(0xc007fe1de0, 0xc001d4f920, 0xf678a0, 0xc001d4f920, 0x1b6, 0xc001d4f920)
        /home/ec2-user/go/pkg/mod/github.com/fjl/memsize@v0.0.0-20180929194037-2a09253e352a/memsize.go:146 +0x202 fp=0xc007fe12e8 sp=0xc007fe1290 pc=0x92f652
github.com/fjl/memsize.(*context).scanStruct(0xc007fe1de0, 0xc001d4f920, 0xf04760, 0xc001d4f920, 0x1b9, 0xc007fe1de8)
        /home/ec2-user/go/pkg/mod/github.com/fjl/memsize@v0.0.0-20180929194037-2a09253e352a/memsize.go:183 +0x1d9 fp=0xc007fe13f0 sp=0xc007fe12e8 pc=0x92fc79
github.com/fjl/memsize.(*context).scanContent(0xc007fe1de0, 0xc001d4f920, 0xf04760, 0xc001d4f920, 0x1b9, 0xe6f6e0)
        /home/ec2-user/go/pkg/mod/github.com/fjl/memsize@v0.0.0-20180929194037-2a09253e352a/memsize.go:154 +0x30f fp=0xc007fe1448 sp=0xc007fe13f0 pc=0x92f75f
github.com/fjl/memsize.(*context).scan(0xc007fe1de0, 0xc001d4f920, 0xf04760, 0xc001d4f920, 0x1b9, 0x101, 0x12afe40)
        /home/ec2-user/go/pkg/mod/github.com/fjl/memsize@v0.0.0-20180929194037-2a09253e352a/memsize.go:118 +0x16f fp=0xc007fe1498 sp=0xc007fe1448 pc=0x92f3bf
github.com/fjl/memsize.(*context).scanContent(0xc007fe1de0, 0x0, 0xefd1a0, 0xc001d4f920, 0x36, 0x6300000000482022)
        /home/ec2-user/go/pkg/mod/github.com/fjl/memsize@v0.0.0-20180929194037-2a09253e352a/memsize.go:146 +0x202 fp=0xc007fe14f0 sp=0xc007fe1498 pc=0x92f652
github.com/fjl/memsize.(*context).scan(0xc007fe1de0, 0x0, 0xefd1a0, 0xc001d4f920, 0x36, 0x0, 0xc007fe15c0)
        /home/ec2-user/go/pkg/mod/github.com/fjl/memsize@v0.0.0-20180929194037-2a09253e352a/memsize.go:118 +0x16f fp=0xc007fe1540 sp=0xc007fe14f0 pc=0x92f3bf
github.com/fjl/memsize.(*context).scanInterface(0xc007fe1de0, 0xeb8aa0, 0xc001da82f8, 0x1b4, 0x9306ff)
        /home/ec2-user/go/pkg/mod/github.com/fjl/memsize@v0.0.0-20180929194037-2a09253e352a/memsize.go:241 +0x99 fp=0xc007fe15a8 sp=0xc007fe1540 pc=0x930579
github.com/fjl/memsize.(*context).scanContent(0xc007fe1de0, 0xc001da82f8, 0xeb8aa0, 0xc001da82f8, 0x1b4, 0xc001da82f8)
        /home/ec2-user/go/pkg/mod/github.com/fjl/memsize@v0.0.0-20180929194037-2a09253e352a/memsize.go:141 +0x139 fp=0xc007fe1600 sp=0xc007fe15a8 pc=0x92f589
github.com/fjl/memsize.(*context).scanStruct(0xc007fe1de0, 0xc001da8000, 0xf9c260, 0xc001da8000, 0x199, 0xc007fe1de8)
        /home/ec2-user/go/pkg/mod/github.com/fjl/memsize@v0.0.0-20180929194037-2a09253e352a/memsize.go:183 +0x1d9 fp=0xc007fe1708 sp=0xc007fe1600 pc=0x92fc79
github.com/fjl/memsize.(*context).scanContent(0xc007fe1de0, 0xc001da8000, 0xf9c260, 0xc001da8000, 0x199, 0xe6f6e0)
        /home/ec2-user/go/pkg/mod/github.com/fjl/memsize@v0.0.0-20180929194037-2a09253e352a/memsize.go:154 +0x30f fp=0xc007fe1760 sp=0xc007fe1708 pc=0x92f75f
github.com/fjl/memsize.(*context).scan(0xc007fe1de0, 0xc001da8000, 0xf9c260, 0xc001da8000, 0x199, 0x101, 0x12afe40)
        /home/ec2-user/go/pkg/mod/github.com/fjl/memsize@v0.0.0-20180929194037-2a09253e352a/memsize.go:118 +0x16f fp=0xc007fe17b0 sp=0xc007fe1760 pc=0x92f3bf
github.com/fjl/memsize.(*context).scanContent(0xc007fe1de0, 0x0, 0xfa0fc0, 0xc001da8000, 0x16, 0x5f00000000482022)
        /home/ec2-user/go/pkg/mod/github.com/fjl/memsize@v0.0.0-20180929194037-2a09253e352a/memsize.go:146 +0x202 fp=0xc007fe1808 sp=0xc007fe17b0 pc=0x92f652
github.com/fjl/memsize.(*context).scan(0xc007fe1de0, 0x0, 0xfa0fc0, 0xc001da8000, 0x16, 0x0, 0xc007fe18d8)
        /home/ec2-user/go/pkg/mod/github.com/fjl/memsize@v0.0.0-20180929194037-2a09253e352a/memsize.go:118 +0x16f fp=0xc007fe1858 sp=0xc007fe1808 pc=0x92f3bf
github.com/fjl/memsize.(*context).scanInterface(0xc007fe1de0, 0xecc520, 0xc0001660e0, 0x194, 0x9306ff)
        /home/ec2-user/go/pkg/mod/github.com/fjl/memsize@v0.0.0-20180929194037-2a09253e352a/memsize.go:241 +0x99 fp=0xc007fe18c0 sp=0xc007fe1858 pc=0x930579
github.com/fjl/memsize.(*context).scanContent(0xc007fe1de0, 0xc0001660e0, 0xecc520, 0xc0001660e0, 0x194, 0xc0001660e0)
        /home/ec2-user/go/pkg/mod/github.com/fjl/memsize@v0.0.0-20180929194037-2a09253e352a/memsize.go:141 +0x139 fp=0xc007fe1918 sp=0xc007fe18c0 pc=0x92f589
github.com/fjl/memsize.(*context).scanStruct(0xc007fe1de0, 0xc000166000, 0xfa2a20, 0xc000166000, 0x199, 0xc007fe1de8)
        /home/ec2-user/go/pkg/mod/github.com/fjl/memsize@v0.0.0-20180929194037-2a09253e352a/memsize.go:183 +0x1d9 fp=0xc007fe1a20 sp=0xc007fe1918 pc=0x92fc79
github.com/fjl/memsize.(*context).scanContent(0xc007fe1de0, 0xc000166000, 0xfa2a20, 0xc000166000, 0x199, 0xe6f6e0)
        /home/ec2-user/go/pkg/mod/github.com/fjl/memsize@v0.0.0-20180929194037-2a09253e352a/memsize.go:154 +0x30f fp=0xc007fe1a78 sp=0xc007fe1a20 pc=0x92f75f
github.com/fjl/memsize.(*context).scan(0xc007fe1de0, 0xc000166000, 0xfa2a20, 0xc000166000, 0x199, 0x101, 0x12afe40)
        /home/ec2-user/go/pkg/mod/github.com/fjl/memsize@v0.0.0-20180929194037-2a09253e352a/memsize.go:118 +0x16f fp=0xc007fe1ac8 sp=0xc007fe1a78 pc=0x92f3bf
github.com/fjl/memsize.(*context).scanContent(0xc007fe1de0, 0xc000055180, 0xfa2fc0, 0xc000055180, 0x196, 0xc000055180)
        /home/ec2-user/go/pkg/mod/github.com/fjl/memsize@v0.0.0-20180929194037-2a09253e352a/memsize.go:146 +0x202 fp=0xc007fe1b20 sp=0xc007fe1ac8 pc=0x92f652
github.com/fjl/memsize.(*context).scanStruct(0xc007fe1de0, 0xc000055180, 0xfa1f40, 0xc000055180, 0x199, 0xc007fe1de8)
        /home/ec2-user/go/pkg/mod/github.com/fjl/memsize@v0.0.0-20180929194037-2a09253e352a/memsize.go:183 +0x1d9 fp=0xc007fe1c28 sp=0xc007fe1b20 pc=0x92fc79
github.com/fjl/memsize.(*context).scanContent(0xc007fe1de0, 0xc000055180, 0xfa1f40, 0xc000055180, 0x199, 0xe6f6e0)
        /home/ec2-user/go/pkg/mod/github.com/fjl/memsize@v0.0.0-20180929194037-2a09253e352a/memsize.go:154 +0x30f fp=0xc007fe1c80 sp=0xc007fe1c28 pc=0x92f75f
github.com/fjl/memsize.(*context).scan(0xc007fe1de0, 0xc000055180, 0xfa1f40, 0xc000055180, 0x199, 0x101, 0x12afe40)
        /home/ec2-user/go/pkg/mod/github.com/fjl/memsize@v0.0.0-20180929194037-2a09253e352a/memsize.go:118 +0x16f fp=0xc007fe1cd0 sp=0xc007fe1c80 pc=0x92f3bf
github.com/fjl/memsize.(*context).scanContent(0xc007fe1de0, 0x0, 0xfa24a0, 0xc000055180, 0x16, 0x41274d)
        /home/ec2-user/go/pkg/mod/github.com/fjl/memsize@v0.0.0-20180929194037-2a09253e352a/memsize.go:146 +0x202 fp=0xc007fe1d28 sp=0xc007fe1cd0 pc=0x92f652
github.com/fjl/memsize.(*context).scan(0xc007fe1de0, 0x0, 0xfa24a0, 0xc000055180, 0x16, 0xc008a10400, 0x0)
        /home/ec2-user/go/pkg/mod/github.com/fjl/memsize@v0.0.0-20180929194037-2a09253e352a/memsize.go:118 +0x16f fp=0xc007fe1d78 sp=0xc007fe1d28 pc=0x92f3bf
github.com/fjl/memsize.Scan(0xfa24a0, 0xc000055180, 0x0, 0x0, 0x0, 0x0)
        /home/ec2-user/go/pkg/mod/github.com/fjl/memsize@v0.0.0-20180929194037-2a09253e352a/memsize.go:25 +0x274 fp=0xc007fe1ef8 sp=0xc007fe1d78 pc=0x92e844
github.com/harmony-one/harmony/internal/memprofiling.(*MemProfiling).PeriodicallyScanMemSize.func1()
        /data/harmony/internal/memprofiling/lib.go:77 +0x62 fp=0xc007fe1fe0 sp=0xc007fe1ef8 pc=0x96ff22
runtime.goexit()
        /home/ec2-user/.gimme/versions/go1.12.linux.amd64/src/runtime/asm_amd64.s:1337 +0x1 fp=0xc007fe1fe8 sp=0xc007fe1fe0 pc=0x45f711
created by github.com/harmony-one/harmony/internal/memprofiling.(*MemProfiling).PeriodicallyScanMemSize
        /data/harmony/internal/memprofiling/lib.go:71 +0x35

goroutine 1 [select (no cases), 134 minutes]:
github.com/harmony-one/harmony/node.(*Node).StartServer(0xc000055180)
        /data/harmony/node/node.go:257 +0x20
main.main()
        /data/harmony/cmd/harmony/main.go:425 +0x917

goroutine 6 [syscall, 134 minutes]:
os/signal.signal_recv(0x0)

**Comment by mikedoan** [comment]
fixed by https://github.com/harmony-one/harmony/pull/964/files
